### ISSUE TITLE
Make scrollback support alternative screen buffer (e.g. tmux history)

### ISSUE THREAD

**Issue by maximbaz** [jwilm/alacritty#1000]
UPDATE: I'm not sure, this might or might not be relevant for alternative screen buffers in general, not only for tmux, see https://github.com/jwilm/alacritty/pull/657#issuecomment-357005356.

----

The initial implementation of scrollback #657 does not support tmux, so when I start tmux and run `tree /` to generate a lot of output, the alacritty's scrollback will be empty.

Sakura terminal on the other hand supports tmux history, so when you have one pane, the results of scrolling via sakura and via tmux itself are identical. Sakura is based on VTE, so presumably there are other terminals that behave in the same way.

I will be using tmux after scrollback is released, some of its features (like incremental search) and plugins (such as [laktak/extrakto](https://github.com/laktak/extrakto)) are too important for me to lose, but I would really like to disable mouse support in tmux and enjoy the much smoother and pleasant scrollback provided by alacritty.

Tmux can probably also help handling reflows (window resizes) until this is implemented in alacritty.

**Comment by tbodt** [comment]
congrats on PR #1000! 🎉

**Comment by nixpulvis** [comment]
This sounds like it'll be tmux specific code. Or is the history buffer something used across programs? Not that we can't have tmux specific code, I'm just trying to understand the issue.

**Comment by maximbaz** [comment]
I hope more knowledgeable people will answer here, bug when I initially brought this question up on IRC, others were using a more generic term, if I remember correctly it was "alternative scrollback buffer". It also sounded like a not very big deal to add the support for tmux. Then there was [this comment](https://github.com/jwilm/alacritty/pull/657#issuecomment-357005356), which was later retracted, so in the end I'm personally not sure how much tmux-specific this is.

**Comment by tbodt** [comment]
tmux does not work with terminal emulator scrollback, by design. Instead it has its own scrollback, which you access with ctrl-b [ (iirc).

**Comment by maximbaz** [comment]
I used sakura terminal before (vte-based, so others probably behave similarly), and it works perfectly fine with tmux scrollback when there is only one pane. I need tmux not for panes, but for other things, and I would really enjoy the much smoother alacritty's scrollback than the one provided by tmux 🙂

**Comment by nixpulvis** [comment]
Are you sure it's not just capturing the mouse events and triggering a faux scroll?

**Comment by maximbaz** [comment]
Absolutely, it's easy to show in a gif.

Here's how the scroll works when sakura is in control of the scroll (tmux' status bottom panel is gone, behavior with second pane is weird):

![sakura-tmux-scrollback](https://user-images.githubusercontent.com/1177900/34898293-92b87ef8-f7f2-11e7-87c5-9e2a2e971c53.gif)

And here's how the scroll works when tmux is in control:

![sakura-tmux-faux-scroll](https://user-images.githubusercontent.com/1177900/34898352-ec1b583a-f7f2-11e7-98c2-e18ae2b0bd11.gif)

**Comment by maximbaz** [comment]
For completeness, this is how alacritty works when alacritty is in control of scrollback (the output of `tree` command is not available when I scroll up):

![alacritty-tmux-scrollback](https://user-images.githubusercontent.com/1177900/34898603-4ce5a50c-f7f4-11e7-8f75-1851b09fe433.gif)

I want alacritty to match the behavior with the sakura terminal on the first gif.

**Comment by chrisduerr** [comment]
Termite, which is based on a fork of VTE, does not support this.

If I understand http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer correctly, this should not exist.
