### ISSUE TITLE
pathfinder integration?

### ISSUE THREAD

**Issue by LifeIsStrange** [jwilm/alacritty#1003]
Which operating system does the issue occur on?
All.

Pathfinder is the rust gpu accelerated fonts/vectors rendering library, and will be integrated in webrender, servo and in the long term, in firefox. https://github.com/pcwalton/pathfinder

I don't know how does this interface with your gpu renderer but I bet you can at least reuse a lot of pathfinder optimisations (or even webrender optimisations).

Maybe some alacritty optimisations are reusable by pathfinder itself!

**Comment by jwilm** [comment]
dupe of #412
