### ISSUE TITLE
Problem minimize/restore window

### ISSUE THREAD

**Issue by phush0** [jwilm/alacritty#1013]
Which operating system does the issue occur on?
MacOsX 10.13.3

Alacritty HEAD version.

If you minimize (minus button) alacritty window and then restore it from dock, all window is selected as you will select with mouse. I am using it with tmux HEAD. I think it is due to that when you use mouse click in titlebar of the window it is passed to user area which is not correct.

<img width="1440" alt="screen shot 2018-01-10 at 10 07 45" src="https://user-images.githubusercontent.com/5719362/34761897-618a8aac-f5ee-11e7-8494-0dcff33baedd.png">

As you see selection is starting from bellow minimize button and finish to mouse position. Also if you use vim in alacritty and try to move alacritty window with mouse, click is passed to vim and it start to scroll up.

**Comment by jwilm** [comment]
Thanks for the report! This is the same problem as #47.
