### ISSUE TITLE
Selections don't update with faux scrolling

### ISSUE THREAD

**Issue by nixpulvis** [jwilm/alacritty#1022]
To replicate this issue run `man read` select some text, then "scroll" the man page with the arrow keys (strangely scrolling with `j` and `k` clear the selection), you'll see the selection stay in the same place despite the text moving.

After digging into the code here a bit, it seems that `event::Processor` shouldn't own the `Selection`, and instead the `Selection` should live in `Term`. This is a pretty large change, so I wanted to talk about it a bit before I started trying to hack this all together.

**Comment by jwilm** [comment]
There's going to be a lot of changes to how selections are handled with a complete scrollback implementation. This will probably be one of them. Thanks for bringing this up!

I would suggest not spending time working on a solution at this time, and instead, wait for the dust to settle on scrollback.

**Comment by nixpulvis** [comment]
Yea that's why I opened this before trying to fix things. I just thought I'd share my thoughts about "who owns the Selection" here.

**Comment by chrisduerr** [comment]
This issue is fixed in the scrollback branch, so it will be solved once it's merged. I've updated the comment in the scrollback PR to auto-close this issue.
