### ISSUE TITLE
Config file not readed if XDG_RUNTIME_DIR is not present

### ISSUE THREAD

**Issue by stkw0** [jwilm/alacritty#103]
Hi.
I copied the yml file to my home, executed alacritty and the config file was not read (as it should) but showed an error **_error: XDG_RUNTIME_DIR not set in the environment._**  Then, after running _export XDG_RUNTIME_DIR="/tmp"_ it will read my ~/.alacritty.yml . 

I don't know what was the problem, but It don't feels like it was the right behavior.

Thank you.

PD: Nice work :)

**Comment by vitiral** [comment]
I am also seeing this.
```
# uname -a
Linux localhost 4.4.39-1-lts #1 SMP Thu Dec 15 21:10:18 CET 2016 x86_64 GNU/Linux
```

**Comment by quininer** [comment]
alacritty reads `$XDG_CONFIG_HOME/alacritty.yml` first, If not found, it will generate one.
You should see a line of logs, like
``` 
Config file not found; write defaults config to "/home/quininer/.config/alacritty.yml"
error: XDG_RUNTIME_DIR not set in the environment.
```

**Comment by okuuva** [comment]
I had the same problem with the OP. Strangely enough, setting $XDG_RUNTIME_DIR changes the behavior so that ~/.alacritty.yml is preferred over ~/.config/alacritty.yml.

**Comment by chrisduerr** [comment]
I'm uncertain when this was resolved, but unsetting `XDG_RUNTIME_DIR` and starting Alacritty seems to work now. If that's not the case for anyone else, please let me know and I'll re-open.
