### ISSUE TITLE
Wayland - Use seat interface version 5

### ISSUE THREAD

**Issue by leezu** [jwilm/alacritty#1030]
Which operating system does the issue occur on?
Gentoo Linux with Wayland and Plasma 5.12 (Beta)

Currently alacritty will crash with the following error.
```
wl_registry@2: error 0: invalid version for global wl_seat (6): have 4, wanted 5 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 71, message: "Protocol error" } }', src/libcore/result.rs:906:4
```

https://github.com/Cloudef/wlc/issues/235 may contain some helpful pointers.

**Comment by aparcar** [comment]
@leezu I have the same error but don't understand what you mean with "the other way round". Could you help me out?

**Comment by chrisduerr** [comment]
Pretty sure he means that alacritty wants 5 but Plasma only supports 4. Instead of alacritty not supporting the highest version.
