### ISSUE TITLE
XOpenIM error - fcitx related

### ISSUE THREAD

**Issue by dcasella** [jwilm/alacritty#1036]
Operating system: Debian GNU/Linux testing (buster) x86_64
Using X11 and i3-gaps.
Alacritty built from source with the latest stable rustc (rustc 1.23.0 (766bd11c8 2018-01-01)).

I used to run Alacritty on startup by having `exec --no-startup-id alacritty -t ddterm -e tmux` in my i3 config.
This doesn't work anymore since https://github.com/jwilm/alacritty/commit/2b5de00241465a77b90d48b9a140e3ce5e531ff4 (see Edit 1).
I've tried changing the command to a simple `exec alacritty` and `exec --no-startup-id alacritty`: no changes.

Running `ps aux | grep alacritty` right after startup shows no results (even if in the i3 log file it's clearly stated `01/17/2018 11:46:39 PM - executing: alacritty -t ddterm -e tmux`).

Manually starting Alacritty from a terminal or drun works fine (even with `-t ddterm -e tmux` options).
Starting Alacritty with `Mod4+Return` in i3 (as you can see below in the log file, it's a binding in my i3 config) works fine as well.

Changing the command to `exec --no-startup-id alacritty -v > ~/alacritty.log` instead produces the following file:
```
Welcome to Alacritty.
Configuration loaded from /home/dcasella/.config/alacritty/alacritty.yml
```

Lines obtained from the i3 log file by running `grep i3logfile -e alacritty` (nothing useful, but it may still be worth sharing):
```
01/17/2018 11:46:39 PM - config_parser.c:parse_config:267 - CONFIG(line  28): bindsym Mod4+Return exec --no-startup-id alacritty
01/17/2018 11:46:39 PM - config_parser.c:parse_config:267 - CONFIG(line 203): exec --no-startup-id alacritty -t ddterm -e tmux
01/17/2018 11:46:39 PM - workspace.c:extract_workspace_names_from_bindings:140 - binding with command exec --no-startup-id alacritty
01/17/2018 11:46:39 PM - auto-starting alacritty -t ddterm -e tmux
01/17/2018 11:46:39 PM - executing: alacritty -t ddterm -e tmux
```

Zipped Alacritty config file:
[alacritty.zip](https://github.com/jwilm/alacritty/files/1640979/alacritty.zip)

If you need more informations plese let me know.

[Edit 1]
I can confirm Alacritty autostart on i3 worked correctly before https://github.com/jwilm/alacritty/commit/2b5de00241465a77b90d48b9a140e3ce5e531ff4:
```
$ git checkout 8aa8422
$ cargo build --release
# mv target/release/alacritty /usr/local/bin/alacritty
$ cp Alacritty.desktop ~/.local/share/applications
$ sudo reboot
```
and Alacritty shows up again.

**Comment by ookhoi** [comment]
Maybe try `exec --no-startup-id alacritty -v &> ~/alacritty.log` (`&>` instead of `>`) to catch stderr?

**Comment by dcasella** [comment]
Whoops you're right, I might've forgotten how to pipe.

Anyway, `exec --no-startup-id alacritty -v &> ~/alacritty.log` creates an empty file.

**Comment by ookhoi** [comment]
Empty file is unexpected. Maybe the `&` gets interpreted.

You can also try `exec --no-startup-id alacritty -v > ~/alacritty.log 2> ~/alacritty.err`

**Comment by dcasella** [comment]
> Empty file is unexpected. Maybe the `&` gets interpreted.

Yep, it does.

stderr with backtrace:
```
thread 'main' panicked at 'XOpenIM failed', /home/dcasella/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:907:16
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: winit::window::<impl winit::WindowBuilder>::build
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/x11/mod.rs:907
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/platform/linux/mod.rs:120
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.10.0/src/window.rs:119
   5: glutin::platform::platform::x11::Context::new
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.12.0/src/platform/linux/x11.rs:207
   6: alacritty::display::Display::new
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.12.0/src/platform/linux/mod.rs:58
             at src/display.rs:140
   7: alacritty::run
             at src/main.rs:104
   8: alacritty::main
             at src/main.rs:62
   9: main
  10: __libc_start_main
  11: _start
```

**Comment by dcasella** [comment]
`sudo apt purge fcitx*` resolves the issue.
