### ISSUE TITLE
The problem with the displayed font

### ISSUE THREAD

**Issue by Mauladen** [jwilm/alacritty#1042]
I use a Font Nerd Hack, the problem lies in the distance between the characters, I tried to edit the config and put different values on the X-axis, but it looks ugly because the distance between some of the characters still differ

![Image](https://i.imgur.com/C9EfWQ7.png)

**Comment by rkanati** [comment]
Can we see your config? That doesn't actually look like Hack.

**Comment by Mauladen** [comment]
The issue with the spacing of the characters I chose, but you can now see how the Russian characters began to stick together

![Image](https://i.imgur.com/MJquhLw.png)

Here is a link to my [config](https://pastebin.com/xQifGgfV)

**Comment by chrisduerr** [comment]
Looks like the width of the fallback font is just too big. Hack probably doesn't include those russian characters and that's why it's messed up.

**Comment by jwilm** [comment]
This looks like a config issue. In the first screenshot, you appear to be using a non-monospace font. The second screenshot may be an issue with either the fallback font size or Alacritty computing the unicode width of the Russian characters. Can you please post the string of Russian characters you entered?

**Comment by Mauladen** [comment]
The problem is only if I use Hack Bold, the problem is solved if you just use a configuration Hack for Bold and Italic

фщы - Maybe even have characters that can cause problems, x offset and I have not helped so the configuration looks like this

![Image](https://i.imgur.com/sR1fk5n.png)

P.S. Project Nerd just uses a different name for the font Hack after adding symbols
