### ISSUE TITLE
Too wide, spaced out fonts when running under i3

### ISSUE THREAD

**Issue by anxiousmodernman** [jwilm/alacritty#1044]
Which operating system does the issue occur on?
Arch

If on linux, are you using X11 or Wayland?
X11

Full disclosure: I am brand new to i3, but I've been using alacritty for a while on Arch.

My alacritty config is default, and my i3 config is nearly default. I only changed it to launch alacritty via `/home/<me>/.cargo/bin/alacritty`.

Please see screenshot. Is there a configuration to make this better? Is this a symptom of a system-level font config?

![img_20180120_181942](https://user-images.githubusercontent.com/396004/35190450-e94ddc70-fe16-11e7-86bf-02ed884c9487.jpg)

**Comment by maximbaz** [comment]
See #1029.

**Comment by anxiousmodernman** [comment]
As mentioned in the linked PR, this seems to be a system-level font config problem. I'll re-open if installing an appropriate font doesn't fix this.
