### ISSUE TITLE
MacOS `open` command and potentially other things not launching right

### ISSUE THREAD

**Issue by zacstewart** [jwilm/alacritty#1046]
I'm on MacOS 10.13.2 (17C88) High Sierra.

Using the MacOS `open` utility does not work as expected when using Alacritty, but works fine in other terminal emulators. I suspect this may be a somewhat recent regression because I just upgraded, and I use `open` so frequently that I feel like I would have noticed it if it was not working before.

The behavior is a little hard to explain, but it seems like it's not forking and detatching from the process right or something. If I `open .` to open the current dir in Finder, I get the following error:

```
~/Code/zacstewart/comm-rs $ open .
LSOpenURLsWithRole() failed with error -600 for the file /Users/zacstewart/Code/zacstewart/comm-rs.
```

But if I try to open a markdown file  (which should open with Marked), it works kinda. It launches Marked, but then blocks until Marked quits.

The potential "other things" that I mention is that a GTK-based GUI app I'm working on in Rust launches just fine from other emulators by running `cargo run`. But in Alacritty, it launches, but Alacritty stubbornly remains "in front" of it. I can exposé the windows, grab the GTK app, and it briefly flashes to the front, but Alacritty quickly jumps back in front. If I move them side-by-side, I still can't interact with the GTK app by either keyboard or mouse.

Thanks a ton for all the great work on Alacritty. I love the simplicity and performance!

**Comment by chrisduerr** [comment]
Could you bisect the commit which broke this?

**Comment by sandersantema** [comment]
I tried the open command on mac os 10.12.6. and the latest version of Alacritty. It works completely as expected so this problem might have something to do with mac os 10.13.2.

**Comment by zacstewart** [comment]
Seems like this had something to do with tmux. After quitting all tmux sessions and starting a new one, it works.
