### ISSUE TITLE
How to bind cmd-K to clear

### ISSUE THREAD

**Issue by snoblenet** [jwilm/alacritty#1047]
Which operating system does the issue occur on? Latest Mac OS X; latest Alacritty; latest Rust

Why is this not working? Thanks
```
 - { key: K,        mods: Command, command: { program: "/usr/bin/clear" } }
```

**Comment by falood** [comment]
@snoblenet this works well for me, hope it's helpful.
```
- { key: K, mods: Command, chars: "\x08K" }
```

**Comment by snoblenet** [comment]
hmmm... thanks @falood but this does not work for me on latest Mac OS/Zsh/Tmux/Alacritty

**Comment by snoblenet** [comment]
hmmm... thanks @chrisduerr but this does not work for me on latest Mac OS/Zsh/Tmux/Alacritty

**Comment by snoblenet** [comment]
As an alternative, I could send the Tmux prefix (`<CTRL-A>` in my case) followed by `-R`?

(It seems Tmux offers a `clear-history` command, which would be easy to map in `alacritty.yml`, but only a keyboard shortcut for clearing the screen.)

**Comment by snoblenet** [comment]
Hey @falood -- where did you find the keycode "\x08K" for "ctrl-k"?

**Comment by falood** [comment]
Hi @snoblenet 
I just checked my config file, I also have such for my tmux, the `\x08` means `C-h`.

```
set -g prefix C-h
unbind K
bind K send-keys -R \; send-keys C-l \; clear-history
```

so alacritty send`C-h K` to tmux, and tmux bind it to the clean command.

**Comment by falood** [comment]
and the [Key Codes](https://manytricks.com/keycodes/) app help me a lot to edit the config file.
when I press `C-h` I get this, so I know it's `\x08`
![image](https://user-images.githubusercontent.com/184053/35675514-3cb2a768-0783-11e8-9bdb-ecc5d4fa1838.png)

hope it's helpful for you 🙂

**Comment by snoblenet** [comment]
Thanks @falood. I had been using Key Codes but I hadn't been able to find a reference that explains how to go from the Unicode value in Key Codes (e.g. `8 / 0x8` in your example) to the equivalent for `alacritty.yml` (e.g. `\x08`).

Without a reference, I decided to do a straight substitute -- i.e. any instance of `* / 0x` becomes `\x0`. It worked :-) -- wish I could find an explanation of why though.

I now have:

`tmux.conf`: `bind -n C-k send-keys -R`, so I can clear the screen without a prefix.

`alacritty.yml`: ` - { key: K, mods: Command, chars: "\x0b" }` (etc), so everything still works if I reflexively use Mac-standard system shortcuts.
