### ISSUE TITLE
Vertically center text in line

### ISSUE THREAD

**Issue by net** [jwilm/alacritty#105]
There's not enough padding between the baseline and the bottom of the line. Here's how it looks right now:

<img width="311" alt="screen_shot_2017-01-06_at_4_31_40_pm" src="https://cloud.githubusercontent.com/assets/6983821/21733687/d1a585aa-d42d-11e6-8a25-310cc24beb44.png">

Here's how it should look:

<img width="123" alt="screen shot 2017-01-06 at 4 33 57 pm" src="https://cloud.githubusercontent.com/assets/6983821/21733731/023c12c4-d42e-11e6-94c0-5539fba46197.png">

Ideally this would be customizable.

**Comment by jwilm** [comment]
I commented on this [in another issue](https://github.com/jwilm/alacritty/issues/174#issuecomment-271130883) with an alternative solution. Feedback welcome :)

**Comment by jwilm** [comment]
We've reworked how we consume font metrics, and text now appears at a sensible location within the line.
