### ISSUE TITLE
Close/Crash on Startup

### ISSUE THREAD

**Issue by erkolson** [jwilm/alacritty#1056]
Which operating system does the issue occur on?
OS X 10.12.6

I installed according to the README and am seeing Alacritty close immediately on startup.  I see this in the system log:
```
com.apple.xpc.launchd[1] (io.alacritty.120860[1579]): Service exited with abnormal code: 1
```
I have made no changes to `alacritty.yml`, just copied it into `~/.alacritty.yml`

**Comment by mjburling** [comment]
I believe if you've only copied the alacritty.yml without changes, you're going to have a bad time.

From the alacritty.yml, lines 64, 70, and 76:
>     family: monospace # should be "Menlo" or something on macOS.

Also helpful, but workflow dependent, you may end up changing lines 287 and beyond to `Command` instead of `Control|Shift` or similar:
>  - { key: V,        mods: Control|Shift,    action: Paste               }
>  - { key: C,        mods: Control|Shift,    action: Copy                }

**Comment by chrisduerr** [comment]
It's recommended to use the `alacritty_macos.yml` as a basis on macos. There you will not have to replace the shortcuts.

**Comment by sandersantema** [comment]
Shouldn't alacritty.yml be in ~/.config/alacritty/alacritty.yml instead of the home directory @erkolson ?

**Comment by erkolson** [comment]
@mjburling Indeed, that was my problem.  I hadn't noticed the `alacritty_macos.yml` file.  I was following the README and it wasn't mentioned.

@sandersantema The README says the configuration can be in any of these places:
1. `$XDG_CONFIG_HOME/alacritty/alacritty.yml`
2. `$XDG_CONFIG_HOME/alacritty.yml`
3. `$HOME/.config/alacritty/alacritty.yml`
4. `$HOME/.alacritty.yml`
