### ISSUE TITLE
MacOS ls columns not aligned

### ISSUE THREAD

**Issue by samdphillips** [jwilm/alacritty#106]
When running `ls` in an alacritty window on MacOS the columns are not aligned.  If I use the same window and ssh to a Linux system the columns are aligned.

Alacritty vs. iTerm2 (same directory)
![Alacritty vs. iTerm2](https://cloud.githubusercontent.com/assets/433662/21733750/f7482a2e-d414-11e6-8005-9989d0d6fb24.png)

Remote Linux system in Alacritty
![Linux system in Alacritty](https://cloud.githubusercontent.com/assets/433662/21733754/fbfbc0a8-d414-11e6-9a66-cbc7e56c6d11.png)

**Comment by samdphillips** [comment]
Looks like it has something to do with how tab is being rendered:
![screen shot 2017-01-06 at 2 02 42 pm](https://cloud.githubusercontent.com/assets/433662/21734590/03ce4fae-d419-11e6-9eb5-7c2c55598768.png)

**Comment by puneetloya** [comment]
+1 on this. Had the same issue.

**Comment by jwilm** [comment]
This has been resolved for some time.
