### ISSUE TITLE
Weird rendering of ncurses based app like Kakoune text editor

### ISSUE THREAD

**Issue by vbauerster** [jwilm/alacritty#1060]
Which operating system does the issue occur on?
macOS 10.13.3 (17D47)

[Kakoune](https://github.com/mawww/kakoune) text editor outputs nasty characters, while rendering any pseudo graphic windows. As far as I know it is based on the ncurses lib. Is this problem on the Kakoune side or alacritty?

**alacritty**
[![cmd_bad.png](https://s25.postimg.org/hyl2l2dkf/cmd_bad.png)](https://postimg.org/image/mkh6tez3f/)

**iterm2**
[![cmd_good.png](https://s25.postimg.org/wujlsn9jj/cmd_good.png)](https://postimg.org/image/wujlsn9jf/)

**alacritty**
[![goto_bad.png](https://s25.postimg.org/mkh6terdr/goto_bad.png)](https://postimg.org/image/v2qmxqxwb/)

**iterm2**
[![goto_good.png](https://s25.postimg.org/5jyakpywv/goto_good.png)](https://postimg.org/image/k35fm4s1n/)

**Comment by vbauerster** [comment]
@mawww Can you comment please?

**Comment by chrisduerr** [comment]
Alacritty is not 100% vttest compliant yet, so it's very possible that there are some special escape sequences Kakoune uses which are not supported yet.

**Comment by jwilm** [comment]
@vbauerster would you mind making a recording of this with `script`? It will generate a file called `typescript` which would be helpful for debugging this problem. Please make sure there is no sensitive data displayed while running `script`.

**Comment by vbauerster** [comment]
Here you are [typescript](https://goo.gl/ZBTgUX) archive.

**Comment by sandersantema** [comment]
Using Mac OS 10.12.6 and the latest version of Alacritty: 

![schermafbeelding 2018-01-29 om 20 45 38](https://user-images.githubusercontent.com/21057514/35530805-68ecd47a-0535-11e8-9ea9-cc30b95772b1.png)
It seems to render correctly, so it might not be Alacritty. 
Things which might cause this which I can think of:
1. Using system Ncurses, I believe iTerm does something different with paths. 
2. Something to do with font rendering, incompatibilities of the font with Alacritty.

**Comment by mawww** [comment]
It might be as well that your configuration with Alacritty does not set an UTF-8 locale while your configuration with iterm2 does.

**Comment by vbauerster** [comment]
@jwilm just in case, how do I check/set UTF-8 settings?

**Comment by vbauerster** [comment]
Well indeed setting following in config, have fixed this.
```yaml
env:
  LANG: en_US.UTF-8
  LC_CTYPE: UTF-8
```
I assumed that alacritty suppose to inherit system env settings. Anyway this issue could be closed now, thank you all for support!
