### ISSUE TITLE
mac alt modifier broken

### ISSUE THREAD

**Issue by monouser7dig** [jwilm/alacritty#1085]
macOS 10.13.3

holding `alt + / => |` or `alt + n => ~` does somehow not work for me anymore

**Comment by monouser7dig** [comment]
**seems to be an issue with german keyboard layout**, never noticed it on my US keyboard and if I switch the german one in software it works (like on a normal US keyboard)

can this mapping be added or maybe alt is just not supported?

**Comment by jwilm** [comment]
There's an outstanding bug in winit to properly support non-US-QWERTY layouts. The bug is basically that the keymap is applied for _received characters_, but not for _key codes_. I believe this is a duplicate of #458.
