### ISSUE TITLE
Provided binary build somewhere.

### ISSUE THREAD

**Issue by pauldotknopf** [jwilm/alacritty#1090]
Maybe you can occasionally create some GitHub release?

I am on Arch, and ```alacritty-git``` has many large dependencies and takes ~5 minutes to compile, all for a single ~5MiB file.

**Comment by pauldotknopf** [comment]
Maybe we can statically link in musl to make it super portable?

**Comment by RealOrangeOne** [comment]
Looks like a duplicate of https://github.com/jwilm/alacritty/issues/927. [This comment](https://github.com/jwilm/alacritty/issues/927#issuecomment-348594235) may be of interest
