### ISSUE TITLE
Workaround until pasting is fixed

### ISSUE THREAD

**Issue by ghost** [jwilm/alacritty#1094]
I've noticed a few open issues related to pasting, and some things are strange for me as well, so until that's fixed I've come up with a workaround involving tmux.

A recent (1 month ago) version of tmux is necessary since the functionality of this to work properly was only just added: https://github.com/tmux/tmux/commit/5849b73b81c1218e57e9931c44e82f0d7c468cb1

My solution is to create a key binding in my `.tmux.conf` that pastes from xclip:
```
#hack fix alacritty pasting
bind -n C-v pipe-pane -I "xclip -o -selection clipboard"
```

~~I can't bind the default C-shift-v key because tmux doesn't support that, and terminal emulators don't really either I guess. :P~~ You can bind actions in .alacritty.yml! I'm open to suggestions on how to make this work.

This seems to work pretty well. Caveat emptor?

**Comment by 22459** [comment]
I can't remember which issues to reference though.

**Comment by chrisduerr** [comment]
I don't quite see the origin of this issue and it should be possible to automate it with the Alacritty config. So since the user has been deleted, I'm closing this issue.
