### ISSUE TITLE
Pressing the global hotkey for 1password causes a 'c' to appear in Alacritty

### ISSUE THREAD

**Issue by Strayer** [jwilm/alacritty#1097]
I don't think this is specific to 1password, but that hotkey is the only one where I experience issues.

Pressing `Alt + Cmd + \` opens the global 1password overlay. I use this frequently to copy server passwords for SSH/sudo. Pressing this key combination in Alacritty causes a `c` to appear in the terminal, obviously messing with a paste in hidden inputs like sudo.

Alacritty rev 2466f81d, macOS 10.13.3

**Comment by hansottowirtz** [comment]
I don't have this problem, has it been fixed?

**Comment by chrisduerr** [comment]
There have been some changes to winit/glutin since this issue was opened. Can you still reproduce this @Strayer?
