### ISSUE TITLE
Tmux and Nvim not found - even though they are installed

### ISSUE THREAD

**Issue by vladovidiu** [jwilm/alacritty#1098]
Which operating system does the issue occur on?
macOS High Sierra - latest updates

As per screenshot
<img width="243" alt="screen shot 2018-02-06 at 09 12 29" src="https://user-images.githubusercontent.com/3762924/35850827-ff97aa10-0b1d-11e8-985b-1aa9ec3b63a4.png">

If I use the Terminal.app or iTerm, those apps work fine. Is it a zsh issue?

**Comment by chrisduerr** [comment]
This is probably an issue with your `$PATH` variable. Make sure the applications you want to run are actually part of your `$PATH`.

**Comment by sodiumjoe** [comment]
@vladovidiu it's also likely to be https://github.com/jwilm/alacritty/issues/645#issuecomment-313485707

**Comment by chrisduerr** [comment]
This is likely to be the issue, thanks for pointing that out. Closing as duplicate, please reopen if it is a different problem.
