### ISSUE TITLE
Alacritty hangs in a loop consuming all memory when font.offset.x is too low

### ISSUE THREAD

**Issue by thugcee** [jwilm/alacritty#1104]
OS: Linux/X11 (Ubuntu 16.04)
Version: git master/cc87390edee9d28d9e7456c6ac0cf3a6b7a096c2

For my previous version of Alacritty I have configured `font.offset.x = -12` to get a nice looking UbuntuMono Nerd Font. The current version doesn't like it. Changing value to '-5' or more solves the problem, but eating all available memory is not a good behaviour for any app.

**Comment by chrisduerr** [comment]
This has been fixed a while ago.
