### ISSUE TITLE
Git pretty format white color is displayed as grey

### ISSUE THREAD

**Issue by pmalek** [jwilm/alacritty#1109]
Which operating system does the issue occur on? Ubuntu 14.04

If on linux, are you using X11 or Wayland? X11

when using the following `git` command:

    git log --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim blue)- %an%C(reset)'

I get:

![image](https://user-images.githubusercontent.com/739996/36061434-76948e1e-0e5a-11e8-9c0b-b7c8c7a21889.png)

when I change it to:

    git log --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(reset)%s%C(reset) %C(dim blue)- %an%C(reset)'

![image](https://user-images.githubusercontent.com/739996/36061440-8512a796-0e5a-11e8-8f10-5d048be0ac72.png)

The difference in commands is that when commit message is displayed greyed out I use `white` as color format. When it's properly displayed as white I use `reset` color.

I use alacritty `cc87390` with 

```
rustc -V
rustc 1.23.0 (766bd11c8 2018-01-01)
```

**Comment by pmalek** [comment]
I use default config - the one from the repo

**Comment by chrisduerr** [comment]
White and foreground are two different colors in the default config.

**Comment by pmalek** [comment]
Ok, well it seems I have forgotten about my config in home directory...
It's all perfectly fine after I have merged those 2.

Thanks a lot for support and keep up the good work : )
