### ISSUE TITLE
Cursor "fell off grid" when resizing window

### ISSUE THREAD

**Issue by sliceofcode** [jwilm/alacritty#111]
I can reliably make Alacritty crash when resizing the window while NeoVim is open:

```
...
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
width: 1022, height: 748
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
num_cols, num_lines = 127, 33
width: 1022, height: 747
thread 'pty reader' panicked at 'cursor fell off grid', src/term/mod.rs:634
note: Run with `RUST_BACKTRACE=1` for a backtrace.
child finished with error '256'
```

I noticed that this problem does not occur with normal Vim. However, this problem does not occur when using NeoVim in `st`, so I think it's a problem with Alacritty.

**Comment by jwilm** [comment]
Thanks for the report! This is a duplicate of #12, but I'll leave it open to make sure this specific case gets a regression test.

**Comment by sliceofcode** [comment]
Hmmm... This is interesting. I just `git pull`ed and built. Some commit in `3c57c03..8d8fca6` fixed the problem for me.

**Comment by sliceofcode** [comment]
However, I don't think #12 is fixed. I can still make it crash by opening `tmux`, resizing down to a tiny size, then exiting `tmux`.
