### ISSUE TITLE
No window decorations in openbox after update

### ISSUE THREAD

**Issue by Iambecomeroot** [jwilm/alacritty#1111]
Ever since a resent system update, Alacritty does not have window decorations. Even if I press Alt+Space to get the openbox window menu and I click "Un/Decorate", there are still no decorations.

Which operating system does the issue occur on?
`uname -a`:
```
Linux Zeus 4.15.2-2-ARCH #1 SMP PREEMPT Thu Feb 8 18:54:52 UTC 2018 x86_64 GNU/Linux
```

If on linux, are you using X11 or Wayland?
X11

`alacritty -V`:
```
alacritty 0.1.0
```

**Comment by ZSBI-Informatycy** [comment]
X11.
`uname -a`:
```
Linux manjaro 4.14.24-1-MANJARO #1 SMP PREEMPT Sun Mar 4 21:28:02 UTC 2018 x86_64 GNU/Linux
```
XFCE4. 
No decorations after last alacritty update.

`alacritty -V`: `alacritty 0.1.0`

Decorations still set to true in the config.

**Comment by Iambecomeroot** [comment]
I think it was a problem with my config. I did a `git reset --hard HEAD` in my dotfiles (so unfortunately I don't know what the problem was) and now everything is fine.
