### ISSUE TITLE
Support drop down windows similar to Guake and iTerm

### ISSUE THREAD

**Issue by behrangsa** [jwilm/alacritty#1119]
![Drop Down Terminal](https://user-images.githubusercontent.com/18451/36287326-45e1db48-1308-11e8-949b-6e9cb7f1bbd7.png)

**Comment by lord-re** [comment]
This feature should be implemented by your windows manager not the terminal itself.

**Comment by chrisduerr** [comment]
I don't think making it a full drop-down terminal like guake is within the scope of the project.

However if #450 is implemented it should be possible to create a different frontend for alacritty that would make this possible.

**Comment by leiserfg** [comment]
https://github.com/noctuid/tdrop

**Comment by nixpulvis** [comment]
@leiserfg very cool, though I'm guessing this won't help OP as he looks to be on macOS.

**Comment by ideologysec** [comment]
@lord-re not all of us have a choice of window manager, unfortunately. There's no way for a macOS application to tell the window manager "make me a Visor."

**Comment by fdcds** [comment]
Can we please include "quake-style terminal" in the issue title to ease finding it in search?

**Comment by kchibisov** [comment]
@fdcds This feature is called `drop down` terminal, so the title is pretty clear imho.

**Comment by fdcds** [comment]
[Different people](https://en.wikipedia.org/wiki/Quake-style_console) call it by [different names](https://en.wikipedia.org/wiki/Drop_down_terminal).

**Comment by AlexCzar** [comment]
Assuming tabbed is installed and you have all the necessary tools (xdotool, wmctrl, xprop), this script will [mostly] achieve behaviour similar to yakuake (guake, etc...) with tabs.
https://gist.github.com/AlexCzar/0c2cea33f88f41473773f1a78e5ef63a

**Comment by edwinclement08** [comment]
I hacked up a script that can help anyone using a Linux system under X11.

https://blog.edwinclement08.com/post/want-any-window-to-work-like-guake-appearing-and-disappearing-with-a-hotkey-use-this-script/

**Comment by tcstory** [comment]
you can use https://extensions.gnome.org/extension/1411/quake-mode/ , it works on gnome 40.x alone with wayland

**Comment by cocoonkid** [comment]
This  works for mac: https://world.hey.com/jonash/alacritty-drop-down-guake-quake-style-terminal-setup-on-macos-6eef7d73

**Comment by pabloab** [comment]
Wayland does not allow applications registering global shortcuts/hotkeys (security reasons, control a not focussed app). The only apps working are the old ones running over xwayland.

1. Install Alacritty (`sudo apt install alacritty` on Pop Jammy)
1. Install [Quake mode](https://extensions.gnome.org/extension/1411/quake-mode/)
  ![image](https://user-images.githubusercontent.com/657836/189228206-8a632a63-0315-40b6-8d27-b11ed9cf0be5.png)
1. Change shortcut
  ![image](https://user-images.githubusercontent.com/657836/189228374-83863ee5-261f-4b42-867d-01fa7e94bafc.png)

**Comment by EdgardoArriagada** [comment]
> This works for mac: https://world.hey.com/jonash/alacritty-drop-down-guake-quake-style-terminal-setup-on-macos-6eef7d73

Thanks!

I've followed the guide but made small changes to make it work with `hs.spaces` instead of the no longer maintained `hs._asm.undocumented.spaces` plus some refactors

My source code here [here](https://github.com/EdgardoArriagada/dotFiles/tree/main/hammerspoon/.hammerspoon) (notice the hammerspoon ignored files at the root of the repo)

**Comment by Vatson112** [comment]
For Gnome 45 use can use [this extension](https://extensions.gnome.org/extension/6307/quake-terminal/)

**Comment by zhangyufei49** [comment]
I made this by [HammerSpoon](https://www.hammerspoon.org/) on MacOS.
This is my HammerSpoon config:

1. Install the Spoon [WindowHalfsAndThirds](https://www.hammerspoon.org/Spoons/WindowHalfsAndThirds.html) for window arangement
2. Create file **$HOME/.hammerspoon/terminal.lua** with content:
```lua
local last_window = nil

hs.loadSpoon('WindowHalfsAndThirds')
local window_manager = spoon.WindowHalfsAndThirds

local function get_application(terminal_name)
    local app = hs.application.get(terminal_name)
    local is_new = false

    if app == nil then
        app = hs.application.open(terminal_name)
        last_window = app:mainWindow()
        is_new = true
    end
    local windows = app:allWindows()
    if last_window == nil or (not hs.fnutils.contains(windows, last_window)) then
        last_window = windows[1]
        is_new = true
    end

    return app, last_window, is_new
end

local function toggle_terminal(terminal_name, size)
    local app, win, is_new = get_application(terminal_name)
    if is_new then
        window_manager[size](window_manager, win)
    end
    -- 判定是否需要隐藏
    if is_new or (hs.window.focusedWindow() ~= win) then
        win:focus()
    else
        if #app:allWindows() == 1 then
            app:hide()
        else
            win:sendToBack()
        end
    end
end

local function setup(mods, key, size, teriminal_name)
    if size == nil then
        size = 'topTwoThird'
    end
    if teriminal_name == nil then
        teriminal_name = 'org.alacritty'
    end

    hs.hotkey.bind(mods, key, hs.fnutils.partial(toggle_terminal, teriminal_name, size))
end

return setup

```
3. Setup up it in **$HOME/.hammerspoon/init.lua**:
```lua
-- use cmd + ctrl + t to toggle alacritty at top two third of the screen
-- the third param can pass 'topHalf' to open alacritty at top half of the screen
require('terminal')({ 'cmd', 'ctrl' }, 't')
```
4. Reload hammerspoon config

**Comment by moqsien** [comment]
A simple dropdown approach with **Hammerspoon** on **MacOS**:



```lua
-- put content below in ~/.hammerspoon/init.lua
hs.hotkey.bind({"ctrl", "cmd"}, "t", function()
    local alacritty = hs.application.get("Alacritty")
    if alacritty == nil then
        hs.application.launchOrFocus("/Applications/Alacritty.app")
    else
        if alacritty:isHidden() then
            hs.application.launchOrFocus("/Applications/Alacritty.app")
            
        else
            alacritty:hide()
        end
    end
end)
```

**Comment by enpinzolas** [comment]
> Under Wayland, what are the recommended solutions for dropdown terminal use ? tdrop ?

There are some solutions on hyperland, but I'm a KDE user so I had to do something using window rules. The reason tdrop doesn't work in wayland is that it lacks the utility used for window management, xdotool. In KDE however, there exists an actual replacement called kdotool so we can do something with it. I based my solution on this gist: https://gitlab.com/-/snippets/4798512

The idea is to create a down rule that forces the window to stay in the position you want, and to create a script using kdotool to execute the terminal if it's not running, and minimize/show it if it's running. I created a gist that might be helpful: https://gist.github.com/enpinzolas/7a32ca2765a69f4d96e81eef711f78bc

**Comment by james-six-flags** [comment]
Missed this functionality too much... If you're a mac user, this works for me:

This is my `~/.hammerspoon/init.lua`, if I wasn't at work, I'd make a spoon for this, I might later. 

```
local alacritty_app_path = "/Applications/Alacritty.app"
local alacritty_app_name = "Alacritty"
local alacritty_resize_step = 100
local state_file = os.getenv("HOME") .. "/.alacritty_height"
local cached_frame = nil

-- Save height to disk
local function saveHeight(height)
    local f = io.open(state_file, "w")
    if f then
        f:write(tostring(height))
        f:close()
    end
end

-- Load height from disk
local function loadHeight()
    local f = io.open(state_file, "r")
    if f then
        local h = tonumber(f:read("*a"))
        f:close()
        return h
    end
    return 500
end

-- Resize height
local function resizeAlacritty(delta)
    local app = hs.application.get(alacritty_app_name)
    if not app then return end
    local win = app:mainWindow()
    if not win then return end

    local f = win:frame()
    f.h = math.max(100, f.h + delta)
    win:setFrame(f)
    saveHeight(f.h)
    cached_frame = f
end

-- Show Alacritty on active screen
local function slideDownAlacritty()
    hs.task.new("/usr/bin/open", nil, { "-g", alacritty_app_path }):start()

    hs.timer.doAfter(0.25, function()
        local app = hs.application.get(alacritty_app_name)
        if not app then return end

        local win = app:mainWindow()
        if not win then return end

        local screen = hs.mouse.getCurrentScreen()
        local screen_frame = screen:frame()
        local term_height = loadHeight()

        cached_frame = {
            x = screen_frame.x,
            y = screen_frame.y - term_height,
            w = screen_frame.w,
            h = term_height,
        }

        win:setFrame(cached_frame)
        win:setAlpha(0)
        win:unminimize()

        hs.timer.doAfter(0.1, function()
            app:unhide()
            win:setAlpha(1)
            win:setFrame({
                x = screen_frame.x,
                y = screen_frame.y,
                w = screen_frame.w,
                h = term_height,
            })
            app:activate()
        end)
    end)
end

-- Hide Alacritty smoothly
local function slideUpAlacritty()
    local app = hs.application.get(alacritty_app_name)
    if not app then return end
    local win = app:mainWindow()
    if not win then return end
    local f = win:frame()
    f.y = f.y - f.h
    win:setFrame(f)
    app:hide()
end

-- Toggle
local function toggleAlacritty()
    local app = hs.application.get(alacritty_app_name)
    if app and app:isFrontmost() then
        slideUpAlacritty()
    else
        slideDownAlacritty()
    end
end

-- Hotkeys
hs.hotkey.bind({"ctrl", "alt"}, "-", function() resizeAlacritty(-alacritty_resize_step) end)
hs.hotkey.bind({"ctrl", "alt"}, "=", function() resizeAlacritty(alacritty_resize_step) end)
hs.hotkey.bind({"cmd"}, "space", toggleAlacritty)
```

Just remember to change your hotkeys, I didnt bother with much of an animation, if you wanna smooth it out, be my guest but this should give you the guake-style feel.
