### ISSUE TITLE
Flag to set window position on screen

### ISSUE THREAD

**Issue by severen** [jwilm/alacritty#1124]
Seeing as Alacritty already has a flag for setting the dimensions of the window, adding a flag for setting its *location* on screen would also be fitting.

My use case for this is writing a script like this [one](https://github.com/f0x52/dots/blob/master/bin/bin/select_st) ([video](https://www.reddit.com/r/unixporn/comments/7snf2z/bspwm_drawing_terminals/)).

**Comment by ishanjain28** [comment]
Hi, I would like to work on this issue.

**Comment by cole-h** [comment]
https://github.com/jwilm/alacritty/pull/2163 implementing this feature landed on master earlier today.
