### ISSUE TITLE
Duplicate Dracula color schemes in alacritty wiki

### ISSUE THREAD

**Issue by anbenson** [jwilm/alacritty#1128]
Not a user of Dracula, but I noticed that the wiki shows two slightly different color schemes labeled as Dracula and linking to the Dracula theme website: https://github.com/jwilm/alacritty/wiki/Color-schemes

I don't know much about Dracula, but I assume it isn't intentional to have duplicate Dracula color schemes in the wiki that are different.

**Comment by alfunx** [comment]
According to the [Xresources file](https://github.com/dracula/xresources) provided by the dracula colorscheme [the first one](https://github.com/jwilm/alacritty/wiki/Color-schemes#dracula) is the correct one.

Also you can see that [the second one](https://github.com/jwilm/alacritty/wiki/Color-schemes#dracula-1) uses, for some colors (e.g. red), the same color for normal and bright variant.

**Comment by chrisduerr** [comment]
I've removed the duplicate colorscheme because I don't think having it twice will do any good.

If this might be a variation it seems like a good idea to add it again with a different name, like `Dracula - iTerm` or something like that.
