### ISSUE TITLE
Performance Issue with Alacritty in Vim/NeoVim

### ISSUE THREAD

**Issue by omaryoussef** [jwilm/alacritty#1129]
Which operating system does the issue occur on?
**macOS High Sierra 10.13.3**

I can't for the life of me figure out why Alacritty is so slow for me, the speed is on par with iTerm 2 at this point. I followed the instructions to compile it from the readme to the letter and have tried multiple different Macs with different macOS versions (Sierra and High Sierra). 

From existing issues, background color being different from the terminal color and using Tmux affects performance. I installed a completely vanilla NeoVim with zero configuration (Via HomeBrew) without Tmux and it's still slow.

Here's a GIF of this in action: https://imgur.com/a/9rRmO
Compare it with this: https://www.youtube.com/watch?v=vlmDm9REV2I

I've also attached my [alacritty.yml](https://github.com/jwilm/alacritty/files/1759435/alacritty.txt). (I'm using the 'Snazzy' theme)

Is there something terribly simple I'm missing, what am I doing wrong?

**Comment by jwilm** [comment]
It looks like your key repeat rate is low. Have you tried changing it?

**Comment by omaryoussef** [comment]
OMG that worked! I know it was something so simple! Yes that was the issue! Thank you and I'm so sorry for wasting your time!
