### ISSUE TITLE
Only functions when given root privileges, GL Context Error 

### ISSUE THREAD

**Issue by alex-eyre** [jwilm/alacritty#1132]
**Which operating system does the issue occur on?**
Gentoo Linux, Kernel v4.9.76-gentoo-r1, [.config](https://github.com/jwilm/alacritty/files/1776208/config.txt)
**If on linux, are you using X11 or Wayland?**
X11 with the proprietary nvidia drivers "x11-drivers/nvidia-drivers".

Alacritty only launches when run as root, when run as a regular user it produces the following when using -vvv:

```error: XDG_RUNTIME_DIR not set in the environment.
Alacritty encountered an unrecoverable error:
Error creating GL context; GL context creation failed
```

It doesn't work even when the x11 opengl implementation is selected using eselect, only when run as root. Any assistance is appreciated!

**Comment by jwilm** [comment]
Can you run `glxgears`?

**Comment by alex-eyre** [comment]
I can as root, functions fine. But as a regular user I get:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  31
  Current serial number in output stream:  32
```

**Comment by jwilm** [comment]
Sounds like this is a configuration issue with your system. Once you can run `glxgears` as a regular user, `alacritty` should function fine.

**Comment by alex-eyre** [comment]
Issue appears to be with the nvidia proprietary drivers and their associated permissions, I have a suspicion my udev rules weren't set up correctly. Switching my system to the nouveau drivers fixed the issue completely.
