### ISSUE TITLE
Color differences between alacritty & iterm 

### ISSUE THREAD

**Issue by ahmedelgabri** [jwilm/alacritty#1135]
Which operating system does the issue occur on?
macOS 10.3.3

There are some color differences between iterm & alacritty that sometimes makes the output not really readable. I ran this [`colortest`](https://github.com/ahmedelgabri/dotfiles/blob/4057a0cb1330d4105590cbf7ed67226d80b49c75/bin/colortest) script to generate color tables.

#### iterm (`Build 3.2.20180301-nightly`) 
<img width="531" alt="iterm" src="https://user-images.githubusercontent.com/63876/36946300-3b620f66-1fbb-11e8-966f-59e791274a53.png">

And inside tmux
<img width="1680" alt="tmux-iterm" src="https://user-images.githubusercontent.com/63876/36946415-f66a4566-1fbc-11e8-8bd6-59454e522ea7.png">

#### alacritty (https://github.com/jwilm/alacritty/commit/475ebecfc4e0648242e82e256dee1489f3a3fe81) [my `alacritty.yml`config](https://github.com/ahmedelgabri/dotfiles/blob/4057a0cb1330d4105590cbf7ed67226d80b49c75/alacritty/.config/alacritty/alacritty.yml)
<img width="544" alt="alacritty" src="https://user-images.githubusercontent.com/63876/36946333-c4fd2238-1fbb-11e8-81f7-6b796c843c81.png">

and inside tmux
<img width="1714" alt="tmux-alacritty" src="https://user-images.githubusercontent.com/63876/36946418-fed0c464-1fbc-11e8-9f18-ca2816955878.png">

You can see that some colors completely disappear from alacritty & it's even clearer in the tmux screenshots were separators are not visible & windows indicators too (top left)

I wonder how can I fix this & if it is a problem with my config or if there is a plan to fix it?

**Comment by chrisduerr** [comment]
I am not aware of any issue with alacritty rendering colors, if your alacritty config is setup properly the colors should always be accurate.

I've tested your colors myself and wasn't able to reproduce your issue, however I've noticed that when you break your config and then save, the live reload does not work anymore.
So for now please make sure you restart alacritty (if possible start it from a different terminal to see stderr) after changing the config to make sure everything is applied properly.

**Comment by ahmedelgabri** [comment]
@chrisduerr One thing I forgot to mention is that I'm using the Mac app (not sure if it makes a difference)

**Comment by ahmedelgabri** [comment]
Ok, I have copied the `alacritty_macos.yml` file & recreated [my config](https://github.com/ahmedelgabri/dotfiles/blob/8fb7565cf787f863d77825d95d4bde2bf30429a5/alacritty/.config/alacritty/alacritty.yml) again. One thing I noticed that I didn't have the dim colors section so I kept this from the default config. 

Still, tmux separators & stuff are not showing (same as the screenshot) actually I don't mind not seeing the separators _in fact I like this, less noise_ but the problem appears with something like `mutt` where I can't see unread messages for example

Here I'm showing my spam folder. See the difference between read messages in iterm & alacritty?

#### iterm
![mutt-item](https://user-images.githubusercontent.com/63876/36947010-78b9cb78-1fc6-11e8-87a8-38503134442c.gif)
 
#### alacritty 
![mutt](https://user-images.githubusercontent.com/63876/36947015-81732aa2-1fc6-11e8-9677-9bda2a1d8487.gif)

**Comment by chrisduerr** [comment]
If there are no issues when starting it from another terminal with `alacritty --config-file <specify file here>`, then I'm not quite sure what might be happening.

I would assume that something else is messing with alacritty. Is the `$TERM` set to `xterm-256`?

**Comment by ahmedelgabri** [comment]
The config looks fine when I lunch from the terminal. Unless I intentionally break the config, then live-reload stops working &`$TERM` is already set to the default `xterm-256color`

**Comment by chrisduerr** [comment]
The live reloading issue should be addressed in the #1136, however that's probably not gonna fix your issue.

I'm not really into macos or tmux, but maybe @jwilm has an idea what could be going on.

**Comment by sodiumjoe** [comment]
I can't reproduce this on macos in tmux, but interestingly:

```bash
➤ echo $TERM
screen-256color
```

**Comment by lloeki** [comment]
> There are some color differences between iterm & alacritty that sometimes makes the output not really readable

iTerm2 likes to mangle colors like nothing else (even with the "minimum contrast" setting to the lowest value). If you want correct color output to match against, compare with Terminal.app (which also correctly handles ICC profiles, contrary to iTerm2).

IMHO this is more of a badly designed theme that iTerm attempts to correct with its "minimum contrast" feature: your alacritty screenshots look correct to me somehow, as when drawing blue on blue, you're *supposed* to see nothing... IOW the colour diagonal should be solid:

<img width="682" alt="screen shot 2018-04-24 at 10 32 36" src="https://user-images.githubusercontent.com/75445/39175541-ec29b54e-47aa-11e8-9545-035f44eeea34.png">

**Comment by lloeki** [comment]
> I am not aware of any issue with alacritty rendering colors, if your alacritty config is setup properly the colors should always be accurate.

@chrisduerr maybe this issue is in fact a feature request for a setting: colour accuracy vs text readability. I am all about the former but can understand the need for the latter, if only for accessibility purposes.

**Comment by ahmedelgabri** [comment]
Thanks @lloeki that was informative 👍 I didn't know about iTerm handling of colors but also I think it will be great as you said if this is improved for accessibility purposes.

**Comment by chrisduerr** [comment]
I'm not quite sure how changing colors would make the terminal more accessible. In my opinion there's just one way to go about this: You set a color in your terminal colorscheme and that color is then displayed. If you have issues with making a distinction between certain colors, you should change your colorscheme instead of alacritty tweaking things.

Unless I'm understanding something wrong here, I don't understand how displaying inaccurate colors would be an accessibility improvement.

**Comment by nomasprime** [comment]
Comparing iTerm to Terminal colours are quite close. Alacritty is way off.

**Comment by fans3210** [comment]
The difference is due to the lack of "P3 color space" in iterm2 production release. Iterm2 recently released a beta version which you can enable this "P3 color space" option in "Advanced" section which can make it look much more similar to Alacritty. 
Refer to: https://gitlab.com/gnachman/iterm2/-/issues/9652
