### ISSUE TITLE
multiple instances of alacritty

### ISSUE THREAD

**Issue by burningTyger** [jwilm/alacritty#1137]
Maybe I'm doing it wrong but is it possible to have more than one window of alacritty open? Yes, I'm using tmux with multiple windows but when I ssh onto another machine which also has tmux open I'm in a nested session which I prefer not to have.

Which operating system does the issue occur on?
Arch

If on linux, are you using X11 or Wayland?
Wayland

**Comment by chrisduerr** [comment]
What happens when you try to run alacritty twice? Have you tried running alacritty with XWayland?

**Comment by burningTyger** [comment]
Ok, when I use `env WAYLAND_DISPLAY= alacritty` inside alacritty to start a second instance it works. I have the exact same setting in my desktop file but it doesn't open a second window through the gnome manager.

**Comment by chrisduerr** [comment]
There still are a few issues with the wayland version, this is most likely an issue with glutin.

**Comment by chrisduerr** [comment]
Also if only the desktop file doesn't work you could try something like `sh -c "env WAYLAND_DISPLAY= alacritty"`. I don't use desktop files so I'm not 100% sure how they work, but that might help.

**Comment by jwilm** [comment]
cc @vberger

**Comment by vberger** [comment]
Hmm, I don't understand, what exactly does not work with starting alacritty several time in a wayland session ?

Trying to run them in weston works fine...

**Comment by chrisduerr** [comment]
I don't think this is a wayland issue, but rather a problem with the `.desktop` file because it seems like starting it from the command line does work.

**Comment by chrisduerr** [comment]
This is tracked together with the same issue for macOS in https://github.com/jwilm/alacritty/issues/607.
