### ISSUE TITLE
Bump alacritty version on commit

### ISSUE THREAD

**Issue by eternaltyro** [jwilm/alacritty#1138]
Please bump minor version on commit. This is just a suggestion for good practice and not a product bug. This will help users determine if the problems they are seeing are old problems. Sure, I can see the commit ID in the build, but it'll be useful to do `alacritty --version` to check at exactly which point it has been compiled from. Right now, it stays at `alacritty 0.1.0`.

An example could be with minor version like `alacritty 0.1.0a`, `alacritty 0.1.1a` and so on. In the future, this might help with releasing defined versions against milestones. 

Operating System: MacOS 10.13 (OS independent however)

**Comment by jwilm** [comment]
We will start doing this once we are shipping precompiled binaries
