### ISSUE TITLE
Apply config changes on the fly

### ISSUE THREAD

**Issue by poisonby** [jwilm/alacritty#1140]
I know it's possible to do this with colour, but is it possible to do it with other options as well? I'm primarily thinking about font settings like changing the font size.

**Comment by chrisduerr** [comment]
You can change the font size on the fly by using the keybinds for that. Currently fonts are actually the only thing that is not live reloaded and I wouldn't expect that to be implemented until #957 is accepted and implemented.

I'm gonna close this issue for now, if you're interested in seeing this land, please leave a comment on the font configuration RFC.

**Comment by cata0309** [comment]
I don't see the live reload to work at all with alacritty. I don't know why that.

**Comment by kchibisov** [comment]
@cata0309 make sure that you're using the right config. You can use `alacritty -v` to find out the config, also it doesn't apply to any setting. You can try changing background color, since it the most noticeable one.
