### ISSUE TITLE
Config failure should be printed in the new alacritty instance

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1143]
When starting alacritty with a faulty config, the errors are printed to `stderr`. However this only helps when starting alacritty from another alacritty instance.

To make debugging more obvious on users warnings and error should also be printed to the newly launched alacritty process. This will clearly indicate to the user if something is wrong without having to launch from another terminal.

Another benefit of this could be a faster adoption of new config layouts. If deprecation warnings are printed whenever starting a new terminal, it will strongly encourage the user to actually make changes so we can quickly remove things.

**Comment by jwilm** [comment]
I like this idea, but it will need to be implemented as sort of another display layer and not interact with whatever app is running.

**Comment by chrisduerr** [comment]
Maybe we could do something similar to the FPS counter and just render some text in the top-left corner for X seconds. To make things simpler we could just show a message like `There were some errors in the config` instead of showing all issues, then the user can start from a different terminal to check out what exactly is wrong.

**Comment by sodiumjoe** [comment]
I think I would prefer a logfile written somewhere that a short popup message could point to.

**Comment by chrisduerr** [comment]
Yeah I'm a fan of that. `/tmp/alacritty.log` and then the message that points there, good idea!
