### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by prdx** [jwilm/alacritty#1146]
> Which operating system does the issue occur on?
Fedora 27

If on linux, are you using X11 or Wayland?
> Wayland

![screenshot from 2018-03-08 12-52-33](https://user-images.githubusercontent.com/4593408/37167365-b7f88462-22cf-11e8-921b-39f5d0c2b943.png)

I have tried to look for the configuration on .allacrity.yml but could not find the correct configuration. Tried to increase the font size as well, but doesn't work. Did I miss something?

**Comment by chrisduerr** [comment]
Try increasing the font size but start alacritty from a different terminal emulator.

If the font size doesn't change when changing it it the config, there's probably something wrong with the config.

**Comment by prdx** [comment]
changing the font to a larger number (30.0) helps. The window size is smaller than the text though, which makes some text goes to the new line. Is it because my screen resolution?

**Comment by chrisduerr** [comment]
I mean there's only so much text that can fit into one line, if it doesn't fit, it will flow over into the next on.

**Comment by jroblak** [comment]
I'm having the same issue on macOS whe my laptop is connected to an external monitor. When the monitor is not connected, alacritty's font rendering is normal. However, when the monitor is attached (iTerm for comparison):
<img width="1464" alt="screen shot 2018-03-12 at 10 46 43 am" src="https://user-images.githubusercontent.com/1679799/37290475-b4e44f8e-25e2-11e8-97fe-7ccbe7b9b1ec.png">

**Comment by chrisduerr** [comment]
This is a current issue with glutin, it does not allow getting the DPI on a per-monitor-basis. So having two very different monitors can lead to issues with font scaling.

**Comment by prdx** [comment]
Sorry for the late reply and for the unclear comment. What I meant was, I need to change my font size into size 30+ to get the same size as font size 18 on gnome-terminal.

I am using XPS 13.3” QHD+ (3200 x 1800)  if that helps

**Comment by eidge** [comment]
Same issue here on Macos.

I need these settings to make the fonts similar on both screens:

Retina screen: 12px
2k 27inch external screen: 18px

**Comment by sodiumjoe** [comment]
Sounds like it might be related to https://github.com/jwilm/alacritty/issues/964

can you try [this](https://github.com/jwilm/alacritty/issues/964#issuecomment-382098460) to see if it fixes your issue?
