### ISSUE TITLE
Selection is not cleared as storage buffer wraps

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#1149]
If a selection scrolls all the way to the end of the buffer, we don't update state accordingly or clear it once the entire selection is off-buffer.

**Comment by chrisduerr** [comment]
By off-buffer you mean completely outside of the scrollback buffer, right? What is the issue with keeping it around, is there some potential issue? Besides that we can't do anything with it anymore.

**Comment by jwilm** [comment]
I just assumed there would be a problem. If there's not a problem, then maybe there's no action required here.

**Comment by chrisduerr** [comment]
I am not able to see any issue. It doesn't crash just by moving outside and even using ctrl+shift+c for copying the selection (that doesn't exist anymore) seems to just be a noop, it doesn't even overwrite the last clipboard content.

**Comment by javmorin** [comment]
Just putting in $0.02; the ability to select while scrolling back in the buffer is certainly a nice to have. You wouldn't want the selection to get removed if parts of it were off screen, though not sure that is actually indicated by this issue though. The ability to select/copy more than one screen of output is key to my usage of scrollback in other terminals (sometimes need to copy lots of debug output).

Looking forward to being able to use alacritty more once this scrollback branch is good to go!

**Comment by chrisduerr** [comment]
I believe this issue is just about clearing the selection when the selected cells leave alacritty's scrollback history storage.

What you are talking about sounds more like #1173.

**Comment by jwilm** [comment]
I don't think this is actually a problem in practice. The selection checks only care if it's in the visible area, not if it's fallen off the buffer.
