### ISSUE TITLE
Faux scrolling under scrollback

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#1152]
How does faux scrolling fit in with native scrollback? It's disabled on the PR right now.

**Comment by chrisduerr** [comment]
Whenever a native scrollback buffer is available, faux scrollback does not exist.

Faux scrollback also is a bit of a wrong name for this (totally my fault, see #1095). This should rather be "faux_scrolling". It only exists in the alternative screen buffer when the mouse is not captured, I don't think scrollback should interact with this at all, it should all be input related.

**Comment by jwilm** [comment]
resolved by #1158
