### ISSUE TITLE
Add support for --hold flag

### ISSUE THREAD

**Issue by occivink** [jwilm/alacritty#1165]
The `--hold` flag is supported by many other terminal emulators and causes the terminal window to stay open after the command returns.

This is useful when using gdb to debug a console application: one can run `favorite_terminal --hold -e tty` to get the tty name and leave it open. 
Then in gdb,  call `tty <tty-name>` before running the application. It will be started on the terminal held open. 
This doesn't work if the command being run is not finished, as the terminal already has a "session leader".

**Comment by chrisduerr** [comment]
I'd be interested why this feature would be added over just running the following:

```
alacritty -e sh -c "command && sleep infinity"
```

The original usecase mentioned in the issue seems a bit special to me, since it requires more than just holding the terminal and I don't see an advantage over just running the application directly in the terminal.

**Comment by occivink** [comment]
Wrapping everything in a shell call is possible, but then you need to carefully quote parameters and you lose the clean argument forwarding that `alacritty -e` does.

>I don't see an advantage over just running the application directly in the terminal.

If you're debugging a program that runs in the terminal (TUIs especailly) it's not really feasible.

**Comment by chrisduerr** [comment]
> If you're debugging a program that runs in the terminal (TUIs especailly) it's not really feasible.

How is it not? I've done this myself before without any problems.

**Comment by occivink** [comment]
I think there's a misunderstanding here. Let's say you want to debug vim. If you just open `gdb vim` and do `run`, vim will take over the terminal so you can't interact with gdb anymore, and in addition you'll get rendering glitches as both programs try to write to the same terminal.
Possible solution are to either 
* attach gdb to vim after it's been launched
* open a blank terminal with `--hold` and tell `gdb` to open the debugged there. This is mostly what this issue is about.

**Comment by occivink** [comment]
I should also mention that solution #2 doesn't work if you do `tty && sleep infinity` since, as I mentioned, the terminal already has a "session leader".
At least this was my understanding at the time I opened this issue.

**Comment by chrisduerr** [comment]
> open a blank terminal with --hold and tell gdb to open the debugged there. This is mostly what this issue is about.

Which terminal does this actually work in?

**Comment by occivink** [comment]
`konsole`, possibly others

**Comment by chrisduerr** [comment]
> possibly others

I don't think that's the usual behavior to be honest. At least not in any of the terminal emulators I've tested.

So this would be quite different from the conventional hold flag.

**Comment by occivink** [comment]
Could be; this was the advice I got from gdb folks on irc at the time.

**Comment by nixpulvis** [comment]
@occivink to run a GDB session for a running instance of `vim` all you should need to do is open a new terminal (running a shell as normal). The shell should be enough to keep your terminal from closing when/if you quit `gdb`. Run `sudo gdb`, and then attach to the `vim` process with `attach PID`.

Am I misunderstanding something?

To me the `--hold` flag is simply a way to avoid the shell, which is of marginal value to me, but does seem potentially useful. Alacritty's got a pretty minimal philosophy, which running commands in a useful way without a shell would fit into IMO.

**Comment by occivink** [comment]
I'm aware of attaching as you've noticed from my previous comment. It works until you want to debug some startup code. The second approach allows you to debug the complete execution of the program when it works.
