### ISSUE TITLE
Key: Left or Right mods: Alt not working

### ISSUE THREAD

**Issue by jesselucas** [jwilm/alacritty#1175]
Which operating system does the issue occur on?
macOS 10.13.3

When I use alt+left or alt+right Alacritty prints `;3D` and `;3C`

**Comment by jesselucas** [comment]
This was a misunderstanding on my part on how backward-word worked in bash and isn't an issue with Alacritty.

**Comment by geowa4** [comment]
What did you do to resolve this? I think I have the same misunderstanding.

**Comment by jesselucas** [comment]
@geowa4 the hot key was set in macOS’ terminal. I’m using bash and found the movement commands here: http://www.gnu.org/software/bash/manual/bashref.html#Readline-Movement-Commands

Ultimately I switched to vimode for myself so didn’t continue down the path of setting up the arrow keys. Hope this helps!

**Comment by geowa4** [comment]
This is how I solved it. 
```
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       }
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       }
```
