### ISSUE TITLE
Selection moving off screen glitch

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#1182]
When selection moves off the screen, it jumps around a bit right now. I think a solution which first resolves a selection to _buffer_ coordinates and then clips and transforms to screen space would not exhibit this problem.

**Comment by chrisduerr** [comment]
If this is what I think it is, this should already be fixed with #1171.

**Comment by jwilm** [comment]
oh, it might be. I just haven't tested #1171 since it had conflicts by the time I looked at it.

**Comment by chrisduerr** [comment]
Yeah there was an issue which lead to really weird behavior when selection was started from the first cell in a line. And a different bug that would not show the first line as selected. So these two combined might lead to very odd results.

**Comment by chrisduerr** [comment]
Is this fixed now with #1171 @jwilm?

**Comment by jwilm** [comment]
I still need to test this.

**Comment by jwilm** [comment]
This looks like it's resolved.
