### ISSUE TITLE
Error creating GL context after update to the latest master

### ISSUE THREAD

**Issue by synaptiko** [jwilm/alacritty#1184]
Few moments ago I've updated to the latest master, commit 196e60238758a473043ef5df5798c7da25e923d1 and I started getting this error:
```
Error creating GL context; Couldn't find any pixel format that matches the criterias.
```

Which is weird because I found [#1178](https://github.com/jwilm/alacritty/pull/1178) should be a fix for it but I didn't have this error before.

Is there something I have to configure?

**Which operating system does the issue occur on?**
ArchLinux (4.15.8-1-ARCH x86_64 GNU/Linux) with X11

**Comment by synaptiko** [comment]
Maybe [#1183](https://github.com/jwilm/alacritty/pull/1183) is the fix of the regression introduced by #1178.

**Comment by tahahawa** [comment]
I was having this issue as well. Applied #1183 and it seems to work, at least in debug build. Haven't tried release mode yet.

**Comment by synaptiko** [comment]
#1183 landed in master, it fixed the problem for me… @svenper does it work for you now too or not? if it works for all of us we could close the issue…

**Comment by svenper** [comment]
@synaptiko I updated to master and it works now. I must have forgotten something the previous try!

**Comment by synaptiko** [comment]
#1183 fixed it for all of us :-) thanks @lo48576 for a quick fix…

**Comment by embik** [comment]
I'm still having this issue with latest `master`, but I'm running the new mesa 18.0.0. Anybody else with mesa 18.0.0 having this issue?
