### ISSUE TITLE
The screen should scroll down when backspace is pressed

### ISSUE THREAD

**Issue by Booteille** [jwilm/alacritty#1187]
> **Which operating system does the issue occur on?**
> Linux Mint 18.3
> 
> **If on linux, are you using X11 or Wayland?**
> X11

I am using the Scrollback branch.

Actually, typing anything in the terminal scroll it down to see what we actually typed. However it doesn't scroll down when we press the backspace key.
Maybe is it just something forgotten or is it the desired behavior?

**Comment by chrisduerr** [comment]
Alacritty has setup backspace as a `bey_binding` by default and whenever a binding is executed alacritty does not scroll (which is definitely the right approach).

We might need to add a special case for this, but the behavior would probably be the same for character sequences setup to print a certain text. So if I have a hotkey for writing `test`, it would not scroll either.

There might be a better place to scroll to the bottom than the `received_char` method.

**Comment by chrisduerr** [comment]
Other terminals also scroll when commands like `sleep 3; ls -lah` are run. Alacritty does not do this.
