### ISSUE TITLE
Ubuntu - installation fails with "No package freetype2 found"

### ISSUE THREAD

**Issue by foo-jin** [jwilm/alacritty#1193]
Ubuntu 16.04, with all the dependencies listed in the README installed. The full error is 

> --- stderr
> configure: error: Package requirements (freetype2) were not met:
> 
> No package 'freetype2' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables FREETYPE_CFLAGS
> and FREETYPE_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> make: *** [/tmp/cargo-install.qGDQTA1ENDff/release/build/servo-fontconfig-sys-ac2ac06b8cdaf817/out/Makefile] Error 1
> thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f",
>                             "makefile.cargo"]).status().unwrap().success()', /home/frank/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/5c1845e/build.rs:17:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `alacritty v0.1.0 (https://github.com/jwilm/alacritty#6debc4f3)`, intermediate artifacts can be found at `/tmp/cargo-install.qGDQTA1ENDff`
> 
> Caused by:
>   build failed

**Comment by chrisduerr** [comment]
Have you tried rebooting after installing the freetype2 dependency? Also make sure the package was actually installed successfully.

**Comment by foo-jin** [comment]
Yes, all the dependencies installed succesfully (the freetype package listed for ubuntu was freetype6-dev instead of freetype2, although that shouldn't matter). Unfortunately I still ran into the same error after restarting.

**Comment by chrisduerr** [comment]
It should be `libfreetype6-dev`.

**Comment by foo-jin** [comment]
You're correct, I made a mistake in my comment. That is the package I had installed however, so that is not the source of this problem.

**Comment by foo-jin** [comment]
Manually exporting `PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig` solved it in my case.
