### ISSUE TITLE
selection span doesn't dispear as expected when scrolling in tmux.

### ISSUE THREAD

**Issue by csmoe** [jwilm/alacritty#1197]
Which operating system does the issue occur on?
`Linux 4.14.27-1-MANJARO #1 SMP PREEMPT Thu Mar 15 19:47:13 UTC │
2018 x86_64 GNU/Linux  `
If on linux, are you using X11 or Wayland?
`X11`

When scrolling within `tmux`, the selection span always remains there.(alacritty installed from master without `ScrollBack`)
![out](https://user-images.githubusercontent.com/35686186/37696228-1646cf34-2d10-11e8-8e7f-14caa68608d9.gif)

**Comment by maximbaz** [comment]
Are you talking about tmux's selection or native alacritty's one?

If former, add something like this to your `.tmux.conf`:

```
# Make mouse scroll clear selection
bind -T copy-mode-vi WheelUpPane   select-pane \; send -X clear-selection \; send -N3 -X scroll-up
bind -T copy-mode-vi WheelDownPane select-pane \; send -X clear-selection \; send -N3 -X scroll-down
```

**Comment by csmoe** [comment]
thank you, I made a mistake, it's not a bug but tmux config.
