### ISSUE TITLE
Cursor disappears on first column in vim

### ISSUE THREAD

**Issue by ijl** [jwilm/alacritty#1198]
Moving the cursor down in vim while on the first column causes the cursor to disappear until moved to the second column of a non-empty line. This is on macOS or Linux, vim or neovim, on the scrollback branch at 14a76ec5c78fde8d4fbf1d78e0108ded13a7edc2.

Reproduce: `vim <(echo 'one\ntwo\n\nthree')` and scroll down.

**Comment by jwilm** [comment]
Thanks for filing the issue! I also noticed a problem of the cursor disappearing when using vim-fugitive and `:Gblame`.

**Comment by ijl** [comment]
Thanks, @jwilm.

**Comment by jwilm** [comment]
This was fixed.
