### ISSUE TITLE
Recent build no longer associated with terminal icon - possible mime-type issue.

### ISSUE THREAD

**Issue by cbcoutinho** [jwilm/alacritty#1199]
Which operating system does the issue occur on? I'm on OpenSUSE Leap 42.3

If on linux, are you using X11 or Wayland? X11

---

Starting `alacritty` through another terminal or using a keyboard shortcut works fine, so this is not a build issue; however, `alacritty` used to be associated with terminal icon on my desktop, and now it's a plain white 'unknown' icon.

A recent build of `alacritty` isn't associated with the `utilities-terminal` icon on my machine. I've looked into it a bit, and it seems to be related to it's mime-type. For instance, trying to execute `alacritty` through the file explorer results in the following error:

![screenshot from 2018-03-22 13-29-15](https://user-images.githubusercontent.com/12901868/37770539-0b71c17a-2dd5-11e8-80b3-74cb87709fdd.png)

I was able to fix this problem by building `alacritty` with `RUSTFLAGS="-C relocation-model=dynamic-no-pic"` (based off a comment in [this answer](https://stackoverflow.com/a/27391580/5536001)), but I don't know enough about how applicable this is to the rest of the project to put in a PR.

Maybe others will find this useful.

**Comment by jwilm** [comment]
Sounds like this is an issue with your `.desktop` file. I have no idea why recompiling without PIC would make a different or how you came to that solution. This is unlikely to be a problem with alacritty and more probably a config issue on your system.

**Comment by cbcoutinho** [comment]
HI @jwilm thanks for your comment. Just to clarify, I didn't changed the `.desktop` file - it's the same one distributed with this project. After building `alacrirtty` using `cargo build --release`, I copied the resulting binary to `~/.local/bin` where I have other user-level packages installed. I also don't know what you mean by a config issue - do you have an idea of where to look?
