### ISSUE TITLE
Ubuntu: Error creating GL context; Some of the required attributes are not supported

### ISSUE THREAD

**Issue by TaylorDennisLee** [jwilm/alacritty#1204]
Which operating system does the issue occur on?

Ubuntu 17.10

If on linux, are you using X11 or Wayland?

Wayland?

It seems to build fine, but when I try to execute the binary, I get this error:

Error creating GL context; Some of the required attributes are not supported

**Comment by DaGuich** [comment]
#1083 
env WAYLAND_DISPLAY= alacritty

**Comment by chrisduerr** [comment]
Closing this as a duplicate of #1083.
