### ISSUE TITLE
Issue while using Fish + Tmux + SSH + Vim

### ISSUE THREAD

**Issue by omtcvxyz** [jwilm/alacritty#1208]
# General information

I assume what I experience are several issues, but since I am not familiar with the alacritty internals I will describe my experience in a single issue.

## Steps to reproduce & tools usage

In my terminal emulator I use Fish. After opening alacritty I connect to a remote server via `$ ssh user@host` and these are the issues I'm having:

### Erasing text

While trying to erase text I'm typing the previous symbols are not removed. Instead, spaces are added and the text I enter after that erasure attempt comes after these spaces.

For example I try to type `$ echo $HOR` then I realise I didnt want to type "R" and I try to erase it to end up with `$ echo $HOME`. I press backspace and get `$ echo $HOR_` (`_` corresponds to a whitespace, otherwise it doesn't render correctly in markdown). Finally, I type `ME` and get

`$ echo $HOR ME`

Pressing enter makes the command execute and actually reveals that the real contents of last command are `$ echo $HOME`.

### Vim issues

Trying to edit something with Vim is a nightmare, too. Launching it causes a warning:

```
E437: terminal capability "cm" required
Press ENTER or type command to continue
```

The opened Vim buffer is messed up, text is shuffled along the lines, there is a huge offset from the beginning of each line, none of the visual effects are present. Closing it (blindly, of course) leaves the contents of that messed window in the terminal and only shows the interpreter prompt after it while leaving the following message:

```
'tmux-256color': unknown terminal type.
```

The very same message appears on any attempt to do `$ clear` or any other terminal-related stuff.

### Other terminals

I have checked `urxvt` terminal, using it none of the issues above are reproducible, the experience is satisfactory.

#### Which operating system does the issue occur on?

Arch Linux

#### If on linux, are you using X11 or Wayland?

X11

#### Software information & Extra

If it helps, here's the information about the software I'm using (basically all the updated Arch packages + the ones on the remote server.

* alacritty-git 0.1.0.755.g6debc4f-1 installed from AUR
* openssh 7.6p1-2
* Vim on the remote server (OpenSUSE)
```
VIM - Vi IMproved 7.4 (2013 Aug 10)                                                                                                    Validated By    : None
Included patches: 1-207, 209-326                                                                                                      
Compiled by 'http://www.opensuse.org/'
```

Again, if it helps, here are my config files:

* [alacritty.yml](https://github.com/omtcvxyz/dotfiles/blob/master/.config/alacritty/alacritty.yml)
* [.tmux.conf](https://github.com/omtcvxyz/dotfiles/blob/master/.tmux.conf)
* [.vimrc](https://github.com/omtcvxyz/dotfiles/blob/master/.vimrc)
* [.bashrc](https://github.com/omtcvxyz/dotfiles/blob/master/.bashrc)

**Comment by chrisduerr** [comment]
This might be an issue with terminfo. Does `echo $TERM` give you `xterm-256color`?

**Comment by omtcvxyz** [comment]
@chrisduerr you are correct. However, my `tmux.conf` overrides `$TERM` with `tmux-256color`, so it shouldn't be `xterm-256color` (it only is outside of Tmux).

Thus, I guess the issue is caused by `$TERM` being `tmux-256color`.

**Comment by maximbaz** [comment]
I'm also on Arch + X11 using tmux, my `$TERM` value is `xterm-256color` outside tmux and `tmux-256color` inside tmux, and I don't experience such issues.

Does the issue reproduce when you are outside tmux? What if you are inside tmux, but use local vim (instead of on the remote server)?

**Comment by maximbaz** [comment]
Actually, I just remembered that I'm doing a special trick when ssh'ing somewhere, try this:

```
TERM=xterm-256color ssh myhost
```

If it helps, just create an alias for yourself:

```
alias ssh='TERM=xterm-256color \ssh'
```

**Comment by chrisduerr** [comment]
I'd assume that this is an issue with the target machine not supporting the `tmux-256color` `$TERM` because `tmux` is not on the target machine and so the terminfo file can not be found?

In that case either using `ssh` with `xterm-256color` the way maximbaz described or installing `tmux` on the target could both solve the issue.

**Comment by omtcvxyz** [comment]
@maximbaz, thanks for the input!

> Does the issue reproduce when you are outside tmux? What if you are inside tmux, but use local vim (instead of on the remote server)?

The issue does not reproduce when I'm using your hint (i.e. `TERM=xterm-256color ssh  ...`). Also, it's fine on my local machine inside and outside of tmux.

Thus, using the trick  you suggested resolves the issue, but I guess it's rather hack than a solution.

@chrisduerr oh, I maybe forgot to mention: the target machine does support `tmux-256color` and it has tmux installed. I.e. when I connect to that machine using `urxvt` after launching tmux locally I get

```
user@host:~> echo $TERM
tmux-256color
```

The very same output I have on alacritty. However, as I mentioned before none of these issues arise when using urxvt.

**Comment by omtcvxyz** [comment]
Oh, wait, actually, `urxvt` with the very same setup appears to have the same issues with `tmux-256colors` via SSH. Apologies for wrong information I reported before.

Therefore, I think it's the host machine problem in the end, even though I'm unsure why this happens because everything there is fairly up-to-date.

I think I will have to use the trick @maximbaz provided, thank you for the help and apologies for inconvenience!

**Comment by Koleon** [comment]
Hello guys, 
I have the same issue that was described by @kirillbobyrev 
I'm connecting from Archlinux with alacritty to a remote server running RHEL 8.1. Have you found out any why is it happening?

**Comment by nixpulvis** [comment]
@Koleon read through this thread, specifically https://github.com/alacritty/alacritty/issues/1208#issuecomment-376697989 may help you.

**Comment by bakkeby** [comment]
The first option in the `alacritty.yml` config file has optional settings to set the TERM environment variable to something other than the default "alacritty".

**Comment by krzkrzkrz** [comment]
> Actually, I just remembered that I'm doing a special trick when ssh'ing somewhere, try this:
> 
i> ```
> TERM=xterm-256color ssh myhost
> ```
> 
> If it helps, just create an alias for yourself:
> 
> ```
> alias ssh='TERM=xterm-256color \ssh'
> ```

How would one do this kind of alias in `fish`? In `.config/fish/aliases.fish`. I have:

```
alias ssh 'TERM=xterm-256color \ssh'
```

Running the `ssh` command in a terminal returns:

```
- (line 1): The function “ssh” calls itself immediately, which would result in an infinite loop.
function ssh --wraps 'TERM=xterm-256color ssh' --description 'alias ssh TERM=xterm-256color ssh';  TERM=xterm-256color ssh $argv; end
```

**Comment by rumpelsepp** [comment]
> alias ssh='TERM=xterm-256color \ssh'

Try `alias ssh='TERM=xterm-256color /usr/bin/ssh'`.

**Comment by krzkrzkrz** [comment]
Oh sweet, didnt cross my mind to put in the full path. This works. Thanks you @rumpelsepp

**Comment by mojitaleghani** [comment]
> Actually, I just remembered that I'm doing a special trick when ssh'ing somewhere, try this:
> 
> ```
> TERM=xterm-256color ssh myhost
> ```
> 
> If it helps, just create an alias for yourself:
> 
> ```
> alias ssh='TERM=xterm-256color \ssh'
> ```

If you have any ssh config, just update it when you are trying to ssh to any remote host. 
By the way, I have a ssh_config file and update it with bellow:

```
Host *
        Port ###
        User ###
        RemoteCommand TERM=xterm $SHELL
        RequestTTY yes
```

and then using tmux you can connect to any remote by sshing to them.
