### ISSUE TITLE
config "action" to change font size

### ISSUE THREAD

**Issue by dannydulai** [jwilm/alacritty#121]
It'd be nice to have an option to change the font size .. like mapping cmd-+ or cmd-- or cmd-0 to reset the fontsize

this should throw away the atlas and changing the number of chars on the window, and not resizing the window.

**Comment by casey** [comment]
@elrond: That sounds scary! Is it actually desirable to allow a command running in your terminal to change the font size? I've never needed it, but perhaps there are cases I'm not considering.

**Comment by deepy** [comment]
@casey maybe have an option for turning it on and leaving it turned off by default?

**Comment by casey** [comment]
@deepy That seems reasonable. Although I'm curious, when would you want a program to be able to change the font size? Would a keyboard shortcut be good enough?

**Comment by jomendoz** [comment]
Any updates with this feature request? Is this improvement considered hard? Or it's menial work?

**Comment by jwilm** [comment]
@jomendoz not considered hard, but I wouldn't call it menial either. Every feature takes time.

**Comment by jomendoz** [comment]
@jwilm I didn't want to sound offensive but if it's not concerned with a lot of thought and design I'd like to help. I'm starting to learn Rust, so if the task is not very demanding I could spend a little bit of time on it.

**Comment by da-x** [comment]
Pending implementation in PR #625.

**Comment by sodiumjoe** [comment]
Looks like this is fixed by https://github.com/jwilm/alacritty/pull/625.

**Comment by angvp** [comment]
It is fixed, working flawlessly this can be closed @jwilm :)

**Comment by jwilm** [comment]
Thanks @angvp

**Comment by lompabo** [comment]
Mmm... not working for me (OSX). It seems to be related to the fact that I am using a non-US keyboard (Italian layout), which may be using different key names.

In particular:

- "Command + =" seems to be recognized as "Command + 0"
- "Command + Minus" is probably recognized as something else, but I don't know how to check it

Ramapping the "ResetFontSize", "IncreaseFontSize", and "DecreaseFontSize" to numeric keys (+ Command) circumvents the issue.

**Comment by angvp** [comment]
@lompabo what kind of keyboard do you have?, for me it works in OSX with the us keyboard (the one on the MBP) and the combination of Cmd =+ key  for increase and for decrease  Cmd _- 

Even if I connect an external keyboard (non apple keyboard) it works the same, again with the US Layout.. maybe it's a layout thing.

**Comment by lompabo** [comment]
@angvp I agree with you it must be related to the layout: I am using an Italian keyboard (see the original post).

Thanks!

**Comment by angvp** [comment]
Well, sucks to be you :), j/k maybe opening a different issue now that we know is a layout thing.. maybe other layouts (almost sure) has the same issue.

**Comment by rafi** [comment]
Works for me (macOS):
```
  - { key: Key0,     mods: Command, action: ResetFontSize }
  - { key: Equals,   mods: Command, action: IncreaseFontSize }
  - { key: Minus,    mods: Command, action: DecreaseFontSize }
```
