### ISSUE TITLE
Alacritty is preventing automatic graphics switching

### ISSUE THREAD

**Issue by mkeeler** [jwilm/alacritty#1211]
Which operating system does the issue occur on?

macOS

If on linux, are you using X11 or Wayland?

According to activity monitor, alacritty is requiring the high perf gpu in my laptop. I looked in the Info.plist and the key for claiming automatic graphics switching is in there. Should the switching work and if not I would like to request it as a new feature.

**Comment by jwilm** [comment]
Hey, sorry about that. This issue is being actively tracked in #210.
