### ISSUE TITLE
Linking error on macOS

### ISSUE THREAD

**Issue by hsribei** [jwilm/alacritty#1213]
- macOS 10.13.3
- rustup show:

```
active toolchain
----------------
stable-x86_64-apple-darwin (directory override for '/Users/hsribei/usr/src/alacritty')
rustc 1.25.0 (84203cac6 2018-03-25)
```
- command run: `cargo build --release`

- error:

```
error: failed to link or copy `/Users/hsribei/usr/src/alacritty/target/release/deps/alacritty-d4ffa9f66d14fa87.dSYM` to `/Users/hsribei/usr/src/alacritty/target/release/alacritty.dSYM`
Caused by:
  the source path is not an existing regular file
```

- note: the file `/Users/hsribei/usr/src/alacritty/target/release/deps/alacritty-d4ffa9f66d14fa87` does exist, just not with the `.dSYM` extension.

**Comment by sodiumjoe** [comment]
Hm, I just tried from the same version of rust and I'm on the same version of macos, no repro.

**Comment by hsribei** [comment]
I ran `cargo clean`, tried again, and it worked  ¯\_(ツ)_/¯
