### ISSUE TITLE
Double pasting in vim when using mouse middle click (linux, X11)

### ISSUE THREAD

**Issue by HerrmannM** [jwilm/alacritty#1215]
Hi guys,

Many thanks for the hard work!

In linux, X11, using vim, I have a "double pasting" behaviour when pasting with the mouse middle click.
Disabling the mouse binding in the alacritty conf prevents from pasting in the term, but still works inside vim itself.

I guess this is a alacritty issue (or maybe feature if it is the intended behaviour ;-) ) as my current vim config works as expected in other term (eg xfce-terminal).

Cheers!

**Comment by chrisduerr** [comment]
I can't reproduce this and it really sounds like a config issue. Does this work with an empty vim config?

**Comment by cyrinux** [comment]
Hi, I have the same problem.
I can confirm there is no problem with an empty neovim config. :/

**Comment by chrisduerr** [comment]
Then it is a configuration issue, you've probably somewhere configured (neo)vim to paste from clipboard when middle mouse is pressed.

**Comment by HerrmannM** [comment]
Hi, and thanks for your replies!

I have the issue in vim (I have never use neovim, so I can't tell for that one), with a .vimrc containing only the line set mouse=a
And with my usual config, removing the line mouse=a causes the issue to disappear.

However, this only happens to me with alacritty, i.e. with a vimrc containing only set mouse=a, I have the double paste in alacritty but not in xterm, gnome-terminal, konsole, xfce-terminal, urxvt.

Cheers!

**Comment by chrisduerr** [comment]
Sounds to me like copy/pasting into/from system clipboard might be disabled in mouse mode, I'll look into how exactly other terminal emulators do it.

**Comment by chrisduerr** [comment]
@HerrmannM I've opened a PR that should fix this with #1218, can you confirm that this PR fixes the issue?

**Comment by HerrmannM** [comment]
@chrisduerr Yes, this fixes the issue, thank you very much!
Cheers!

**Comment by n1zzo** [comment]
The pull request fixes the issue but breaks scroll wheel support on master 3d75c4.

**Comment by chrisduerr** [comment]
The PR does not touch anything other than the `PasteSelection` action, are you sure that it broke scroll wheel support? Also what do you mean by "scroll wheel support" exactly @n1zzo?

**Comment by n1zzo** [comment]
Sorry for the cryptic message,
in my machine the alacritty client does not scroll whenever I scroll my scrollwheel.
However I just tried and this is totally independent from your patch.
I will look among the other issues and eventually open a new one.
Just for information I'm using an up-to-date version of Arch Linux on kernel 4.15.15-1.

**Comment by chrisduerr** [comment]
No problem, better to have one too many bug reports than missing one! :)

The `alacritty-scrollback-git` aur package currently uses the #1147 PR, once that is merged it will be available on the latest master.

**Comment by valarauca** [comment]
So I've see too. The pasting is _spotty_. But my version is very old (pratically from release). I'll recompile to the current HEAD and try to recreate.

**Comment by chrisduerr** [comment]
@valarauca The PR to fix this is not merged yet. So you'll have to wait until jwilm gets around to it.

**Comment by valarauca** [comment]
@chrisduerr @jwilm thanks :D
