### ISSUE TITLE
Part of screen unused

### ISSUE THREAD

**Issue by FelipeMarcelino** [jwilm/alacritty#1221]
Which operating system does the issue occur on? Manjaro/i3

My neovim editor has some space unused(below/right):

![1522625564_2032_01 04 2018_1366x768](https://user-images.githubusercontent.com/15383718/38178615-05d87054-35ed-11e8-91f9-3f6f0b47d2ff.png)

But, when I try another terminal, like xfce-terminal:

![1522626105_2041_01 04 2018_1366x768](https://user-images.githubusercontent.com/15383718/38178621-1eaf8298-35ed-11e8-8274-89d0a6d884e6.png)

I  don't have this space below and right.

**Comment by chrisduerr** [comment]
Did you accidentally float the window maybe? I'm using i3 and I've never had alacritty tile incorrectly.

**Comment by maximbaz** [comment]
I think what they mean is that there is some space beyond the grid inside the alacritty window. With https://github.com/jwilm/alacritty/pull/1190 the grid will be centered, so the empty space will be all around the window.

**Comment by sodiumjoe** [comment]
#388 would also be a way to handle this I think

**Comment by chrisduerr** [comment]
Closing since there was no more reply and I do not believe what's reported here is an Alacritty issue (or it's something that's tracked in a different issue already).
