### ISSUE TITLE
/usr/local/bin/ is stripped from the $PATH env. variable

### ISSUE THREAD

**Issue by cryptoeraser** [jwilm/alacritty#1223]
Which operating system does the issue occur on?
OSX 10.11.6 (15G1004)

If on linux, are you using X11 or Wayland?
(Not applicable)

Is it possible that, somehow the `/usr/local/bin/` string is stripped from the `$PATH` variable.

When  running iTerm2 or the native OSX terminal, everything is fine. However, when I fire-up Alacritty, I have noticed that `/usr/local/bin/` is not in there?

I have `npm` and `gulp` installed there, so I have noticed this issue when those stopped working inside Alacritty.

**Comment by jwilm** [comment]
This sounds like you want a login shell. Try adding `-l` to the start command args in your config.

**Comment by doy** [comment]
i also just ran into this issue - would it make sense for the behavior on osx to be to default to running a login shell, since that appears to be standard there?

**Comment by sodiumjoe** [comment]
There's already an open issue capturing that: #1071
