### ISSUE TITLE
Mouse scrolling in nvim results in ctrl+T?

### ISSUE THREAD

**Issue by vorner** [jwilm/alacritty#1228]
Hello. For some time I was observing some strange behaviour and assumed it was some kind of plugin in nvim responsible. But after a time I tracked it to alacritty.

I have `set mouse=a` in nvim configuration. That way, when I use the mouse scroll wheel, it should actually scroll in nvim. This is what happens if I run nvim in other terminals, like urxvt.

With alacritty, I get an error message „tag stack empty“, when scrolling either up or down (doesn't matter). The same error message appears if I press ctrl+T.

Alacritty version should be current master. Is there anything I should check out?

Which operating system does the issue occur on?

Linux (gentoo, to be specific).

If on linux, are you using X11 or Wayland?

X11.

**Comment by sodiumjoe** [comment]
I wonder if it's related to #1000

**Comment by vorner** [comment]
I can't say for sure, but I don't think so. It's not any kind of history in nvim. It's scrolling in the edited file, just like you'd do with the arrow keys or ctrl+u/d. I think it is implemented completely in nvim. Only that the scroll wheel events are understood wrong by it somehow.

Is there something that prints these kinds of events in some rawish way? Like there's xev, but in a terminal? So I can compare what gets delivered to a program in urxvt and in alacritty?

**Comment by chrisduerr** [comment]
Is this an issue on the latest master? X11/i3 and I can not reproduce.

**Comment by vorner** [comment]
Yes, latest master, just re-installed now to make sure.

With some playing, I noticed this happens only when I have `set mouse=a` in my config. If I don't, it scrolls properly. But I'd really like to keep it in, because it allows me to move the cursor by clicking.

**Comment by chrisduerr** [comment]
If you don't have `set mouse=a` it will use faux scrolling instead of actual scrolling. If `set mouse=a` is set it sends the mouse events to vim for it to handle.

Make sure your `$TERM` is `xterm-256color` and you have the terminfo files for that installed.

**Comment by vorner** [comment]
That seems to have helped. I did have `$TERM` set to `xterm-256color`  and I do have the terminfo files installed. But when trying some other `$TERM` values, I discovered that it works with:

* `xterm-color`
* `screen`
* `screen-color`
* `screen-256color`

It does not work with:

* `xterm`
* `xterm-256color`

I'm attaching output of infocmp with one working and one not ‒ not that I'd understand what it says, but maybe it may show what triggers the problem on my system and if it's fault of alacritty or of the term definition.

```
$ infocmp xterm-256color
#       Reconstructed via infocmp from file: /etc/terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors,
        am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
        el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
        kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
        kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[<, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
        memu=\Em, oc=\E]104\007, op=\E[39;49m, rc=\E8,
        rep=%p1%c\E[%p2%{1}%-%db, rev=\E[7m, ri=\EM,
        rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B, rmam=\E[?7l,
        rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l, rmkx=\E[?1l\E>,
        rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
        smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?%[;0123456789]c,
        u9=\E[c, vpa=\E[%i%p1%dd,
```

```
 infocmp xterm-color
#       Reconstructed via infocmp from file: /etc/terminfo/x/xterm-color
xterm-color|nxterm|generic color xterm,
        am, km, mir, msgr, xenl,
        colors#8, cols#80, it#8, lines#24, ncv@, pairs#64,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, bold=\E[1m, clear=\E[H\E[2J, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        dch=\E[%p1%dP, dch1=\E[P, dl=\E[%p1%dM, dl1=\E[M, ed=\E[J,
        el=\E[K, enacs=\E)0, home=\E[H, ht=^I, hts=\EH, il=\E[%p1%dL,
        il1=\E[L, ind=\n,
        is2=\E[m\E[?7h\E[4l\E>\E7\E[r\E[?1;3;4;6l\E8, kbs=^H,
        kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kf1=\E[11~, kf10=\E[21~, kf11=\E[23~,
        kf12=\E[24~, kf13=\E[25~, kf14=\E[26~, kf15=\E[28~,
        kf16=\E[29~, kf17=\E[31~, kf18=\E[32~, kf19=\E[33~,
        kf2=\E[12~, kf20=\E[34~, kf3=\E[13~, kf4=\E[14~,
        kf5=\E[15~, kf6=\E[17~, kf7=\E[18~, kf8=\E[19~, kf9=\E[20~,
        kfnd=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kslt=\E[4~, meml=\El, memu=\Em, op=\E[m, rc=\E8, rev=\E[7m,
        ri=\EM, rmacs=^O, rmcup=\E[2J\E[?47l\E8, rmir=\E[4l,
        rmkx=\E[?1l\E>, rmso=\E[m, rmul=\E[m,
        rs2=\E[m\E[?7h\E[4l\E>\E7\E[r\E[?1;3;4;6l\E8, sc=\E7,
        setab=\E[4%p1%dm, setaf=\E[3%p1%dm, sgr0=\E[m, smacs=^N,
        smcup=\E7\E[?47h, smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m,
        smul=\E[4m, tbc=\E[3g, u6=\E[%i%d;%dR, u7=\E[6n,
        u8=\E[?1;2c, u9=\E[c,
```

**Comment by FliiFe** [comment]
I can confirm this issue. Built from master today

**Comment by chrisduerr** [comment]
Oh something that was mentioned in another issue: `set mouse=sgr` should work a lot better than `set mouse=a`. You should give that a try.

**Comment by FliiFe** [comment]
neovim doesn't recognise `sgr` as a correct value (throws an error), only `nvichar` are valid (see help page).
vim seems to has the exact same help page.

I'll try to fiddle around with this value

**Comment by FliiFe** [comment]
I found the issue you were talking about. You probably meant `set ttymouse=sgr`
Unfortunately, this option has been removed from neovim, as per the help page:

>The `ttymouse` option, for example, was removed from Nvim (mouse support
should work without it).

Note that scrolling works perfectly fine in vim, but not in neovim

**Comment by chrisduerr** [comment]
Yeah I was talking about `ttymouse`. However scrolling works perfectly fine for me in vim even with `set mouse=a`. Maybe there's something wrong with the config? Also please specify if you're running inside or outside of tmux and which `$TERM` is set.

**Comment by FliiFe** [comment]
The config I use is the exact same across vim and neovim. `$TERM` is `xterm-256color` and I tested inside tmux. I juste tested ouside tmux (though I kept the environment variables from tmux, tell me if that's an issue), and the issue is still present.

**Comment by chrisduerr** [comment]
I run mine outside of tmux with `$TERM=xterm-256color`. You could try it with an empty config and just running `:set mouse=a` after entering neovim. If the issue still persists I'm not sure what the difference between your setup and mine is.

**Comment by FliiFe** [comment]
Here is my exact neovim version
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.4
Compilation: /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-gcc -march=native -O1 -pipe -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.2.2-r1/work/neovim-0.2.2_build/config -I/var/tmp/portage/app-editors/neovim-0.2.2-r1/work/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.2.2-r1/work/neovim-0.2.2_build/src/nvim/auto -I/var/tmp/portage/app-edi```

**Comment by chrisduerr** [comment]
Got pretty much exactly the same there. Except for `LuaJIT 2.0.5` but that should be completely irrelevant to the issue. If it doesn't work with an empty config for you, you can also try my config: https://github.com/chrisduerr/dotfiles/blob/master/files/init.vim.

At this point I'd strongly assume it's unrelated to github and an issue with something like `$TERM` though. Are you running alacritty master or the scrollback branch? Please make sure you're running the latest master when testing this.

**Comment by chrisduerr** [comment]
I just checked @vorner's infocmp output and it's identical to mine, weird.

**Comment by FliiFe** [comment]
I was testing on master. I have not tried the scrollback branch. I'll send
my infocmp tomorrow

Le dim. 6 mai 2018 à 23:53, Christian Duerr <notifications@github.com> a
écrit :

**Comment by chrisduerr** [comment]
I might look into this a bit more tomorrow too. It seems like it should work when it does function correctly for me. Maybe I can add a few useful printlns to narrow down the issue. Kinda hard to troubleshoot when I can't reproduce it though.

**Comment by sbor23** [comment]
As @michaeltintiuc has found, `screen-256color` seems to fix the issue. Regardless if it's alacritty or gnome terminal.
So we must assume the problem lies within (neo)vim's inability in handling mouse input with `TERM=xterm-256color`?

Sorry I'm not knowledgeable how escape codes are treated through the stack of terminals, shells and application (like neovim).
But my experience with alacritty + default TERM `xterm-256color` + neovim (with mouse=a) was that mouse clicks or scrolling would result in gibberish written to the vim command-line, like this: `;15M28;15M28;27M28...`.
It probably entered command-line prompt because I use `nmap ; :`.

Starting with `neovim -u NORC` and `:set mouse=a` showed the same behavior as @vorner describes: scrolling triggers Ctrl+T.

Now with `screen-256color` my vim configs works, with `mouse=a` set.

**Comment by chrisduerr** [comment]
Can I get clarification if this is an issue only within tmux or outside of it too? I can't reproduce it without tmux.

I'm still not able to reproduce this and it might be related to the Alacritty/Neovim versions used. I run the latest Alacritty with Neovim 0.3.8 at the moment.

**Comment by sbor23** [comment]
This is without using tmux. 
`alacritty 0.3.3`

```
NVIM v0.3.8
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/x86_64-solus-linux-gcc -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/build/YPKG/root/neovim/build/neovim-0.3.8/build/config -I/home/build/YPKG/root/neovim/build/neovim-0.3.8/src -I/usr/include -I/home/build/YPKG/root/neovim/build/neovim-0.3.8/build/src/nvim/auto -I/home/build/YPKG/root/neovim/build/neovim-0.3.8/build/include
Übersetzt von build@paddedroom

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I'm on an updated Solus Linux if that matters.

**Comment by chrisduerr** [comment]
Have you tested the `alacritty` terminfo?

**Comment by sbor23** [comment]
`TERM=alacritty` seems to work just fine with my config and `mouse=a`!

**Comment by chrisduerr** [comment]
Please note that terms other than `alacritty` are not supported. When this issue was opened, I think Alacritty's terminfo didn't exist yet, but with having our own terminfo now, that should be used.

Of course pretending to support escape sequences which Alacritty does not support can lead to funky stuff happening, which is likely what's going on.

**Comment by sbor23** [comment]
Makes sense, thanks for your explanation.
I just realized that the Solus package does not place the terminfo files in the correct location, hence `alacritty` couldn't be used as the default.
Submitting a PR for this in the Solus repo right now.
