### ISSUE TITLE
Weird font rendering issues

### ISSUE THREAD

**Issue by DorianGray** [jwilm/alacritty#1229]
Linux, xorg, awesomewm. kernel 4.13.13 on ubuntu

So...this is weird. If I start alacritty from the shell, fonts render incorrectly in the session. If I'm running it from somewhere that already has an xorg session, like from the already misrendered alacritty, it renders correctly.

[example](https://imgur.com/a/wj5r6)

**Comment by DorianGray** [comment]
...anyone have any ideas? I've been following this project for over a year but haven't been able to use it yet because of silly rendering issues.

**Comment by chrisduerr** [comment]
Probably an issue with font fallback. Improvements to how alacritty currently does this have been proposed in #957.

**Comment by chrisduerr** [comment]
This seems to be an issue with fontconfig fallback. This is tracked in #1560.
