### ISSUE TITLE
Config for font.offset and font.glyph_offset no longer works

### ISSUE THREAD

**Issue by bugeats** [jwilm/alacritty#1232]
macOS 10.13.3 using this [alacritty.yml](https://github.com/bugeats/dotfiles/blob/master/src/config/alacritty/alacritty.yml)

I just recompiled from HEAD and my font rendering has changed. It appears that `font.offset` and `font.glyph_offset` config values are no longer being applied. I'm using the same DejaVu Sans Mono typeface that I always have been.

<img width="706" alt="screen shot 2018-04-05 at 3 37 47 pm" src="https://user-images.githubusercontent.com/33055/38395335-632f4690-38e7-11e8-9e96-a7f43c910d23.png">

On the left is iTerm 2 displaying the fonts the way I expect. On the right is Alacritty. As you can see, Alacritty has short line heights and column widths. I originally added the `font.offset` config in order to force Alacritty to match iTerm 2, but now it appears to have no effect whatsoever. I tried modifying these values to extremes -- still no change.

I suspect there's been a regression in font rendering.

**Comment by chrisduerr** [comment]
When you launch `alacritty` from a different terminal emulator you will probably see that there were some config changes which swapped the `glyph_offset` and `offset` to integers instead of floating point numbers, that's probably the issue here.

**Comment by bugeats** [comment]
Yep that was it. Looks like the example config files have been updated too. I guess we're done here, thanks.
