### ISSUE TITLE
Allow changing scrollback history size at runtime

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1235]
It should be possible to use `live-config-reload` to change the scrollback history size at runtime. This should allow both shrinking and growing the number of  scrollback lines available.

I can't quite estimate how complex this change would be because it's possible that a lot of structs would need to be updated. Maybe @jwilm knows if this should be easy to implement?

If this is easy to implement it could be added to the scrollback project, otherwise it's probably fine to do this after scrollback has been merged because it should not be relevant for most users.

**Comment by nixpulvis** [comment]
:fireworks:
