### ISSUE TITLE
'cp: /usr/share/fish/vendor_completions.d/alacritty.fish: No such file or directory' on macOS

### ISSUE THREAD

**Issue by ji-zhou** [jwilm/alacritty#1237]
Which operating system does the issue occur on?
macOS 10.13.4 (17E199)

If on linux, are you using X11 or Wayland?
No

---

Read from https://github.com/jwilm/alacritty#fish, but I can not install the completions for fish that installed by `brew install fish`, on the macOS, there is no directory `/usr/share/fish/vendor_completions.d` default.

Users can see the completion directories by `echo $fish_complete_path`, and I think the `$__fish_datadir/vendor_completions.d` is for `/usr/share/fish/vendor_completions.d`

I can install the completions for fish by `sudo cp alacritty-completions.fish $__fish_datadir/vendor_completions.d/alacritty.fish`.

Thanks!

**Comment by chrisduerr** [comment]
Feel free to change the command in the `README` to the one you've used if that works. Maybe there's a linux fish user who can test this too, but it looks like it should work.

**Comment by ji-zhou** [comment]
@chrisduerr I have created a [new pull request](https://github.com/jwilm/alacritty/pull/1283) and this is my first PR😊.

**Comment by chrisduerr** [comment]
Thanks!
