### ISSUE TITLE
Scrollback: `reset` Still Allows Scrollback

### ISSUE THREAD

**Issue by theGeekPirate** [jwilm/alacritty#1242]
System: X11 on Arch Linux

Using the latest scrollback branch, `reset` still allows me to scroll up afterwards, assuming you initially activate the scrollback ability by entering enough text vertically.

On a related note, `clear` may also need to be looked at, but I'm unsure if there's a spec for it, as both `xterm` and `urxvt` handle it differently. On `urxvt`, I'm able to scroll back up assuming I've filled the vertical space enough to allow scrolling, while `xterm` seems to never allow me to scroll back, regardless of the amount of text entered.

**Comment by jwilm** [comment]
Thanks for the report!
