### ISSUE TITLE
Compilation error on openbsd 6.3-current

### ISSUE THREAD

**Issue by Superpat** [jwilm/alacritty#1247]
Which operating system does the issue occur on?
OpenBSD 6.3-current

[errors.txt](https://github.com/jwilm/alacritty/files/1908867/errors.txt)

Just linking this here, I'll come back when I have time to investigate more. But if somebody wants to take a look it would be appreciated.

**Comment by jwilm** [comment]
What were the steps you took to acquire the source and to build? What version of the rust compiler are you using? (`rustc -V` from alacritty project root).

**Comment by Superpat** [comment]
Oh yes of course, forgot to give that info.
rust 1.25.0
I simply git cloned the latest master and ran cargo build

**Comment by jschx** [comment]
I'm getting the following from `cargo install --git https://github.com/jwilm/alacritty`:

[errors.txt](https://github.com/jwilm/alacritty/files/1911547/errors.txt)

I'm also on 6.3-current with rustc 1.25.0.

**Comment by Superpat** [comment]
I get exactly the same error message as @jschx

**Comment by Superpat** [comment]
I thought it could be related to this, but the example c program to prove the existence of the constant works and the libc src/unix/netbsdlike/mod.rs has the proper constant defined. https://github.com/rust-lang/libc/issues/292

**Comment by jwilm** [comment]
What happens if you `cargo update -p libc` before compiling?

**Comment by jschx** [comment]
Same output with and without `cargo update -p libc`. Using `cargo build` on latest master this time.

[errors.txt](https://github.com/jwilm/alacritty/files/1913297/errors.txt)

**Comment by wmoxam** [comment]
I've got the same problem. It's because a new version of libc has not been released since https://github.com/rust-lang/libc/commit/22d078e6782a1719a9b19c900c12b66d3d099700 was added.

libc 0.2.41 should fix the issue once its released

**Comment by kpcyrd** [comment]
I've added alacritty to [openbsd.rs](https://openbsd.rs/#/builders/29). It's going to build weekly and on pushes to master, it should become green after the next libc release.

**Comment by chrisduerr** [comment]
Since it seems like Alacritty builds on FreeBSD and this issue has been around without update for a while, I'm going to close it as resolved.

If there should still be issues with Alacritty even with an updated libc, please let me know and I'll re-open this issue.
