### ISSUE TITLE
Slow rendering using Mesa

### ISSUE THREAD

**Issue by RX14** [jwilm/alacritty#125]
Using `time find /usr` benchmark:

My current terminal, Terminology: `find /usr  0.41s user 0.90s system 63% cpu 2.081 total`

Alacritty: `find /usr  0.58s user 0.89s system 5% cpu 28.101 total`

I'm using the same font, arch linux using the AMD open source drivers with a radeon HD7850 GPU. I observe Terminology using 100% cpu and Alacritty using about 7%. Neither program seems to bottleneck any part of the GPU when observed with `radeontop`. This should be a release build ([`cargo build --release`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alacritty-git)).

```
$ find /usr | wc -c
30957177
```

**Comment by dhedberg** [comment]
I get these numbers for gnome-terminal:
`real	0m3.306s
user	0m0.720s
sys	0m1.040s`

And these for alacritty:
`real    0m32.088s
user    0m0.772s
sys     0m1.116s`

This is with an i7-4510U and the integrated GPU. If I understand correctly though, gnome-terminal "cheats" a bit by simply capping the frame rate and throwing away the intermediate output.

Does Terminology do something similar? Does alacritty? Should it?

**Comment by 0X1A** [comment]
I'm also having similar results where `alacritty` is significantly slower than `gnome-terminal` on an Intel HD 530, for example
```
time find /usr

# gnome-terminal
real	0m1.492s
user	0m0.183s
sys	0m0.469s

# alacritty
real    0m24.272s
user    0m0.774s
sys     0m1.525s
```
This is even after I've run the command twice. This issue and #110 might be related. As an aside, I do not have this issue on a desktop with a GTX 970 and Nvidia proprietary drivers 375.26

**Comment by accaldwell** [comment]
Mesa appears to be the common factor here. I'm running Arch Linux, Mesa 13.0.3 on Intel HD Graphics 4400 (Haswell iGPU).

Stats from time find /usr in fish shell:

terminator: 0.69 user 1.26 system 0:04.48 elapsed 43% CPU
alacritty: 1.09 user 1.71 system 0:49.33 elapsed 5% CPU

**Comment by shosti** [comment]
I'll just chime in mine (both for the second run):

```
time find /usr

# urxvt
real	0m2.235s
user	0m0.737s
sys	0m1.463s

# alacritty
real    1m0.506s
user    0m1.053s
sys     0m1.910s
```

This is on a Core i5-4278U (with built-in graphics and the open source driver), Mesa 13.0.3.

**Comment by spytheman** [comment]
Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Ivybridge Desktop  (0x162)
    Version: 11.2.0
    Accelerated: yes
    Video memory: 1536MB
    OpenGL vendor string: Intel Open Source Technology Center
    OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Desktop 
    OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.0
    OpenGL core profile shading language version string: 3.30


find /usr | wc -c
53525793

time find /usr/ > /dev/null 
real    0m0.958s
user    0m0.436s
sys     0m0.516s

time find /usr/

# stterm
real    0m2.381s
user    0m1.046s
sys     0m1.248s

# terminology
real    0m2.556s
user    0m1.114s
sys     0m1.138s

# konsole
real    0m4.855s
user    0m1.130s
sys     0m1.150s

# alacritty
real    1m6.198s
user    0m1.192s
sys     0m1.704s

**Comment by Muffindrake** [comment]
> time -p find /usr

st
    real 2.56
    user 0.90
    sys 2.06

alacritty
    real 89.50
    user 5.46
    sys 6.61

That's more than a factor of 30 slower. What a piece of tra-

primusrun alacritty (using nvidia's opengl implementation explicitly with my dedicated card, rather than the integrated intel one, which uses mesa's)
    real 2.77
    user 0.87
    sys 2.20

[Intel HD 530](https://gist.github.com/Muffindrake/9999f10dc0f74f78c486f1bcb6b77f3b) / [GTX 950M](https://gist.github.com/Muffindrake/3de125e27a4265cdfbc712071f9b45f0) (glxinfo)

Linux 4.9.0

(just adding my findings here)

**Comment by RX14** [comment]
Looks pretty clear to me that mesa is the culprit here.

**Comment by ordian** [comment]
Not sure whether it's relevant, but here is the (part of) output of
```
LD_DEBUG=libs ./target/debug/alacritty 2>&1 | rg error
```

```
315:     28965: /usr/lib/libEGL.so.1: error: symbol lookup error: undefined symbol: eglCreatePlatformPixmapSurfaceEXT (fatal)
316:     28965: /usr/lib/libEGL.so.1: error: symbol lookup error: undefined symbol: eglCreatePlatformWindowSurfaceEXT (fatal)
317:     28965: /usr/lib/libEGL.so.1: error: symbol lookup error: undefined symbol: eglGetPlatformDisplayEXT (fatal)
```
system info at #235

**Comment by kilbith** [comment]
```Bash
time seq -f 'blah blah %g' 100000
```

Mesa 13.0.3 - Intel HD 4400

```Ruby
Alacritty
real   0m3,314s
user   0m0,153s
sys    0m0,200s

URxvt
real   0m0,334s
user   0m0,117s
sys    0m0,220s
```

**Comment by jonhoo** [comment]
Same command as @kilbith, Intel HD 5500, same Mesa version.

URxvt: 19ms (97% CPU)
Alacritty: 321ms (6% CPU)
URxvt + tmux: 209ms (10% CPU)
Alacritty + tmux: 207ms (10% CPU)

**Comment by jwilm** [comment]
I've pushed a patch that addresses the biggest cause of slowness on Mesa. If anyone is feeling adventurous, I would appreciate some feedback on perf in #410.

**Comment by jwilm** [comment]
Going to close this since feedback in #410 is very positive.
