### ISSUE TITLE
Dynamic title don't display title of running app in BSPWM.

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [jwilm/alacritty#1251]
Expected behavior:  Title is Newsboat/Neomutt in title. Actual behavior: Title is Alacritty. Why is this?.

**Comment by chrisduerr** [comment]
Probably because you're running Newsboat/Neomutt inside of alacritty?

**Comment by eyvindbjartiandersen** [comment]
Yes I want to display the titles of the apps running in Alacritty. How would that be done?.

**Comment by chrisduerr** [comment]
Oh okay, I don't think that's currently supported. I'm not sure how other terminal emulators do this.

**Comment by eyvindbjartiandersen** [comment]
I use ZSH and export the XTERM title in a precmd. I can get path, but not the title. I've set it so the title should be displayed in the XTERM export command. This doesn't work.

**Comment by chrisduerr** [comment]
I'm not sure exactly how it works because I don't make use of it. But alacritty does have dynamic title support (in theory).

This is done here: https://github.com/jwilm/alacritty/blob/master/src/ansi.rs#L754-L763

I'm not sure what the issue might be for you.

**Comment by difarem** [comment]
Seems like alacritty doesn't *actually* set the window title dynamically when using the `-e` flag.

**Comment by eyvindbjartiandersen** [comment]
Bump. 

Weechat sets the title correctly: https://i.imgur.com/b95rUnA.png

Newsboat don't: https://i.imgur.com/b95rUnA.png

Is this Alacritty or Newsboat or something else?.

**Comment by chrisduerr** [comment]
If weechat does it correctly, it sounds to me like Alacritty supports it.

Does this work in any other terminal emulator? If newsboat doesn't set the title manually, Alacritty will not do so automatically. The dynamic window title just means that when the escape sequence for window title change is issued, that it is not ignored. The application still needs to send it.

**Comment by chrisduerr** [comment]
Closing this since it's likely a Newsboat issue, if there's any indication that this is untrue, please let me know and I'll re-open.

**Comment by cata0309** [comment]
It's not working on other apps, it doesn't show the commands that are running in Alacritty

**Comment by chrisduerr** [comment]
It's all up to the application actually sending the escape. If the application isn't sending it, we won't be able to display it.
