### ISSUE TITLE
Full screen mode ?

### ISSUE THREAD

**Issue by hiimdoublej** [jwilm/alacritty#1252]
A full screen mode would suite programmers with a habit like mine,
where my terminal is always full screen and I use tmux to arrange the panes myself.
Do we have a timeline for full screen mode implementation as of now ? Thanks

**Comment by sodiumjoe** [comment]
I think it depends on which platform, but for macos, it should be available in https://github.com/tomaka/winit/pull/465, after it propagates up through glutin.

**Comment by sodiumjoe** [comment]
I think this is actually a dupe of #34

**Comment by chrisduerr** [comment]
Closing as duplicate of #34.

**Comment by monokrome** [comment]
This issue still exists. MacOS menubar doesn't work at all in alacritty w/ fullscreen @chrisduerr @sodiumjoe
