### ISSUE TITLE
Error compiling on macOS

### ISSUE THREAD

**Issue by BastienAr** [jwilm/alacritty#1253]
macOS 10.13.3
rustc 1.25.0 (84203cac6 2018-03-25)

```shell
cargo build --release --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error inflating zlib stream; class=Zlib (5)
```

Did I forgot something ?

**Comment by jwilm** [comment]
This sounds like it was a temporary issue. Either that or your Rust installation is broken somehow. In either case, it's not something we can help you with.

**Comment by BastienAr** [comment]
Ok thanks, I will investigate my Rust install
