### ISSUE TITLE
scrollback: first character of line always bold

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#1259]
Which operating system does the issue occur on?
manjaro 4.14.34-1-MANJARO
If on linux, are you using X11 or Wayland?
Linux using x11
xorg-server 1.19.6+13+gd0d1a694f-2

This seems to be a bug of the scrollback branch. I can reproduce on 0d568180761d7da56e756762d5f4b1555eea6a7f

The first character of a new line seems to always be printed as bold.
![alacritty](https://user-images.githubusercontent.com/476013/39083191-d20d4fc8-4560-11e8-8667-ef9ce6996f96.png)

EDIT: for the record: I could not reproduce this on the master branch

**Comment by chrisduerr** [comment]
It seems like it's not actually bold but some other rendering issue:

![Bug](https://imgur.com/a/R9qrlIy)

**Comment by matthiaskrgr** [comment]
Maybe what happens is that the first character is displayed twice on the same place so that transparent pixels gain more saturation...

**Comment by matthiaskrgr** [comment]
I'm closing this since the PR has been merged.

**Comment by chrisduerr** [comment]
Thanks! Unfortunately github can't close issues when the PRs haven't been merged into master yet.
