### ISSUE TITLE
nightly-2016-12-16 had a bug that completely broke it on i686; patched 24 days ago

### ISSUE THREAD

**Issue by i336** [jwilm/alacritty#126]
Relevant notes here: https://github.com/rust-lang/rust/issues/38898#issuecomment-271043893

This means that the pinned Rust nightly does not build on i686. There's also a recent bug showing the exact same exception on ppc64, unsure if that's related.

The i686 machine I wanted to build on is unlikely to run Alacritty so FWIW I don't need this, I'm just reporting it for completeness.

**Comment by jwilm** [comment]
Thanks for the report :)

**Comment by arzeth** [comment]
I use Arch Linux i686.
```nightly-2016-12-16``` could not compile package ```dtoa``` (```error: internal compiler error: unexpected panic```), so I have had to use ```nightly-2016-12-19``` to successfully compile alacritty (with its dependencies).
top, htop (has little graphical bug) and neovim work fine, no segfaults/etc.

**Comment by i336** [comment]
"Little graphical bug"s in anything are probably interesting, feel free to upload a screenshot to a new issue. (No problem that you mentioned it here, but the new issue could have an appropriate bug title.)

Perhaps Alacritty could bump up to using `2016-12-19`, in order to resolve this so i686 can build without incident. And maybe occasional "where's it at nowadays" in a 32-bit VM would be useful?

**Comment by jwilm** [comment]
I think we should be able to drop the nightly pinning entirely per #196. Just haven't had time to update docs and test it.
