### ISSUE TITLE
Implement ctrl+shift+u unicode behaviour

### ISSUE THREAD

**Issue by towc** [jwilm/alacritty#1261]
In previous terminals I've used, as well as browsers and other text inputs, by using `ctrl+shift+u` you could enter a mode that lets you type the charcode for a unicode char, and would then transform it to that character. Any plans to implement this in alacritty? Right now it seems to just ignore the `ctrl+shift+u`.

Which operating system does the issue occur on?
Ubuntu

If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment]
This is a dubplicate of #866, would love to have this but it might be more complicated than expected.
