### ISSUE TITLE
Support scancode-based key bindings

### ISSUE THREAD

**Issue by yurikhan** [jwilm/alacritty#1265]
Which operating system does the issue occur on? GNU/Linux

If on linux, are you using X11 or Wayland? X11

Some keyboards have dedicated Undo/Cut/Copy/Paste keys. It would be nice to be able to bind them.

(There are multiple possible USB HID usage codes for these keys, but after kernel and XKB processing they boil down to the same keycodes.)

`alacritty --print-events` generates the following output:

```
glutin event: KeyboardInput(Pressed, 139, None, , None)
glutin event: KeyboardInput(Released, 139, None, , None)
glutin event: KeyboardInput(Pressed, 145, None, , None)
glutin event: KeyboardInput(Released, 145, None, , None)
glutin event: KeyboardInput(Pressed, 141, None, , None)
glutin event: KeyboardInput(Released, 141, None, , None)
glutin event: KeyboardInput(Pressed, 143, None, , None)
glutin event: KeyboardInput(Released, 143, None, , None)
```

I understand that one way to support these keys would be to teach glutin to decode their codes, but maybe it makes sense to implement raw keycode-based bindings in Alacritty?

**Comment by jwilm** [comment]
> maybe it makes sense to implement raw keycode-based bindings in Alacritty?

Yes! We would like to support scan code based key bindings. I thought we had an issue for it already, but I can't seem to find it. Guess I'll make this the canonical issue.

**Comment by chrisduerr** [comment]
Got an initial implementation for this here: #1306. Any testing and feedback is appreciated. :)

**Comment by yurikhan** [comment]
That seems to work.

**Comment by gtarsia** [comment]
@chrisduerr don't mean to clutter this thread, but gigantic thanks, I had some very annoying behaviour on a japanese mac keyboard with the Underline key that wasn't mapped to anything.
