### ISSUE TITLE
Passing parameters to command specified in -e results in "spawn() failed"

### ISSUE THREAD

**Issue by craftyguy** [jwilm/alacritty#1266]
> Which operating system does the issue occur on?

Arch Linux

> If on linux, are you using X11 or Wayland?

X11

When using the `-e` option with Alacritty, if you pass any parameters to the command you want to execute then alacritty fails with the following error:

```
$ alacritty -e "/bin/bash -i"
Command::spawn() failed: No such file or directory (os error 2)
```

In the example above, if I remove the `-i`, then alacritty works as expected. I am reporting this because the example above works as expected in other terminal emulators (e.g. termite).

**Comment by craftyguy** [comment]
That seems to result in a new error:

```
alacritty -e /bin/bash -- -i
Event loop exitting due to error: Input/output error (os error 5) [src/event_loop.rs:400]
```

**Comment by jwilm** [comment]
The argument immediately after `-e` is the program to run, and all subsequent arguments are passed to that program. This is working as intended.

**Comment by FlyingWombat** [comment]
I'm getting a similar error:  
```
alacritty -e "$SHELL -c 'ls && $SHELL'"  # doesn't work
alacritty -e $SHELL -c 'ls && $SHELL'  # works
```
Is this a problem with alacritty's parser?

**Comment by chrisduerr** [comment]
The problem is that the first parameter passed to `-e` is used as the program. This is intentional.

You're passing `$SHELL -c 'ls && $SHELL'` as the first parameter, which is not a valid executable. Excessive quoting in bash can have impact on the semantics and should be done with caution.

I'm not familiar with the internals of XTerm, but I'd say that it's incorrect to accept that parameter in this case.

**Comment by FlyingWombat** [comment]
OK, I understand now.  
I didn't get that this meant no parsing would be done, if it were quoted.

**Comment by chrisduerr** [comment]
That seems like a good way to do it. Though you could of course put it in a separate file if you want to make execution from CLI a little easier.

**Comment by TotalKrill** [comment]
This does however leave us with another problem i believe, since there is no way to run multiple commands after eachother or use redirections or piping. For example is not possible.

    alacritty --hold -e echo "hello world"; echo "this is in the wrong terminal, and will be executed after user quites the spawned one"
