### ISSUE TITLE
resizing size-aware scripts causes crash

### ISSUE THREAD

**Issue by d3rrial** [jwilm/alacritty#127]
This script crashes alacritty when the window is resized, whereas it simply resizes when executed in urxvt:
```bash
#!/bin/bash
echo -e "\033[2J\033[?25l"; R=`tput lines` C=`tput cols`;: $[R--] ; while true 
do ( e=echo\ -e s=sleep j=$[RANDOM%C] d=$[RANDOM%R];for i in `eval $e {1..$R}`;
do c=`printf '\\\\0%o' $[RANDOM%57+33]` ### http://bruxy.regnet.cz/web/linux ###
$e "\033[$[i-1];${j}H\033[32m$c\033[$i;${j}H\033[37m"$c; $s 0.1;if [ $i -ge $d ]
then $e "\033[$[i-d];${j}H ";fi;done;for i in `eval $e {$[i-d]..$R}`; #[mat!rix]
do echo -e "\033[$i;${j}f ";$s 0.1;done)& sleep 0.05;done #(c) 2011 -- [ BruXy ]
```

While urxvt produces undefined behavior, it doesn't completely crash at least. Maybe build a graceful handler for this?

Possible duplicate of #88

**Comment by jwilm** [comment]
Thanks for filing the issue!

What's with the URL in the middle of that command?

**Comment by d3rrial** [comment]
It's the creators signature. You can remove it and it works just fine.

It's that popular matrix effect for bash

**Comment by jwilm** [comment]
hah, nifty. I'll try it out later.

**Comment by d3rrial** [comment]
99% sure that this is a duplicate of #12 
Closed.
