### ISSUE TITLE
problem with fonts after libfontconfig update

### ISSUE THREAD

**Issue by doubleloop** [jwilm/alacritty#1270]
After system update (`debian buster`), in particular package `libfontconfig1:amd64 (2.12.6-0.1 -> 2.13.0-4)` the font from `alacritty.yml` file (`monospace`) stopped working, also I get some logs:
```
Fontconfig warning: line 5: unknown element "its:rules"
Fontconfig warning: line 6: unknown element "its:translateRule"
Fontconfig error: line 6: invalid attribute 'translate'
Fontconfig error: line 6: invalid attribute 'selector'
Fontconfig error: line 7: invalid attribute 'xmlns:its'
Fontconfig error: line 7: invalid attribute 'version'
Fontconfig warning: line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
...
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load default config file
```
I found simmilar issue for google-chrome and based on this [post](https://bugs.chromium.org/p/chromium/issues/detail?id=829890#c4) it seems that
> the latest version of fontconfig changes the config format in a backwards-incompatible way

**Comment by chrisduerr** [comment]
I think this is an issue with your system, not with alacritty.

**Comment by jwilm** [comment]
I agree with @chrisduerr; it sounds like the fontconfig update broke its config file parsing in some way.

The reason `monospace` stopped working is that the `monospace` alias is configured in one of those XML files that fontconfig is failing to parse.

**Comment by doubleloop** [comment]
Hmm, `sudo apt install libfontconfig1-dev; cargo clean; cargo build --release` solved the issue. The configs in `/etc/fonts/conf.d` are correct according to the new format so from the system point everything is as expected.

As a side note, I am wondering why compilation did not fail when `libfontconfig1-dev` package was missing. I tested that after I remove this package and do `cargo clean; cargo build --release` alacritty is compiled without error (but again with font issue). Is the old libfontconfig hardcoded somewhere as a fallback? I would expect that compilation will fail rather then building with dependency not matching the system version.

**Comment by OliverUv** [comment]
I was also bitten by this issue. Thanks to @doubleloop for finding the solution.

**Comment by tv42** [comment]
I'm a rust newbie but it looks like servo-fontconfig-sys at https://github.com/servo/libfontconfig embeds a version of the C fontconfig library that's very stale. Could that be it?

I can confirm that installing libfontconfig1-dev and rebuilding fixed my fontconfig errors and slow startup.
