### ISSUE TITLE
a way to disable the mouse style replacement

### ISSUE THREAD

**Issue by NikkyAI** [jwilm/alacritty#1274]
Which operating system does the issue occur on?
manjaro

If on linux, are you using X11 or Wayland?
X11

i am not sure if i overlooked this in the autogenerated config or if there is a issue for this already (i did not find one)

alacritty replaces the mouse mounter style ![original](https://i.imgur.com/93cSc15.png) to ![fake](https://i.imgur.com/qrY9qo1.png)

i hope this is not a technical limitation or i just overlooked the setting

**Comment by chrisduerr** [comment]
Mouse cursors in X.Org work in mysterious ways, make sure you're not confusing your GTK with your X.Org mouse cursor. Also make sure that the cursors in use are all correct, by default alacritty should use the I-Beam cursor, not the arrow.

**Comment by NikkyAI** [comment]
i checked and apparently my theme does not specifically defines one https://i.imgur.com/GYGJE7A.png
once i use a theme where it is define the I beam is displayed properly

**Comment by chrisduerr** [comment]
This is not an alacritty issue but a problem with your setup.

**Comment by NikkyAI** [comment]
a restart fixed it apparently
