### ISSUE TITLE
Feature request: Static prompt

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [jwilm/alacritty#1275]
Is something like the gif possible: https://doughellmann.com/blog/wp-content/uploads/2018/04/demo.gif

**Comment by siiptuo** [comment]
Isn't it already possible by using [demoshell](https://github.com/dhellmann/demoshell) like in the gif? Alacritty is a terminal emulator that can be used with any shell.

**Comment by jwilm** [comment]
Sounds like this should already work.

**Comment by NickeZ** [comment]
I think you just mixed up what a terminal emulator is and what a shell is. Alacritty would not be the right place to implement this. This should be done in the shell, like demoshell does it.

**Comment by eyvindbjartiandersen** [comment]
You are right. It wasn't thought through. Thanks for pointing it out.
