### ISSUE TITLE
Cursors Beam and Underline revert to Block during grab and drag or lose focus

### ISSUE THREAD

**Issue by Sas-18** [jwilm/alacritty#1277]
Linux Mint 18.3 Sylvia, up to date.
X11 with Xinerama, with Nvidia binary driver.
No Composite extension, No Wayland.

Alacritty cloned from git Master, with src/window.rs line 211 edited to disable transparency.

Was trying the other cursors to see what they looked like, and noticed while dragging the Alacritty window, the cursor changed to a Block. Once dragging stopped, the desired cursor shape came back.

**Comment by siiptuo** [comment]
#1079 should allow changing this behavior.

**Comment by Sas-18** [comment]
@siiptuo thank you; that option was not in my config file and I did not find that thread when searching earlier. Cheers!
