### ISSUE TITLE
keyboard bind to open alacritty

### ISSUE THREAD

**Issue by shoober420** [jwilm/alacritty#1278]
Using Wayland/Weston, there is no keybind to launch a terminal. In X11, there are different possible ways to use keybinds to launch your terminal.

Why I ask this be added, is that since Weston has no keybind to launch a terminal, you have to open a terminal via the terminal icon on the taskbar. I personally go for minimalism, so I would prefer to run Weston without a taskbar, and spawn terminals with keybinds like I do in X11.

**Comment by chrisduerr** [comment]
This is not an issue with alacritty. If you need to set shortcuts for the applications you want to execute, you have to do that in Weston, alacritty can't do anything about it.

If I misunderstood your question, please re-open this issue.

**Comment by shoober420** [comment]
To my knowledge, weston cannot set key binds to launch programs, which is why I asked if this feature could be implemented. Other wayland compositors can do this, but not weston. The only Wayland compositor that I've come across that supports EGLStreams is weston. Since I have an NVIDIA card, I need a compositor that supports EGLStreams.

As a workaround so I can keep my desktop minimal, I want to remove the task bar and launch alacritty through a keybind so I don't depend on the taskbar to launch it. I only asked because I saw there are other keybinds in the alacritty.yml file.

**Comment by chrisduerr** [comment]
This is an issue with weston, alacritty can't do anything about that.
