### ISSUE TITLE
Tmux status line last character appears on on next line

### ISSUE THREAD

**Issue by Thermatix** [jwilm/alacritty#1288]
Currently running MacOS High Sierra, version 10.13.3.

I'm using alacritty built from source into an `.app` .

Now normally this would be an issue for `Tmux` itself however this Issue only appears on Alacritty, I've added the character `|` to the end of my Tmux status line so It doesn't bother me too much. 
Without `|` the last character printed gets moved to the beginning of the last line, so you might see a number if you're using a date for example, and no, adding whitespace doesn't stop the last character from getting moved.

Here's a screenshot example (look at the first character next to the buffer tab): 

![Tmux Status line ](https://image.ibb.co/h23cpS/Tmux_Status_line.png)

P.s. I'd like to add, Alacritty is Sooooo much faster then Iterm2 and it's fixed a super aggravating, annoying problem where the powerline characters didn't line up properly, so just for this THANK YOU!

**Comment by jwilm** [comment]
This is an issue with how unicode widths are calculated. Closing in favor of #1295.
