### ISSUE TITLE
macOS: Ignore first click on unfocused windows

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jwilm/alacritty#1291]
It would be really nice of Alacritty to ignore the first click on an unfocused window on macOS. This is also the behavior that iTerm2 exhibits. The reason is mainly that it's really easy to cause an accidental selection (and possibly copy to clipboard) when switching focus using a mouse.

I've already had some close calls where I copied an identifier or URL from somewhere and didn't notice making an accidental selection upon window switching and pasted garbage into a shell. Luckily the garbage hasn't (yet) contained any harmful shell commands, but seems like only a matter of time since a lot of the stuff in terminal windows is in fact shell commands you may not want to repeat.

**Comment by jwilm** [comment]
Fantastic suggestion.

**Comment by chrisduerr** [comment]
This might also fix #47? I think this should only be applied on macos though, I wouldn't want this behavior on linux.

**Comment by chrisduerr** [comment]
If anyone wants to implement this, I believe this might just be enough:
```rust
MouseInput { state, button, modifiers, .. } => {
    if !cfg!(target_os = "macos") || *window_is_focused {
        *hide_cursor = false;
        processor.mouse_input(state, button, modifiers);
        processor.ctx.terminal.dirty = true;
    }
},
```
https://github.com/jwilm/alacritty/blob/master/src/event.rs#L303
By leaving out the `cfg!` part this could be applied to any target. I'm not sure how this works on linux with DEs like GNOME/KDE and other terminal emulators though.

If there are any problems feel free to ping me here or on irc (UndeadLeech).

**Comment by felippemr** [comment]
Hey @chrisduerr, is it still relevant?

**Comment by chrisduerr** [comment]
Yes it is, in fact it even has come up in a recent issue (#1354).

It would probably make sense to introduce this as an option (behind a config setting) on all platforms.

**Comment by felippemr** [comment]
Why an option? It seems more like a bug than a feature.

**Comment by chrisduerr** [comment]
Because it depends on the system. There are many linux window managers where the first click on a window should actually register with the window.

**Comment by felippemr** [comment]
How can I ` introduce this as an option (behind a config setting) on all platforms` @chrisduerr ?

**Comment by chrisduerr** [comment]
You have to add a boolean field with documenation about what it does to the `Config` struct here:
https://github.com/jwilm/alacritty/blob/master/src/config.rs#L314

Make sure to also annotate it with `#[serde(default, deserialize_with = "failure_default")]` to make sure that deserialization will never fail and `false` will be provided as a default value should anything go wrong.

Then you should be able to access the `config` struct from within the code and just access it with `config.whatever_name_you_choose()`. To be able to do so you'll first have to create a method in the `impl Config` section though, but the other fields should help here.

The config struct should be accessible from most parts of the code, if it is not already, you might have to pass it around a bit. If you have any more questions, feel free to ask. If you have any specific code you need help with, you can also open a WIP PR and I'm happy to take a look and help out. :)

**Comment by felippemr** [comment]
Nice! Can you assign this task to me? I'll give it a try later this week.

**Comment by chrisduerr** [comment]
I've assigned it to myself because I still can't seem to assign to anyone other than jwilm, me or the creator of the issue. But that should be fine. :)

Thanks for looking into this!

**Comment by felippemr** [comment]
@chrisduerr would it be something like https://github.com/jwilm/alacritty/pull/1384 ?

**Comment by chrisduerr** [comment]
@felippemr Yeah that's looking great! Thanks for working on this.
