### ISSUE TITLE
Guide to uninstall alacritty completely

### ISSUE THREAD

**Issue by surmish** [jwilm/alacritty#1296]
Which operating system does the issue occur on?
arch-linux on a Thinkpad x230i (very old laptop)

If on linux, are you using X11 or Wayland?
wayland (using gnome3)

I don't have a gpu and the laptop I am using is quite old too. There are some bugs I can't fix. E.g. In Neovim, button press for a long time only registers as 1 press. This is terrible for scrolling. And it seems like an open bug as reported here: https://github.com/jwilm/alacritty/issues/1062 
I wish to uninstall this for the time being. This seems like an otherwise great project.

pacman uninstall doesn't work because this package was installed outside of it.

**Comment by chrisduerr** [comment]
That really depends on the method of installation, but it really should be no different from doing all the installation steps in reverse. Everything copied, has to be removed. That should be it. There shouldn't be anything special involved.

**Comment by surmish** [comment]
Okay. You can close the bug. Thank you.

**Comment by chrisduerr** [comment]
If you have any idea how to help users, please bring it forward. But right now there really shouldn't be any "magic" required. :)

We only have the binary, the completions and at runtime we only create the config file. That's all that needs to be removed.
