### ISSUE TITLE
archlinux input method iusse

### ISSUE THREAD

**Issue by leihuxi** [jwilm/alacritty#1297]
Which operating system does the issue occur on?
Archlinux
If on linux, are you using X11 or Wayland?

x11

After upgrade ,  I cant use my input method.

**Comment by chrisduerr** [comment]
Could you elaborate a bit? I'm not quite sure what you are talking about.

**Comment by leihuxi** [comment]
sorry, english is not my mother language
I mean when I upgrade the alacritty, my fcitx-sogoupinyin not working.

**Comment by francesca64** [comment]
Alacritty is still on winit 0.11. winit 0.13 contained about 1kLOC of X11 IME changes, so it's safe to say there's not much point in investigating this until after Alacritty updates.

**Comment by leihuxi** [comment]
Maybe it's not Alacritty's iusse, i just find my ideaj also cound not  inpput chinese.
Before this, i run pacman -Syyu for full system upgrade.

**Comment by francesca64** [comment]
Does it work on this branch? https://github.com/francesca64/alacritty/tree/winit-git

**Comment by leihuxi** [comment]
@francesca64 it not work.

**Comment by francesca64** [comment]
`echo $XMODIFIERS`

**Comment by quininer** [comment]
@francesca64 
I saw the input method work very well (optirun still not work), but its font size seems unusually large.

![screenshot_20180516_125826](https://user-images.githubusercontent.com/6286761/40097446-bc77de88-5908-11e8-8ca3-4ff16142e477.png)

@leihuxi 
I don't think it's a alacritty problem, you may need to provide `fcitx-diagnose` output, or go to IRC `#archlinux-cn` for help.

**Comment by leihuxi** [comment]
@francesca64 @quininer, thank you very much.
after I set below variables in .xprofile, now it work:
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx

**Comment by francesca64** [comment]
I feel bad for how often @im must get pinged by mistake.

@quininer prior to tomaka/winit#515, `Window::hidpi_factor` would always return 1.0. Now it calculates the DPI factor using XRandR.
