### ISSUE TITLE
compiling error on arch linux

### ISSUE THREAD

**Issue by BafFlynN** [jwilm/alacritty#130]
Compiling servo-fontconfig v0.2.0 (https://github.com/jwilm/rust-fontconfig#419135e5)
     Running `rustc /home/elio/.cargo/git/checkouts/rust-fontconfig-74c44fcd18a59a5d/419135e5e1106ec0973dd4923bd9c70d8e438cc8/src/lib.rs --crate-name fontconfig --crate-type lib -C opt-level=3 -g -C metadata=7de0c55f3beac4a1 -C extra-filename=-7de0c55f3beac4a1 --out-dir /home/elio/Downloads/alacritty-master/target/release/deps --emit=dep-info,link -L dependency=/home/elio/Downloads/alacritty-master/target/release/deps --extern fontconfig_sys=/home/elio/Downloads/alacritty-master/target/release/deps/libfontconfig_sys-5f3b046d6b3fe525.rlib --extern libc=/home/elio/Downloads/alacritty-master/target/release/deps/liblibc-6ec63c5a0e74a074.rlib --cap-lints allow -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib`
Build failed, waiting for other jobs to finish...
error: Could not compile `parking_lot_core`.

Caused by:
  process didn't exit successfully: `rustc /home/elio/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.0/src/lib.rs --crate-name parking_lot_core --crate-type lib -C opt-level=3 -g --cfg feature="nightly" -C metadata=b776954c2db52c62 -C extra-filename=-b776954c2db52c62 --out-dir /home/elio/Downloads/alacritty-master/target/release/deps --emit=dep-info,link -L dependency=/home/elio/Downloads/alacritty-master/target/release/deps --extern smallvec=/home/elio/Downloads/alacritty-master/target/release/deps/libsmallvec-cf4677c7857fc4a9.rlib --extern libc=/home/elio/Downloads/alacritty-master/target/release/deps/liblibc-6ec63c5a0e74a074.rlib --extern rand=/home/elio/Downloads/alacritty-master/target/release/deps/librand-8ea7d489d4a383a0.rlib --cap-lints allow` (exit code: 101)

**Comment by theduke** [comment]
Did you install the dependencies and set the specific rustc compiler version with rustup as described in the README?

**Comment by polyzen** [comment]
https://aur.archlinux.org/packages/alacritty-git/

You have to install `rustup` from the repos to fulfill the nightly Rust version for now.

**Comment by jwilm** [comment]
It sounds like you may be missing the `fontconfig-dev` dependency or equivalent on your system. The are instructions in the README for doing so on Arch.

**Comment by BafFlynN** [comment]
yeah I completely missed that single one, once I am done with work I plan on getting it running :) Will report back.

**Comment by mfrischknecht** [comment]
> https://aur.archlinux.org/packages/alacritty-git/
>
> You have to install rustup (in the repos) to fulfill the nightly Rust version for now.

I just compiled alacritty using the mentioned AUR package and can confirm this. After installing `rustup`, everything builded smoothly.

**Comment by BafFlynN** [comment]
I agree. Just ran it and using it for work as we speak. So far love it.
