### ISSUE TITLE
support for dropping a file to insert its path

### ISSUE THREAD

**Issue by codl** [jwilm/alacritty#1301]
other terminals support dropping a file from a file manager onto the terminal to insert its path in quotes. this is very convenient when dealing with files that are more easily found through a file manager

it'd be nice if alacritty could support this as well

**Comment by monouser7dig** [comment]
I personally use it a lot in the standard Mac Terminal, along with alt + arrows not working it makes alacritty quite a bit less usable for me.

**Comment by jwilm** [comment]
I think this would actually be pretty easy to implement assuming this winit event is actually implemented for both X11 and macOS. [`winit::WindowEvent::DroppedFile(PathBuf)`](https://docs.rs/winit/0.13.1/winit/enum.WindowEvent.html#variant.DroppedFile) sounds like just what we would need.

**Comment by chrisduerr** [comment]
Oh yeah that sounds quite convenient.

**Comment by francesca64** [comment]
`DroppedFile` is implemented on Windows, macOS, and X11. In fact, implementing drag and drop on X11 was my very first contribution to winit. I can tell you that the path is pre-canonicalized on X11, though I haven't investigated the exact path format on other platforms; I just know that it works.

(In case you were wondering, `HoveredFile` and `HoveredFileCancelled` are only implemented on macOS and X11, though it doesn't seem like you have to worry about that.)

**Comment by jwilm** [comment]
Thanks for filling in the details @francesca64!

**Comment by jwilm** [comment]
@francesca64 I continue to be amazed by how much time you dedicate to winit. I don't know how you make the time to also follow and comment on winit issues in Alacritty. Thanks again for all your hard work!

**Comment by jedahan** [comment]
@monouser7dig what do you use alt-arrows for? mind making another issue for that if its not configurable yet?

**Comment by monouser7dig** [comment]
they jump by word left/ right, I believe there is an issue related to winit about it somewhere, there was something about non US keyboards but I actually can't use arrow properly on my US keyboard either. 
something like [this](https://github.com/jwilm/alacritty/issues/700)

**Comment by chrisduerr** [comment]
MacOS is weird...

**Comment by chrisduerr** [comment]
Implementation was super simple, hopefully this works on all platforms, testing is welcome!

PR: #1304

**Comment by jedahan** [comment]
Interestingly enough, and perhaps related to #675 , I don't immediately see the contents pasted, i have to click on the alacritty window and thats when I guess it gets the event. I wonder if winit is bufferring that event until focus? Could also be related to https://github.com/jwilm/alacritty/commit/5be0e3ad8fcde5d8dec98c0e71a2b495294d03be ...

**Comment by chrisduerr** [comment]
5be0e3a shouldn't have anything to do with this at all. But there's an easy way to figure out if it's buffering the event until focus, or if the window is just not redrawn. If you put a `println!("aaontehu")` in the event handling section (https://github.com/jwilm/alacritty/commit/57281363503ddd1ebb373ed5de2b84c79d5aa3aa#diff-3d7686001860aa382f8b9c18554cc138R343), you should see when the event is actually first received. So if it shows the event is received but doesn't show up in the terminal, I might need to set the `dirty` flag. @jedahan

**Comment by jedahan** [comment]
Cool I will test this out tonight thanks for the quick response.
