### ISSUE TITLE
fails to start with shader error

### ISSUE THREAD

**Issue by c-Monster** [jwilm/alacritty#1303]
Which operating system does the issue occur on?
`arch linux 4.16.5`
If on linux, are you using X11 or Wayland?
`X11`

I've looked at issue 128 and others, but I think mine is different: 
```libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Alacritty encountered an unrecoverable error:

	There was an error initializing the shaders: failed compiling shader:
```
Alacritty worked just fine until yesterday when I installed eclipse and attempted to install eclim. Other users seem to have the same issue with steam and they say there's a broken symlink somewhere. Has anyone else seen this?

**Comment by chrisduerr** [comment]
This really looks like something messed with your drivers.

**Comment by chrisduerr** [comment]
Is this issue still present? If it is, does changing to the proprietary drivers resolve the problem?

**Comment by c-Monster** [comment]
Actually, the issue was another app messing up DLLs

**Comment by c-Monster** [comment]
Sorry for the late response
