### ISSUE TITLE
Rename alacritty-completions.zsh to _alacritty?

### ISSUE THREAD

**Issue by jedahan** [jwilm/alacritty#1305]
I tried sourcing `alacritty-completions.zsh` and it failed, then I read the readme.md, and saw it needs to be renamed and added to fpath. It would be cool if it was just named `_alacritty` so all I had to do is add the directory to fpath.

Maybe we could put it in a subdirectory `completions` to make it clearer.

Alternatively, could the zsh file be reworked so that it could be sourced easily? I'm not sure how.

I made this hack to work around it for now https://github.com/jedahan/alacritty-completions

**Comment by chrisduerr** [comment]
I don't really see an issue. I've intentionally named it like this for verbosity to make clear what the file is. If you want to make use of the completions, you should either follow the installation instructions or make use of the package in your repositories (like aur). In both cases there shouldn't be any problem present.

**Comment by jedahan** [comment]
Most of the issue is around it not being a source-able zsh file, while the other ones are. So in this case the name and how it's expected to be used conflict with each other, which seems less clear (shown by the fact that it needs extra manual steps to install) than even renaming it to something like alacritty-completions-zsh.

**Comment by chrisduerr** [comment]
Why don't you just install the file in the path made for storing zsh completions?

**Comment by jedahan** [comment]
The path is different on different systems (for example, there is no `/usr/share/zsh/functions` directory on my laptop), so I use a zsh package manager to handle it for me.

Most package managers consider `.zsh` files as source-able, add directories to `fpath`, etc. By naming things in a way they are expecting, it would help reduce the papercuts of both manual and managed installations (less work for package maintainers as well).

I'm not quite sure why there is resistance to making the zsh file sourceable - if I see something with a .zsh extension, I expect no errors when sourcing it (likewise for bash or fish or sh). In addition symlinking or renaming it to _alacritty as compdef expects, but I'm glad I made an issue first before doing the work of a pull request.

**Comment by chrisduerr** [comment]
The thing is, you probably shouldn't be running directly from the repository anyways. If you want to install a program it seems like the far better choice to move the files where they're supposed to be. Zsh completions are never supposed to be in some `alacritty` directory. If you have to `mv` them anyways, changing the name to what you need shouldn't make any difference. Also the `/usr/share/zsh/functions/Completion` path should be universal and work on all machines with zsh. There has to be some directory where your zsh stores completions and that's probably the right place to put the completions file, or symlink it.

I'm not against changing the name, I just see no benefit in it. In every normal use-case where alacritty is installed properly following the instructions in the README or by having a maintainer do it for you this should be absolutely no problem.

And I disagree with the statement that this will make things easier for maintainers, it shouldn't make any difference for them. The file has to be moved out of the working directory anyways, so the target name can be chosen freely.

**Comment by chrisduerr** [comment]
That said, if you still feel like there would be a significant benefit for creating a `completions` directory with the fish, zsh and bash files in there, named the way you want them to be named, go for it. I generally don't think it's a bad idea to clean up the root directory of alacritty a bit.
