### ISSUE TITLE
Copy Paste not not working

### ISSUE THREAD

**Issue by MaxiMaerz** [jwilm/alacritty#1307]
I'm on Ubuntu 16.04 and built from source (currently scroll back branch but tested in master, too).
I use i3 as a window manager and x11 as display manager.

Currently Alacritty is working as it should besides i cannot copy paste anything. My alacritty.yml is detected and read correctly, (e.g. if i change the modifier for copy to ctrl+c the normal behaviour (SIGINT) is not sent anymore, but it does not copy either. All other shortcuts are recognized correctly.

Here is the output of --print-events -vvv:

    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 46, state: Pressed, virtual_keycode: Some(C), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 46, state: Released, virtual_keycode: Some(C), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(V), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 47, state: Released, virtual_keycode: Some(V), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
    glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 46, state: Pressed, virtual_keycode: Some(C), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }

If i can provide more output, could you please tell me how.
Copy Paste does work in all other terms: gnome-terminal, xterm, konsole and kitty

**Comment by MaxiMaerz** [comment]
Ty, this fixed it. I must have incompletely copied the requirements.

**Comment by GregTheHun** [comment]
Sorry to bring up an old bug, but it appears that this one appears to be affecting me in debian 12 sid w/ gnome.

I installed it via nala (basically a pretty wrapper for apt), and made sure xclip was installed, still not working for me. Is there any settings in alacritty I can check?

**Comment by kchibisov** [comment]
We don't use xclip, we use the clipboard access directly.

**Comment by DriNeo** [comment]
On Archlinux Alacritty can copy/paste using Ctrl Shift C/V.
On Mx Linux (Debian fork) that shortcut doesn't work, but the middle click paste in Alacritty the last text that is selected anywhere in the desktop. It is the same for all apps. I didn't know that mouse shortcut, but it is a convenient replacement.
