### ISSUE TITLE
cava screen cutting issue much more noticable in alacritty than gnome-terminal

### ISSUE THREAD

**Issue by daboross** [jwilm/alacritty#1312]
Which operating system does the issue occur on? Linux, Ubuntu 18.04

If on linux, are you using X11 or Wayland? Running Wayland with XWayland (`env WAYLAND_DISPLAY= alacritty`)

When running `cava` audio visualizer, there's noticable screen cutting in alacritty which does not occur in gnome-terminal. I'm not sure what to do to debug this further, so creating an issue here in case anyone knows where to look for more information.

Screen recording of the problem: https://webmshare.com/mPQoX

glxinfo:

```console
$ glxinfo | grep OpenGL                           
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.0-rc5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.0-rc5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.0-rc5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by daboross** [comment]
This seems more likely due to how cava is implemented than anything alacritty can change, I guess. With frame rates and all.

**Comment by chrisduerr** [comment]
I do wonder how cava is implemented. It should be possible to do this without having these weird cuts inside the bars.
