### ISSUE TITLE
Alacritty doesn't close until the first event after exiting shell

### ISSUE THREAD

**Issue by daboross** [jwilm/alacritty#1313]
Which operating system does the issue occur on? Linux, Ubuntu 18.04

If on linux, are you using X11 or Wayland? Running Wayland with XWayland (`env WAYLAND_DISPLAY= alacritty`)

When I leave the shell with ^d or "exit", alacritty will stay alive until I do the next thing (move my mouse, click, type a character, or defocus). I'd expect it to die immediately after exiting the shell.

Screen recording of the issue: https://webmshare.com/DdYGG

glxinfo:

```console
$ glxinfo | grep OpenGL                           
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.0-rc5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.0-rc5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.0-rc5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by chrisduerr** [comment]
According to #1342 this issue is not only present with Wayland, so removing the wayland tag and changing the title to be more accurate.

More information about this issue on X.Org is present in the referenced issue.

**Comment by semaj** [comment]
I took a peek at this one. Looks like when https://github.com/jwilm/alacritty/blob/6cbae83f174fa6d114ea66b1f8dd6185950ca835/src/event.rs#L384 is blocking, it doesn't notice `SHOULD_EXIT` until an event occurs. This blocks the main loop as well.

New to the codebase, but it seems like the super hacky solution is to send a `notify` to the process handler upon `SIGCHLD`; the more reasonable solution is finding out how to do away with the unsafe `SHOULD_EXIT`.

**Comment by tjkirch** [comment]
This is the same as #915 right?

**Comment by chrisduerr** [comment]
Yes it is, thanks for the heads-up.
