### ISSUE TITLE
Text cursor should be more 'lazy'.

### ISSUE THREAD

**Issue by c-edw** [jwilm/alacritty#1314]
_Which operating system does the issue occur on?_
Ubuntu 18.04

_If on GNU/Linux, are you using X11 or Wayland?_
X11.

I've noticed that in some cases, the text cursor will jump to the start of the line, then immediately to the end when something is printed. In Ubuntu's GNOME Terminal, the text cursor doesn't flicker/move around.

Steps to reproduce:
- Open a new Alacritty window
- Type `ls` (the behavior is not specific to this command)
- Observe that a new line is printed, and the text cursor jumps to the start of the new line, then to the end once something is printed

**Comment by nixpulvis** [comment]
I'm having trouble reproducing this.

**Comment by c-edw** [comment]
Looks like it's been fixed. I'm running the latest commit on the `scrollback` branch. Closing.
