### ISSUE TITLE
Wrong focus events 

### ISSUE THREAD

**Issue by mox-mox** [jwilm/alacritty#1320]
#Which operating system does the issue occur on?
Archlinux using X11 and i3wm

First of all: Thank you for writing and maintaining alacritty. And a big thumbs up for code quality. I have never before looked at alacritty code (or Rust code in general), but still this looks quite readable.

I noticed some incorrect focus events  when using alacritty:

# First Issue:
## Steps to reproduce:
1. On an empty workspace spawn an alacritty window
2. Go to another (empty) workspace
 - Expected: `Focus Lost` event
 - Got: `Focus Lost` event
3. Go back to the workspace with alacritty
 - Expected: `Focus Gained` event
 - Got: `Focus Gained` event, then `Focus Lost` event

# Second Issue:
## Steps to reproduce:
1. On an empty workspace spawn an alacritty window
2. Spawn some other window (takes Focus)
 - Expected: `Focus Lost` event
 - Got: `Focus Lost` event, then `Focus Gained` event
2. Close the other window (alacritty regains focus)
 - Expected: `Focus Gained` event
 - Got: sometimes `Focus Gained` event, then `Focus Lost` event

# How I measured the events:
In the alacritty window, I started neovim with the following minimal init.vim:
```
augroup i3_focus
        autocmd VimEnter             * :sleep 100m | silent !notify-send "NeoVimEnter"        && i3-msg -q mode vim
        autocmd FocusGained          * :sleep 100m | silent !notify-send "NeoVimFocusGained"  && i3-msg -q mode vim
        autocmd FocusLost            * :sleep   1m | silent !notify-send "NeoVimFocusLost"    && i3-msg -q mode default
        autocmd VimLeave             * :sleep   1m | silent !notify-send "NeoVimLeave"        && i3-msg -q mode default
augroup END
```
I cross-checked my steps with an urxvt with a perl extension to send the relevant focus escape sequences to neovim, and it worked without problems. I also removed the sleep and notify commands from the autocommands in case those were causing any interference, but to no avail.
(Side note: My i3 is configured to pass presses of the alt key (that i3 usually acts on) to my neovim so I can use mappings on the alt key in neovim. Using this, I use alt+[h|j|k|l] to switch split windows in neovim, and when for example the rightmost split window is focused, alt+l focuses the next non-neovim window to the right. Sadly, this breaks when the focus reporting for the terminal running neovim is wrong. Btw: The sleep 100m is to avoid the race condition when switching between two terminals running neovim)

If there is more testing I can do, or if you need more information, please let me know.

I looked at `on_focus_change` and `handle_event` and I think they both look all right to me. I do not quite understand where events are fed into Processor::pending_events (except when calling `process_events` with the `wait_for_event` flag set), but I guess there might be an error there.

Best regards,
mox

**Comment by francesca64** [comment]
This sounds like it's probably a bug in [winit](https://github.com/tomaka/winit) (...or i3). Does this still happen on this branch? https://github.com/francesca64/alacritty/tree/winit-git (it's patched to use the latest winit)

**Comment by chrisduerr** [comment]
This might be related to #1227?

**Comment by francesca64** [comment]
You'd be surprised; any seasoned X11 abstraction will contain plenty of workarounds for non-conformance in different WMs. For instance, Mutter doesn't correctly report all the hints it supports, and on i3 we have to reset scroll axes using a different condition. Of course, even if it's an i3 bug, it's still going to be winit's responsibility to deal with it, since that's just the nature of the beast.

**Comment by chrisduerr** [comment]
Since there hasn't been any report to the contrary, this issue should be resolved with recent updates to winit/glutin.

If this issue is still present, please let me know and I'll re-open.

**Comment by z0xyz** [comment]
The problem still persists on two of my machines (fedora with cinnamon, and elementaryOS with bspwm) . Both of them have alacritty obtained through cargo, being of version 0.10.1. One being without any customized configuration, and the other is slightly configured. Still, both of them don't support FocusLost event with vim, whereas something like gnome-terminal does.
@chrisduerr The issue still somehow persists .

**Comment by kudashevs** [comment]
> The problem still persists on two of my machines (fedora with cinnamon, and elementaryOS with bspwm) . Both of them have alacritty obtained through cargo, being of version 0.10.1. One being without any customized configuration, and the other is slightly configured. Still, both of them don't support FocusLost event with vim, whereas something like gnome-terminal does. [@chrisduerr](https://github.com/chrisduerr) The issue still somehow persists .

@kqvanity Here, it sounds like the issue with Vim and how it treats the alacritty. Have you tried to change TERM variable to `xterm` or `xterm-256color`? You can do it in `alacritty.toml` file (recommended) or in `~/.bashrc` (not recommended).

Open an alacritty config file (if it does not exist, create it: `~/.config/alacritty/alacritty.toml`) and add:
```toml
[env]
TERM = "xterm-256color"
```

Start a new terminal and check whether focus works. Cheers.
