### ISSUE TITLE
Keyboard modifier order should be irrelevant

### ISSUE THREAD

**Issue by kpcyrd** [jwilm/alacritty#1322]
I think two bugs got mixed up in #1321 with one of them being a duplicate, so I've decided to file a new bug and include the feedback I've received in the original report.

**Note:** `<` is `less then`, not `arrow left`.

I'm trying to migrate from xfce4-terminal to alacritty for weechat, I've quickly noticed that `alt+<` does not work, which is used in weechat to navigate to the previous buffer. `alt+>` is working correctly (which navigates forward in the buffer history).

I use this feature heavily, in xfce4-terminal+bash it selects the oldest command of the history, in alacritty it's the same as just pressing `<`.

I assume this is because, on my keyboard layout, `>` involves the shift key (see picture below), but `<` does not. Also, this is working correctly on a US keyboard layout, where both `<` and `>` depend on the shift key.

### Version
24e8a19e7d981fbc8853891ad4a17a9de2ac36bd

### Keyboard layout
German (no dead keys)

![german keyboard layout](https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/550px-KB_Germany.svg.png)

### Which operating system does the issue occur on?
Archlinux

### If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment]
Just to make sure: The issue discussed in #1321 was that when releasing just </> and pressing it again it doesn't work. But there's also the issue that shift -> alt -> </> does not work but alt -> shift -> </> does, right?

You could have also just commented under the different issue, always happy to re-open (but let's keep this here now). :)

**Comment by kpcyrd** [comment]
> The issue discussed in #1321 was that when releasing just </> and pressing it again it doesn't work.

I've mentioned this in my bug report as well, but I think it was a bad idea to report two (mostly) unrelated problems in one issue. :)

> But there's also the issue that shift -> alt -> </> does not work but alt -> shift -> </> does, right?
> 
> You could have also just commented under the different issue, always happy to re-open (but let's keep this here now). :)

Yes, this is what this bugreport is about. :) I've decided to create a new one since my original report was a bit confusing.

**Comment by chrisduerr** [comment]
@kpcyrd I'll have to look into this issue myself again. I'll let you know what needs to be done.

**Comment by chrisduerr** [comment]
I've just tested this again and I don't think it's an issue with order of modifiers. All things seem to work properly using `Alt + Shift + T` to print some random characters.

First of all, could you test if this issue is still present? Just to make sure that it hasn't been resolved in a recent update.

If this issue is still present, I'd assume that the key is just not reported. There are similar issues but the easiest way to confirm this is by running `alacritty --print-events` and checking what is printed when the bug occurs. I'd assume that the keycode is probably not correct, using scancodes instead might help.

**Comment by kpcyrd** [comment]
I've just tried again and it's working correctly in a recent alacritty version :+1:
