### ISSUE TITLE
one (colorscheme) background color is wrong

### ISSUE THREAD

**Issue by phaazon** [jwilm/alacritty#1323]
The background should have value `#282c34` :yum:

**Comment by nixpulvis** [comment]
FWIW, here is my complete One Dark theme for alacrity.

```
# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '0x282c34'
    foreground: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x131613'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'
```

Not sure if other colors are off, I didn't take this from the wiki.

**Comment by chrisduerr** [comment]
IIRC it should be possible for anyone to edit themes. Even though I would discourage editing existing themes based on a hunch, if you know that a certain theme is incorrect, feel free to change it @phaazon.

If you have the canonical source of that theme's colorscheme, feel free to also add it to the title (by making the title a link to the colorscheme, similar to how it's already done for others). If that all worked out for you, please close this issue. :)

**Comment by phaazon** [comment]
I cannot change the Wiki code AFAIK :/

**Comment by jwilm** [comment]
@phaazon everyone should be able to change the wiki

**Comment by phaazon** [comment]
Oh. Ok then, fair enough! :)

**Comment by nixpulvis** [comment]
I can update the Wiki, but would we like both of my changes (`background` and `normal.black`) or just the updated `background`?

**Comment by phaazon** [comment]
I guess as long as you fix something, it’s all good! :P

**Comment by nixpulvis** [comment]
@phaazon yea, it fixes the issue of not being able to see black text on the background, though some might argue that's intended...

The wiki is now updated, and this can be closed assuming everyone is happy. :yin_yang:

**Comment by chrisduerr** [comment]
Leaving it up to @phaazon to review the changes and close this issue if everything's fine.

Thanks for the work @nixpulvis!

**Comment by phaazon** [comment]
So you didn’t update the `black` value, @nixpulvis?

Otherwise, I shall close this, yeah.

**Comment by nixpulvis** [comment]
I didn't change the value, but left a note for people who want to see black on the background. I choose to do this because it's consistent with what people would expect if they are using the config as it was before.

**Comment by phaazon** [comment]
LGTM. Thanks!
