### ISSUE TITLE
Selection highlighting is one character off

### ISSUE THREAD

**Issue by snoblenet** [jwilm/alacritty#1325]
- Tmux 2.7
- ZSH 5.5.2
- Mac OS X 10.13.4
- Alacritty @ 24e8a19

![image](https://user-images.githubusercontent.com/62277/40457416-b2d02750-5f39-11e8-89e7-10725ff7d760.png)

The letter 'c' is part of the selection (as desired) but is not highlighted.

(The error happens when selecting in the middle of a line too.)

**Comment by jwilm** [comment]
Is your cursor on the `c`? it looks like it's highlighted properly but inverted.
