### ISSUE TITLE
Disable bold font (text)

### ISSUE THREAD

**Issue by nanangarsyad** [jwilm/alacritty#1328]
OS being used:
Ubuntu 18.04, on X11

It's not really an issue, it just that I want to disable the bold font. I know it's a silly question.
But, I've tried to search similar issue about disabling bold text (font), sadly what I found,  it was about setting bold text color.
In the end I created new issue here (I hope I didn't re-post) .
So, what should I do to disable the bold font (text)?

Thank you.

**Comment by jwilm** [comment]
You should be able to use a non-bold style for the bold font config.

**Comment by nanangarsyad** [comment]
Sorry for the late reply.
Changing the bold config font into regular font fixed the issue. I'll close this issue.
Thanks a lot.
