### ISSUE TITLE
Problem to page...

### ISSUE THREAD

**Issue by GiovanniSM20** [jwilm/alacritty#1331]
I try to see (for the example) the output for the ```rustc --help``` but I can't just because I can't to roll on the terminal. Can someone help me ? :octocat:

**Comment by chrisduerr** [comment]
I'm sorry but could you elaborate on the issue a bit? If I understand this correctly, you want to see the `rustc --help` output, but you can't scroll, right?

If that's your problem, then I'd recommend looking at the scrollback branch:
https://github.com/jwilm/alacritty/tree/scrollback

This is a new feature that is currently in development and hasn't been integrated into master yet. If this solves your issue you can subscribe to #124 and #1147 to keep up to date so we can close this issue.

If I did not understand correctly, please feel free to correct me. :)

**Comment by GiovanniSM20** [comment]
that was exactly what I wanted :octocat: :heart:
