### ISSUE TITLE
Opens and quits immediately on macOS High Sierra

### ISSUE THREAD

**Issue by gretzky** [jwilm/alacritty#1334]
Having an issue where once I compile Alacritty, it won't open. It opens and force quits immediately. No logs that I can find, no issues with hardware spikes (according to iStat Menus). I'm at a loss, there seems to be no reason why this happens. Potentially related to #818 somehow?

I'm on a MacBook Pro 13,2. running High Sierra 10.3.4. I added the model number because on my old MBP(12,1) it ran perfectly. Any suggestions are appreciated if someone's run into this before.

**Comment by chrisduerr** [comment]
Thanks for opening an issue. Currently alacritty doesn't write any logs, so the only way to find out what went wrong is to start alacritty from a different terminal instance (so you can see stderr).

This should hopefully get you some more information about what's going on.

**Comment by gretzky** [comment]
Solved it. Migrated my `alacritty.yml` file before installation, and so removing it and readding it fixes it. 
 Figured it out via [this section](https://github.com/jwilm/alacritty/blob/e34dccdabf210612666cbb9d22d7afff23487eaf/src/main.rs#L74). Thanks again!

**Comment by chrisduerr** [comment]
No problem, always happy to help! :)
