### ISSUE TITLE
Crash by drawing out of bounds (List of related issues)

### ISSUE THREAD

**Issue by d3rrial** [jwilm/alacritty#134]
A list of all opened issues that have the same underlying problem: Drawing out of bounds.

- ~~#136~~
- ~~#133~~
- ~~#94~~  
- ~~#88~~ 
- ~~#12~~

Please don't open new issues for this same problem anymore and instead put a comment here (unless @jwilm says otherwise)

**Comment by d3rrial** [comment]
Large negative offsets cause characters to be drawn out of bounds and cause crashes as well.

**Comment by jwilm** [comment]
There's a bunch of functions like `goto` that blindly accept valid lines and columns. I think most of these could be fixed by coercing them into the bounds of the terminal.

**Comment by jwilm** [comment]
I went through your list of issues here and they all seem to be fixed. Closing.
