### ISSUE TITLE
Pasting text using Shift-Insert doesn't work when tmux is running in alacritty

### ISSUE THREAD

**Issue by stefancocora** [jwilm/alacritty#1352]
Which operating system does the issue occur on?
```
 OS: Arch Linux
 Kernel: x86_64 Linux 4.16.13-1-ARCH
 Shell: zsh 5.5.1
 WM: i3
```
If on linux, are you using X11 or Wayland?
```
Display: x11 server: X.Org 1.20.0 driver: i915 ...
```
Package versions:
```
alacritty-git 0.1.0.774.g2fcdd40-1
tmux 2.7-1
gpaste 3.28.2-1
```

**Issue description**
- unable to paste text from the system clipboard into a tmux session running inside alacritty :crying_cat_face: 
- pasting text from the system clipboard works fine when using another terminal emulator and tmux ( tested with `kitty` , `tilix`, `gnome-terminal`, `terminator` )
- pasting text from the system clipboard works fine when using alacritty **without tmux**
- when pasting text I'm using Shift+Insert in all test cases.
- I'm using `gpaste` as the clipboard manager.

**Comment by chrisduerr** [comment]
Your clipboard manager shouldn't matter, on X11 alacritty currently uses `XClip` for copy/pasting. The key bindings used to do so should be defined in your `alacritty.yml` configuration file.

Do you have `xclip` installed? If not, that should probably be the first step. After that you need to define a shortcut for it, by default one is only defined for Ctrl+Shift+C/V.

**Comment by stefancocora** [comment]
Thank you for looking into this and for your clarifications.

I already have `xclip` installed:

```
xclip 0.13-1
```

This is the keybinding part of my `alacritty.yml` config file, these
haven't changed:

```
key_bindings:
  - { key: V,        mods: Control|Shift,    action: Paste               }
  - { key: C,        mods: Control|Shift,    action: Copy                }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Insert,   mods: Shift,   action: PasteSelection               }
...
```

Looks like I've always been using what the alacritty config calls
`PasteSelection` to paste into tmux running inside alacritty and it has
always worked.

If I use the keybindings for `Paste` then pasting inside a tmux pane
running in alacritty works.

I wonder if this is not some sort of regression with the alacritty code
around the `PasteSelection` functionality...

**Comment by stefancocora** [comment]
@chrisduerr thanks for explaining the subtle differences between Paste
and PasteSelection !

Note:
I've made no changes to my alacritty.yml, but since
```
alacritty-git 0.1.0.774.g2fcdd40-1
```
PasteSelection has stopped working.

PasteSelection was working before this build version.


Switching my keybindings to:

```
  - { key: Insert,   mods: Shift,   action: Paste               }

```
allows me to successfully use `Shift-Insert` to paste inside a tmux
window running in alacritty.

Thanks for your help!

**Comment by sazarkin** [comment]
I think there is still a problem?
If I select something using `shift+Mouse` and want to paste it using `shift+insert` it do not work in tmux.
Selection works fine, and xclip has the data. Problem only with shift+insert.
Why `PasteSelection` action does not work inside tmux?
I am switching from gnome-terminal, everything fine there.

**Comment by chrisduerr** [comment]
@sazarkin See https://github.com/jwilm/alacritty/pull/1300 and https://github.com/jwilm/alacritty/issues/1298.
