### ISSUE TITLE
Disable mouse?

### ISSUE THREAD

**Issue by tokudan** [jwilm/alacritty#1354]
Is there a way to prevent applications like Midnight Commander from knowing about the mouse?
Selections in alacritty should work just as before, but any application in alacritty should just not be aware of the mouse, because the changed behaviour and cursor is very irritating to me.

**Comment by NickeZ** [comment]
Hold shift while clicking

**Comment by tokudan** [comment]
That still leaves the mouse enabled in mc.
That still has a different mouse cursor.

**Comment by chrisduerr** [comment]
@tokudan I'm not quite sure what you mean. Do you want to disable the pointer cursor when mouse mode is enabled and instead use the I-Beam cursor even when an application makes use of the mouse?

**Comment by tokudan** [comment]
I do not want an application like midnight commander to know that there is a mouse.
I do not know how exactly e.g. mc detects the mouse, but I guess is that it sends some escape sequence and alacritty responds with another sequence that contains information about the mouse.
I want alacritty to tell mc "nope, there is no mouse" and of course also not forward any mouse events.

**Comment by jwilm** [comment]
@tokudan you can configure applications like midnight commander not to enable mouse mode. This is opt-in per application, and Alacritty will not be providing any setting to control this globally.

**Comment by chrisduerr** [comment]
Midnight commander just advertises its own capabilities with escape sequences and then responds no requests to use those capabilities. The closest thing to midnight commander asking if mouse is supported is the terminfo.

I have the feeling that you might actually want something different than you say you want though, so would you mind expanding on why you don't want midnight commander to "know about your mouse"? How does this change anything, I'm not a midnight commander user, so I have no experience with it.

**Comment by chrisduerr** [comment]
Okay, there are actually a few issues here, but I think most already have reasonable solutions:

 * annoy colleagues changing configs -> user configs instead of global ones
 * inverted cursor -> configure system cursors (your theme is missing cursors #1319)
 * click when moving -> it has already been requested to ignore the first click after gaining focus (#1291)

I hope this lineup of solutions will help you out, this issue itself can not be resolved because alacritty never tells anyone it actually supports a mouse at all, this is done completely through `terminfo`.

**Comment by timvisher** [comment]
FWIW as someone new to Alacritty the feature that I believe is being asked for here is 
![Settings 2024-10-31 16-26-32](https://github.com/user-attachments/assets/6a1ff47b-14da-4c97-85b0-043359b5b18e)

I never want to interact with a terminal application via the mouse. I only ever want to be interacting with the terminal emulator itself.
