### ISSUE TITLE
regression: <C-Tab> keybinding no longer works

### ISSUE THREAD

**Issue by sodiumjoe** [jwilm/alacritty#1358]
Which operating system does the issue occur on? macos 10.10.5

If on linux, are you using X11 or Wayland? n/a

the specific keybinding is:

```yaml
  - { key: Tab,      mods: Control, chars: "\x01n",                      }
```

`git bisect` points at [this commit](https://github.com/jwilm/alacritty/commit/765949f256aefcc513d0bfb46b64d315f9c2f3d2), which is just an upgrade of glutin/winit.

I haven't really figured out whether it's an issue with an upstream breaking change or what. Running `winit`'s `window` example, I can see the event come through on the keypress:

```
WindowEvent { window_id: WindowId(Id(140330957578608)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 48, state: Released, virtual_keycode: Some(Tab), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
```

A `println` [here](https://github.com/jwilm/alacritty/blob/master/src/event.rs#L294) also does show the event coming through, so maybe it has something to do with config parsing or something. I'm going to continue investigating, but wanted to make an issue in case anyone has ideas.

**Comment by snoblenet** [comment]
related to this? https://github.com/jwilm/alacritty/issues/1336

**Comment by sodiumjoe** [comment]
this was fixed in https://github.com/jwilm/alacritty/pull/1403

**Comment by chrisduerr** [comment]
Once winit's cargo version is updated I'll run `cargo update` on the #1403 PR so it will resolve this problem.

Thanks for the update @sodiumjoe.

**Comment by sodiumjoe** [comment]
@chrisduerr I think we'll have to get it into glutin first, right?

**Comment by chrisduerr** [comment]
@sodiumjoe Not if it's just a minor update. So if glutin says it just wants 0.6.0, then everything until 0.7.0 should be viable.

**Comment by sodiumjoe** [comment]
oh great! hm, I guess I need to review my understanding of cargo
