### ISSUE TITLE
Split terminal

### ISSUE THREAD

**Issue by cunhazera** [jwilm/alacritty#1360]
Is there some way to split the alacritty terminal or open some new tab?

Running on Ubuntu with X11.

**Comment by chrisduerr** [comment]
From the README:
```
The simplicity goal means that it doesn't have features
such as tabs or splits (which can be better provided by
a window manager or terminal multiplexer) nor niceties
like a GUI config editor.
```

This is out of scope of the idea of the project, the focus is rather on making the simple things alacritty can do fast and efficient. However there's some ongoing work to extract parts of alacritty into a library (#1023), if this ever takes off it would be possible to have a different front-end which might come with different design goals.

**Comment by CopernicusPY** [comment]
In my opinion, efficiency is not achieved by removing ecential (for some people) features. A lot of people are used to having multiple instances of their terminal emulator. Having to open a new window for every new instance (or having to use term multiplexers, or window managers as mentioned in the readme file) slow down the workflow of the user. Just imagine having to open new windows every time you want to do something else without closing your current session. It would such a waste of RAM.  For GUI config, I think it really isn't needed but having a simple menu with pressing right click would be nice. I am happy to chat about it so feel free to answer people and maintainers! Have a nice day/night or whatever :)

**Comment by eddiehazel** [comment]
this is dealbreaker for me :( 

given that it has indeed now taken off, is it time to entertain the possibility of a little wrapper that can do t he splits? :banana:

**Comment by MariuzM** [comment]
Yep agree i was looking for this feature, shame i have to switch back to iTerm :(

**Comment by Hadlock** [comment]
For ops purposes (tailing logs, checking status, etc) I generally have 2-3 windows each with at least one vertical split, and often a horizontal split. Intentionally leaving this core functionality out of an otherwise modern terminal is very unfortunate.

**Comment by eddiehazel** [comment]
since i wrote the comment, i realised that the main added functionality of split panes over tmux is the ability to change the text size in different panes ( :

**Comment by devarda** [comment]
If you added tabs, you should add split panes please.

**Comment by chrisduerr** [comment]
> If you added tabs, you should add split panes please.

Alacritty didn't add tabs.
