### ISSUE TITLE
Incorrect font rendering?

### ISSUE THREAD

**Issue by natedooley** [jwilm/alacritty#1365]
I'm on Arch Linux using X11 and the alacritty-git package from the AUR.

After the most recent update, something weird started happening with my fonts. I didn't change anything in the config and they used to work correctly. I'm using the Tamzen font. I don't know if it's not finding the right font or what, but the character width is definitely wrong. Here's a screenshot, above is Termite and below is Alacritty.

![qxogwvl](https://user-images.githubusercontent.com/31457788/41203114-d0c003ce-6ca0-11e8-9920-bde9c50e5f59.png)

Here's the output of alacritty -v:

![u0phq0t](https://user-images.githubusercontent.com/31457788/41203151-2c96c714-6ca1-11e8-9a91-6ab282f47058.png)

and neofetch:

![wjv06ew](https://user-images.githubusercontent.com/31457788/41203173-6875e8e6-6ca1-11e8-9367-e5153290ca6b.png)

I'm not sure if this is a bug or just something I'm doing wrong, but any help would be appreciated.

**Comment by chrisduerr** [comment]
How is the character width definitely wrong? It seems fine to me looking at the screenshots.

The only thing that changed with fonts recently is that automatic DPI got introduced on X11. You can read more about that in #1339.

**Comment by natedooley** [comment]
Wrong compared to the size it used to be, I mean. I changed my DPI in X and it looks like it did before.
