### ISSUE TITLE
Text on color looks pixelated on non-retina OSX display

### ISSUE THREAD

**Issue by HendrikPetertje** [jwilm/alacritty#1368]
When looking at Alacritty from my retina display things look pretty good and crisp, though a bit fatter than what i was used to in Iterm2 (when it comes to non-bold text). when however opening an Alacritty session on my non-retina connected 4k display text warps around, becomes pixelated and looks really awful (at sub 15px sizes). screenshot below is a zoomed in example: 

![screen shot 2018-06-11 at 11 30 46](https://user-images.githubusercontent.com/3583395/41224155-0a267dac-6d6c-11e8-9d83-9225a62737e4.png)

On blacks everything works pretty fine and the color distortion is not noticeable. when however dealing with coloured backgrounds things become ugly fast.

I tried tweaking with "scale:with_dpi" and "use_thin_strokes" false-ing or true-ing doesn't make a difference. I also tried this with the "Hack" font and the "DejaVu Sans Mono for Powerline" font. both have the same issues.

Which operating system does the issue occur on?
OSX high sierra

1:1 ratio example:
![screen shot 2018-06-11 at 11 30 19](https://user-images.githubusercontent.com/3583395/41227557-91e8f66c-6d75-11e8-9cab-7b236ad9f685.png)

vs Iterm (with same font and aliasing settings):
![screen shot 2018-06-11 at 12 48 35](https://user-images.githubusercontent.com/3583395/41227632-d00d0e4c-6d75-11e8-9d4c-3768a5c5dc6e.png)

**Comment by chrisduerr** [comment]
I'm not super familiar with the macos font rendering, however this looks like it's just subpixel RGB at play here?

There seems to be a difference between alacritty and iTerm, but I'm not quite certain if this is alacritty's fault? Maybe the font configuration RFC can help here (#957)?

**Comment by tpict** [comment]
This looks like the same problem as #486

**Comment by chrisduerr** [comment]
@tpict Thanks for mentioning this, I wasn't aware of #486. Closing this a as a duplicate so all discussion can be kept in one place.
