### ISSUE TITLE
Control Space does not work and prevents further input

### ISSUE THREAD

**Issue by legendre6891** [jwilm/alacritty#137]
After pressing Control-Space, alacritty stops responding to keyboard input and has to be restarted to function correctly. (I use Control-Space as my tmux prefix.)

I suspect I need an entry in the `.alacritty.yml` but am unsure what the right `char` should be.

**Comment by d3rrial** [comment]
duplicate of #99

**Comment by jwilm** [comment]
Thanks @d3rrial
