### ISSUE TITLE
Distribute line-height remainder amongst all lines

### ISSUE THREAD

**Issue by softmoth** [jwilm/alacritty#1370]
[Edit: I guess this proposal could cause an issue with line-drawing glyphs (and similar) that are meant to connect from one line to the next. An alternative proposal is to divide the gap-size in to, above the first row and below the last. Or, maybe this idea just doesn't work.]

Currently when the line height doesn't divide into the window height evenly, there is a gap (0 < gap-size < line-height) at the bottom of the window.
It would be nice to have the top line at the top, bottom line at the bottom, and the gap-size split between all lines. So, for example, the tmux status is always flush against the bottom of the window and the vim tab line is always flush against the top, with no black pixels drawn below or above.
This is a minor issue, of course, but I think it'd be subtly comforting.

Arch Linux, X11

**Comment by chrisduerr** [comment]
It looks like you're talking about an issue that is already tracked in #1065. There's even an open PR which should fix this behavior (#1190) so hopefully we'll be able to merge that soon. :)

The idea of increasing gaps between lines and columns however doesn't seem like a good choice to me, but if you want to discuss that further, please feel free to do so in #1065.
