### ISSUE TITLE
Unable to use floating point for font offset

### ISSUE THREAD

**Issue by ghost** [jwilm/alacritty#1371]
On macOS High Sierra (10.13.2) I'm unable to set the font x-offset to a floating point like 0.5. This is unfortunate because for many fonts 1 is too wide and 0 is too thin.

I read [**here**](https://github.com/jwilm/alacritty/issues/1308) that a fairly recent change forced all font offsets to be whole integers. Is there any way to get floating points back?

**Comment by chrisduerr** [comment]
The reason why the font offset forced all offsets to be whole integers is because it has always been an offset by pixels, so offsetting by half a pixel wasn't possible.

IIRC internally the offset has always been rounded/truncated to whole numbers, so there wasn't much point to represent that with floating point numbers internally.

**Comment by chrisduerr** [comment]
Closing this issue since I don't think there's any issue here? If you would like to investigate this a bit more, feel free to reopen. But I don't think it's possible to offset by fractional pixels.

**Comment by chrisduerr** [comment]
It might be possible to switch this up so the offsets use floats instead of whole numbers, however I'm not quite sure how the renderer would handle offsets by fractional pixels. It's possible that it is just not possible to offset a glyph by .3 pixels.

**Comment by bchbchbch** [comment]
Hmm, I thought OpenGL used floats. Presumably the offset is converted to a translation matrix of floats? Or does Alacritty use integers internally in a way that's hard to change?

**Comment by chrisduerr** [comment]
The font renderer itself (at least on linux) is definitely unable to do subpixel alignment. However it's possible that OpenGL uses floats, so it might still make a slight difference with rounding.

I believe I've looked at parts of the OpenGL code before and they supported floats, but I'd have to check again to be 100% certain.

**Comment by jwilm** [comment]
The problem with this for us is that we rasterize glyphs aligned to the pixel grid and then simply copy them from a texture at draw time. Spreading a glyph across 2 pixels in this case will result in **terrible** appearance. Correctly doing fractional pixel offsets requires the rasterizer to know that a glyph is being shifted 0.x pixels to the side, and then it can decide to use just a fraction of neighboring pixels.

Anyway, the OP disappeared and I don't have any plans to address this.
