### ISSUE TITLE
Slow performance when outputting many lines

### ISSUE THREAD

**Issue by ibrokemypie** [jwilm/alacritty#1380]
Which operating system does the issue occur on?
arch linux

If on linux, are you using X11 or Wayland?
x11

When running cat /dev/urandom, alacritty noticeably slows down compared to other terminals such as xiate and kitty.

**Comment by chrisduerr** [comment]
`cat /dev/urandom` is probably the most inconsistent source four outputting a large number of lines.

Can you reproduce this using the following code?
```
yes | dd count=100k > out
time cat out
```

Also what exactly do you mean by "noticeably slows down", is there any specific metric you can give?

**Comment by ibrokemypie** [comment]
Using that code alacritty does perform much faster, perhaps it is the fact that urandom draws many different characters across the screen?

By noticeably slows down I mean the rate that the terminal updates is a lot slower, both terminals seem to slow down outputing a full screen of text at a time, but alacritty has great pauses between each screen update.

**Comment by chrisduerr** [comment]
This could be related to what has slightly been discussed in https://github.com/jwilm/vtebench/pull/6.

It seems like this is also already tracked in #511, so further discussion should probably happen in there.
