### ISSUE TITLE
Control + Shift + Left/Right + tmux

### ISSUE THREAD

**Issue by zackhsi** [jwilm/alacritty#1385]
Which operating system does the issue occur on? `macOS 10.13.5`

I am not entirely sure this is an alacritty issue, but I was hoping someone who has more expertise than I do would be able to help me out :)

I have a [tmux keybinding](https://github.com/zackhsi/dotfiles/blob/95dcb1ecfc6c44f5972c6dfb0ecf9514618bfda9/sources/tmux.conf#L60-L62) whereby I can press control, shift, and the left/right arrows in order to rearrange a session's windows. This does not work properly in alacritty, for reasons unknown to me.

I have already [updated my alacritty.yml config](https://github.com/zackhsi/dotfiles/commit/95dcb1ecfc6c44f5972c6dfb0ecf9514618bfda9), and _I believe_ that alacritty and iterm are sending the same escape sequence. My test is that when I press control+v, and then I press control+shift+arrow, I see the same thing printed to the screen for iterm and alacritty, which is:

```bash
# Control+Shift+Left
^[[1;6D
# Control+Shift+Right
^[[1;6C
```

However, the desired tmux window rearrangement does not happen. Either something is up with the escape sequence, or something peculiar is happening when tmux listens to `bind`-ed keystrokes...or something else entirely. Please help!

**Comment by snoblenet** [comment]
related to this? https://github.com/jwilm/alacritty/issues/1336

**Comment by zackhsi** [comment]
Moving all custom keybindings to the bottom of my config seems to have fixed the issue.
