### ISSUE TITLE
Quadruple click for "smart select"

### ISSUE THREAD

**Issue by zackhsi** [jwilm/alacritty#1399]
Hi, I'm a fan of the iTerm features for smart selection, details [here](https://www.iterm2.com/documentation-general-usage.html).

Thanks!

**Comment by chrisduerr** [comment]
Alacritty's double-click already is a semantic selection that reacts based on the content which is present. However making this select URLs has been requested previously and it is possible to do so by switching away from the semantic escape characters to something slightly more powerful like regex.

See #1210 for more discussion around this.

**Comment by zackhsi** [comment]
They are two separate features. I like my double click how it is (I have added `.`, `/`, `-` to my list and am happy). Separately, I would like quadruple click to do the things mentioned in the thread. Perhaps a different set of semantic escape chars is all I need, e.g. don't escape on hyphen if I quadruple click.

**Comment by chrisduerr** [comment]
Semantic selection is already present in Alacritty, for tracking improvements like URL detection there's https://github.com/jwilm/alacritty/issues/1210 to track it.
