### ISSUE TITLE
Semantic selection behaving unexpectedly with wrapped lines on scrollback

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1406]
I've noticed an interesting behavior with semantic selection in combination with linewraps. This issue consists of these two problems:

#### Live selection updating

Every time the user scrolls in the scrollback PR, the semantic selection is re-calculated. This leads to selection changing in combination with the problems caused by other issues.
This shouldn't be a huge issue though, but searching for semanatic escapes every time the user scrolls doesn't seem like a great idea for performance.

#### Selection across viewport borders

When the first line in the viewport is a line which wrapped from the previous line (which is outside of the viewport), the selection itself only goes to the beginning of the line, instead of wrapping to the line outside of the viewport. This can be observed by pasting the selection made. As soon as the user scrolls up now, the selection is updated.

#### Selection off-by-one
When double-clicking the last `e` in `"teee[...]est"`, the selection is displayed correctly (`teee[...]est`), however the text copied is `teee[...]est"`. This is only a problem whith linewraps, it doesn't happen if the word is a single line. The viewport is irrelevant here.

**Comment by nixpulvis** [comment]
@chrisduerr unless I'm mistaken, d20931950d498457832488a6ec12f25951d9b184 doesn't fix the "Live selection updating" issue, though I'm happy to report it does fix the "Selection across viewport borders" issue.

As for "Selection off-by-one" I'm honestly not 100% sure what you mean? I'm assuming `[...]` means enough `e`s to pass onto a new line, but I'm not able to replicate an issue copying the trailing `"` on the scrollback branch or master. I'm also happy to report that the scrollback branch correctly selects the whole `teeeeee[...]est` across lines, unlike master in the few cases I tested.

**Comment by chrisduerr** [comment]
That is correct, the PR doesn't change anything about the live selection updating, since I'm not entirely sure if a change to that mechanic is desired.

The "Selection off-by-one" seems like something that was caused inside the PR itself, at least I can't reproduce it with the latest master. So that shouldn't be an issue.

**Comment by chrisduerr** [comment]
I'm going to close this issue because the only problem left in scrollback right now is the live selection updating which doesn't have any effect on the user.

If desired it should be possible to change this behavior, however I'd like to hear from @jwilm why this is done the way it currently works instead of having the semantic selection immutable after the LMB is not held down anymore.
