### ISSUE TITLE
Ctrl+{arrow key} does not jump word

### ISSUE THREAD

**Issue by bpierce1** [jwilm/alacritty#1408]
First, let me say alacritty is great! I'm trying to fully make the switch. However, I'm running into an issue even with the default config. When I type `ctrl+left-arrow` or `ctrl+right-arrow`, I get `;5D` (left) or `;5C` (right). 

If I go into an Ubuntu 18.04 docker container, the problem goes away. 

Any suggestions?

Which operating system does the issue occur on?
OS X

If on linux, are you using X11 or Wayland?

**Comment by bpierce1** [comment]
I solved the problem by replacing the lines in the config:

```
  - { key: Left,      mods: Control, chars: "\x1b[15c"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
```
with
```
  - { key: Left,     mods: Control, chars: "\x1bb"                       }
  - { key: Right,    mods: Control, chars: "\x1bf"                       }
```

**Comment by aepsil0n** [comment]
Just in case any zsh user happens to stumble on this like I did: it's not Alacritty, it's zsh. You have to bind the keys in `.zshrc`:

```sh
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
```

→ [StackExchange: Ctrl + left/right arrow keys issue](https://unix.stackexchange.com/questions/58870/ctrl-left-right-arrow-keys-issue)

**Comment by Paul1987** [comment]
I was able to resolve this by upgrading to the latest version of `zsh`.

**Comment by BellaRany04** [comment]
bellarany65@gmail.com

**Comment by BellaRany04** [comment]
Facebook business

**Comment by BellaRany04** [comment]
bellarany04@gmail.com

**Comment by BellaRany04** [comment]
bellarany65@gmail.com
