### ISSUE TITLE
unhandled osc_dispatch CursorShape - neovim cursor shape not working on some machines

### ISSUE THREAD

**Issue by haadr** [jwilm/alacritty#1409]
Which operating system does the issue occur on?
Debian stretch on plasma

If on linux, are you using X11 or Wayland?
X11

Hi all!

I've got a strange problem. I'm using neovim with alacritty. The cursor shape changes correctly on *one* of my installs/machines, but not my three other debian stretch installs. 

I've tried everything from both neovim's and this issue tracker, as well as trying different versions and compiling neovim (and obviously alacritty) myself. I even copied the neovim and alacritty binaries around, but it always works on one machine and not the others. It must be something else on the systems which causes this, so I'm asking for advice here.

Note: Cursor shape changes successfully in other terminals, like konsole.

What other libraries are called by alacritty for which the versions might differ? What could be causing this? 

# Versions
* built via cargo, checkout alacritty-de74975f496aa2c0
* neovim, tried 0.2.2-3, 0.3.0 and master

# Expected behaviour
When launching `nvim -u NONE` in alacritty I press insert and expect the cursor shape to change.

# Actual behaviour
No cursor shape change.

# Alacritty output
Start nvim and entering/exiting insert mode a few times:
```
[Unhandled CSI] action='t', args=[8, 18, 89], intermediates=[]
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','0',],['B','l','i','n','k','i','n','g','C','u','r','s','o','r','E','n','a','b','l','e','d','=','0',],] at line 746
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','0',],['B','l','i','n','k','i','n','g','C','u','r','s','o','r','E','n','a','b','l','e','d','=','0',],] at line 746
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','1',],['B','l','i','n','k','i','n','g','C','u','r','s','o','r','E','n','a','b','l','e','d','=','0',],] at line 746
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','0',],['B','l','i','n','k','i','n','g','C','u','r','s','o','r','E','n','a','b','l','e','d','=','0',],] at line 746
[unhandled osc_dispatch]: [['5','0',],['C','u','r','s','o','r','S','h','a','p','e','=','1',],['B','l','i','n','k','i','n','g','C','u','r','s','o','r','E','n','a','b','l','e','d','=','0',],] at line 746
```

**Comment by haadr** [comment]
Actually, I only just noticed upgrading my glibc from version 2.24 (debian stretch) to 2.27 (testing/unstable), make the cursor shape change work. 

Is this a bug with alacritty, or is there a glibc version requirement not caught/enforced by during compilation?

**Comment by chrisduerr** [comment]
I haven't heard of this `glibc` version requirement before. I haven't noticed any issues like that myself.

However there's an open PR #1315 that should fix this. I'm not sure why updating to 2.27 resolved this issue for you.

**Comment by haadr** [comment]
Good to know about the PR. 

For what it's worth, I also had another issue which now seems connected to this one.

When running alacritty via krunner (kde's "Run program" thing), and then running nvim within that alacritty instance, alacritty would crash upon entering insert mode. This was also fixed by upgrading glibc. I couldn't find anything about enabling log files, so I can't provide any concrete error message for that.

**Comment by chrisduerr** [comment]
Closing this issue since the PR has been merged.

You're not actually running into the missing cursor escape issue @j605. Neovim will not try to reset the cursor shape if your `TERM` is set to `xterm-256color`, which Alacritty uses.

The only thing Alacritty could do about this, would be to make use of a custom terminfo, which has been explored here: #1491.

However there is a way to fix this, you can simply manually reset the cursor yourself when closing vim. Here's how I do it:
https://github.com/chrisduerr/dotfiles/blob/master/files/init.vim#L98-L99
