### ISSUE TITLE
Mouse input doesn't go past row 223

### ISSUE THREAD

**Issue by daurnimator** [jwilm/alacritty#141]
If you set a terminal to be *very* tall, then click + drag, after row 223 you no longer get events.

Likewise for columns for a very wide terminal

**Comment by jwilm** [comment]
What environment are you experiencing this in? At least with vim, you can get SGR reporting with `set ttymouse=sgr`.

**Comment by daurnimator** [comment]
I was testing using https://github.com/daurnimator/lua-tui/blob/master/examples/echo_input.lua

**Comment by jwilm** [comment]
Ah, great! SGR events will only be delivered if the application asks for them.

**Comment by daurnimator** [comment]
With other terminals, the byte wraps overflows around so you get at *least* 255 rows/columns. (often they wrap around and keep going)

**Comment by jwilm** [comment]
Was there some action required here? SGR events are designed to solve this problem.

**Comment by chrisduerr** [comment]
@jwilm Is this fixed with #1001?
