### ISSUE TITLE
High cpu usage and improper window display and positioning

### ISSUE THREAD

**Issue by steakiestsauce** [jwilm/alacritty#1414]
Operating System - Linux, Wayland, Gnome 3.28.2

-- intro --
Hello I recently tried out alacritty on my desktop for the first time and installed the binary through cargo using rust stable 1.27 

-- problem one -- 
When launched, the alacritty window appears in the top left corner beyond the screen (unable to access titlebar to move the window) and the gnome activities area doesn't allow me to select it and displays it in the wrong position
![screenshot from 2018-07-04 23-11-59](https://user-images.githubusercontent.com/33026478/42285113-203b66b6-7fe1-11e8-92a6-4010b96dd0ee.png)
![screenshot from 2018-07-04 23-11-25](https://user-images.githubusercontent.com/33026478/42285117-22a3e6ee-7fe1-11e8-976c-ab9d21b93b4b.png)
 
-- problem two --
Alacritty appears to use 25% of the cpu, probably because the cpu usage is limited to one core
![screenshot from 2018-07-04 23-12-32](https://user-images.githubusercontent.com/33026478/42285214-6c2786b8-7fe1-11e8-8786-6e7f2a001c84.png)

**Comment by chrisduerr** [comment]
Thanks for reporting this issue! :)

Have you tried the Wayland workaround mentioned in the README? Try starting Alacritty with `env WAYLAND_DISPLAY= alacritty`.

Unfortunately Wayland support is still a work in progress, since Wayland itself is still a bit of a work in progress. Hopefully that will make it work for you!

**Comment by steakiestsauce** [comment]
Thank you, running with XWayland does seem to fix the issues, I should of really read the whole README

**Comment by chrisduerr** [comment]
I'd be interested to hear what @jwilm thinks about wayland issues on github. Should they just all be tagged with Wayland? I can imagine that these will probably be around a lot longer than usual.

Or maybe it makes sense to have a wayland tracking issue that contains a checklist with all major wayland related issues that still need to be resolved? It would be possible to either close the other issues or keep them around and use them to track the individual problems. But that would give a central place to look if a wayland issue has already been reported or not.

**Comment by jwilm** [comment]
@chrisduerr for now I would like to keep tagging things with `Wayland`. At the point we want to invest time into improving Wayland support, we can generate such a checklist issue and probably a GH project.

**Comment by trimental** [comment]
This was fixed in https://github.com/Smithay/client-toolkit/commit/a1805b749dd4aa80d48159c52ddd907ddd6d6d28 which will be in https://github.com/jwilm/alacritty/pull/1403
