### ISSUE TITLE
Replace runtime sizeof assertions with static asserts on scrollback

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1419]
To enable compile-time checking of `debug_assert!(mem::size_of::<T>() == foo);` blocks, the crate `static_assertions` should also be introduced on the scrollback PR.

This change has already been introduced on the latest master with #1418 (#1417), so following along with this should make it easy for anyone to get started with this. I've tagged this issue as `easy` and `help wanted` to give new people a shot that might not be comfortable starting out with bigger issues, this should be something everyone is capable off.

To make this work [this](https://github.com/jwilm/alacritty/blob/07aaf05f7463a971e56de87e3b6b24e4153e5a98/src/grid/storage.rs#L232) is the place which needs to be changed.

If there are any questions feel free to comment on this issue or ask in the #alacritty irc on freenode.

**Comment by felipesere** [comment]
With the PR merged, I assume this issue could be closed?

**Comment by chrisduerr** [comment]
Thanks for the notification! Github doesn't auto-close unless a commit is merged to master. This is good to go though on scrollback.
