### ISSUE TITLE
Error building for macOs following instructions

### ISSUE THREAD

**Issue by favetelinguis** [jwilm/alacritty#1421]
Which operating system does the issue occur on?
macOs 10.13.4 (17E199)

Following the instructions on the make page for installing on macOs i get the following error after cloning:

```
D-MBP:alacritty D$ make app
cargo build --release
make: cargo: No such file or directory
make: *** [alacritty] Error 1
```

**Comment by jwilm** [comment]
You'll need to [install the rust compiler toolchain](https://github.com/jwilm/alacritty#installing-rust-compiler-with-rustup).
