### ISSUE TITLE
How to type umlaut on Mac OS?

### ISSUE THREAD

**Issue by cideM** [jwilm/alacritty#1423]
Which operating system does the issue occur on? macOS High Sierra (it probably existed in prior macOS releases too)

In other apps I can type option + u followed by a character to type e.g., ü, ä or ö. It works in iterm and kitty, but in alacritty it just displays a normal u, a or o. I am using the default keybindings that come with alacritty. It occurs in alacritty proper, regardless of `tmux`, `vim`, or `neovim` usage.

**Comment by CarlosEvo** [comment]
For me I just use the German input method along side English (and Chinese, not in Alacritty tho)

**Comment by cideM** [comment]
@CarlosEvo what do you mean by German input method? Choosing a German keyboard layout would be extremely inconvenient for me as the physical keyboard layout and keycap legends are US. It's an extremely rare occurrence that I have to type an umlaut in a terminal. But I recently wanted to edit some Latex documents and it felt clunky in Texmate so I wanted to just edit the files in `neovim` directly. That's when I realized the umlaut thing (the document is in German).

**Comment by cideM** [comment]
@CarlosEvo I prefer a US layout though. But it's strange that it works for you. Here's a short [clip](http://recordit.co/askt9gWBYj) showing the behavior. In both cases I hit `alt+u u`.

**Comment by CarlosEvo** [comment]
@cideM The US layout was visible because the stickers are transparent. But anyhow, I am using a pretty recent build of `alacritty`. I did not change much in the config other than some character spacing and fonts... I saw you have big `y` offset, maybe that affects it?

**Comment by cideM** [comment]
Resetting the offsets didn't change. I am running version `0.1.0` by the way.

**Comment by CarlosEvo** [comment]
@cideM I am not aware of such a version. In fact I doubt it has a version yet... I would just pull the latest commit from the repo and compile it

**Comment by h-michael** [comment]
@cideM 
Alacritty is v0.1.0 from 2 years ago.
I think Alacritty is not stable, so I build Alacritty every time PR merged to master.

**Comment by cideM** [comment]
@h-michael I had gotten that version from `cargo.toml` which was a bad idea and misleading for this ticket, sorry about that. Could very well be that I was using a really outdated version? I built it from source and now it's working just fine. Thanks!
