### ISSUE TITLE
macOS no longer able to bind Command + Period

### ISSUE THREAD

**Issue by fallwith** [jwilm/alacritty#1428]
I'm on macOS. I just grabbed the latest code (7433f45ff9c6efeb48e223e90dd4aa9ee135b5e8) and built a fresh app via `make app`.

A previous keybinding of mine has stopped working. I had mapped `Command + Period` to send `\x03` as suggested by jwilm via freenode to match the default behavior of macOS's built-in Terminal app. With this latest code base the binding no longer works.

The character sequence in question works great when bound to any other key combination. I am unable to get `Command + Period` to bind to anything, be it my desired character sequence or any other characters or action.

```yaml
# used to work but no longer does
  - { key: Period,   mods: Command, chars: "\x03"                        }

# works fine (Alt instead of Command)
  - { key: Period,   mods: Alt,     chars: "\x03"                        }

# does not work - can't bind Command + Period to anything?
  - { key: Period,   mods: Command, action: IncreaseFontSize             }
```

**Comment by chrisduerr** [comment]
I highly doubt that the commit you've linked is actually what broke this functionality. Would you mind bisecting which commit exactly introduced this regression for you?

Also please make sure that there are no syntax errors in your config, you can do so by starting alacritty from the CLI to capture the stderr, if there's any output while starting alacritty from a different terminal session, there's probably something wrong with your configuration file.

**Comment by fallwith** [comment]
Thanks, @chrisduerr - I took a look at the CLI output on startup and the only thing reported was an issue with my alacritty.yml having old (default) `0.0` values for font offsets that have since changed to `0`. I updated my config and there's nothing echoing out now on startup. No change for the issue.

I'll try to pinpoint the specific commit that broke my desired functionality and report back.

**Comment by fallwith** [comment]
@chrisduerr the commit that broke things for me is 765949f256aefcc513d0bfb46b64d315f9c2f3d2
 ("Update to glutin 0.16.0").

**Comment by chrisduerr** [comment]
Yeah that makes sense. Winit 0.15 has overhauled keyboard support in macos, I'd assume this might be a regression introduced there. Is `Period` the only key which is creating issues with `Command`? I'd be interested to know if others are also causing trouble.

I'd also be interested in seeing exactly which keys are reported when you press `Command + Period`. If you have some time and feel like investigating, here's a patch which will write exactly which keys are reported to stdout: https://paste.rs/slY. I'd be interested in seeing the output of this when you hit `Command + Period`.

**Comment by fallwith** [comment]
Thanks, @chrisduerr - I'll try other `Command` based combinations and I'll try your patch and report back on both items.

**Comment by chrisduerr** [comment]
Thanks for the help with troubleshooting this, it's very much appreciated!

**Comment by fallwith** [comment]
@chrisduerr 

These three (default) bindings involving the `Command` key but not the `Period` key work just fine:

```
  - { key: Key0,     mods: Command, action: ResetFontSize                }
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Minus,    mods: Command, action: DecreaseFontSize             }
```

With your patch applied, if I press and then release `Command + Period`, the following is printed:

```
STATE: Released, KEY_CODE: Some(RWin), MODIFIERS: ModifiersState { shift: false, ctrl: false, alt: false, logo: true }
STATE: Released, KEY_CODE: Some(RWin), MODIFIERS: ModifiersState { shift: false, ctrl: false, alt: false, logo: false }
```

**Comment by fallwith** [comment]
The same debug output can be produced by pressing and releasing the `Command` key by itself. It's as if `Period` doesn't register at all when `Command` is pressed.

For comparison, here's the output produced by pressing and releasing `Alt + Period`:

```
STATE: Released, KEY_CODE: Some(LAlt), MODIFIERS: ModifiersState { shift: false, ctrl: false, alt: true, logo: false }
STATE: Pressed, KEY_CODE: Some(Period), MODIFIERS: ModifiersState { shift: false, ctrl: false, alt: true, logo: false }
STATE: Released, KEY_CODE: Some(Period), MODIFIERS: ModifiersState { shift: false, ctrl: false, alt: true, logo: false }
STATE: Released, KEY_CODE: Some(LAlt), MODIFIERS: ModifiersState { shift: false, ctrl: false, alt: false, logo: false }
```

**Comment by chrisduerr** [comment]
I'd assume that there might be some IME stuff going on where it's waiting for additional keystrokes or something like that.

@francesca64 you probably know best about these kind of things, are you aware of a bug like this?

Also I hope it's okay to ping you for winit/glutin related stuff, but I don't really want to always put the burden on you. So if you would prefer it I could instead also open issues on the winit/glutin repo, so you have more control about when you want to get to it (or someone else might be able to).

**Comment by francesca64** [comment]
Well, the best reason for opening an issue on winit instead is because I totally forgot about this for 2 days... it's a lot simpler from an organization perspective.

I don't mind being pinged on principle or anything, but my stress levels have been higher lately, so the results will reflect that.

Since macOS keyboard issues are still abundant, the plan of attack is to compare against the implementations of `NSTextInputClient` in SDL, GTK, and Qt: 

- https://github.com/spurious/SDL-mirror/blob/b00ee82424a5a8198e2556f960e8a09bfe584b26/src/video/cocoa/SDL_cocoakeyboard.m#L47
- https://github.com/GNOME/gtk/blob/83a80ab86640c4b24698c9755e9699ae3cce0d33/gdk/quartz/GdkQuartzView.c#L26
- https://github.com/qt/qtbase/blob/1ef03f69e8416a70efd14df09e1231ce0bc00ea9/src/plugins/platforms/cocoa/qnsview.mm#L126

When I'll get a chance to do that is anyone's guess, but it at least looks pretty straightforward (and these resources would make it manageable for someone else to take a crack at it).

**Comment by francesca64** [comment]
Nope, no issue was made. If you went ahead with that, that would be super!
