### ISSUE TITLE
terminal is not response after python pdb

### ISSUE THREAD

**Issue by kaldown** [jwilm/alacritty#1430]
debian 9
x11
tmux

try to run some services in python, and stop, using pdb
then hot-reload service (while debug is still stopped)
after that, you can not use this terminal.

Output works, but but input - not

**Comment by chrisduerr** [comment]
Does this work in other terminal emulators? Also is it possible to use something like Ctrl+C or Ctrl+D to kill anything that might be potentially taking up the input? If nothing of this works, maybe typing `reset` will do the job, even if it's not shown in the prompt, it might allow resetting the terminal state.

**Comment by kaldown** [comment]
No, it's impossible
The only way - `pkill`
Ok, I'll try with other emulators

**Comment by kaldown** [comment]
reset wont work
and it's repeats even in xfce4-terminal
I guess I need to investigate some time to find a problem source
sorry for misleading
