### ISSUE TITLE
Getting [unhandled osc_start]

### ISSUE THREAD

**Issue by daurnimator** [jwilm/alacritty#144]
```
[unhandled osc_start]
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=';'
[unhandled osc_put] byte='d'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='m'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='o'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='@'
[unhandled osc_put] byte='d'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='u'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='n'
[unhandled osc_put] byte='-'
[unhandled osc_put] byte='z'
[unhandled osc_put] byte='1'
[unhandled osc_put] byte='7'
[unhandled osc_put] byte='0'
[unhandled osc_put] byte=':'
[unhandled osc_put] byte='~'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='s'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='/'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='l'
[unhandled osc_put] byte='a'
[unhandled osc_put] byte='c'
[unhandled osc_put] byte='r'
[unhandled osc_put] byte='i'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='t'
[unhandled osc_put] byte='y'
[unhandled osc_end] byte=0
Goodbye
```

This seems to be some issue with handling my PS1 prompt? (this might be my fault!).
xxd output of my bash prompt:
```
00000000: 011b 5b33 336d 0230 312d 3037 2031 333a  ..[33m.01-07 13:
00000010: 3530 3a32 3320 011b 5b30 3b31 6d02 6461  50:23 ..[0;1m.da
00000020: 7572 6e69 6d61 746f 7201 1b5b 306d 0240  urnimator..[0m.@
00000030: 011b 5b33 326d 0264 6175 726e 2d7a 3137  ..[32m.daurn-z17
00000040: 3020 011b 5b31 3b33 346d 027e 2f73 7263  0 ..[1;34m.~/src
00000050: 2f61 6c61 6372 6974 7479 011b 5b30 6d02  /alacritty..[0m.
00000060: 2001 1b5b 3332 6d02 6769 743a 7b6d 6173   ..[32m.git:{mas
00000070: 7465 722e 2e2e 6f72 6967 696e 2f6d 6173  ter...origin/mas
00000080: 7465 723a 6337 3332 3935 377d 2001 1b5b  ter:c732957} ..[
00000090: 306d 0224 2001 1b5b 306d 02              0m.$ ..[0m.
```

Note that bash will eat the `\1` and `\2` (bash uses them as delimiters to know what chars to count for positioning the cursor)

**Comment by jwilm** [comment]
This is Alacritty not handling that your shell wants to set the terminal title. There's an issue for that feature already: #23. Going to close this as a duplicate.

**Comment by daurnimator** [comment]
This is not setting a terminal title.

**Comment by jwilm** [comment]
Oh, I'll have to look more closely. Sorry about that!

**Comment by daurnimator** [comment]
I thought this issue wasnt about title?

**Comment by jwilm** [comment]
Part of the `'0'` OSC turns out to be setting the title. Also notice that your PS1 has more data than provided in the OSC.

http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands

**Comment by daurnimator** [comment]
But OSC is `\27` (`\33` in hex) then `]`. That doesn't appear anywhere in my output.

**Comment by jwilm** [comment]
That's right. The parser eats those bytes and only provides the OSC arguments to the `osc_dispatch` method.

**Comment by daurnimator** [comment]
I'm confused.... looking at my `xxd` output there is no `[` (which is part of an OSC sequence)

**Comment by jwilm** [comment]
OSC can also be initiated by `0x9d`.

**Comment by daurnimator** [comment]
Okay yes: but that is not in the xxd output either.

**Comment by jwilm** [comment]
In the middle of the second line

```
00000010: 3530 3a32 3320 011b 5b30 3b31 6d02 6461  50:23 ..[0;1m.da
```

I see `011b 5b30` which includes the osc start `1b` and `5b`.

We're still talking about the output in original issue, right?

**Comment by daurnimator** [comment]
yes. 5b is `[`. OSC uses `]` (5d).

**Comment by jwilm** [comment]
Looking at the parser definition, there's only two ways to begin the OSC:

```rust
    State::Anywhere => {
        0x9d        => State::OscString,
    },
    State::Escape => {
        0x5d        => State::OscString,
    }
```

So the initial log that shows an OSC starting seems very likely to be correct. I'm no longer convinced that the `xxd` dump below it is for the same segment of protocol as the stderr logs.

**Comment by bluss** [comment]
Fwiw, the unhandled errors from my prompt or prompt command setting the title looked exactly the same.
