### ISSUE TITLE
Documentation Request - How to enable scrollback?

### ISSUE THREAD

**Issue by brycefisher** [jwilm/alacritty#1441]
I'd like to propose a wiki with instructions for building a scrollback enabled version of alacritty. Periodically, I try to rebuild Alacritty and I always forget that the project does not include scrollback in master. My guess is that many other users of this project would also value a canonical way to get a scrollback-enabled build as well, but perhaps I'm mistaken.

(I'd much prefer to have a cargo feature for toggling scrollback support at compile time, but I realize that adds a lot of ongoing complexity that may be not desirable.)

**Comment by chrisduerr** [comment]
I don't think officially documenting how to build PRs is going to be beneficial. I'd much rather push for merging Scrollback into Master, since it has been progressing nicely and as far as I know there's only one major issue left.

There are still a few minor issues, but I'd consider them non-blocking. Having a PR as an acceptable version of Alacritty would just encourage keeping them separated imho.

**Comment by nixpulvis** [comment]
It's an interesting question of what kinds of features should be Cargo features. I'm not sure what @jwilm or @chrisduerr think about making scrollback a compile-time option, but I personally wouldn't mind it. It does make packaging the application more complex however.

**Comment by chrisduerr** [comment]
There's no benefit in making Scrollback a compile-time feature. It's too complex to make it completely opt-in and there is no disadvantage to just setting the history size to `0` if the code is always present anyways.

So while compile time options might make sense for other things, for scrollback it seems pointless to me.

**Comment by brycefisher** [comment]
Ok! Adding this to master makes sense to me, especially if scrollback does
not impact performance for those wishing to opt-out.

Totally agree, a cargo feature for this would make the code much, much more
complex and a wee bit horrible.

I'll close out this issue.
