### ISSUE TITLE
issue with rbenv

### ISSUE THREAD

**Issue by tuananh** [jwilm/alacritty#1444]
Which operating system does the issue occur on?
macOS

If on linux, are you using X11 or Wayland?

I'm using zsh with oh-my-zsh. i installed rbenv via homebrew and add this line to my `.zshrc`

    eval "$(rbenv init -)"

In iTerm2 or Terminal, it works as expected. However in Alacrity, i got `command not found: rbenv` error.

**Comment by chrisduerr** [comment]
I don't know much about MacOS, but there have been a few issues reported which seem similar.

I would recommend checking out the locale which is set and making sure the .app is installed properly.

**Comment by benmp** [comment]
You need to change the shell login command in your alacritty.yml file.  macOS doesn't perform the same kind of login everytime like linux does.  I had similar issues with nodejs until I did this.

```
shell:
  program: login
  args: ["-fp", "your.username"]

**Comment by tuananh** [comment]
@benmp i change to 

```
shell:
  program: /usr/local/bin/zsh
  args: ["-fp", "myusername"]
```

and Alacritty won't start again. Any idea?

**Comment by chrisduerr** [comment]
Try running `zsh -fp username` and you'll notice that will not work, so this will not work either.

The program itself (`login`) also is important on macos. Just starting the shell will not give you the desired results iirc.

**Comment by sodiumjoe** [comment]
try
```
shell:
  program: /usr/local/bin/zsh
  args: ["--login"]
```

**Comment by tuananh** [comment]
thank you. it works for me now
