### ISSUE TITLE
Build and install instructions for Ubuntu/Debian in Readme

### ISSUE THREAD

**Issue by zaript** [jwilm/alacritty#1445]
Information about prerequisites comes after build instructions raising unnecessary confusion. Before opening PR I wanted to confirm that there is no bigger idea behind current structure.
Also prerequisites missing gperf.

**Comment by chrisduerr** [comment]
Which install instructions are you talking about specifically? I don't think `gperf` is required for building Alacritty.

**Comment by zaript** [comment]
@chrisduerr I am referring to the fact the the Debian/Ubuntu installation instructions section (https://github.com/jwilm/alacritty#debianubuntu) comes before the manual installation section (https://github.com/jwilm/alacritty#debianubuntu-1), that lists required dependencies.

Also I had the same dpkg issue as @acirtautas

**Comment by chrisduerr** [comment]
I'm not actually aware of any dependency to `gperf`, unless `.deb` itself requires this. Could anyone of you (@acirtautas / @zaript) test if the application builds correctly when this dependency is removed from the `Cargo.toml`?

I'm going to open a PR to rework the section about the `deb` a bit, it would be nice to remove the useless dependency if it's not required.

**Comment by zaript** [comment]
@chrisduerr I've got successful deb install after removing gperf from the system and from the Cargo.toml. This dependency is redundant.

**Comment by chrisduerr** [comment]
I've created this [Installation](https://github.com/jwilm/alacritty/wiki/Installation) wiki page in an attempt to rework the installation instructions in the README.

@zaript Please let me know if you'd consider this an improvement or leave any other kind of comments you have.

**Comment by zaript** [comment]
@chrisduerr The wiki page looks good to me. I played with idea of creating separate "full guide" sections for each distribution for people who just came for quick all-in-one-place solution, but there are too much repetition.

**Comment by chrisduerr** [comment]
Yeah I've thought about that too. I've also thought about having a subsection for each distribution which would just walk through everything.

I'll keep this as a wiki for a bit, if you or anyone else see any potential improvements, feel free to add them directly. I believe everyone is able to edit wiki pages.

**Comment by chrisduerr** [comment]
It seems like `apt-get -f install` will install all missing dependencies after doing `cargo deb --install`. If this works, just adding this to the README might be enough.

Can someone confirm that this works?

**Comment by chrisduerr** [comment]
The instructions have been recently updated to structure everything a bit more clearly. That should hopefully resolve this issue.
