### ISSUE TITLE
Cargo-deb: unable to parse Cargo.toml (profile.release.debug)

### ISSUE THREAD

**Issue by acirtautas** [jwilm/alacritty#1446]
cargo deb --install    
    cargo-deb: unable to parse Cargo.toml
       because: invalid type: integer `1`, expected a boolean for key `profile.release.debug`

https://github.com/jwilm/alacritty/blob/3dabb9783e13580ba283942d632c5469eca8956a/Cargo.toml#L61

I believe it expects a true/false value

**Comment by enizor** [comment]
duplicate of #1438
