### ISSUE TITLE
home_dir function deprecated since rustc 1.29.0-nightly

### ISSUE THREAD

**Issue by blueswhisper** [jwilm/alacritty#1447]
OS:  
macOS Sierra(10.12.6)
active toolchain:
nightly-x86_64-apple-darwin
rustc 1.29.0-nightly (12ed235ad 2018-07-18)

Reproduce:

```bash
cd alacritty
make app
```

Output:
```bash
warning: use of deprecated item 'std::env::home_dir': This function's behavior is unexpected and probably not what you want. Consider using the home_dir function from https://crates.io/crates/dirs instead.
  --> src/main.rs:51:26
   |
51 |     env::set_current_dir(env::home_dir().unwrap()).unwrap();
   |                          ^^^^^^^^^^^^^
   |
   = note: #[warn(deprecated)] on by default
```

std::env::home_dir function has been deprecated since 1.29.0,  alacritty should follow the advice to replace it with `home_dir` function provided by [dirs](https://crates.io/crates/dirs ) crate.

**Comment by chrisduerr** [comment]
Thanks for the report!

I've attempted to fix this in #1450, however I'm not able to test this myself since I don't have a macOS machine. Travis signing this off should be enough, but I'd appreciate any testing help I can get!

**Comment by blueswhisper** [comment]
I mean `std::env::home_dir` is not only deprecated in macOS, but also Windows & Linux. It is not an platform specific function.  Please refer to [nightly std doc](https://doc.rust-lang.org/nightly/std/env/fn.home_dir.html). 

BTW I'd love to help testing.

**Comment by blueswhisper** [comment]
I see.  
I have check out you PR branch on my macOS, build warning has disappeared. Nice work! 👍

**Comment by chrisduerr** [comment]
Thanks for the feedback, going to merge this PR then!
