### ISSUE TITLE
Add support for dim foreground color

### ISSUE THREAD

**Issue by dsifford** [jwilm/alacritty#1448]
> Which operating system does the issue occur on? ==> **Arch Linux**
> 
> If on linux, are you using X11 or Wayland? ==> **X11**

Hello there.

To my knowledge, it appears that alacritty does not support the dim escape sequence (and associated color setting in alacritty.yml) for the foreground color.

Could this be added? Or if it exists, how do I adjust?

Thanks in advance.

**Comment by dsifford** [comment]
Example: This works in xterm (and others), but not alacritty:

```sh
echo -e "Normal \e[2;31mDim \e[22mNormal"
```

**Comment by chrisduerr** [comment]
Just to clarify here: Dim colors in general work, it's only the dim (bright) foreground color that does not.
