### ISSUE TITLE
RHEL 7 failure to build

### ISSUE THREAD

**Issue by toomanycats** [jwilm/alacritty#147]
I'm running RHEL 7 at work and tried to build Alacrity following the README.

cargo check --verbose                                                                                                                                                     
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: [0/-1] an unknown error occurred

Let me know what other details I can share.

**Comment by jwilm** [comment]
could you maybe try and run this again with `RUST_LOG=debug` and post the output?

**Comment by Gonzih** [comment]
@toomanycats can you build other rust packages on this machine? Are you using nightly? It looks like issue with your rust setup, not with the project itself.

**Comment by toomanycats** [comment]
@Gonzih This is my first experience with Rust so I'll have to research a simple test. I did read the notes about the nightly build and "set" command.

Let me report back with RUST_LOG=debug. 
Cheers

**Comment by toomanycats** [comment]
I changed the build back to the default:
    rustup override set nightly

re-exported the paths and tried again with DEBUG:
--- stderr
/home/dcuneo/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/missing: line 81: gperf: command not found
WARNING: 'gperf' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing 'gperf' program.
make[3]: *** [fcobjshash.h] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [/home/dcuneo/alacritty/target/release/build/servo-fontconfig-sys-be329699d5f46d04/out/libfontconfig.a] Error 2
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f",
                            "makefile.cargo"]).status().unwrap().success()', /home/dcuneo/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/build.rs:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

After exporting the variable:

--- stderr
/home/dcuneo/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/missing: line 81: gperf: command not found
WARNING: 'gperf' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing 'gperf' program.
make[3]: *** [fcobjshash.h] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [/home/dcuneo/alacritty/target/release/build/servo-fontconfig-sys-be329699d5f46d04/out/libfontconfig.a] Error 2
thread 'main' panicked at 'assertion failed: Command::new("make").args(&["-R", "-f",
                            "makefile.cargo"]).status().unwrap().success()', /home/dcuneo/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/build.rs:17
stack backtrace:
   1:     0x7f9f21c8512a - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f9f21c8a1af - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x7f9f21c89dae - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x7f9f21c8a597 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x7f9f21c75a74 - std::panicking::begin_panic::h1dc990fced681ffe
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x7f9f21c768be - build_script_build::main::hf57109037f3eb7e3
                        at /home/dcuneo/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/build.rs:17
   7:     0x7f9f21c92d6a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
   8:     0x7f9f21c8acd6 - std::rt::lang_start::h832f9067ed8c4dd4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
   9:     0x7f9f20e6fb34 - __libc_start_main
  10:     0x7f9f21c75928 - <unknown>
  11:                0x0 - <unknown>
