### ISSUE TITLE
Compose key does not work

### ISSUE THREAD

**Issue by nagisa** [jwilm/alacritty#148]
A chiefly x11 feature called compose keys does not work with alacritty.

**Comment by joushou** [comment]
It does not work with OS X compose either. A character appears (well, it's empty due to fallback fonts missing), but subsequent keypresses just result in more characters typed, rather than attempting to compose a new character.

So yeah, +1

**Comment by samcv** [comment]
For me compose key sort of works. Here is the output shown at different stages of typing the compose sequence:
Typing:
<Multi_key>: `no output`
<Multi_key> + a: `a`
<Multi_key> + a + e: `aææ`

**Comment by jonhoo** [comment]
This is really unfortunate, as it means I also can't type many special characters inside `mutt` or `vim` :/

**Comment by algesten** [comment]
if it hinges on font fallbacks, that's very nearly there. hacking away at it right now. #45

**Comment by jonhoo** [comment]
@algesten I don't *think* this is related to font fallbacks, but rather that alacritty doesn't correctly interpret the keyboard input sequence :/

**Comment by fabi1cazenave** [comment]
Alacritty crashes whenever the Compose key nor any dead key that relies on XCompose is used.

Using Ubuntu 16.04, X11 + Intel driver, Qwerty-intl layout (`setxkbmap us -variant intl`):
* `MultiKey` + `,` + `c` → segfault
* `'` + `c` → segfault

**Comment by francesca64** [comment]
Does it work (on X11) on this branch? https://github.com/francesca64/alacritty/tree/winit-git
