### ISSUE TITLE
Support macOS Mojave Dark Mode

### ISSUE THREAD

**Issue by philipp-spiess** [jwilm/alacritty#1484]
Which operating system does the issue occur on?

macOS 10.14

It would be great if we can support the system wide dark mode by changing the chrome around the window similar to what Terminal.app does:

**Terminal.app**

<img width="697" alt="screen shot 2018-07-31 at 16 04 53" src="https://user-images.githubusercontent.com/458591/43464479-7f93002e-94db-11e8-8bae-04ea8206987d.png">

**Alacritty**

<img width="683" alt="screen shot 2018-07-31 at 16 04 54" src="https://user-images.githubusercontent.com/458591/43464484-81bba7d4-94db-11e8-8c3a-37db00407d29.png">

**Comment by jedahan** [comment]
So I think the window decorations are handled by [glutin](https://github.com/tomaka/glutin/), it might be a great patch to that project, and it might not even need any changes to alacritty, besides bumping the glutin dependency once its merged and released there.

Maybe open up [an issue on the glutin tracker?](https://github.com/tomaka/glutin/issues)

**Comment by philipp-spiess** [comment]
Awesome, thanks @jedahan! I've filed https://github.com/tomaka/glutin/issues/1053 :)

**Comment by nixpulvis** [comment]
@philipp-spiess reading through the linked issue, can you update the plist in this project and have dark mode? that's my understanding.

**Comment by philipp-spiess** [comment]
@nixpulvis Yes that indeed worked 🙂 . I've just created a PR for that (#1486). Should have done the research earlier 🙈 Thank you all for being so responsive!
