### ISSUE TITLE
Ubuntu 18.04 missing dependency

### ISSUE THREAD

**Issue by liamdawson** [jwilm/alacritty#1497]
If I do not install any GPU drivers or similar on Ubuntu 18.04 (just using built-in Nouveau support), and run in Wayland, I get the following error when starting `alacritty`:

```
Alacritty encountered an unrecoverable error:

	Error creating GL context; could not find libEGL: could not find libEGL
```
It worked after I installed the package `libegl1-mesa-dev` (not sure that's the most specific package). Also not sure if this is a Wayland specific issue, I'd have to uninstall that package and run in Xorg to be sure.

**Comment by chrisduerr** [comment]
`egl` sounds like a Wayland specific issue. Specifically Wayland + Nvidia.

**Comment by hkupty** [comment]
Having the same issue on a fedora, running on Wayland on top of Intel Graphics.

**Comment by juchiast** [comment]
I also have this problem on Fedora, Wayland on Intel Graphics. I solved it by installing mesa-libEGL-devel.
