### ISSUE TITLE
Weird "bad archive header magic" when attempting to install build deb on ubuntu 18.04

### ISSUE THREAD

**Issue by damageboy** [jwilm/alacritty#1513]
Hi, I'm using ubuntu 18.04.

rustup show:
```
Default host: x86_64-unknown-linux-gnu
stable-x86_64-unknown-linux-gnu (directory override for '/home/user/projects/public/alacritty')
rustc 1.28.0 (9634041f0 2018-07-30)
```

When running `cargo deb`, I get a `.deb` file built with no errors/warnings what so ever.

When I attempt installing the freshly built deb I get:

```
# dpkg -i alacritty_0.1.0_amd64.deb
dpkg-deb: error: file 'alacritty_0.1.0_amd64.deb' is corrupt - bad archive header magic
dpkg: error processing archive alacritty_0.1.0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 alacritty_0.1.0_amd64.deb
```

In addition, when I attempt running the `file` command on the generate deb, I get a very weird printout:

regular deb file (downloaded during `apt install`):
```
$ file /var/cache/apt/archives/remmina-plugin-vnc_1.2.31.2+ppa201807311347.r647d2e8.dd32dbcd~ubuntu18.04.1_amd64.deb
/var/cache/apt/archives/remmina-plugin-vnc_1.2.31.2+ppa201807311347.r647d2e8.dd32dbcd~ubuntu18.04.1_amd64.deb: Debian binary package (format 2.0)
```

alacritty deb:
```
$ file target/debian/alacritty_0.1.0_amd64.deb
target/debian/alacritty_0.1.0_amd64.deb: Debian binary package (format     `)
```

The build binary runs just fine with no other issues...
I tried and got the same error both with master + scrollback branch...

**Comment by jwilm** [comment]
Thanks for the report. In the mean time, you can build/install manually.

**Comment by jameshiew** [comment]
I can reproduce the issue on one Ubuntu 18.04 machine, but on a different Ubuntu 18.04 machine `cargo deb` actually works fine, so there must be some other factor as well.

**Comment by chrisduerr** [comment]
Might be interesting to compare system information between the two systems @jameshiew? Since @damageboy has the 64bit toolchain installed, I'd assume it's not a 32vs64 issue or something like that.

**Comment by samuelkarp** [comment]
@damageboy @jameshiew I ran into this as well.  I believe the issue is that cargo-deb embeds the UID and GID of the invoking user into the deb archive, and longer UIDs and GIDs can overflow the fields in the archive.  I opened https://github.com/mmstick/cargo-deb/pull/80, which fixed the issue for me.

**Comment by damageboy** [comment]
This got resolved indeed with the last build I did.
Closing this issue..
