### ISSUE TITLE
Create a release?

### ISSUE THREAD

**Issue by FFY00** [jwilm/alacritty#1530]
Hey, can you create a release so that I can properly distribute this package?

**Comment by chrisduerr** [comment]
Hey, please take a look at #1240 for more information about Alacritty releases.

There is an open PR for the scrollback PR which will bump the version number to 0.2.0 (#1492), this will be merged when scrollback is merged and following that a more regular release cycle should be present.

Just out of curiosity, where do you want to distribute Alacritty?

**Comment by FFY00** [comment]
Thank you, I'll wait then.

**Comment by chrisduerr** [comment]
Solved in ca1b75b4c094460e19e62241cc2fadb934ba56a5.
