### ISSUE TITLE
Color change not updating

### ISSUE THREAD

**Issue by alexbode** [jwilm/alacritty#1531]
<img width="787" alt="screen shot 2018-09-01 at 09 57 10" src="https://user-images.githubusercontent.com/25521899/44948151-85d48b00-adcd-11e8-87bc-8ac064a67996.png">
When I updated the ~/alacritty/alacritty.yml file in macosx with the gruvbox theme, alacritty does not change colors after restart. What am I doing wrong? Thanks in advance.

**Comment by siiptuo** [comment]
Does changing other options work?

Usually Alacritty loads configuration from `~/.config/alacritty/alacritty.yml` or `~/.alacritty.yml`. You can check the actual location by running `alacritty -v` in another terminal. (not sure if this works in macOS)

**Comment by chrisduerr** [comment]
As @siiptuo has already said I would recommend using `~/.config/alacritty/alacritty.yml`. I would assume just moving that file there will already fix your issue.

**Comment by alexbode** [comment]
Yes that was the problem. Thank you siiptuo and chrissduerr!

**Comment by isaacaggrey** [comment]
For those who may also stumble on this issue for a related issue - this *doesn't* (obviously) stop any config in your shell of choice (mine is Zsh) from changing the color scheme. I had `dynamic-colors init` still running in my `.zshrc` which changed the color from what I had configured in Alacritty.
