### ISSUE TITLE
Color schema added to ~/.alacritty/alacritty.yml but did not change anything

### ISSUE THREAD

**Issue by cooldesigns** [jwilm/alacritty#1533]
OSX High Sierra
ZSH? - I am not configred to use zsh but it seems like using zsh

Another issue
sudo cp alacritty-completions.zsh /usr/share/zsh/functions/Completion/X/_alacritty
This command says no such file or directory

**Comment by cooldesigns** [comment]
I will give a try pull request but before I need to notice that:
alacritty -v says alacritty not found
code . says code not found, it is shortcut for visual studio code

**Comment by jwilm** [comment]
You'll have to find the `alacritty` binary wherever it's installed (somewhere under /Applications; try `find -name alacritty /Applications`).

In any case, this sounds like a configuration error.
