### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#1534]
Before shipping scrollback, add a CHANGELOG file. We don't need to worry about backdating for everything that's happened in the last 21 months ;).

**Comment by chrisduerr** [comment]
I've added a basic CHANGELOG here: #1492. Hopefully that will capture at least a few of the changes introduced in the scrollback PR already. For future versions there shouldn't be any issue.

I've just left the version out for now since `0.2.0` is not released yet.
