### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by unmellow** [jwilm/alacritty#1537]
it would be cool to have GPU accelerated rendering of web apps that run in your terminal
https://github.com/unconed/TermKit#readme
though it might be a better idea to have an optional dependency that adds support for these web technologies

**Comment by unmellow** [comment]
my whole idea here is my terminal emulator and window manager don't have to be different things just have them be different UI's you can switch between of course I know turning this into a full fledge window manager is out of scope but adding support for this so people can easily convert this into one doesn't seem like anything to ridiculous

**Comment by unmellow** [comment]
though pls don't use there UI it's ugly I still want my stuff to look terminally but I also want pictures and videos in my terminal

**Comment by chrisduerr** [comment]
I don't think this is within the scope of Alacritty, or a terminal emulator in general.

There are options for rendering raw image data to the terminal, the primary one which is already standardized and supported by XTerm would be libsixel (see #910). Other terminal emulators like Kitty (and I believe Terminator?) have their own escape sequences which are supported by tools written just for these terminal emulators.

If you want to support having non-terminal content inside a terminal emulator, using an escape sequence like libsixel is the way to go. Just embedding arbitrary content doesn't really fall in line with the way terminal emulators work. So I recommend subscribing to the libsixel issue, that's probably the most likely path to get what you're looking for working right now.

**Comment by quininer** [comment]
[Notty](https://github.com/jwilm/alacritty/issues/51) is a good choice, but it is currently stagnant.

**Comment by unmellow** [comment]
then how about extraterm[https://github.com/sedwards2009/extraterm](url) then?

**Comment by jwilm** [comment]
This isn't going to happen. We are interested in extending functionality with `notty` protocol at some point, though.
