### ISSUE TITLE
Alacritty stops drawing until different window is selected when using compton

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [jwilm/alacritty#1538]
Which operating system does the issue occur on?
Artix (Arch)

If on linux, are you using X11 or Wayland?
X11

If I have compton on with GLX as backend, alacritty becomes unusable by constantly locking up whenever i hold down a key, as in for example scrolling in _vim_, _less_, _man_.

This is only a problem in Alacritty

As can be seen in gif, alacritty seems to still take keyboard input and work normally except that it just doesn't redraw.

**Gif of issue in action:**
![Gif of issue in action](https://i.imgur.com/EpVpnaP.gif)

**Comment by chrisduerr** [comment]
Hmm, that looks very interesting. Could you share the output you get when running it using `alacritty -vvv`? Might be useful to share this with a gif too. Ideally every once in a while this should print `carriage_return`.

I've never seen this issue before though, so I wonder if this might have something to do with systemd not running. In my experience Alacritty doesn't have issues like this on Void though.

**Comment by AlmightyFloppyFish** [comment]
carriage_return does appear in the log every once in a while however It's hard to see exactly when, the problem doesn't actually persist if i have the debug log on the screen as well, I'm guessing the debug log outputs info, causing other alacritty windows to redraw? If i have the debug log in another workspace the issue happens but i don't see carriage_return other than right when alacritty opens

I don't know what carriage_return is but could the lack of it be an issue?

**Comment by chrisduerr** [comment]
Which window manager are you running? And is this issue present without compton too?

**Comment by AlmightyFloppyFish** [comment]
This issue is only present with compton running with `backend = "glx"`, I'm using spectrwm.
Without compton or with compton using xrender as backend, there's no problems what so ever

This is only a problem with Alacritty, Termite or any other program works fine

**Comment by chrisduerr** [comment]
Huh, would you mind sharing your complete compton configuration? Also could you give it a try with [my compton conf](https://paste.rs/M90)? I also use `backend = "glx"` but everything works just fine for me.

If this doesn't produce any new insights, I'd propose adding some debug output to the renderer to outline more exactly what's going on.

Also just to make sure, could you try #1518? It's a PR which alters the order of Alacritty's rendering optimizations. Maybe that will fix the issue.

**Comment by AlmightyFloppyFish** [comment]
Issue persists with your compton config, issue persists with trimental's fork. My best guess right now is that this is a 3-way compatibility issue with Compton, Alacritty AND spectrwm

**Comment by AlmightyFloppyFish** [comment]
Issue does indeed not happen when switching to i3, using the same alacritty and compton configs.

This appears to be a compton+alacritty+spectrwm issue which might not be fixable in alacritty itself

**Comment by chrisduerr** [comment]
Hmm I wonder if spectrwm does something differently when it comes to focus or rendering.

Just to see if the terminal is properly marked as dirty, could you give this patch a shot:
<details>

```diff
diff --git a/src/main.rs b/src/main.rs
index fc6b082..58247ed 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -171,6 +171,7 @@ fn run(mut config: Config, options: &cli::Options) -> Result<(), Box<Error>> {
     let io_thread = event_loop.spawn(None);
 
     // Main display loop
+    let mut i = 0u128;
     loop {
         // Process input and window events
         let mut terminal = processor.process_events(&terminal, display.window());
@@ -198,6 +199,8 @@ fn run(mut config: Config, options: &cli::Options) -> Result<(), Box<Error>> {
             display.handle_resize(&mut terminal, &config, &mut [&mut pty, &mut processor]);
 
             // Draw the current state of the terminal
+            println!("REDRAWING {}", i);
+            i += 1;
             display.draw(terminal, &config, processor.selection.as_ref());
         }
```
</details>

This should print `REDRAWING {NUMBER}` every time Alacritty attempts to redraw. The number itself is just useful to make sure that Alacritty is actually still redrawing when the whole terminal is full of `REDRAWING`. Ideally this should keep printing `REDRAWING {NUMBER}` when you hold down a key. If it still prints this but the window doesn't update itself, it's likely not completely Alacritty's fault.

**Comment by AlmightyFloppyFish** [comment]
It does still print REDRAWING $n when the window doesn't update, so likely not alacritty's fault.

How strange though, this issue is exclusive to Alacritty so now I'm really curious of what could be causing it...

Might do some tinkering and experimenting with this in the future but if you're out of ideas, and consider this not being an issue on alacritty's side, we could close the issue.

**Comment by chrisduerr** [comment]
This probably has something to do with how rendering works in Alacritty/winit/glutin. I would suspect that this issue is still present with other applications making use of winit/glutin.

I'm not sure if there's any example project you could run to test this though, since most just render a static image. Maybe some examples in gfx-rs have moving content.

**Comment by AlmightyFloppyFish** [comment]
Solved by changing 
`vsync = "opengl-swc"`
to
`vsync = "opengl"`
in compton config. 

Both of our compton configs use opengl-swc so that made it a bit harder to find the issue.

**Comment by chrisduerr** [comment]
Hm, I guess that solves the issue for now, thanks for updating this issue.

If someone else has similar problems, it might be worth looking into what exactly is going on here. Might be a combination of Alacritty/Winit/Glutin using some niche feature and spectrwm not supporting it.
