### ISSUE TITLE
The fix for #1291 caused a regression in Linux (and Windows) mouse click handling

### ISSUE THREAD

**Issue by nolanl** [jwilm/alacritty#1539]
On Linux (X11) wit click-to-focus WM (i3).  Gnome and KDE both default to click-to-focus, so I expect most Linux users will be affected.

Previous versions of Alacitty worked on my system the same way that every GTK+ app, every Qt App, Electron apps, xterm, rxvt, etc.  In fact, this is the first time I've seen an X11 app behave this way, like a MacOSX app.  Which is not surprising since Issue #1291 was for Mac users who were surprised by the X11 behavior.

Qt and GTK+ apps actually change the mouse cursor to show the expected result of clicking, which for a terminal is the "I" bar indicating that selection is possible.  With this change, that (expected, normal) visual cue is misleading.

I don't think there needs to be an configuration option for this, because I expect pretty much everyone to want their terminal to behave according to the conventions of their OS, so just making this MacOS only would fix the issue.

From my limited testing, it appears that Windows follows the X11 convention.  Both firefox's URL bar and Cygwin's terminal will let you start a selection with the first click on an unfocused window.  cmd.exe's console is hard to tell, since you need an explicit command to start selection even when the window is focused, but I do note that right-clicking on an unfocused cmd.exe window does immediately pop up the context menu.

@felippemr @chrisduerr

**Comment by chrisduerr** [comment]
There has been some discussion about this in #1384. And as mentioned there, I'd propose adding a configuration option which will allow setting this up however you want.

**Comment by chrisduerr** [comment]
I'd just set the option to be commented-out by default. And add as a comment that it is `true` on macos and `false` on linux. Then we just need to support `true` and `false` as command line options and whenever you want to make use of the platform default, you just leave out the setting.

**Comment by nolanl** [comment]
Good idea, I'll do that.  Thanks.

**Comment by chrisduerr** [comment]
See #1540.
