### ISSUE TITLE
The CPL escape sequence isn't working

### ISSUE THREAD

**Issue by DrunkenPoney** [jwilm/alacritty#1543]
I'm on linux and I'm using X11.

There's an issue with the ANSI escape sequences.
The CPL escape sequence does not seem to work (`ESC[#F` where `#` is a number)

See https://github.com/terkelg/prompts/issues/89#issuecomment-421069795 for more informaion.

**Comment by chrisduerr** [comment]
The CPL sequence is currently not implemented yet.

You can see a placeholder for this (which should show up with `alacritty -vvv`) here:
https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L1417-L1425

**Comment by chrisduerr** [comment]
This has been implemented in #1590.
