### ISSUE TITLE
Can't build alacritty on macOS Sierra

### ISSUE THREAD

**Issue by varun06** [jwilm/alacritty#1547]
Which operating system does the issue occur on?
MacOS Sierra
If on linux, are you using X11 or Wayland?

```
alacritty ((v0.2.0)) cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  failed to authenticate when downloading repository
attempted ssh-agent authentication, but none of the usernames `git` succeeded
Caused by:
  no authentication available

```

It looks like either a cargo issue or git issue, but thought of asking here and googling didn't help yet.

Note: Already tried `rm -rf ~/.cargo/registry`, didn't help.

**Comment by chrisduerr** [comment]
I think this is a cargo issue. It looks like it's trying to clone a repository using your login credentials.

You could try killing `ssh-agent`, maybe that will help, or it might just prompt you to enter the credentials manually. I think I've seen this issue before, but I don't remember the solution.

**Comment by varun06** [comment]
Thanks Chris.

This is what helped me -> https://github.com/rust-lang/cargo/issues/3381#issuecomment-308460530

**Comment by chrisduerr** [comment]
Thanks for updating this issue, that should hopefully help out the next person with this problem!
