### ISSUE TITLE
Huge memory consumption when setting history variable to a big number

### ISSUE THREAD

**Issue by soupi** [jwilm/alacritty#1550]
This is on Linux (Ubuntu 17.10), X11.

While running alacritty, changing the `history` variable in the configuration to a big number (say 1,000,000, 10,000,000 and above) results in a huge memory consumption (allocation?) instantly that gets the computer stuck very quickly.

**Comment by chrisduerr** [comment]
Currently all lines in the history are immediately allocated. So if you specify a million lines, this means that a million lines are actually already stored in the history, even if it's empty.

Alacritty also stores all lines in memory, so a million lines would take some space.

So the primary way to counteract this issue, would be to dynamically allocate scrollback lines. This is tracked in https://github.com/jwilm/alacritty/issues/1236, so subscribing to that is probably the best way to stay updated right now.

For now, reducing the history size to a smaller number is the only way to work around this.

**Comment by soupi** [comment]
How about putting some hard coded limit in the meantime or even crash with an error? It will be better than letting a user's computer get stuck.

**Comment by chrisduerr** [comment]
That's a fair point, however it depends on the User's system.

Maybe putting in a limit of 100k will do the job. Have you tested at which point this causes freezing issues?

**Comment by soupi** [comment]
I'm not sure if it was 1,000,000 or 10,000,00 but I don't really want to try again. 100,000 was ok i think.

**Comment by chrisduerr** [comment]
I've opened a PR to set an upper limit to the scrollback history size:
https://github.com/jwilm/alacritty/pull/1551

This should resolve the issue, appreciate the feedback!
