### ISSUE TITLE
How can I scroll and select content at the same time?

### ISSUE THREAD

**Issue by axionl** [jwilm/alacritty#1553]
Which operating system does the issue occur on?

ArchLinux

If on linux, are you using X11 or Wayland?

X11

I'm using the latest version of alacritty in a touchpad enviroment.
My laptop is thinkpad X1 Carbon 2014 and the touchpad is a whole piece.

![image](https://www.laptopmag.com/images/uploads/ppress/44608/lenovo-thinkpad-x1-carbon-2014-g19.jpg)

**Comment by ishanjain28** [comment]
Hey there, I am on arch linux, i3, X11. 

I select the text with primary click(hold it), Select the currently visible text by moving the cursor, Then I scroll up/down with double finger swipe up/down and select the text by moving the cursor. 


Alacritty doesn't selects text as I am scrolling but it does selects as soon as I stop scrolling.

**Comment by jwilm** [comment]
This is being worked on in #1512
