### ISSUE TITLE
Middle click only works when Alacritty has focus

### ISSUE THREAD

**Issue by haarp** [jwilm/alacritty#1556]
> Which operating system does the issue occur on?

Linux X11

Depending on the window manager, it's possible to interact with application windows without focussing or raising them. This involves mouse buttons (except left mouse) and mouse scrolling.

Alacritty however only reacts to

    mouse_bindings:
      - { mouse: Middle, action: PasteSelection }

when the window has focus.

**Comment by chrisduerr** [comment]
This should be fixed with 7a8a002da6a7c5b17edf5dc8cc8e3f9e089632fc.

If this does not solve the issue for you, please let me know and I can re-open this issue.

**Comment by haarp** [comment]
Yup, this commit fixed it. Thanks, that was quick! :)
