### ISSUE TITLE
Roboto Mono

### ISSUE THREAD

**Issue by Appadeia** [jwilm/alacritty#1562]
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
X11 Intel iGPU

Roboto Mono seems to be completely malfunctioning.
Here's a comparison of Alacritty with Roboto Mono vs. another terminal with Roboto Mono.
This is the powerline patched version that can be seen [here](https://github.com/powerline/fonts/tree/master/RobotoMono).

![image](https://user-images.githubusercontent.com/20326855/45728905-1ebe2100-bb98-11e8-82aa-945af91e64a6.png)

**Comment by chrisduerr** [comment]
Looks like the correct font isn't loaded at all. Please make sure that the name is specified correctly. Since Alacritty makes use of `fontconfig`, to find the fonts you specified, you can test if a name returns the correct font by running `fc-match "Fira Mono Medium"`.

**Comment by chrisduerr** [comment]
Closing this since there has been no update in a while. This is very likely a configuration issue, alternatively it might also be related to fontconfig fallback problems which are already tracked separately.

**Comment by llitz** [comment]
I saw the same behavior with the font for Roboto Mono all garbled up:

Output of fc-match is good:
fc-match "Roboto Mono for Powerline"
Roboto Mono for Powerline.ttf: "Roboto Mono for Powerline" "Regular"

**Comment by llitz** [comment]
@chrisduerr 

I think I may have been able to track it down to the DPI scaling algorithm. Starting alacritty with WINIT_HIDPI_FACTOR=1.0 fixes the issue for me with Roboto Mono
