### ISSUE TITLE
Cursor not hollow when window starts unfocused

### ISSUE THREAD

**Issue by ad1217** [jwilm/alacritty#1563]
Platform: Linux X11 (i3 specifically)

When launching a new instance of alacritty, the cursor is a solid block despite the window being out of focus (I have `no_focus [tiling]` set in my i3 config). Focusing the window, then un-focusing it behaves correctly. For reference, the related settings are the defaults of `cursor_style: Block` and `unfocused_hollow_cursor: true`.

**Comment by jwilm** [comment]
Thanks for the report! Sounds like a bug.

**Comment by chrisduerr** [comment]
https://github.com/jwilm/alacritty/pull/1569 resolves this issue on i3. I'd love some testing on macOS/Wayland if possible, but it should be good to go the way it is.
