### ISSUE TITLE
[Question] How to change code to use zsh or fish-shell?

### ISSUE THREAD

**Issue by tienhv** [jwilm/alacritty#157]
Hi, how should I modify the code to use zsh or fish-shell instead of bash?

Thanks

**Comment by jwilm** [comment]
You should be able to use the `chsh` utility.

**Comment by tienhv** [comment]
Thanks, the point is changing the shell but only for alacritty. So there is no option, even in the code?

**Comment by jwilm** [comment]
Ah yeah. There's a PR up for this. #138

**Comment by jwilm** [comment]
Shell can now be specified in the config file or by using the `-e` argument.
