### ISSUE TITLE
cargo deb --install ends in fails to compile libz-sys

### ISSUE THREAD

**Issue by tsbertalan** [jwilm/alacritty#1576]
Which operating system does the issue occur on?
Ubuntu 16.04

If on linux, are you using X11 or Wayland?
X11

The instructions given for Ubuntu fail on the final step, `cargo deb --install`. On second invocation, the output looks like this:

```
tsbertalan@gungnir:~/usr/alacritty$ cargo deb --install ; sayalert "installed alacritty"
   Compiling cmake v0.1.34
   Compiling libloading v0.5.0
   Compiling libz-sys v1.0.22
   Compiling rustc_version v0.2.3
error[E0425]: cannot find function `read_to_string` in module `fs`
   --> /home/tsbertalan/.cargo/registry/src/github.com-1ecc6299db9ec823/libz-sys-1.0.22/build.rs:115:13
    |
115 |         fs::read_to_string("src/zlib/zlib.pc.in")
    |             ^^^^^^^^^^^^^^ did you mean `read_string`?

error[E0658]: use of unstable library feature 'fs_read_write' (see issue #46588)
   --> /home/tsbertalan/.cargo/registry/src/github.com-1ecc6299db9ec823/libz-sys-1.0.22/build.rs:113:5
    |
113 |     fs::write(
    |     ^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `libz-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
cargo-deb: build failed
'NoneType' object has no attribute 'group'
```

**Comment by tsbertalan** [comment]
Commands were simply
```
git clone https://github.com/jwilm/alacritty.git
cd alacritty
cargo install cargo-deb
sudo apt install cargo
cargo install cargo-deb
cargo deb --install
```

**Comment by chrisduerr** [comment]
Is this on Debian? I suspect that the version of Rust that Debian is shipping is just too old.

**Comment by eberfreitas** [comment]
@tsbertalan have you installed cargo via apt? I had the same problem and had to uninstall cargo and use rustup to install it back again... Then it worked. Not without a few errors (missing dependencies) but it is running now :)

**Comment by tsbertalan** [comment]
Yes. I guess I could revisit this later; I was hoping for a more turnkey
experience.

**Comment by chrisduerr** [comment]
@tsbertalan I can totally understand that sentiment, however there's little we can do when the distribution doesn't provide an up-to-date version of the latest Rust compiler.

Hopefully this should be resolved once Alacritty starts providing binaries. If updating rust resolves this issue, I think this issue should be resolved, right?

**Comment by tsbertalan** [comment]
Yup. I also get that this is more of a product for people likely to have
installed a more up-to-date compiler; casuals like me can totally just use
konsole anyway. Close away.

**Comment by chrisduerr** [comment]
For everyone interested in a solution to this problem, please follow #80. This should allow everyone to get a working binary for their system, independent from which Rust versions are supported by their distribution.
