### ISSUE TITLE
wmclass is null in Wayland

### ISSUE THREAD

**Issue by sevagh** [jwilm/alacritty#1582]
### Which operating system does the issue occur on?

Fedora 28, 64-bit Linux with Wayland

### If on linux, are you using X11 or Wayland?

Wayland

### Description of the problem

Alacritty shows up as an unknown icon and application, e.g.:

![unknown-app](https://user-images.githubusercontent.com/8574092/45917419-9788db80-be2b-11e8-92f9-b622a67a82b5.png)

Using Gnome's Looking Glass (alt+f2 and run 'lg'), we can see that the `wmclass` of alacritty is null:

![wmclass-null-alacritty](https://user-images.githubusercontent.com/8574092/45917424-aec7c900-be2b-11e8-832e-7b3779731a02.png)

I _believe_ this causes running instances of alacritty to not be associated to the `alacritty.desktop` file.

Not sure which part of alacritty's upstream dependencies sets this `wmclass` value. If this belongs in a more general Wayland ticket, feel free to close it/move it.

**Comment by sevagh** [comment]
https://github.com/jwilm/alacritty/issues/97

**Comment by sevagh** [comment]
Did some preliminary hacking on my end, just to see what's what:

```
sevagh:alacritty $ git diff src/main.rs
diff --git a/src/main.rs b/src/main.rs
index 0888c9b..3480ac6 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -25,6 +25,10 @@ extern crate log;
 #[cfg(target_os = "macos")]
 extern crate dirs;

+extern crate gio;
+extern crate gtk;
+extern crate glib;
+
 use std::error::Error;
 use std::sync::Arc;
 #[cfg(target_os = "macos")]
@@ -114,6 +118,12 @@ fn run(mut config: Config, options: &cli::Options) -> Result<(), Box<Error>> {
     let terminal = Term::new(&config, display.size().to_owned());
     let terminal = Arc::new(FairMutex::new(terminal));

+    let app_name = "com.github.jwilm.alacritty"; //needs to be in this form to be a valid GTK id
+    // Set the Application Name to play nicely with .desktop files in Wayland
+    gtk::Application::new(app_name, gio::ApplicationFlags::FLAGS_NONE);
+    glib::set_application_name("Alacritty");
+    glib::set_prgname(Some(app_name));
```

This is based on observing the Python source code of some other application.

Anyway, it didn't actually work yet - not sure what I'm missing.

Also, I'm not sure if this belongs better in one of alacritty's dependencies (winit, glutin, etc.).

**Comment by chrisduerr** [comment]
As far as I know, we're setting the window class appropriately in Alacritty using glutin's `with_class` call:
https://github.com/jwilm/alacritty/blob/master/src/window.rs#L343

This will probably need to be fixed in https://github.com/tomaka/glutin.

If you are willing to open an issue on glutin's issue tracker about this functionality, please do. Otherwise I'd go ahead and open one myself.

Note that according to their documentation, setting the window class is only supported in X11:
https://docs.rs/glutin/0.18.0/glutin/os/unix/trait.WindowBuilderExt.html#tymethod.with_class

So this would probably be a new feature request, however I'm not aware if this is a standard Wayland thing or just something Gnome does. So it might be a bit more complicated.

**Comment by sevagh** [comment]
I'll open the issue in glutin - and I'm also just wallowing in the deep end here. I have no idea what Wayland truly uses (dbus? GTK application_id? window classes) to do the running application associations to desktop files.

Hopefully somebody with more GTK and/or Wayland experience can chime in there (or here).

**Comment by haarp** [comment]
Curiously it also shows up as an unknown/generic application on X11 here (Xfce)

**Comment by chrisduerr** [comment]
Hopefully fixed in #2077, please let me know if this works.

**Comment by sevagh** [comment]
Great, I'll test and reply - do you know if this release also includes the version of glutin that fixes the repeated keypress issue? I recall using a custom fork (with a bumped version of glutin) to enable multiple keypresses.

**Comment by chrisduerr** [comment]
@sevagh I think this has been solved a while ago, however I'm not certain which key repetition issue you're talking about.

**Comment by sevagh** [comment]
Apologies for vagueness
This is the issue: https://github.com/jwilm/alacritty/issues/1257
Looks like it was solved here: https://github.com/jwilm/alacritty/pull/1403

**Comment by sevagh** [comment]
It looks fixed @chrisduerr 
![alacritty-fixed](https://user-images.githubusercontent.com/8574092/52310253-a645da00-2957-11e9-9d93-ba8351413134.png)
![alacritty-lg-fixed](https://user-images.githubusercontent.com/8574092/52310255-a645da00-2957-11e9-91d2-237afb2993f8.png)

**Comment by chrisduerr** [comment]
Thanks a lot for the feedback! Glad to see it works.
