### ISSUE TITLE
Update selection when scrolling

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1598]
When scrolling in Alacritty with an active selection, the selection will not update until the mouse cursor is moved.

The expected behavior would be that after scrolling, the selection would update itself to go right to the new position of the mouse cursor while the primary mouse button is held down.

This affects both normal scrolling in the scrollback buffer and scrolling inside of Applications like `man` using the faux scrolling feature.

**Comment by cstyan** [comment]
I'd like to try this

**Comment by chrisduerr** [comment]
Thanks for the interest @cstyan, but it looks like nixpulvis is already working on it in #1600.

**Comment by nixpulvis** [comment]
I spent about 30 min on it so far, if your interested in making some commits I'll happily take PRs into my branch. @chrisduerr has left some really good comments on my initial hackory.

**Comment by cstyan** [comment]
no problem, I've been busy and it seems you've been making progress, I'll look for something else :)
