### ISSUE TITLE
Can you force Alacritty to use the sRGB color profile?

### ISSUE THREAD

**Issue by svanharmelen** [jwilm/alacritty#1599]
Which operating system does the issue occur on? 

macOS 10.14

I wondered if its possible to force Alacritty to use the sRGB color profile instead of system (P3) one? I've gotten so used to that when using iTerm2 for years, this new brightness is a bit too much for my eyes.

Thanks!

**Comment by svanharmelen** [comment]
Even though being able to specify this would be nice, after 10 hours of working with it I think I can get used to it. So I'm not going to bother you this issue and close it :wink:

**Comment by naruaway** [comment]
FYI The fix is done in https://github.com/alacritty/alacritty/pull/6602
