### ISSUE TITLE
Problem with "no decoration" (window title bar)

### ISSUE THREAD

**Issue by holygeek** [jwilm/alacritty#161]
In openbox I can specify the list of application that should not have window decoration (no window title) by specifying the following entry in `~/.config/openbox/rc.xml`

```xml
<applications>
  <application class="UXTerm">
    <decor>no</decor>
  </application>
  <application class="Alacritty">
    <decor>no</decor>
  </application>
</applications>
```

It works for uxterm, somehow it doesn't for alacritty. But if I restart openbox then the existing alacritty windows which previously (wrongly) had window titles would (correctly) no longer have the titles. New instances of alacritty will (wrongly) have the window title though.

**Comment by chrisduerr** [comment]
It's now possible to disable the titlebar using the Alacritty config.
