### ISSUE TITLE
macOS: backspace registers twice

### ISSUE THREAD

**Issue by sodiumjoe** [jwilm/alacritty#1611]
Which operating system does the issue occur on?
macOS 10.13.6

I have no idea how I haven't run into this earlier or how it hasn't been reported yet, but as I was working on #1589 I started experiencing two characters being deleted on each backspace. I then reproduced on master, and `git bisect`ed it down to [this commit](https://github.com/jwilm/alacritty/commit/72495172c25e00799f29eb2e79fe40ddfa189866).

Still not sure what's going on, but reverting that commit fixes it for me locally. I'll dig into it further, but wanted to log the issue.

**Comment by sodiumjoe** [comment]
also kinda confused about why this would only happen on macos, the commit doesn't look macos specific in any way.

**Comment by chrisduerr** [comment]
Do you have any keybindings in your configuration file which use the backspace key? Or is this reproducible with the default configuration file?

**Comment by sodiumjoe** [comment]
@chrisduerr 🤦‍♂️ that was it, and I don't remember why I had those in there
```
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
```
