### ISSUE TITLE
Some differences when using alacritty terminfo

### ISSUE THREAD

**Issue by E5ten** [jwilm/alacritty#1614]
Which operating system does the issue occur on?
linux
If on linux, are you using X11 or Wayland?
X11
In neovim, when using xterm-256color going into insert mode make the cursor a line, while with the alacritty terminfo it stays as a block. When compiling a CMake project with xterm-256color as terminfo, there is coloured output, while the output isn't colored with the alacritty terminfo.

**Comment by E5ten** [comment]
https://github.com/jwilm/alacritty/pull/1491#issuecomment-423275013 as said here moving alacritty to xterm-alacritty fixed the issues in neovim, however CMake colours are still not present.

**Comment by jwilm** [comment]
@E5ten can you share the terminfo you're using?

**Comment by chrisduerr** [comment]
This bug is due to the way Neovim detects this feature. It maintains its own database for which terminfo should be supported for it.

I've sent a PR to Neovim a while ago to fix this and it should be resolved with the next version update.

**Comment by E5ten** [comment]
@chrisduerr I will compile CMake with alacritty added to that list and if colours work after that I will make a PR.

**Comment by chrisduerr** [comment]
@E5ten There are two Alacritty terminfo files (`alacritty` and `alacritty-direct`). If you send a PR, please make sure to add both, so we won't have this issue in the future anymore.

**Comment by E5ten** [comment]
@chrisduerr done.

**Comment by E5ten** [comment]
I guess I can close this then, but this could be considered a general issue if other apps use the same method to find compatible terminfos as neovim.

**Comment by E5ten** [comment]
The fix has been merged into CMake so the problem will be fixed after the next release.
