### ISSUE TITLE
Support login -fp $USER as default command

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#1621]
Terminals on macOS including both iTerm2 and Terminal.app use `login -fp $USER` to start the appropriate shell with correct environment. The approach taken by iTerm is to have an option "use login shell" to do something completely different than executing a particular command.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/4285147/46434363-42d94080-c708-11e8-94ae-6c431e0aa887.png">

So, that's one option. Another option might be performing variable substitution on command arguments. In any case, we want to support this because it's the expected behavior on macOS.

**Comment by sodiumjoe** [comment]
this is a dupe of #1071 😂 

There's already some worthwhile discussion there.

Fwiw, I have in my `~/.alacritty.yml`:
```
shell:
  program: /usr/local/bin/tmux
  args:
    - attach
```

and in my `~/.tmux.conf`:
```
set-option -g default-shell /usr/local/bin/zsh
```

and I haven't run into any issues.

**Comment by jwilm** [comment]
Oops; thanks for linking. This was on my mind yesterday.
