### ISSUE TITLE
Support Fraktur ANSI escape sequence

### ISSUE THREAD

**Issue by kevinburke** [jwilm/alacritty#163]
If I run `echo -e "\e[20mfoobarblahbizbang\e[0m"` in the command line, I expect to see Gothic text, but instead see text rendered in the default font.

According to the ANSI escape specification in ECMA-48, this escape sequence should produce text rendered in Fraktur (see page 75 here: http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-048.pdf).

**Comment by tbodt** [comment]
what the fuck how does this escape sequence even exist
