### ISSUE TITLE
Cursor no longer switches shape according to nvim settings.

### ISSUE THREAD

**Issue by derrickcope** [jwilm/alacritty#1630]
Which operating system does the issue occur on? Arch Linux

If on linux, are you using X11 or Wayland? X11

As mentioned above the cursor, after the last update, no longer responds to nvim settings. It just stays a block the entire time.

**Comment by chrisduerr** [comment]
Hey, this is due to Alacritty using its own terminfo now and neovim has an internal terminfo database which doesn't check terminfo for the cursor changing capability.

I've sent a PR to neovim to fix this a while ago. So the two choices you have right now are either running the git version of neovim, or setting `TERM: xterm-256color` in the config, until a new neovim version is released.

Note that cmake had a similar issue, for more information see #1614.

**Comment by derrickcope** [comment]
Hi, thanks for the response. I did read those threads that you linked. I do have xterm-256color set in my alacritty.yml. For some reason it isn't reading the config. When I 'echo $TERM' I get alacritty no matter what I set in alacritty.yml. my config file is it $XDG_HOME_CONFIG . When I export $TERM= xterm-256color in .bashrc it works fine. The color scheme is still correct so maybe alacritty isn't reading env: correctly.

**Comment by derrickcope** [comment]
I'm getting this when I start alacritty from the terminal

problem with config: env: invalid type: unit value, expected a map at line 18 column 1; Using default value
deprecated decorations boolean value, use one of none|full instead; Falling back to "none"
problem with config: colors.primary: invalid type: unit value, expected struct PrimaryColors at line 196 column 3; Using default value
problem with config: colors.normal: invalid type: unit value, expected struct AnsiColors at line 201 column 3; Using default value
Error: problem with config: deserializing from YAML containing more than one document is not supported; Loading default config
problem with config: env: invalid type: unit value, expected a map at line 17 column 1; Using default value

**Comment by YoEight** [comment]
Greetings, 

I'm using neovim HEAD (fresh from two days ago), and I'm still having that issue. What info can I provide to help to figure out a solution?

**Comment by chrisduerr** [comment]
@YoEight Which `TERM` do you have set? I've added the neovim patch myself, so I'm certain it should work with Alacritty.

**Comment by YoEight** [comment]
I'm using `alacritty` as a `TERM` value.

**Comment by chrisduerr** [comment]
@YoEight I'll test the latest master of neovim again, I'll let you know if it works on my machine or not once I get around to it.

**Comment by YoEight** [comment]
Thank you very much @chrisduerr for your time!

**Comment by chrisduerr** [comment]
@YoEight I've just recompiled neovim to test and the cursor still changes shapes appropriately when switching between modes. So this should definitely work again once a new version is published.

Make sure you're up to date with Alacritty and you have the terminfo file installed properly. Also something to note is that changing cursors currently doesn't work due to an unrelated bug on Windows, so this fix only helps with macOS and Linux.

**Comment by YoEight** [comment]
Thanks for your feedback. I'm running Alacritty on OSX 10.14, 0.2.4 version. Do you ask me to run Alacritty master too?

**Comment by chrisduerr** [comment]
0.2.4 should work just fine. Might be terminfo related, not sure. I'd have to test myself and I don't run macOS, but the neovim support is definitely present with the latest master.

**Comment by derrickcope** [comment]
I am having the same issue again on Arch.  The alacritty version is 0.2.4. setting xterm as the term value fixed the issue.

**Comment by chrisduerr** [comment]
@derrickcope Running neovim from the repos or the latest master? Arch hasn't updated their neovim version in the repos for a while.

I'm on Arch and it works just fine.

**Comment by derrickcope** [comment]
I'm just running what's in the repo. I try to keep things simple. Thanks for your reply, hopefully nvim will be updated soon.

**Comment by YoEight** [comment]
Just an update. It actually works as you said @chrisduerr. It stops to work though if I'm in a tmux session. I didn't pick it up the first time as I'm always working within a tmux session.

Here's my tmux configuration:

```
set -g default-terminal "alacritty"
set-option -ga terminal-overrides ",alacritty:Tc"
```

Thanks for your time.

**Comment by chrisduerr** [comment]
Starting `tmux` changes the `TERM` value. So neovim will have to support that, which is not related to ALacritty.

**Comment by chrisduerr** [comment]
Which `TERM` is it actually using inside `tmux` though? Alacritty is exposing the functionality correctly, this is not something Alacritty is doing wrong, but rather a setup problem or an issue with neovim.

**Comment by YoEight** [comment]
As mentioned above, I set this configuration when entering in tmux:

```
set -g default-terminal "alacritty"
set-option -ga terminal-overrides ",alacritty:Tc"
```
The install instructions don't mention anything about tmux. However, it suggests that if we want terminal applications to be aware of `alacritty` features, we should use `alacritty` TERM value. Based on this, I decided to also set `alacritty` terminfo within my tmux sessions.

Maybe we should mention in the documentation (I'm volunteering for writing the PR) that using `alacritty` as a TERM value could lead to some unwanted side-effects when dealing with applications like neovim. I didn't try with vim or another modal editors, so maybe only neovim is affected.

**Comment by chrisduerr** [comment]
Using `alacritty` as a `TERM` value works perfectly fine when using the latest neovim master.

Please run `echo "$TERM"` inside a tmux session, to make sure the value is actually set correctly.

Neovim reads directly out of this value, if it is set properly, it will change the cursor shape.

**Comment by chrisduerr** [comment]
@YoEight Turns out you were on to something all along, thanks for the clarification.

When running `echo -e "\e[6 q"` inside alacritty, termite or termite with tmux, everything works great and the cursor is changed.

But when running `echo -e "\e[6 q"` inside Alacritty with tmux, the cursor isn't changed. This is definitely not a bug with neovim, which is great because it means we can fix it without having to wait for an upstream update.

Feel free to open a new issue for tracking this, it's completely unrelated to this one, so continuing the discussion here is unfit.

**Comment by JeanMertz** [comment]
> Feel free to open a new issue for tracking this

I'm unable to find the follow-up issue, and it appears I'm running into the same situation:

* using Alacritty (8d5e122), Tmux (2.8), Nvim (0.3.4)
* Using a block-shaped cursor by default
* Going into Insert mode does not switch to a pipe cursor
* I've set `guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor2/lCursor2,r-cr:hor20,o:hor50` in Vim
* I've installed the Alacritty terminal definitions

This Tmux config does not work:

```tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"
```

This one does:

```tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```

Although I'm asuming I'm now missing some Alacritty-specific definitions?

**Comment by JeanMertz** [comment]
A few more points, unsure if they are related:

`alacritty.info` does define `Ss` and `Se`, although `Se` differs:

https://github.com/jwilm/alacritty/blob/8d5e1226d500579692128439abd9c991ba9a72d3/alacritty.info#L109

```diff
- Se=\E[0 q
+ Se=\E[2 q
```

However, making that change (and re-applying the config + restarting tmux) does not fix the problem.

When I apply the config however, it does mention:

```
<...>
"alacritty.info", line 109, col 40, terminal 'alacritty+common': unknown capability 'Se'
"alacritty.info", line 109, col 55, terminal 'alacritty+common': unknown capability 'Ss'
```

Now, I've read in another issue here that this is a warning, and not an error per sé, but it might be related to this issue?

**Comment by chrisduerr** [comment]
Please make sure that this works outside of tmux first. If it does, then this is likely a problem with your tmux configuration.

Since I've fixed this issue myself upstream, I'm confident that this works in Neovim and I'm using it on a regular basis without any problems. The important part here is that you have the correct `TERM` definition and that the terminfo file of Alacritty is installed properly. Otherwise this will not work.

**Comment by JeanMertz** [comment]
I was replying to your comment here: https://github.com/jwilm/alacritty/issues/1630#issuecomment-448725586

I have the exact same behavior:

* If I run `echo -e "\e[6 q"` in Alacritty, my cursor changes
* If I do the same in Alacritty after starting `tmux`, the cursor does not change

Here's some details:

**outside tmux**

```shell
$ echo $TERM
alacritty
```

`echo -e "\e[6 q"` works

**inside tmux** (`tmux -f tmux.conf`)

tmux.conf:

```tmux
set -g default-terminal "alacritty"
set -ga terminal-overrides ",alacritty:Tc"
```

```shell
$ echo $TERM
alacritty
```

`echo -e "\e[6 q"` does not work

Making this change makes the cursor change:

```diff
set -g default-terminal "alacritty"
set -ga terminal-overrides ",alacritty:Tc"
+ set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```

---

```shell
$ infocmp
#       Reconstructed via infocmp from file: /Users/jean/.terminfo/61/alacritty
alacritty|alacritty terminal emulator,
        am, bce, ccc, hs, km, mc5i, mir, msgr, npc, xenl,
        colors#256, cols#80, it#8, lines#24, pairs#32767,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, dsl=\E]2;\007, ech=\E[%p1%dX,
        ed=\E[J, el=\E[K, el1=\E[1K, flash=\E[?5h$<100/>\E[?5l,
        fsl=^G, home=\E[H, hpa=\E[%i%p1%dG, ht=^I, hts=\EH,
        ich=\E[%p1%d@, il=\E[%p1%dL, il1=\E[L, ind=^J,
        indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
        kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
        kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, kb2=\EOE, kbs=^H,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, oc=\E]104\007,
        op=\E[39;49m, rc=\E8, rep=%p1%c\E[%p2%{1}%-%db,
        rev=\E[7m, ri=\EM, rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B,
        rmam=\E[?7l, rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l,
        rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        setb@, setf@,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h\E[22;0;0t, smir=\E[4h, smkx=\E[?1h\E=,
        smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        tsl=\E]2;, u6=\E[%i%d;%dR, u7=\E[6n,
        u8=\E[?%[;0123456789]c, u9=\E[c, vpa=\E[%i%p1%dd,
```

The `infocmp` does not mention anything about `Ss` or `Se`, so I'm guessing this is where the issue originates from?

I followed the installation instructions:

```
sudo tic -e alacritty,alacritty-direct alacritty.info
```

But as mentioned, it did warn about `Ss` and `Se` (amongst others): 

```
<...> "alacritty.info", line 109, col 40, terminal 'alacritty+common': unknown capability 'Se' "alacritty.info", line 109, col 55, terminal 'alacritty+common': unknown capability 'Ss'
```

This is on macOS 10.14

**Comment by JeanMertz** [comment]
Quick update, the following _does_ work as expected:

```
sudo tic -ex alacritty,alacritty-direct alacritty.info
```

So adding `-x` solved this issue, although going from [your comment in this PR](https://github.com/jwilm/alacritty/pull/1877#pullrequestreview-182701932), this might break other things?

**Comment by chrisduerr** [comment]
@JeanMertz I wasn't aware you're responding to the existing comments, since this issue has been last active a long while ago. If you're interested in getting this resolved, please open a separate issue to keep track of this (as mentioned in my comment last year).

**Comment by JeanMertz** [comment]
No problem 👍, that's why I opened with "I'm unable to find the follow-up issue".

I've create the issue (https://github.com/jwilm/alacritty/issues/2131) although I'm not sure what _exactly_ the issue is, and if it's only related to macOS or not. But feel free to edit the issue with whatever details are needed.

**Comment by chrisduerr** [comment]
Thanks for creating an issue, refining it later should be no problem!
