### ISSUE TITLE
Mac OS X Mojave - unexpected delete key behaviour

### ISSUE THREAD

**Issue by sganondorf** [jwilm/alacritty#1639]
Which operating system does the issue occur on?
OS X 10.14

The delete key moves the cursor a few spaces right instead of deleting as shown here:
![deletekeybug](https://user-images.githubusercontent.com/5974006/46699060-b686bc00-cbe6-11e8-9d68-4f010dbe09a4.gif)

This is with the default mapping which worked as expected when I tried it on a machine running High Sierra (exact same alacritty config).

**Comment by chrisduerr** [comment]
Since this might be relevant here, which shell are you using? Is it just standard bash?

**Comment by jwilm** [comment]
My guess would be that Mojave updated the terminfo for xterm-256color and that broke what appears to be zsh in Alacritty. @sganondorf, assuming that is indeed zsh, could you try adding this to your ~/.zshrc?

```sh
key[Home]="$terminfo[khome]"
key[End]="$terminfo[kend]"
key[Insert]="$terminfo[kich1]"
key[Backspace]="$terminfo[kbs]"
key[Delete]="$terminfo[kdch1]"
key[Up]="$terminfo[kcuu1]"
key[Down]="$terminfo[kcud1]"
key[Left]="$terminfo[kcub1]"
key[Right]="$terminfo[kcuf1]"
key[PageUp]="$terminfo[kpp]"
key[PageDown]="$terminfo[knp]"

# setup key accordingly
[[ -n "$key[Home]"      ]] && bindkey -- "$key[Home]"      beginning-of-line
[[ -n "$key[End]"       ]] && bindkey -- "$key[End]"       end-of-line
[[ -n "$key[Insert]"    ]] && bindkey -- "$key[Insert]"    overwrite-mode
[[ -n "$key[Backspace]" ]] && bindkey -- "$key[Backspace]" backward-delete-char
[[ -n "$key[Delete]"    ]] && bindkey -- "$key[Delete]"    delete-char
[[ -n "$key[Up]"        ]] && bindkey -- "$key[Up]"        up-line-or-history
[[ -n "$key[Down]"      ]] && bindkey -- "$key[Down]"      down-line-or-history
[[ -n "$key[Left]"      ]] && bindkey -- "$key[Left]"      backward-char
[[ -n "$key[Right]"     ]] && bindkey -- "$key[Right]"     forward-char

# Finally, make sure the terminal is in application mode, when zle is
# active. Only then are the values from $terminfo valid.
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
    function zle-line-init () {
        echoti smkx
    }
    function zle-line-finish () {
        echoti rmkx
    }
    zle -N zle-line-init
    zle -N zle-line-finish
fi
```

**Comment by sganondorf** [comment]
Sorry, I should have specified: I am using zsh.

@jwilm I tried adding that to my `.zshrc` but it didn't change anything for me unfortunately.

I checked and this does not happen when using bash.

I did realize I had
`TERM: xterm-256color-italic`
in my config.
Commenting this out so that `xterm-256color` is used is what fixed the issue for me.

Thank you for taking a look at this!

**Comment by chrisduerr** [comment]
@sganondorf If the `xterm-256color-italic` terminfo is the only one causing issues, I would assume that it's a problem with that terminfo file. Can you confirm that Alacritty's standard terminfo (`alacritty`) also works?

And if it really is the fault of `xterm-256color-italic`, could you test if it shows similar behavior in other terminal emulators?

Also just making sure that `xterm-256color-italic` exists is probably a good idea. Zsh will warn you if you do `export TERM=xterm-256color-italic` when it doesn't exist, so that's probably the best way to test this.

**Comment by sganondorf** [comment]
`xterm-256color-italic` did not exist which was the source of my issue, thank you @chrisduerr for that quick method of checking. The issue was solved when I added it myself. Likewise, once I installed `alacritty` it worked as well. 

I may have misunderstood the problem here a bit, so I think this issue can probably be closed 🙃 thank you both!

**Comment by chrisduerr** [comment]
No problem, glad we could sort this out! :)
