### ISSUE TITLE
Excessive memory usage/leak during selection with less

### ISSUE THREAD

**Issue by haarp** [jwilm/alacritty#1640]
> Which operating system does the issue occur on?
Linux X11

On Alacritty 0.2, when working with large text files (in the order of millions of lines) I am using ```less``` as I don't want the terminal itself to deal with such large numbers of lines. Nonetheless, ```scrolling.history``` is set to 100000 lines.

When I select lots of text in less using the mouse cursor, and exceed the upper or lower screen edge with the selection, Alacritty freezes and starts continuously consuming more and more memory. I managed to SIGSTOP it at 25.5GB, and it would've killed my system had I not managed to do that.

It seems something related to selections triggers a severe memory leak or unbound loop. I will try to provide better repro steps when I have the time.

**Comment by haarp** [comment]
Ok, managed to repro.

- Open ```less``` with a text file that contains a few screens worth of lines at least.
- Scroll down a few screens
- Select everything
- Scroll up using the mousewheel, **fast**, (mwheel events needs to be passed through to less)
- When less reaches the top, Alacritty freezes and starts consuming memory

**Comment by jwilm** [comment]
Wow, sounds bad. Thanks for the report. Prioritizing as high.

**Comment by nixpulvis** [comment]
I was trying to reproduce this earlier. I'm not sure if it's related but there also seems to be a behavior issue with the selection if you scroll down at least one line in something like `less`, then select at least two lines including the status line at the bottom, then scroll back up.

**Comment by haarp** [comment]
Further info: Tested on 0.2.0 with commit 1887722ef5b6ac1 and 0.2.1, both are affected. I've also addede taht you have to release the selection button to the repro steps.

**Comment by nixpulvis** [comment]
Video of reproduction on my system http://cl.ly/3142fd7366ed.

**Comment by sveint** [comment]
I have same issue, happened during text selection, but I'm not sure whether I was in less at the time. Anyways, I never had time to stop it, so it brought down the whole system.

**Comment by haarp** [comment]
With the commit applied, I can't reproduce the bug anymore. Thanks!
