### ISSUE TITLE
Clear selection when scrolling horizontally in less

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1644]
When running `less -S <FILE>` in a window which isn't wide enough to show the full content of the file, it is possible to scroll left/right in less. Having a selection active in this scenario will lead to the selection staying in place while the content under it moves.

I've tested this in XTerm, URxvt and Termite and all these terminal emulators remove the selection when scrolling horizontally. So instead of keeping the selection in place, Alacritty should follow their example.

Note that the selection isn't always removed when left/right is pressed in the alternate screen buffer. The selection should only be removed when the content actually moves horizontally.

**Comment by arthropodSeven** [comment]
since the left-right scrolling is handled by less, i imagine we'll have to detect when the content under the selection changes. i'm happy to take a crack at it but i could use some guidance. would i need to add some kind of reaction when display content updates?

**Comment by chrisduerr** [comment]
`less` actually sends an escape sequence to clear the screen. When this is invoked, the selection should be cleared too (it currently is not).

There's no need to listen for changes and that would likely be pretty bad for performance anyways.

**Comment by chrisduerr** [comment]
Fixed in #2090.
