### ISSUE TITLE
urxvt-like color scheme?

### ISSUE THREAD

**Issue by l29ah** [jwilm/alacritty#1649]
The default color scheme of alacritty is woefully dull, making it really hard to tell colors apart, say, in cataclysm-dda on low brightness level on my IPS panel. Does anyone have a piece of alacritty config with contrast colors, by any chance?

**Comment by nixpulvis** [comment]
I would check https://github.com/jwilm/alacritty/wiki/Color-schemes.

**Comment by chrisduerr** [comment]
Yeah, there should be plenty of color schemes available in the wiki.

Which ones you like is up to your personal preference, so you'll have to check yourself from there.

If you don't like any of the colorschemes present, feel free to make one yourself and add it to the wiki. It just takes 16 colors, so it should be pretty straight-forward and there are plenty of tools like https://terminal.sexy (even supports outputting to Alacritty's config format directly) which can help you with that.
