### ISSUE TITLE
keybinding Ctrl-Space stop working after change input source

### ISSUE THREAD

**Issue by AndreGeng** [jwilm/alacritty#1652]
Which operating system does the issue occur on?
macOS High Sierra 10.13.6

using alacritty with tmux and vim all together, I want to use Ctrl-Space as prefix for tmux. So I have below configs:
.tmux.conf
```
unbind C-b
set -g prefix C-Space
set -g prefix2 C-a
# ensure that we can send Ctrl-Space to other apps
bind C-Space send-prefix
``` 
.alacritty.yml
```
key_bindings:
  - { key: Space, mods: Control, chars: "\x00" }
```
They works, except when I change input source to pinyin/wubi and input some chinese character inside alacrity. The keybinding C-Space seems stop working after that. Everytime when I hit C-Space, feels like a space character is emitted.
I am not sure whether it's alacritty's problem but when I try it in iTerm2, it works ok. 
So does anyone know what causing this, any help is appreciated.

**Comment by AndreGeng** [comment]
Plz ignore me, seems I put alacritty.yml into the wrong location. - -!!  Now it works.

**Comment by sukima** [comment]
This is happening to me as well. And I haven't moved my alacritty.yml in years. Seems to happen _at random_ when I Alt-Tab between apps. Have to close alacritty and re-open to get <kbd>CTRL-Space</kbd> working again.

**Comment by marcossantiago** [comment]
@sukima before I open a ticket, have you fixed your issue? I am experiencing the same problem.

**Comment by sukima** [comment]
I don't think so. though I haven't seen it in a while (watch it will star up again now that I said that). I did upgrade Alacritty recently. Sorry wish I had more info.

**Comment by BartSte** [comment]
> @sukima before I open a ticket, have you fixed your issue? I am experiencing the same problem.

Same here. Haven't changed my config the last year. All of a sudden ctrl+space is not working anymore. I will investigate later this week if I can find this issue..

**Comment by marcossantiago** [comment]
@sukima that's correct. upgrading fixed the issue 🎉

**Comment by nooneknowspeter** [comment]
{ key = "Space", mods = "Control", chars = "\u0000" } worked for me
