### ISSUE TITLE
Unable to run WSL instead of cmd on windows

### ISSUE THREAD

**Issue by Fumler** [jwilm/alacritty#1657]
OS: Win 10
alacritty version: 1.0.2 bin from appveyor artifacts

Tried `bash`, `bash.exe`, `wsl`, `wsl.exe` as well as full windows path to both without any luck.

How do I run WSL on the windows version?

**Comment by jwilm** [comment]
cc @zacps

**Comment by jwilm** [comment]
@Congee you may be able to start alacritty with `-vvv` flag to get more info

**Comment by zacps** [comment]
The lack of an error message for the original issue is caused by winpty throwing an exception which we can't handle from rust code ([tracking issue](https://github.com/rust-lang-nursery/rust-bindgen/issues/1208)).

I'll keep digging to find the route cause.

**Comment by zacps** [comment]
This should have been fixed as a side effect of https://github.com/jwilm/alacritty/pull/1666 because of a downstream fix in [winpty 0.4.3](https://github.com/rprichard/winpty/releases/tag/0.4.3).

Downloading the new `winpty-agent.exe` should fix the issue.
