### ISSUE TITLE
Won't build on macOS 10.12.2

### ISSUE THREAD

**Issue by cultavix** [jwilm/alacritty#166]
I've tried to build, using this command, and following instructions provided, I am receiving errors.

**cmd:** 
`cargo build --release --verbose`

**error:**
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name _ --print=file-names --crate-type bin --crate-type proc-macro --crate-type rlib --target x86_64-apple-darwin` (exit code: 101)
--- stderr
error: unknown crate type: `proc-macro`
```

Note: Command was used before hand `rustup override set $(cat rustc-version)`

**Comment by NeuralSandwich** [comment]
I had this issue when I was using rust from homebrew.

Which version of rustc are you using? The newer/nightly should be able to build this fine.
If you could switch to the latest version and try building it again, It Should Just Work™.

**Comment by cultavix** [comment]
I am running
`rustc 1.13.0`

I'll try that now and update this.

**Comment by uvesten** [comment]
Following the instructions in the `Readme.md` (using rustup, and pining version of rustc for alacritty), it built without problems for me on macOS 10.12.2.

**Comment by cultavix** [comment]
@uvesten Really glad it works for you, that must mean I am doing something wrong? 

I've upgraded all packages using brew and nothing. I didn't install using brew though.

I used `https://rustup.rs/` (shamefully used curl into sh :( )

Note: This is the first time I have ever used anything Rust related!

**Comment by uvesten** [comment]
After installing rust using rustup, did you source the cargo environment / restart your terminal? Maybe that's the problem? 

My output from `which cargo` is `/Users/uvesten/.cargo/bin/cargo`

**Comment by cultavix** [comment]
mine points to `/usr/local/bin/cargo`

And no, I didn't source any cargo env... :(

**Comment by uvesten** [comment]
Then add this to the end of your .profile

`export PATH="$HOME/.cargo/bin:$PATH"`

and restart your terminal. Should work then.

**Comment by jwilm** [comment]
Sounds like compiler is just out of date; closing.

**Comment by james2doyle** [comment]
Adding this for anyone: I had to do a `brew unlink rust` then restart the terminal before cargo would show the correct path (`~/.cargo/bin/cargo`).
