### ISSUE TITLE
Change the config path code to use a cross platform library

### ISSUE THREAD

**Issue by zacps** [jwilm/alacritty#1660]
Currently we use the [xdg](https://github.com/whitequark/rust-xdg) crate on unix systems and implement our own logic on windows.

Moving to [directories-rs](https://github.com/soc/directories-rs) (or an alternative) would let us remove the platform specific code and let the lib worry about it.

[Prior discussion](https://github.com/jwilm/alacritty/pull/1374/files/d2e1d9ecfce8a699654668a734b6dc95f986c0a9#diff-6d8a5e2104954a026de2bfe2b936aea4).

**Comment by JacksonCoder** [comment]
I could take on this issue.

**Comment by chrisduerr** [comment]
@JacksonCoder Feel free to just give it a go. If you need any help you can ask either here or on #alacritty (freenode).

**Comment by JacksonCoder** [comment]
Alright, sorry that I've been busy, but I finally had some time to look through the code today; if I'm correct, I should focus on replacing [this code](https://github.com/jwilm/alacritty/blob/master/src/config.rs#L1492-L1556) which uses different libraries depending on the OS, to code that uses directories-rs or something like that.

**Comment by zacps** [comment]
Yup that's right.

**Comment by JacksonCoder** [comment]
Will this require an update to the README, since we're not using xdg for config paths anymore?

Also, since the config locations are currently different, should I continue making the config path locations platform-dependent, or should they both use a common config location? (like the user config directory)

**Comment by chrisduerr** [comment]
The Linux API should still follow the XDG directory spec. This is supported by `directories-rs` as far as I know. There should not be any breaking changes on Linux as a result of this.

**Comment by JacksonCoder** [comment]
So just to be clear, I should keep the platform-specific code (with the `#[cfg(windows)` and all that), but have both functions use a common library? Sorry for the late response, I've been very busy.

**Comment by zacps** [comment]
This should get rid of the platform specific code, relying on the library to deal with platform specific differences.

**Comment by JacksonCoder** [comment]
I'm sorry, I've been really busy and I think I won't be able to dedicate time to this issue. I might have some time in the future, but until then, someone else can take on this issue.
