### ISSUE TITLE
256 colours are not supported in bash on windows

### ISSUE THREAD

**Issue by zacps** [jwilm/alacritty#1662]
[Original issue](https://github.com/zacps/alacritty/issues/24) by @BartXYZ

[Downstream issue](https://github.com/rprichard/winpty/issues/108)

---

Which operating system does the issue occur on?
Windows 10 - WSL

I tried the last compiled build from AppVeyor, but the colors don't seem to be displayed correctly. This is what it looks like:
![image](https://user-images.githubusercontent.com/5583518/43946261-075bbab8-9c85-11e8-93f8-f5f5bffbd19d.png)

This is what it looks like on [wsltty](https://github.com/mintty/wsltty):
![image](https://user-images.githubusercontent.com/5583518/43946338-4cff2fdc-9c85-11e8-9991-8d59bc555f6e.png)

As a side question. I am starting bash by simply typing 'bash' in de cmd prompt that starts. Would this be the proper way?

**Comment by BartXZX** [comment]
Yeah, my guess would be that this gets fixed when #1661 gets done. :)

**Comment by chrisduerr** [comment]
@zacps Do you want to open an issue with WinPTY and try to resolve it there? Or is it unlikely this will get implemented there and this should instead be handled through #1661?

**Comment by dgriffen** [comment]
WinPTY already has an issue tracking support for the new ConPTY APIs [here](https://github.com/rprichard/winpty/issues/152).

**Comment by zacps** [comment]
I would personally rather implement it in alacritty rather than rely on winpty's implementation. We'll probably have to live with winpty for a while to support older OSs but I'd still like to avoid using it where we can.

**Comment by chrisduerr** [comment]
Well Alacritty already supports it. So this doesn't seem to be an issue that should be worked around in Alacritty.

If WinPTY does not properly handle this, it should be fixed upstream.

**Comment by dgriffen** [comment]
I think the idea that zacps was referring to was that we should use the ConPTY API directly in Alacritty instead of relying on WinPTY to add support for it. In an ideal world there wouldn't be a need for WinPTY at all but its the only way to support versions of windows earlier than Win 10 1809.

**Comment by chrisduerr** [comment]
In that case I would recommend closing this as wontfix and using the #1661 issue to keep track of the ConPTY API.

Otherwise we'd just have two issues tracking the same thing. @zacps Please let me know if you meant something else.

**Comment by zacps** [comment]
Originally I didn't want to close this because it could be supported with [wslbridge](https://github.com/rprichard/wslbridge/) which is how wsltty does it. 

On the other hand the ConPTY API will hopefully be around soon, so I don't think it's worth the effort.

For now if you want this functionality you can tell Alacritty to run [wslbridge](https://github.com/rprichard/wslbridge/) and it *should* work, but I **won't** provide support for issues involving it.

**Comment by cup** [comment]
https://github.com/alacritty/alacritty/issues/2107
https://github.com/alacritty/alacritty/issues/1792

https://github.com/alacritty/alacritty/issues/1662
https://github.com/alacritty/alacritty/issues/2088
https://github.com/alacritty/alacritty/issues/2578
