### ISSUE TITLE
Allacritty cannot find config file

### ISSUE THREAD

**Issue by gurpreetshanky** [jwilm/alacritty#1665]
Which operating system does the issue occur on?

Windows 10 .

Alacritty cannot find config file in %userprofile% named as alacritty.yml.

**Comment by gurpreetshanky** [comment]
And as suggested by @zacps  there is no information from -vvv flag when launched from another terminal.

**Comment by PrsPrsBK** [comment]
Hi. I use the version before merge, and `Microsoft Windows [Version 10.0.17134.286]`
`%HOME%\alacritty.yml` works (I have been using this environment variable many years).

I guess #1660 may handle this. Thanks.

**Comment by gurpreetshanky** [comment]
Thanks @PrsPrsBK . Yup that the correct file location(in my case %UserProfile%\AppData\Roaming\SPB_Data).It works now. Readme is wrong should be echo %HOME% to find the correct path.
