### ISSUE TITLE
[Windows] background_opacity doesn't work as expected.

### ISSUE THREAD

**Issue by yashwanthreddyg** [jwilm/alacritty#1667]
Which operating system does the issue occur on?
Windows 10 64bit

changing background_opacity from 1.0 to 0.5 only makes the background a little grey but not transparent.
![ala](https://user-images.githubusercontent.com/7929962/47068415-d848fa00-d209-11e8-9580-a905ce9fb0b3.png)

[alacritty.yml.txt](https://github.com/jwilm/alacritty/files/2486208/alacritty.yml.txt)

**Comment by chrisduerr** [comment]
Might be interesting to test this with the upstream examples for glutin.

Would you mind running some tests on https://github.com/tomaka/glutin?
You should be able to clone that repository and run `cargo run --example transparent` and get a completely transparent window. If this does not give you a transparent window, this issue will need to be reported upstream.

**Comment by subnomo** [comment]
Yeah, this is an upstream issue. I recently patched this in winit (https://github.com/tomaka/winit/pull/675), but we'll have to wait until it makes it into a release.

**Comment by chrisduerr** [comment]
@subnomo Thanks for the heads-up! This can probably be included into #1403.

**Comment by yashwanthreddyg** [comment]
@chrisduerr  Closing the issue as it seems to be working now on master.
