### ISSUE TITLE
Dragging by the title bar does not report cursor position to OS

### ISSUE THREAD

**Issue by skryl** [jwilm/alacritty#167]
When clicking and holing by the title bar to drag the window, a highlighted area appears in the terminal and the cursor position doesn't seem to be reported to the OS. This prevents BetterTouchTool (and other window tools) from performing auto window snapping/resizing.

Thanks for the great work! 👍

**Comment by chrisduerr** [comment]
I was not able to reproduce this with my macos machine, so I'd assume it has been fixed since this issue has been inactive for quite a while.

If it should still exist and there are some specific steps required to reproduce, please let me know.
