### ISSUE TITLE
Default font (11pt) is very large

### ISSUE THREAD

**Issue by norru** [jwilm/alacritty#1675]
HIDPI strikes again.

![nico lenovo-devuan -projects-3rdparty-alacritty_006](https://user-images.githubusercontent.com/889291/47109468-38f62800-d246-11e8-8f89-9a6e09187fc4.png)

For reference, here's a shot of the Xfce term (12pt font).

![terminal - nico lenovo-devuan _007](https://user-images.githubusercontent.com/889291/47109516-575c2380-d246-11e8-9cf9-fb76c6cf709a.png)

OS: Devuan unstable
Desktop: Xfce4

This can be fixed by disabling font scaling - thus defeating the purpose of HIDPI autodetect.

**Comment by chrisduerr** [comment]
XFCE4 might not scale at all, so it's difficult to compare two different terminal emulators to each other like this.

Is the font size identical to xfce4-terminal when you run Alacritty using `WINIT_HIDPI_FACTOR=1 alacritty`?

**Comment by norru** [comment]
with WINIT_HIDPI_FACTOR=1 the text appears of the expected size.

**Comment by chrisduerr** [comment]
Then xfce4-terminal is just not scaling by DPI at all, but Alacritty is.

So if the resolution and physical size of your monitor are correct, the DPR should be accurate and the font size should be correct. As far as I'm concerned this is an issue with xfce4-terminal, not Alacritty. Or rather that the two applications handle DPI differently.

If you wish to disable DPI scaling, the `WINIT_HIDPI_FACTOR=1` env variable should be used.

**Comment by norru** [comment]
I see.

The main issue here is that I don't want to use scaling and I want every application on my desktop to try and second guess my zoom preferences.

The whole HIDPI is just a huge PITA.

Unfortunately there is no standard way for Linux desktops to set a HIDPI_FACTOR for each and every application, so for the Rust/Winit ones it's WINIT_HIDPI_FACTOR, for AwesomeTool it's AWESOME_TOOL_HIDPI and so on, while we could really do for an unified XDG_HIDPI setting which is understood by each and every app and desktop (in time).

We should push for a standard.

Anyway, rant over. Clearly not a bug. Closing.
Anyway, rant over,

**Comment by norru** [comment]
On another note, why is the text scaled, but the window size is not?

**Comment by chrisduerr** [comment]
@norru It will be once #1403 is merged.
