### ISSUE TITLE
Rendering issue with CursorStyle::Beam

### ISSUE THREAD

**Issue by ethanhs** [jwilm/alacritty#1676]
As can be seen here, it seems that with the Beam as the Cursor, there is a rendering glitch. I am using DejaVu Sans Mono as my font, but this happens even if I switch back to Consolas.

![image](https://user-images.githubusercontent.com/9504279/47075258-1108b500-d1b1-11e8-8ed8-dedc03f230fa.png)

**Comment by chrisduerr** [comment]
Do all other cursors work correctly? Specifically the box and underline cursors would be interesting, since they are drawn in the same way the beam cursor is.

Also could you share some more information about your system please? Is this on Linux/X11?

**Comment by ethanhs** [comment]
Sorry, this is on Windows 10. Box works fine, underline is also broken in the same way. Thank you for the fast response :)

**Comment by chrisduerr** [comment]
I'm really surprised that the box works. But we're drawing these characters manually as our own glyphs, chances are that's just not done in the rusttype renderer yet.

@zacps Do you know anything about this? Did you make the box work yourself? Alacritty makes these three characters available by using glyphs in the free use area. So all font implementations would have to provide the glyph for each character.

With #1568 we'll likely have to change the way these characters are created anyways, but for now getting the rusttype backend up to speed should do the trick.

**Comment by zacps** [comment]
It's not implemented specifically, I guess the codepoint chosen for the block happened to line up to an actual character which is how I noticed it.

I might restructure it a bit so that behavior is actually part of the rasterizer trait.
