### ISSUE TITLE
Cannot adjust font size on Windows

### ISSUE THREAD

**Issue by steveklabnik** [jwilm/alacritty#1684]
This might just be me being a noob, but I wasn't able to adjust the font size, and the default is tiny.

In PowerShell, I can click the upper right corner and select "properties" from the menu to get this:

![image](https://user-images.githubusercontent.com/27786/47190610-67403a00-d310-11e8-9ad5-d9b9b524d7bc.png)

I couldn't find something similar for alacritty.

**Comment by jwilm** [comment]
There are two things you can try if you haven’t already. Please confirm if one of these works. 

1. In the config file, there is a font.size property which will take effect on reopen. 
2. Via hot key, I believe the default is control w/ +. The exact hotkey should be listed at the bottom of our config file.

**Comment by steveklabnik** [comment]
Oh, I did try control-+ too, it didn't work.

I set up a config file, but it seems like it's not loading at all... this *might* be because `%userprofile%` contains a space...

**Comment by steveklabnik** [comment]
Oh, it's actually control-= not control-+,. that *does* work.

**Comment by zacps** [comment]
@steveklabnik Alacritty does not have a configuration menu.

The config file is currently located with [this function](https://doc.rust-lang.org/std/env/fn.home_dir.html#windows) but that is planned to change https://github.com/jwilm/alacritty/issues/1660.

Let me know if you still can't get the config file to work.

**Comment by zacps** [comment]
I'm assuming everything is working, closing.

**Comment by steveklabnik** [comment]
I renamed my home directory to not contain a space, but I think there’s still bugs related to loading the config file when there is one.

That said it caused enough bugs that I had to rename it, so maybe that’s fine as a WONTFIX.
