### ISSUE TITLE
Alacritty consumes more and more memory on each window resize

### ISSUE THREAD

**Issue by dm1try** [jwilm/alacritty#1685]
osx(10.14)
latest master

<details>
  <summary>See the movie (4MB)</summary>
  
![screen recording 2018-10-19 at 04 50 51 mov](https://user-images.githubusercontent.com/486807/47194876-d5611d00-d361-11e8-8647-f69effb7820d.gif)

</details>

I noticed this while I switched from fullscreen mode a couple of times(each time ~50MB was consumed)

though, I'm not sure which memory is consumed(see the gif, it looks like the real memory value is ~50 MB)

**Comment by chrisduerr** [comment]
Not sure how the macOS activity monitor works, but the 'Real Mem' should be the only thing that's actually consumed by the application and necessary, right? The other is just the OS caching stuff.

If you run close to your memory limit, is that memory actually freed or do you run into memory issues?

**Comment by dm1try** [comment]
>Not sure how the macOS activity monitor works, but the 'Real Mem' should be the only thing that's actually consumed by the application and necessary, right? 

yep, that was my first thought
though `top` util shows similar results
<img width="1174" alt="screen shot 2018-10-19 at 15 02 19" src="https://user-images.githubusercontent.com/486807/47217276-84c4e080-d3b0-11e8-9677-00b7837ae30f.png">

> If you run close to your memory limit, is that memory actually freed or do you run into memory issues?

under the limits It looks like kernel frees the memory each time
moreover it does not feel like I'm close to my memory limits =) though active monitor still shows strange stats
<img width="630" alt="screen shot 2018-10-19 at 15 15 08" src="https://user-images.githubusercontent.com/486807/47217755-0ff2a600-d3b2-11e8-91ce-06e1d938d72a.png">

**Comment by chrisduerr** [comment]
I'm not familiar with the way top displays memory here, but usually it should also separate `VIRT` and `RES` memory. You can try this with `htop` too, it should be the same thing there.

The virtual memory is not actually consumed by the application, so it shouldn't be relevant, instead the `RES` (resident) memory is what is actually used. I'd assume that this story is similar for the macOS system monitor you're showing, where `Memory` shows the virtual memory and `Real Mem` shows the resident memory.

Note that this virtual memory allocation seems high, I can't reproduce that on my system, but it shouldn't be an issue.

Here's a little more information of how this works on linux, I'd assume macOS is the same:
https://serverfault.com/questions/138427/top-what-does-virtual-memory-size-mean-linux-ubuntu#138625

Note that I'm not sure why the virtual memory is steadily increasing even when shrinking the terminal size, but it shouldn't cause any direct issues.

**Comment by dm1try** [comment]
@chrisduerr thanks!
let's keep the issue open for a while, I'm going to investigate this on weekend
somehow it's only reproducible with `alacritty` on my machine

**Comment by dm1try** [comment]
ok, I've got more information
In our case, consumed memory is a virtual memory indeed and it is related to the graphics core.
<img width="1248" alt="screen shot 2018-10-21 at 17 24 43" src="https://user-images.githubusercontent.com/486807/47268210-9ba53780-d556-11e8-88ce-781f7dfa7360.png">

as you can see, each call to [`flashBuffer`](https://developer.apple.com/documentation/appkit/nsopenglcontext/1436211-flushbuffer) creates persistent VM regions (`flashBuffer` is called indirectly [by glutin on `swapBuffers`](https://github.com/tomaka/glutin/blob/209ab925f5325c35b8c35020e2d9a85f519f84c3/src/platform/macos/mod.rs#L217-L222))

I'm going to close this, as this is not something we can fix in alacritty.

though, there is another issue. `flushBuffer` is deprecated on osx as well as [whole OpenGL layer](https://developer.apple.com/macos/whats-new/).
>Apps built using OpenGL and OpenCL will continue to run in macOS 10.14, but these legacy technologies are deprecated in macOS 10.14. Games and graphics-intensive apps that use OpenGL should now adopt Metal. Similarly, apps that use OpenCL for computational tasks should now adopt Metal and Metal Performance Shaders.

"Someone" should adopt Metal 🤘

**Comment by chrisduerr** [comment]
> "Someone" should adopt Metal

Metal is not a good target for a cross-platform application. Especially because Alacritty doesn't require any complicated graphics rendering. Unfortunately MacOS isn't really helpful here since they do not support Vulkan either, but chances are OpenGL will still work for years to come.

The only way I can see native Metal support landing in Alacritty would by by using an abstraction layer for rendering. But even that would mean a lot of work without any direct benefit at this point.
