### ISSUE TITLE
Windows alacritty :) 256-colors not working on WSL

### ISSUE THREAD

**Issue by cecton** [jwilm/alacritty#1691]
Which operating system does the issue occur on? WINDOWS 10 on Windows Subsystem Linux

Using this script: https://gist.github.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263

But basically the problem occurs on any program that wants to use the 256 colors.

![image](https://user-images.githubusercontent.com/3018448/47255670-1c8c0280-d475-11e8-9067-d5f586aa820b.png)

**Comment by cecton** [comment]
(btw, what are the dependencies on Visual Studio to compile? It's complaining about a missing "clang.dll/libclang.dll")

```
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'clang.dll\', \'libclang.dll\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', libcore\result.rs:1009:5
```

**Comment by chrisduerr** [comment]
This is a duplicate of https://github.com/jwilm/alacritty/issues/1662.

The full comments should explain how this will be resolved.
