### ISSUE TITLE
Update the Windows configuration file

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1692]
While working on #1617, I've noticed that the configuration file on Windows is missing some major changes which have been made to the other configuration files.

The Windows configuration should be updated to incorporate all missing fields and documentation reworks.

Since this is non-trivial I think it's best to do this in a separate PR rather than incorporating it into the unrelated #1617.

**Comment by gnumoksha** [comment]
Hi, can I do it?

**Comment by chrisduerr** [comment]
@gnumoksha Of course! Feel free to let me know here or on IRC if you have any questions.

**Comment by chrisduerr** [comment]
Since this issue has been open for a while and there was noone actively working on it, I've decided to resolve it myself in #1718.

**Comment by zacps** [comment]
Reopening because of https://github.com/jwilm/alacritty/pull/1723
