### ISSUE TITLE
Title does not get updated in Windows

### ISSUE THREAD

**Issue by Tarik02** [jwilm/alacritty#1695]
Window title is always "Alacritty" on Windows OS

**Comment by robbat2** [comment]
Is this Windows specific? I'm also seeing this on Linux, in `alacritty-0.2.3`. urxvt does correctly update title, but alacritty doesn't :-(

**Comment by chrisduerr** [comment]
@robbat2 It works on my machine. Are you on Wayland or X11?

**Comment by Tarik02** [comment]
@robbat2, yes: https://github.com/jwilm/alacritty/blob/742a6b48a196cabf65354862548c07d057a28d55/src/window.rs#L245

**Comment by robbat2** [comment]
Somewhere is a similar bug for non-windows then :-(. X11 here.

**Comment by Tarik02** [comment]
@robbat2, no, they are absolutely different. Alacritty doesn't even try to change title on Windows as mentioned above.
