### ISSUE TITLE
Add support for Win7+ JumpLists

### ISSUE THREAD

**Issue by prabirshrestha** [jwilm/alacritty#1697]
Which operating system does the issue occur on?
Window

Been giving alacritty a try instead of ConEmu and miss this feature. I pin conemu on the task bar and right click and click on the tasks which directly cds into a folder runs a bunch of script to prepare the environments. 
https://conemu.github.io/en/Windows7Taskbar.html
![image](https://user-images.githubusercontent.com/287744/47308655-13bb3e00-d5e7-11e8-8808-fa8475c5eb09.png)

Might even worth having `alacritty --tasks taskname`. Tasks could be useful for other OS too.

**Comment by chrisduerr** [comment]
I don't use Windows so I'm not really aware of what this does, could you go into a little more detail?

Do you want to setup different Alacritty 'versions' which have separate launch configurations?

**Comment by zacps** [comment]
Yeah, I think just changing the shell and arguments is all we'd need to make this work.

I'm not sure if this should be in-scope though?

**Comment by chrisduerr** [comment]
Couldn't you already easily do this by using the `-e` flag of Alacritty? This allows launching different shells.

I'm not sure how this 'JumpLists' thing works, but you could just create a bunch of scripts to launch the desired configurations.

**Comment by zacps** [comment]
You can create shortcuts to Alacritty that pass in specific arguments which you can place in startmenu/desktop/toolbar/etc.

Cmd does also support persistent aliases, see [here](https://stackoverflow.com/questions/20530996/aliases-in-windows-command-prompt).
