### ISSUE TITLE
alacritty --help doesn't exit

### ISSUE THREAD

**Issue by prabirshrestha** [jwilm/alacritty#1698]
Which operating system does the issue occur on?
Windows

![image](https://user-images.githubusercontent.com/287744/47309594-b2e13500-d5e9-11e8-853a-9bfa1103bcc3.png)

**Comment by chrisduerr** [comment]
Does it exit when sending additional characters (like pressing enter inside the window a couple of times), or does it just never quit unless you kill it?

Also, does Ctrl+C/Ctrl+D work?

**Comment by prabirshrestha** [comment]
I do use Ctrl+C but was expecting it to naturally exit. Pressing enter also seems to quite.

**Comment by chrisduerr** [comment]
If pressing enter fixes this problem, it might be related to #1367.

**Comment by zacps** [comment]
This could also just be a clap bug. What happens if you run with a build built from f3a76e24f1b8e70050e106fa4b68bf582b7bf558?
