### ISSUE TITLE
~/# key doesn't work

### ISSUE THREAD

**Issue by thejpster** [jwilm/alacritty#170]
I'm running alacritty on Fedora 25. Wayland is used for GDM but my session is running Xorg.

When I press the ~/# key, nothing happens, either with shift or without. All the other keys seem to work OK. It's a UK keyboard layout so ~/# is next to Enter.

xev reports the keypress events correctly:

```
KeyPress event, serial 36, synthetic NO, window 0x2e00001,
    root 0xd5, subw 0x0, time 11055582, (1071,521), root:(1204,713),
    state 0x10, keycode 51 (keysym 0x23, numbersign), same_screen YES,
    XLookupString gives 1 bytes: (23) "#"
    XmbLookupString gives 1 bytes: (23) "#"
    XFilterEvent returns: False
KeyRelease event, serial 36, synthetic NO, window 0x2e00001,
    root 0xd5, subw 0x0, time 11055747, (1071,521), root:(1204,713),
    state 0x10, keycode 51 (keysym 0x23, numbersign), same_screen YES,
    XLookupString gives 1 bytes: (23) "#"
    XFilterEvent returns: False
```

Have I done something daft?

**Comment by basile-henry** [comment]
Same as #55 and it looks like it might be fixed by #159

**Comment by thejpster** [comment]
Ah, yes. In my defence # is a tricky thing to search for.

**Comment by basile-henry** [comment]
No worries, that pull request fixes my issue so it should be good for you too! 😃

**Comment by dbrgn** [comment]
For me (Swiss German keyboard layout) typing tilde works, but with a quirk. The tilde is a deadkey on my layout, so I have to type "<tilde> <space>" for the character to show up in the regular terminal.

The thing is that alacritty then renders two tilde characters instead of one.

**Comment by jwilm** [comment]
Sounds like this issue was fixed

**Comment by b3z** [comment]
For me still if I type one of those
```
^´`~
```
One is rendered and if I press enter the command executes but with a second one of those chars appended.
