### ISSUE TITLE
new alacritty build errors out immediately on OSX

### ISSUE THREAD

**Issue by azah** [jwilm/alacritty#1701]
Which operating system does the issue occur on? **OSX**

```
Command::spawn() failed: No such file or directory (os error 2)
```

This was made with `make app`.

**Comment by chrisduerr** [comment]
Sounds like it can't find your shell.

Does this work when running Alacritty with `alacritty -e login`?

**Comment by azah** [comment]
@chrisduerr `alacritty -e login` did work. My shell is `/bin/zsh`.

**Comment by chrisduerr** [comment]
Does `alacritty -e /bin/zsh` work? Or `alacritty -e true`? Or does this cause the same error?

**Comment by azah** [comment]
@chrisduerr `alacritty -e /bin/zsh` works, `alacritty -e true` does not.

**Comment by chrisduerr** [comment]
That sounds like your `PATH` isn't correct. I'd assume that `alacritty -e zsh` also does not work. You can just change the configuration file to use `/bin/zsh` and it should work.
