### ISSUE TITLE
Support changing cursor shape

### ISSUE THREAD

**Issue by topaxi** [jwilm/alacritty#171]
Neovim supports changing the cursor shape in supported terminals: https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal

This basically means we get a `|` shape for insert mode, `_` shape for replace mode and the default rectangle in command mode.

**Comment by CarwynNelson** [comment]
+1 for this. I've recently switched to graphical emacs (with evil mode) and this feature is always something I miss when I go back to regular vim.

I'm sure if I were to come back to neovim using alacritty this would be a very nice feature.

**Comment by net** [comment]
I like to use `_` in fish shell instead of the block `█`.

**Comment by jmacdonald** [comment]
Would be great to see general config support for this too, in addition to the escape code-driven approach proposed above!
