### ISSUE TITLE
X11 gets stuck in drag'n'drop mode when dragging certain elements across Alacritty

### ISSUE THREAD

**Issue by haarp** [jwilm/alacritty#1713]
> Which operating system does the issue occur on?

Linux X11

During a drag'n'drop operation, when certain elements are dragged across Alacritty (they don't have to be dropped on it), X11 instantly gets stuck in drag'n'drop mode. This is 100% reproducible on my system.

When in this state, cursor operation and window focusing is very broken und unusable. In case someone wants to reproduce, killing the application that initiated the DnD operation will restore normal cursor operation; I recommend having a shortcut or a `sleep 30; killall foo` for this.

Drag'n'drop sources I've noticed triggering this bug so far:

- Firefox tabs
- Engrampa / File-roller files
- gedit text

**Comment by chrisduerr** [comment]
This has actually happened a couple of times to me, but I've always thought it's a Firefox thing because killing Firefox would resolve it.

This makes it completely impossible to do anything in i3 and it's required to switch tty and kill firefox, so it has been very annoying, even though it rarely ever happened.

**Comment by chrisduerr** [comment]
I've created an issue upstream, since I was able to reproduce this with the winit examples:
https://github.com/tomaka/winit/issues/687

**Comment by dvergeylen** [comment]
tomaka/winit#687is fixed 😉

**Comment by chrisduerr** [comment]
You're on point with this @dvergeylen! Thanks. :D

**Comment by haarp** [comment]
Sweet, I compiled with winit-0.18.0 and it no longer freezes 🎉 

Thanks!
