### ISSUE TITLE
Build fails on winpty on Debian

### ISSUE THREAD

**Issue by CrashyBang** [jwilm/alacritty#1716]
Which operating system does the issue occur on?

Debian (Buster)

If on linux, are you using X11 or Wayland?

X11.

Get the following error when trying to compile (have installed build dependencies):
```
   Compiling winpty-sys v1.1.0 (https://github.com/zacps/winpty?branch=rust#9ccec645)
error: failed to run custom build command for `winpty-sys v1.1.0 (https://github.com/zacps/winpty?branch=rust#9ccec645)`
process didn't exit successfully: `/home/otis/Downloads/alacritty/target/release/build/winpty-sys-0d08c9ca7441caf5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to generate GenVersion.h: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

cargo-deb: build failed
```

Cheers.

**Comment by chrisduerr** [comment]
Are you able to build this version without `cargo-deb`? Just using `cargo build --release` and then running `./target/release/alacritty`?

**Comment by CrashyBang** [comment]
That worked perfectly, hey just out of curiosity is that the command to build the latest 'stable' or 'released' version? If so that is actually what I want over the other command.

Does it require I run `cargo install cargo-deb` before running `cargo build --release`? Also I am assuming I still need the [build dependencies](https://github.com/jwilm/alacritty/blob/master/INSTALL.md#debianubuntu) regardless.

**Comment by chrisduerr** [comment]
If you clone the repository and do `cargo deb --install` or `cargo build --release` it will install the latest development version.

To get the latest 'stable' version, you have to checkout the git tag of the latest version. You can do that using `git checkout v0.2.1`.

You do still need the build dependencies. What `cargo deb --install` does is it first builds the binary using `cargo build --release` and then uses that to create the target binary.

I'd have to investigate myself why building the deb doesn't work anymore, but I'd assume it's related to the latest workspace changes @zacps made.

If you just want a working version without any trouble, using the last release will probably be easier. That should build with both `cargo deb --install` and `cargo build --release`.
