### ISSUE TITLE
No artifacts section for Windows

### ISSUE THREAD

**Issue by fxdgear** [jwilm/alacritty#1719]
the readme states: 
> Prebuilt binaries can be downloaded from the artifacts section of appveyor.

https://github.com/jwilm/alacritty/blob/master/README.md#windows

When I nav to the link provided there's no artifacts section to download. 

Can you please include the pre-build windows binaries into the `releases` section of github?

**Comment by chrisduerr** [comment]
The artifacts are available under the last successful build job on appveyor.

**Comment by fxdgear** [comment]
I see that now. Thanks

**Comment by chrisduerr** [comment]
Note that github releases will be available with #1329.
