### ISSUE TITLE
OS X: Config on $HOME/.alacritty.yml ignored

### ISSUE THREAD

**Issue by rhaps0dy** [jwilm/alacritty#172]
The config at `$XDG_CONFIG_HOME/.alacritty.yml` is read instead. Of course, the config at `$XDG_CONFIG_HOME/alacritty.yml`is also read.

**Comment by martinlindhe** [comment]
Possibly related to #103

**Comment by alextooter** [comment]
it read from ~/.config/alacritty.yml, so copy this file to ~/.config/

**Comment by 0X1A** [comment]
If the file is in `~/.config` then I don't think it the file should be a hidden 'dot' file. I doubt there's any standardization for this but there's no point in hiding a file in an already hidden directory.

**Comment by plivox** [comment]
Found the answer in the file [src/config.rs](https://github.com/jwilm/alacritty/blob/master/src/config.rs#L974):

```rust
let fallback = PathBuf::from(&home).join(".config/alacritty/alacritty.yml");
```
so:

> .config/alacritty/alacritty.yml

**Comment by jwilm** [comment]
Has been resolved.
