### ISSUE TITLE
Config error on Windows

### ISSUE THREAD

**Issue by aspurdy** [jwilm/alacritty#1722]
Which operating system does the issue occur on? Windows 10

I tried running `cargo run --release` with latest commit a9e03f1 and got 
```
problem with config: while parsing a block mapping, did not find expected key at line 274 column 10
```
Deleted my `alacritty.yml` and tried again, same error. 

I checked out the previous commit, deleted the default `alacritty.yml` and ran again and didn't get any errors. Maybe a bug introduced with #1718?

**Comment by zacps** [comment]
Thanks for the catch. I'll revert this shortly, then we can push a fixed version later.

**Comment by zacps** [comment]
Should be resolved.
