### ISSUE TITLE
there doesn't seem to be a way to get only bright colors for "bold" text

### ISSUE THREAD

**Issue by saurik** [jwilm/alacritty#1735]
I am on macOS, and maybe I'm doing something wrong (it would not at all surprise me, not in the slightest). But: despite draw_bold_text_with_bright_colors being set to true, and even if I try to override the style of the bold font to Regular, text marked with the intensity bit is still being rendered heavier than other text unless I go into the renderer's code and change font::Weight::Bold to font::Weight::Normal. I would argue that when draw_bold_text_with_bright_colors is turned on, the text should no longer be rendered bold; but, if for some reason you actually liked that behavior, there at least needs to be a different way to get the AFAIK historically-more-common behavior of "16-colors for only one font weight" (FWIW, Terminal.app has these as separate settings so people can turn on bright colors and turn off bold fonts).

https://github.com/jwilm/alacritty/blob/15e0deae2b49078b47a782679300cdf99d9ce687/src/renderer/mod.rs#L240

**Comment by saurik** [comment]
> If you want to disable bold text, just change your bold font to be the same as your normal font.

Allow me to repeat what I very carefully explained:

> ...**even if I try to override the style of the bold font to Regular**...

Now what?

**Comment by chrisduerr** [comment]
Then this is a duplicate of https://github.com/jwilm/alacritty/issues/1560.

**Comment by saurik** [comment]
(It really doesn't seem like it has anything to do with fontconfig...) OK, I've tracked this down to some kind of configuration file parsing/finding issue (and am now giving up, as at this point I'm just doing this to be useful, not because I actually think I still want to use Alacritty): I don't think it is loading my config file at all (which I should have noticed before; I apologize :/).

FWIW, it actually works if I manually pass --config-file with a path to a config file, but I can't for the life of me get it to load a config file from anywhere that is listed as a real path (and I have taken to just spamming copies of the config file everywhere, even with names that I know are wrong, just to try to make it work; this is in addition to having it available at compile time).

```
$ echo $XDG_CONFIG_HOME
/Users/saurik/.config
$ ls -a ~/.alacritty* ~/.config/alacritty/* $(find target -name '*.yml') | cat
/Users/saurik/.alacritty.yml
/Users/saurik/.alacritty_macos.yml
/Users/saurik/.config/alacritty/alacritty.yml
/Users/saurik/.config/alacritty/alacritty_macos.yml
target/release/alacritty.yml
target/release/alacritty_macos.yml
target/release/osx/Alacritty.app/Contents/MacOS/alacritty.yml
target/release/osx/Alacritty.app/Contents/MacOS/alacritty_macos.yml
target/release/osx/Alacritty.app/Contents/Resources/alacritty.yml
target/release/osx/Alacritty.app/Contents/Resources/alacritty_macos.yml
target/release/osx/Alacritty.app/Contents/alacritty.yml
target/release/osx/Alacritty.app/Contents/alacritty_macos.yml
target/release/osx/Alacritty.app/alacritty.yml
target/release/osx/Alacritty.app/alacritty_macos.yml
target/release/osx/alacritty.yml
target/release/osx/alacritty_macos.yml
```

**Comment by saurik** [comment]
OK, I got it. OF COURSE I copied the most important one of those wrong.

This entire thing was a waste of your time. At least I know some Rust now.

**Comment by chrisduerr** [comment]
@saurik No worries, glad you were able to figure it out.
