### ISSUE TITLE
Option to enable vertical synchronization

### ISSUE THREAD

**Issue by Scrumplex** [jwilm/alacritty#1739]
There should be an option to enable vertical sychronization (aka VSync). This could fix tearing issues. 

I am using [C.A.V.A](https://github.com/karlstav/cava) and I often have tearing issues. The bars of the visualizer sometimes get cut off. I think this could be fixed with enabling VSync in the renderer. 

I could try to record and demostrate it. 

Both OpenGL and [gl](https://crates.io/crates/gl) support vertical synchronization. We probably just need to load a value from the config file and set a flag for `gl`.

May be related to #598.

**Comment by Scrumplex** [comment]
I am running KWin on X11. I do have VSync enabled. Cava has no tearing issues on urxvt for example iirc.

**Comment by Scrumplex** [comment]
Closing this as this seems to be a [bug with cava](https://github.com/karlstav/cava/issues/196).

**Comment by jwilm** [comment]
vsync is enabled by default btw

**Comment by plasmoduck** [comment]
There is a patch made for the 'Simple Terminal' "st" named Autosync which fixes this issue on st with cava. Perhaps you could skim through the source and implement something into alacritty itself to fix this, if it helps? https://st.suckless.org/patches/sync/ <- The first patch autosync is the one you want.

**Comment by chrisduerr** [comment]
There's no interest to implement something like that.

**Comment by JPenuchot** [comment]
Being able to disable vsync would be nice too.
