### ISSUE TITLE
[mac] ctrl+shift+left or right arrow and ctrl+alt+left or right arrow don't seem to work

### ISSUE THREAD

**Issue by arooni** [jwilm/alacritty#1741]
Which operating system does the issue occur on?
mac;

If on linux, are you using X11 or Wayland?

had a look at the config file but couldn't see any reserved shortcuts there.  am i doing this wrong?

i use shortcuts in the description within tmux for moving windows around
bind-key -n C-S-Left swap-window -t -1
bind-key -n S-M-Left swap-window -t -1

combo works fine on kitty + fish + tmux as well as iterm2 + fish + tmux

**Comment by arooni** [comment]
can be solved with these key bindings ... 

  - { key: Left,     mods: Control|Shift,     chars: "\x1b[1;6D"                       }
  - { key: Right,     mods: Control|Shift,     chars: "\x1b[1;6C"                       }

in the future it would be helpful to tell mac users how we can get these escape sequences because showkey -a doesn't run on mac and can't seem to be installed via homebrew.

**Comment by chrisduerr** [comment]
Note that it is also possible to get the escape sequences for key combinations by using `cat -e`.

If you think that this should be better documented for macOS or/and these bindings should be present by default, please open a PR. Otherwise please close this issue if the problem has been resolved.

**Comment by arooni** [comment]
Is there any way to just have alacritty remap anything on mac from 

command + key combo
ctrl + key combo?

would be so much easier than trying to one off and find out all these things i've gotten used to have stopped working.

it also seems alacritty cares not for any mappings i've made in better touch tool https://folivora.ai/ ... and instead sees through the mappings i try to make there.

**Comment by arooni** [comment]
also;  

  - { key: I,        mods: Command,     chars: "\x09"                       }

doesn't work, while

  - { key: I,        mods: Control,     chars: "\x09"                       }

does.  what am i doing wrong?

**Comment by chrisduerr** [comment]
This has been fixed in https://github.com/jwilm/alacritty/commit/9a14ca42d35e3b72ca254384ef7e4639aab0e100.
