### ISSUE TITLE
Cannot map Control + Plus

### ISSUE THREAD

**Issue by dbrgn** [jwilm/alacritty#1747]
I'm using a Swiss German keyboard. The plus is on the "1" key, so typing "+" means pressing Shift + 1.

I tried to use this keybinding for zoom control:

```
  - { key: Key0,     mods: Control, action: ResetFontSize    }
  - { key: Add,      mods: Control, action: IncreaseFontSize }
  - { key: Subtract, mods: Control, action: DecreaseFontSize }
```

Control+Key0 as well as Control+Subtract both work, but Control+Plus (which I type using Control+Shift+1) does not.

I also tried mapping directly to `key: Key1, mods: Control|Shift`, but that doesn't seem to work either.

Any ideas how this should work?

## Which operating system does the issue occur on?

Arch Linux

## If on linux, are you using X11 or Wayland?

X11

**Comment by dbrgn** [comment]
Note that for some reason, Control+Add doesn't even work when using the numpad "+" key, even though it requires no modifiers.

**Comment by dbrgn** [comment]
Here's `showkey -a` output:

```
# Key1
1        49 0061 0x31
# Shift + Key1 (+)
+        43 0053 0x2b
# Ctrl + Key1
1        49 0061 0x31
# Ctrl + Shift + Key1
+        43 0053 0x2b
# Ctrl + Numpad+
+        43 0053 0x2b
```

And this is `xev` output when pressing Ctrl + Shift + Key1:

```
KeyPress event, serial 32, synthetic NO, window 0x3200001,
    root 0x295, subw 0x0, time 16839504, (1390,235), root:(1391,251),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x3200001,
    root 0x295, subw 0x0, time 16839512, (1390,235), root:(1391,251),
    state 0x1, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x3200001,
    root 0x295, subw 0x0, time 16840016, (1390,235), root:(1391,251),
    state 0x5, keycode 10 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XmbLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x3200001,
    root 0x295, subw 0x0, time 16840152, (1390,235), root:(1391,251),
    state 0x5, keycode 10 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x3200001,
    root 0x295, subw 0x0, time 16840448, (1390,235), root:(1391,251),
    state 0x5, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x3200001,
    root 0x295, subw 0x0, time 16840448, (1390,235), root:(1391,251),
    state 0x1, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
```

**Comment by chrisduerr** [comment]
Does it work when you do not hold shift down? This works sometimes since what matters is not actually the `Add` character, but rather the `Add` key. I'm on dvorak for example and I have to press the `=` key without holding shift.

Alternatively it's possible to use scancodes directly in the Alacritty configuration file. That should always work without any problems.

**Comment by arooni** [comment]
If I could piggy back on this.

On Ubuntu I don't seem to be able to map control minus to DecreaseFontSiz
  - { key: Subtract,    mods: Control, action: DecreaseFontSize             }

**Comment by chrisduerr** [comment]
> How would I use scancodes for the keybindings?

See https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L334-L338.

**Comment by arooni** [comment]
showkey --scancodes
Couldn't get a file descriptor referring to the console

may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - brofist.com
twitter - @brofist <https://twitter.com/brofist>

**Comment by chrisduerr** [comment]
The `showkey --scancodes` command needs to be run with root permissions.

**Comment by arooni** [comment]
i just see output like

0x1d etc... none of the x1d sequences that it seems the config file demands

may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - brofist.com
twitter - @brofist <https://twitter.com/brofist>

**Comment by rsansores** [comment]
Same problem. Cannot zoom-in zoom-out font with a key binding.

Linux 5.0.8-arch1-1-ARCH GNU/Linux
Wayland - Sway 1.0
alacritty 0.2.9

**Comment by chrisduerr** [comment]
We've added a few additional keybindings and scancodes are usable now too, so it should definitely be possible to make ctrl+plus work on every platform without any issues.

Could you share the output of `alacritty --print-events` when pressing the shortcut @rsansores?

**Comment by rsansores** [comment]
Hi, it was my mistake. After reading the output with --print-events is saw that the key is "Minus" not "Substract" like the default config file. I changed to Minus and Plus and now is working.

```
[2019-04-23 11:25] [INFO] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(93957427704336))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 53, state: Pressed, virtual_keycode: Some(Minus), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-04-23 11:25] [INFO] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(93957427704336))), event: ReceivedCharacter('-') }
```
Thanks for the tip of using --print-events

**Comment by chrisduerr** [comment]
Thanks, I'm going to close this issue since we've recently added another keybinding and it should have fixed this issue.

If you still can't make it work, please let me know.
