### ISSUE TITLE
Mouse cursor on Wayland is always default

### ISSUE THREAD

**Issue by Limero** [jwilm/alacritty#1750]
When I run alacritty on Wayland (sway), the mouse cursor is always default, but if I run it on xorg, the cursor is correctly made a text cursor when it's held over the terminal. The cursor is a text cursor on gnome-terminal with Wayland, so it's most likely a alacritty bug and not related to sway.

Wayland, Arch Linux
alacritty 0.2.1
sway version 1.0-beta.1-151-ge9c77970 (Nov  5 2018, branch 'master')

**Comment by paulrouget** [comment]
Most likely a winit issue: https://github.com/tomaka/winit/issues/735

**Comment by Kommynct** [comment]
They seem to have fixed that bug, yet alacritty still displays the default mouse cursor.

**Comment by kchibisov** [comment]
@Kommynct No, [they don't](https://github.com/rust-windowing/winit/blob/7eed52a97a3639f5e284a750f47898b1244c90ec/src/platform_impl/linux/wayland/window.rs#L295)

**Comment by kchibisov** [comment]
Now it seems like this functionality was added upstream, so bumping winit on #2438 should fix it.
