### ISSUE TITLE
'Rocket' macOS emoji app cannot be disabled in Alacritty

### ISSUE THREAD

**Issue by Lachlantula** [jwilm/alacritty#1751]
[Rocket](https://matthewpalmer.net/rocket/) is a fantastic application that supports Slack-like emoji input globally. It is possible to configure Rocket so that certain applications do not use Rocket input, ie. a colon followed by other letters will not trigger the application to appear. Disabling Alacritty in the preferences will not prevent Rocket from opening.

![image](https://user-images.githubusercontent.com/12870244/48033250-b7dbe200-e1ae-11e8-8570-37e22f958c9e.png)

[Here is a demonstration of what I mean.](https://youtu.be/t_dhJC_8Se4)

OS: macOS Mojave 10.14.1
Alacritty: 0.2.1

**Comment by chrisduerr** [comment]
I'm not familiar with Rocket, but this sounds like it might be an issue with Rocket?

**Comment by Lachlantula** [comment]
Thanks for the swift reply. That's what I initially thought, but @jwilm replied to me on Twitter with the following:

> This might be an Alacritty bug. We're using winit (Rust equivalent of GLFW), and there's some issues displaying even the native emoji keyboard.

https://twitter.com/i_am_jwilm/status/1058176153268183040

**Comment by jwilm** [comment]
@chrisduerr I suggested this might be an Alacritty issue due to other issues we've seen with, for instance, the built-in emoji keyboard on macOS. It's a bit surprising that this would work everywhere else besides Alacritty.

**Comment by felipesere** [comment]
This is fixable: rename `alacritty` to `Alacritty` in Rocket and you are good to go.
I think the issue is with what name is in the app bundle (I guess) and what name is reported to the OS. 

<img width="490" alt="screenshot 2018-12-02 at 17 36 31" src="https://user-images.githubusercontent.com/1850188/49342902-d66fb480-f658-11e8-92e2-7c4328ff6858.png">

**Comment by chrisduerr** [comment]
If there's anything Alacritty can do to resolve this (the canonical name should be `Alacritty`, not `alacritty`), feel free to send a PR.
