### ISSUE TITLE
URL detection picks up trailing `,`

### ISSUE THREAD

**Issue by kpcyrd** [jwilm/alacritty#1753]
I ran into an issue with the link detection: `asdf https://example.com/, asdf` detects `https://example.com/,` as a valid url. I think trailing `,` and `.` should be ignored.

**Comment by chrisduerr** [comment]
@quininer I didn't know about this. It looks great, I'll play with it a bit today. Thanks a lot for the link. One problem we have is that we need to parse from the middle out. Since we just have the click location and aren't actually searching the complete buffer.

**Comment by kpcyrd** [comment]
I've found a similar issue, but slightly more obscure:
```
https://github.com/TunSafe/TunSafe/blob/master/docs/WireGuard%20TCP.txt
```
I can't see any trailing characters in both alacritty or xfce4-terminal, but alacritty opens:
```
https://github.com/TunSafe/TunSafe/blob/master/docs/WireGuard%20TCP.txt%EF%BB%BF
```
while xfce4-terminal just opens the link as displayed.

when opening the logfile in vim, the message is displayed as:
```
2018-11-18 11:39:54 vidal72[m]  https://github.com/TunSafe/TunSafe/blob/master/docs/WireGuard%20TCP.txt<feff>
```
