### ISSUE TITLE
Support the -e flag

### ISSUE THREAD

**Issue by g2p** [jwilm/alacritty#176]
`term -e command` is the standard way to override the default shell on Unix.

Unfortunately there's an inconsistency in the way multiple arguments are handled.

    gnome-terminal -e 'screen vim'

vs

    rxvt -e screen vim

gnome-terminal's way is more compatible with getopt argument conventions. On the other hands there's probably a call to `system()` to make it work, instead of an exec.

xterm handles both. Please don't do that, because that means weird rules for space handling.

**Comment by g2p** [comment]
Related: #122.

**Comment by jwilm** [comment]
Sounds good! Thanks for filing this. Going to keep this as the tracking issue.

**Comment by jwilm** [comment]
This has been added
