### ISSUE TITLE
Add command line option '--foreground #rrggbb'

### ISSUE THREAD

**Issue by fudgemond** [jwilm/alacritty#1765]
I manage about 20 systems and am able to open a terminal to any one of them over ssh.  I have a different font colour which helps me recognise what system I'm on.  Can a new command line option be added  '--foreground #rrggbb' so that I can use only the one default config yml file?  I'm already very impressed by alacritty and would like to see it become even more useful.  Many regards.

**Comment by chrisduerr** [comment]
I don't think making this a dedicated command line flag makes much sense for most users, however the proposal has come up before to allow overriding any configuration file setting from the command line.

Please see https://github.com/jwilm/alacritty/issues/1258 for more info. That should resolve this issue too, so closing this as a duplicate.

**Comment by fudgemond** [comment]
Thanks Chris.  I'll keep an eye on what happens in the other thread.  Looks like https://crates.io/crates/config can may be quite useful.  Keep up the good work.
