### ISSUE TITLE
Disable DPI scaling

### ISSUE THREAD

**Issue by dikiaap** [jwilm/alacritty#1768]
**Which operating system does the issue occur on?**
Ubuntu

**If on linux, are you using X11 or Wayland?**
X11

I got this issue when Glutin 0.19 PR is merged

The `WINIT_HIDPI_FACTOR=1` environment variable didn't work either I use
`export WINIT_HIDPI_FACTOR=1` and in alacritty config

```
env:
  TERM: xterm-256color
  WINIT_HIDPI_FACTOR: 1.0
```

The only way I know is to disable it on every command line execution, but it didn't work in .desktop entries.

![x](https://user-images.githubusercontent.com/8542502/48308590-3bc11000-e59b-11e8-982b-6cd90a77c0f2.png)

Disabled:
![y](https://user-images.githubusercontent.com/8542502/48308594-424f8780-e59b-11e8-8c4d-cc9cab883a6a.png)

**Comment by chrisduerr** [comment]
I've created a PR which sets the environment variables before starting the Alacritty window. Please let me know if this fixes the problem for you:
https://github.com/jwilm/alacritty/pull/1769
