### ISSUE TITLE
Bundle winpty-agent

### ISSUE THREAD

**Issue by Aaron1011** [jwilm/alacritty#1770]
Currently, running Alacritty on Windows requires downloading both `Alacritty.exe` and `winpty-agent.exe`. It would be nice if Alacritty could package winpty in the main executeable, to avoid the need to download and manage two different executables.

**Comment by notlmn** [comment]
Hey, to whoever it may concern.

I just got https://github.com/lukesampson/scoop-extras/pull/1514 merged so people who already use scoop on Windows can now install Alacritty without worrying about any missing dependencies or manually copying files.

Thanks to the authors and maintainers of Alactritty!

**Comment by chrisduerr** [comment]
@notlmn Feel free to add this to the README.md if it's just a simple `scoop install alacritty` (or whatever the syntax may be), or to the INSTALL.md if it requires building yourself and a Rust toolchain to be installed.

**Comment by zacps** [comment]
I'm going to have to close this as a wontifx. It's not possible to include two binaries in one file, at least not without storing the bytes, writing it to a temp file, etc.

Instead, creating an installer is probably the best way to resolve this. I'd done some work previously, but not created an issue until now.

See https://github.com/jwilm/alacritty/issues/1900
