### ISSUE TITLE
Make centering of the grid inside the window optional

### ISSUE THREAD

**Issue by synaptiko** [jwilm/alacritty#1778]
Centering was added in PR #1190. While I think it does make perfect sense in some situations, I found this behavior a bit annoying under a tiling window manager. Maybe it's only because I'm used to the previous (maybe broken) state. Anyway I would like to have an ability to turn this off.

**Comment by nixpulvis** [comment]
Well TBH, I feel most users (wheather they really notice it or not) will be unhappy with the jumping. If trying both x and y booleans separately is too complex I'd personally argue for disabled being the default. I might try hacking in just disabling the Y and seeing how much better things are. I suspect it's worth it.

**Comment by chrisduerr** [comment]
I'd love some more feedback on this topic. I personally can't stand it when things are completely unaligned the way they were previously. But I don't have a general picture.

Probably also a case where a vocal minority might complicate getting proper feedback. But generally the complete on/off switch shouldn't be too far out there.

**Comment by chrisduerr** [comment]
Note that as far as I can tell at first glance, neither XTerm, URxvt nor Termite do padding at all. Just as an indicator for a reasonable default that doesn't surprise users.

**Comment by chrisduerr** [comment]
I've created a PR which implements this feature, I think that should be good enough:
https://github.com/jwilm/alacritty/pull/1780
