### ISSUE TITLE
Alacritty won't start if window.dimensions.columns and lines is 0

### ISSUE THREAD

**Issue by synaptiko** [jwilm/alacritty#1781]
I have following in my config:
```
window:
  dimensions:
    columns: 0
    lines: 0
```

This seems to be breaking alacritty now with:
```
thread 'pty reader' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551615', libcore/slice/mod.rs:2052:14
```

I think it's broken by change: https://github.com/jwilm/alacritty/commit/d05d16f023b27fc4707478668db73d6860918956#diff-f3f442280fb5120848272b348120ec52L156

Although [comment in the default config](https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L19) says the `0` is valid:
```
# If both are `0`, this setting is ignored.
```

**Comment by chrisduerr** [comment]
I was not aware that specifying 0 was allowed here. I would have expected optional values to use `Option` instead. I'll fix this asap to make it work again, but in the future there might be a better stylistic approach to optional values.

**Comment by chrisduerr** [comment]
Would you mind testing if https://github.com/jwilm/alacritty/pull/1782 works?
