### ISSUE TITLE
Can't install the deb package for 32-bit system

### ISSUE THREAD

**Issue by dikiaap** [jwilm/alacritty#1786]
**Which operating system does the issue occur on?**
Ubuntu 18.04 32 bit

**If on linux, are you using X11 or Wayland?**
X11

I can't install the deb package, it says the package is only for 64 bit system

```shell
~/Downloads 
$ sudo dpkg -i Alacritty-v0.2.3_i386.deb
dpkg: error processing archive Alacritty-v0.2.3_i386.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 Alacritty-v0.2.3_i386.deb
```

The binary build also doesn't work

```shell
~/Downloads 
$ ./alacritty                           
zsh: exec format error: ./alacritty
```

**Comment by chrisduerr** [comment]
That is actually correct. The deb is currently build twice on the 64 bit host, instead of the 32-bit container.
