### ISSUE TITLE
Alacritty update seems to have affected top margin

### ISSUE THREAD

**Issue by snoblenet** [jwilm/alacritty#1787]
Updating Alacritty seems to have added a margin between the top of my Tmux tabs (at the top of the screen) and the top of the Alacritty window.

![image](https://user-images.githubusercontent.com/62277/48445648-2cd09c80-e7eb-11e8-8852-0c03d12d0027.png)

Which operating system does the issue occur on? Mac OS X 10.14.1.

I'm on Tmux 2.7 and have not recently updated it. Also I have not recently changed my Tmux, ZSH or Alacritty settings.

An automatic Mac OS X minor update went through a few days ago.
```
~/code/alacritty → git reflog
d05d16f (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull: Fast-forward
9bc888f HEAD@{1}: pull: Fast-forward
865727c (tag: v0.1.1) HEAD@{2}: pull: Fast-forward
1adb5cb HEAD@{3}: pull: Fast-forward
24a74d4 HEAD@{4}: pull: Fast-forward
ea512cb HEAD@{5}: pull: Fast-forward
68b3d8a HEAD@{6}: pull: Fast-forward
2fcdd40 HEAD@{7}: pull: Fast-forward
24e8a19 HEAD@{8}: pull: Fast-forward
e34dccd HEAD@{9}: checkout: moving from 7298b58e74ac16d2a7a31ef7da5877f9fb54ef38 to master
7298b58 HEAD@{10}: checkout: moving from master to 7298b58e74ac16d2a7a31ef7da5877f9fb54ef38
e34dccd HEAD@{11}: pull: Fast-forward
6debc4f HEAD@{12}: pull: Fast-forward
b9ad0cf HEAD@{13}: pull: Fast-forward
59b561b HEAD@{14}: pull: Fast-forward
692cdef HEAD@{15}: pull: Fast-forward
```

**Comment by jwilm** [comment]
Thanks for the report! The grid positioning behavior changed in a recent release to automatically center within the window. This makes padding effectively quantized to the size of a cell. PR #1780 makes this a config option and may restore the previous behavior as default. Please chime in there if you feel strongly about the default behavior :).

**Comment by chrisduerr** [comment]
Note that this all should be documented in the change log. I can only recommend it to everyone, since these kind of things are precisely why it's written. :)
