### ISSUE TITLE
font.scale_with_dpi configuration ignored

### ISSUE THREAD

**Issue by sroebuck** [jwilm/alacritty#1791]
Running alacritty 0.2.3 (and this is a regression since 0.2.1) the `font.scale_with_dpi: false` setting appears to be ignored.

To be clear, I have two screens which could both be classified as HiDPI but I want to ignore this, not least because the alacritty screen resizes as I drag it between screens and this is not a behaviour that I want.

I had 0.2.1 installed previously with `scale_with_dpi` set to `false`.  With 0.2.3 this setting seems to be ignored and when I drag between windows it also resizes temporarily even though both screens resolve to the same dpi when the drag has finished.

I am running Ubuntu 18.10 on the default X11 rather than Wayland.

**Comment by chrisduerr** [comment]
Oh, looks like this wasn't included in the change log, but if you run it from a different instance of Alacritty you should get an error that the `font.scale_with_dpi` setting is not supported anymore, right?

Note that the `WINIT_HIDPI_FACTOR` env variable can now be set from the configuration file (which is documented in the change log. You can simply set `WINIT_HIDPI_FACTOR=1` in the `env:` section and it should have the same effect.

I'd assume this resolves this issue for you, but I'd like to use this to track fixing the change log. It should properly document that the option has been removed and how the issue can be worked around on X11.

**Comment by mguindin** [comment]
I'm seeing this issue as well since moving from 0.2.1 to 0.2.3, also running on macOS High Sierra.  I know there have been changes to display settings between High Sierra and Mojave, is it possible that it's working on one and not the other (I don't have a Mojave machine to test).

**Comment by pbgc** [comment]
@chrisduerr No! What happens is that the font is really small and in the middle of the screen ... just like the other screenshots on #1631 
I'm sorry for posting the original discussion here! ... I thought it was related ... And just posted again to answer your question.
