### ISSUE TITLE
Resizing causing text stretch/shrink

### ISSUE THREAD

**Issue by badfilms** [jwilm/alacritty#1798]
OS: macOS 10.14.1
Caveats: [Amethyst](https://github.com/ianyh/Amethyst)

If I open an additional instance of Alacritty, the previous window will have its text shrunk until I switch focus to said window. Using a tiling window manager, this is a notable issue.

This can also be seen when simply resizing the window, as the text will stretch/shrink, depending on action, however, once the action is stopped, the window will redraw.

I understand that performance issues likely occur if the window is redrawn for every pixel change, but if the window changes size and loses focus, it should still redraw.

<img width="857" alt="screen shot 2018-11-15 at 1 01 51 am" src="https://user-images.githubusercontent.com/10216930/48533530-deff7700-e872-11e8-8a2a-0842eb984fe5.png">

**Comment by tokyovigilante** [comment]
This also occurs with the chunkwm tiling window manager on macOS.

**Comment by chrisduerr** [comment]
The window will redraw if it's resized or if it loses/gains focus and that changes the window contents (like the hollow cursor).

This looks like a problem with third party window managers in macOS to me.

I'm interested to know if there are any issues with glutin. Can you test the glutin example (https://github.com/tomaka/glutin)? You can run it using `cargo run --example window`. The triangle should be perfectly centered inside the window.

**Comment by badfilms** [comment]
Glutin doesn't produce any issues on my end. That is, the triangle is indeed centered. Furthermore, the original window upon which it is called does not suffer from the text shrink issue, but this is likely due to the fact that there is output to the original window.

**Comment by chrisduerr** [comment]
That sounds to me like the third party window manager isn't sending resize events properly.

**Comment by badfilms** [comment]
Ok I will see if I can address that on Amethyst's end, but I should note that I don't have this issue with iTerm, so I imagine that this could also be addressed on Alacritty's end.

**Comment by chrisduerr** [comment]
There might be some other event that is sent which is expected to cause a redraw. But since the normal window manager works properly and linux window managers work perfectly fine it seems like there's at least something slightly odd going on with Amethyst here. I don't know enough about macOS to say for sure though, maybe there's some kind of expose event which isn't handled.

Maybe @francesca64 knows something about this? I feel like this could potentially be a problem with winit too, even though the triangle is still properly centered.

**Comment by badfilms** [comment]
I'll open an issue with Amethyst so some other eyes can get on this, as I probably can't address this for another month or so (current student). But since it has been mentioned that this issue also exists with chunkwm, another macOS window manager, I personally feel that it would be best for the issue to be addressed at the source such that its behavior is expected across all window managers.

**Comment by tokyovigilante** [comment]
It also happens with standard floating windows when the window is resized by grabbing a corner, so I'm also unconvinced it's a window manager issue. 

Also, the macOS terminal reflows the scrollback buffer on resize, which is another feature it would be great to pick up. Alacritty (and to be fair other 3rd-party terminals) seem to preserve the line width of the scrollback buffer even if the window is resized narrower or wider, which is IMHO probably technically correct but a negative for readability.

Possibly relevant Cocoa APIs:
https://developer.apple.com/documentation/appkit/nsview/1483795-preservescontentduringliveresize?language=objc
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaPerformance/Articles/CocoaLiveResize.html#//apple_ref/doc/uid/TP40001444-BAJGDIBE

**Comment by tokyovigilante** [comment]
Also highly likely to be related - looks like live resize events aren't handled by glutin.

https://github.com/fasihrana/skryn/issues/24

**Comment by paulrouget** [comment]
Ran into this issue with Servo. It's a problem with how the `winit` event loop is used.

Looking at the event loop code in Alacritty, I believe that it makes the assumption that `run_forever(|..| {... return Break})` will return early. This doesn't work with resized events on Mac (at least). It will return only once resizing is over.

Events are still received though, but computed too late.

I believe the right approach is to process the `winit` events **inside** the `run_forever` callback, not later (by appending events to a pending events vec). And on resize, call `GLWindow::resize` (I believe this is necessary) and maybe redraw synchronously (I'm not sure how Alacritty schedules painting).
