### ISSUE TITLE
Fallback works with ttf-hack on Arch but not powerline-fonts

### ISSUE THREAD

**Issue by jwtcmu9316** [jwilm/alacritty#1804]
I'm using X11 on Arch and I'm having a weird issue with font fallback. My default font is Fantasque because I love how it looks, but it has no ligatures. Naturally, I tried downloading powerline-fonts to no avail. I tried lots of configuration options, both in my fonts.conf and in alacritty.yml. After giving up, I tried Hack from ttf-hack and the ligatures showed up without any configuration.

Why is this happening? How do I make it work with powerline-fonts?

**Comment by chrisduerr** [comment]
See #1560 for tracking some issues with fontconfig. There is an open PR to make use of an alternative font library which will hopefully resolve these issues.
