### ISSUE TITLE
error with vim and TERM=xterm-256color: [unhandled osc_dispatch]: [['1','0',],['?',],] at line 754

### ISSUE THREAD

**Issue by fd0** [jwilm/alacritty#1809]
Which operating system does the issue occur on?

 * Archlinux
 * vim 8.1.0527-1
 * alacritty 0.2.3.1003.g3593ec7-1 (commit 3593ec72dd19f5e2766a57241f2ecb9f05929a0b)

If on linux, are you using X11 or Wayland?

X11, using i3 as the window manager

I've seen #944, but that seems to be a different error reported by the same method. I was unable to find the arguments in the error message (`[['1','0',],['?',],]`) in any other issue, so I opened a new one.

Thanks to the error log notification feature merged recently, I was made aware that every time I start vim an error occurs:
```
[2018-11-18 12:45] [WARN] [unhandled osc_dispatch]: [['1','0',],['?',],] at line 754
[2018-11-18 12:45] [WARN] [unhandled osc_dispatch]: [['1','1',],['?',],] at line 754
```

I've reproduced the error with the default alacritty config and an empty vim config. It depends on the value of `$TERM`, setting it to `xterm-256colors` produces the error, e.g.:

```
TERM=xterm-256color vim -u NONE -U NONE -N
```

When setting `TERM=alacritty`, the error does not occur:

```
TERM=alacritty vim -u NONE -U NONE -N
```

But then setting `termguicolors` make vim's output render in black and white (so no nice colors).

Other random things I noticed:
 * It does not happen with neovim (with both values for `TERM`, version 0.3.1-1)
 * It does not happen with vim 8.0 (tested only via SSH to a system running Debian stable)

Any idea what's going on here? Is there anything I can do to help?

Thanks a lot for your work on alacritty, I love it!

**Comment by chrisduerr** [comment]
Thanks for pointing this out. An undandled OSC/CSI/ESC event doesn't actually necessarily mean that there's any error at all. It just means that a program is sending an escape sequence which isn't supported by Alacritty yet.

These messages are mainly there for debugging and I've set both CSI and ESC to the `debug!` level in my PR. But it looks like I've forgot about the OSC escapes.

Unless there's something that doesn't work, it should be fine to ignore this.

**Comment by binary132** [comment]
Same on macOS 10.14 with `xterm-256color`

**Comment by CNG** [comment]
Came here because I am having the same issue, and while I understand it's not a critical error, I would love to get rid of the "WARNING! See log at /tmp/Alacritty-8573.log" that is blocking me from seeing what I type at the command prompt. Can we *please* move this warning to *anywhere* but directly over the cursor? :)
