### ISSUE TITLE
Set x-windows urgent on bell

### ISSUE THREAD

**Issue by stephenh** [jwilm/alacritty#181]
I'm not really an expert on how this is implemented (and especially have no idea what the Mac/growl/whatever equivalents are), but I use the X urgent-on-bell feature of my current terminal to flash the window title in i3wm when long-running commands (compiles/etc.) are complete.

E.g. a short command to run as a test to see if it works is:

```
sleep 2 && echo -e "\a"
```

The sleep is because if you're already looking at the terminal window, i3wm will ignore/reset the urgent flag right away, so "sleep 2" gives me time to switch to another window/desktop to see if, when echo \a runs, the window it's in is highlighted. I don't know how other window managers handle/display the urgent flag.

Understood if this is considered bloat, but hopefully it wouldn't be too hard to add; I currently have it working even through tmux sessions, so a bell in a terminal session on a remote host gets percolated through tmux back to my local terminal window, and it's very nice/important for my workflow, to get me back on task.

**Comment by okuuva** [comment]
Definitely +1 for this, besides using it for long jobs in both remote and localhost. It is also nice with irssi / weechat for having an audible ping and or flash the terminal when receiving a pm or highlight. I understand some people find it annoying and it could be off by default.

**Comment by jwilm** [comment]
Sounds reasonable. Adding it to the list!
