### ISSUE TITLE
Can't clear warning/error with `clear` or `CTRL-L` in tmux

### ISSUE THREAD

**Issue by OkanEsen** [jwilm/alacritty#1811]
Which operating system does the issue occur on?
Fedora release 29 (Twenty Nine)

If on linux, are you using X11 or Wayland?
X11

The warning/error which is displayed by Alacritty at the bottom of the terminal doesn't go away, if I press `CTRL-L` or type `clear` inside the terminal. It obviously works, if I'm outside of tmux, just not inside.

**Comment by chrisduerr** [comment]
I've looked into which escape sequences are sent in `tmux` when running the `clear` command, just to check if there's something Alacritty could hook into to remove the errors and warnings when running that. Based on my testing, there's no nice escape sequence sent which would allow for that, so I'd probably just recommend adding a new key action which then can be used.

Just for documentation, these escapes are sent when running `clear` inside of `tmux` on my system:
```
[Unhandled CSI] action='l', args=[2004], intermediates=[63] -> Reset bracketed paste mode
[Unhandled CSI] action='r', args=[1, 30], intermediates=[] -> Set scrolling region [1, 30]
[Unhandled CSI] action='r', args=[2, 30], intermediates=[] -> Set scrolling region [2, 30]
[Unhandled CSI] action='S', args=[29], intermediates=[] -> Scroll up 29 lines
[Unhandled CSI] action='H', args=[1, 1], intermediates=[] -> Cursor position [1, 1]
[Unhandled CSI] action='K', args=[], intermediates=[] -> Erase in line to right
[Unhandled CSI] action='r', args=[1, 31], intermediates=[] -> Restore DEC Private Mode Values
[Unhandled CSI] action='H', args=[1, 1], intermediates=[] -> Cursor position [1, 1]
[Unhandled CSI] action='m', args=[1], intermediates=[] -> Bold
[Unhandled CSI] action='m', args=[7], intermediates=[] -> Inverse
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42) -> Character set United States (USASCII), VT100
[Unhandled CSI] action='m', args=[], intermediates=[] -> Normal
[Unhandled CSI] action='H', args=[1, 1], intermediates=[] -> Cursor position [1, 1]
[Unhandled CSI] action='H', args=[], intermediates=[] -> Cursor position [1, 1]
[Unhandled CSI] action='r', args=[1, 30], intermediates=[] -> Set scrolling region [1, 30]
[Unhandled CSI] action='r', args=[2, 30], intermediates=[] -> Set scrolling region [2, 30]
[Unhandled CSI] action='S', args=[29], intermediates=[] -> Scroll up 29 lines
[Unhandled CSI] action='H', args=[1, 1], intermediates=[] -> Cursor position [1, 1]
[Unhandled CSI] action='K', args=[], intermediates=[] -> Erase in line to right
[Unhandled CSI] action='m', args=[30], intermediates=[] -> Foreground black
[Unhandled CSI] action='m', args=[101], intermediates=[] -> Background red
[Unhandled CSI] action='m', args=[37], intermediates=[] -> Foreground white
[Unhandled CSI] action='m', args=[100], intermediates=[] -> Background black
[Unhandled CSI] action='m', args=[30], intermediates=[] -> Foreground black
[Unhandled CSI] action='m', args=[101], intermediates=[] -> Background red
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42) -> Character set United States (USASCII), VT100
[Unhandled CSI] action='m', args=[], intermediates=[] -> Normal
[Unhandled CSI] action='K', args=[], intermediates=[] -> Erase in line to right
[Unhandled CSI] action='r', args=[1, 31], intermediates=[] -> Set scrolling region [1, 31]
[Unhandled CSI] action='H', args=[1, 48], intermediates=[] -> Cursor position [1, 48]
[Unhandled CSI] action='h', args=[2004], intermediates=[63] -> Set bracketed paste mode
```

**Comment by OkanEsen** [comment]
> Based on my testing, there's no nice escape sequence sent which would allow for that, so I'd probably just recommend adding a new key action which then can be used.

Yeah, no worries, I'm just going to do that. Maybe an option inside the config to disable the warning displayed on the bottom would be a good idea? I don't know.

**Comment by chrisduerr** [comment]
@OkanEsen I'm not a huge fan of that idea. These warnings should be fixed, rather than ignored. Most cases this is something which can be easily resolved by the user.

**Comment by OkanEsen** [comment]
Yeah, just gave it a second thought and I agree with you.

I think the issue can be closed, if that's okay.

**Comment by chrisduerr** [comment]
I'll close it with the PR for the action. I'll open that in a sec.

**Comment by chrisduerr** [comment]
I've opened the PR (https://github.com/jwilm/alacritty/pull/1814), feel free to test if this resolves the problem for you.
