### ISSUE TITLE
Extra padding on bottom of terminal

### ISSUE THREAD

**Issue by nhadler** [jwilm/alacritty#1816]
**Which operating system does the issue occur on?**
I'm using i3 manjaro with scrollback alacritty from aur with X11. I just updated alacritty to the latest version and I'm getting extra padding from what used to---nearly a whole lines worth. I've disabled window decoration and it did nothing.

![extra_padding](https://user-images.githubusercontent.com/3527739/48683897-4112f180-eb7d-11e8-83e7-9eb2badcfd23.png)

**Comment by chrisduerr** [comment]
You get 'nearly a whole line' of padding, because there's not enough space for another line. So especially with a tiling WM, it's necessary to pad that space.

Please see #1780 and #388, the issue is covered there already.
