### ISSUE TITLE
macOS 10.12.2 Doesn't show Chinese char at all.

### ISSUE THREAD

**Issue by alextooter** [jwilm/alacritty#182]
Hi,
Just build on macOS 10.12.2, and ls my Downloads, alacritty display all Chinese char as black.

**Comment by Lin-Buo-Ren** [comment]
It seems that currently Alacritty doesn't support font fallbacking.
![default](https://cloud.githubusercontent.com/assets/13408130/21742440/4a2ac06a-d52a-11e6-9153-cd284286515c.png)

Setting font -> normal, bold, italic to a non-generic font that provides Chinese glyphs(like WenQuanYi Zen Hei Mono) will let Alacritty be able to render Chinese characters with issues

![alacritty_089](https://cloud.githubusercontent.com/assets/13408130/21742467/d68b4e76-d52a-11e6-881a-d03c91459402.png)

**Comment by humean** [comment]
In the blog post:

> Fallback fonts are not supported

This means that if your chosen font doesn't support the character then it won't render them correctly. Once fallback fonts are implemented, as they are in most terminals, then this problem will be resolved.

**Comment by jwilm** [comment]
We recently added some fallback support to macOS, and I think this should work now

**Comment by zhaozg** [comment]
![Uploading 屏幕快照 2018-10-17 上午09.09.26.png…](wrong character)
uname -a: `Darwin zhaozgdeMacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`
