### ISSUE TITLE
Window not respecting my WM

### ISSUE THREAD

**Issue by GrayJack** [jwilm/alacritty#1825]
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
X11

I use awesome as WM, and when I open in tile mode, it doesn't respect the tile rules, always opens with the same size

Notice that my window.dimensions are both set to 0, so it should respect the WM

Plus this error don't exist on the 0.2.1 or 0.2.2

My config:
https://up1.secretalgorithm.com/#BaeXwcGJR6xxKEse1u-_hg

Examples:

![image](https://user-images.githubusercontent.com/17973728/48745270-e4cdd180-ec51-11e8-963c-612f316d1591.png)

![image](https://user-images.githubusercontent.com/17973728/48745300-075fea80-ec52-11e8-8caa-835591d47f75.png)

**Comment by slavoutich** [comment]
Can confirm the same under X11 and XMonad: window starts as specified by WM and immediately rescales to some fixed size. Pretty annoying, since I launch some terminal apps in fixed-size scratchpads.

**Comment by slavoutich** [comment]
To elaborate: was playing now with launching the terminal, the behaviour is not deterministic. To my estimate, there is a chance slightly higher than 50% that Alacritty will respect WM setting and slightly lower than 50% that it will rescale.

**Comment by chrisduerr** [comment]
Could someone provide an `alacritty -v` output? I use i3 and everything works beautifully there. I suspect that the WM might be resizing and Alacritty resizes itself shortly after that.

**Comment by warptozero** [comment]
@GrayJack I'm using this as a hacky fix in awesome, maybe you find it useful
```lua
client.connect_signal("manage", function(c)
    if not awesome.startup and awful.rules.match(c, { class = "Alacritty" }) then
        c.resize_alacritty = true
    end
end)
client.connect_signal("request::geometry", function(c)
    if c.resize_alacritty then
        c.width = 800
        c.height = 700
        c.resize_alacritty = false
    end
end)
```

**Comment by warptozero** [comment]
Reimplemented it more properly as a normal rule for the `awful.rules.rules` table.
```lua
awful.rules.rules = {
    ...
    { rule = { class = "Alacritty" },
      callback = function(c)
          local resize_alacritty
          function resize_alacritty(_c)
              _c:disconnect_signal("request::geometry", resize_alacritty)
              gears.timer.delayed_call(function()
                  _c.width, _c.height = 800, 700
              end)
          end
          if not awesome.startup then
              c:connect_signal("request::geometry", resize_alacritty)
          end
      end
    },
    ...
```

**Comment by Tanuj69** [comment]
> local resize_alacritty client.connect_signal("manage", function(c) if not awesome.startup and awful.rules.match(c, { class = "Alacritty" }) then client.connect_signal("request::geometry", resize_alacritty) end end) function resize_alacritty(c) c.width, c.height = 800, 700 client.disconnect_signal("request::geometry", resize_alacritty) end

Where to actually put this code?

**Comment by Tanuj69** [comment]
Please work this over, this is really intriguing me to move back to kitty

**Comment by chrisduerr** [comment]
@Tanuj69 Various people have various preferences as to what needs to be focused on in Alacritty, so the best way to accelerate the progress on one specific issue is to help out with it.

Mentoring is always an option, so if you feel like the Alacritty contributors aren't prioritizing the right things, that's the best choice to fix it.

**Comment by chrisduerr** [comment]
This is potentially related to https://github.com/jwilm/alacritty/issues/204.

**Comment by chrisduerr** [comment]
Can someone test https://github.com/jwilm/alacritty/pull/2307 to see if that helps with things?
