### ISSUE TITLE
window.start_maximized conflicts with window.dimensions

### ISSUE THREAD

**Issue by jedahan** [jwilm/alacritty#1826]
As debugged by @dm1try in #1823, `window.start_maximized: true` with `window.dimensions` of anything other than `0` creates weird behavior.

A first pass fix is that the dimensions should be ignored when `window.start_maximized` is true.

A second pass fix would be coming up with a better config so that these cannot contradict each other.

Perhaps changing `start_maximized()` to be `window.dimensions.columns + window.dimensions.lines == 0`, and get rid of `start_maximized` completely.

**Comment by chrisduerr** [comment]
I don't think there's any problem with them 'contradicting' each other. Making maximization automatic when both columns and lines are 0 is an absolute no-go, these are not the same thing and should be treated differently.

I think just ignoring columns/lines when maximized is set is the best way to resolve this. It's an easy fix and allows the user the most freedom by just keeping lines/columns in and toggling `start_maximized` whenever it's desired that Alacritty should be started in a maximized mode. With a command line flag this could be made even easier.

**Comment by dm1try** [comment]
totally agreed with @chrisduerr
> start_maximized() to be window.dimensions.columns + window.dimensions.lines == 0

 is very opinionated behavior; someone can rely on default window size/etc

btw I use this patch locally for starting alacritty in "fullscreen" mode
```diff
diff --git a/src/config.rs b/src/config.rs
index 4f62440..c103213 100644
--- a/src/config.rs
+++ b/src/config.rs
@@ -384,6 +384,9 @@ pub struct WindowConfig {
     /// Start maximized
     #[serde(default, deserialize_with = "failure_default")]
     start_maximized: bool,
+
+    #[serde(default, deserialize_with="failure_default")]
+    pub fullscreen: bool,
 }
 
 fn default_padding() -> Delta<u8> {
@@ -424,6 +427,7 @@ impl Default for WindowConfig {
             decorations: Default::default(),
             dynamic_padding: false,
             start_maximized: false,
+            fullscreen: false,
         }
     }
 }
diff --git a/src/window.rs b/src/window.rs
index de3eb9a..93dede1 100644
--- a/src/window.rs
+++ b/src/window.rs
@@ -154,6 +154,10 @@ impl Window {
         let window_builder = Window::platform_builder_ext(window_builder, &class);
         let window = create_gl_window(window_builder.clone(), &event_loop, false)
             .or_else(|_| create_gl_window(window_builder, &event_loop, true))?;
+
+        if window_config.fullscreen {
+            window.set_fullscreen(Some(window.get_current_monitor()));
+        }
         window.show();
 
         // Text cursor
```

I did not do any PR because were some "glitches" while opening a window and I've realized now that it is because of "dimensions" setting mentioned above. It works like a charm now with "zerofied" dimensions  :)
So maybe we can rename the setting differently(`start_size/start_dimensions/start_state`) and add additional option.

**Comment by chrisduerr** [comment]
@dm1try That is not a correct implementation for fullscreening the window at startup. It starts the window normally and then moves it into the fullscreen state after it's already been started.

For correct behavior it would be necessary to make use of the `with_fullscreen` method on the window builder.

**Comment by chrisduerr** [comment]
I'd be fine with having a setting which allows specifying `maximized, fullscreen, windowed` as options, but that should be unrelated to this issue.

**Comment by nixpulvis** [comment]
Just looking at these config settings now for the first time. My gut reaction is to assume that if a window is full screen it's ignoring any set dimension.

I'm sure you could nest the window dimensions under an enum like `maximized, fullscreen, windowed(x,y)` but I really don't think it's too confusing to leave it "in conflict" and just ignore the dimensions when the full screen config is set.
