### ISSUE TITLE
Change log level for missing config

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1829]
If the configuration file is missing, it will currently raise an error which will be displayed in the UI. However an empty configuration file should neither be an error nor an warning, since it's perfectly valid.

As a solution, changing the log level of this error to `info!` should resolve the problem, but will still inform a user about what's going on when running Alacritty with the `-v` option.

**Comment by Tezkerek** [comment]
I made a pull request: #1831.
