### ISSUE TITLE
On macOS, can't use alt-keys to type @, |

### ISSUE THREAD

**Issue by fredsted** [jwilm/alacritty#1832]
I can't type *some* special characters with Alacritty. 

For example, alt-* should result in `@` on my keyboard (Danish keyboard with Danish mapping), but instead nothing is written. 

Other special characters using the alt key, e.g ± (alt-+) I can type with no issues.

I've just installed Alacritty 5 mins ago and didn't touch the configuration. 

I can type the mentioned characters in iTerm2 as well as Terminal.app with no issues.

Which operating system does the issue occur on? macOS Mojave 10.14.1

**Comment by chrisduerr** [comment]
This has been reported in several other issues already.

Please see https://github.com/jwilm/alacritty/issues/1349, https://github.com/jwilm/alacritty/issues/1681 and https://github.com/jwilm/alacritty/issues/1139 for just a few similar problems.
