### ISSUE TITLE
Disown child processes to avoid zombie processes

### ISSUE THREAD

**Issue by lord-re** [jwilm/alacritty#1833]
When you click an URL which triggers the opening of the browser, **the browser's process will stay as a Zombie process when closed**.

You can have multiple Z processes as long as you don't close alacritty.

As discussed on IRC 5 minutes ago, it may be interesting to **launch the browser as a daemon process and disown it** to avoid this issue.

**Comment by chrisduerr** [comment]
The relevant part of the code where the process is spawned can be found here:
https://github.com/jwilm/alacritty/blob/master/src/input.rs#L563

It would be possible to fix this by spawning a thread and waiting for the child (see [here](https://doc.rust-lang.org/std/process/struct.Child.html#method.wait)), however this would require spawning a thread just to wait for a process which is a bit pointless.

As mentioned in the initial comment, the better approach is to make the child process a daemon instead. An example for that can be found here:
https://github.com/jwilm/alacritty/blob/master/src/input.rs#L243-L251
