### ISSUE TITLE
Alacritty resets colours prior to shell being usable

### ISSUE THREAD

**Issue by lachlantula** [jwilm/alacritty#1836]
To display what I mean by the (admittedly confusing) title, [here's a demonstration.](https://gfycat.com/DefensiveAggravatingLiger)

As you can see, Alacritty flashes the correct colour scheme momentarily, before switching back to the default colour scheme. There are no defined `colors` in my `alacritty.yml`. My `.zshrc` runs a command that intends to change the colour scheme; for `wpgtk`, for instance, this is `wpg -t`. Trying `(cat $HOME/.config/wpg/sequences &)` later produces the same results, albeit a bit quicker, seemingly.

I am experiencing this issue with both `pywal` and `wpgtk`; I am currently using the latter. I am running Alacritty 0.2.1 on Manjaro i3, with pywal 3.2.1 and wpgtk 5.8.0.

**Comment by chrisduerr** [comment]
I am still not sure what the issue here is. Alacritty seems to load some custom colorscheme, please have a look at `alacritty -v` to determine which one that is.

**Comment by Lachlantula** [comment]
Running `alacritty -v` outputs the following:

```
Welcome to Alacritty.
Configuration loaded from /home/lshoesmith/.config/alacritty/alacritty.yml
device_pixel_ratio: 1
width: 947, height: 1031
Initializing glyph cache
Finished initializing glyph cache in 0.137541944
width: 960, height: 728
Cell Size: (11 x 27)
PTY Dimensions: Line(24) x Column(80)
Font size changed: Size(32)
width: 947, height: 1031
[unhandled osc_dispatch]: [['1','3',],['#','c','8','a','a','c','1',],] at line 754
[unhandled osc_dispatch]: [['1','7',],['#','c','8','a','a','c','1',],] at line 754
[unhandled osc_dispatch]: [['1','9',],['#','3','6','0','b','0','a',],] at line 754
[unhandled osc_dispatch]: [['7','0','8',],['[','1','0','0',']','#','3','6','0','b','0','a',],] at line 754
[unhandled osc_dispatch]: [['4',],['2','5','6',],['#','c','8','a','a','c','1',],] at line 754
[Unhandled CSI] action='p', args=[], intermediates=[33]
[Unhandled CSI] action='l', args=[3, 4], intermediates=[63]
[Unhandled CSI] action='t', args=[22, 0, 0], intermediates=[]
[Unhandled CSI] action='t', args=[22, 2], intermediates=[]
[Unhandled CSI] action='t', args=[22, 1], intermediates=[]
[unhandled osc_dispatch]: [['1','0',],['?',],] at line 754
[unhandled osc_dispatch]: [['1','1',],['?',],] at line 754
[Unhandled CSI] action='t', args=[23, 2], intermediates=[]
[Unhandled CSI] action='t', args=[23, 1], intermediates=[]
[Unhandled CSI] action='t', args=[22, 2], intermediates=[]
[Unhandled CSI] action='t', args=[22, 1], intermediates=[]
[Unhandled CSI] action='t', args=[23, 2], intermediates=[]
[Unhandled CSI] action='t', args=[23, 1], intermediates=[]
[Unhandled CSI] action='t', args=[23, 0, 0], intermediates=[]
```

You may view my Alacritty configuration [here](https://gist.github.com/Lachlantula/be1b3db1173f0af3b856ff530a0bc8ea), if it helps.

**Comment by chrisduerr** [comment]
> PTY Dimensions: Line(24) x Column(80)

Looks like it's working exactly as intended.

> width: 947, height: 1031

Looks like your window manager resizes it after it's been spawned.

> Font size changed: Size(32)

There is no DPR specified here, which means you haven't run the latest master for testing. Please run the latest master.

**Comment by lachlantula** [comment]
Sorry, this was an issue with my `~/.zshrc`; at the end of the script I run `tput reset`. Removing this line and subtituting it for the more-ubiquitous `clear` fixed my problems.
