### ISSUE TITLE
macOS `Paste` outputs double with Glutin v0.19.0

### ISSUE THREAD

**Issue by guildencrantz** [jwilm/alacritty#1842]
Which operating system does the issue occur on?
Darwin 16.7.0 x86_64

macOS Paste is outputting double since commit `2434547 - Upgrade Glutin to v0.19.0`.

I've tested a few times since the glutin v0.19.0 update (including v0.2.2, v0.2.3, and the current master HEAD)  and when I use the `Paste` action the clipboard buffer is output twice.

This behavior can be reproduced using just this config:

```
key_bindings:
  - { key: Period,   mods: Command, action: Paste                        }
```

Steps to replicate:

1. `echo -n "test" | pbcopy`
1. CMD-.

Expected behavior: `test` should be output to the prompt.
Actual behavior: `testtest` is output to the prompt.

When alacritty is compiled from git commit `8161798 - Fix grammatical errors in README` or earlier the expected behavior is observed.

**Comment by chrisduerr** [comment]
@guildencrantz Is my assumption correct that nothing is pasted at all when the line is removed from the config? Just to make sure there is no duplicate binding.

**Comment by guildencrantz** [comment]
@chrisduerr Correct, it just outputs the pressed character. And I'm serious: That two line config is what I used for final validation, so literally no other bindings defined.

**Comment by chrisduerr** [comment]
Just making sure there's no system shortcut pre-setup or anything like that. I don't have access to macOS myself, maybe someone else can verify this?

I'm unsure how the glutin update would have changed that, the only thing I can see is that the key is sent twice.

If you run `alacritty --print-events`, is the key event for `Period + Command` send twice?

**Comment by guildencrantz** [comment]
Yes, the `2434547fce7bf47a848f088f2600e8ba7027a62b` build does log `Period` is sent twice:

```
[2018-11-24 19:09] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140189987027360)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2018-11-24 19:09] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140189987027360)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2018-11-24 19:09] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140189987027360)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2018-11-24 19:09] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140189987027360)), event: ReceivedCharacter('v') }
```

The parent commit, however, doesn't:
```
glutin event: WindowEvent { window_id: WindowId(Id(140371448368032)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Released, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140371448368032)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140371448368032)), event: ReceivedCharacter('v') }
```

For context: The character received is `v` when `.` is pressed because I use the dvorak keymap.

**Comment by chrisduerr** [comment]
Very interesting, thanks for the logs. Looks like this is an issue with the upstream `winit` crate!

Would you mind testing the winit example just to confirm? You can find winit here:
https://github.com/tomaka/winit

You can run the example by running `cargo run --example window` in that project. That should print all events, so you should also see duplicate messages there, right?

**Comment by guildencrantz** [comment]
Sorry for the delay, was out of town.

Yes, `winit` (current head, commit `cb0a085968252dc4f0178a40fb5ba88d8530bb31`) shows the same duplication behavior:

```
WindowEvent { window_id: WindowId(Id(140521690408224)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } }
 } }
WindowEvent { window_id: WindowId(Id(140521690408224)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true }
 } } }
WindowEvent { window_id: WindowId(Id(140521690408224)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true }
 } } }
WindowEvent { window_id: WindowId(Id(140521690408224)), event: ReceivedCharacter('v') }
```

**Comment by guildencrantz** [comment]
No, and no other app registers repeat at that speed.

**Comment by richardxia** [comment]
I'm also seeing this issue on macOS, and I am also a Dvorak user. Let me know if there's anything I can do to help. I don't know any Rust, but let me know if there are any logs that I can grab and post here.

**Comment by alexanderjeurissen** [comment]
Same here observing the same issue on MacOs, also Dvorak user.

**Comment by rrichardson** [comment]
Interestingly, it is only for Command + Period I can't explain why.

If I remap it to Control + Period it works fine. If I remap it to Command + Comma or any other value, it is fine.

If I remap it to Control + . . it doesn't send twice.

**Comment by chrisduerr** [comment]
@aengelas You're talking about https://github.com/jwilm/alacritty/issues/458.

**Comment by aengelas** [comment]
@chrisduerr Ah, yes, I think you're right. I was reading all of these and must have commented in the wrong issue. It is slightly different though, in that this is affecting the Ctrl key, not Cmd. I'll post in the other thread.

**Comment by waynehoover** [comment]
Would love to use Alacritty, but this is a show stopper for me.

**Comment by richardxia** [comment]
I just upgraded to the latest version of alacritty, since https://github.com/jwilm/alacritty/commit/0f96a62218cfc78b56606f0dcc334d59202edf7c bumped glutin to 0.20.0, and I can confirm that this has fixed the double pasting issue I was experiencing.

**Comment by chrisduerr** [comment]
Thanks for the update!

**Comment by waynehoover** [comment]
Thanks for the update. Just a FYI to anyone else this fix is currently in the unreleased version.
