### ISSUE TITLE
Color contrast

### ISSUE THREAD

**Issue by huyvohcmc** [jwilm/alacritty#1844]
Is there any way to set color contrast?

![screen shot 2018-11-25 at 12 06 14 pm](https://user-images.githubusercontent.com/17645203/48975751-abaabc80-f0aa-11e8-9537-ad3e4996be07.png)

This image is the output of htop, as you can see the values of mem, swap etc are un-seenable without some contrasts. In iTerm2 it is easy to fix but in `alacritty.yml` I can't find any option to do that.

Which operating system does the issue occur on? MacOS 10.14.1

**Comment by chrisduerr** [comment]
Just change the colors in your `alacritty.yml` until the contrast is to your liking.
