### ISSUE TITLE
crashes on Wayland when starting tmux

### ISSUE THREAD

**Issue by stfl** [jwilm/alacritty#1847]
Which operating system does the issue occur on?
Fedora 27
4.18.18-100.fc27.x86_64

If on linux, are you using X11 or Wayland?
Wayland

I've built alacritty today:

commit 742a6b48a196cabf65354862548c07d057a28d55 (HEAD -> master, origin/master, 
Date:   Sun Nov 25 10:08:02 2018 +1300

It worked for some time until on a plane switch in tmux alacritty crashed.
Restarting alacritty and trying to reattach to tmux session leads to:

tmux version: 2.8

    tmux a

```
hread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:477
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   4: rust_begin_unwind
             at libstd/panicking.rs:326
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::panicking::panic
             at libcore/panicking.rs:52
   7: andrew::text::Text::get_width
             at libcore/macros.rs:20
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/andrew-0.1.4/src/text/mod.rs:99
             at libcore/option.rs:414
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/andrew-0.1.4/src/text/mod.rs:97
   8: <smithay_client_toolkit::window::concept_frame::ConceptFrame as smithay_client_toolkit::window::Frame>::redraw
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.2/src/window/concept_frame.rs:547
   9: <smithay_client_toolkit::window::Window<F>>::refresh
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.2/src/window/mod.rs:380
  10: winit::platform::platform::wayland::event_loop::EventsLoop::post_dispatch_triggers
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/wayland/event_loop.rs:257
  11: winit::platform::platform::wayland::event_loop::EventsLoop::poll_events
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/wayland/event_loop.rs:172
  12: alacritty::main
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/mod.rs:491
             at src/main.rs:85
  13: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: _start
```

when trying to start a new tmux session alacritty crashes with 

    tmux new

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:477
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   4: rust_begin_unwind
             at libstd/panicking.rs:326
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::panicking::panic
             at libcore/panicking.rs:52
   7: andrew::text::Text::get_width
             at libcore/macros.rs:20
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/andrew-0.1.4/src/text/mod.rs:99
             at libcore/option.rs:414
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/andrew-0.1.4/src/text/mod.rs:97
   8: <smithay_client_toolkit::window::concept_frame::ConceptFrame as smithay_client_toolkit::window::Frame>::redraw
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.2/src/window/concept_frame.rs:547
   9: <smithay_client_toolkit::window::Window<F>>::refresh
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.2/src/window/mod.rs:380
  10: winit::platform::platform::wayland::event_loop::EventsLoop::post_dispatch_triggers
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/wayland/event_loop.rs:257
  11: winit::platform::platform::wayland::event_loop::EventsLoop::poll_events
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/wayland/event_loop.rs:172
  12: alacritty::main
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.0/src/platform/linux/mod.rs:491
             at src/main.rs:85
  13: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: _start
thread 'pty reader' panicked at 'called `Result::unwrap()` on an `Err` value: EventsLoopClosed', libcore/result.rs:1009:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:477
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   4: rust_begin_unwind
             at libstd/panicking.rs:326
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::result::unwrap_failed
             at libcore/macros.rs:26
```

**Comment by chrisduerr** [comment]
Can you reproduce this with a completely empty Alacritty and tmux configuration?

**Comment by trimental** [comment]
@stfl When opening the plane that crashes alacritty on another terminal what is shown as the terminal title? Also what is your systems default sans font (i.e what does `fc-match sans`) return?

Hopefully with those two things I'll be able to replicate the issue

**Comment by stfl** [comment]
The title of the terminal (xfce4-terminal) that starts alacritty:
`Terminal - 1:1:run - "sll-developer-machine.mission-embedded.at" 3#`

I disabled dynamic_title in alacritty.yml and it seams to work (for now)

    fc-match sans

DejaVuSans.ttf: "DejaVu Sans" "Book"

I have this font configured:

```
font:
  normal:
    family: Source Code Pro for Powerline
    style: Regular
  bold:
    family: Source Code Pro for Powerline
    style: Bold
  italic:
    family: Source Code Pro for Powerline
    style: Italic
  size: 11.0
```

**Comment by trimental** [comment]
Unfortunately I cannot seem to replicate this issue.

![image](https://user-images.githubusercontent.com/40879396/49198917-6a7b1b00-f3d0-11e8-9544-a5f6081bbdb7.png)

Is the look of the alacritty window similar to the screenshot above?

Not being able to replicate this issue makes it hard to track it down. I could write tests that you could perhaps run to help find the source of this issue. You can either email me or we could discuss this on either the smithay matrix channel or alacritty IRC with my handle 'trimental' :)

**Comment by stfl** [comment]
The alacritty windows has no title at all:

![image](https://user-images.githubusercontent.com/1321542/49233341-1daa3b00-f3f6-11e8-974a-e879b380ddd4.png)

I now checked now in conjunction with `.tmux.conf`:

## original setup (crash)

alacritty.yml:

    dynamic_title: true

.tmux.conf:

    set-window-option -g automatic-rename on
    set-option -g set-titles on

-> startint alacritty -> no title
-> starting tmux -> no title or crash..

## no crash 1

alacritty.yml:

    dynamic_title: false

.tmux.conf:

    set-window-option -g automatic-rename on
    set-option -g set-titles on

-> startint alacritty -> no title
-> starting tmux -> no title **no** crash..

## no crash 2

alacritty.yml:

    dynamic_title: true

.tmux.conf:

    set-window-option -g automatic-rename off
    set-option -g set-titles off

-> startint alacritty -> no title
-> starting tmux -> no title **no** crash.. (for the short time testing)

## no crash 3

alacritty.yml:

    dynamic_title: true

.tmux.conf:

    set-window-option -g automatic-rename on
    set-option -g set-titles off

-> startint alacritty -> no title
-> starting tmux -> no title **no** crash.. (so far.. I will stick to this one for now..)

## crash

alacritty.yml:

    dynamic_title: true

.tmux.conf:

    set-window-option -g automatic-rename off
    set-option -g set-titles on

-> startint alacritty -> no title
-> starting tmux -> **correct** title -> crash at some pane switches..

**Comment by trimental** [comment]
Do you see the title with any of the [smithay-client-toolkit](https://github.com/Smithay/client-toolkit) examples? 

Its strange that no title is displayed to begin with.

**Comment by stfl** [comment]
I have a title in all of them (besides pointer_input which does not set a window title..)

**Comment by trimental** [comment]
Version 0.1.5 of andrew fixes two issues to do with text measurement calculations, perhaps one of those fixes helps here.

**Comment by stfl** [comment]
I had a crash again today.
I reenabeld all the title options

`dynamic_title: true`

`set-window-option -g automatic-rename on`
`set-option -g set-titles on`

I don't see any title in Alacritty. Might be related to #2104 ?
with backtrace enabled I get this:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:476
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   4: rust_begin_unwind
             at libstd/panicking.rs:325
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::panicking::panic
             at libcore/panicking.rs:52
   7: andrew::text::Text::get_width
             at libcore/macros.rs:20
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/andrew-0.1.6/src/text/mod.rs:99
             at libcore/option.rs:424
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/andrew-0.1.6/src/text/mod.rs:97
   8: <smithay_client_toolkit::window::concept_frame::ConceptFrame as smithay_client_toolkit::window::Frame>::redraw
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.4/src/window/concept_frame.rs:556
   9: <smithay_client_toolkit::window::Window<F>>::refresh
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.4/src/window/mod.rs:384
  10: winit::platform::platform::wayland::event_loop::EventsLoop::post_dispatch_triggers
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/wayland/event_loop.rs:268
  11: winit::platform::platform::wayland::event_loop::EventsLoop::poll_events
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/wayland/event_loop.rs:183
  12: alacritty::main
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.18.1/src/platform/linux/mod.rs:504
             at ./.cargo/git/checkouts/alacritty-de74975f496aa2c0/851e773/src/main.rs:82
  13: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by trimental** [comment]
I have now successfully replicated the issue and am working on a fix. The fix should be apart of andrew 2.1 which will be used by SCTK 0.5 which should be updated to winit through https://github.com/tomaka/winit/pull/790

**Comment by trimental** [comment]
I think that https://github.com/trimental/andrew/commit/0ad9d14e1a30b07b1beec1051898d691caa1a277 will fix this issue once it works its way up the dependencies into alacritty

**Comment by trimental** [comment]
I'm assuming this is fixed now after a cargo update?

**Comment by chrisduerr** [comment]
Thanks for the update, `get_width` can't panic on an unwrap anymore, so this issue can definitely be closed.

This has just been verified on IRC too, so if this issue still exsits, updating to the latest master will resolve that.
