### ISSUE TITLE
Does not load the config file at %UserProfile%\alacritty.yml

### ISSUE THREAD

**Issue by PetterS** [jwilm/alacritty#1850]
This occurs on Windows.

I have a config file at `%UserProfile%\alacritty.yml`. This is where it is supposed to be according to the readme. When I run
```
Alacritty.exe --config-file %UserProfile%\alacritty.yml
```
everything works.

But when I run just `Alacritty.exe`, it does not use the config file and prints warnings:
```
problem with config: font.offset.x: invalid type: floating point `0`, expected i8 at line 86 column 8; Using default value
problem with config: font.offset.y: invalid type: floating point `0`, expected i8 at line 87 column 8; Using default value
problem with config: font.glyph_offset.x: invalid type: floating point `0`, expected i8 at line 93 column 8; Using default value
problem with config: font.glyph_offset.y: invalid type: floating point `0`, expected i8 at line 94 column 8; Using default value
Config `custom_cursor_colors` is deprecated.
Config `hide_cursor_when_typing` is deprecated. Please use `mouse.hide_when_typing` instead.
```

**Comment by chrisduerr** [comment]
What does it print when running `alacritty -v`? That should give you the place where the config is actually located.

**Comment by PetterS** [comment]
Thanks. 👍 Looks like it uses `HOME` even on Windows. Simply A documentation issue, then.

**Comment by chrisduerr** [comment]
@PetterS Are you running bash on Windows or the cmd.exe?

**Comment by PetterS** [comment]
I am starting it by clicking on the .exe. (or from cmd with -v)

**Comment by zacps** [comment]
This is planned to change. See https://github.com/jwilm/alacritty/issues/1660.

**Comment by PetterS** [comment]
Thanks!
