### ISSUE TITLE
Don't work alacritty in Fedora 29 Gnome with Wayland

### ISSUE THREAD

**Issue by Dmitryi** [jwilm/alacritty#1851]
$sudo alacritty

error: XDG_RUNTIME_DIR not set in the environment.
No protocol specified
thread 'main' panicked at 'Failed to initialize any backend!
    Wayland status: NoCompositorListening
    X11 status: XOpenDisplayFailed
', /home/fedora/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/linux/mod.rs:428:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ rustc --version
rustc 1.30.1
$ cargo --version      
cargo 1.30.0
$ sudo alacritty --version 
alacritty 0.2.1

**Comment by chrisduerr** [comment]
Does `WAYLAND_DISPLAY= alacritty` work?

It actually looks like there are multiple disconnected problems. I don't think the `XDG_RUNTIME_DIR` error is related to the failure to initialize any backend for example.

**Comment by ndreas** [comment]
I get the same crash in Gnome+Wayland when I run `sudo alacritty` and it's because Alacritty can't connect to the Wayland compositor. `sudo gnome-terminal` also fails, but `sudo -E alacritty` works since it carries over the necessary environment needed to connect to the compositor.

**Comment by Dmitryi** [comment]
@ndreas New error

sudo -E alacritty
problem with config: invalid value: string "ClearLogNotice", expected Paste, Copy, PasteSelection, IncreaseFontSize, DecreaseFontSize, ResetFontSize, ScrollPageUp, ScrollPageDown, ScrollToTop, ScrollToBottom, ClearHistory, Hide, or Quit; Skipping value
[unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/','2','9','/','h','o','m','e','/','f','e','d','o','r','a',],] at line 754
[Unhandled CSI] action='t', args=[22, 0, 0], intermediates=[]

Alacritty start

**Comment by chrisduerr** [comment]
Thanks for the help ndreas, looks like this problem is solved now.

@Dmitryi please make sure you're using the correct configuration file for the version of Alacritty you're running. That warning probably means you're running the configuration file of the latest master with an older Alacritty version.
