### ISSUE TITLE
Font pixel size is inconsistent with other applications

### ISSUE THREAD

**Issue by daboross** [jwilm/alacritty#1852]
I'm using Linux and X11. Operating system is openSUSE tumbleweed.

I've tried to get into using alacritty a few times, but haven't really actually started using it yet. One of the issues I've been running into is getting the configuration to match my configuration for other terminals, in particular the font size.

When I "Text size" to 10.0 in most or all software on my computer, I get the same text size, and the same number of lines fit in my screen - this is consistent between my IDE, browser, and current terminal (Konsole). But when I set `size: 10.0` in alacritty, I get strangely huge text.

See this screenshot:

![image](https://user-images.githubusercontent.com/1152146/49195628-ba100700-f33c-11e8-80d8-cafc68bc07b2.png)

I can almost approximate the right size by using `size: 6.0`, but this is still not *quite* on and it's bothering me more than it should.

Is there a particular reason that alacritty's "size" scale is inconsistent with other applications? Is this an issue in general, or has anyone else run into this?

If this is a known issue, are there any workarounds or anything I can do to get the "right" size?

This is tested with 742a6b48a196cabf65354862548c07d057a28d55, though I have tried it several times before and run into a similar issue.

**Comment by chrisduerr** [comment]
Alacritty scales by DPI by default. Try running it with `WINIT_HIDPI_FACTOR=1 alacritty` to see if that fixes the issue.

**Comment by sukovec** [comment]
Can this behavior be disabled in config? I've used alacritty for long time, but now I've installed new version and on laptop display, font is ridiculously big although I try to set DPI for both monitor to 96 (you can see old and new versions running together on this screenshot: https://sh.sukovec.cz/upload/alacritty-dpi-old-new-comparison.png )

Using WINIT_HIDPI_FACTOR=1 is working, but then it would be necessary to replace /usr/bin/alacritty with some script after every package upgrade...

**Comment by chrisduerr** [comment]
You can put it into the `env` section of the configuration file. Though if it's extremely off, there might be something wrong with your monitor's physical dimensions in `xrandr`, so maybe you want to fix that.

**Comment by sukovec** [comment]
Yeah, it worked. It's definitely something wrong, but as all other software is working OK (maybe is everyting ignoring DPI?), I don't want to waste time on solving this and workaround is fine. Maybe it can be a bug? Do you want some specific info about this? I have two monitors - both fullHD, both should be set to 96dpi (although one is 22" and the other one 15.6")

**Comment by chrisduerr** [comment]
> maybe is everyting ignoring DPI?

Yes, that is correct.

**Comment by daboross** [comment]
Is there any way to tell where `winit` is getting the idea that I should have a hidpi factor greater than 1? As far as I can tell I've configured everything possible to have no scaling and a regular 96 dpi.

Even `xdpyinfo` gives the correct scaling here:

```
$ xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    1920x1080 pixels (508x285 millimeters)
  resolution:    96x96 dots per inch
```

**Comment by chrisduerr** [comment]
The DPI is calculated automatically based on the dimensions of the display (output of `xrandr`).

**Comment by daboross** [comment]
Shouldn't the display manager and X settings be referred to instead?

In both Windows and Linux most or all applications respect user settings, whether they want higher or lower DPI than the display's default. `alacritty` is a stark outlier here as far as I can tell.

I mean I get what it's doing, but is there any rational for why this is the correct thing to do?

**Comment by chrisduerr** [comment]
It's not possible to get a per-monitor scaling with the X settings.
