### ISSUE TITLE
Can't type # or ~ (Ubuntu 16.10 UK Keyboard)

### ISSUE THREAD

**Issue by joel-wright** [jwilm/alacritty#186]
Alacritty compiles and starts fine, but the #~ key on my laptop keyboard is ignored. I'm using the standard Ubuntu 'English (UK)' keymap on 16.10.

**Comment by quininer** [comment]
duplicate https://github.com/jwilm/alacritty/issues/55

**Comment by joel-wright** [comment]
Sorry, I searched for the issue but couldn't find it. Closing.
