### ISSUE TITLE
Using alacritty as term, colors do not display in htop on macOS

### ISSUE THREAD

**Issue by zaayer** [jwilm/alacritty#1862]
I'm using macOS and running Alacritty v0.2.3.

I've installed the alacritty terminfo and found that colors do not display correctly in htop. See screenshots. (I'm using command htop, because I currently use a work around by setting the TERM variable at the local level in a function to xterm-256color to make it work).

![screen shot 2018-12-04 at 2 21 00 pm](https://user-images.githubusercontent.com/18469554/49467275-14dbaf80-f7d0-11e8-838e-5e8cb3357388.png)

![screen shot 2018-12-04 at 2 19 15 pm](https://user-images.githubusercontent.com/18469554/49467284-1c9b5400-f7d0-11e8-9be5-c02ecb0851b8.png)

Then in the screenshots below, you can see if I set the TERM to xterm-256color, the colors work fine.

![screen shot 2018-12-04 at 2 21 22 pm](https://user-images.githubusercontent.com/18469554/49467313-2cb33380-f7d0-11e8-81ab-7a5aa2d1fe99.png)

![screen shot 2018-12-04 at 2 19 33 pm](https://user-images.githubusercontent.com/18469554/49467318-2fae2400-f7d0-11e8-9af0-f31e1600569e.png)

Does anyone have any idea what may be going on?

**Comment by chrisduerr** [comment]
@zaayer Did you follow the readme instructions for installing the terminfo file?

**Comment by zaayer** [comment]
Yeah, I did follow it. Before I installed it, I had an issue that nvim italics weren't working, but now using alacritty as my TERM allows nvim to display everything correctly.

**Comment by zaayer** [comment]
@chrisduerr I’m actually using the home brew installed fish. Once I get back to my computer I can try it with bash to see if the issue persists.

**Comment by zaayer** [comment]
@chrisduerr Sorry about the delay on this, ended up having to travel for work and didn't bring my macbook with me. So I installed the latest bash using brew and the issue is also occurring in bash. I checked both using TERM = alacritty and TERM = xterm-256color and the same issue happens in fish as documented in my first post.

I also tried TERM = alacritty-direct and it has the same issue as alacritty (I'm not sure what the actual difference is between the two, but just wanted to verify).

**Comment by chrisduerr** [comment]
That's very interesting! It seems odd to me though that with a lower pairs value, the color starts rendering. I'd expect it to be the opposite way around.

Please do send this as a PR, I think this should be fine when xterm uses the same value here. If I had to take a guess, maybe we're running into an overflow here? But then it shouldn't work on other systems, but it works just fine for me. Though macOS has a super ancient bash by default, so who knows.

Thanks for looking into this.

**Comment by YoEight** [comment]
Greetings,

I want to mention that I also get that issue, but I'm using `zsh` (not Apple default, but one install with `Homebrew`), with the 5.6.2 version.

I'm running OSX 10.14.

Thanks for your time.

**Comment by zaayer** [comment]
I've created a pull request which fixes this issue. Let me know if you need any other updates or have any comments.

**Comment by dnkl** [comment]
Glad that this has been resolved. Just wanted to mention that at least on my system (arch, with ncurses 6.1), xterm-256color has

```
colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
```

which is the reason the alacritty terminfo has/had that number to begin with.

Could it be that this is a bug that has been fixed in more recent versions of htop? My htop (version 2.2.0) has no apparent problems with colors with pairs=0x10000.

**Comment by chrisduerr** [comment]
@dnkl That's not unlikely, since `htop` worked fine for me too. But I guess unless we run into issues with the maximum number of color pairs, going with the lower number that works everywhere should be a safer bet.

**Comment by zaayer** [comment]
@dnkl @chrisduerr  - that is interesting perhaps it's just a mac problem? I'm also using htop 2.2, but the xterm-256color on mac has colors of 0x7FFF (well it has 32767, technically). Agree with chris though, I can't imagine the lower pairs number causing problems, but if it did I suppose we could create a mac terminfo and a linux terminfo?

**Comment by chrisduerr** [comment]
> we could create a mac terminfo and a linux terminfo

That would be the worst case scenario I think. The different configuration files already are a massive burden for maintenance so I don't think that would ever be a nice solution. I think what we have should work perfectly for now though!
