### ISSUE TITLE
Need for contributing file

### ISSUE THREAD

**Issue by vsag96** [jwilm/alacritty#1870]
I have searched the repo but could not find it.This is a popular application it has over 13k stars, it's time that we have a contributing.md file. Off the top of my head it can talk about formatting the code and adding a changelog entry. It saves new people time and that's the first thing some people search for in a repository. Thoughts?

**Comment by chrisduerr** [comment]
I think this is a great idea and don't see how it would harm anyone.

I can't say what exactly I'd expect to be inside it right now, but maybe my checklist for code reviews can help with some baselines what people should watch out for.

```
FUNCTIONALITY: Does it actually work? (includes `cargo test`)
PERFORMANCE: Does it work good enough for Alacritty?
STYLE: Is the code clean?
DOCUMENTATION: Is the code documented?
TESTS: Are there any test that could be added?
BENCHES: Are there any benches that could be added?
CHANGELOG: Is an entry present?
```

I'll usually make sure I've gone through all of these points before any PR is merged. So someone who is contributing should probably check these too to reduce the potential back and forth. Note that these are just quick notes for myself and shouldn't be taken literally the way they're presented here.
