### ISSUE TITLE
"Unknown capability" error when installing terminfo

### ISSUE THREAD

**Issue by talal** [jwilm/alacritty#1876]
OS: macOS 10.14.1
Alacritty: built from `master`

I get multiple "unknown capability" errors when installing Alacritty's terminfo by following the instructions from the `INSTALL.md` file.

An example of the error:
```
"alacritty.info", line 27, col 43, terminal 'alacritty+common': unknown capability 'AX'
```

**Comment by chrisduerr** [comment]
These are not errors, but warnings.

Some terminal application read capabilities which aren't officially standardized and part of the terminal database. Alacritty supports some of those capabilities.

This is not a problem and shouldn't cause any issues.
