### ISSUE TITLE
Inserting character at any prompt allows for temporary modification of the prompt

### ISSUE THREAD

**Issue by AlexDvorak** [jwilm/alacritty#1882]
## Character in question
`\342\217\217`
## .bashrc
```bash
export PS1='[\u \W]\$ '
export TERMINAL='alacritty'
```
## Versions
```
linux 4.18.12.arch1-1
i3-wm 4.15-1
alacritty 0.2.1
GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
```
Font: [Inconsolata for Powerline](https://github.com/powerline/fonts/tree/master/Inconsolata-g)
## Description
Typing/pasting this character at a bash prompt will allow the cursor to back up onto the prompt text itself. Appears to work with all prompts, tested with Perl6 as well as bash

**Comment by chrisduerr** [comment]
Can't repro, closing as fixed by #1318.

If this issue should still be present, please let me know. Also please include information about the behavior with different terminal emulators and shells.
