### ISSUE TITLE
Alacritty prints scancodes instead of copy-paste on macos

### ISSUE THREAD

**Issue by TheIndifferent** [jwilm/alacritty#1886]
Trying out latest Alacritty for the first time, macos 10.14.2.

When pressing Command-C and Command-V seeing following output (if the `Paste` actin is set, then the scancode is inserted *before* the last character of inserted text)

![alacritty-command-c-command-v](https://user-images.githubusercontent.com/9323482/49698230-27cff480-fbc1-11e8-85df-4b4c0db93489.png)

Pasting with middle mouse button (if configured) works correctly, so that does not look like a buffer issue.

Output of `--print-events` is following:
```
~❯  /Applications/Alacritty.app/Contents/MacOS/alacritty --print-events
[Unhandled CSI] action='h', args=[1034], intermediates=[63]
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: Focused(true) }
glutin event: Awakened
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 8, state: Pressed, virtual_keycode: Some(C), modifiers: ModifiersState { shift:false, ctrl: false, alt: false, logo: true } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: ReceivedCharacter('c') }
glutin event: Awakened
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Released, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 8, state: Released, virtual_keycode: Some(C), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 9, state: Pressed, virtual_keycode: Some(V), modifiers: ModifiersState { shift:false, ctrl: false, alt: false, logo: true } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: ReceivedCharacter('v') }
glutin event: Awakened
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Released, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 9, state: Released, virtual_keycode: Some(V), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140713351318912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(RWin), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
```

**Comment by chrisduerr** [comment]
This looks like the `RWin` key is detected instead of the `C` key when copying. If you change the config mapping from Command + C to Command + RWin, does everything work properly?

**Comment by TheIndifferent** [comment]
Hm, interesting, when I am trying to use `Command+C` it prints `COPY`, but when I am trying to use `Command+V` it does not print anything.

**Comment by TheIndifferent** [comment]
I've tried that on tag `v0.2.3`, should I try that on master as well?

**Comment by chrisduerr** [comment]
Yes, please try on the latest master just to make sure all dependencies are updated.

`PASTE` not getting printed seems extremely odd to me, since the key is reported according to your output. Please make sure you have the right configuration file loaded (its location is output with `alacritty -v`) and make sure the binding is `Paste` and not `PasteSelection`.

**Comment by TheIndifferent** [comment]
Yes, my mistake, commented out `Cmd+V` from the config.

Tried on master now, here's the output in the console:
```
❯  ./target/release/osx/Alacritty.app/Contents/MacOS/alacritty
COPY
PASTE
```

And here's how it looks:
![alacritty-reproducing-1](https://user-images.githubusercontent.com/9323482/49702927-eeb67500-fbfe-11e8-9203-a522a869e91b.png)

**Comment by TheIndifferent** [comment]
* when pressing `Command+C`, `8` is being printed to the command line.
* when trying to paste a text `./target/release/osx/Alacritty.app/Contents/MacOS/alaritty` with `Command+V` combination, `./target/release/osx/Alacritty.app/Contents/MacOS/alaritt9y` is being inserted instead, with cursor being placed after `9` before trailing `y`.
* when `Paste` shortcut is disabled in the config, only `9` is being printed on `Command+V`.
* pasting with mouse works correctly.
* the following config is being used (`shell` section has to be modified): https://github.com/TheIndifferent/dotfiles/blob/master/macos/alacritty_and_tmux/.config/alacritty/alacritty.yml

**Comment by chrisduerr** [comment]
Okay, so this issue is completely unrelated to copy-pasting, but the real issue is that some weird numbers are inserted when you press `Command + C` and `Command + V`.

I'm very surprised scancodes are being printed to the shell for you, since it should only print received characters.

I've got another patch for you which might help troubleshooting this:

<details>

```diff
diff --git a/src/event.rs b/src/event.rs
index c9043a0..7b1db04 100644
--- a/src/event.rs
+++ b/src/event.rs
@@ -383,6 +383,7 @@ impl<N: Notify> Processor<N> {
                         }
                     },
                     ReceivedCharacter(c) => {
+                        println!("GLUTIN EVENT, RECEIVED CHAR: '{}'", c);
                         processor.received_char(c);
                     },
                     MouseInput { state, button, modifiers, .. } => {
diff --git a/src/input.rs b/src/input.rs
index 3eafa43..6c7f604 100644
--- a/src/input.rs
+++ b/src/input.rs
@@ -209,6 +209,7 @@ impl Action {
     fn execute<A: ActionContext>(&self, ctx: &mut A, mouse_mode: bool) {
         match *self {
             Action::Esc(ref s) => {
+                println!("ESC ACTION");
                 ctx.scroll(Scroll::Bottom);
                 ctx.write_to_pty(s.clone().into_bytes())
             },
@@ -284,6 +285,7 @@ impl Action {
     }
 
     fn paste<A: ActionContext>(&self, ctx: &mut A, contents: &str) {
+        println!("PASTING");
         if ctx.terminal_mode().contains(TermMode::BRACKETED_PASTE) {
             ctx.write_to_pty(&b"\x1b[200~"[..]);
             ctx.write_to_pty(contents.replace("\x1b","").into_bytes());
@@ -406,6 +408,7 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
                 32 + 1 + line.0 as u8,
             ];
 
+            println!("NORMAL MOUSE REPORT");
             self.ctx.write_to_pty(msg);
         }
     }
@@ -418,6 +421,7 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
         };
 
         let msg = format!("\x1b[<{};{};{}{}", button, column + 1, line + 1, c);
+        println!("SGR MOUSE REPORT");
         self.ctx.write_to_pty(msg.into_bytes());
     }
 
@@ -615,6 +619,7 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
                 content.push(b'O');
                 content.push(cmd);
             }
+            println!("SCROLL TERMINAL");
             self.ctx.write_to_pty(content);
         } else {
             for _ in 0..scroll_multiplier {
@@ -633,6 +638,7 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
             };
 
             let msg = format!("\x1b[{}", chr);
+            println!("FOCUS SCHANGE");
             self.ctx.write_to_pty(msg.into_bytes());
         }
     }
@@ -682,6 +688,7 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
 
     /// Process a received character
     pub fn received_char(&mut self, c: char) {
+        println!("RECEIVED CHAR: '{}'", c);
         if !*self.ctx.suppress_chars() {
             self.ctx.scroll(Scroll::Bottom);
             self.ctx.clear_selection();
```

</details><br>

With this patch, every time Alacritty is writing to the pty, it should be printed in the stdout of the terminal you started Alacritty from. Try starting Alacritty and then pressing `Command + C` and tell me what's printed to stdout.

**Comment by TheIndifferent** [comment]
Will do. I am away till next Saturday, so unfortunately will not be able to
do that soon.

**Comment by TheIndifferent** [comment]
Ok, results are in:

For `Command+C`:
```
ESC ACTION
GLUTIN EVENT, RECEIVED CHAR: 'c'
RECEIVED CHAR: 'c'
```

For `Command+V`:
```
ESC ACTION
GLUTIN EVENT, RECEIVED CHAR: 'v'
RECEIVED CHAR: 'v'
```

I've tried that on fresh master. I will try building previous versions, to see if it was introduced at some point via some dependency bump.

**Comment by TheIndifferent** [comment]
Follow up:

I've tried building each version starting with 0.2.0 and up, noticed that it works correctly in 0.2.1 but breaks in 0.2.2, so I went build-and-test commit by commit.

This is the commit that breaks it: https://github.com/jwilm/alacritty/commit/a727801f60286282795e850637de7e21f15d4114

To verify I tried commenting out all custom key bindings from the config:
https://github.com/TheIndifferent/dotfiles/blob/master/macos/alacritty_and_tmux/.config/alacritty/alacritty.yml#L471-L485

Of course after that everything worked. Checked the article again:
https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/

According to the article, my config was correct. But then googled for different config on github:
https://github.com/tmcdonell/config-alacritty/blob/master/alacritty.yml#L338-L344

Seems like the second character is given as is, not by the code. So I tried that one and it worked.

The issue is resolved for me, thank you for your help! I can only suggest to include the correct example in the sample config for mac, so people would not need to go to the article that suggests non-working configuration:
https://github.com/jwilm/alacritty/blob/master/alacritty_macos.yml

**Comment by chrisduerr** [comment]
Glad you were able to figure it out. IIRC there already are issues around for making some more keybindings work and if they are supported on all platforms, they could be added to the default config too. Maybe #40 will help with this too.
