### ISSUE TITLE
alacritty-0.2.4 fails to compile due to unstable features

### ISSUE THREAD

**Issue by UnixRonin** [jwilm/alacritty#1889]
alacritty-0.2.4 fails to compile against stable rust-1.29.1-r1 due to unstable features used.  I'm going to retry against rust-1.31.0.

Which operating system does the issue occur on?

Gentoo Linux 17.0 profile

If on linux, are you using X11 or Wayland?

X11

   Compiling crossbeam-utils v0.2.2
error[E0658]: scoped lint `clippy::all` is experimental (see issue #44690)
 --> copypasta/src/lib.rs:3:9
  |
3 | #![deny(clippy::all, clippy::if_not_else, clippy::enum_glob_use, clippy::wrong_pub_self_convention)]
  |         ^^^^^^^^^^^

error[E0658]: scoped lint `clippy::if_not_else` is experimental (see issue #44690)
 --> copypasta/src/lib.rs:3:22
  |
3 | #![deny(clippy::all, clippy::if_not_else, clippy::enum_glob_use, clippy::wrong_pub_self_convention)]
  |                      ^^^^^^^^^^^^^^^^^^^

error[E0658]: scoped lint `clippy::enum_glob_use` is experimental (see issue #44690)
 --> copypasta/src/lib.rs:3:43
  |
3 | #![deny(clippy::all, clippy::if_not_else, clippy::enum_glob_use, clippy::wrong_pub_self_convention)]
  |                                           ^^^^^^^^^^^^^^^^^^^^^

error[E0658]: scoped lint `clippy::wrong_pub_self_convention` is experimental (see issue #44690)
 --> copypasta/src/lib.rs:3:66
  |
3 | #![deny(clippy::all, clippy::if_not_else, clippy::enum_glob_use, clippy::wrong_pub_self_convention)]
  |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.

AFTER updating to dev-lang/rust-bin-1.31.0, alacritty compile failed because it asserted it could not find cargo.  Not sure what's up with that:

>>> Source unpacked in /var/tmp/portage/x11-terms/alacritty-0.2.4/work
>>> Preparing source in /var/tmp/portage/x11-terms/alacritty-0.2.4/work/alacritty-0.2.4 ...
 * Applying alacritty-0.2.4-avoid-fetching-custom-windows-deps.patch ...     [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/x11-terms/alacritty-0.2.4/work/alacritty-0.2.4 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/x11-terms/alacritty-0.2.4/work/alacritty-0.2.4 ...
/var/tmp/portage/x11-terms/alacritty-0.2.4/temp/environment: line 1202: cargo: command not found
 * ERROR: x11-terms/alacritty-0.2.4::gentoo failed (compile phase):
 *   cargo build failed

**Comment by chrisduerr** [comment]
Please update your compiler to the latest stable version. Only the latest stable is supported by Alacritty.
