### ISSUE TITLE
Line height looking weird on macOS

### ISSUE THREAD

**Issue by fernandezpablo85** [jwilm/alacritty#189]
Just installed and the terminal looks "compressed" vertically (see image).

Also, the background color changes if you move the mouse pointer over it.

![screen shot 2017-01-07 at 1 29 01 pm](https://cloud.githubusercontent.com/assets/28029/21743263/48ad41e2-d4dd-11e6-8768-acd0217faa40.png)

**Comment by d3rrial** [comment]
Change the y offset in ~/.alacritty.yml until it looks how you want it.

**Comment by spiderpug** [comment]
I used the `Monaco` font and an offset of `x: 1`, `y: 1`. Looks good.

**Comment by fernandezpablo85** [comment]
Fixed! Thanks!
