### ISSUE TITLE
start_maximized doesn't work on KDE

### ISSUE THREAD

**Issue by gggggtj** [jwilm/alacritty#1902]
Which operating system does the issue occur on?
ThinkPad x1 carbon 5gen(1920×1080)
Latest KDE neon

If on linux, are you using X11 or Wayland?
X11

Width not be maximized.

**Comment by chrisduerr** [comment]
I've received varying feedback on this feature with different window managers on X11. It also does not have any effect on i3 for example, but it works just fine on macOS.

Note that i3 doesn't really have a maximized mode though, only a fullscreen one. These are treated differently by the window library Alacritty is using. I'd assume KDE has both though?

**Comment by chrisduerr** [comment]
Would you mind cloning https://github.com/tomaka/glutin, appyling the attached patch using `git apply <patchfile>` and then running it using `cargo run --example window`? This should make sure the error is not due to a problem in Alacritty.

Patch:
```diff
diff --git a/examples/window.rs b/examples/window.rs
index 0786887..8eebfcb 100644
--- a/examples/window.rs
+++ b/examples/window.rs
@@ -6,9 +6,10 @@ use glutin::GlContext;
 
 fn main() {
     let mut events_loop = glutin::EventsLoop::new();
-    let window = glutin::WindowBuilder::new().with_title("A fantastic window!");
+    let window = glutin::WindowBuilder::new().with_title("A fantastic window!").with_maximized(true);
     let context = glutin::ContextBuilder::new();
     let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();
+    gl_window.set_maximized(true);
 
     let _ = unsafe { gl_window.make_current() };
 
```

**Comment by paulie-g** [comment]
I have the same problem with start_maximized with openbox. Tested as per @chrisduerr and the example window does start maximized correctly. Presumably this means alacritty is the problem?

**Comment by chrisduerr** [comment]
@paulie-g The example I've set uses two different ways to maximize the application, just to make sure that it really is maximized. Could you try removing the `gl_window.set_maximized(true);` line to check if it still works?

**Comment by paulie-g** [comment]
@chrisduerr Both work on their own. The difference is that .with_maximized(true) results in a maximized window with the contents stretched to fill the window, while .set_maximized(true) results in the pyramid remaining the same size, positioned bottom left.

**Comment by paulie-g** [comment]
Disregard the stretch/positioning difference, it appears to have been a glitch I can no longer reproduce.

**Comment by paulie-g** [comment]
```
[2018-12-20 13:42] [INFO] Welcome to Alacritty.
[2018-12-20 13:42] [INFO] Configuration loaded from /home/paul/.config/alacritty/alacritty.yml
[2018-12-20 13:42] [INFO] device_pixel_ratio: 1
[2018-12-20 13:42] [INFO] width: 1024, height: 768
[2018-12-20 13:42] [INFO] Initializing glyph cache
[2018-12-20 13:42] [INFO] Finished initializing glyph cache in 0.01473262
[2018-12-20 13:42] [INFO] width: 1024, height: 768
[2018-12-20 13:42] [INFO] Cell Size: (9 x 17)
[2018-12-20 13:42] [INFO] Padding: (2 x 2)
[2018-12-20 13:42] [INFO] PTY Dimensions: Line(44) x Column(113)
[2018-12-20 13:42] [INFO] Initialisation complete
[2018-12-20 13:42] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2018-12-20 13:42] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(62914563))), event: Resized(LogicalSize { width: 1024.0, height: 768.0 }) }
[2018-12-20 13:42] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(62914563))), event: Moved(LogicalPosition { x: 0.0, y: 1.0 }) }
[2018-12-20 13:42] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(62914563))), event: Refresh }
[2018-12-20 13:42] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(62914563))), event: Focused(true) }
[2018-12-20 13:42] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(62914563))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: 3185.0, y: 1339.0 }, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
```

This log appears to indicate that alacritty first starts at the default 1024x768px, infers cols x rows, starts up and only then maximizes. I don't see the same glutin Resized event with the correct 3440x1396 px size I see when running the example, but the last line suggests this does happen in the end as it reports a cursor position with x > 3000.

**Comment by chrisduerr** [comment]
@paulie-g Just to clarify, you're saying that when removing the `set_maximized` call (just having the `with_maximized` left), it still works?

Then it's definitely something we should be able to fix.

**Comment by paulie-g** [comment]
@chrisduerr Indeed, that is exactly what I'm saying. I tried it with both, either and none, all with expected results - maximized, maximized, not maximized respectively.

**Comment by paulie-g** [comment]
Rebuilt alacritty with start_maximized set to true in config.rs.

```
 429 impl Default for WindowConfig {
 430     fn default() -> Self {
 431         WindowConfig{
 432             dimensions: Default::default(),
 433             padding: default_padding(),
 434             decorations: Default::default(),
 435             dynamic_padding: false,
 436             start_maximized: true,
 437         }
 438     }
 439 }
```

Same issue. The -d command line argument doesn't seem to be working either, as I tried to feed it -d 382 100 and nada, still same size and log shows it insisting on 113 x 44

**Comment by chrisduerr** [comment]
@paulie-g Just to make sure, please ensure that you're running the latest Alacritty version with `alacritty --version`.

**Comment by chrisduerr** [comment]
Just making sure. Also, setting the `start_maximized` to `true` in the `config.rs` will not do anything when you have a config file in place, since that overwrites the setting in the code. The code you've changed is only used when the `window` field is not present at all in the config.

**Comment by paulie-g** [comment]
I understand; I was trying to rule out a problem with the config code. I've narrowed this down further:

window.rs:
```
144 impl Window {
145     /// Create a new window
146     ///
147     /// This creates a window and fully initializes a window.
148     pub fn new(options: &Options, window_config: &WindowConfig) -> Result<Window> {
149         let event_loop = EventsLoop::new();
150 
151         let title = options.title.as_ref().map_or(DEFAULT_TITLE, |t| t);
152         let class = options.class.as_ref().map_or(DEFAULT_TITLE, |c| c);
153         let window_builder = Window::get_platform_window(title, window_config);
154         let window_builder = Window::platform_builder_ext(window_builder, &class);
155         let window = create_gl_window(window_builder.clone(), &event_loop, false)
156             .or_else(|_| create_gl_window(window_builder, &event_loop, true))?;
157         //window.set_maximized(true);
158         window.show();
159         window.set_maximized(true);
```

window.set_maximized(true) before window.show() does *not* work. window.set_maximized(true) after window.show() does. This indicates to me that either show() is doing something it ought not do *or* that glutin isn't mapping the window in when it creates it. The WM can't maximize a window if it's not under its management, which it won't be until it's mapped in. This is correct behaviour on the part of the WM.

**Comment by paulie-g** [comment]
https://tronche.com/gui/x/xlib/window/map.html if you're curious. It's been a while since I hacked on WMs, but the gist is that most WMs will only do something about a window once they get a MapNotify for it. Since maximizing is a WM function rather than an X function, you need the window to be under the WM's control for it to work.

**Comment by chrisduerr** [comment]
The `set_maximized` call explicitly exists for maximizing the window AFTER it has been started, that's why it doesn't work before `show` and that is fully intentional.

That's why Alacritty is using `with_maximized` instead.

**Comment by paulie-g** [comment]
Right, that makes sense.

**Comment by chrisduerr** [comment]
No worries, I'll look into it when I've got the time. Probably going to take a while though.

**Comment by sabrehagen** [comment]
Just wanted to weigh in and say I'm experiencing this too on KDE `5.12.7`. As a workaround I used [KWin](https://userbase.kde.org/KWin_Rules_Window_Matching/en) to set alacritty to always start maximised.

**Comment by evesprini** [comment]
> Latest KDE neon

> I have the same problem with start_maximized with openbox.

Same issue on Pantheon (ElementaryOS).

**Comment by evesprini** [comment]
Here's a hacky 'fix':

    window:
      dimensions:
        columns: 999
        lines: 999
      start_maximized: false

**Comment by igorepst** [comment]
Same on Gnome 3.30.2. 
```
[2019-03-20 08:59] [INFO] Welcome to Alacritty
[2019-03-20 08:59] [INFO] Configuration loaded from "/home/igor/.config/alacritty/alacritty.yml"
[2019-03-20 08:59] [INFO] Device pixel ratio: 1
[2019-03-20 08:59] [INFO] Width: 1024, Height: 768
[2019-03-20 08:59] [INFO] Initializing glyph cache...
[2019-03-20 08:59] [INFO] ... finished initializing glyph cache in 0.020548217s
[2019-03-20 08:59] [INFO] Width: 1024, Height: 768
[2019-03-20 08:59] [INFO] Cell Size: (9 x 17)
[2019-03-20 08:59] [INFO] Padding: (2 x 2)
[2019-03-20 08:59] [INFO] PTY Dimensions: Line(44) x Column(113)
[2019-03-20 08:59] [INFO] Initialisation complete
[2019-03-20 08:59] [INFO] Font size changed to Size(22) with DPR of 1
[2019-03-20 08:59] [INFO] Width: 1024, Height: 768
[2019-03-20 08:59] [INFO] Goodbye
```
However, monitor resolution is 1920x1080.
Columns: 0, lines: 0, start_maximized: true.
[Link to the config](https://github.com/igorepst/.dotfiles/blob/7c60cf5fc0c434cdec615193e347427a6183c8f3/config/alacritty/alacritty.yml)
