### ISSUE TITLE
Launch URLs only when left-clicking

### ISSUE THREAD

**Issue by UnixRonin** [jwilm/alacritty#1903]
alacritty-0.2.4:  Erroneous URL activation when middle-button-pasting URLs

OS:  Gentoo Linux 17.0 with x11-base/xorg-server-1.20.3 and x11-drivers/nvidia-drivers-415.18

Behavior:
Intermittently, when I paste a URL into alacritty using X11 middle-button paste, alacritty will open a previous URL in the terminal history (**usually**, but not always, either the most recent previous URL displayed in the terminal or the most recent previous URL I pasted).

**Comment by UnixRonin** [comment]
That's a good question.  Nothing is logged to .xsession-errors; I have not tried launching alacritty with -v.  I will see if I can find a way to modify the script that launches the sessions that use alacritty to use -v and redirect output to a log.

**Comment by UnixRonin** [comment]
(I've tried to reproduce it in an alacritty launched from an xterm, but so far haven't been able to, as it seems to occur randomly and is not consistently reproducible.)

**Comment by chrisduerr** [comment]
I'd expect this to be the recently added URL launching feature. It's currently still got a couple of issues and URLs aren't highlighted. So I'd try to disable that in the config and that should fix the problem, of course you won't be able to open URLs by clicking on them anymore either. But that's likely what's going on.

**Comment by UnixRonin** [comment]
Well, it only occasionally mislaunches, so I don't want to disable it.  But I figured I should report the issue.

**Comment by chrisduerr** [comment]
@UnixRonin I believe right now any mouse click will launch URLs, so that's probably what you're experiencing.

I'm gonna rename this issue to track what's going on.

**Comment by UnixRonin** [comment]
Aaaaaaah!  That would certainly explain the behavior (though not why I had such difficulty trying to deliberately reproduce it).

**Comment by nixpulvis** [comment]
Just jumping in here to suggest that middle mouse click be a copy of the URL, since that's somewhat consistent with Linux copy paste at least.

**Comment by chrisduerr** [comment]
Middle mouse click is used for pasting, not for copying.

**Comment by nixpulvis** [comment]
Oh boy, yea. Bad suggestion.
