### ISSUE TITLE
alacritty-0.2.4:  URLs can be incorrectly extended onto the next line

### ISSUE THREAD

**Issue by UnixRonin** [jwilm/alacritty#1906]
Which operating system does the issue occur on?    Probably any
If on linux, are you using X11 or Wayland?   X11, but I don't think that's relevant

There is a minor bug in the URL grabber.  I'm running irssi in an alacritty, and this is an excerpt of my session:

13:17  * Grimes examines the latest issue of Stars and Stripes
13:22 < ToCoTox> https://www.geologyin.com/2018/12/largest-known-diamond-in-north-america.html
13:22  * ShowTitle <Title> Largest Known Diamond in North America Found

It just so happens that the URL in the middle line ends **EXACTLY** in the last column of the terminal.  When I click the link to open it, alacritty does not realize that the URL ends there, and wraps around and grabs the timestamp from the next line and appends it to the URL, which then does not resolve because largest-known-diamond-in-north-america.html13:22 does not exist.

I'm not certain how alacritty can best detect this condition.  Clearly I can work around it **in this use case** by making my URL handler strip anything that looks like an Irssi timestamp off the end of the URL, but that's not going to work for everyone.

**Comment by chrisduerr** [comment]
It should be possible to check the last cell of the row for the line break flag and only wrap around if this is not present.

**Comment by chrisduerr** [comment]
This has been fixed in #2192. Please let me know if this does not solve the problem for you.

**Comment by UnixRonin** [comment]
I will keep a watch out for an opportunity to retest this as soon as 0.3.0 hits Gentoo.
