### ISSUE TITLE
Cannot copy path to log in event of error

### ISSUE THREAD

**Issue by JacksonKearl** [jwilm/alacritty#1907]
Which operating system does the issue occur on?
MacOS.

When I start, I get a message "Error! See log at [....]", but I cannot copy that path. It would be nice to be able to copy that path.

**Comment by chrisduerr** [comment]
Alacritty currently doesn't actually treat the error message as cell content, but it's just added before the rendering step. As a result of this, it would probably be tough to be able to copy/paste this text.

However, there might be alternative ways to achieve the same thing. I'd propose automatically copying the URL to the system clipboard maybe? That way it wouldn't require copying it anymore.

I'm open to alternative suggestions, but I don't know if it would be worth it to try and make it work with 'normal' copy/pasting.

**Comment by NickeZ** [comment]
> However, there might be alternative ways to achieve the same thing. I'd propose automatically copying the URL to the system clipboard maybe? That way it wouldn't require copying it anymore.

I suggest not doing this automatically, but maybe if a user click on the alert? Modifying the users clipboard without interaction from the user is a bit unfriendly I think.

**Comment by chrisduerr** [comment]
> maybe if a user click on the alert

The problem is that this error/warning is added just right before the rendering step. So it never gets into contact with any interface for selection/keyboards/mouse input. So clicking on it has similar difficulties to selecting it.

**Comment by chrisduerr** [comment]
Since there are more issues with this feature than simply copying the log path, I've opted to create a separate task for reworking this feature: https://github.com/jwilm/alacritty/issues/1996.

To keep duplication low (even though this issue came first), it seems best to move tracking there. Though I've made sure to explicitly mention this so it will not get lost in the process.
