### ISSUE TITLE
Windows + alacritty + vim has weird behavior with the <esc> key

### ISSUE THREAD

**Issue by ubsan** [jwilm/alacritty#1914]
Basically, whenever I try to exit out of insert-mode, I have to wait for the escape key to "catch", about a second - otherwise, I get a modified character and continue on inserting. For example, if I type <esc>j, I get `ê`.

**Comment by chrisduerr** [comment]
I wasn't able to notice something like that when running Alacritty on Windows myself. Repro might be interesting if anyone else also has the issue.

Would be interesting to see if the ESC alternatives (I believe it was Ctrl+]) create the same problem?

**Comment by zacps** [comment]
Duplicate of https://github.com/jwilm/alacritty/issues/1680

**Comment by ubsan** [comment]
Ah, sorry @zacps, I missed it
