### ISSUE TITLE
Middle-click to paste shouldn't trigger a click (e.g. to select)

### ISSUE THREAD

**Issue by victorhsieh** [jwilm/alacritty#1915]
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
X11

I'm on 0c3e28617a95b4ca30ad9bdbb9114f1e4d41dce5.  Here is what I expect (like previous version, and also other terminals):

1. Double click to select.  Word is highlighted correctly.
2. Immediately middle click to paste.

Expect: highlight is gone after paste
Actual: highlight the whole line, as if I triple-clicked.

**Comment by chrisduerr** [comment]
Note that right-clicking also allows starting the semantic selection. The correct behavior here should be to allow selection only when using the LMB.
