### ISSUE TITLE
Use HPCON definition from winapi

### ISSUE THREAD

**Issue by davidhewitt** [jwilm/alacritty#1920]
In `src/tty/conpty.rs`, near the top we have the definition `pub type HPCON = *mut c_void;`

Once https://github.com/retep998/winapi-rs/pull/699 is released then we can update to a newer winapi and `use winapi::um::wincontypes::HPCON;`

(I added this definition there so that we could merge the support for `ConPty` apis without having to depend on a patched `winapi`.)

**Comment by chrisduerr** [comment]
The upstream PR has been merged.

**Comment by atouchet** [comment]
winapi 3.7 is now out.
