### ISSUE TITLE
Make all options optional with fallback to defaults

### ISSUE THREAD

**Issue by Jomik** [jwilm/alacritty#1923]
I am making a module for configuring alacritty using Nix.
It is pretty tedious to make an option for each and every configuration option available in alacritty, especially the ones that most users may never touch.
Would it be possible to make all options optional, such that they fallback to the default values provided in https://github.com/jwilm/alacritty/blob/master/alacritty.yml ?
This makes it possible for the user to make a minimal configuration, thus it is easy to see what you have actually changed, and what is still default.
This is the module I am speaking of: https://github.com/rycee/home-manager/pull/500

**Comment by chrisduerr** [comment]
This is also slightly related to https://github.com/jwilm/alacritty/issues/40, since it will be necessary to make all differences between the platforms fallback to platform-specific defaults which need to be hardcoded into the application.

**Comment by chrisduerr** [comment]
Also I'm open for incremental improvements here. Something like the semantic escape characters could be fixed with proper defaults without much trouble at all, while others like the key bindings are a lot more work.
