### ISSUE TITLE
Arrow keys (and friends) send text

### ISSUE THREAD

**Issue by Jomik** [jwilm/alacritty#1924]
Linux, NixOS release 18.09 X11.
Alacritty version 0.2.4
Fish shell version 2.7.1

Whenever I press the arrow keys, I get something that looks like a unicode escape sequence printed in my terminal input, rather than the expected behavior of it moving the cursor.

[My alacritty.yml is here](https://git.io/fhT0V)

Output I get is the string in the chars field in my config for the `~AppCursor` mode.

"All" configuration options are being applied - window is being sized according to columns and lines I set and the background color has changed.

EDIT: Updated with more info.

**Comment by chrisduerr** [comment]
That configuration is not a valid yml file. It should print errors when trying to start Alacritty too.

**Comment by Jomik** [comment]
@chrisduerr Why is this not a valid yaml file? There is no errors printed.
YAML is a superset of JSON, thus all JSON is valid YAML :+1:

**Comment by Jomik** [comment]
Perhaps I need to adapt my alacritty.yml to match the characters [here/in fish](https://github.com/faho/fish-shell/blob/master/share/functions/fish_default_key_bindings.fish)

**Comment by chrisduerr** [comment]
Try starting Alacritty with `alacritty -v` to show which configuration file is printed. The configuration file you've posted here is certainly not valid, not because of the JSON layout, but because there's an invalid value in there.

**Comment by Jomik** [comment]
Output of `alacritty -v` is as seen below.
It targets the `alacritty.yml` that I linked in the gist.
Which value are you thinking of?
```
Created log file at "/tmp/Alacritty-2547.log"
[2018-12-26 13:19] [INFO] Welcome to Alacritty.
[2018-12-26 13:19] [INFO] Configuration loaded from /home/jomik/.config/alacritty/alacritty.yml
[2018-12-26 13:19] [INFO] device_pixel_ratio: 1.75
[2018-12-26 13:19] [INFO] width: 1792, height: 1344
[2018-12-26 13:19] [INFO] Initializing glyph cache
[2018-12-26 13:19] [INFO] Finished initializing glyph cache in 0.02739233
[2018-12-26 13:19] [INFO] width: 966, height: 582
[2018-12-26 13:19] [INFO] Cell Size: (8 x 16)
[2018-12-26 13:19] [INFO] Padding: (3 x 3)
[2018-12-26 13:19] [INFO] PTY Dimensions: Line(36) x Column(120)
[2018-12-26 13:19] [INFO] Initialisation complete
[2018-12-26 13:19] [INFO] Font size changed: Size(12) [DPR: 1.75]
[2018-12-26 13:19] [INFO] width: 966, height: 1017
```

**Comment by dm1try** [comment]
the config above works for me, though the line 180 really has broken char(`DEL` between the quotes) so if someone will copy-and-paste the config it might be a problem
<img width="314" alt="screen shot 2018-12-26 at 16 55 41" src="https://user-images.githubusercontent.com/486807/50447863-190e6f00-092f-11e9-90b2-5329ec7cc7a2.png">

at least, Neovim was unable to parse this(it actually deletes the symbol).

**Comment by Jomik** [comment]
Ah, I see that broken char. But that doesn't really explain why it doesn't correctly controls my shell, except for that one case.
I am thinking that perhaps fish is using different characters?

**Comment by dm1try** [comment]
yeah sorry, it was not related to the original problem, it was just the assumption about that broken in the config :)

btw, I was unable to reproduce the problem using the config above on `osx/alacritty/zsh`.

**Comment by chrisduerr** [comment]
Oh yeah, the unescaped character was probably interpreted by my shell making the configuration file invalid.

@Jomik have you tried running the default config? If the issue isn't present there, it's likely a fault with your config. Testing out different shells might also work.

**Comment by dm1try** [comment]
I was able to reproduce it with `fish` shell though it still looks like a configuration issue: some keys are use two backslashes for escaping and (this does not follow JSON/YAML spec at least) and some miss the backslash for escaping at all(see the comment above). I've fixed a couple and tried, it works fine for me.

**Comment by Jomik** [comment]
@dm1try IIUC, backslash should be escaped with a backslash, thus it becomes `\\`. This will result in alacritty getting the string `\u...`. Is this not expected?
I guess a reason could be that my converter has replaced the escape sequences from the default config with a \u equivalence..

**Comment by Jomik** [comment]
I will try implementing all the config options in nix, such that I don't have to use the hacky solution of merging it into the default alacritty config as JSON :yum:

**Comment by dm1try** [comment]
> backslash should be escaped with a backslash, thus it becomes \\. This will result in alacritty getting the string \u.... Is this not expected?

I don't think so, see the default YAML config. Alacritty needs not an escaped string with the representation of escaped control character but the escaped control character itself. All JSON strings are Unicode, to deliver an escaped character using Unicode string you should to escape the character(ex. backspace  => `\u007f`). Does it sound reasonable?

**Comment by Jomik** [comment]
Yeah, makes perfect sense now that I look at it. I suppose the issue is that nix (or the toJSON function) doesn't actually handle those escape sequences :-1:

**Comment by dm1try** [comment]
it looks like the original issue is resolved

**Comment by Jomik** [comment]
Apologies, yes, this is solved :)
