### ISSUE TITLE
URL detection is too liberal

### ISSUE THREAD

**Issue by mqudsi** [jwilm/alacritty#1937]
While #1727 would help with alacritty incorrectly picking up URLs where there are none, in all cases the URL detection is too liberal. In `::` namespaced code (e.g. rust), the following line is considered to contain a URL, beginning at `iMessage::`

```rust
    ┆   let attachment = imessage::get_attachment(&self.db, request.guid)?; 
```

I believe URLs should, at minimum, be required to match `\b(?<scheme>[a-zA-Z]+:\/\/`. 

(Special leniency may be given for matching local `file:///` paths if that is desired (e.g. additionally matching `C:\foo.txt` or `/var/db/foo`) as special "local URIs", probably gated behind an option given their prevalence in terminal output.)

Unfortunately, this is probably dependent on the definition of "URI" as some RFCs (for example, RFC2806) decided to go with `scheme:address` as a URI, but I think valid cases for handling that (esp. since alacritty does not offer a per-scheme handler for URIs but rather just one catch-all handler to configure) are few and far in-between.

**Comment by chrisduerr** [comment]
This has already been discussed in #1727. The plan is to rework the way URL detection works right now significantly and there's already a WIP PR here: #1764.
