### ISSUE TITLE
Keys eaten when alt is held

### ISSUE THREAD

**Issue by parkovski** [jwilm/alacritty#1939]
Windows issue.

Run `wsl xxd` under alacritty and conhost and type while holding alt. In conhost, I see each key prefixed by an escape; in alacritty nothing appears. It seems when alt is down, most keypresses are eaten. The only time Alt works is with the function keys, although the generated number is wrong (6, should be 3).

I've noticed a couple of other key map related issues - `Ctrl-Shift, Alt-Shift, Ctrl-Alt-Shift` are eaten for many keys as well (noticed F-keys, Home/End/PgDown/PgUp/Backspace/Delete). `C-/` should generate a `^_`, and `C-Space` should generate `^@`.

**Comment by mqudsi** [comment]
Was coming here to report this. In my case, this is with `conpty` mode.

**Comment by zacps** [comment]
@parkovski Did you find this using conpty or winpty (it's winpty if you're not sure)?.

**Comment by parkovski** [comment]
Conpty, although I don't see them in winpty either. Can't use alt bindings in either WSL or PowerShell, and tested as many shell configurations as I could.

Interestingly, I can add individual bindings in `alacritty.yml`, but only some keys work with shift. E.g. I can create a binding for "Alt-j", but not "Alt-J", but "Alt-X" works fine 😕.

Here is a config snippet that adds the 2 missing bindings I found and enables a couple alt keys to test - the capitals don't work for me - `M-H` prints `^[h` (lowercase) and the others just cause the cursor to flicker.

```yaml
- { key: Space,    mods: Control, chars: "\x00"                        }
- { key: Slash,    mods: Control, chars: "\x1f"                        } 
- { key: H,        mods: Alt,     chars: "\x1bh"                       }
- { key: H,        mods: Shift|Alt, chars: "\x1bH"                     }
- { key: J,        mods: Alt,     chars: "\x1bj"                       }
- { key: J,        mods: Shift|Alt, chars: "\x1bJ"                     }
- { key: K,        mods: Alt,     chars: "\x1bk"                       }
- { key: K,        mods: Shift|Alt, chars: "\x1bK"                     }
- { key: L,        mods: Alt,     chars: "\x1bl"                       }
- { key: L,        mods: Shift|Alt, chars: "\x1bL"                     }
```

Conpty work is awesome btw :heart:

**Comment by luisdavim** [comment]
I'm not sure if this is related but I have a vim key binding `ctrl+/` to toggle comments, it works fine in every terminal emulated I've used except Alacritty.

**Comment by parkovski** [comment]
@luisdavim This issue only affects key combos with alt, not control. However, you might try binding `<C-S-_>` and/or `<Char-0x1f>`. If those don't work, maybe you could open a separate issue with details on your setup (vim/neovim, conpty/winpty, your alacritty.yml), because there are unfortunately many places that specific keybinding could go wrong.

**Comment by chrisduerr** [comment]
@CypherZealot could you provide the output of `alacritty --print-events | grep "ReceivedCharacter"` after pressing a couple of `alt` keys?

We'll probably have to report this upstream, but I just want to verify first that normal keys result in a `ReceivedCharacter` event, but when holding `alt` there is none.

**Comment by CypherZealot** [comment]
> @CypherZealot could you provide the output of `alacritty --print-events | grep "ReceivedCharacter"` after pressing a couple of `alt` keys?
> 
> We'll probably have to report this upstream, but I just want to verify first that normal keys result in a `ReceivedCharacter` event, but when holding `alt` there is none.
If `alt` is a member of any key-chord nothing prints that matches the pattern `ReceivedCharacter`. Other key-chords do print. 

@chrisduerr, here is an example of the following sequence:
1. `b`
2. `ctrl+b`
3. `alt+b`
4. `alt+ctrl+b`
5. `ctrl+d`

```shell
alacritty.exe --print-events 2>&1 | grep "ReceivedCharacter"
[2019-11-16 18:35] [INFO] glutin event: WindowEvent { window_id: WindowId(WindowId(0xb01de)), event: ReceivedCharacter('b') }
[2019-11-16 18:35] [INFO] glutin event: WindowEvent { window_id: WindowId(WindowId(0xb01de)), event: ReceivedCharacter('\u{2}') }
[2019-11-16 18:35] [INFO] glutin event: WindowEvent { window_id: WindowId(WindowId(0xb01de)), event: ReceivedCharacter('\u{4}') }
```

Note the two missing events between `\u{2}` and `\u{4}`.

Nothing prints matching that pattern if the `Alt` key is held. 

---

If I define a keybinding:
```yaml
key_bindings:
  - { key: B, mods: Alt, chars: "\x1bb"  }
  - { key: B, mods: Alt|Control, chars: "\x1b\x02" }
```
And repeat the same sequence above, I can see `^[b` and `^[^B` prints in `showkey -a` but I get the same result from the `RecievedCharacter` pattern match as before, nothing prints when `Alt` is held.

**Comment by chrisduerr** [comment]
I've reported this upstream in https://github.com/rust-windowing/winit/issues/1280.

**Comment by chrisduerr** [comment]
Fixed in https://github.com/jwilm/alacritty/pull/3055.
