### ISSUE TITLE
Current line disappears on window resize

### ISSUE THREAD

**Issue by SirAiedail** [jwilm/alacritty#194]
When resizing the terminal window, the prompt and anything I already typed after it disappears. Anything above that line is not affected.
Once I start typing it reappears.

This does not happen in `vim`.

The third line in the following screenshot is supposed to show the prompt

![Screenshot](http://i.imgur.com/PQlACf3.png)

**Comment by casey** [comment]
Here's a video of it happening in macOS: https://youtu.be/4MTutlRWTqE

For some reason the screen gets dark when I launch alacritty, but this only occurs when making a recording.

**Comment by jwilm** [comment]
Has this been resolved?

**Comment by SirAiedail** [comment]
Yes. Doesn't happen anymore on the newest version.

**Comment by jwilm** [comment]
Thanks!
