### ISSUE TITLE
How often is the nightly updated?

### ISSUE THREAD

**Issue by steveklabnik** [jwilm/alacritty#196]
alacritty compiles with the latest nightly, and in fact, because it has procedrual macros in let, lets you remove that flag. How often do you plan to update the pinned version, roughly?

**Comment by jwilm** [comment]
I've just been updating it whenever there's a fix or something that necessitates it. With the recent changes, we can probably drop the pinning and just say "a recent nightly".

**Comment by steveklabnik** [comment]
Great! i'm going to close this, given that this will just become stable as of 1.15, so the question is a bit moot 😄
