### ISSUE TITLE
Cannot mouse binding (Right) to use copy action

### ISSUE THREAD

**Issue by LinkTed** [jwilm/alacritty#1963]
Hi,
i cannot use the action `copy` with the mouse binding `right`. Here a snippet of my config file:
```
mouse_bindings:
   - { mouse: Right,  action: Copy }
```

Which operating system does the issue occur on?
Linux 4.20.0-arch1-1-ARCH (Arch Linux)

If on linux, are you using X11 or Wayland?
X11 (i3) and Wayland (sway)

The version is: 0.2.4

Thank you for your attention

**Comment by chrisduerr** [comment]
This is likely because the selection gets removed when right-clicking. So the selection is first removed and then copied, which leads to an empty selection.

**Comment by chrisduerr** [comment]
@nixpulvis I don't see how that would break anything, assuming that it does indeed solve the problem. Mouse bindings getting triggered should have no side effects.

**Comment by chrisduerr** [comment]
This has been fixed in #1965.
