### ISSUE TITLE
no icon on Arch Linux and X11

### ISSUE THREAD

**Issue by Maxgy** [jwilm/alacritty#1966]
**Which operating system does the issue occur on?**
Arch Linux
**If on linux, are you using X11 or Wayland?**
X11

There is no icon real icon on the xfce4 window when I open alacritty.  The icon is simply a white rectangle with a blue top.

**Comment by chrisduerr** [comment]
This is a duplicate of https://github.com/jwilm/alacritty/issues/1591.
