### ISSUE TITLE
Alacritty not using config file v0.2.4

### ISSUE THREAD

**Issue by BenStigsen** [jwilm/alacritty#1978]
OS: Windows 10 Pro 10.0.17134 Build 17134

**Alacritty.exe**, **alacritty.yml** and **winpty-agent.exe** are all placed in `%APPDATA%\alacritty\`

When I change values in the **alacritty.yml** file, nothing changes. I've tried changing the cursor, color and if the window should start maximized, Alacritty opens the same way it usually does. I've tried having the configuration file named **alacritty.yml** and **alacritty_windows.yml**

![image](https://user-images.githubusercontent.com/24865450/50732874-4656ea80-1183-11e9-8bc5-be512e3613cf.png)

**Comment by chrisduerr** [comment]
@BenStigsen You can run `alacritty -v` to see where the config file is loaded from. Note that the config is only loaded from the `%APPDATA%` directory on the master branch, this has been a recent change and is not part of any release yet.

Running `alacritty -v` will tell you where the current location is.
