### ISSUE TITLE
Best way to get tabs on Windows?

### ISSUE THREAD

**Issue by mikemaccana** [jwilm/alacritty#1981]
Similar to https://github.com/jwilm/alacritty/issues/366 - what's the best way to get tabs on Windows? On nix it's tmux (even then a lot of people prefer using graphical tabs rather than text ones), but on Windows tmux isn't an option. I'm currently using Terminus, which has tabs out of the box. What's the best way to open a new tab on Alacritty/Windows?

**Comment by chrisduerr** [comment]
There is no intention for Alacritty to implement its own tabs, however with the Windows 'Sets' feature which is currently in available for testing in Windows 10, it should be able to have multiple tabs of Alacritty in the same window.

**Comment by mikemaccana** [comment]
Sets got cancelled, and removed from current Windows builds.

**Comment by mikemaccana** [comment]
https://www.theregister.co.uk/2018/06/28/sets_scrapped_from_windows_10/

**Comment by mikemaccana** [comment]
Maybe Groupy might be a good alternative...I;m going to investigate...

**Comment by chrisduerr** [comment]
Oh, I was not aware that sets got canceled. There might be other alternatives to provide the same feature, but even without sets it's not planned to manually implement this in Alacritty just for Windows.

**Comment by mikemaccana** [comment]
I still think adding tabs would be useful for all OSs, but I do understand your view that this is a job better suited to the window manager or an app running inside the terminal. 

Looks like Groupy does this:

![image](https://user-images.githubusercontent.com/172594/50767350-5a2e4980-1274-11e9-90aa-17dad8ed5919.png)

**Comment by liufuyang** [comment]
Thank you very much, I was wondering the same. Perhaps the doc can suggest a good windows manager for Windows. Alacrity seems working out of the box in Mac with "tabs" but not in Windows.

**Comment by chrnz008** [comment]
its seems to be groupy is the only alternative. there is no windowmanager or multiplexer for windows that does this. are there any other alternatives
