### ISSUE TITLE
Crash on macOS with SpawnNewInstance action

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#1988]
This has been introduced by https://github.com/jwilm/alacritty/pull/1971.

It has already been accepted in #1979 that implementing this feature on Windows takes significantly more effort than on Linux, so it's not fully supported initially.

For macOS this feature has been enabled, but it currently leads to a crash whenever it is used. It should be investigated if this can be easily fixed to achieve feature parity with Linux, otherwise it should be disabled on macOS, similar to the current Windows implementation.

**Comment by nixpulvis** [comment]
Reposting my comment from the PR threads here:

This blog post might help the situation on macOS, https://astojanov.wordpress.com/2011/11/16/mac-os-x-resolve-absolute-path-using-process-pid/. See [this](https://stackoverflow.com/questions/8327139/working-directory-of-running-process-on-mac-os) SO post for more.

Though I'm starting to think it would be easier to have the PTY just tell us the output of [`current_dir`](https://doc.rust-lang.org/stable/std/env/fn.current_dir.html) directly.

**Comment by Camotubi** [comment]
There is a wrapper for the libproc 
https://github.com/andrewdavidmackenzie/libproc-rs
There is a function called pidpath that may solve the issue.

@nixpulvis current_dir wont work. That will return the path where alacritty was spawned. We need the shell cwd.

**Comment by chrisduerr** [comment]
I've also just looked into `libproc-rs` and it seems to be that [`pidpath`](https://docs.rs/libproc/0.3.2/libproc/libproc/proc_pid/fn.pidpath.html) should indeed make this quite simple.

Considering that, it's probably worth just fixing this issue so it will work properly on macOS rather than disabling it temporarily.

Note that this would not solve the problem on BSD though, which is likely to have similar problems.

**Comment by chrisduerr** [comment]
I've talked to some BSD users and apparently this will likely crash on BSD too.

However the `libproc-rs` library is macOS specific. It seems like the `procstat` utility is able to get working directory information about processes owned by the current user, so there likely is a way to solve this on BSD too.

**Comment by Camotubi** [comment]
I have read [here](https://stackoverflow.com/questions/27145686/how-to-get-the-current-working-directory-of-a-process-in-freebsd-in-c) that in BSD you could use lsof to get the cwd.
With this I could resolve the shell cwd :
```bash
lsof -p $$ | sed '2q;d'| awk '{print $NF}'
# Note: $$ is the PID of the shell.
```

I'm currently installing a freeBSD VM to test if it works.

[libprocstat](https://www.freebsd.org/cgi/man.cgi?query=libprocstat&apropos=0&sektion=3&manpath=FreeBSD+9-current&format=html) is also mentioned, but I'm not sure how to call C libraries from rust.
