### ISSUE TITLE
Add a command to scroll the scrollback buffer so we can bind it to keys

### ISSUE THREAD

**Issue by coredump** [jwilm/alacritty#1989]
As discussed on IRC:

It would be nice to have a way to bind a 'scroll up' action to keys, so we can simulate the behaviour on other terminals. For example, on termite I can use shift+pgup to see the scrollback, and pgup/down do whatever my shell does (scroll through history). inside vim shift+pgup/down scrolls by page, but I suspect I have something on my to do that, and on tmux it doesn nothing.  

Thanks!

**Comment by ti-mo** [comment]
Unless you mean something else, I've had this since scrollback was merged:

```
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp                 }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown               }
```

This is documented in the comment above `key_bindings`. (https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L369)

Might be a good candidate to add to the default config, though.

**Comment by nixpulvis** [comment]
Might be worth a quick survey of what other terminals use for defaults with respect to the scrollback buffer. I can test some Linux terminals easily. I'd be curious about macOS and Windows (what other windows terminals are out there worth comparing?).

**Comment by nixpulvis** [comment]
Cool, yea. This is a keybinding I've never used before (been using Alacritty too long :wink:).

**Comment by chrisduerr** [comment]
Fixed in https://github.com/jwilm/alacritty/pull/2089.

**Comment by sourjyo0** [comment]
I get scrolling along with 2~2~2~

**Comment by kchibisov** [comment]
make sure you don't have multiple bindings to scroll and to send chars. The default scrolling bindings `Shift + PageUp/Down` with default config shouldn't send anything. To launch alacritty with default config use `alacritty --config-file /dev/null`.

**Comment by sci4me** [comment]
I also get the `2~2~2~` thing when using the default config.

**Comment by jcguu95** [comment]
> Unless you mean something else, I've had this since scrollback was merged:
> 
> ```
>   - { key: PageUp,   mods: Shift,   action: ScrollPageUp                 }
>   - { key: PageDown, mods: Shift,   action: ScrollPageDown               }
> ```
> 
> This is documented in the comment above `key_bindings`. (https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L369)
> 
> Might be a good candidate to add to the default config, though.

A similar change doesn't work for me.. 

```
  - { key: PageUp,                    action: ScrollPageUp                 }
  - { key: PageDown,                  action: ScrollPageDown               }
```
