### ISSUE TITLE
build is failing 

### ISSUE THREAD

**Issue by SolarAquarion** [jwilm/alacritty#20]
Compiling alacritty v0.1.0 (file:///home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git)
error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Cursor` has already been defined in this module
  --> src/index.rs:24:59
   |
24 | #[derive(Debug, Clone, Default, Eq, PartialEq, Serialize, Deserialize)]
   |                                                ---------  ^^^^^^^^^^^ already defined
   |                                                |
   |                                                previous definition of `_IMPL_DESERIALIZE_FOR_Cursor` here

error[E0428]: a type named `Cursor` has already been defined in this module
  --> src/index.rs:25:1
   |
24 | #[derive(Debug, Clone, Default, Eq, PartialEq, Serialize, Deserialize)]
   |                                                           ----------- previous definition of `Cursor` here
25 | pub struct Cursor {
   | ^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Line` has already been defined in this module
  --> src/index.rs:33:82
   |
33 | #[derive(Debug, Copy, Clone, Eq, PartialEq, Default, Ord, PartialOrd, Serialize, Deserialize)]
   |                                                                       ---------  ^^^^^^^^^^^ already defined
   |                                                                       |
   |                                                                       previous definition of `_IMPL_DESERIALIZE_FOR_Line` here

error[E0428]: a type named `Line` has already been defined in this module
  --> src/index.rs:34:1
   |
33 | #[derive(Debug, Copy, Clone, Eq, PartialEq, Default, Ord, PartialOrd, Serialize, Deserialize)]
   |                                                                                  ----------- previous definition of `Line` here
34 | pub struct Line(pub usize);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Column` has already been defined in this module
  --> src/index.rs:45:82
   |
45 | #[derive(Debug, Copy, Clone, Eq, PartialEq, Default, Ord, PartialOrd, Serialize, Deserialize)]
   |                                                                       ---------  ^^^^^^^^^^^ already defined
   |                                                                       |
   |                                                                       previous definition of `_IMPL_DESERIALIZE_FOR_Column` here

error[E0428]: a type named `Column` has already been defined in this module
  --> src/index.rs:46:1
   |
45 | #[derive(Debug, Copy, Clone, Eq, PartialEq, Default, Ord, PartialOrd, Serialize, Deserialize)]
   |                                                                                  ----------- previous definition of `Column` here
46 | pub struct Column(pub usize);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Flags` has already been defined in this module
  --> src/term.rs:82:29
   |
82 |         #[derive(Serialize, Deserialize)]
   |                  ---------  ^^^^^^^^^^^ already defined
   |                  |
   |                  previous definition of `_IMPL_DESERIALIZE_FOR_Flags` here

error[E0428]: a type named `Flags` has already been defined in this module
  --> src/term.rs:81:5
   |
81 |     bitflags! {
   |     ^ already defined
82 |         #[derive(Serialize, Deserialize)]
   |                             ----------- previous definition of `Flags` here
   |
   = note: this error originates in a macro outside of the current crate

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Color` has already been defined in this module
  --> src/term.rs:91:54
   |
91 |     #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
   |                                           ---------  ^^^^^^^^^^^ already defined
   |                                           |
   |                                           previous definition of `_IMPL_DESERIALIZE_FOR_Color` here

error[E0428]: a type named `Color` has already been defined in this module
  --> src/term.rs:92:5
   |
91 |     #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
   |                                                      ----------- previous definition of `Color` here
92 |     pub enum Color {
   |     ^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Cell` has already been defined in this module
  --> src/term.rs:97:39
   |
97 |     #[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
   |                            ---------  ^^^^^^^^^^^ already defined
   |                            |
   |                            previous definition of `_IMPL_DESERIALIZE_FOR_Cell` here

error[E0428]: a type named `Cell` has already been defined in this module
   --> src/term.rs:98:5
    |
97  |     #[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
    |                                       ----------- previous definition of `Cell` here
98  |     pub struct Cell {
    |     ^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_SizeInfo` has already been defined in this module
   --> src/term.rs:222:41
    |
222 | #[derive(Debug, Copy, Clone, Serialize, Deserialize)]
    |                              ---------  ^^^^^^^^^^^ already defined
    |                              |
    |                              previous definition of `_IMPL_DESERIALIZE_FOR_SizeInfo` here

error[E0428]: a type named `SizeInfo` has already been defined in this module
   --> src/term.rs:223:1
    |
222 | #[derive(Debug, Copy, Clone, Serialize, Deserialize)]
    |                                         ----------- previous definition of `SizeInfo` here
223 | pub struct SizeInfo {
    | ^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Color` has already been defined in this module
   --> src/ansi.rs:306:73
    |
306 | #[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
    |                                                              ---------  ^^^^^^^^^^^ already defined
    |                                                              |
    |                                                              previous definition of `_IMPL_DESERIALIZE_FOR_Color` here

error[E0428]: a type named `Color` has already been defined in this module
   --> src/ansi.rs:307:1
    |
306 | #[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
    |                                                                         ----------- previous definition of `Color` here
307 | pub enum Color {
    | ^ already defined

error[E0428]: a type named `Config` has already been defined in this module
  --> src/config.rs:29:1
   |
28 | #[derive(Debug, Deserialize)]
   |                 ----------- previous definition of `Config` here
29 | pub struct Config {
   | ^ already defined

error[E0428]: a type named `Colors` has already been defined in this module
   --> src/config.rs:455:1
    |
454 | #[derive(Debug, Deserialize)]
    |                 ----------- previous definition of `Colors` here
455 | pub struct Colors {
    | ^ already defined

error[E0428]: a type named `PrimaryColors` has already been defined in this module
   --> src/config.rs:462:1
    |
461 | #[derive(Debug, Deserialize)]
    |                 ----------- previous definition of `PrimaryColors` here
462 | pub struct PrimaryColors {
    | ^ already defined

error[E0428]: a type named `AnsiColors` has already been defined in this module
   --> src/config.rs:502:1
    |
501 | #[derive(Debug, Deserialize)]
    |                 ----------- previous definition of `AnsiColors` here
502 | pub struct AnsiColors {
    | ^ already defined

error[E0428]: a type named `Dpi` has already been defined in this module
   --> src/config.rs:756:1
    |
755 | #[derive(Debug, Deserialize)]
    |                 ----------- previous definition of `Dpi` here
756 | pub struct Dpi {
    | ^ already defined

error[E0428]: a type named `FontOffset` has already been defined in this module
   --> src/config.rs:789:1
    |
788 | #[derive(Debug, Deserialize)]
    |                 ----------- previous definition of `FontOffset` here
789 | pub struct FontOffset {
    | ^ already defined

error[E0428]: a type named `Font` has already been defined in this module
   --> src/config.rs:850:1
    |
849 | #[derive(Debug, Deserialize)]
    |                 ----------- previous definition of `Font` here
850 | pub struct Font {
    | ^ already defined

error[E0428]: a type named `Key` has already been defined in this module
    --> src/config.rs:1021:1
     |
1020 | #[derive(Deserialize, Copy, Clone)]
     |          ----------- previous definition of `Key` here
1021 | enum Key {
     | ^ already defined

error[E0428]: a value named `_IMPL_SERIALIZE_FOR_Grid` has already been defined in this module
  --> src/grid.rs:32:37
   |
32 | #[derive(Clone, Debug, Deserialize, Serialize, Eq, PartialEq)]
   |                        -----------  ^^^^^^^^^ already defined
   |                        |
   |                        previous definition of `_IMPL_SERIALIZE_FOR_Grid` here

error[E0428]: a type named `Grid` has already been defined in this module
  --> src/grid.rs:33:1
   |
32 | #[derive(Clone, Debug, Deserialize, Serialize, Eq, PartialEq)]
   |                                     --------- previous definition of `Grid` here
33 | pub struct Grid<T> {
   | ^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Row` has already been defined in this module
   --> src/grid.rs:224:35
    |
224 | #[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
    |                        ---------  ^^^^^^^^^^^ already defined
    |                        |
    |                        previous definition of `_IMPL_DESERIALIZE_FOR_Row` here

error[E0428]: a type named `Row` has already been defined in this module
   --> src/grid.rs:225:1
    |
224 | #[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
    |                                   ----------- previous definition of `Row` here
225 | pub struct Row<T>(Vec<T>);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^ already defined

error[E0428]: a value named `_IMPL_DESERIALIZE_FOR_Rgb` has already been defined in this module
  --> src/lib.rs:70:65
   |
70 | #[derive(Debug, Eq, PartialEq, Copy, Clone, Default, Serialize, Deserialize)]
   |                                                      ---------  ^^^^^^^^^^^ already defined
   |                                                      |
   |                                                      previous definition of `_IMPL_DESERIALIZE_FOR_Rgb` here

error[E0428]: a type named `Rgb` has already been defined in this module
  --> src/lib.rs:71:1
   |
70 | #[derive(Debug, Eq, PartialEq, Copy, Clone, Default, Serialize, Deserialize)]
   |                                                                 ----------- previous definition of `Rgb` here
71 | pub struct Rgb {
   | ^ already defined

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/config.rs:31:5
   |
31 |     #[serde(default)]
   |     ^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/config.rs:35:5
   |
35 |     #[serde(default)]
   |     ^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/config.rs:39:5
   |
39 |     #[serde(default)]
   |     ^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/config.rs:43:5
   |
43 |     #[serde(default="true_bool")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/config.rs:47:5
   |
47 |     #[serde(default)]
   |     ^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/config.rs:51:5
   |
51 |     #[serde(default)]
   |     ^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/config.rs:55:5
   |
55 |     #[serde(default)]
   |     ^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:463:5
    |
463 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:465:5
    |
465 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:503:5
    |
503 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:505:5
    |
505 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:507:5
    |
507 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:509:5
    |
509 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:511:5
    |
511 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:513:5
    |
513 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:515:5
    |
515 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:517:5
    |
517 |     #[serde(deserialize_with = "rgb_from_hex")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
   --> src/config.rs:864:5
    |
864 |     #[serde(deserialize_with="DeserializeFromF32::deserialize_from_f32")]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: aborting due to 18 previous errors

error: Could not compile `alacritty`.

**Comment by jwilm** [comment]
Hey there,

Alacritty is pinned to a specific nightly compiler. Try running `rustup override set $(cat rustc-version)` from the alacritty project root.

**Comment by jwilm** [comment]
By the way, I'm a bit curious how you came across the project. I've been trying to keep it quiet until an alpha release (which is coming soon!). Do you mind sharing?

**Comment by SolarAquarion** [comment]
the aur

**Comment by jwilm** [comment]
oh, wow. I'll make this work on latest nightly since it appears that's what the AUR package wants. Will have to wait until this evening, though. Thanks for the info 😄

**Comment by jwilm** [comment]
Should now build on latest nightly
