### ISSUE TITLE
Memory leak with awesomeWM when window shape is enabled

### ISSUE THREAD

**Issue by Holi0317** [jwilm/alacritty#2004]
Which operating system does the issue occur on?

Arch Linux with AwesomeWM 4.2

If on linux, are you using X11 or Wayland?

X11

Alacritty version

0.2.5. But latest git (`4caf3d3`) was also affected

---

[Minimal awesome configuration](https://gist.github.com/Holi0317/5ad8e8ad02e3d6b79b1f0f6cecdd7220)

I was experiencing memory leak issue under awesomeWM when alacritty is launched, even if alacritty is not rendered on the screen.

When the screen is switched off by `xset dpms force off`, the memory usage of awesome starts to rise. With the minimal configuration, awesome starts to rise in memory usage.

This issue is resolved when window shape decoration code is commented out (line 561 to line 567 in the config).

I've tried other terminal emulators, namely `qterminal` and there is no such issue.

With my [actual awesome configuration](https://gitlab.com/holi0317/awesome-config/tree/leak), the memory usage increase rapidly and lua GC could not keep up. Eventually awesome is killed by Linux OOM killer.

**Comment by chrisduerr** [comment]
Can you reproduce this issue by adding the shape decoration code to an example of https://github.com/tomaka/winit? I strongly suspect that the issue does not lie with Alacritty, but rather with winit.

**Comment by Holi0317** [comment]
Confirmed this is an issue on winit end.

tomaka/winit#761

**Comment by chrisduerr** [comment]
Thanks for the update and creating an issue upstream!

**Comment by Holi0317** [comment]
The issue no longer exists after updating awesomeWM or updating winit. Closing this issue now.

Thanks for your help :)
