### ISSUE TITLE
Config file migrator

### ISSUE THREAD

**Issue by Lucretiel** [jwilm/alacritty#2011]
Feature request: please add a utility or command that allows us to migrate deprecated config file fields (update the names as necessary, remove deprecated fields, and prompt if necessary to change things (for example, changing decorations from a bool to a list of options). This should also add new config fields as they're added.

Currently my solution for this problem is to have an edited config file in my local git repo, and merge it with the upstream config defaults every time I do a pull. This means that I can't use package managers like `brew cask`.

**Comment by nixpulvis** [comment]
I was pondering something like this myself, though mostly for comparing. I'm a little confused as to why you can't just fix the deprecations and then commit it like anything else however. Yes we need to update the config file (either manually or automatically), but how does that effect the use of package managers?

I'm not sure it's a good idea to maintain a mapping of all the deprecations, since there's not always a single new config to choose. The tool would probably need to ask the user which value they'd like and now it's getting complex. I was thinking something simple to diff things could be good enough. Maybe https://github.com/sahilm/yamldiff?

**Comment by chrisduerr** [comment]
All new configuration options are always added to your configuration option silently as fallback defaults. You only need to add them yourself if you want them as documentation or you'd like to change them. The defaults will always take effect, no matter if the option is present or not.

**Comment by Lucretiel** [comment]
That's good to know. Still, it prevents discovering the new options; it's
nice to be able to read through the config file and see the comments with
all the things that can be changed. Sublime text does this well; it shows
the (read-only) default config file side by side with yours

**Comment by chrisduerr** [comment]
That's why the default configuration file is always present in the repository. The change log should also always document the new options since the last versioned release.

**Comment by Lucretiel** [comment]
Yes, but if you use a package manager, your upgrades don't involve a round
trip to the repository, at least not in any easily accessible way.

**Comment by nixpulvis** [comment]
@Lucretiel maybe log into IRC if you can, I'm curious how this effects a package manager. But this thread is not making it easy, and is getting a little noisy.

**Comment by MarioRicalde** [comment]
This issue has been without activity for close to 2 months. If there's nothing more to be said about it perhaps it'd be wise to close it?

**Comment by chrisduerr** [comment]
Time flies! I think it makes sense to close this issue as wontfix in its current state. I don't see Alacritty ever having a dedicated tool to config file migration (like `rustfix`). Instead, Alacritty should strive to provide backwards-compatibility for as long as possible and using warnings to guide users to the new options.

Hopefully the more mature Alacritty becomes, the less useful such a tool should become too. If there are any great arguments or proposals for this, I'm open to discuss it. But I don't think there's going to be any change in this space.
