### ISSUE TITLE
Implement Alt + Enter to fullscreen on Windows

### ISSUE THREAD

**Issue by jantari** [jwilm/alacritty#2012]
\- Feature request -

Alt + Enter is a standard, expected shortcut on Windows systems to fullscreen the active application.
It is supported by the default conhost terminal too - it should be enabled by default in alacritty as well.

I often use it when I don't want to be distracted by other stuff that's open on my monitor,
it would be fantastic if you could add it - thanks a lot!

**Comment by chrisduerr** [comment]
It should be possible to add a new key action to fullscreen Alacritty. That should take care of this.

**Comment by jantari** [comment]
Thank you - I realize that. This is more of a suggestion to enable it by default on Windows as it is an "expected" behavior on the platform - feel free to disagree and close though if it's not in the cards.

**Comment by nixpulvis** [comment]
This is 100% just because I find this interesting, not because I think we need to do anything with this information but...

From: https://support.microsoft.com/en-us/help/81823/alt-enter-switches-between-window-and-full-screen

> NOTE: ALT+ENTER only switches to full screen on x86 machines.

Very strange.

**Comment by seritools** [comment]
@nixpulvis The support article probably talks about the exclusive/"raw" fullscreen just like DOS in the old days. Since virtual 8086 mode/16bit mode/DOS mode is not possible anymore in long mode/64bit, these old video modes were removed as well, probably.

At least on Windows 10, ALT+ENTER basically goes into "borderless windowed" fullscreen mode.

**Comment by iryan2** [comment]
Would love this in MacOS too - muscle memory from iTerm ;)

**Comment by chrisduerr** [comment]
It's possible to add a global binding for maximizing on macOS already I believe. Though this would likely be added with an `action` which would be available as a keybinding on all systems (though only bound by default on Windows).

**Comment by shinobu-uwu** [comment]
Can I disable this behavior? Alacritty is pretty much unusable by me on windows because of this

**Comment by kchibisov** [comment]
You can unbind any binding in the config by adding the exact same binding and changing the action to `None` or `ReceiveChar`

```
  - { key: Return,   mods: Alt,           action: ReceiveChar }
```
