### ISSUE TITLE
Can I link alacritty with my executable?

### ISSUE THREAD

**Issue by Gymmasssorla** [jwilm/alacritty#2013]
Hello!

I want to write my own console application in Rust that will be communicating with users entirely on alacritty and will be distributed under the GPL-3.0 license. Can I do that according to the [alacritty's license](https://github.com/jwilm/alacritty/blob/master/LICENSE-APACHE), and if I can, what should I do (for example, print some messages and give files to end users)?

**Comment by chrisduerr** [comment]
I'm not entirely sure what you're talking about, but I don't think there would be license issues.

However the terminal interface is completely standardized and doesn't require complying with any licenses. Writing a shell that works inside of Alacritty, or a program that works inside a shell should always be perfectly fine.

**Comment by nixpulvis** [comment]
> "Derivative Works" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of,
the Work and Derivative Works thereof.

Seems like linking shouldn't be an issue, though I'm no legal/license expert.

@chrisduerr I believe @Gymmasssorla is talking about linking in some kind of shell and packaging it together with Alacritty to use as a standalone application. Is that correct?

**Comment by Gymmasssorla** [comment]
> > "Derivative Works" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely **link** (or bind by name) to the interfaces of,
> > the Work and Derivative Works thereof.
> 
> Seems like linking shouldn't be an issue, as the Apache license doesn't seem to mention what license a linking application must use. Though I'm no legal/license expert, maybe I'm wrong.
> 
> @chrisduerr I believe @Gymmasssorla is talking about linking in some kind of shell and packaging it together with Alacritty to use as a standalone application. Is that correct?

Yes, it is. By doing that, my application will automatically launch with the alacritty interface, since it will be compiled with alacritty.

**Comment by MarioRicalde** [comment]
What's the status with this issue? If it's done, please close it. Thank you!

**Comment by Gymmasssorla** [comment]
Yeah, it's done. Thank you!
