### ISSUE TITLE
Smart selection, select everything between brackets

### ISSUE THREAD

**Issue by JeanMertz** [jwilm/alacritty#2014]
In Terminal.app, you can double-click a starting bracket (for example, `{`), or the closing one, to select it and everything up to and including the bracket pair:

![terminal](https://user-images.githubusercontent.com/383250/51379123-f8d96680-1b0e-11e9-9d2a-e2e0433e14bb.gif)

I believe this behaviour is different (but not exclusive) to the already existing "[smart selection](https://github.com/jwilm/alacritty/issues/30)" functionality. 

I use this functionality a lot when dealing with large (log) outputs that include JSON for example, to quickly see where an object starts and ends. It serves as a quick visual aid to limit the scope in which I have to search for some key.

I know this use case can also be tackled by using `less` or `grep` or some other way, but it's not always obvious when I run a command that I need to find a needle in a haystack, so in Terminal.app I could use this handy functionality to quickly find what I'm looking for, instead of having to execute the command again with some extra commands piped onto it, to achieve the same result.

**Comment by chrisduerr** [comment]
I'm unaware of how this feature works. What happens when there is no opening bracket?

**Comment by JeanMertz** [comment]
> What happens when there is no opening bracket?

It only selects the single character (`}`) when double-clicking.

**Comment by chrisduerr** [comment]
Does this only work over a single line? How far back will this work? Will it search the entire scrollback buffer for the matching bracket?

**Comment by JeanMertz** [comment]
It works over multiple lines.

So for example this:

```
{ hello \
    }
```

selects both lines.

Interestingly, I never tested how it works across commands, and never really ran into this situation, but here's another case:

```
$ echo "{"
{
$ echo "}"
}
```

Selecting the first `{` between `"`, selects everything starting from that character all the way to the last `}` on the last line (which makes sense, if you just consider all text as one big blob).

Similarly, selecting the second `{` (the output of the echo, on line 2), selects all the way until the first `}` on line three, so including the `"` before that bracket, but excluding the one after the bracket. Which again is consistent with it considering all text on the screen combined as one blob to select over.

I don't have a big example at the ready, so I don't know the limits of the scrollback, but I used to use this daily, and have never noticed a situation where it didn't work across multiple lines or when using a "very large" payload.

**Comment by JeanMertz** [comment]
Also, one more note: I'm demonstrating this using `{` and `}`, but it works the same for `(` and `[`.

**Comment by chrisduerr** [comment]
Thanks for going into detail about this feature. There's still a few issues with this like the huge amount of cells it might potentially have to go through in a worst-case scenario or the unexpected behavior for users which aren't familiar with it. But generally I'm not completely opposed to the idea.

**Comment by JeanMertz** [comment]
> But generally I'm not completely opposed to the idea.

👍

If I find some time, I'll take a stab at this.

It might be interesting to introduce a `selection.pair_match_chars` config, similar to `selection.semantic_escape_chars`, which you can set to characters that you want to match on.

The behaviour would then be:

* one click + hold = regular selection
* two clicks + hold = semantic selection
* two clicks + release on a character that's configured in `pair_match_chars` = pair match selection (or however we want to name this)
* three clicks = line selection

`selection.pair_match_chars` would default to `{}[]()<>`, but you could also add `"` to that list to be able to quickly select text between quotes (including the quotes), or if you have some special use case to select everything between `|` or `a`, you could configure that if you want to.

The only problem I see with anything that does not have a clear start and end character, is that you'd have to default to searching forward, but also search backward if no matching pair is found when double-clicking `"` for example. So perhaps we should just start with still allowing to tweak `selection.pair_match_chars`, but the only valid values are any of `{}[]()<>`?

How does this approach sound?

**Comment by chrisduerr** [comment]
Limiting it to characters that have a clear start and end seems like a good choice. I'm not sure if I'd want a configuration option for this setting at all. Giving such tiny features configuration options quickly leads to a lot of config bloat.

**Comment by nixpulvis** [comment]
@JeanMertz this sounds like an awesome feature. I agree our default `pair_match_chars` (would `paired_chars` be any better) should be only the list (`{}[]()<>`) you provided, others could be added.

**Comment by JeanMertz** [comment]
I've done a first pass at implementing this in #2022. Let me know your thoughts. For now, I've opted to: ignore anything discussed in #1210, stick to the agreed upon brackets, and not provide any tunables.

**Comment by JeanMertz** [comment]
> I'm not sure if I'd want a configuration option for this setting at all. Giving such tiny features configuration options quickly leads to a lot of config bloat.

I did not add a configuration option in the current implementation, and I'm fine with that, but I wanted to quickly give my 2¢ on this.

As a "pro" application, I believe Alacritty caters to people that like their tools to do the job for them exactly the way they want. At the same time, I also agree that it shouldn't require going through 1000 tunables to get a "basic" set-up that works for 80% of the cases you need it to work for.

That's why I prefer tools that give both: they have a higher-level configuration overview that allows you to tweak the basic functionality of the tool, but also offer a way to dig down into the nitty-gritty, and configure the tool exactly to your liking.

Usually, tunables start in this second (lower-level) category, and if deemed useful to a large percentage of people, they are "promoted" to the main configuration interface of the tool. Similarly, if a tunable becomes less useful due to changes in the tool, it makes sense to downgrade that tunable back to the lower-level category.

Sometimes, these two levels are distinguished by having a UI for the high-level configurations, and a configuration file for the lower-level tunables, but that's not always the case, it could just as well be two separate configuration files, or just one file, with (in the case of Alacritty) a distinction between the two by having a separate nested YAML object to signify that you're heading down into the nitty-gritty details.

Some tools that follow these practices (I'm sure there are more, but these are the ones I can think of right now):

* VS Code, by having a configuration panel, and a separate json file to expose all tunables
* Google Chrome, by having a `chrome://flags` page, and the regular settings page

Just some food for thought 😄

**Comment by JeanMertz** [comment]
> frankly I'm inclined to side with @chrisduerr here, as I can't see changing the values. I might have a different impression after weeks of using it.

I fully agree, with the current implementation, I too don't see a reason to make this particular feature tunable.

I was more talking about the general approach towards configurability of Alacritty, the choice between a simple configuration with few tunables, or complicated configuration with many, and the fact that there is an alternative, where both situations are possible.

Thanks for linking to that issue. It does seem somewhat related, but yeah, this is less of a technical challenge, and more of a principle of the project itself.
