### ISSUE TITLE
Crash on startup Windows: not yet implemented

### ISSUE THREAD

**Issue by danreeves** [jwilm/alacritty#2020]
Which operating system does the issue occur on?
Windows

Crashing on launch of a fresh install of v0.2.6 with no prior installs

```
panicked at 'not yet implemented: ', font\src\rusttype\mod.rs:64:35
```

I tried removing the font settings completely from the genereated alacritty.yml but it didn't change anything

**Comment by chrisduerr** [comment]
Does this occur with the default config?

@zacps This is the first time I've seen this. Is there any reason why this would *ever* lead to a hard crash instead of falling back to the normal weight/slant and printing a log message?

**Comment by danreeves** [comment]
Yes, it was the default config alacritty generated

**Comment by chrisduerr** [comment]
I've created a PR here: #2021. Testing would be appreciated since I don't have a Windows 10 machine myself.

I'll release another version once this is resolved.
