### ISSUE TITLE
SSH unusable due to escape character being sent

### ISSUE THREAD

**Issue by wpovell** [jwilm/alacritty#2027]
Arch Linux 4.20.3 (X11), Alacritty versions 0.2.5 and 0.2.6

When SSHing certain escape character seem to be sent over, which is especially apparent when using editors like nano and vim as it prevents the editor from handling actually typed keystrokes. I believe the escape character is `^[[?6c`. Using the same SSH server and config this does not occur in either kitty or xterm. The escape code does not appear in my alacritty config but I might be missing something. I've included it below, but it's just the default.

[config.txt](https://github.com/jwilm/alacritty/files/2777043/config.txt)

**Comment by chrisduerr** [comment]
Does this get fixed when running ssh using `TERM=xterm-256color ssh`?

**Comment by wpovell** [comment]
Still occurs. Also seems shell independent, fails to work in both `bash` and `fish`

**Comment by chrisduerr** [comment]
Could you go into more details on how to reproduce this?

**Comment by wpovell** [comment]
Okay, I've figured out what it is. If I `export TERM=xterm-256color` after SSHing before running nano it works. My TERM variable on the remote host was `linux` (I forget why I set it to this exactly, it was due to a bug in Kitty which I used to use haha). I can reproduce without SSH by exporting it locally and running `nano`. It definitely spazzes out when this happens, but not sure if it qualifies as a bug. Let me know what you think, thanks for the TERM export suggestion.

**Comment by wpovell** [comment]
I don't know SSH handles inheriting envvars, but your ssh snippet above may have worked on other hosts; the host I'm testing on hops though a gateway which was probably dropping and reexporting locally.

**Comment by chrisduerr** [comment]
Everything other than `TERM=alacritty` is not officially supported. Even though sometimes it might work out for you, since the `alacritty` terminfo might not be installed, it's not officially the right way to run Alacritty. Using the appropriate terminfo is important to tell applications which features Alacritty supports, missreporting these features can obviously lead to problems.
