### ISSUE TITLE
Conform to XDG spec

### ISSUE THREAD

**Issue by 0X1A** [jwilm/alacritty#203]
Alacritty configuration should default to `$HOME/.config/alacritty/alacritty.yml` as the [XDG spec suggests](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). This is also the standard behavior for most applications. This will also help avoid environment variables being unset and introduce bugs with expected configuration file loading.

I'm also willing to open a PR for this issue.

**Comment by jwilm** [comment]
I would take a patch that makes that the default, but I want to keep supporting the current location for the present time (rather than cause unnecessary churn right now). We're using the `xdg` crate, so this should be relatively easy to add.

Thanks for filing the issue!

**Comment by 0X1A** [comment]
I honestly think the earlier this is done the better. If we keep falling back to `$HOME/.alacritty.yml` the harder it will become to change this as alacritty gains more users.

**Comment by jwilm** [comment]
Forcing people to switch it over immediately doesn't buy us anything. We can make it the default for all new installs, and update the documentation to only reference this location. We can also announce that this is the plan moving forward, and that gives people a chance to migrate at their leisure. When support for the other locations is removed, it would potentially affect less people.

This would probably be a good time to start a change log.

**Comment by NickeZ** [comment]
I'm also in favor of moving it now. At least make sure to move it *before* the alpha release.

**Comment by jwilm** [comment]
This would definitely happen before the alpha release.

**Comment by lukaslueg** [comment]
One could make alacritty look for the old path as last resort and only create the default in the new one

**Comment by 0X1A** [comment]
@lukaslueg This move would result in three paths that are looked for:

1. `$HOME/.alacritty.yml`
2. `$HOME/.config/alacritty.yml`
3. `$HOME/.config/alacritty/alacritty.yml`

1 and 2 do not conform to the xdg spec. Ideally there should be only one hard-set config path for default when `XDG_CONFIG_HOME` is not set that would be case 3

**Comment by lukaslueg** [comment]
This would me a stopgap measure so that older installations would still work while newer put the file in the right place from the get-go. Alacritty might issue a warning when it loads the file from there. The priority is

1. `$HOME/.config/alacritty/alacritty.yml`
2. `$HOME/.alacritty.yml`
3. `$HOME/.config/alacritty.yml` (works, but warning given)
