### ISSUE TITLE
Rendering artifacts in last column on Windows

### ISSUE THREAD

**Issue by lzybkr** [jwilm/alacritty#2031]
I see this most often when using `vim` - characters written in the last column are not cleared when switching between the alternate screen buffer and the main screen buffer.

Here is a simple PowerShell script that demonstrates the problem (I'm using conpty with a version of conhost that is post 1809, so something like the Windows Insiders builds):

```powershell
try {
    $e = [char]0x1b
    [Console]::Write("${e}[?1049h")

    $w = [Console]::WindowWidth
    $t = [Console]::WindowTop

    for ($i = $t; $i -lt $t + [Console]::WindowHeight; $i++) {
        [Console]::Write("${e}[${i};${w}HZ")
    }
    $null = [Console]::ReadKey()
} finally {
    [Console]::Write("${e}[?1049l")
}
```

Before:

![image](https://user-images.githubusercontent.com/2148248/51563831-512ba380-1e42-11e9-9f94-0e6a12d5c614.png)

And after:

![image](https://user-images.githubusercontent.com/2148248/51563852-5e489280-1e42-11e9-8e1c-b9708319c383.png)

**Comment by chrisduerr** [comment]
Fixed in the latest master: https://github.com/jwilm/alacritty/pull/2015.

**Comment by lzybkr** [comment]
Awesome, fix verified with my repro.

**Comment by chrisduerr** [comment]
Thanks for testing, glad to hear it works!
