### ISSUE TITLE
Pasting large text then CTRL-C makes the terminal freeze

### ISSUE THREAD

**Issue by verdie-g** [jwilm/alacritty#2032]
Hi,

I'm using Archlinux and X11, here is the bug I have experienced.

Steps to reproduce:
- select large text ([this one for example](https://pastebin.com/raw/dT9fkv2D))
- paste it in alacritty
- CTRL-C before the pasting is done

The pasting stops but no prompt is displayed, you need to restart the term.

**Comment by chrisduerr** [comment]
Which shell are you using @verdie-g?

**Comment by nixpulvis** [comment]
I can reproduce this issue in **both** Alacritty and Termite inside of `fish`, but not in other shells. I suspect this is a fish bug, and should be reported (if it's not already) there.

**Comment by verdie-g** [comment]
Fish. Shoud I close ?

**Comment by nixpulvis** [comment]
@verdie-g I just did a quick search of https://github.com/fish-shell/fish-shell/issues and I couldn't find anything. Maybe do a search yourself and open one there. I'm personally using `fish` myself (at least until my https://github.com/nixpulvis/oursh project works better), so I'd love a link to the issue to follow.

But yea, this issue should be closed.

**Comment by verdie-g** [comment]
@nixpulvis I'm also searching in fish issues, I haven't found anything. I have opened one [#5572](https://github.com/fish-shell/fish-shell/issues/5572)
