### ISSUE TITLE
Mouse wheel scrolling on macOS swallowing clicks

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#2033]
I've just recently gotten access to a MBP and noticed that when using a mouse with it, that scrolling by a single mouse 'click' does not work. Even with the scrolling speed at maximum. It is possible to repeat this infinitely without ever scrolling a single line if there's enough of a pause in between the clicks. When scrolling quickly, it seems to work.

My assumption would be that mouse scrolling on macOS is actually handled like a trackpad instead of a mouse, so it might be sending fractional updates instead of independent clicks. However I haven't verified that yet.

**Comment by chrisduerr** [comment]
I've checked this out on my MBP again and it seems like macOS is actually sending fractional line updates. So it's not using the trackpad handling, but instead using the normal line scrolling with fractional values.

It should be fairly simple to fix this. It would probably be good to make sure there won't be any duplication between the trackpad and scroll wheel updates though.

**Comment by danpker** [comment]
I'm not sure if it's related but I'm getting a similar issue (on MacOS) where I can't click on the window to gain focus anymore, I have to alt tab to Alacritty before I can get focus. Weirdly, if I move the cursor over the Alacritty window and scroll on the trackpad, it will cycle through recently used commands.

**Comment by chrisduerr** [comment]
I've realized that Alacritty is doing everything right here. The macOS mouse support is just awful and has extremely shitty mouse scaling that almost makes using anything other than the touchpad impossible.

**Comment by soooch** [comment]
Hi, just wondering if there was any possibility of further exploration in this area? Terminal.app and iTerm seem to be able to handle scrolling events from both trackpad and notched mouse wheels correctly on Mac.

This file from iTerm2 may be of use: https://gitlab.com/gnachman/iterm2/-/blob/master/sources/iTermScrollAccumulator.m

I would be interested in creating a PR for this issue, but have not looked at Alacritty's code at all, so would appreciate any direction on where to start or whether there is anything I may be overlooking.

**Comment by soooch** [comment]
This super quick change seems to fix the behavior on my machine. I have a mouse with a notched scroll wheel, and this change allows alacritty to scroll just like terminal.app. I am not sure if mice with smooth scroll wheels would be negatively impacted by this change as I do not have one to test.

```diff
    pub fn mouse_wheel_input(&mut self, delta: MouseScrollDelta, phase: TouchPhase) {
        match delta {
            MouseScrollDelta::LineDelta(_columns, lines) => {
+               #[cfg(not(target_os = "macos"))]
                let new_scroll_px = lines * self.ctx.size_info().cell_height();
+               #[cfg(target_os = "macos")]
+               let new_scroll_px = lines.signum() * self.ctx.size_info().cell_height();
                self.scroll_terminal(f64::from(new_scroll_px));
            },
            MouseScrollDelta::PixelDelta(lpos) => {
                match phase {
                    TouchPhase::Started => {
                        // Reset offset to zero.
                        self.ctx.mouse_mut().scroll_px = 0.;
                    },
                    TouchPhase::Moved => {
                        self.scroll_terminal(lpos.y);
                    },
                    _ => (),
                }
            },
        }
    }
```

**Comment by soooch** [comment]
Just realized this would disable scroll acceleration, and so does not exactly match terminal.app. The following solution is better, but probably still does not exactly match.

```diff
diff --git a/alacritty/src/input.rs b/alacritty/src/input.rs
index 07b3154c..b2a12b32 100644
--- a/alacritty/src/input.rs
+++ b/alacritty/src/input.rs
@@ -606,7 +606,10 @@ impl<T: EventListener, A: ActionContext<T>> Processor<T, A> {
     pub fn mouse_wheel_input(&mut self, delta: MouseScrollDelta, phase: TouchPhase) {
         match delta {
             MouseScrollDelta::LineDelta(_columns, lines) => {
+                #[cfg(not(target_os = "macos"))]
                 let new_scroll_px = lines * self.ctx.size_info().cell_height();
+                #[cfg(target_os = "macos")]
+                let new_scroll_px = lines.abs().max(1.).copysign(lines) * self.ctx.size_info().cell_height();
                 self.scroll_terminal(f64::from(new_scroll_px));
             },
             MouseScrollDelta::PixelDelta(lpos) => {
```

**Comment by 0xDAEF0F** [comment]
I have had this exact same problem on macos since I started using alacritty (~2 years ago) and I just do scrollback with my keyboard instead with TMUX.

I wonder if this issue has been tracked.

**Comment by zaidamazon191** [comment]
bump
