### ISSUE TITLE
Key repeat rate on Linux, Wayland, Sway is interpreted inversely

### ISSUE THREAD

**Issue by e00E** [jwilm/alacritty#2041]
I am using Linux with Wayland with Sway.

I am setting the key repetition rate in my sway config. Per `man 5 sway-input`:
> input \<identifier\> repeat_rate \<n\>
>           Sets the key repeat rate in number of keypresses per second.

Alacritty is interpreting this value the wrong way.

When set to 1 I should observe one repetition per second and when set to 1000 I should observe 1000 repetitions per second. This works correctly in the browser I am typing this from (Firefox).

Alacritty seems to interpret the value as the number of milliseconds between repetitions giving me a lot of repetitions per second in the first case and 1 in the second case.

```
$ alacritty --version
alacritty 0.2.7
```

```
sway --version
sway version 1.0-beta.2-274-g5f45a4bb (Jan 25 2019, branch 'makepkg')
```

**Comment by e00E** [comment]
Which example should I use? The ones in the examples directory do not seem to display key presses judging by a quick glance at the code.

**Comment by chrisduerr** [comment]
@e00E Most of the examples will print all events. I'd recommend going for the `window` example using `cargo run --example window`.

**Comment by e00E** [comment]
It seems to be a bug in winit. See the last issue reference above this comment.

**Comment by e00E** [comment]
https://github.com/Smithay/client-toolkit/pull/62
