### ISSUE TITLE
Disable copy on selection

### ISSUE THREAD

**Issue by BartXZX** [jwilm/alacritty#2050]
Which operating system does the issue occur on?
Windows 

Repro steps
Select something in alacritty, paste into notepad++.

Whenever I select text in alacritty it gets copied.
I would like to disable this behavior, but I can't seem to find an option to do so.

Am I missing a setting? Someone over on IRC said he does not have this behavior on Arch Linux.

**Comment by chrisduerr** [comment]
https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L310?

**Comment by chrisduerr** [comment]
I'm not aware of this issue, potentially there was some mistake in the Windows implementation.

@zacps can you reproduce this issue?

**Comment by JDTX** [comment]
@chrisduerr  I can replicate this issue on my Windows machine.
Windows 10 build 1809, 64bit.

I set the "save_to_clipboard" directive to "false" and it still copies on selection.

**Comment by chrisduerr** [comment]
Fixed in https://github.com/jwilm/alacritty/pull/2341.

**Comment by simnalamburt** [comment]
FYI, This issue occurred again in v0.7.1 on Linux environment. It ignores `save_to_clipboard` directive.

**Comment by simnalamburt** [comment]
I'm experiencing the same issue with Alacritty 0.7.1 in linux wayland environment (sway).
