### ISSUE TITLE
ncmpcpp resets colors when window is resized

### ISSUE THREAD

**Issue by harrisonthorne** [jwilm/alacritty#2052]
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | Arch Linux 4.20 |
| Rust Version     | rustc 1.32.0   |
| Display Server   | Wayland (reproducible on X11 as well) |
| Window Manager   | sway |

# Behavior
I use wpgtk to match terminal colors to my wallpaper. When I'm using ncmpcpp, alacritty's colors will change (or reset?) when alacritty is resized. This issue isn't reproducible on kitty.

# Expectation
alacritty's colors should not change when alacritty is resized while running ncmpcpp.

Edit: here's a picture for reference. Alacritty on the left wasn't resized. Alacritty on the right was resized and the colors have changed.

![ncmpcpp on alacritty colors](https://i.ibb.co/hMdJDFB/1548874546.png)

**Comment by pezcore** [comment]
Noticed this in several other terminals as well.

**Comment by chrisduerr** [comment]
Looks like this is related to https://github.com/jwilm/alacritty/issues/1082, closing as duplicate.

**Comment by harrisonthorne** [comment]
Adding that this problem happens in `ranger` too. I haven't tracked down what causes ranger to have alacritty's colors reset yet, but wanted to note that this problem isn't limited to ncmpcpp.
