### ISSUE TITLE
Installing fonts-linuxlibertine makes font-rendering go weird

### ISSUE THREAD

**Issue by aslatter** [jwilm/alacritty#2055]
Which operating system does the issue occur on?

Linux (Ubuntu 18.04)

If on linux, are you using X11 or Wayland?

X11.

I'm using the default font in my Alacritty config (`monospace`), and I'm using the 'oh my zsh' theme 'agnoster', which uses fancy symbols for the prompt:

![image](https://user-images.githubusercontent.com/44175/52028149-86379600-24d3-11e9-9678-7019cbd04a47.png)

If I install the Ubuntu package "fonts-linuxlibertine" (required by the Ubuntu "libreoffice" package) these fancy symbols break in Alacritty:

![image](https://user-images.githubusercontent.com/44175/52028182-abc49f80-24d3-11e9-9ecf-63a28ea6dbdd.png)

The default Ubuntu terminal still renders these correctly, and if I switch both terminals to use the same fonts Alacritty displays the same error but the default Ubuntu terminal does not (although font configuration in Alacritty seems complex, so I could be doing it wrong).

**Comment by chrisduerr** [comment]
Can you reproduce this in a different terminal emulator? To me it looks like the priorities of your fonts just aren't setup correctly.

**Comment by chrisduerr** [comment]
Oh, I somehow confused myself and thought this was a macOS issue. If this is on Linux, then there are some known issues with the default fontconfig fallback which are tracked here: https://github.com/jwilm/alacritty/issues/1560.

You might still be able to make this work by tweaking the global font configuration a bit though.

**Comment by grawish** [comment]
> The default 'Termnial' application in Ubuntu doesn't appear to be affected:
> 
> ![image](https://user-images.githubusercontent.com/44175/52100896-142c8300-259f-11e9-8529-96d296821ed9.png)
> 
> It's possible that the unaffected terminal emulator doesn't support the new font I've installed, I guess?
> 
> I'm not familiar with font-priorities, but know I have a new term to search for! I'll post back if that turns up a fix.

hey the arrow symbol is shifted upwards in my machine same as the picture in this post. Can you please suggest a solution for this.
Thankyou.

**Comment by aslatter** [comment]
> > The default 'Termnial' application in Ubuntu doesn't appear to be affected:
> > ![image](https://user-images.githubusercontent.com/44175/52100896-142c8300-259f-11e9-8529-96d296821ed9.png)
> > It's possible that the unaffected terminal emulator doesn't support the new font I've installed, I guess?
> > I'm not familiar with font-priorities, but know I have a new term to search for! I'll post back if that turns up a fix.
> 
> hey the arrow symbol is shifted upwards in my machine same as the picture in this post. Can you please suggest a solution for this.
> Thankyou.

Which OS are you using? And which font?

Whenever I run into issues like this (on any OS/terminal emulator) I generally grab a different power line-patched font to try to see if it’s any different.
