### ISSUE TITLE
Input method select list position is not correct

### ISSUE THREAD

**Issue by chrisniael** [jwilm/alacritty#2056]
MacOS Mojave 10.14.2
Alacritty v0.2.7

<img width="663" alt="2019-02-01 1 34 26" src="https://user-images.githubusercontent.com/5593254/52109112-4984af80-2637-11e9-9702-d2394488bd90.png">

**Comment by chrisduerr** [comment]
Note this is not macOS-specific, but has been reproduced on Linux in #2061.

**Comment by pickfire** [comment]
@chrisduerr Why not update ime position after redraw?

**Comment by awused** [comment]
@chrisduerr That patch does not fix the issue for me, the IME position is unchanged.

I quickly fixed it for myself by dividing nspot_x and nspot_y in update_ime_position by hidpi_factor.

**Comment by chrisduerr** [comment]
Not taking DPI into account, sounds like a very likely cause for this problem! Thanks for looking into this @awused, unfortunately I'm completely unfamiliar with IME.

Would you mind sending a PR? I'll gladly help out with style or other issues if there still are some.

**Comment by chrisniael** [comment]
@chrisduerr , @awused 's PR code works fine for me
