### ISSUE TITLE
Two instances opened when keypress delay is too short

### ISSUE THREAD

**Issue by alter2000** [jwilm/alacritty#2067]
I'm on Arch and made a NixOS build (both X11 with tmux inside, tried on i3), and I'm seeing that whenever I do `xset r rate D F` for any D < 280 milliseconds, I get two running instances of Alacritty. Termite, xterm and urxvt (tested with all 3 in 2 different setups) didn't do this, so I guess I should write here.

I tried alacritty even without tmux with the default config and still got the same issue. Spawning another instance from shell opened only one, so I don't know any way find out more about this. I can work around this by autostarting alacritty or opening via .desktop files, although oftentimes I need quick separate terminals for ssh. IMHO this is not urgent, but I thought it's good to share if people get confused.

**Comment by chrisduerr** [comment]
This has been previously discussed in https://github.com/jwilm/alacritty/issues/1859 and the conclusion there was that i3 is requesting Alacritty to start twice, so Alacritty obliges.

If there is any indication that this is not the case, please let me know and I'll reopen #1859.
