### ISSUE TITLE
Support background image

### ISSUE THREAD

**Issue by tamamu** [jwilm/alacritty#2068]
I'd love to display a background image on alacritty.
I've already seen #565 that you don't plan to, so I tried to implement it (https://github.com/tamamu/alacritty/commit/8ca7e81985115d100fe3deacc7b7cf2195d37376).

However the text has not been displayed correctly like this;
<img width="593" alt="2019-02-03 18 15 50" src="https://user-images.githubusercontent.com/9401982/52174981-cc486e80-27df-11e9-9d7a-a78aee240263.png">
so can you give me some advice?

**Comment by chrisduerr** [comment]
Looks like a shader issue to me. Instead of checking for each pixel's opacity in the glyph, it just takes the whole glyph's bounding box.

**Comment by tamamu** [comment]
ok, I understand, but the first view has no problem... 
<img width="515" alt="2019-02-04 21 57 03" src="https://user-images.githubusercontent.com/9401982/52209717-173db100-28c8-11e9-9cec-5f809b430b39.png">
I got the situation I commented first, when the second drawing had run, so I doubt that `QuadRenderer::draw_rects` doesn't proper termination.

**Comment by butla** [comment]
Thinking about switching to alacritty, would love to have my usual calm grassy background.

@tamamu what's the issue with the last screenshot you've provided?
