### ISSUE TITLE
Add option to override colour of selected text

### ISSUE THREAD

**Issue by awused** [jwilm/alacritty#2069]
Right now selected text always inverts the colours, but this isn't always desirable, especially when the background and foreground colours are similar. It'd be nice to be able to override that so that text can always be made legible on selection.

A similar setting already exists for cursor colours, this would function equivalently for selected text.

**Comment by chrisduerr** [comment]
Seems reasonable to have something in line with what the already have for cursor colors, since both behave very similar anyways.

**Comment by MarioRicalde** [comment]
@chrisduerr isn't this closed by #2159 ?

**Comment by chrisduerr** [comment]
It is, thanks!
