### ISSUE TITLE
Alacritty doesn't place fish prompt at the top of the viewport on clear (C-l)

### ISSUE THREAD

**Issue by xorgy** [jwilm/alacritty#207]
I don't know how fish does this differently from bash, but whatever the case, Alacritty doesn't handle its escape sequence correctly.

**Comment by qoh** [comment]
Does this still happen? I use fish in alacritty and the prompt is always properly at the top after clearing.

**Comment by chrisduerr** [comment]
Closing because according to @qoh it seems like it should work and there was no further response from @xorgy.
