### ISSUE TITLE
True colors on Windows 10 with Cygwin

### ISSUE THREAD

**Issue by JDTX** [jwilm/alacritty#2088]
=== Environment ===
OS: **Windows 10** 64bit version **1809**
Alacritty version: **v0.2.7** (latest)
Shell: **Cygwin** (bash.exe)
Backend: **ConPTY**, but I tried winPTY, it has the same problem.

Here's my alacritty.yml config (renamed to .txt from .yml so it doesn't make this report huge)
[alacritty.txt](https://github.com/jwilm/alacritty/files/2842209/alacritty.txt)

Basically I cannot get true colors to work on Alacritty with Cygwin. I have tried everything possible to get it working but nothing has helped.
• Using [ANSICON](https://github.com/adoxa/ansicon) to launch/inject the alacritty/bash process
• Setting the `TERM` env variable in .bashrc and alacritty.yml to `xterm-256color`, `xterm`, `cygwin`, etc.
• Setting `COLORTERM` to `truecolor` in both .bashrc & alacritty.yml
• Importing the alacritty term (using `tic`) and setting it explicitly using `TERM` in .bashrc & alacritty

This is what Alacritty looks like with Cygwin for me:
![image](https://user-images.githubusercontent.com/24833917/52433477-c77f0580-2ad2-11e9-83ca-c0bb2491b71f.png)

This is what that same colortest.sh script looks like in MinTTY
![image](https://user-images.githubusercontent.com/24833917/52433508-d82f7b80-2ad2-11e9-96b4-222c940a4eb0.png)

(PS: If you're wondering why window titles are working for me in Windows, I applied the commit from https://github.com/jwilm/alacritty/pull/1708)

Here's the output of infocmp & `echo $TERM`
[infocmp-and-term.txt](https://github.com/jwilm/alacritty/files/2842233/infocmp-and-term.txt)

Here's the bash/shell script I used to test:
```awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```

I've done some of my own research and it seems that Cygwin processes ANSI codes internally instead of passing them to the TTY. So no sequences are sent to Alacritty whatsoever.  MinTTY works because it uses pipes instead of a TTY.   Another project called ConEMU made a [POSIX-compatible connector](https://conemu.github.io/en/CygwinMsysConnector.html) to fix this problem with Cygwin. Can something similar be made for Alacritty? Or is this too outside of the scope of the project?

Some (hopefully) useful links for this problem:
https://conemu.github.io/en/CygwinAnsi.html
https://conemu.github.io/en/CygwinMsysConnector.html#how-to-use
https://stackoverflow.com/a/40001741/1715736
https://github.com/adoxa/ansicon

Any input would be appreciated.

**Comment by nixpulvis** [comment]
Is this a dup of #2074?

**Comment by chrisduerr** [comment]
I think it would make sense to track this together with https://github.com/jwilm/alacritty/issues/1792, so closing this as duplicate.

Note that https://github.com/jwilm/alacritty/issues/2074 might be directly related, however it doesn't explicitly mention truecolor so I'll keep it a separate issue for now.

**Comment by cup** [comment]
https://github.com/alacritty/alacritty/issues/2107
https://github.com/alacritty/alacritty/issues/1792
https://github.com/alacritty/alacritty/issues/1662

https://github.com/alacritty/alacritty/issues/2088
https://github.com/alacritty/alacritty/issues/2578
