### ISSUE TITLE
launch failed

### ISSUE THREAD

**Issue by SolarAquarion** [jwilm/alacritty#21]
RUST_BACKTRACE=1 alacritty                            101 ↵  1471  20:36:18 
device_pixel_ratio: 1
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `1`, right: `0`)', font/src/ft/list_fonts.rs:161
stack backtrace:
   1:     0x556182a565f3 - <unknown>
   2:     0x556182a5bbed - <unknown>
   3:     0x556182a5b7eb - <unknown>
   4:     0x556182a5c078 - <unknown>
   5:     0x556182a5bf12 - <unknown>
   6:     0x556182a5be50 - <unknown>
   7:     0x556182a2697f - <unknown>
   8:     0x55618297e03c - <unknown>
   9:     0x556182a64996 - <unknown>
  10:     0x556182a5c8f8 - <unknown>
  11:     0x7f15fe914290 - __libc_start_main
  12:     0x55618293ac39 - <unknown>
  13:                0x0 - <unknown>

**Comment by jwilm** [comment]
Thanks for the report! Have you setup an `.alacritty.yml`? In any case, the code here should probably handle bad font config and provide a helpful message.

**Comment by SolarAquarion** [comment]
No, I have not.  But it should be installed in either /etc/xdg/alacritty or
/etc/alacritty.  It should also be able to look for
XDG_CONFIG_HOME/alacritty or ~/.alacritty.yml

**Comment by jwilm** [comment]
I hadn't thought about having a system level configuration file; that's a good idea. Per user configuration is supported by reading from `$HOME/.alacritty.yml` or `$HOME/config/alacritty.yml`. You can copy the `alacritty.yml` from the project root.

**Comment by SolarAquarion** [comment]
it still fails

**Comment by jwilm** [comment]
I'm guessing the font specified in the config isn't available on your system. Adding an issue to improve error messages on that front.

**Comment by SolarAquarion** [comment]
Just have "monospace" as the default font.  Let me try that

**Comment by jwilm** [comment]
Alacritty's fontconfig wrapper has been rewritten to not panic at all, and I think that means the original error you encountered should be fixed. There's still some work to do on error handling in the font loading code, however.

**Comment by SolarAquarion** [comment]
it's launches now thankfully.  I just need to change the font to a nicer one to be more "Nerd Font"

**Comment by jwilm** [comment]
Awesome. So others don't run into the same issue you did, I've updated the font loading code default to find whatever monospace font is default on the system and use that.
