### ISSUE TITLE
Alacritty displays garbage after 0.2.8 update

### ISSUE THREAD

**Issue by bemeurer** [jwilm/alacritty#2102]
I'm on Gentoo Linux running Wayland (sway). After the update to 0.2.8 (from 0.2.6) this is what Alacritty looks like:
![image](https://user-images.githubusercontent.com/7243783/52598159-db47a600-2e09-11e9-92db-e3ed81bfbc88.png)
Yikes! Any clues @chrisduerr ?

**Comment by bemeurer** [comment]
My [alacritty.yaml](https://github.com/bemeurer/dotfiles/blob/master/alacritty.yml)

**Comment by bemeurer** [comment]
Still happens with a fresh alacritty.yml:
![image](https://user-images.githubusercontent.com/7243783/52598336-41ccc400-2e0a-11e9-9b31-bf5ee94a2cc5.png)

**Comment by chrisduerr** [comment]
This is my bad, I've introduced a bad commit slightly before the version release and wasn't able to catch it in time.

This is related to font size changing, so resetting font size or moving alacritty between monitors with different DPI will cause this.

Testing of the fix would be appreciated, it's already included in the latest master.

A new point release is planned as soon as I've done sufficient testing to make sure everything works properly on all platforms.

**Comment by bemeurer** [comment]
Alright, testing master now

**Comment by bemeurer** [comment]
@chrisduerr I can confirm that fixes it!

I have another bug though, hang tight :)

**Comment by JohnMaguire** [comment]
Just chiming in to say I saw this issue too, as Arch updated to 0.2.8.

Installed the latest master with the alacritty-git package in the AUR, and everything is working again. Thanks for the quick fix @chrisduerr!

**Comment by chrisduerr** [comment]
@JohnMaguire The Alacritty maintainers on Arch have already updated to the 0.2.9 version in a matter of just a few hours. So hopefully that should work just as well.

**Comment by bemeurer** [comment]
@chrisduerr Thanks for the _phenomenal_ speed in fixing this!
