### ISSUE TITLE
Fonts look super weird

### ISSUE THREAD

**Issue by defau1t** [jwilm/alacritty#2103]
Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
Latest version of wayland, just installed alacritty version 0.2.8

I just updated, rebooted, and logged in. Now fonts in alacritty look like this...?
![screenshot](https://user-images.githubusercontent.com/6886717/52598775-70539a80-2e1c-11e9-8864-d03292c7d536.png)

Let me know what other details you need

**Comment by chrisduerr** [comment]
See https://github.com/jwilm/alacritty/issues/2102.

I'll try to release a new version asap as soon as sufficient testing is done to make sure no other regression has been introduced.

Sorry for the inconvenience.

**Comment by defau1t** [comment]
Alright no worries :) Thanks for the quick reply!
