### ISSUE TITLE
Allow highlighting drag to start from the border

### ISSUE THREAD

**Issue by wkral** [jwilm/alacritty#2109]
This is sort of a papercut type issue, often when I go to highlight some text in the window especially when it's maximized and against the left edge of my screen I can't start the drag without moving a couple of pixels to the right which appears to be the width of the border of the window. It usually means I end up having to attempt to drag more than once to get it right or start from the other end. I think this would improve the ergonomics of alacritty.

Which operating system does the issue occur on?

Linux

If on linux, are you using X11 or Wayland?

Wayland, though it appears alacritty runs in XWayland as it shows up in xwininfo.

**Comment by chrisduerr** [comment]
I've noticed this too and I think this is a great suggestion!

It also shouldn't be super complex to do, so if someone is interested this might be a fun thing to play around with. All relevant code should be in the `mouse_moved` method in `src/input.rs`.

**Comment by ladotonia** [comment]
Was interested to learn some Rust and took a look at this.

Seems to be a limitation of glutin::GlWindow, see here https://docs.rs/glutin/0.19.0/glutin/enum.WindowEvent.html#variant.CursorMoved

The event loop does not receive any events while the cursor is moving on the border, which exists even when the app is maximized. There is an undocumented "MouseMotion" WindowEvent that occurs (on Linux X11) but it only provides motion delta, so it would require tracking outside the app.

**Comment by chrisduerr** [comment]
This is about the padding that is created by Alacritty, so it is not relevant if we can get window events outside of Alacritty or not.

**Comment by ladotonia** [comment]
Thanks for the clarification, FWIW, on x11 I don't have any issues drag selecting from the left side of a maximized screen except for on the ~2 pixel window border.

**Comment by ladotonia** [comment]
@chrisduerr Thanks for the clarification, I misunderstood the issue.
