### ISSUE TITLE
Dead keys / combined characters printed twice

### ISSUE THREAD

**Issue by dbrgn** [jwilm/alacritty#211]
I'm on the Swiss German layout.

When typing dead keys (e.g. the backtick or the tilde) by pressing the corresponding key (usually with the AltGr modifier) and then space, the symbol is printed twice.

The same thing happens with combined characters. When typing the `é` using the corresponding direct key (it's available on my keyboard layout) it works. But when typing the forward-accent modifier dead key and then the letter e, the output is `éé`.

**Comment by uvesten** [comment]
Probably related to #209, but a bit different. On swedish layout, macOS the terminal stops responding when entering '´'

**Comment by okuuva** [comment]
This issue appeared after fixing the problem with non-ascii character typing in issue #87. It's mentioned there too.

**Comment by jwilm** [comment]
The duplication may be happening due to [this block](https://github.com/jwilm/alacritty/blob/master/src/input.rs#L358-L360) not being hit when the `Option<VirtualKeyCode>` is `None`.

**Comment by michelboaventura** [comment]
Hi @jwilm, I would like to give this issue a try, since I'm learning rust and this bug really make alacritty unusable for me, since every dead key is printed twice (even ^ and ~). Can you point me to where to start looking? Thanks

**Comment by jwilm** [comment]
@michelboaventura keyboard input processing is handled [here](https://github.com/jwilm/alacritty/blob/master/src/input.rs#L391-L420). It might be good to see what events are actually being sent to Alacritty too; try running with `--print-events`.

**Comment by jwilm** [comment]
@michelboaventura feel free to message me here or on IRC if you have more questions. Thanks for looking into this!

**Comment by michelboaventura** [comment]
@jwilm, I think I found the problem.

[Here](https://github.com/jwilm/glutin/blob/master/src/api/x11/input.rs#L134) glutin is calling ``XFilterEvent`` but is ignoring its result. Xlib [doc](https://www.x.org/archive/current/doc/man/man3/XFilterEvent.3.xhtml) says:

> If XFilterEvent returns True, then some input method has filtered the event, and the client should discard the event. If XFilterEvent returns False, then the client should continue processing the event.

So I moved the call to outside the ``if`` and did:
```Rust
let raw_ev: *mut ffi::XKeyEvent = event;
let filter = unsafe { (self.display.xlib.XFilterEvent)(mem::transmute(raw_ev), self.window) };

if filter == 1 {
    return translated_events;
}
```

And this fixed the issue for me \o/

I also found another issue which apparently is not causing any issue right now. If you look [here](https://github.com/jwilm/glutin/blob/master/src/api/x11/window.rs#L232) you will see that the code calls ``translate_key_event`` (which calls  ``Xutf8LookupString``) with both ``KeyPress`` and ``KeyRelease``, but according to [doc](https://www.x.org/archive//current/doc/man/man3/XmbLookupString.3.xhtml): 

> To ensure proper input processing, it is essential that the client pass only KeyPress events to XmbLookupString, XwcLookupString and Xutf8LookupString. Their behavior when a client passes a KeyRelease event is undefined.

So I remove the ``KeyRelease`` and things still work. And since ``translate_key_event`` is only being called with ``KeyPress`` its code can be simplified a bit.

I didn't send you a PR because this changes are on Glutin and we are using a specific commit from it.

**Comment by jwilm** [comment]
@michelboaventura That is some grade-A research! Fantastic job tracking this down. Bonus points for the bonus issue 👍 .

The thing to do with these fixes is upstream them to

1. My fork of Glutin
2. The winit library, which we will hopefully be using soon.

**Comment by jwilm** [comment]
Here's the [Glutin fork](https://github.com/jwilm/glutin), and you'll want the [`keyboard-mods` branch](https://github.com/jwilm/glutin/tree/keyboard-mods). After the patch lands on that branch, we can update Alacritty.

**Comment by michelboaventura** [comment]
@jwilm, thanks mate. Every time I decide to move from C I always end up debugging C code/documentation :)

I've created the PR on the glutin fork and will to the same on winit. Someone seems to had already tracked the same issue down there: https://github.com/tomaka/winit/issues/107

Speaking of winit, are you planning to move from glutin to winit? If so, I could give it also a try.

Cheers

**Comment by jwilm** [comment]
@michelboaventura winit is in the middle of a big API change. I'm hoping that we can get all of our features in before that is released and then switch once it's released.

**Comment by jwilm** [comment]
Oh, I landed your PR on my fork, and Alacritty can now be updated. I can do this later or if you make a PR I'll push the merge button whenever it shows up.

**Comment by michelboaventura** [comment]
@jwilm you mean a PR to update glutin on Cargo.toml?

**Comment by jwilm** [comment]
@michelboaventura yeah, and the changes to Cargo.lock after building with the new Cargo.toml.

**Comment by michelboaventura** [comment]
Done!

**Comment by rhaps0dy** [comment]
Sorry for reopening this and it's probably me doing something wrong. But this issue (and #411) are not still resolved for me on OS X. Is that normal? Can you point me to a way to fix them?

Thank you!

**Comment by b3z** [comment]
Somehow for me it still occurs as well.
