### ISSUE TITLE
No preview when cycling through Alacritty instances in Gnome3 / wayland

### ISSUE THREAD

**Issue by sevagh** [jwilm/alacritty#2111]
Fedora 29 with Wayland, latest master version of alacritty.

Bad quality pictures because it's unscreenshottable (being in floating/alt-tab mode prevents me from taking screenshots), so I took camera photos. The shortcut `alt-backtick` on Gnome 3 cycles through instances of the same program.

I have photos of it working for `urxvt`, and not working for `alacritty`. I have no idea where this behavior comes from, sorry I couldn't be more helpful.

![alacritty-no-preview](https://user-images.githubusercontent.com/8574092/52749674-bb95b680-2f9e-11e9-96a5-6db633259480.jpg)
![alacritty-no-preview2](https://user-images.githubusercontent.com/8574092/52749675-bb95b680-2f9e-11e9-9afb-7a82683d635d.jpg)

**Comment by agriffis** [comment]
FWIW I see working previews on GNOME/Wayland on Fedora 30 with v0.3.2-34-gdbad1b6 (master build from yesterday)

**Comment by sevagh** [comment]
Confirmed. I think we can close this.
