### ISSUE TITLE
Mango emoji (possibly others) has incorrect display width

### ISSUE THREAD

**Issue by keenahn** [jwilm/alacritty#2119]
Which operating system does the issue occur on?
MacOs Sierra

```
const LEMON  = '🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋'
const MANGO  = '🥭🥭🥭🥭🥭🥭🥭🥭🥭🥭🥭🥭'
const ORANGE = '🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊🍊'
```
<img width="310" alt="screen shot 2019-02-17 at 12 39 56" src="https://user-images.githubusercontent.com/283603/52918878-2bfb4b00-32b1-11e9-9729-2986cab2bd9e.png">

**Comment by nixpulvis** [comment]
Interesting, Firefox with `noto-fonts-emoji` is rendering pretty differently than we are too. Is there a reference somewhere for how to draw these things properly? Aka, who's "correct" here.

![deepinscreenshot_select-area_20190217155512](https://user-images.githubusercontent.com/715947/52919075-6c1bf700-32cc-11e9-857d-3f3da68d655b.png)

**Comment by chrisduerr** [comment]
See #1295.
