### ISSUE TITLE
Alacritty crashes when apt finishes

### ISSUE THREAD

**Issue by okuuva** [jwilm/alacritty#212]
Whenever `apt` finishes installing, upgrading or removing package(s) Alacritty crashes. The operation finishes just fine, and immediately after that the terminal window closes. This doesn't happen with `apt-get`, just with `apt`. Might have something to do with the progress bar in `apt` but there doesn't seem to be any unusual characters in it...
```
$ uname -a
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
```

**Comment by d3rrial** [comment]
Most likely a duplicate of #94

**Comment by okuuva** [comment]
I just tried this again with the latest master and the problem seems to have gone away, probably with the PR #91 as this indeed seems to be a duplicate of #94. Closing this, thanks!
