### ISSUE TITLE
Render issues on wake-up on MacOS

### ISSUE THREAD

**Issue by tehdb** [jwilm/alacritty#2124]
MacOS: 10.14.3
Alacritty: 0.2.9

On wake-up alacritty does not render properly:

![image](https://user-images.githubusercontent.com/3496336/53015064-677d4d00-344a-11e9-854c-2b8854a05ecb.png)

**Comment by chrisduerr** [comment]
I'm unable to reproduce this issue.

Can you provide minimal reproduction steps? Spawning Alacritty, going to sleep, then waking up, doesn't introduce it for me.

**Comment by tehdb** [comment]
I have two external monitors connected to MacBook Pro 2018 with dedicated Radeon Pro Vega 20 graphics card.

The left monitor (HD Monitor) is connected via hdmi without scaling and the right monitor (4k Monitor scalled to 3008x1692) is connected via display port to usb-c cable:

![image](https://user-images.githubusercontent.com/3496336/53080388-de711f00-34f8-11e9-81c4-cc196dd82ed5.png)

The originally described render issue also happens when I move the alacritty from one screen to another:

![2019-02-20 10 20 55](https://user-images.githubusercontent.com/3496336/53080589-4b84b480-34f9-11e9-8c90-8cd74ef94cd7.gif)

**Comment by tehdb** [comment]
```bash
sh-3.2$
sh-3.2$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
sh-3.2$
sh-3.2$
sh-3.2$ sh -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
sh-3.2$
sh-3.2$
sh-3.2$ brew cask info alacritty
alacritty: 0.2.9
https://github.com/jwilm/alacritty/
/usr/local/Caskroom/alacritty/0.2.8 (64B)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/alacritty.rb
==> Name
Alacritty
==> Artifacts
Alacritty.app (App)
sh-3.2$
sh-3.2$
sh-3.2$
```

please tell me if I should provide additional info about my system and developer env setup

**Comment by chrisduerr** [comment]
> sh-3.2$ brew cask info alacritty
alacritty: 0.2.9
https://github.com/jwilm/alacritty/
/usr/local/Caskroom/alacritty/0.2.8 (64B)

Looks like you're running version 0.2.8 to me, which I know had this issue. Though I was confused because you mentioned you were running 0.2.9. This looks like brew might be having some troubles.

**Comment by tehdb** [comment]
just did `brew cask upgrade alacritty` again, got 0.2.9 version and the issue seems to be gone

**Comment by tehdb** [comment]
did several tests, can not reproduce the issue anymore, it looks like it really should have been the problem with updating via brew, going to close this issue, thanks a lot for support
