### ISSUE TITLE
Windows: Cannot spawn new "cmd" instance using "command" keybinding

### ISSUE THREAD

**Issue by davidhewitt** [jwilm/alacritty#2128]
On windows if I add the following keybind:

      - { key: T,        mods: Control|Shift, command: {program: "cmd", args: []} }

Then when I hit Ctrl+Shift+T, the following happens:

- If the `Alacritty` instance running was launched from the desktop or taskbar, the `cmd` window immediately crashes.
- If the `Alacritty` instance was launched from another terminal, then that terminal is taken over by the new `cmd` process (wat!)

The fault all seems to lie in the `spawn_daemon` function. I think to fix we would need to use windows APIs directly rather than `std::process::Command`, which is a bit sad.

I will write up a PR, but I wanted to survey opinion first on what "correct" behaviour of this keybind should be. I propose the following:

Keybind | Result
------------ | -------------
`{program: "cmd", args: []}` | New command window opens
`{program: "cmd", args: ["echo", "hello"]}`| New command window opens, prints hello, immediately closes.
`{program: "foo", args: []}`| Program "foo" opens in new window

In particular, in Linux daemons as I understand are background processes. So should there be any situations where I can spawn a process with a hidden console window?

I discovered this while digging around with solving #1979. The `cmd.exe` pseudoconsole immediately crashes with the conpty backend.

**Comment by chrisduerr** [comment]
> If the `Alacritty` instance running was launched from the desktop or taskbar, the `cmd` window immediately crashes.

What reason does it give for crashing?

> In particular, in Linux daemons as I understand are background processes. So should there be any situations where I can spawn a process with a hidden console window?

I don't quite understand what you mean by this. Daemon mode is unrelated to the visibility of the window, it's about blocking the spawning process.

Regarding the behavior of the examples you linked, it all depends on how cmd.exe behaves when launching. The results should be the same they are when running it from the CLI. Of coures Windows' odd behavior to put terminal and shell together make things a bit more difficult, but from what I can tell `start cmd.exe` should open cmd, while just running `cmd.exe` spawns a new subshell.

So from what I can tell, neither of the first two examples should open a new window, they should instead run subshells, which would fall in line with the behavior of running `bash` on Linux. Running the program `foo` should only open `foo` in a new window, if `foo` spawns a process itself. In general it should just spawn the process foo, disconnect from its output, allow the OS to reap it and let it do whatever it wants.

**Comment by davidhewitt** [comment]
Thanks for your thoughts! More thoughts of mine below. The question seems to be where should the stdio of processes launched from Alacritty's keybinds be connected to? I see three possible options:

1. It goes to `/dev/null` or equivalent (I think this is what a unix "daemon" would typically do?)
2. It should output in the Alacritty window (i.e. suitable mode for subshells)
3. It should output in a new "windows" console window. 
3b. The above but output in a new Alacritty window

I get the impression that you suggest 1 & 2 are both fitting in different circumstances, but 3 is unusual.

I'm going to try and get alacritty running on my girlfriend's Mac in a bit and see what a `bash` keybind does on that system 😄 

---

> What reason does it give for crashing?

Still yet to establish that. It instantly closes with return code 1. My guess is that one or more of the stdio handles is incorrect for some reason.

> I don't quite understand what you mean by this. Daemon mode is unrelated to the visibility of the window, it's about blocking the spawning process.

Sorry, my poor wording. I meant I think of a daemon dissociated from its parent with stdio (usually) going to `/dev/null`, and while I guess it can spawn a window, most daemons I know of don't.

> Of course Windows' odd behavior to put terminal and shell together make things a bit more difficult, but from what I can tell `start cmd.exe` should open cmd, while just running `cmd.exe` spawns a new subshell.

AFAIK `start` is a keyword built in rather than an executable that we can spawn. It creates a new console window. cmd.exe takes over the current console window.  I don't think `start` can be used by `std::process::Command()` (or windows `CreateProcess`), so wouldn't be usable by alacritty's keybinds?

On that thought - I think a shortcut to launch a subshell would be really neat. Looks like a different problem than spawning a daemon, as the stdio handles would have to be owned by the shell running in Alacritty?

**Comment by chrisduerr** [comment]
> I get the impression that you suggest 1 & 2 are both fitting in different circumstances, but 3 is unusual.

1 would follow what Alacritty does on macOS and Linux today. So I'd recommend doing the same on Windows.

> while I guess it can spawn a window, most daemons I know of don't

Spawning a Window or not is completely unrelated to daemon mode. In fact, a ton of graphical applications spawn in daemon mode by default (like all Browsers I'm familiar with for example). This is also something Alacritty will need to support in the future, because macOS expects all applications to spawn in daemon mode by default (by themselves, regardless of who starts them).

>  I don't think `start` can be used by `std::process::Command()` (or windows `CreateProcess`), so wouldn't be usable by alacritty's keybinds?

That's definitely possible, but either way running Alacritty for a new Window would still be possible, so I wouldn't worry too much about that.

> On that thought - I think a shortcut to launch a subshell would be really neat

What for? Do you have any practical applications in mind? Also I'd assume you are talking about spawning a completely separate shell and forwarding its stdout to Alacritty's stdin, since spawning a subshell inside of the shell running in Alacritty doesn't make much sense.

**Comment by davidhewitt** [comment]
Gotcha - linux daemons are even more common things than I thought!

The subshell idea would be more useful in Windows where I often drop into a bash / WSL subshell. But I it would be a lot of work to implement so let's not do it when it's so easy to just type "bash".

I'll put a PR together which resolves #1979 and makes the behaviour here as close to a windows-equivalent to (1) as I can get.
