### ISSUE TITLE
crash in Parallels Desktop 

### ISSUE THREAD

**Issue by Vonfry** [jwilm/alacritty#2133]
Which operating system does the issue occur on?
NixOS in Parallels Desktop(virtual machine) with Parallels Tools installed.

If on linux, are you using X11 or Wayland?
X11

Error:
```
$ RUST_BACKTRACE=1 alacritty -v
Welcome to Alacritty.
Configuration loaded from /home/vonfry/.config/alacritty/alacritty.yml
device_pixel_ratio: 1
Alacritty encountered an unrecoverable error:

        There was an error initializing the shaders: failed compiling shader: ERROR: 0:14: '' :  version '330' is not supported
ERROR: 0:14: '' : syntax error: #version
ERROR: 0:15: 'layout' : syntax error: syntax error
```

**Comment by chrisduerr** [comment]
Alacritty requires support for OpenGL, since it's using the GPU to do all the rendering. Your virtual machine does not satisfy the requirements necessary for running Alacritty.

Note that there is #128 to track support for earlier versions of OpenGL.
