### ISSUE TITLE
Alacritty in ConPTY mode is breaking Python's string encoding, with "unknown encoding: cp0"

### ISSUE THREAD

**Issue by radix** [jwilm/alacritty#2137]
**OS:** Windows 10

This happens when I run Alacritty in ConPTY mode, but *not* in WinPTY mode.

```
PowerShell 6.2.0-preview.3
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Loading personal and system profiles took 1261ms.
C:\Users\radix> python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 'foo'

LookupError: unknown encoding: cp0
```

This also breaks some non-interactive Python programs:

```
aws ecr get-login --registry-ids 555 --no-include-email
Traceback (most recent call last):
  File "C:\Users\radix\.virtualenvs\devlandia\Scripts\aws.cmd", line 59, in <module>
    sys.exit(main())
  File "C:\Users\radix\.virtualenvs\devlandia\Scripts\aws.cmd", line 55, in main
    return awscli.clidriver.main()
  File "C:\Users\radix\.virtualenvs\devlandia\lib\site-packages\awscli\clidriver.py", line 56, in main
    return driver.main()
  File "C:\Users\radix\.virtualenvs\devlandia\lib\site-packages\awscli\clidriver.py", line 192, in main
    parsed_args, remaining = parser.parse_known_args(args)
  File "C:\Users\radix\.virtualenvs\devlandia\lib\site-packages\awscli\argparser.py", line 100, in parse_known_args
    setattr(parsed, arg, value.decode(terminal_encoding))
LookupError: unknown encoding: cp0
```

**Comment by radix** [comment]
More info. Note that I do not have the `PYTHONIOENCODING` environment variable set.

### With ConPTY:

```
C:\Users\radix> python -c 'import sys; print sys.stdin.encoding; print sys.stdout.encoding'
cp0
cp1252
```

### With WinPTY:

```
C:\Users\radix> python -c 'import sys; print sys.stdin.encoding; print sys.stdout.encoding'
cp437
cp437
```

**Comment by radix** [comment]
More info: I did some spelunking in ancient history googling stuff about "cp0". I found this thread on the Python mailing list:

https://mail.python.org/pipermail/python-bugs-list/2009-July/081533.html

Apparently Python uses [GetConsoleCP](https://docs.microsoft.com/en-us/windows/console/getconsolecp) to determine the encoding, so it seems that, for some reason, ConPTY is making GetConsoleCP return 0, while in WinPTY, it is returning 437.

**Comment by radix** [comment]
0 is supposed to indicate an error, according to the windows API documentation, but if I call GetLastError, I'm just getting 0 again -- "The operation completed successfully.". 🤷‍♂️

**Comment by chrisduerr** [comment]
I'm uncertain if this is due to Alacritty or ConPTY, but thanks for the report.

**Comment by radix** [comment]
This may just be a matter of Python needing to specifically avoid use of GetConsoleCP when it's running in a ConPTY. I see that vim has done a similar workaround: https://github.com/vim/vim/pull/3794/files/ac333c2db584231e295f170e0d80b38ff981590b#diff-8cbf5ccd71d2da642611b9b50c411233R3750 -- they have it fall back to GetACP. I guess this kinda makes sense, since ConPTY isn't a Windows Console, but a new thing entirely. But maybe MS should make GetConsoleCP actually work correctly in a ConPTY...

Even stranger, though, is that GetConsole*Output*CP does return something other than 0, but it's still not the same as what it used to return in a native console.

**Comment by chrisduerr** [comment]
Looks like this is none of Alacritty's business then? So this issue should probably be reported to Python (if it hasn't been already)?

**Comment by radix** [comment]
Yeah, and it seems python 3 already works around this issue (though not explicitly to support ConPTY; they just implemented properly error checking for the call).

I've worked around this issue by setting PYTHONIOENCODING explicitly.
