### ISSUE TITLE
tmux configuration: `set style -g` with `bold` attribute changes colors

### ISSUE THREAD

**Issue by rederekt** [jwilm/alacritty#2138]
Hi there!

I'm using MacOS Mojave with tmux 2.8 and alacritty.

While configuring tmux in `~/.tmux.conf` I discovered that trying to set the `bold` attribute (e.g. `setg status-style fg=white,bold`) changes the other colors set for that element.

Without `bold`:
<img width="335" alt="screen shot 2019-02-28 at 9 40 49 am" src="https://user-images.githubusercontent.com/4472562/53586400-02c79e00-3b80-11e9-80c5-65f57826306a.png">

With `bold`:
<img width="365" alt="screen shot 2019-02-28 at 9 42 46 am" src="https://user-images.githubusercontent.com/4472562/53586534-491cfd00-3b80-11e9-96d0-dfca96a831cf.png">

Strangely enough the `bold` option works for window configuration settings (i.e. `setw -g window-status-current-style fg=white,bold,bg=blue`) works as expected.

To make sure this was an alacritty issue, I opened up my `Terminal` app and ran `tmux`. Sure enough:

<img width="710" alt="screen shot 2019-02-28 at 9 46 25 am" src="https://user-images.githubusercontent.com/4472562/53587046-4cfd4f00-3b81-11e9-96b6-28b45cb97a4f.png">

Ignoring the messed up coloring, the text is definitely not grayscale, and it is bold.

Relevant settings and variables:
- `TERM` within `tmux`: `screen-256color`
- `TERM` outside of `tmux`: `xterm-256color`. I tried changing this to `screen-256color` in the Alacritty settings (and, separately, in my bash_profile), but it did not make a difference.
`.tmux.conf`
```
# Colors and Styling

# full 256 colors
set -g default-terminal "screen-256color"

# better status line colors
set -g status-style fg=white,bold,bg=colour8
# 
# set the color of the window list
setw -g window-status-style fg=cyan,bg=colour8
# 
# set colors of the active window
setw -g window-status-current-style fg=white,bold,bg=blue
# 
# colors for pane borders
setw -g pane-border-style fg=green,bg=black
setw -g pane-active-border-style fg=white,bg=yellow
# 
# active pane normal, others shaded out
setw -g window-active-style fg=colour12,bg=colour8
setw -g window-style fg=colour10,bg=colour8
# 
# command / message line
set -g message-style fg=white,bold,bg=colour8

# status line left side to show Session:window:pane
set -g status-left-length 40
set -g status-left '#[fg=green]Session: #S #[fg=yellow]#I #[fg=cyan]#P'

# status line right side: date/time
set -g status-right '#[fg=colour15] %d %b %R'
```

Relevant color/font settings in `alacritty.yml` (I'm using Solarized Dark):
```
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: '0x002b36' # base03
    foreground: '0x839496' # base0

  # Normal colors
  normal:
    black:   '0x073642' # base02
    red:     '0xdc322f' # red
    green:   '0x859900' # green
    yellow:  '0xb58900' # yellow
    blue:    '0x268bd2' # blue
    magenta: '0xd33682' # magenta
    cyan:    '0x2aa198' # cyan
    white:   '0xeee8d5' # base2

  # Bright colors
  bright:
    black:   '0x002b36' # base03
    red:     '0xcb4b16' # orange
    green:   '0x586e75' # base01
    yellow:  '0x657b83' # base00
    blue:    '0x839496' # base0
    magenta: '0x6c71c4' # violet
    cyan:    '0x93a1a1' # base1
    white:   '0xfdf6e3' # base3
```

Thanks in advance!

**Comment by chrisduerr** [comment]
> \# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

This is a common convention used by most linux terminals I'm aware of. If you do not like it, try setting this to `false`?

**Comment by rederekt** [comment]
@chrisduerr Now that you mention that...I realize the configuration is doing exactly what it's supposed to. I just didn't read the hex codes close enough during copy-pasta. 😝
