### ISSUE TITLE
Allow configuration files per OS

### ISSUE THREAD

**Issue by peter-edge** [jwilm/alacritty#2142]
Right now, Alacritty only allows a single configuration file that it searches for. Some of us use both Mac and Linux at varying times, and store our configuration files in a GitHub repository. Some configuration items are OS-specific, for example font, shell, and key bindings.

It would be nice if Alacritty allowed an OS-specific configuration file. The simplest version of what this would look like would be Alacritty not only searching for `alacritty.yml` in each of the four search paths, but also `alacritty_darwin.yml`, `alacritty_linux.yml`, or `alacritty_windows.yml`. So the new behavior:

1. $XDG_CONFIG_HOME/alacritty/alacritty_os.yml
2. $XDG_CONFIG_HOME/alacritty/alacritty.yml
3. $XDG_CONFIG_HOME/alacritty_os.yml
4. $XDG_CONFIG_HOME/alacritty.yml
5. $HOME/.config/alacritty/alacritty_os.yml
6. $HOME/.config/alacritty/alacritty.yml
7. $HOME/.alacritty_os.yml
8. $HOME/.alacritty.yml

This is the simplest option. Another option would be to do a merge of the main `alacritty.yml` and the specialized `alacritty_os.yml`, however this can be more confusing in practice with maps or lists in YAML. If this is done, instead of attempting to merge lists, you'd probably want to do overwrite, but I'd argue to keep this simple and just have an OS-specific config file override the `alacritty.yml` file.

Right now, "best practice" would be to do this with symlinks, ie you maintain seperate `alacritty_darwin.yml` and `alacritty_linux.yaml` files, and you make a symlink `alacritty.yml` at dotfiles installation time, which is a bit annoying.

**Comment by chrisduerr** [comment]
You can specify whatever configuration file you want to use with the `--config-file` CLI flag.

For everything else, there's https://github.com/jwilm/alacritty/issues/779.

**Comment by peter-edge** [comment]
That’s orthogonal, and doesn’t solve the problem/is not a duplicate.

If I have Alacritty installed as a Mac app, I’m not easily calling it with flags. As described above, it would be nice (and easy) for Alacritty to be able to detect this.

It’s disappointing that there can’t be discussion on such a useful feature and that this was closed. I would have offered some help here

**Comment by scallister** [comment]
Curious if others have found a preferred way to have Mac's spotlight open Alacritty with a specific config file?
Using an alias with `--config-file` works for terminals, but that does mean one has to open a terminal first just to close it again after opening Alacritty.

I also looked but am not seeing a way to specify `--config-file` via ENV variable, that could also be helpful.

Thanks!

**Comment by markgandolfo** [comment]
@scallister I'm not sure if you solved this. but you could just put a script in /Applications that executes `alacritty --config-file ~/.config/alacritty/alacritty_dawin.yml` 

you may need to create a directory, i.e. `/Applications/alac.app/alac.sh` 

as long as it's chmod +x spotlight should run it.
