### ISSUE TITLE
terminal 'alacritty-direct': limiting value of `colors' from 0x1000000 to 0x7fff

### ISSUE THREAD

**Issue by anowlcalledjosh** [jwilm/alacritty#2149]
When I compile Alacritty's terminfo with `tic -e alacritty,alacritty-direct /usr/share/terminfo/a/alacritty`, I get the following message amongst all the `unknown capability` spam:

```
terminal 'alacritty-direct': limiting value of `colors' from 0x1000000 to 0x7fff
```

and when `$TERM` is set to `alacritty`, 24-bit colours don't work in Vim (the root cause being that `t_8f` and `t_8b` aren't set).

I'm afraid I don't actually know if this is an Alacritty bug, a tic bug, or a Vim bug, sorry!

**Comment by chrisduerr** [comment]
This was changed due to https://github.com/jwilm/alacritty/issues/1862.

Can you actually make it work when changing the value in the `alacritty.info` to something else? Or how did you come to the conclusion that this is the issue?

**Comment by anowlcalledjosh** [comment]
Nope, I can't get 24-bit colour to work in Vim at all with `TERM=alacritty` without making modifications to my vimrc. I think it might be a Vim issue, though, based on the fact that Vim also doesn't support ctrl+cursor keys even when they're in the terminfo (#919).

I was basically just wondering if the message from tic was indicative of an issue with alacritty's terminfo file :)

**Comment by chrisduerr** [comment]
Would you mind telling me which platform this is on?

There's #1792 if you're on Windows, so there it definitely will not work.

On Linux/macOS/BSD there's also #1485 which is about supporting a certain kind of truecolor support.

**Comment by anowlcalledjosh** [comment]
I'm using Ubuntu 18.04.

---

going slightly off-topic: I did some digging, so here's why truecolour support in Vim is broken by default, and always will be broken without a change in Vim or in ncurses. (If I set `t_8b` and `t_8f` in Vim to the same values as they're set to for xterm, 24-bit colour works fine.)

The reason that truecolour works in xterm (and terminals like mlterm that Vim thinks are "like xterm") is that Vim includes a [hardcoded terminfo-like structure for xterm](https://github.com/vim/vim/blob/4f97475d326c2773a78561fb874e4f23c25cbcd9/src/term.c#L833), which includes a load of capabilities that aren't usually set in termcap.

Vim appears to be checking whether the terminal supports 24-bit colour by checking the `8f` and `8b` termcap capabilities:

https://github.com/vim/vim/blob/4f97475d326c2773a78561fb874e4f23c25cbcd9/src/term.c#L1617

I *think* these are going through ncurses (ltrace says that Vim is comparing "alacritty" with the name of each of its built-in terminfos, then calling `tgetstr` a lot), which AFAIK is meant to translate them into terminfo capabilities – I believe that ncurses doesn't know about `8f` and `8b` to translate them into whatever the appropriate terminfo check is for truecolour support (`setaf`/`setab`?), and instead just says that they're undefined. See https://invisible-island.net/ncurses/ncurses.faq.html#xterm_16MegaColors.

**Comment by dnkl** [comment]
This is what I've been having in my `/etc/vimrc` to force 24-bit colors:
```
" 24-bit color support
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

**Comment by chrisduerr** [comment]
@anowlcalledjosh Can you make this work with the config options that @dnkl has mentioned?

**Comment by anowlcalledjosh** [comment]
Yep, it works fine with `t_8f` and `t_8b` set by hand.

**Comment by chrisduerr** [comment]
Sounds like there's little Alacritty can do then, right? This issue should be addressed in vim.

**Comment by xerron** [comment]
Yep, it works fine with t_8f and t_8b set by hand.
