### ISSUE TITLE
Color scheme utility

### ISSUE THREAD

**Issue by shuhei** [jwilm/alacritty#2150]
Hi, I just wanted to let you know that I published a command line tool [colortty](https://github.com/shuhei/colortty) to generate color schemes for alacritty.

```sh
cargo install colortty

# List color schemes on https://github.com/mbadolato/iTerm2-Color-Schemes
colortty list

# Output a color scheme for alacritty
colortty get <color scheme name from `colortty list`>
# For example
colortty get Chalk
colortty get 'Solarized Dark'
```

I hope it's useful for alacritty users and updating the color scheme wiki!

**Comment by chrisduerr** [comment]
Looks like a nice tool, thanks for letting us know!
