### ISSUE TITLE
Extend key_bindings key enum

### ISSUE THREAD

**Issue by schonert** [jwilm/alacritty#2153]
I'm trying to configure alacritty to handle my danish keyboard mapping, and i've now reached the piont where i need to make a binding on `'` - which is not a [supported key](https://github.com/jwilm/alacritty/blob/master/src/config/mod.rs#L2290), at least of what i'm aware of.

I'm sure i'll encounter more unsupported characters along the way - 
so my questions goes:

### Can i somehow make a binding on a special characters?
_Yes)_ Awesome - Please enlighten me!
_No)_ No props - How can i contribute to the list of allowed keys?

**Comment by schonert** [comment]
Im closing this again. Digging through some old PRs and issues i figured out the syntax for `Scancodes` - seems so obvious now.

If anyone should stumble over this in the future - key_bindings support keycodes as `key` value. I ended up with the following line for `ALT` + `'` = `@`

```yml
  - { key: 42,        mods: Alt,          chars: "\x40"     } # @
```

**Comment by enizor** [comment]
If this is the "normal" way to make a  `@` on a Danish keyboard, I encourage you to add the whole remapping in the [wiki](https://github.com/jwilm/alacritty/wiki/Keyboard-mappings) :)

**Comment by enizor** [comment]
And FYI, `'` is actually mapped to `Apostrophe`
