### ISSUE TITLE
Alacritty doesn't respect working directory command line arg

### ISSUE THREAD

**Issue by kevlar1818** [jwilm/alacritty#2155]
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
X11

Running `alacritty` chooses `~/.config/bspwm` as the default working directory. (Perhaps I was working in that directory when I first ran alacritty? I'm really at a loss.) Running `alacritty --working-directory ~` or using any valid directory name does not change alacritty's startup working directory.

**Comment by chrisduerr** [comment]
If you run a shell inside your shell, Alacritty will not be able to track the working directory anymore and just running `alacritty` will not open the second instance in the same directory as the original. This is intended and there's little to do about it.

However, changing the working directory with `--working-directory` should definitely work and I can't reproduce that issue.

Could you share some more information about the shell you're running? If you run just `alacritty -e bash` and then try `alacritty --working-directory /tmp`, does that work?

**Comment by kevlar1818** [comment]
I use [sxhkd](https://github.com/baskerville/sxhkd) to launch programs with keyboard shortcuts, which appears to run commands using the default shell (for me, fish) ala SHELL -c COMMAND (according to `man sxhkd`). Sounds like this isn't a supported workflow by alacritty?

Running `alacritty -e bash` and then `alacritty --working-directory /tmp` does not work.

**Comment by nixpulvis** [comment]
Without anything like sxhkd I can launch `alacritty -e bash` then `alacritty --working-directory /tmp` and have a new terminal window inside the `/tmp` directory.

Maybe this is a problem with the way sxhkd passes arguments to `fish -c`. `fish -c alacritty --working-directory /tmp` doesn't pass `--working-directory` to `alacritty` at all, while `fish -c "alacritty --working-directory /tmp"` does, and therefor works as intended.

**Comment by kevlar1818** [comment]
Well this is clearly an issue with my setup (most likely sxhkd and/or fish), so I'll close this for now. Thanks for the input everyone.
