### ISSUE TITLE
Render issue - Doubles on TAB

### ISSUE THREAD

**Issue by a-nesovic** [jwilm/alacritty#2164]
_OS:_ Arch (with X11)
_Shell:_ ZSH 5.7.1
_Alacritty version:_ 0.2.9

**Issue:**
When using TAB to auto-complete a command, amount of letters typed before TAB get double rendered. Also, it's not possible to delete them. Take a look at the following GIF, if a description isn't good enough.

![wrong_render](https://user-images.githubusercontent.com/48174247/54055775-57a58d00-41ee-11e9-87b7-80bd39c34f1e.gif)

Other than this I experienced no issues. And I'm really starting to enjoy every single product out there that is based on Rust! ^_^

**Comment by chrisduerr** [comment]
Does this get fixed when changing the prompt to only include ascii characters?

**Comment by a-nesovic** [comment]
> Does this get fixed when changing the prompt to only include ascii characters?

Prompt was by default only ASCII. But I doublechecked now to be sure...
Any other ideas @chrisduerr ? And thanks for answering so quickly! :1st_place_medal:

**Comment by chrisduerr** [comment]
> Prompt was by default only ASCII

The `->` arrow is not an ascii character. I'd suggest removing it (maybe just replace the prompt with a simple `$` and then testing things again).

Unless I've misunderstood you and you mean that you've ran into the issue before changing your prompt.

I'm using zsh on Arch myself too and I've noticed this issue on macOS before, most of the time it was due to #1295 and replacing all unicode characters with pure ascii resolved it.

**Comment by a-nesovic** [comment]
@chrisduerr Perfect! You were right, can't thank you enough :bowing_man: 

The moment I become somewhat capable of at least solving those **`D-easy`** issues, I'll make my commitment.

I'm just blasted by Rust and underlying community. :heart_eyes:

**Comment by a-nesovic** [comment]
@chrisduerr Something else that I noticed just now, this happens only when the last character in the terminal prompt is UTF-8.
When **→** was the last character, the issue is there. But on the third line after sourcing my `.zshrc`, and changing it to **~**, even tho I had **●** and **U+FE0F** before it, I had no issues.

Maybe you already knew this behavior, and I guess this is really low priority to get fixed, but I just wanted to put it out here :wave:
