### ISSUE TITLE
Icon not showing properly on Openbox

### ISSUE THREAD

**Issue by hrqmonteiro** [jwilm/alacritty#2166]
Which operating system does the issue occur on? Arch

If on linux, are you using X11 or Wayland? X11

I noticed that no matter what i do, the alacritty doesn't show with the "utilities-terminal" which is written on the .desktop file config, neither any other icon, even the default icon openbox uses (which is on /usr/share/pixmaps and also shows on some electrons applications i have, like SimpleNote, is not used for Alacritty), it only shows a default icon everywhere, like my taskbar, my app switcher and so on. Is there anything i can do, is this only happening here? Pic above of the blank icon on tint2 with alacritty open on taskbar. (the middle one, ofc)

![2019-03-09-034253_126x50_scrot](https://user-images.githubusercontent.com/17055027/54067328-6e170d00-421d-11e9-80d5-655349e3f8a0.png)

EDIT: added the app switcher, so i guess the problem is not on tint, just something with alacritty and gtk icon not working around properly, i think

![2019-03-09-034555_1920x1080_scrot](https://user-images.githubusercontent.com/17055027/54067387-1f1da780-421e-11e9-97b4-352eaf67ddec.png)

**Comment by chrisduerr** [comment]
This sounds like you might have installed the desktop file improperly. Did you follow the instructions provided in the INSTALL.md?

**Comment by hrqmonteiro** [comment]
On arch it already provided a desktop file with the installation of the alacritty package

**Comment by hrqmonteiro** [comment]
> This sounds like you might have installed the desktop file improperly. Did you follow the instructions provided in the INSTALL.md?

On arch it already provided a desktop file with the installation of the alacritty package

**Comment by chrisduerr** [comment]
Alacritty has no control over the Alacritty version distributed by Archlinux. If you want to make sure this is an issue with Alacritty, please try following the steps described in the INSTALL.md.

If this can't be reproduced by following the official install instructions, this should be reported to the Archlinux bugtracker.

**Comment by hrqmonteiro** [comment]
> Alacritty has no control over the Alacritty version distributed by Archlinux. If you want to make sure this is an issue with Alacritty, please try following the steps described in the INSTALL.md.
> 
> If this can't be reproduced by following the official install instructions, this should be reported to the Archlinux bugtracker.

Well i uninstalled the version from the official arch package and then i installed the alacritty-git from the aur just to see that for a reason this one could have no problem with the icon, then it happened again, so then i builded manually as you said, following the instructions from the Install.md and then the bug happened again, still has no icon..

For a matter of comparison, the urxvt i have installed used the "Icon=utilities-terminal" on the .desktop file, as the .desktop file from alacritty build uses too, but just alacritty shows the blank icon, so i guess the problem can lie there, idk

**Comment by chrisduerr** [comment]
Does the `/usr/share/applications` directory contain the `alacritty.desktop` file?

**Comment by hrqmonteiro** [comment]
> Does the `/usr/share/applications` directory contain the `alacritty.desktop` file?

Yes. Actually the desktop file is only there and nowhere else, like /.local/share/applications or whatever

**Comment by E5ten** [comment]
This is the same as #1591
