### ISSUE TITLE
Interpretation of "private" CSI diverges from other terminals.

### ISSUE THREAD

**Issue by textshell** [jwilm/alacritty#2171]
Please don't threat CSI sequences with "private use" (<, = , >, ?) chars the same as sequences without with the same final character.

These are code space extensions and often have quite different functions. Interpreting them the same as the sequence without will create glitches and confuse applications. The same applies to the intermediates (` !\"#$%&'()*+,-./`).

Properly ignoring unknown sequences is essential for the ongoing terminal ecosystem evolution as new sequences are allocated.

The current code in ansi.rs: `csi_dispatch` seems to get both these sequence parts in `intermediates` but mostly ignores them, except for select cases.

The following is based on information of the sequences interpreted by xterm, vte/gnome-terminal, konsole and rxvt-unicode. Also see my ongoing [documentation project](https://terminalguide.netlify.com/seq/) for further details.

I think for the currently implemented sequences the only ones that should trigger with an non empty `intermediates` are:
* `J` and `K` for `intermediates` exactly `?`. Strictly this is for protected cells, but it's commonly implemented on terminals that don't actually implement protected cells (if protected cells are not supported it behaves like the non `?` version)
* And of course `h` and `l` for `intermediates` exactly `?`. Similar to what alacritty currently does.
* possibly `n` for `intermediates` exactly `?`. The expected behavior here is different from the not `?` versions and alacritty should either ignore them or properly implement this different behavior. alacritty currently only supports 5 and 6 so a proper implementation can just add a additional `?` in the output for the dec private variants.
* `q` should set cursor style only when `intermediates` is exactly ` ` (space). Without it's a different sequence understood by xterm (and DEC compatible terminals; DECLL).

Currently i think the following claimed sequences are misinterpreted:
```
ESC [ Ⓝ ␣ @  	Scroll Left
ESC [ Ⓝ ␣ A  	Scroll Right
ESC [ > Ⓝ T  	Unset Title Mode
ESC [ > Ⓝ c  	Secondary Device Attributes
ESC [ = Ⓝ c  	Tertiary Device Attributes 
ESC [ Ⓝ ␣ d  	Unset Tab Stop
ESC [ > Ⓝ ; Ⓝ m  	xterm keyboard mode configuration
ESC [ ? Ⓝ n  	private Device Status Report (different expected response)
ESC [ Ⓝ q  	Load LEDs (DECLL)
ESC [ Ⓝ * q  	DEC secure reset
ESC [ Ⓝ " q  	Select Character Protection Attribute (DECSCA)
ESC [ ? Ⓝ s  	Save Mode
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ $ r  	Change attributes in rectangular area 
ESC [ Ⓝ ␣ u  	Set Margin Bell Volume
```
But in the future there are a lot more that have different meanings with non empty `intermediates`
```
ESC [ ? W  	Set Tab At Every 8 Columns
ESC [ Ⓝ $ p  	Request Mode
ESC [ Ⓝ + p     DEC secure reset
ESC [ ? Ⓝ $ p  	Request Private Mode
ESC [ > Ⓝ p  	Change Mouse Pointer Auto Hide
ESC [ ! p  	Soft Reset
ESC [ ? Ⓝ r  	Restore Mode
ESC [ ? Ⓝ t  	Toggle Mode
ESC [ > Ⓝ t  	Set Title Mode
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ $ t  	Reverse Attributes in Rectangular Area
ESC [ Ⓝ ␣ t  	Set Warning Bell Volume
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ $ v  	Copy rectangular area
ESC [ Ⓝ $ w  	Request Presentation State Report
ESC [ 1 $ w  	Request Cursor Information Report
ESC [ 2 $ w  	Request Tab Stop Report
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ' w  	DEC Locator
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ $ x  	Fill Rectangular Area
ESC [ Ⓝ * x  	Select Attribute Change Extent
ESC [ Ⓝ # y  	Setup checksum parameters
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ * y  	Request Checksum of Rectangular Area
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ $ z  	Erase Rectangular Area
ESC [ Ⓝ ; Ⓝ ' z  	DEC Locator
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ $ {  	Selective erase rectangular area
ESC [ Ⓝ # {  	SGR Push
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ ' {  	DEC Locator
ESC [ Ⓝ $ |  	DECSCPP
ESC [ Ⓝ ; Ⓝ ; Ⓝ ; Ⓝ # |  	Report SGR Rectangle
ESC [ Ⓝ * |  	DECSNLS
ESC [ Ⓝ ' |  	DEC Locator
ESC [ # }  	SGR Pop State
ESC [ Ⓝ ' }  	Insert Column
ESC [ Ⓝ ' ~  	Delete Column
```

**Comment by chrisduerr** [comment]
Thanks for going into so much detail about the issue. It sounds like a very sane suggestion though I'd have to look into it myself to get a full grasp of the issue at hand.

**Comment by textshell** [comment]
Any news on this? Anything i can do to help this along?

**Comment by chrisduerr** [comment]
While I think I understand the general situation, it's hard for me to judge what exactly needs to be done to resolve this.

I'm also not aware of any serious bugs this *currently* causes in the wild.

Because of this other issues have had priority for now. The best way to help is obviously always to contribute, but I don't expect that from anyone. Other than that this will just have to wait until I can get around to it.

**Comment by textshell** [comment]
I don't have much clue about rust. So i'm reluctant to open a PR, because i expect whatever i come up would be highly unidiomatic. 

Basically csi_dispatch in ansi.rs would need to include `intermediates` in addition to `action` in the matching. With almost all matches only triggering if `intermediates` is empty.

The 'q' match would need to be modified to match on `action == 'q' && intermediates == [' ']`.
The matches for 'l' (reset mode) and 'h' (set mode) would need to work with both `intermediates == []` and `intermediates == ['?']` but the modes are different namespaces (i.e. `\e[12h` is [send receive mode](https://terminalguide.netlify.com/mode/12/) while `\e[?12h` is [cursor blinking mode](https://terminalguide.netlify.com/mode/p12/))

I think alacritty might work with just those sequences. One step more would be to think about the other combination from my start post and thinking about what alacritty should respond to "Secondary Device Attributes" (`\e[>c`).

If you want to see which sequences (`action` + `intermediates`) other terminals support the documentation for vte (gnome-terminal, etc) at https://terminalguide.netlify.com/seq/ is fairly complete (all toplevel CSI sequences are listed and most have a description).

I'm happy to help reviewing a possible PR for this, or course.

I'm not sure if this currently causes bugs in the wild, i would expect software that does terminal identification based on responses to get confused by getting a "Primary Device Attributes" when asking for "Secondary Device Attributes". The library i'm working with certainly does.
