### ISSUE TITLE
can't input chinese characters in tmux with alacritty

### ISSUE THREAD

**Issue by YUFENGWANG** [jwilm/alacritty#2173]
Which operating system does the issue occur on?
mac os, latest version 

when I'm tying, and i get this 
![image](https://user-images.githubusercontent.com/12859005/54249458-3ee50080-457b-11e9-8156-9c303ba2b2b6.png)

**Comment by YUFENGWANG** [comment]
my font problem, closed.

**Comment by imkundev** [comment]
Same problem,How to fixed this?

**Comment by YUFENGWANG** [comment]
@imkundev set your terminal font
