### ISSUE TITLE
ScrollPageUp/Down scrolls more than a page

### ISSUE THREAD

**Issue by dnkl** [jwilm/alacritty#2174]
> Which operating system does the issue occur on?

Linux/x64

> If on linux, are you using X11 or Wayland?

https://github.com/swaywm/sway/commit/acdb4ed7a32a7cefd4ac37190ba65d33d752bee0 (wayland)

Scrolling up/down a page (key bound to `ScrollPageUp`/`ScrollPageDown`) now scrolls more than a page at a time (by a fair amount of lines).

This is on https://github.com/jwilm/alacritty/commit/0b9ae4ce936dfafbf5ea1929a170c97391cdea0b. I didn't see this on 0.2.7.1089, and I assume this is an unintentional regression?

**Comment by dnkl** [comment]
Sorry about the edits. I hit enter by mistake...

**Comment by dnkl** [comment]
I might be able to bisect tomorrow, unless someone already knows the cause.

**Comment by chrisduerr** [comment]
Does this happen with the default configuration file?

**Comment by dnkl** [comment]
No it does not. However, with this patch it **does**:
```diff
--- alacritty.yml.original	2019-03-13 19:54:08.312956597 +0100
+++ alacritty.yml	2019-03-13 20:38:30.375463534 +0100
@@ -490,7 +490,7 @@ key_bindings:
   - { key: End,      mods: Alt,     chars: "\x1b[1;3F"                       }
   - { key: End,                     chars: "\x1bOF",        mode: AppCursor  }
   - { key: End,                     chars: "\x1b[F",        mode: ~AppCursor }
-  - { key: PageUp,   mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
+  - { key: PageUp,   mods: Shift,   action: ScrollPageUp,                    }
   - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~",     mode: Alt        }
   - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                       }
   - { key: PageUp,   mods: Alt,     chars: "\x1b[5;3~"                       }
```
The other PageUp-bindings doesn't seem to affect this; keeping them or removing them makes no difference. Removing `mode: ~Alt` from the first one is enough to trigger it.

**Comment by chrisduerr** [comment]
Is this inside of tmux?

**Comment by dnkl** [comment]
No, just alacritty (running zsh, if that somehow matters)

**Comment by chrisduerr** [comment]
Then I don't see how changing that binding would make a difference. Unless you're not running the latest version of Alacritty.

**Comment by dnkl** [comment]
Me neither. But latest it is (except your text reflow commit ~2h ago...). But it is 100% reproducable; I just tried it again with a fresh copy of the default `alacritty.yml`.

I'm fine with closing this; I've updated my key bindings to the latest and greatest anyway.

**Comment by chrisduerr** [comment]
What happens if you launch Alacritty with `alacritty --config-file /dev/null`? And how much does it scroll exactly?

I can't reproduce this and the `~Alt` mode just checks that you're not in the alternate screen. So the only way that wouldn't work is if you're in the alternate screen for some reason, which would mean you're not just sitting in zsh but in some kind of editor/pager/multiplexer.

**Comment by dnkl** [comment]
> What happens if you launch Alacritty with alacritty --config-file /dev/null? And how much does it scroll exactly?

This behaves just like the default `alacritty.yml` - it scrolls **exactly** one page (meaning, if I ScrollPageUp, and then down **one** line, I see the line that was at the top before the ScrollPageUp).

I'm definitely sitting on a zsh prompt; I'm just doing `ls /usr/bin` when testing this.

**Comment by chrisduerr** [comment]
> This behaves just like the default alacritty.yml - it scrolls exactly one page (meaning, if I ScrollPageUp, and then down one line, I see the line that was at the top before the ScrollPageUp).

So everything's working fine?

If you add a second mapping to trigger on Shift+ScrollPageUp, it will scroll by two pages. If you don't want that, you should remove the duplicate mapping.

**Comment by dnkl** [comment]
Everything's working fine with the default conf, and no conf.

> If you add a second mapping to trigger on Shift+ScrollPageUp, it will scroll by two pages. If you don't want that, you should remove the duplicate mapping.

Well, even if I only have a single mapping for _any_ key + `PageUp`, it scrolls too much if I remove `mode: ~Alt`

**Comment by chrisduerr** [comment]
That's because you're adding a second binding. All bindings in the default config are added by default, if they are present there or not.

This should be documented in the config too, including how to unmap default bindings. To do that you need to map them to the action `None` and they will not trigger anymore.

**Comment by pfrenssen** [comment]
Can we reopen this until the documentation is updated?

It is not clear now how to resolve this. I only have one config file and it is in the default location. It only has one entry for `Shift-PageUp`:

```
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp                 }
```

Why is there a default config being used if I only have one config file? How do I map the default binding to `None`?
