### ISSUE TITLE
Completion leaves undeletable characters

### ISSUE THREAD

**Issue by elbaro** [jwilm/alacritty#2178]
Similar to  #2026 

![clip](https://user-images.githubusercontent.com/1851290/54369600-8f627800-46b9-11e9-81f8-6b516d0a9ecd.gif)

`cargo install --git https://github.com/jwilm/alacritty.git` does not have this problem.

But Alacritty.app from this commit has this problem.
```
~/.cargo/git/checkouts/alacritty-de74975f496aa2c0/b1032bc
make app
cp -r target/release/osx/Alacritty.app /Applications/
```

**Comment by chrisduerr** [comment]
This is a duplicate of #1295.

Another related issue with a possible workaround and a ton more information can be found here: https://github.com/jwilm/alacritty/issues/2026

**Comment by elbaro** [comment]
I saw #2026, but any idea why `cargo install` build works without a problem for the same commit?

**Comment by chrisduerr** [comment]
Is that on a different machine? Or with a different prompt? I don't see why that would change anything, I suspect it might just change the environment enough where it is harder to run into the bug?

**Comment by elbaro** [comment]
It turns out the only difference was env `LANG`. Running `/Applications/Alacritty.app/Contents/MacOS/alacritty` directly from the terminal does not inherit env. Adding LANG=..UTF-8 to zshrc fixed the issue.

**Comment by sombrastudios** [comment]
Just a small follow up on this, 
you can find more information about this [here](https://stackoverflow.com/questions/19305291/remnant-characters-when-tab-completing-with-zsh)
