### ISSUE TITLE
Can't render Japanese in tmux and zsh

### ISSUE THREAD

**Issue by hnkz** [jwilm/alacritty#2182]
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | macOS 10.14.2    |
| Rust Version     | rustc 1.33.0-nightly |
| Fonts | Anonymous Pro for Powerline |
|Alacritty| 0.2.9 |
|tmux | 2.8|
|zsh| 5.7.1 |

# Summary
I built Alacritty, tmux, zsh and installed those with Japanese font.
I start Alacritty.app but Japanese and Powerline font don't render.
On the other hand, start Alacritty via command line, success to render.

# Behavior
iTerm
<img width="486" alt="スクリーンショット 2019-03-16 12 58 56" src="https://user-images.githubusercontent.com/21235948/54470623-43651f80-47ee-11e9-9d74-6273f316de42.png">

Alacritty.app
<img width="632" alt="スクリーンショット 2019-03-16 12 59 10" src="https://user-images.githubusercontent.com/21235948/54470618-3c3e1180-47ee-11e9-8bcd-388f9aa74fa6.png">

./alacritty
<img width="644" alt="スクリーンショット 2019-03-16 13 05 34" src="https://user-images.githubusercontent.com/21235948/54470620-3fd19880-47ee-11e9-820e-3c71af7cf59c.png">

**Comment by chrisduerr** [comment]
Do these fonts get displayed correctly when using the default macOS font?

**Comment by hnkz** [comment]
Yes. I tried other fonts but can't.

**Comment by lambdalisue** [comment]
I'm using the following and started Alacritty.app directly but I don't have any issue for rendering Japanese. fyi.

- Font: Liberation Mono for Powerline
- Mac: 10.14.3
- Alacritty: 0.2.9
- tmux: next-2.9
- zsh: 5.7.1

<img width="519" alt="Alacritty 2019-03-20 20-01-05" src="https://user-images.githubusercontent.com/546312/54679570-f0bb9880-4b4a-11e9-96b2-63244990eadf.png">

**Comment by chrisduerr** [comment]
@hnkz What's your locale, maybe that can give any hints?

**Comment by hnkz** [comment]
@chrisduerr 
Below is a result of locale command in my terminal.
```
LANG="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_CTYPE="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_ALL=
```
I don't know why my app cannot start collectly...

**Comment by chrisduerr** [comment]
Did you download the latest version from github or build the app file yourself? Maybe trying to build it yourself could give some insights.

**Comment by lalala** [comment]
Try running tmux with the -u flag.

**Comment by idl3** [comment]
I can verify that running `tmux -u` solved my Unicode font rendering issues (not just for Japanese fonts)
