### ISSUE TITLE
Vim/Tmux not taking the full size of the window

### ISSUE THREAD

**Issue by MarioRicalde** [jwilm/alacritty#2183]
Which operating system does the issue occur on?
MacOS 10.14.3

Please look at the following screenshot:

![image](https://user-images.githubusercontent.com/125900/54470697-1ecb6200-4772-11e9-83ba-bd89d7baa096.png)

The green is the color of the terminal and vim has a different color to make it pop out more. 

As you can see there's a border to the right and bottom. This doesn't seem to happen on iTerm.

**Comment by chrisduerr** [comment]
If there is not enough space for another cell, the additional content has to be filled with something.

If it is desired that the additional content is spread evenly, there's a configuration setting for that in the config file.
