### ISSUE TITLE
Refresh problem on release build

### ISSUE THREAD

**Issue by JCavallo** [jwilm/alacritty#2188]
Which operating system does the issue occur on?  Linux (Ubuntu 18.04)

If on linux, are you using X11 or Wayland? X11

Maybe similar to https://github.com/jwilm/alacritty/issues/546

When typing commands in the terminal, I noticed that sometimes, the character I typed  will not be displayed until I type the next one. Sometimes this will only show the previous character, sometimes it will display both.

This only appears on the "release" build, the "debug" one looks fine.

I switched from 0.2.3 (was fine) to master / 0.2.9 (problem appears on both)

rustc 1.31.1 (b6c32da9b 2018-12-18)

Edit : Actually, I have the same behavior as described in https://github.com/jwilm/alacritty/issues/540

**Comment by chrisduerr** [comment]
> Edit : Actually, I have the same behavior as described in #540

Closing as duplicate.

**Comment by chrisduerr** [comment]
Note that if you find a specific commit which broke this for you, that would probably help with troubleshooting. Though #540 was reported even before 0.2.3.

**Comment by JCavallo** [comment]
Well in 0.2.3 I did not notice any problem running the release version.

I will maybe take some time to see which commit made the problem appear on my machine, that could give us a hint.

**Comment by chrisduerr** [comment]
Thanks, being able to pinpoint a specific commit would likely help a lot.

**Comment by JCavallo** [comment]
Okay so I think I actually misunderstood the behavior of `cargo install` and assumed that it would build with `--release` where indeed it would not.

So I think I was using the debug target all along, sry...

**Comment by chrisduerr** [comment]
No worries, thanks for letting me know.
