### ISSUE TITLE
Tab characters are not output, at least for copying

### ISSUE THREAD

**Issue by colindean** [jwilm/alacritty#219]
I tweeted about display time, [praising Alacritty for being faster to display than iTerm2](https://twitter.com/colindean/status/817881616198537216). Way to go!

But in the process, identified a bug: tab characters are copied as spaces. See the tweet linked above and its replies for the thoughts.

I reproduced it more simply here:

```
# iterm2
$ echo -e "[\t\t\t\t]"
[				]

#alacritty
$ echo -e "[\t\t\t\t]"
[       ]
```

I retrieved the above output by highlighting from the `$` to the `]` as displayed by each terminal emulator. iTerm2 is allowing the copy of 4 tab characters. Alacritty is outputting _7_ spaces?

I'm using Alacrity at 61389c1 on macOS 10.11 using what is the default settings, but with font changed to Menlo and the Solarized theme uncommented.

#106 could be related because it demonstrates some tab weirdness.

**Comment by zethra** [comment]
This is working for me on Arch Linux running the AUR package version `0.1.0.569.g4e9b1c5-1`

**Comment by colindean** [comment]
Still not working for me as of 59b561b.

I check this by executing

    echo -e "tab\ttab"

in iTerm2 and Alacritty, and then copypasting the output after `echo` and appending `| wc -c`.

    echo "tab     tab" | wc -c

If tab is spaces, then it'll be 12. If it's a tab, it'll be 8.

**Comment by nixpulvis** [comment]
Hmmm, interesting. I believe I can reproduce this as well.

**Comment by Rizhiy** [comment]
@chrisduerr There appears to be a regression on this.
Just tested with Ubuntu 20.04.
Alacritty installed from cargo: `alacritty 0.11.0`

**Comment by chrisduerr** [comment]
I can copy tabs just fine. Make sure you're not running tmux or anything else sitting in-between PTY and Alacritty.

**Comment by Rizhiy** [comment]
Hmm, indeed. I'm running `tmux`, any idea how that can be fixed?

**Comment by chrisduerr** [comment]
That's up to tmux really, which I do not use.
