### ISSUE TITLE
Wrong key binding to decrease font size on Gnome 3.32

### ISSUE THREAD

**Issue by krobelus** [jwilm/alacritty#2190]
After upgrading from Gnome 3.30 to 3.32, the default keybinding (shown below) for `DecreaseFontSize` does not work anymore:
 `{ key: Subtract, mods: Control,       action: DecreaseFontSize }`

If I change the binding to  `key: Minus` then it works just fine.

I'm not sure what exactly caused the issue, but having both bindings on Linux by default seems like an easy fix for now.

> Which operating system does the issue occur on?

Arch linux
> If on linux, are you using X11 or Wayland?

Wayland

**Comment by chrisduerr** [comment]
This is fixed on the latest master.
