### ISSUE TITLE
Default colors for bash on windows make directories really hard to read

### ISSUE THREAD

**Issue by lukeschlather** [jwilm/alacritty#2198]
Which operating system does the issue occur on? Windows 10

On windows all directories in bash have the drwxrwxrwx permission, which makes them render in this very low-contrast greenish-yellow on greenish blue. I'm looking into other color schemes but having something higher contrast out of the box would be nice.

![image](https://user-images.githubusercontent.com/184099/54716648-6d328500-4b13-11e9-9e96-b0d684cc6577.png)

**Comment by chrisduerr** [comment]
You can change the colors in the default configuration file.

**Comment by lukeschlather** [comment]
Just in case anyone else finds this, my problem wasn't actually the color scheme. My problem was that on Windows, alacritty starts up in Powershell by default. The bash.exe that it executes when I run bash from within alacritty is C:\Windows\System32\bash.exe (which might be the WSL bash? I'm not sure.) 

I really wanted to run C:\Program Files\Git\bin\bash.exe which treats NTFS directories as drwxr-xr-x.

**Comment by chrisduerr** [comment]
You can also set your directory colors by setting the `LS_COLORS` env variable (you'll probably find plenty of resources for that online).
