### ISSUE TITLE
Ctrl-K and Up have same scancode on Mac

### ISSUE THREAD

**Issue by orlandoc01** [jwilm/alacritty#2204]
Which operating system does the issue occur on?
Mac 1.14.3

**Background**: I'm considering switching over from iTerm2 to Alacritty. One of the key plugins though for my current workflow uses the [Vim Tmux Navigator](https://github.com/christoomey/vim-tmux-navigator) plugin across Vim and Tmux. With these tools, I use the following keys:
  `Ctrl-J` -> move down one pane
  `Ctrl-K` -> move up one pane
   `Up`      -> go up one command in my history
   `Down` -> Nothing right now

**Setup**: Now, when I try to set this up in Alacrity, it seems like Alacritty can't distinguish beween `Ctrl-J` and `Down` and `Ctrl-K` and `Up`. As a result, the above key combinations don't work with the plugin, and pressing either `Ctrl-K` or `Up` both just go up one command (default behavior of `Up` key as described above)

When I run alacrity with --print-events, both the `Ctrl-J` combination and the `Down` key result in the same value.

```
[INFO] glutin event: WindowEvent { window_id: WindowId(Id(140343609730912)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 125, state: Released, virtual_keycode: Some(Down), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```
And similar output is shown with both `Ctrl-K` and `Up` yielding 126 as the scancode.

I first tried this binding:
```
  - { key: K,  mods: Control, chars: "\x0b"  } 
```
but I could never trigger this event. 

I then tried the following binding. After using `xxsd`, I managed to get the chars seen by iTerm and tried the following mapping:
```
  - { key: Up,  chars: "\x0b"  } 
```
This then sends the correct command to Tmux (move up a pane) but it *also* goes up one command in the same pane, indicating both are still present.

**Question**: How can I distinguish (and make work) the `Ctrl-K`, `Ctrl-J`, `Up`, and `Down` keys for my setup?

**Comment by chrisduerr** [comment]
> When I run alacrity with --print-events, both the Ctrl-J combination and the Down key result in the same value.

That sounds extremely odd, I was initially thinking your issue is with your shell and you've got a keyboard shortcut setup there, but it sounds like you've actually got some weird system setup going on.

Do you have anything like a custom keyboard shortcut program running or an unusual keyboard layout?

**Comment by orlandoc01** [comment]
Oh you're totally right. I'm using [khd](https://github.com/koekeishiya/khd), a modal key hot daemon, and I totally forgot about this section.

```
# vi-mode for non-terminal applications
# remap left-control h/j/k/l -> arrow keys
lctrl - h         ![HyperTerm,Terminal,iTerm2]      :   khd -p "- left"
lctrl - j         ![HyperTerm,Terminal,iTerm2]      :   khd -p "- down"
lctrl - k         ![HyperTerm,Terminal,iTerm2]      :   khd -p "- up"
lctrl - l         ![HyperTerm,Terminal,iTerm2]      :   khd -p "- right"
```
Added Alacritty above and it works great. Thanks so much for the help!
