### ISSUE TITLE
Color Rendering Issues

### ISSUE THREAD

**Issue by sabrehagen** [jwilm/alacritty#2205]
On Ubuntu 18.04 with X11, I notice line colors sometimes corrupt. I can't create a repro though. See screenshot for example (if you are on a screen with low contrast ratio you will need to look closely).

![image](https://user-images.githubusercontent.com/1094600/54858928-e6241d80-4d5b-11e9-8bef-281987a17e74.png)

**Comment by chrisduerr** [comment]
Does this still happen when setting your prompt to something simpler (like `$`)?

The issue might be that the background color is set, but never properly reset again.

**Comment by sabrehagen** [comment]
> The issue might be that the background color is set, but never properly reset again.

I believe this is the case. Is there a simple fix to remedy this?

**Comment by chrisduerr** [comment]
Add `\e[0m` to the end of your prompt.

**Comment by sabrehagen** [comment]
Is `\e[0m` equal to `%{$resetcolor%}`? That's at the end of my prompt currently.

**Comment by chrisduerr** [comment]
It should be equal to it assuming that it works properly. Have you been able to confirm that your issue is fixed by setting the prompt to something simple like `$`?

**Comment by sabrehagen** [comment]
When the issue presents again, I will `export PROMPT=$` and see if the issue clears.

On a fresh shell, there is no issue with the background color. I've only witnessed it after another program has written output to the terminal, and only once every few days at that. Once this happens, commands that previously render without issue (e.g. `ls -l`) reliably render with the issue above.

**Comment by chrisduerr** [comment]
> I've only witnessed it after another program has written output to the terminal, and only once every few days at that.

That's a pretty interesting thing to point out and significantly changes the assumptions I've made until now. That definitely means that your prompt should be irrelevant and exporting a simpler one will not help.

I'd be curious what kind of commands cause this? Is it something odd like `cat /dev/urandom` which is likely to corrupt terminal state or is it something relatively 'normal'? Also does running `reset` fix things?

**Comment by sabrehagen** [comment]
I just encountered another instance of this. I typed `man cat` which produced this page. Exiting `less` and re-running `man cat` cleared the issue. Still confusing.

![image](https://user-images.githubusercontent.com/1094600/55666807-88d1b580-589f-11e9-81eb-52803c4cb810.png)

**Comment by sabrehagen** [comment]
Running `cat /dev/urandom` didn't cause the issue. The "normal" case above did though.

**Comment by sabrehagen** [comment]
> Is it something odd like cat /dev/urandom which is likely to corrupt terminal state

Running `cat /dev/urandom` caused no corruption for me.

> or is it something relatively 'normal'?

As per the `cat` manpage above, it seems to happen on relatively normal output.

> Also does running reset fix things?

In my experience, yes.

**Comment by sabrehagen** [comment]
Found this is present in other terminals than `alacritty`. Good news for you! :)

I also found that running `reset` does not always fix the issue.
