### ISSUE TITLE
Runtime error: Conpty assertion panic

### ISSUE THREAD

**Issue by notlmn** [jwilm/alacritty#2206]
Whenever I close Alacritty the following error pops us. Not a world ending situation but good to look into.

![image](https://user-images.githubusercontent.com/37769974/54866517-c3652980-4d9a-11e9-81e6-c1804cd2eecc.png)

OS: Windows 10 1809, with experimental conpty enabled

**Comment by chrisduerr** [comment]
This was fixed in https://github.com/jwilm/alacritty/pull/2123.

**Comment by notlmn** [comment]
Oh, awesome!
