### ISSUE TITLE
Cursor has different dimensions depending on shape

### ISSUE THREAD

**Issue by anowlcalledjosh** [jwilm/alacritty#2209]
This is probably best demonstrated with a picture:

![image](https://user-images.githubusercontent.com/9433472/54887059-9beb8b00-4e86-11e9-802d-b41382a6a5c4.png)

With the hollow cursor, there's a 2-pixel gap between the top of the cursor and the edge of the cell.

Interestingly, the size of the gap appears to stay at 2 pixels even with an increased font size (36 instead of 12):

![image](https://user-images.githubusercontent.com/9433472/54887098-0bfa1100-4e87-11e9-8fa7-8e12f9c29a9d.png)

It also happens with the vertical bar cursor (which I hadn't noticed until I increased the font size!):

![image](https://user-images.githubusercontent.com/9433472/54887085-ecfb7f00-4e86-11e9-85d1-9f573221d593.png)

Ubuntu 18.04, X11, Alacritty 0.2.9 and still present on latest master (3e36d714fec8139a1e506036a394b343bd1a8bb4)

**Comment by chrisduerr** [comment]
I'd assume that these issues are only present with the hollow and I-Beam cursors, right? So the underline and block are both correct?

**Comment by anowlcalledjosh** [comment]
Yep, underline and block cursors both look fine.

**Comment by chrisduerr** [comment]
@anowlcalledjosh Do you have a font offset set? I think that might be the cause of this.

**Comment by anowlcalledjosh** [comment]
I do! Changing the offsets doesn't appear to affect the height or width of the hollow cursor, or the height of the beam cursor, so I think you're right.

```yaml
  offset:
    x: 0
    y: 2
```

**Comment by anowlcalledjosh** [comment]
(and so the underline cursor *is* affected, I just didn't have an x-offset specified when I originally tested it)

**Comment by chrisduerr** [comment]
Thanks, I've identified the issues then and am working on a fix. Will update once there's a PR.
