### ISSUE TITLE
Crash when clicking on highlighted URL

### ISSUE THREAD

**Issue by dvergeylen** [jwilm/alacritty#2211]
Which operating system does the issue occur on? **Linux**

If on linux, are you using X11 or Wayland? **X11**

Hi,

I am running 022f0782 and when I click on a link inside vim, alacritty closes abruptly and outputs:

```bash
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 241 requests (241 known processed) with 0 events remaining.
```

**Comment by chrisduerr** [comment]
Do you have xclip installed? Can you reproduce this with a previous commit or did this commit introduce the regression? Or has this never worked before?

**Comment by dvergeylen** [comment]
Hi @chrisduerr,

>Do you have xclip installed?

Yes: `xclip/testing,now 0.13-1 amd64  [installed]` (Debian testing)

I tried many revisions trying to bissect the problem but couldn't find a previous working commit. It seems to me it's a dependency problem (cargo taking latest available version of a crate so whatever I choose as a commit revision I still get the bug once compiled).

Do you have any hint of what crate might be failing so I could 'force' some kind of version?

**Comment by chrisduerr** [comment]
Are you running a 32bit system or running the 32bit binary on a 64 bit system?

Does this only happen when launching URLs or does this happen in other cases too?

If you click on links in vim, are you pressing `shift`? Because otherwise this wouldn't open the URL. So just clicking in vim does not break things, right? Or are you using some kind of vim plugin for this?

Can this be reproduced outside of vim at all? In something like `less` or `man` for example?

Is this only with a precompiled binary, or does this issue happen also when compiling Alacritty yourself?

Also if you click on links, are these links in a huge text document or can this be reproduced when the file in vim is *only* a short URL?

Sorry for such a barrage of questions, but hopefully these should help quickly narrow down the issue. Feel free to answer only those you can easily answer so we can quickly get an idea of what might be going on.

**Comment by dvergeylen** [comment]
> Are you running a 32bit system or running the 32bit binary on a 64 bit system?

I am compiling via `cargo build --release` each time, I am on a 64 bit system.

> Does this only happen when launching URLs or does this happen in other cases too?

I though it was vim but actually this happens whenever I click on a url, in a program or not, simply cat test.txt and then clicking on a displayed url makes it crash! 😕

> If you click on links in vim, are you pressing `shift`? Because otherwise this wouldn't open the URL. So just clicking in vim does not break things, right? Or are you using some kind of vim plugin for this?

Crash happens when I use shift or not. I don't use any `vim` plugin.

> Can this be reproduced outside of vim at all? In something like `less` or `man` for example?
Yes, even in the terminal within no other text editor.

> Is this only with a precompiled binary, or does this issue happen also when compiling Alacritty yourself?
I haven't tested with a precompiled binary yet, will do :+1: 

> Also if you click on links, are these links in a huge text document or can this be reproduced when the file in vim is _only_ a short URL?

No, a simple one liner file with a url to let say https://google.com will do it.

> Sorry for such a barrage of questions, but hopefully these should help quickly narrow down the issue. Feel free to answer only those you can easily answer so we can quickly get an idea of what might be going on.

No matter, tell me if I can help / do some further testing!

**Comment by chrisduerr** [comment]
> I though it was vim but actually this happens whenever I click on a url, in a program or not, simply cat test.txt and then clicking on a displayed url makes it crash! confused

That's very odd. Can you get it to crash when clicking on non-url text? Or when selecting text? That would indicate that the clicking itself is the problem and nothing URL related.

If it is URL related then there are two options really. Either it's related to URL parsing, or it's related to launching the URL. You can try setting the `launcher` to `None` (as documented in the config file) and that should disable URL launching. So that would be a good way to test if things still crash in that case.

If this fixes the crash, the next step would be to check if something trivial like `/bin/true` also produces the crash.

**Comment by dvergeylen** [comment]
> > I though it was vim but actually this happens whenever I click on a url, in a program or not, simply cat test.txt and then clicking on a displayed url makes it crash! confused
> 
> That's very odd. Can you get it to crash when clicking on non-url text? Or when selecting text? That would indicate that the clicking itself is the problem and nothing URL related.

It doesn't crash when I click on non-url text, nor when selecting text. I guess it's URL related then :thinking: 

> If it is URL related then there are two options really. Either it's related to URL parsing, or it's related to launching the URL. You can try setting the `launcher` to `None` (as documented in the config file) and that should disable URL launching. So that would be a good way to test if things still crash in that case.

You are right: setting `launcher` to `None` fixes the crash!

> If this fixes the crash, the next step would be to check if something trivial like `/bin/true` also produces the crash.

Setting `launcher` to `/bin/true` makes it crashing again. Having error message homologous to my first post:
```bash
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 200 requests (200 known processed) with 0 events remaining.
```

We are making progress aren't we? Don't hesitate to ask further tests, as I can reproduce this rather easily :+1:

**Comment by chrisduerr** [comment]
> You are right: setting launcher to None fixes the crash!

> Setting launcher to /bin/true makes it crashing again. Having error message homologous to my first post.

That's very interesting, so it must be related to code which is only run when the launcher is enabled, significantly reducing the possible culprits.

Assuming you're not on the latest commit, this can only mean the error is in this part of the codebase:
https://github.com/jwilm/alacritty/blob/master/src/input.rs#L675-L683

I've recently changed the way that daemon processes are launched, so I think the best bet would be to revert that change.

Can you check if 32cb48774ad139c7f4fe9864e28fefeaa1009c79 is a broken commit and if c6ab2a8867ad0d064d67dc5e32138cbb3d3ab833 is working? If that's the case, then something's wrong with the double fork.

**Comment by dvergeylen** [comment]
* c6ab2a8 is working → Yes
* 32cb487 is a broken commit → Yes

**Comment by chrisduerr** [comment]
Can you verify if adding `::libc::setsid();` after [this line](https://github.com/jwilm/alacritty/blob/master/src/util.rs#L102) (before the `Ok(())`) resolves the issue?

**Comment by dvergeylen** [comment]
Hi,

I am afraid it doesn't... 😕

```bash
dv@asusdaniel:/tmp/alacritty$ git status --short
 M src/util.rs
dv@asusdaniel:/tmp/alacritty$ git diff src/util.rs
diff --git a/src/util.rs b/src/util.rs
index 4532d2e..17ae677 100644
--- a/src/util.rs
+++ b/src/util.rs
@@ -100,6 +100,7 @@ pub fn start_daemon<I, S>(program: &str, args: I) -> io::Result<()>
             if ::libc::fork() != 0 {
                 std::process::exit(0);
             }
+            ::libc::setsid();
             Ok(())
         })
         .spawn()?
dv@asusdaniel:/tmp/alacritty$ alacritty # → I do the test here, it crashes
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 184 requests (184 known processed) with 0 events remaining.
```

**Comment by chrisduerr** [comment]
Just one more attempt out of desperation, what happens if you move the `setsid` call *before* the call to fork?

**Comment by chrisduerr** [comment]
Just to shorten the feedback loop a bit, I've got two more things I'd like you to try if moving the setsid does not work.:

```rust
#[cfg(not(windows))]
pub fn start_daemon<I, S>(program: &str, args: I) -> io::Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
{
    Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .before_exec(|| unsafe {
            daemon();
            Ok(())
        })
        .spawn()?
        .wait()
        .map(|_| ())
}

unsafe fn daemon() -> isize {
    match libc::fork() {
        -1 => return -1,
        0 => (),
        _ => std::process::exit(0),
    }

    if libc::setsid() == -1 {
        -1
    } else {
        0
    }
}
```

This creates a 1:1 copy of glibc's daemon method assuming it's called with the parameters `1, 1`, so if daemon doesn't crash, neither should this.

And just to make sure the issue isn't the callsite and the problem is unrelated to redirection of stdout/in/err, this is worth another shot:

```rust
#[cfg(not(windows))]
pub fn start_daemon<I, S>(program: &str, args: I) -> io::Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
{
    Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .before_exec(|| unsafe {
            libc::daemon(1, 1);
            Ok(())
        })
        .spawn()?
        .wait()
        .map(|_| ())
}
```

If you're willing to help with troubleshooting and testing these three things, that would help a lot. Unfortunately everything's working great on my system.

If neither of these give any new insights, I think it would be fine to just revert the code and suppress the deprecation warning, since macos hasn't actually deprecated `daemon` but is just discouraging its use.

**Comment by dvergeylen** [comment]
Hehey good news! :sparkles: 

* Test 1:
>Just one more attempt out of desperation, what happens if you move the setsid call before the call to fork?

Still crash 😕

* Test 2:
```rust
#[cfg(not(windows))]
pub fn start_daemon<I, S>(program: &str, args: I) -> io::Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
{
    Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .before_exec(|| unsafe {
            daemon();
            Ok(())
        })
        .spawn()?
        .wait()
        .map(|_| ())
}

unsafe fn daemon() -> isize {
    match libc::fork() {
        -1 => return -1,
        0 => (),
        _ => std::process::exit(0),
    }

    if libc::setsid() == -1 {
        -1
    } else {
        0
    }
}
```
Still having a crash 😕

* Test 3:
```rust
#[cfg(not(windows))]
pub fn start_daemon<I, S>(program: &str, args: I) -> io::Result<()>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<OsStr>,
{
    Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .before_exec(|| unsafe {
            libc::daemon(1, 1);
            Ok(())
        })
        .spawn()?
        .wait()
        .map(|_| ())
}
```
Works! 😎 No crash at all!

**Comment by chrisduerr** [comment]
> Hehey good news!

Unfortunately this does not mean good news. Test 2 was an attempt from me to reproduce exactly what `libc::daemon(1, 1)` does without having to use the `libc::daemon` call. As far as I can tell this is identical to the code in glibc's `daemon` function, but at this point I'm fine with reverting this change.

Thanks for all the help with debugging this.
