### ISSUE TITLE
OTF font support

### ISSUE THREAD

**Issue by nkantar** [jwilm/alacritty#222]
Alacritty doesn't seem to recognize OTF font files. Example error message:

```
Couldn't find a font with name 'SourceCodePro' and style 'Regular'
```

Is this a known issue, and are there plans to fix it? Thanks!

---

Edit: macOS Sierra 10.12.2, TTF fonts work just fine and dandy.

**Comment by jwilm** [comment]
Hmm... We're just using CoreText for font loading, and I would expect it to support OTF just find. I'm guessing maybe the font you're looking for has a different style or name than you configured. It would certainly be helpful to be able to dump the list that Alacritty sees as available for configuration purposes.

**Comment by N-006** [comment]
On Linux `family: "Source Code Pro"` works fine for me.

**Comment by nkantar** [comment]
@jwilm You were correct—I wasn't using the correct font family and style. Running `fc-scan` (from `fontconfig`) on the font files revealed the correct values and all is well now.

@N-006 I was using the file name for reference instead of the `family` value from the font file metadata.
