### ISSUE TITLE
URL selection mode

### ISSUE THREAD

**Issue by shibumi** [jwilm/alacritty#2227]
Hi, I use Alacritty on Arch Linux. I am missing one feature from termite. In Termite you could open up an `URL selection mode` (CTRL+SHIFT+X). In this mode the terminal will pop up flags on URLs. This way you could press a button for a flag and you will open the URL magically in your browser. I know that I can click on the URL in alacritty, but this mode would be even more handy.
Here is a picture with it: ![https://paste.xinu.at/4qLMQ/](https://paste.xinu.at/4qLMQ/)

**Comment by chrisduerr** [comment]
See #262.
