### ISSUE TITLE
Copy-Paste inop in XUbuntu

### ISSUE THREAD

**Issue by gcplante** [jwilm/alacritty#223]
Unable to user Copy-Paste in XUbuntu.
Tried middle click, ctrl-c, ctrl-v to no avail

**Comment by solowt** [comment]
did you copy the `alacritty.yml` file from the repo root to `~/.alacritty.yml`?

that file contains configuration settings including keybindings.  the default for copy/paste is command-c/command-v.

**Comment by gcplante** [comment]
Yes, in my current user dir, saw theses bindings. Let me know if need more details to reproduce bug, really loved the snappyness!

**Comment by theduke** [comment]
The default is NOT Ctrl-C / Ctrl-V but Super-c / Super-V.

Super = Command on Macs or the Windows key on Win keyboards...

**Comment by sokoow** [comment]
It'd be also cool if there was a right click menu, gnome-terminal style with copy/paste options there.

**Comment by gcplante** [comment]
I second sokoow's comment. Issue might need renaming: Right-click menu feature request.

**Comment by jwilm** [comment]
Right-click menus are not going to happen. It's just too much work for a tiny quality-of-life feature. What's wrong with just having key bindings?
