### ISSUE TITLE
Can't set app_id on wayland

### ISSUE THREAD

**Issue by gaurav712** [jwilm/alacritty#2232]
Which operating system does the issue occur on?
Arch Linux (64-bit, up-to-date)

If on linux, are you using X11 or Wayland?
sway on wayland (sway-git, AUR package)

I tried `alacritty -t cmus -e cmus` to open `cmus` with special `app_id` to be able to do some special stuff with that window but it doesn't work.

**Comment by chrisduerr** [comment]
The `-t` option sets the title, not the appid. Running `alacritty -c cmus` will sett the app id to `cmus`.

**Comment by gaurav712** [comment]
I read the `man` pages.  `-c` woks on `X`-windows. Wayland's windows don't have classes. And one for all, **there's no such option in `alacritty`**. It's `--class`.  
And even if I believe you, It says, `error: Found argument '-c' which wasn't expected, or isn't valid in this context`.
I am not drunk. I didn't **just post it** without any research.

**Comment by snakeroot** [comment]
This needs to be "--class" not "-c".
