### ISSUE TITLE
Is [inline]  doing anything?

### ISSUE THREAD

**Issue by Roger** [jwilm/alacritty#2241]
Since alacritty is using LTO in release binaries, is there any need of having [inline] everywhere?

As far as I understand, the compiler is trying to inline by default (where needed) and adding LTO makes it more aggressive and also cross crate (by default only external inline functions get hinted to the compiler from external crates).

Just tried `sed -i '/#\[inline\]/ d' **/*rs` and testing with vtebench can't see any difference in performance or binary size.

**Comment by chrisduerr** [comment]
That's actually very interesting. I've had the same question previously and after I've removed all `#[inline]` annotations, performance definitely changed.

Looking into this again might be interesting and I think there are two metrics where I'd want some concrete benchmarking examples before accepting any changes.

First we'd have to check the performance of #[inline] with all vtebench benchmarks and potentially some things that currently aren't tested yet. Like decreasing the font size significantly.

The other thing I'd like some benchmarks on is compile-times. In theory we should see a compile-time improvement after removing the inline annotations.

If anyone is interested in looking into this, feel free to let me know what kind of performance results you've gathered.

**Comment by chrisduerr** [comment]
I've looked into this and running the asrw test, removing the `#[inline]` annotations increases the runtime by about 20%.

I've also benchmarked the compile times and removing inline had no effect at all.
