### ISSUE TITLE
Alacritty v0.3.0-rc2 does not start (Error creating GL context)

### ISSUE THREAD

**Issue by doubleloop** [jwilm/alacritty#2243]
Alacritty release: v0.3.0-rc2
OS: Debian GNU/Linux buster/sid x86_64
Kernel: 4.19.0-4-amd64O
DE: GNOME 3.30.2
GPU: NVIDIA Quadro FX 880M
using X11

```
$ alacritty
Created log file at "/tmp/Alacritty-19721.log"
[2019-04-02 14:35] [ERROR] Alacritty encountered an unrecoverable error:

        Error creating GL context; `glXQueryExtensionsString` found no glX extensions
```

## notes: 
* alacritty version v0.2.9 works fine
* `cargo run --example window` works fine when cloned glutin master
* tried both installing from released deb file and building from sources

**Comment by chrisduerr** [comment]
Could you bisect which exact commit broke this for you?

**Comment by doubleloop** [comment]
0f96a62218cfc78b56606f0dcc334d59202edf7c is the first bad commit

Also I chacked last commit (e98ea64c748f1cce673c97adbc72e6a9a3c11e5f) and the same error still occurs.

**Comment by doubleloop** [comment]
I just investigated glutin repo and found that example window do work on master, but it does not work with 0.20 release, the commit that did fix the issue was tomaka/glutin@600030ac41abdb7a03e0ed735a179ea10e249a4f

**Comment by chrisduerr** [comment]
Sounds like it would be beneficial to wait for the next glutin release before releasing 0.3. Thanks for looking into this.

**Comment by chrisduerr** [comment]
@doubleloop I'd be interested in getting feedback on #2253. Does that PR fix the build issues for you?

**Comment by doubleloop** [comment]
Just verified it does not (it produces segfault, I posted stack trace in [PR comment](https://github.com/jwilm/alacritty/pull/2253#issuecomment-480236516)

**Comment by chrisduerr** [comment]
That backtrace is kinda surprising because it fails at the following code:
```rust
    let windowed_context = ContextBuilder::new()
        .with_srgb(srgb)
        .with_vsync(true)
        .with_hardware_acceleration(None)
        .build_windowed(window, event_loop)?;
```

Which is actually before any of Alacritty's OpenGL routines run. So in theory you should be able to repro this with my glutin fork.

Could you take the glutin `window.rs` example and add all these flags (you can test both `with_srgb(true)` and `with_srgb(false)` and report back if you can make the glutin example fail like that?

If it does fail, it would also be interesting which option causes the failure, so removing them until the failure is gone would likely be another good troubleshooting step as follow-up.

**Comment by doubleloop** [comment]
Glutin example segfaults if `with_vsync(true)` is added:
```
iff --git a/glutin_examples/examples/window.rs b/glutin_examples/examples/window.r
index 92cedb7..fab65c3 100644
--- a/glutin_examples/examples/window.rs
+++ b/glutin_examples/examples/window.rs
@@ -7,6 +7,7 @@ fn main() {
     let wb = glutin::WindowBuilder::new().with_title("A fantastic window!");

     let windowed_context = glutin::ContextBuilder::new()
+        .with_vsync(true)
         .build_windowed(wb, &el)
         .unwrap();
```
I tested all other flags and they do not cause any problem. `with_vsync` segfaults both on glutin master and on tomaka/glutin@600030ac41abdb7a03e0ed735a179ea10e249a4f

**Comment by chrisduerr** [comment]
So does removing this from Alacritty allow you to run it again?

**Comment by doubleloop** [comment]
Yes, just checked this.

**Comment by chrisduerr** [comment]
Then I'd propose a temporary workaround for BSD which disables vsync. Does removing vsync cause any issues that would deem Alacritty unusable to you? It wouldn't be worth adding this as a workaround if Alacritty is still unusable though technically working.

**Comment by doubleloop** [comment]
> a temporary workaround for BSD
I use debian

>Does removing vsync cause any issues
I can not observe any, alacrity is fully usable for me.

**Comment by chrisduerr** [comment]
Oh, sorry. For some reason I confused this issue with https://github.com/jwilm/alacritty/issues/2244.

I'm not entirely sure why vsync was enabled since I can't reproduce any errors of the original commit message, so I'm not sure if I want to make this change before the 0.3.0 release. It's also possible that it might have impact on performance and resource usage, the latter being difficult to benchmark for me.

**Comment by chrisduerr** [comment]
Reported upstream in https://github.com/tomaka/glutin/issues/1135.

**Comment by Bad3r** [comment]
I just encountered this issue on Arch Linux `5.7.5-arch1-1`
```
$ alacritty 
Created log file at "/tmp/Alacritty-210538.log"
[2020-06-26 07:32:58.968605364] [ERROR] Alacritty encountered an unrecoverable error:

	Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`
```

**Comment by bhayward93** [comment]
@Bad3r me too on Ubuntu. 

![image](https://user-images.githubusercontent.com/18596813/85859732-8960af80-b7b5-11ea-8e15-799763f7a5ee.png)

@chrisduerr

**Comment by caioaao** [comment]
same thing on pop os after upgrading some packages (don't remember which ones)

alacritty version:

```
[~]$ alacritty --version                                                                                                                                                                                                                                                                                                     
alacritty 0.4.3
```

**Comment by bhayward93** [comment]
I have also noticed that the issue has resolved; thought I had rebooted but maybe not.

**Comment by JanSurft** [comment]
This issue happens to me on every upgrade of some graphic specific package on my system, although I didn't determine which one it is yet.

As alacritty leverages GPU capabilities, it is likely some cuda or nvidia package upgrade... Today I upgraded the below listed packages and had to restart the system for alacritty to start again, after the above mentioned error `Error creating GL context; Received multiple errors. Errors: [OsError("eglInitialize failed"), OsError("GL context creation failed")]` appeared.

```
bbswitch-0.8-365
bctoolbox-4.4.10-1
botan-2.17.2-1
c-ares-1.17.1-1
fmt-7.1.2-2
glibmm-2.64.4-1
intel-ucode-20201118-1
lib32-libjpeg-turbo-2.0.6-1
lib32-libx11-1.7.0-1
lib32-mesa-20.2.3-1
lib32-nvidia-utils-455.45.01-1
libakonadi-20.08.3-2
libimagequant-2.13.1-1
libqtxdg-3.6.0-2
libraqm-0.7.1-1
librsvg-2:2.50.2-1
libx11-1.7.0-1
libxkbcommon-1.0.3-1
libxkbcommon-x11-1.0.3-1
libxnvctrl-455.45.01-1
linux-5.9.10.arch1-1
linux-headers-5.9.10.arch1-1
lsof-4.94.0-1
mesa-20.2.3-1
mpv-1:0.33.0-2
nvidia-455.45.01-2
nvidia-settings-455.45.01-1
nvidia-utils-455.45.01-1
opencascade-7.5.0-2
opencl-nvidia-455.45.01-1
opensubdiv-3.4.3-4
openxr-1.0.12-1
sdl_image-1.2.12-7
uranium-4.7.1-4
vulkan-intel-20.2.3-1
vulkan-mesa-layers-20.2.3-1
webkit2gtk-2.30.3-1
xorg-server-1.20.9.r21.g5c400cae1-2
xorg-server-common-1.20.9.r21.g5c400cae1-2
xorg-server-xephyr-1.20.9.r21.g5c400cae1-2
xorg-xprop-1.2.5-1
```

I will come back after the next breaking upgrade and likely narrow down the involved packages with an intersection.

**Comment by ojsl1** [comment]
Unfortunately this is still happening with nvidia drivers – just finished a ~500MB system upgrade (Arch Linux) and was greeted with alacritty not launching. I've recently migrated from nvidia-390xx legacy drivers to nvidia-470xx legacy drivers (for vulkan support) and this was the first time I had an upgrade with the new drivers, i don't remember ever seeing this behavior with the nvidia-390xx drivers.

Packages (+nvidia) matching to the above mentioned ones:
`[2021-12-17T16:43:44+0200] [ALPM] upgraded lib32-libx11 (1.7.2-1 -> 1.7.3.1-1) 
[2021-12-17T16:43:44+0200] [ALPM] upgraded lib32-mesa (21.2.5-1 -> 21.3.1-1) 
[2021-12-17T16:43:46+0200] [ALPM] upgraded linux (5.15.7.arch1-1 -> 5.15.8.arch1-1) 
[2021-12-17T16:43:49+0200] [ALPM] upgraded linux-headers (5.15.7.arch1-1 -> 5.15.8.arch1-1) 
[2021-12-17T16:43:38+0200] [ALPM] upgraded mesa (21.2.5-1 -> 21.3.1-1) 
[2021-12-17T17:07:46+0200] [ALPM] upgraded nvidia-470xx-utils (470.86-3 -> 470.94-2) 
[2021-12-17T17:07:46+0200] [ALPM] upgraded nvidia-470xx-dkms (470.86-3 -> 470.94-2) 
[2021-12-17T17:10:25+0200] [ALPM] upgraded lib32-nvidia-470xx-utils (470.86-1 -> 470.94-1) 
[2021-12-17T16:43:37+0200] [ALPM] upgraded xorg-server (21.1.1-3 -> 21.1.2-1) 
[2021-12-17T16:43:37+0200] [ALPM] upgraded xorg-server-common (21.1.1-3 -> 21.1.2-1) 
[2021-12-17T16:43:51+0200] [ALPM] upgraded xorg-server-xephyr (21.1.1-3 -> 21.1.2-1)
`

**Comment by chrisduerr** [comment]
@ojsl1 You probably just need to reboot after a driver update. That's just something you need to do with certain drivers.

**Comment by annymosse** [comment]
it's same issue in  `ubuntu 20.04` using `nix-env` by running: `nix-env -iA nixpkgs.alacritty`, then `alacritty` in your terminal.
[Alacritty's link at nix package](https://search.nixos.org/packages?channel=22.05&show=alacritty&from=0&size=50&sort=relevance&type=packages&query=Alacritty)

**Comment by kchibisov** [comment]
You need GL wrapper for OpenGL stuff with nix outside of nixos. Consult nix docs wrt that.

**Comment by annymosse** [comment]
@kchibisov thanks for your comment, I had fixed my issue after installed the GL wrapper.
