### ISSUE TITLE
Build failure on OpenBSD

### ISSUE THREAD

**Issue by xguerin** [jwilm/alacritty#2244]
> Which operating system does the issue occur on?

OpenBSD 6.5-current

> Problem

`nix:0.12.0` does not compile on OpenBSD. `nix:0.13.0` should, I believe. I tried to force `alacritty` to use the latter but `wayland-client` keeps pulling down the dependency to `0.12.0`. This is probably a layman question, but would there be a way to globally pin `nix` or configure `alacritty` to skip the `wayland-client` dependency, useless on OpenBSD?

Thanks !

**Comment by chrisduerr** [comment]
Going just by semver versions, 0.13.0 is a breaking update compared to 0.12.0 and as a result of that it would be impossible to override the dependency of wayland-client with 0.13.0 since it will be incompatible.

The only way forward if 0.12.0 truly does not build would be to patch wayland-client, which should not be a huge issue if there were no major breaking changes.

In an ideal world, a build failure would be resolved on a patch version which would automatically be pulled in. Unfortunately it doesn't look like nix releases patches.

**Comment by chrisduerr** [comment]
Note that wayland-client has just been bumped to 0.23.1 including a bump of the nix dependency.

In theory that should resolve the problem once Alacritty is updated (which I will do later today). In the meantime feel free to test if this issue is resolved when editing the Cargo.toml yourself.

**Comment by xguerin** [comment]
Thanks for the piece of advice. I tried to force-use the updated wayland client, but `glutin:0.20` is still stuck on `wayland-client:0.21.11` and I could not find an updated for this library ...

**Comment by chrisduerr** [comment]
Oh yeah, if glutin is still a minor or major version behind, that does not help.

**Comment by chrisduerr** [comment]
Note that currently winit is using 0.11 internally. Downgrading Alacritty's `nix` version to `0.11` would likely solve this issue too.

**Comment by chrisduerr** [comment]
Thanks to the cooperation of the wayland-client maintainer, we were able to backport the 0.13 update of nix to the currently used version of winit. This should resolve all build failures with nix on BSD.

Could you confirm that this works for you @xguerin? I've created a PR which updates our dependencies to the required version here:
https://github.com/jwilm/alacritty/pull/2247

**Comment by chrisduerr** [comment]
Note that while the `nix` build failure has been fixed now, `winit` still has a build error on OpenBSD and requires a new release.

**Comment by xguerin** [comment]
Thanks for the great response time 👍

**Comment by chrisduerr** [comment]
No problem. Note that this issue also raises the interesting question of running CI for at least one of the popular BSDs.

I've created a new issue to track this that might be of interest:
https://github.com/jwilm/alacritty/issues/2248

**Comment by chrisduerr** [comment]
@xguerin I'd be interested in getting feedback on #2253. Does that PR fix the build issues for you?

**Comment by xguerin** [comment]
Let me check. I'll let you know ASAP.

**Comment by xguerin** [comment]
My 8GB laptop is chocking on the linking of `cargo build --release`, but all compilation stages passed successfully 👍 I'll bootstrap a beefier VM and try again to confirm.
