### ISSUE TITLE
Panic in liballoc/string.rs

### ISSUE THREAD

**Issue by AdamVig** [jwilm/alacritty#2245]
Which operating system does the issue occur on?
Windows 10.0.17763 Build 17763

Happened twice today on Alacritty 0.2.9 while running Tmux.
```
panicked at 'assertion failed: self.is_char_boundary(new_len)', src\liballoc\string.rs:1134:13
```

**Comment by chrisduerr** [comment]
This is a duplicate of https://github.com/jwilm/alacritty/issues/2231.
