### ISSUE TITLE
DECSTR and RIS does not reset scrolling region

### ISSUE THREAD

**Issue by dnkl** [jwilm/alacritty#2258]
RIS (Reset to Initial State) doesn't reset scrolling marginals (DECSTBM).

This can be triggered/tested by first
```sh
echo -e '\e[10r'
```
This sets the top scroll margin to 10 lines. I.e. top 10 lines doesn't scroll.

Now do
```sh
echo -e '\ec'
```

Or simply:
```sh
echo -e '\e[10r\ec'
```
Most state seems to be reset just fine, but not the scrolling margins.

I checked with a couple of other terminal emulators (urxvt, simple terminal, xterm, gnome-terminal) and they all reset the scrolling margins.

**Comment by dnkl** [comment]
Same issue with DECSTR (soft reset), `\e[!p`

**Comment by chrisduerr** [comment]
> I checked with a couple of other terminal emulators (urxvt, simple terminal, xterm, gnome-terminal) and they all reset the scrolling margins.

Thanks for checking multiple other terminals, that always gives a good comparison of potential differences that are not technically 'incorrect'.

I'd suspect that this isn't super difficult to do but someone likely missed it when implementing these escapes.
