### ISSUE TITLE
Keybinding open -n -a /Application/Alacritty.app not working

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#2259]
We've had a hack for a while on macOS to open multiple windows as a workaround to #607. I dusted of my MBP this morning and found that it's not working. Running the command from a shell in Alacritty works just fine, but the keybinding version causes Alacritty to exit immediately. Seems that this may be a problem with how we create child processes.

If this is a dupe, I blame GitHub search

**Comment by jwilm** [comment]
This seems to fix it, but it's not a 100% solution.

```diff
diff --git a/src/input.rs b/src/input.rs
index 8ce8f2c..555bf60 100644
--- a/src/input.rs
+++ b/src/input.rs
@@ -285,16 +285,24 @@ impl Action {
                 }
             },
             Action::Command(ref program, ref args) => {
+                use ::std::process::Command;
                 trace!("Running command {} with args {:?}", program, args);

-                match start_daemon(program, args) {
-                    Ok(_) => {
-                        debug!("Spawned new proc");
-                    },
-                    Err(err) => {
-                        warn!("Couldn't run command {}", err);
-                    },
-                }
+                Command::new(program)
+                    .args(args)
+                    .spawn().expect("spawn ok")
+                    .wait();
+
+
+
+                // match start_daemon(program, args) {
+                //     Ok(_) => {
+                //         debug!("Spawned new proc");
+                //     },
+                //     Err(err) => {
+                //         warn!("Couldn't run command {}", err);
+                //     },
+                // }
             },
             Action::Hide => {
                 ctx.hide_window();
```

Including a `wait()` here means all commands are blocking, but removing the `wait()` would result in zombies accumulating (#976).

**Comment by chrisduerr** [comment]
I'm using a MBP at work on a regular basis and at least the `SpawnNewInstance` action has worked great for me before.

I'll test this again later just to make sure, but I'd be surprised if it suddenly broke.

**Comment by jwilm** [comment]
I tried that as well; for me, it flashes a new window for fraction of a second. 😞

**Comment by jwilm** [comment]
My MBP is on macOS 10.13... may be part of my `SpawnNewInstance` issue. Haven't looked at the code for it though.

**Comment by chrisduerr** [comment]
I'm using 10.14.3 and just re-tested and `SpawnNewInstance` works great. However running `open -na /Applications/Alacritty.app` as a command in a key binding results in a -10810 error.

Could you try applying this change again: https://github.com/jwilm/alacritty/pull/2193/files? This fixed the issue for me.

I had to revert this change because of issues on some Linux systems (https://github.com/jwilm/alacritty/issues/2211) even though I'm unsure what caused these issues. But potentially we could use `daemon` on Linux and `fork` on Linux.

Though if you have any idea what could have caused these issues on Linux, I'd be very curious to hear. I basically recreated glibc's `daemon` call 1:1 and it still didn't show the same behavior.

**Comment by dnkl** [comment]
One difference between glibc's `daemon()` and yours is that glibc calls `_exit(2)`, while you call `std::process::exit(0)`, which I assume maps to `exit(3)`.

`exit` will cause at-exit handlers to run (registered with either `atexit(3)` or `on_exit(3)`).

**Comment by chrisduerr** [comment]
Huh that's interesting, I wasn't aware of that. Though I'm not sure why that would cause a fatal X IO error on some systems.

**Comment by dnkl** [comment]
Me neither. But there may be a system-installed at-exit handler that closes/frees something that triggers the X IO error maybe.

Just one example; C++ uses at-exit handlers to execute global variables' destructors.

In any case, I think `_exit()` is the appropriate call to use in this scenario.

**Comment by chrisduerr** [comment]
It actually looks like glibc calls `_exit(0)` and not `_exit(2)`.

@dvergeylen if you're willing to look into this, I'd be curious if you can make this work by changing things to either `libc::_exit(0)` or `libc::_exit(2)`.

**Comment by dnkl** [comment]
> It actually looks like glibc calls _exit(0) and not _exit(2).

I meant `_exit(2)` as in `man 2 _exit` ;)

**Comment by chrisduerr** [comment]
Ooooooh, that explains a lot of things. And it does indeed [call `libc::exit`](https://github.com/rust-lang/rust/blob/9ebf47851a357faa4cd97f4b1dc7835f6376e639/src/libstd/sys/unix/os.rs#L540-L542) instead of `libc::_exit`. So it might be worth to test that out.

Though maybe that will cause macOS to fail again, I'm not sure.

**Comment by dnkl** [comment]
> Though maybe that will cause macOS to fail again, I'm not sure.

If it does, maybe it's related to `setsid`? Your PR that changed daemon -> fork didn't call `setsid()`.

**Comment by chrisduerr** [comment]
If you take a look at the linked issue, you'll be able to see that `setsid` was one of the first things we've tested. So I don't think that's it. Good idea though.

**Comment by cjustin88** [comment]
> I tried that as well; for me, it flashes a new window for fraction of a second. 😞

Also getting this on latest master (090842bd), on macOS 10.14.4.

**Comment by sts10** [comment]
Interestingly, for me:

```
- { key: N,        mods: Command, action: SpawnNewInstance             }
```

works well for me in version 0.3.0 on MacOS 10.11.6. 

For the record, I replaced this old keybinding: 
```
- { key: N,        mods: Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }
```

**Comment by leonbreedt** [comment]
Using a variant of @jwilm 's workaround on macOS 10.14.4 (18E226). Made similar patch in `ActionContext::spawn_new_instance()`.

```diff
diff --git a/src/event.rs b/src/event.rs
index ffedce2..0627536 100644
--- a/src/event.rs
+++ b/src/event.rs
@@ -183,10 +183,17 @@ impl<'a, N: Notify + 'a> input::ActionContext for ActionContext<'a, N> {
         #[cfg(not(unix))]
         let args: Vec<String> = Vec::new();

-        match start_daemon(&alacritty, &args) {
-            Ok(_) => debug!("Started new Alacritty process: {} {:?}", alacritty, args),
-            Err(_) => warn!("Unable to start new Alacritty process: {} {:?}", alacritty, args),
-        }
+        use ::std::process::Command;
+
+        Command::new(alacritty)
+            .args(args)
+            .spawn().expect("spawn ok")
+            .wait();
+
+        //match start_daemon(&alacritty, &args) {
+        //    Ok(_) => debug!("Started new Alacritty process: {} {:?}", alacritty, args),
+        //    Err(_) => warn!("Unable to start new Alacritty process: {} {:?}", alacritty, args),
+        //}
     }
 }
```

**Comment by chrisduerr** [comment]
@leonbreedt Could you test the patch I've proposed?

Here is it again to make applying a little simpler:
```diff
diff --git a/src/util.rs b/src/util.rs
index b70f2f1..ec27a80 100644
--- a/src/util.rs
+++ b/src/util.rs
@@ -15,6 +15,7 @@
 use std::ffi::OsStr;
 use std::process::Command;
 use std::{cmp, io};
+use std::process::Stdio;
 
 #[cfg(not(windows))]
 use std::os::unix::process::CommandExt;
@@ -22,8 +23,6 @@ use std::os::unix::process::CommandExt;
 #[cfg(windows)]
 use std::os::windows::process::CommandExt;
 #[cfg(windows)]
-use std::process::Stdio;
-#[cfg(windows)]
 use winapi::um::winbase::{CREATE_NEW_PROCESS_GROUP, CREATE_NO_WINDOW};
 
 /// Threading utilities
@@ -91,9 +90,14 @@ where
 {
     Command::new(program)
         .args(args)
+        .stdin(Stdio::null())
+        .stdout(Stdio::null())
+        .stderr(Stdio::null())
         .before_exec(|| unsafe {
-            #[allow(deprecated)]
-            libc::daemon(1, 0);
+            if ::libc::fork() != 0 {
+                ::libc::_exit(0);
+            }
+            ::libc::setsid();
             Ok(())
         })
         .spawn()?

```

**Comment by leonbreedt** [comment]
@chrisduerr applied to 651823192495d6e70e98bd09fce4f233028384fa (no other changes, reverted the workaround in `src/event.rs`). Tested using the following key binding:

```yaml
  - { key: N,        mods: Command, action: SpawnNewInstance             }
```

seems to do the trick so far.

**Comment by chrisduerr** [comment]
Does it work with using `command: { program: "open", args: ["-na", "/Applications/Alacritty.app"] }`?

**Comment by leonbreedt** [comment]
@chrisduerr yes, that works as well. 👍

**Comment by chrisduerr** [comment]
Awesome, so all that's left to sort out is if this fixes the issue of @dvergeylen too. Otherwise we'd have to roll the fork out on macos and keep the current code on linux.

**Comment by dvergeylen** [comment]
Hi @chrisduerr,

How can I test this? Do I apply the patch you mention in [this comment](https://github.com/jwilm/alacritty/issues/2259#issuecomment-481589622)? On current master?

**Comment by chrisduerr** [comment]
Yeah, it should cleanly apply on the current master. Thanks for the cooperation!

**Comment by dvergeylen** [comment]
651823192495d6e70e98bd09fce4f233028384fa (latest master) → Working
651823192495d6e70e98bd09fce4f233028384fa + [patch](https://github.com/jwilm/alacritty/issues/2259#issuecomment-481589622) → Working as well 🙂

**Comment by jperras** [comment]
@chrisduerr Can confirm that 651823192495d6e70e98bd09fce4f233028384fa + [patch](https://github.com/jwilm/alacritty/issues/2259#issuecomment-481589622) solves the issue for myself as well!

**Comment by simmel** [comment]
Interestingly(?) I only hit this bug when I used a User Font (installed via `brew cask` into `~/Library/Fonts/`). When I used a system font it worked.. o_O

Works perfectly with this patch though, thanks!

**Comment by awgn** [comment]
As of today, the brew cask version still does not work, and neither SpawnNewInstance nor open -na work for me. I'm running Mojave 10.14.4. Any clue to launch multiple sessions, apart for running open -na /Application/Alacritty.app manually?

**Comment by jwilm** [comment]
Thanks all who helped fix this. Latest master works for me :)
