### ISSUE TITLE
Unhandled Esc Dispatch

### ISSUE THREAD

**Issue by unrealhoang** [jwilm/alacritty#226]
I'm getting the following error from Alacritty whenever I do anything in vim (inside tmux), and I think it make vim scrolling very slow.

```
[unhandled] esc_dispatch params=[], ints=[40], byte='B' (42)
```

**Comment by richiejp** [comment]
As far as I can tell this is telling the terminal to switch to the G0 graphic character set which is he default (i.e. the characters in section 7.4 of this document http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-043.pdf). Alacritty never switches to the G1 set or higher from what I have seen.

If Vim tries to switch to any of the other graphic sets then it won't display correctly (I don't think Vim will by default). I think I have observed this problem with YaST2 in ncurses mode, where you can also see the following which I haven't found in the specification yet

```
[Unhandled CSI] action='l', args=[4], intermediates=[]
[Unhandled CSI] action='h', args=[7], intermediates=[63]
[Unhandled CSI] action='h', args=[1034], intermediates=[63]
[Unhandled CSI] action='h', args=[1034], intermediates=[63]
[Unhandled CSI] action='h', args=[1034], intermediates=[63]
...
[unhandled] esc_dispatch params=[], ints=[40], byte='0' (30)
```

**Comment by richiejp** [comment]
So it appears `ESC ( B` sets the G0 character set to ASCII and `ESC ( 0` sets it to the DEC/VT100 line drawing set, which is neatly explained here: https://en.wikipedia.org/wiki/Box-drawing_character#Unix.2C_CP.2FM.2C_BBS and in more detail here: http://vt100.net/docs/vt520-rm/ek-vt520-rm.pdf (page 352)

I suppose this could be implemented by mapping the equivalent Unicode characters to the appropriate G0 code points. In the mean time `ESC ( B` could be treated as a No-Op to prevent any slow down from printing to another terminal. If I get time I will make a pull request.

**Comment by jwilm** [comment]
This was resolved a while ago

**Comment by alexherbo2** [comment]
I have the same issue.
