### ISSUE TITLE
Windows: Title Bar Icon missing with 0.3.0 rc3 

### ISSUE THREAD

**Issue by davidhewitt** [jwilm/alacritty#2260]
I think the icon was replaced recently? It no longer shows in the Window title bar for me with the latest master / 0.3.0 rc3.

**Comment by chrisduerr** [comment]
What did you use to install it? The .msi file? I thought I've fixed everything so it should work, but it's possible I missed something.

**Comment by davidhewitt** [comment]
I was just using the portable one. It's also missing if I run alacritty using `cargo run`.

**Comment by chrisduerr** [comment]
Interestingly enough, it doesn't seem like the latest master broke this. I thought it would have to do with the icon reorganization but I bisected it and the first bad commit is the glutin 0.20 update.

I've created an issue upstream to track this: https://github.com/tomaka/winit/issues/828.

**Comment by davidhewitt** [comment]
> I thought it would have to do with the icon reorganization but I bisected it and the first bad commit is the glutin 0.20 update.

That would make sense - I hadn't updated my alacritty for a little while. Thanks for figuring that out :smile:
