### ISSUE TITLE
Bug: Alacritty showing _ instead of special chars

### ISSUE THREAD

**Issue by kurko** [jwilm/alacritty#2268]
Which operating system does the issue occur on? MacOS

First I opened https://github.com/jwilm/alacritty/issues/1620, which is now "fixed" on [0.3.0-rc3](https://github.com/jwilm/alacritty/releases/tag/v0.3.0-rc3). I say "fixed" because now it seems that another bug is happening. No special char is being shown on the screen.

Below is my terminal:

<img width="119" alt="Screen Shot 2019-04-08 at 11 43 46" src="https://user-images.githubusercontent.com/70312/55733233-d828fa80-59f3-11e9-9545-d8d72f42e2c3.png">

The 1st `_` is actually a `→`, the 2nd is a `á` and the 3rd is a `ê`. In other words, Alacritty is just showing `_` instead of special characters.

Is it on the radar? Known bug?

**Comment by chrisduerr** [comment]
Which font are you using? Have you tried switching your font to see if that resolves the problem?

**Comment by kurko** [comment]
How can I change my font? There are no menus on Alacritty?

It seems like the same font from iTerm.app, but it works fine there. Can't confirm yet that it's the same font though.

**Comment by kurko** [comment]
Oh, it's Tmux that's causing it. Outside it, it's fine:

<img width="337" alt="Screen Shot 2019-04-09 at 16 27 00" src="https://user-images.githubusercontent.com/70312/55829137-5c5aab00-5ae4-11e9-9fe0-7b4d869eb13e.png">

Thanks a lot.

**Comment by chrisduerr** [comment]
I'd check locale and TERM if it works outside of tmux but not inside.

**Comment by kurko** [comment]
Yep, locale. Thanks.
