### ISSUE TITLE
prebuilt 0.3.0 binaries fail to run in Debian 10 buster

### ISSUE THREAD

**Issue by anarcat** [jwilm/alacritty#2272]
I have tried running the prebuilt binaries from the releases page in a Debian 10 Buster environment, and it seems it completely failed to load *something*.

A screenshot doesn't quite give it justice, because it doesn't capture how things are garbled up, but here it is:

![image](https://user-images.githubusercontent.com/796623/55769524-27504900-5a4f-11e9-8a1e-4408257eea79.png)

In the back window you can see the rxvt that started the alacritty process and all the fontconfig errors. In the foreground you see a blank square where the alacritty window should be...

During that time, alacritty takes up an entire CPU and makes my fan go crazy:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                          
31835 anarcat   20   0  188840  72088  39228 R 100,0   0,4   0:46.73 alacritty  
```

I originally thought this was a permanent condition, but I have seen alacritty recover at least once and actually show the terminal and bash shell correctly. Maybe it is, therefore, an instance of #2236, but at this point it is beyond slow - it takes well over two minutes to load, which is of course not really acceptable for a terminal. :)

I am running Debian 10 buster GNU/Linux in Xorg. This only occurs with the prebuilt binaries, when compiled from source everything works fine.

**Comment by chrisduerr** [comment]
The precompiled binary is compiled with Ubuntu 18.04 which means it's not compatible with every linux distributions. Unfortunately this means that your only solutions are either compiling from source or using something like the snap version.

We can't really fix this since building for all available distros is unrealistic, though some improvements might be possible in the future.

**Comment by anarcat** [comment]
there are ways to provide statically built binaries that will work everywhere, by bundling more stuff in the binary. git-annex's joey hess has done a lot of work on this, although with haskell...

in any case, I think this should still be somewhat fixed, even if only as a documentation update to warn about possible problems.

**Comment by chrisduerr** [comment]
Linking things like fontconfig and freetype statically is not worth the trouble.

A completely static build for CLI applications works great without any problems. In fact a lot of Rust binaries will provide that automatically. But for GUI applications it's often unreasonable.
