### ISSUE TITLE
Opacity isn't working with i3 + compton + Arch + X11

### ISSUE THREAD

**Issue by glalonde** [jwilm/alacritty#2275]
Which operating system does the issue occur on?
Arch

If on linux, are you using X11 or Wayland?
X11

It worked great on <=2.9, now having copied over the default config(into ~/.config/alacritty) and just changing the opacity value from 1.0 to 0.3, it is opaque black.

I guess it is more correct to say opacity is working too well.

**Comment by juchiast** [comment]
Doesn't work with me too. I'm on Fedora with i3 and xcompmgr. 

Font config doesn't work too.

**Comment by chrisduerr** [comment]
I've reopened the original issue https://github.com/jwilm/alacritty/issues/2254. Apparently things were not fixed on all systems.

**Comment by xiaolitongxue666** [comment]
I have the same question

**Comment by chrisduerr** [comment]
The bug is fixed, please update to the latest version of Alacritty.
