### ISSUE TITLE
Windows installer wrong paths

### ISSUE THREAD

**Issue by vladvasiliu** [jwilm/alacritty#2276]
Alacritty installed via the MSI installer seems to reference some wrong paths.

**Environment:**
OS: Windows 2019
Alacritty: 0.3.0
Install type: MSI installer

**How to reproduce:**
Install alacritty 0.3.0 with msi from releases page
Attempt to launch alacritty from start menu.

**Error:**
````
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'gl function was not loaded', C:\Users\travis\build\jwilm\alacritty\target\release\build\alacritty-de9c656a86c6792b\out/gl_bindings.rs:20624:13

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------
````

**Comment by chrisduerr** [comment]
Which GPU do you use? That sounds like the error you get when the OpenGL support is not sufficient.

**Comment by vladvasiliu** [comment]
I have an integrated GPU with an i5-42xx.
I think the problem was the video driver as this is a windows 2019 install. After installing the intel drivers it seems to run OK.
