### ISSUE TITLE
Panic due to error in config

### ISSUE THREAD

**Issue by igor37** [jwilm/alacritty#2279]
## System

OS: Antergos Linux, Kernel v. 5.0.6
Display Server: X11
WM: i3
Compositor: compton (afaik irrelevant here)
Alacritty version 0.2.9 (similar problems occurred in previous versions as well, though)

## Summary
In case of certain configuration errors, e.g. when the colors: primary: background property is set twice in a row, alacritty will panic:

```
colors:
  primary:
    background: '0x002b36'
    background: '0x002b36'
    foreground: '0x839496'
```

## Expectation
Fallback to default setting

## Output

```
Created log file at "/tmp/Alacritty-8246.log"
[2019-04-09 11:23] [ERROR] Problem with config: colors.primary: duplicate field `background` at line 1
45 column 15; using default value
thread 'main' panicked at 'unexpected end of mapping', /build/.cargo/registry/src/github.com-1ecc6299d
b9ec823/serde_yaml-0.8.8/src/de.rs:147:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by chrisduerr** [comment]
Our upstream parsing dependency does not strive to propagate errors if the file is invalid, giving no guarantees that there will not be a runtime crash.

The best approach might be to verify the validity of the input file first before starting to try and parse it with serde, https://github.com/chyh1990/yaml-rust might be a good choice for this.

**Comment by paul** [comment]
:+1: Also happened to me. I was tweaking the font settings, and copied the current `family: ` line and pasted it below, and alacritty immediately crashed and wouldn't relaunch. I had to launch a different terminal to edit the alacritty.yml file before I could start it again. Not a showstopper, but kinda annoying.
