### ISSUE TITLE
100% CPU when no configuration alacritty.yml

### ISSUE THREAD

**Issue by lzutao** [jwilm/alacritty#2282]
I opened `alacritty` with no configuration. The terminal popped up
with blank screen and it used 100% CPU.
The problem is fixed by copy the default `alacritty.yml` to home 
directory. So could we add a note about this issue on `README`
or FAQ?

#### Alacritty version
22eff1b (2019-04-08)

#### Which operating system does the issue occur on?
Linux

```console
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
% uname -a
Linux us 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

#### If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment]
What system are you on? Do have an 'odd' system like no `~/.config` available or no permissions to write to `~/.config` for Alacritty?

**Comment by lzutao** [comment]
I'm on Ubuntu 18 x86_64. The permissions on `~/.config` seems normal to me.
```console
% sha256sum ~/.config/alacritty/alacritty.yml ~/alacritty.yml
fb158a325a57fa29d104bf1c7352daa118252b2900d677a146f3679624e2640f  /home/lzutao/.config/alacritty/alacritty.yml
fb158a325a57fa29d104bf1c7352daa118252b2900d677a146f3679624e2640f  /home/lzutao/alacritty.yml
% ls -la ~/.config/alacritty                              
total 32K
drwxrwxr-x  2 lzutao lzutao 4.0K Apr  9 21:37 .
drwxr-xr-x 23 lzutao lzutao 4.0K Apr  9 21:37 ..
-rw-rw-r--  1 lzutao lzutao  23K Apr  9 21:37 alacritty.yml
```

**Comment by chrisduerr** [comment]
Are you running the snap or something like that?

**Comment by lzutao** [comment]
No, I built it form git.

**Comment by chrisduerr** [comment]
Could you maybe run it through `perf` to check what the CPU is busy with? I'd assume there might be some empty loop going on.

**Comment by lzutao** [comment]
Sorry, I can't reproduce it anymore. So I will close this issue for now.
