### ISSUE TITLE
Text on Alacritty 0.3.0 does not reflow on MacOS 

### ISSUE THREAD

**Issue by danemacmillan** [jwilm/alacritty#2283]
**Which operating system does the issue occur on?**
MacOS Mojave (10.14.4)

The [`0.3.0` release](https://github.com/jwilm/alacritty/releases/tag/v0.3.0) yesterday included "Text will reflow instead of truncating when resizing Alacritty."

This blog post includes a [video](https://blog.christianduerr.com/images/reflow.mp4) of how that looks:
https://blog.christianduerr.com/alacritty_030_announcement

I'm not seeing this behaviour.

**Comment by chrisduerr** [comment]
Are you running a terminal multiplexer like tmux?

**Comment by danemacmillan** [comment]
The same lack of text reflow occurs with and without tmux running.

**Comment by chrisduerr** [comment]
Will Alacritty print `0.3.0` when running `alacritty --version`?

**Comment by danemacmillan** [comment]
Yes:

![](https://i.imgur.com/twCCJQk.png)

**Comment by chrisduerr** [comment]
Which shell are you using? Please make sure to test with bash since a shell inserting newlines itself will break reflow.

**Comment by danemacmillan** [comment]
`GNU bash, version 5.0.3(1)-release (x86_64-apple-darwin18.2.0)`

![](https://i.imgur.com/yZwmUj0.png)

I even tested on an empty profile without any dotfiles, so there are no customizations in place.

It's not even that the text reflow is partially broken or anything, it's behaving as though I'm resizing an image without any scale constraints: ![here's a video](https://cvws.icloud-content.com/S/AaVokrSIXYL2gp6egk4rBceDVMlH/Screen+Recording+2019-04-09+at+1.32.48+PM.mp4?o=AilA0KJHnlnTY9d9P3ebzurxuGzlMX5-24O5K2gsDDFz&v=1&z=https%3A%2F%2Fp72-content.icloud.com%3A443&x=1&a=BtzxXjTBHPs1tRKEmfsmUb9BddPpA3hlSgEAAAPEZEo&e=1554842397&r=73245848-4f88-414b-a53b-7241b146097b-1&s=e8jLkUcaGN3kkyfEXU9X0lKIWOc).

**Comment by chrisduerr** [comment]
Reflow is actually working in that video if you take a look at it though. It just doesn't update until the resize is complete, which is likely a performance optimization made by our window library for macos.

**Comment by danemacmillan** [comment]
Sure, reflow "works," but it's not [live](https://blog.christianduerr.com/images/reflow.mp4), which is a reasonable expectation, and does not work the same on every platform.

Instead of simply modifying this ticket, you prefer I open a new one that calls out the "performance optimization made by our window library for macos," so that text reflow [behaves like in this video](https://blog.christianduerr.com/images/reflow.mp4), is that correct?

**Comment by chrisduerr** [comment]
Different platforms will always behave differently. Which is why they're... different.

**Comment by danemacmillan** [comment]
> Different platforms will always behave differently. Which is why they're... different.

Insightful. You've really only taught me something about you personally, though.

Thank you for the upstream pointer. I'll open an issue there in due time.

**Comment by Ciebiada** [comment]
@danemacmillan Can you post the link to the issue? I can't find it
