### ISSUE TITLE
Appreciation + potentially unrelated bug

### ISSUE THREAD

**Issue by adrianbrink** [jwilm/alacritty#229]
I am on macOS10.12 and build it with --release and running it from iTerm2 with ./target/release/alacritty .

The problem that I have is that the typed command shadows over to its output.
<img width="212" alt="screen shot 2017-01-08 at 12 03 20" src="https://cloud.githubusercontent.com/assets/11320251/21749218/b79e2626-d59a-11e6-883e-20d9dbd871f5.png">

The same issue appears with Terminal.app, however it doesn't appear with iTerm2.app

Any help would be appreciated.

Also, damn this is awesome. :-) I'm going to start using alacritty from now on (even though it would be nice to get rid of the shadowing).
Furthermore, how can I bind alacritty to a desktop shortcut that I can open from spotlight?

**Comment by tgummerer** [comment]
I've had the same problem of the command shadowing the output before, when I was using zsh and had set `$TERM` to screen-256color.  Either setting it to xterm-256color or running inside of tmux solved the problem for me.

**Comment by jwilm** [comment]
> Also, damn this is awesome

Thanks!

> Furthermore, how can I bind alacritty to a desktop shortcut that I can open from spotlight?

Need to build an `Alacritty.app`. We'll be publishing these at some point once the project matures.

> Any help would be appreciated.

This does sound like a potential TERM issue. Going to close this as such, but feel free to correct me if this turns out to be an Alacritty issue.
