### ISSUE TITLE
URL Launcher does not work within tmux session

### ISSUE THREAD

**Issue by spaun2002** [jwilm/alacritty#2297]
URL Launcher functionality does not detect URLs inside tmux session.
Without tmux a click on a URL works as expected.
Compared to another terminal (MATE terminal) where URLs are clickable even inside tmux sessions.

Which operating system does the issue occur on?
- Linux Ubuntu 18.04 LTS

If on linux, are you using X11 or Wayland?
- X11

**Comment by chrisduerr** [comment]
Does this work when pressing `shift`?

**Comment by spaun2002** [comment]
It does if I specify Shift as a modifier in the config. So it does not work with either 'None' or 'Control' modifiers.

**Comment by chrisduerr** [comment]
It works because you've got mouse mode enabled in tmux. To make it possible to click URLs you have to first deactivate this mouse mode or tmux will handle all the events itself.

You don't need to specify shift as modifier, shift will automatically disable mouse mode when held for all purposes.

**Comment by sorliem** [comment]
Encountered this same issue - TIL about shift to disable mouse mode. Thanks @chrisduerr!
