### ISSUE TITLE
Cursor doesn't change shape in Neovim *inside Tmux*

### ISSUE THREAD

**Issue by doronbehar** [jwilm/alacritty#2306]
Which operating system does the issue occur on? Arch Linux

If on Linux, are you using X11 or Wayland? X11

I've read #1630 and #2131 which are sort of related to this issue. When I use Neovim inside Alacritty the cursor does change it's shape but when it's inside Tmux it doesn't. I've read on those issues that it is suggested to change `$TERM`. This could be changed when launching `nvim` only or by adding `set -g default-terminal xterm-alacritty` in `~/.tmux.conf`. I'm not sure if it's a bug within Alacritty or in Tmux. Note that `man tmux` explicitly says:

> For tmux to work correctly, this must be set to ‘screen’, ‘tmux’ or a derivative of them.

BTW, [Kitty](https://sw.kovidgoyal.net/kitty/#quickstart) (Similar project, this one looks better though :smiley_cat:) Doesn't have this problem.

**Comment by chrisduerr** [comment]
Nvim uses an internal lookup table to check for this feature, so there's nothing Alacritty can do about this.

IIRC Kitty uses the `xterm-kitty` TERM which means it pretends to be `xterm` for compatability and solves some of these problems.

This, however is an upstream issue with neovim. I'm not sure what the tmux `TERM` looks like by default for you, that would probably be relevant information. Either way your best bet is likely to alias neovim to use a different term.

**Comment by doronbehar** [comment]
> Nvim uses an internal lookup table to check for this feature, so there's nothing Alacritty can do about this.

I understand. But the point is, that my `$TERM` inside Tmux is the same whether I use it inside Kitty or Alacritty - `screen`. How else could Neovim know what is the actual parent terminal? What I mean to say, is that the fact that Kitty's natural (without Tmux) `$TERM` is different is irrelevant, unless there are other means in which Neovim decides if those term capabilities exist. To be clear - Tmux' `$TERM` inside both Kitty and Alacritty is the same.

Additionally, you've stated in your comment https://github.com/jwilm/alacritty/issues/1630#issuecomment-427570121 that you've sent a PR that added Alacritty to Neovim's internal database. It was a long time ago so it is definitely available in the stable version since without Tmux the cursor changes it's shape fine.

If so, the question is: Assuming this is issue is on Neovim's side, what is the difference Neovim detects when it's inside Tmux inside Kitty and inside Alacritty?

**Comment by chrisduerr** [comment]
This might also be a tmux bug. Since you can fix it with `set -g default-terminal ...` and not with `TERM=...`.

Don't get me wrong, if there's anything Alacritty can do to resolve this (other than using an `xterm-...` terminfo), I'd love to know. I'm just not sure at this point.

I thought I'd look into this myself again before just dismissing it and I am not actually able to reproduce it. I've got a neovim branch with some debug output about cursor support and it prints the exact same info with both kitty and Alacritty.

Can you test this with an empty Alacritty, Tmux and Kitty config to confirm that you haven't messed anything up in your config?

Just FYI, this is the patch I'm using:

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 4aff2d264..29ebaaee1 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -1500,6 +1500,13 @@ static void patch_terminfo_bugs(TUIData *data, const char *term,
     && strstr(colorterm, "mate-terminal");
   bool true_xterm = xterm && !!xterm_version && !bsdvt;

+  printf("TMUX: %d\n", tmux);
+  printf("ALACRITTY: %d\n", alacritty);
+  printf("VTE: %d\n", gnome);
+  printf("ALSO VTE: %d\n", gnome_pretending_xterm);
+  printf("SCREEN: %d\n", screen);
+  printf("XTERM: %d\n", xterm);
+
   char *fix_normal = (char *)unibi_get_str(ut, unibi_cursor_normal);
   if (fix_normal) {
     if (STARTS_WITH(fix_normal, "\x1b[?12l")) {
@@ -1691,6 +1698,7 @@ static void patch_terminfo_bugs(TUIData *data, const char *term,
             // Example: console-terminal-emulator from the nosh toolset.
             || (linuxvt
                 && (xterm_version || (vte_version > 0) || colorterm)))) {
+        printf("DECSCUSR IS SUPPORTED");
       data->unibi_ext.set_cursor_style =
         (int)unibi_add_ext_str(ut, "Ss", "\x1b[%p1%d q");
       if (-1 == data->unibi_ext.reset_cursor_style) {
```

It's possible that this won't cleanly apply on the latest neovim master anymore, but it should be trivial to recreate or fix issues during applying.

**Comment by doronbehar** [comment]
Thanks for your comment. I've applied that patch against the stable version of Neovim - `0.3.4`. It wasn't a completely clean apply but I've tested this with the default kitty and Alacritty's configuration file.

From some reason, I get a coredump when I run it in inside Tmux (inside Alacritty *or* Kitty). Without Tmux, those `printf`s work fine - The only differences between the outputs are the lines with `XTERM: ` and `ALACRITTY: ` which show `0` and `1` for Kitty and Alacritty in conjunction - as expected.

As for using branch `master` of Neovim, that wasn't successful because of [`ld` errors](https://gist.github.com/doronbehar/578c2f5e6f21a2a909773a16b763f1d4).

**Comment by chrisduerr** [comment]
Just to make sure, you have installed the Alacritty terminfo files, right?

**Comment by doronbehar** [comment]
You wouldn't believe it...

Yes I do have them installed it's just that Arch Linux apparently can have outdated packages in it's `community` repository - https://www.archlinux.org/packages/community/x86_64/alacritty/ .

Anyway, I've built an updated version of the package but it still behaves the same.

**Comment by chrisduerr** [comment]
As long as you're using the `alacritty-terminfo` package everything should be good to go, since that's what I'm using too.

Though I'd recommend at least trying to install it from source and using the way to install the terminfo files specified in the `INSTALL.md`, since it seems like the Archlinux package does it incorrectly.

**Comment by doronbehar** [comment]
I was just thinking about it - `tic` without `-xe alacritty,alacritty-direct` threw errors when I've built the package and I was thinking you should know about it.

That solved the issue! I'm so happy you were willing to help. I hope to contribute some day to this project. It seems very, very promising.

Cheers :beers:

**Comment by chrisduerr** [comment]
Glad we were able to figure it out. I've also opened an issue with the `alacritty-terminfo` Arch package, so hopefully that should resolve the problem with the package itself.
