### ISSUE TITLE
Instance spawned with keyboard shortcut cannot be maximized on OSX

### ISSUE THREAD

**Issue by nicolashahn** [jwilm/alacritty#2317]
Which operating system does the issue occur on?
OSX Mojave 10.14.4
(Alacritty 0.3.0)

To reproduce:
- Edit `config.yaml` to include the keyboard shortcut: 
```
  - { key: N,         mods: Command,      action: SpawnNewInstance       }
```
- Open Alacritty (this one can be maximized properly)
- Create another instance of Alacritty with the keyboard shortcut
- Attempt to maximize this one as well - fullscreen button should give the OSX "I can't do that" audio bell
- If you attempt to maximize this one by dragging it into its own workspace in the "three finger swipe up" view, it takes up a full workspace, but overlays the original windowed mode:
<img width="1438" alt="Screen Shot 2019-04-15 at 9 31 21 AM" src="https://user-images.githubusercontent.com/9121818/56137470-f007fd80-5f62-11e9-8cf6-79de2905c771.png">

Creating a new instance by running `alacritty` from within the original instance does create one that can be maximized. So I'm curious, what is the difference between creating one through this method and through the keyboard shortcut?

Also, looking for a way to contribute, if you think this is a good first item to start with, I'd appreciate any tips on where to begin.

**Comment by chrisduerr** [comment]
Can you reproduce this by compiling Alacritty from source? There have been some changes to the `SpawnNewInstance` action recently.

**Comment by nicolashahn** [comment]
That fixed it. Thanks for the quick response. Closing.
