### ISSUE TITLE
application written with cursive is not rendered correctly

### ISSUE THREAD

**Issue by msehnout** [jwilm/alacritty#2319]
Which operating system does the issue occur on?
macOS

How to reproduce:
1. install alacritty using homebrew
2. clone cursive repository: https://github.com/gyscos/Cursive
3. run `cargo run --example dialog`
4. compare with different terminal emulator

Actual result:
![Screen Shot 2019-04-16 at 13 33 01](https://user-images.githubusercontent.com/9369632/56206550-f70b3a80-604c-11e9-9414-431fae138a3b.png)

Expected result:
![Screen Shot 2019-04-16 at 13 34 11](https://user-images.githubusercontent.com/9369632/56206567-ff637580-604c-11e9-97d4-ddabd6aa31c8.png)

**Comment by chrisduerr** [comment]
This looks like you've potentially got your locale messed up, could you verify that it's set to something sensible?

**Comment by msehnout** [comment]
Good idea! I haven't checked. Indeed after:
```
export LC_CTYPE="UTF-8"
```
it looks better. Still different from iTerm, but better.
![Screen Shot 2019-04-17 at 10 18 38](https://user-images.githubusercontent.com/9369632/56272214-87ec1f80-60fa-11e9-9d31-d7c96ac60dd7.png)

now my setting looks like this:
```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by chrisduerr** [comment]
Have you tried setting the other variables too? For me all of these are `en_US.UTF-8` on macOS.

This is important because the box drawing characters used by ncurses are often part of the extended ascii table, which is different depending on region and encoding.

**Comment by msehnout** [comment]
I used the same setting as I found in the iTerm. Anyway the result looks the same with this setup:
```
$ export LC_ALL=(locale -a | rg UTF | rg US)
$ locale
LANG=
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by msehnout** [comment]
ok, I found the source of this problem. I was using the `Hack` font. Changing it back to the default and using UTF-8 for everything fixes this issue. Now I have another issue with my git prompt in fish :-), I will open a new issue in case I don't find a solution myself.
