### ISSUE TITLE
Alacritty crashes immediately on start in Xmonad

### ISSUE THREAD

**Issue by kinghajj** [jwilm/alacritty#2320]
**Which operating system does the issue occur on?**

Ubuntu 18.04

**If on linux, are you using X11 or Wayland?**

X11, running xmonad.

When I try to start Alacritty on an empty workspace, it immediately crashes before showing the UI. If there are existing windows on the workspace, though, it starts successfully, but crashes once the other windows are closed.

I used git-bisect to pinpoint the problem commit as 6757acbb824e8be9968529a66e9a75a0a2ea2f5d, "Bump version to 0.3.0". The only change that seems related is the version of glutin:

    -glutin = { git = "https://github.com/chrisduerr/glutin", branch = "bsd-build-fix", features = ["icon_loading"] }
    +glutin = { version = "0.21.0-rc1", features = ["icon_loading"] }

So this may just be a problem in glutin and/or my configuration.

**Comment by chrisduerr** [comment]
Is there any output when starting Alacritty from a separate command line?

**Comment by kinghajj** [comment]
I wrote this script

    #!/bin/bash
    RUST_BACKTRACE=1 strace -o ~/alacritty.strace.log ~/Documents/alacritty/target/release/alacritty 2>&1 >~/alacritty.out.log

`alacritty.out.log` is 0 bytes, so there was no output from stderr nor stdout.

The last lines of the strace output have some possibly-important details:

    futex(0x56010b9aacd8, FUTEX_WAKE_PRIVATE, 1) = 0
    write(2, "XIO:  fatal IO error 11 (Resourc"..., 77) = 77
    write(2, "      after 202 requests (200 kn"..., 73) = 73
    getpid()                                = 130879
    munmap(0x7f192eefe000, 131072)          = 0
    munmap(0x7f1932941000, 131072)          = 0
    getpid()                                = 130879
    exit_group(1)                           = ?
    +++ exited with 1 +++

I uploaded the complete strace output [here](https://pastebin.com/HR6vcYmB).

**Comment by chrisduerr** [comment]
I don't think that redirect would properly redirect Rust error messages.

Could you just execute the binary through the command line and check yourself if there's anything printed to stderr without attaching strace or anything?

**Comment by kinghajj** [comment]
Ah yes, I forgot that you have to swap the order of the redirects to capture all output. Changed the script to

    ~/Documents/alacritty/target/release/alacritty >~/alacritty.out.log 2>&1

And executed via xmobar on an empty workspace, and got this output:

    libEGL warning: DRI2: failed to authenticate
    XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
          after 202 requests (200 known processed) with 0 events remaining.

The libEGL warning occurs even when another window is open on the workspace and Alacritty starts successfully. The XIO fatal error only occurs when the workspace is empty.

**Comment by nixpulvis** [comment]
@kinghajj can you tell us what video driver you're using? Because, though I can't imagine why it would change across versions of glutin myself, it seems others have had similar issues on proprietary nvidia drivers.

**Comment by kinghajj** [comment]
I do have an nvidia card, but use the nouveau open-source driver.

**Comment by nixpulvis** [comment]
OK, I've installed `xmonad` on my system with the following setup:

```
Linux pukak 5.0.7-arch1-1-ARCH #1 SMP PREEMPT Mon Apr 8 10:37:08 UTC 2019 x86_64 GNU/Linux


03:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM204 [GeForce GTX 980] [10de:13c0] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: eVga.com. Corp. GM204 [GeForce GTX 980] [3842:2983]
	Physical Slot: 4
        ...
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia_drm, nvidia
```

```hs
import XMonad

main = xmonad def
    { terminal    = "/home/nixpulvis/Code/alacritty/target/release/alacritty"
    , modMask     = mod4Mask
    , borderWidth = 3
    }
```

**Comment by chrisduerr** [comment]
Would be interesting to know if you can reproduce this with the winit examples:
https://github.com/tomaka/winit

You can run them using `cargo run --example window`. If that causes a crash it's probably best to report this upstream and move any further discussion there.

**Comment by kinghajj** [comment]
I built the window example both in debug and release mode, and both started successfully when invoked on an empty workspace from a script.

**Comment by kinghajj** [comment]
I recently tried launching Alacritty in Xmonad under VNC, and it starts without issue. I think this may be caused by my graphics card / driver (Nvidia / nouveau), and out of scope for this project. Closing.
