### ISSUE TITLE
Chinese character selection width

### ISSUE THREAD

**Issue by Hentioe** [jwilm/alacritty#2322]
A single Chinese character requires two default widths to be fully selected. Otherwise only half can be selected. Just like this:

![image](https://user-images.githubusercontent.com/13946976/56286417-3c626180-614c-11e9-9b39-8acbf27f7669.png)

Running in Archlinux, Xorg environment. Alacritty version is `0.2.9`

**Comment by taigacute** [comment]
got similer problem
![1](https://user-images.githubusercontent.com/41671631/56859844-0aaa8f80-69c3-11e9-858d-2e8455a8a0fe.png)
