### ISSUE TITLE
 Can not normally corresponding ctrl key

### ISSUE THREAD

**Issue by taigacute** [jwilm/alacritty#2325]
Which operating system does the issue occur on? mac
my  tmux prefix key is `ctrl-space` . the alacritty cant normally corresponding the prefix key. its normal in iterm2

![term](https://user-images.githubusercontent.com/41671631/56360876-8153ca00-6218-11e9-9390-9433e879ffff.gif)

**Comment by chrisduerr** [comment]
What output do you get when you press ctrl+space after running `cat -v`? It should print `^@`, at least that's what it does for me.

If it does, it would also be interesting to see what iTerm prints.

**Comment by taigacute** [comment]
The ctrlspace key is not reflected in alacritty. I type `ctrlv` and then ctrl space in iterm2 i got`^@`。 
![term](https://user-images.githubusercontent.com/41671631/56362140-be6d8b80-621b-11e9-96b3-30555aa19e57.gif)

**Comment by chrisduerr** [comment]
I have tested this on my MBP and it seems to send all the escapes correctly. Are you using 0.3.0 (please check `alacritty --version`)?

I'm using dvorak myself, but I'd assume most other layouts should work too. Are you using a layout other than us or dvorak?

Checking that you don't have any programs that might have setup special escape sequences setup themselves could help too.

**Comment by taigacute** [comment]
when i remake alacritty.yaml it works fine
