### ISSUE TITLE
Underline and Strikethrough Bleed Into Current Line on Backspace

### ISSUE THREAD

**Issue by nixpulvis** [jwilm/alacritty#2330]
When I run `printf "\e[4;9mTEST      asd\n"` once to get our next prompt stuck with terminal attributes of underline and strikethough, then type at least 2 characters, finally using the arrow keys (or <kbd>ctrl-a</kbd>) and delete any but the last character of the text you entered, and notice that the styles bleed onto the right of the terminal.

A gif's worth a million words (even if it's of horrid quality):
![QlrVhaj](https://user-images.githubusercontent.com/715947/56397609-99284f80-6212-11e9-8f39-f02079336406.gif)

```
Linux masva 5.0.7-arch1-1-ARCH #1 SMP PREEMPT Mon Apr 8 10:37:08 UTC 2019 x86_64 GNU/Linux
```

**Comment by Ratione** [comment]
I also have this problem. I am also experiencing a (related?) rendering problem, where the Underline of the font is sometimes a few pixels and  cuts through the chars. 

Running Arch with the Awesome-Fonts. This issue was not present yesterday, and I don't believe I changed any config files.
