### ISSUE TITLE
When displays are (un)plugged under Windows, parts of the terminal might become invisible

### ISSUE THREAD

**Issue by HenkPoley** [jwilm/alacritty#2334]
Which operating system does the issue occur on?
Windows 10 1809

Went from from dock to laptop screen to (crappy, slow) StarLink USB2.0 external graphics card, and afterwards I noticed that the top my vim and bash were hidden out of sight behind and below the window titlebar and buttons.

Basically the OpenGL buffer was displayed offset, so the top was not visible inside the window (or anywhere for that matter).

**Comment by benpye** [comment]
This happens when you change your display DPI also, though I admit, this might be a less common scenario.
