### ISSUE TITLE
Cursor's colors config no longer works

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#2338]
Linux X11.

As you can see cursor colors in the config and the real cursor colors are mismatched. Now it's just inverts its colors.

![Screenshot-Sat_20_Apr_2019_32](https://user-images.githubusercontent.com/27620401/56452736-c1609d00-633d-11e9-9a07-29fd91da3563.png)

**Comment by chrisduerr** [comment]
It works great for me. Please make sure you're testing this outside of vim/tmux/... though so there's nothing else that could mess with it.

Also please make sure the correct config is loaded by running `alacritty -v` and checking the path.

**Comment by kchibisov** [comment]
I've tested this one once again. ( Cloned repo, cargo build --release, uncommented cursor's colors options in default alacritty.yml and then cargo run --release -- -v --config-file alacritty.yml). shell - fish shell ( also tested with zsh )
![Screenshot-Sat_20_Apr_2019_18](https://user-images.githubusercontent.com/27620401/56456131-a8251400-6370-11e9-8d18-ebb27bf819ae.png)
![Screenshot-Sat_20_Apr_2019_31](https://user-images.githubusercontent.com/27620401/56456132-a9eed780-6370-11e9-9772-a2d4b92686bf.png)

And this the result from a47d716daace7c197392854754406a06454ec380

![Screenshot-Sat_20_Apr_2019_46](https://user-images.githubusercontent.com/27620401/56456152-fb976200-6370-11e9-96d4-506d3cbf39ae.png)

![Screenshot-Sat_20_Apr_2019_35](https://user-images.githubusercontent.com/27620401/56456141-cab72d00-6370-11e9-9b90-f02dcfb85ce7.png)

**Comment by chrisduerr** [comment]
That looks to me like it's working? The default should be a white cursor with black foreground.

**Comment by chrisduerr** [comment]
Can confirm this has been broken, likely through the cursor rework. I'll check it out right now.

**Comment by chrisduerr** [comment]
I've created a fix for this issue: https://github.com/jwilm/alacritty/pull/2339

Let me know if that does the job for you!
