### ISSUE TITLE
Update Glutin

### ISSUE THREAD

**Issue by rigtorp** [jwilm/alacritty#234]
This version of glutin doesn't compile on Windows 10:
```
[dependencies.glutin]
git = "https://github.com/jwilm/glutin"
rev = "af7fe340bd4a2af53ea521defcb4f377cdc588cf"
```
Upstream glutin 0.7.1 compiles fine:
```
glutin = "0.7.1"
```

This is blocking windows support.

**Comment by d3rrial** [comment]
Have you tried compiling alacritty with glutin 0.7.1? I'm curious what your results are

**Comment by jwilm** [comment]
> Have you tried compiling alacritty with glutin 0.7.1? I'm curious what your results are

This will not work. Alacritty is on a fork of glutin that has a very different `Event::KeyboardInput` variant:

- Includes `Mods` which are the modifier keys as provided by the XEvent or equivalent on other platforms
- Includes the UTF-8 string generated by the input sequence. This is normally provided in a separate event, but Alacritty needs both at once to either run a key binding or forward the string to the pty.

**Comment by rigtorp** [comment]
@jwilm Does it make sense to upstream your changes to glutin?

**Comment by jwilm** [comment]
Very much so. I was hoping to make these changes for windows and wayland before opening a PR, but maybe they would be accepted separately.

**Comment by jwilm** [comment]
Renamed this issue to suggest an action. We need to reapply my patches on top of what's now two projects (winit + glutin), upstream them, and then update Alacritty's dependencies.

**Comment by rigtorp** [comment]
Opened this issue https://github.com/tomaka/winit/issues/108 to see if upstream is willing to accept these improvements.

**Comment by rigtorp** [comment]
Submitted PR https://github.com/tomaka/winit/pull/112 to add keyboard modifiers to winit keyboard event.

**Comment by emersion** [comment]
https://github.com/tomaka/winit/pull/112 has been merged

**Comment by rigtorp** [comment]
@emersion Now we need to update glutin to this newer version of winit

**Comment by mystal** [comment]
Looks like with the merge of https://github.com/tomaka/glutin/pull/864 glutin's master branch is now using the latest winit. One step closer!

**Comment by emersion** [comment]
Linking a related PR: #554

**Comment by jonhoo** [comment]
I wonder if this would also fix #148...

**Comment by jwilm** [comment]
It might; there's been a lot of work in this area in winit lately. There's also someone waiting to contribute some fixes for IME support which *might* be the fix needed for compose key.

**Comment by jwilm** [comment]
Glutin/winit API churn is really high right now, and the latest candidate branch has some bugs. There's a new WIP to update current Glutin API to winit 0.7.1, and hopefully we can get on that.
