### ISSUE TITLE
Performance issue on Linux with Mesa

### ISSUE THREAD

**Issue by ordian** [jwilm/alacritty#235]
> Alacritty is incredibly fast. Compare find /usr or equivalent with your favorite terminal emulator. Keep in mind that command will be faster the second time it’s run due to OS caching.

_On Alacritty (width: 724, height: 484)_
```
find /usr  1.88s user 3.00s system 5% cpu 1:32.78 total
```
_On gnome-terminal, Konsole (width: 1366, height: 768)_
```
find /usr  1.13s user 1.75s system 44% cpu 6.409 total
find /usr  1.31s user 1.75s system 72% cpu 4.204 total
```
> Alacritty’s biggest claim is that it’s the fastest terminal emulator available. If there’s a case where it’s not, then it’s either a bug in Alacritty or a misconfigured system. 

I've recorded some flame graphs (w/ and w/o "--call-graph dwarf"):
```sh
perf record -F 99 --call-graph dwarf target/release/alacritty
perf script | stackcollapse-perf| flamegraph --width 1920 > alacritty_dwarf.svg
``` 
[flame_graphs.zip](https://github.com/jwilm/alacritty/files/692326/flame_graphs.zip)

Some system info:
* Alacritty: 9e713189cc6dc83f97e87fa18b66b39d2c7222cc
* Kernel: x86_64 Linux 4.9.0-1-MANJARO
* CPU: Intel Core i7-3520M @ 4x 3.6GHz
* GPU: Mesa DRI Intel(R) Ivybridge Mobile
* OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.2
* OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

**Comment by 0X1A** [comment]
This is a known issue, see #125

**Comment by ordian** [comment]
Sorry, closing as duplicate. Nevertheless, flame graphs may be helpful.

**Comment by jwilm** [comment]
Thanks for the charts!
