### ISSUE TITLE
Redraw failure

### ISSUE THREAD

**Issue by SV3A** [jwilm/alacritty#2353]
Since the last two releases I've been experiencing these redrawing errors with neovim/tmux on macOS. On some lines the screen simply does not redraw. Reverting back to 0.3.0, the problem disappears again.

Gif of the problem:
![screen](https://user-images.githubusercontent.com/12109115/56564307-0985f680-65ae-11e9-9358-0a02ea44d8be.gif)

OS: macOS Mojave 10.14.4
Alacritty version: 0.3.1/0.3.2

Config changes (all working in 0.3.0):
- 0 padding
- no decorations
- fonts
- colors scheme
- two keybindings

[config file](https://gist.github.com/SV3A/7fd92b5a50e13bc34117d2fed35539ed)

Furthermore, the following commands don't report anything unordinary during the event:
```
alacritty -vvv
alacritty --print-events
```

**Comment by unphased** [comment]
I experience the same. Same macOS version

**Comment by chrisduerr** [comment]
Could you bisect which specific commit broke this?

**Comment by SV3A** [comment]
> Could you bisect which specific commit broke this?

I'll have a go at it now.

**Comment by jperras** [comment]
I can confirm this behaviour. Was fine on 0.3.0, but on 0.3.1 to 4fbae5e397c514c245432a6415a4c99c52b7978f I have a similar issue on emacs.

**Comment by SV3A** [comment]
It seems that cfc20d4f34dca535654cc32df18e785296af4cc5, was the culprit.

**Comment by unphased** [comment]
I bisected but i'm currently not able to reproduce this issue on master, even after a clean recompile on v0.3.2  on this machine so i am not sure what's going on but i definitely saw the issue before. @SV3A can you still reproduce after a cargo clean?

**Comment by SV3A** [comment]
@unphased, I found that sometimes the problem took a little while to manifest itself, so it was a pain to bisect. One way to set it off by visually selecting stuff in tmux, jumping around etc. 

Anyways, just made a clean build, and the problem persists here.

**Comment by jperras** [comment]
It *seemed* to only present itself when I was in weechat or emacs; given the bisected commit from above, perhaps those two windows of mine were ones that contained non-ASCII glyphs and/or double-width unicode characters.

**Comment by martinezhermes** [comment]
Can confirm it is still there after a clean build from source today. 0.3.0 is fine.

**Comment by ikicic** [comment]
Not sure if helpful, but the underlines are shown correctly with the correct color, even though the text is missing.

**Comment by chrisduerr** [comment]
Could someone test https://github.com/jwilm/alacritty/pull/2367? It might fix this issue too.

**Comment by SV3A** [comment]
@chrisduerr, the commit seems the have fixed the bug here.

**Comment by benmezger** [comment]
Anyone still having this issue? I have no been able to fix it yet, even after this last release :(.

**Comment by kchibisov** [comment]
@benmezger you should try the latest master, since this fix wasn't “released”.

**Comment by benmezger** [comment]
@kchibisov thanks, compiling the latest master fixed! Thanks!

**Comment by jh69** [comment]
I was experiencing this and compiling the latest master fixed it. Same setup as the OP (Mojave, running tmux)

**Comment by jakyns** [comment]
@kchibisov @benmezger I installed by `brew cask`, how can I try the latest master? please help

**Comment by chrisduerr** [comment]
You'd have to build from source. Instructions for doing that can be found in the repository root's INSTALL.md file.

Otherwise you'll have to wait for the next release, which should hopefully happen with in the next week or so.
