### ISSUE TITLE
Insert cursor disappearing in Neovim

### ISSUE THREAD

**Issue by sQVe** [jwilm/alacritty#2355]
I've have noticed an issue with the cursor in **INSERT** mode in `neovim`. After having `neovim` open in `alacritty` for a while the cursor disappears when in insert mode. I'm having a hard time replicating the issue.

![Peek 2019-04-23 10-52](https://user-images.githubusercontent.com/2284724/56567834-0989f480-65b6-11e9-895f-042eb233d43e.gif)

Worth noting is that restarting `neovim` does not fix the issue. I have to restart `alacritty` for it to disappear. I did not notice this issue with version `0.3.0`.

**EDIT:** I also now noted that the cursor does not respect my set color. I have: 

```
  cursor:
    text: '0x343434'
    cursor: '0xf8f8f2'
```
But it looks like this:
![Peek 2019-04-23 10-58](https://user-images.githubusercontent.com/2284724/56568327-09d6bf80-65b7-11e9-8bcb-1b450abefa0f.gif)

I'm running `alacritty` built from https://github.com/jwilm/alacritty/commit/4fbae5e397c514c245432a6415a4c99c52b7978f on **Arch Linux** with Xorg.

**Comment by evilr00t** [comment]
It's not just NeoVim... for me it disappears in normal ZSH shell...

https://asciinema.org/a/SciyUWI6u7eSJX49faYToor4C

**Comment by jonleopard** [comment]
Getting the same issue as @sQVe. Are there some new configuration variables we should be aware of? I haven't updated mine since 0.3.0.

**Comment by kchibisov** [comment]
I've start noticing the same issue in neovim (in my case, since in fish shell cursor is fine). Alacritty respects the cursor colors in my config at startup, but it's stops doing so after some time spending in neovim ( 1 - 2 hours, maybe I'm lucky and not getting it triggered very fast).

**Comment by chrisduerr** [comment]
That looks extremely odd and I'm not able to reproduce it at all. I think some more background information might help out here.

When you say it's hard to reproduce, do you mean this rarely happens? Or does it happen reliably, but it seems to happen after an arbitrary amount of time?

Also does this happen with every cursor, or do only certain cursors like the underline and beam go invisible? Or only the block cursor? If you try changing the cursor using `printf "\e[?1Xq"` (replace X with 1/3/5), are all the cursors invisible or can you get it to show up again with certain cursors?

Does `reset` fix this issue?

> I also now noted that the cursor does not respect my set color.

I also can not reproduce that issue, would you mind opening a separate issue for that?

**Comment by evilr00t** [comment]
@chrisduerr 

For me this wrong behaviour hits me immediately when I try to move my cursor back...
As I'm checking now it seems to be that regression has been introduced after `a47d716` altho I'm still checking which commit is the "bad" one.

**Comment by chrisduerr** [comment]
If a47d716daace7c197392854754406a06454ec380 broke this for you that would certainly be very surprising to me. I would have expected 371d13f8ef95157c97f7de9964bcbc89d4a8e930 to cause this problem.

Can someone else maybe help with bisecting? I'd be curious if a47d716 is actually the culprit.

**Comment by jonleopard** [comment]
I should clarify, the issue is only happening to me while inside Neovim. I just ran `reset` and it _seems_ to have fixed the issue. If it happens again I'll keep an eye out for any patterns that trigger it.

**Comment by sQVe** [comment]
@chrisduerr It's hard to reproduce because it seems to happen randomly, at least for me. It does happen quite quickly though. I had to restart my terminal around 30-40 times today, 8 hour work day.

I've only seen an issue with the "insert cursor", i.e. the narrow line cursor. 

The cursor color had the same behavior as above. At first it works and when the insert cursor disappears the cursors are reverted to default setting.

I'll try to check the rest later today. 👊

**Comment by chrisduerr** [comment]
If `reset` fixes the issue that would at least indicate that there's some terminal state which gets corrupted. Though getting the exact commit breaking this would probably still help out a ton.

I currently don't have any clue where this could be coming from, so anything that would help me repro or narrow down the issue would be extremely helpful. So far the only reported platform is Arch with X11, is anyone here not running X11?

**Comment by svanharmelen** [comment]
Yes, I have the same issue when using neovim on my mac. And in my case it happens immediately when I open neovim.

**Comment by fsouza** [comment]
Also seeing something similar on neovim + tmux immediately after opening neovim. Not only the cursor disappears, but the screen also goes blank (and different parts of it show up and go blank as I navigate through the file). Testing on Mac. Interestingly enough, if I open neovim with no plugins/custom configurations (``nvim -u NONE``), the issue is gone. So it works fine with barebone neovim, but it also works fine when using other terminal emulators.

I'll try to identify which neovim configuration/plugin is triggering the issue and I'll see if I can find some time to bisect alacritty too

**Comment by chrisduerr** [comment]
I've tried adding some debug statements in hope that this might shed some more light on what exactly is going on when the cursor disappears. If someone who's capable of reproducing this reliably could try running this diff and send me the output it would be much appreciated.

<details>

```diff
diff --git a/src/term/mod.rs b/src/term/mod.rs
index 0e95423..ecfb2a4 100644
--- a/src/term/mod.rs
+++ b/src/term/mod.rs
@@ -236,6 +236,7 @@ impl<'a> RenderableCellsIter<'a> {
                 && (cursor.col + 1) < grid.num_cols();
             Some(cursor::get_cursor_glyph(cursor_style, metrics, offset_x, offset_y, is_wide))
         } else {
+            println!("Cursor is hidden: {:?} {:?}", term.mode.contains(TermMode::SHOW_CURSOR), grid.contains(cursor));
             // Use hidden cursor so text will not get inverted
             cursor_style = CursorStyle::Hidden;
             None
@@ -377,6 +378,7 @@ impl<'a> Iterator for RenderableCellsIter<'a> {
             if self.cursor_offset == self.inner.offset() && self.inner.column() == self.cursor.col {
                 // Handle cursor
                 if let Some(cursor_cell) = self.cursor_cell.take() {
+                    println!("Rendering existing cursor glyph with style {:?}", self.cursor_style);
                     let cell = Indexed {
                         inner: self.grid[self.cursor],
                         column: self.cursor.col,
@@ -388,11 +390,13 @@ impl<'a> Iterator for RenderableCellsIter<'a> {
                     renderable_cell.inner = RenderableCellContent::Raw(cursor_cell);
 
                     if let Some(color) = self.config.cursor_cursor_color() {
+                        println!("Overriding cursor cursor color");
                         renderable_cell.fg = color;
                     }
 
                     return Some(renderable_cell);
                 } else {
+                    println!("Rendering content below cursor with style {:?}", self.cursor_style);
                     let mut cell =
                         RenderableCell::new(self.config, self.colors, self.inner.next()?, false);
 
@@ -400,6 +404,7 @@ impl<'a> Iterator for RenderableCellsIter<'a> {
                         std::mem::swap(&mut cell.bg, &mut cell.fg);
 
                         if let Some(color) = self.config.cursor_text_color() {
+                            println!("Overriding cursor text color");
                             cell.fg = color;
                         }
                     }
```

</details>

**Comment by dead10ck** [comment]
I have the same issue on Fedora

**Comment by kchibisov** [comment]
Cannot reproduce on a47d716daace7c197392854754406a06454ec380 . Was using this commit all day.

**Comment by kchibisov** [comment]
@chrisduerr I've run alacritty with your diff. I was able to get the broken cursor behavior, but the output, in the moment of switching to the wrong behavior, was the same as with the 'normal' cursor. Anyway here is the log. I've opened the file with neovim and start moving my cursor down and then up, until I got my cursor inverted, then closed terminal ( when HollowBlock messages appear). 

[log.txt](https://github.com/jwilm/alacritty/files/3109885/log.txt)

I will try to debug it with rr and gdb. I hope that I'll find something.

**Comment by kchibisov** [comment]
I've done some testing under gdb and figured out that this [`if`](https://github.com/jwilm/alacritty/blob/e9813031f6e308984cb5547aa1049839cb75745f/src/term/mod.rs#L379) in pair with its `else` returns absolutely the same things whether cursor final colors are broken or not, so probably the colors are fine here.

In my test I was moving from `(0,0)` cell in alacritty to `(1,0)`, both times from the same line in the file. CursorStyle - block, `cursor.cursor == Rgb(171,178, 191)`, `cursor.text == Rgb(40,44,52)`. Compiled alacritty with `--debug` and used `rust-gdb` as a debugger. The results of examining `return` statements with gdb `p` command are in the file. `If` branch is marked with `if:` and `else` with `else:` 
[log_next.txt](https://github.com/jwilm/alacritty/files/3110369/log_next.txt)

**Comment by evilr00t** [comment]
@kchibisov @chrisduerr 
For me a47d716 is fine, cfc20d4f34 introduced the problem.

**Comment by kchibisov** [comment]
@chrisduerr Here's some config files for you, to reproduce this issue. Just run alacritty with this config, open provided neovim config `nvim ~/.config/nvim/init.vim` and start moving cursor up and down (moving with `j,k` is enough to reproduce, no insert mode required). `xset r rate 200 60` can help you doing this. 
[init.vim.txt](https://github.com/jwilm/alacritty/files/3112211/init.vim.txt)
[alacritty.yml.txt](https://github.com/jwilm/alacritty/files/3112222/alacritty.yml.txt)

Let me know if you were able to do this.

**Comment by luisdavim** [comment]
running `reset` does solve the issue temporarily

**Comment by chrisduerr** [comment]
@kchibisov Thanks for looking into this. It looks to me like this is not related to the terminal logic but is caused somewhere in the renderer.

Unfortunately I'm not able to repro this bug even when using the files you've provided.

This is just a completely random guess, but could someone try applying this patch to 73e7a95d543ccd0e197c923e305d4d7c45e273d8 to see if that helps at all?

<details>

```diff
diff --git a/src/cursor.rs b/src/cursor.rs
index 196241a..6bcb4d3 100644
--- a/src/cursor.rs
+++ b/src/cursor.rs
@@ -55,7 +55,7 @@ pub fn get_underline_cursor_glyph(width: i32, line_width: i32) -> RasterizedGlyp
     let buf = vec![255u8; (width * line_width * 3) as usize];
 
     // Create a custom glyph with the rectangle data attached to it
-    RasterizedGlyph { c: ' ', top: line_width, left: 0, height: line_width, width, buf }
+    RasterizedGlyph { c: '\u{10a3e2}', top: line_width, left: 0, height: line_width, width, buf }
 }
 
 // Returns a custom beam cursor character
@@ -64,7 +64,7 @@ pub fn get_beam_cursor_glyph(height: i32, line_width: i32) -> RasterizedGlyph {
     let buf = vec![255u8; (line_width * height * 3) as usize];
 
     // Create a custom glyph with the rectangle data attached to it
-    RasterizedGlyph { c: ' ', top: height, left: 0, height, width: line_width, buf }
+    RasterizedGlyph { c: '\u{10a3e3}', top: height, left: 0, height, width: line_width, buf }
 }
 
 // Returns a custom box cursor character
@@ -86,7 +86,7 @@ pub fn get_box_cursor_glyph(height: i32, width: i32, line_width: i32) -> Rasteri
     }
 
     // Create a custom glyph with the rectangle data attached to it
-    RasterizedGlyph { c: ' ', top: height, left: 0, height, width, buf }
+    RasterizedGlyph { c: '\u{10a3e4}', top: height, left: 0, height, width, buf }
 }
 
 // Returns a custom block cursor character
@@ -95,5 +95,5 @@ pub fn get_block_cursor_glyph(height: i32, width: i32) -> RasterizedGlyph {
     let buf = vec![255u8; (width * height * 3) as usize];
 
     // Create a custom glyph with the rectangle data attached to it
-    RasterizedGlyph { c: ' ', top: height, left: 0, height, width, buf }
+    RasterizedGlyph { c: '\u{10a3e5}', top: height, left: 0, height, width, buf }
 }
```

</details>

**Comment by kchibisov** [comment]
@chrisduerr I've tried your diff, but the issue is still here. Also I'd add to my previous comments, that `reset` doesn't work for me, but the very important detail that i've just noticed is that changing the font size somehow fixes the cursor.

**Comment by chrisduerr** [comment]
I've got some more debug output which can be played with if anyone's interested. This should print rendering information about the cursor whenever the window is redrawn.

<details>

```diff
diff --git a/src/renderer/mod.rs b/src/renderer/mod.rs
index fd10c86..83c0109 100644
--- a/src/renderer/mod.rs
+++ b/src/renderer/mod.rs
@@ -429,6 +429,14 @@ impl Batch {
             self.tex = glyph.tex_id;
         }
 
+        if let RenderableCellContent::Raw(_) = cell.inner {
+            println!("---------------------------------");
+            println!("RENDERING CURSOR:");
+            println!("CELL: {:?}", cell);
+            println!("GLYPH: {:?}", glyph);
+            println!("---------------------------------");
+        }
+
         self.instances.push(InstanceData {
             col: cell.column.0 as f32,
             row: cell.line.0 as f32,
```

</details>

**Comment by kchibisov** [comment]
@chrisduerr , The output of normal and broken behaviors. As you can see they have different `tex_id`.I was testing on the same position in the file both times. Also changing font size restores `tex_id` to 1.

[normal.txt](https://github.com/jwilm/alacritty/files/3113865/normal.txt)
[broken.txt](https://github.com/jwilm/alacritty/files/3113866/broken.txt)

**Comment by chrisduerr** [comment]
Huh, I feel like we're getting somewhere!

Just to confirm my suspicion, could you add some debug output before this line:
https://github.com/jwilm/alacritty/blob/master/src/renderer/mod.rs#L1056

If my assumption is correct, as soon as this line is triggered and a new atlas is generated, the cursor will break.

**Comment by kchibisov** [comment]
Yes, I've testing your idea with `gdb` (also added `dbg!`). And it's getting broken somewhere after hitting this line.
![image_2019-04-24_22-53-13](https://user-images.githubusercontent.com/27620401/56689556-0bea6c80-66e4-11e9-8d62-fce4da3cd734.png)

**Comment by chrisduerr** [comment]
Great to hear we've got the issue narrowed down now, I'll take a look at why this might cause the cursor to disappear and hopefully there'll be a simple fix.

We might just have to hook it up to the cache and be good to go.

**Comment by ngortheone** [comment]
I am also affected by this. Started noticing this some time after upgrading to 0.3. As a temporary fix I change font size of the terminal with `Ctrl +` and cursor appears again.

**Comment by chrisduerr** [comment]
I think https://github.com/jwilm/alacritty/pull/2367 should fix it. Please let me know if you still see issues with this PR.

**Comment by FelipeMarcelino** [comment]
For me only fix changing the font size of the terminal. I have a function in zsh to change beam to block and block to beam when I enter and leave zsh mode. When a change to beam I am leaving neovim.

**Comment by kchibisov** [comment]
@FelipeMarcelino Do you mean, that #2367 is not working for you?

**Comment by FelipeMarcelino** [comment]
Sorry, I didn't make the update of alacritty last days. I think #2367 solved the problem.

**Comment by tiev** [comment]
Can the change be released now?
Because of this issue, I cannot use Alacritty now.

**Comment by svanharmelen** [comment]
Same here, I needed to manually change Homebrew so I could downgrade and cannot do a `brew cask upgrade` until this fix is out. So a new release with this fix would b very nice.

**Comment by ianbattersby** [comment]
Just to confirm the current master fixed the issue for me. Thanks all, it’s was killing me 🤦‍♂️

**Comment by luisdavim** [comment]
Yeah, there hasn't been a release in a while. When will this be released?

**Comment by chrisduerr** [comment]
I've initially planned to wait with the next release until the #2438 PR is merged and ready. However it looks like winit upstream is still going to take a while, so there'll be a new version soon. I'd expect a new RC this weekend at the latest.

**Comment by lockejan** [comment]
This is occurring again on my side, but so far only inside neovim (while using tmux). 
Once it occurs only a new window instance of alacritty solves it.
It doesn't seem to be related to tmux because attaching to the running tmux session within the new window where neovim is opened already renders everything correctly:
![Peek 2020-12-15 17-01](https://user-images.githubusercontent.com/25434434/102239647-5d69ef80-3ef7-11eb-9dfe-b3376d78f7e8.gif)


Running
- alacritty 0.6.0 (04cbf767)
