### ISSUE TITLE
3.x panic on Wayland 

### ISSUE THREAD

**Issue by stokhos** [jwilm/alacritty#2356]
Which operating system does the issue occur on?

If on linux, are you using X11 or Wayland?

I'm using Clear Linux gnome with wayland. Having problem  to start alacritty, but under X11 it works fine. 

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   4: rust_begin_unwind
             at src/libstd/panicking.rs:312
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::result::unwrap_failed
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/macros.rs:17
   7: <smithay_client_toolkit::window::concept_frame::ConceptFrame as smithay_client_toolkit::window::Frame>::redraw
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:798
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.5/src/window/concept_frame.rs:486
   8: <smithay_client_toolkit::window::Window<F>>::refresh
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.5/src/window/mod.rs:384
   9: winit::platform::platform::wayland::event_loop::EventsLoop::post_dispatch_triggers
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/wayland/event_loop.rs:272
  10: alacritty::main
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/wayland/event_loop.rs:205
             at ./.cargo/git/checkouts/alacritty-de74975f496aa2c0/4fbae5e/src/main.rs:104
  11: std::rt::lang_start::{{closure}}
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64
  12: main
  13: __libc_start_main
             at ../csu/libc-start.c:308
  14: _start
             at ../sysdeps/x86_64/start.S:120

**Comment by chrisduerr** [comment]
Can you reproduce this issue when running the examples from https://github.com/rust-windowing/winit?

It should be possible to execute them using `cargo run --example window`.

**Comment by chrisduerr** [comment]
It seems like this issue might be related to a missing `/etc/fonts/fonts.conf` file. So it is possible that this could be fixed by creating that file manually with some sane defaults.

Here's the default contents on Arch linux, let me know if that works for you:

<details>

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
		<its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
	</its:rules>
	<description>Default configuration file</description>
	<dir>/usr/share/fonts</dir>
	<dir>/usr/local/share/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<dir>~/.fonts</dir>
	<match target="pattern">
		<test qual="any" name="family">
			<string>mono</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>monospace</string>
		</edit>
	</match>
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans serif</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>
	<match target="pattern">
		<test qual="any" name="family">
			<string>sans</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>
	<include ignore_missing="yes">conf.d</include>
	<cachedir>/var/cache/fontconfig</cachedir>
	<cachedir prefix="xdg">fontconfig</cachedir>
	<cachedir>~/.fontconfig</cachedir>
	<config>
		<rescan>
			<int>30</int>
		</rescan>
	</config>
</fontconfig>
```

</details>

**Comment by stokhos** [comment]
@chrisduerr  Yes, adding fonts.conf fixed the problem. Thanks chris!

**Comment by stokhos** [comment]
@chrisduerr Hi Chris, i'm wondering if alacritty searches for fonts.conf from somewhere else? Cause by default there is no /etc/fonts/ directory, clear linux puts fonts.config in  /usr/share/defaults/fonts/.
This is an wayland specific problem, it workes without any problem in xorg.

**Comment by chrisduerr** [comment]
I think most distros put it in `/etc/fonts/` including Arch which is what I'm using.

This is because of one of our dependencies though and they're already working on a fix.
