### ISSUE TITLE
conda activate and alacritty

### ISSUE THREAD

**Issue by FSund** [jwilm/alacritty#2359]
I'm trying to replace cmd with alacritty on my Windows 10 machine, but I can't seem to get conda working (Anaconda is a Python distribution).

The standard "Anaconda Prompt" that gets added to the start menu when installing Anaconda is just a shortcut with Target

    %windir%\System32\cmd.exe "/K" C:\Users\filip\Anaconda3\Scripts\activate.bat C:\Users\filip\Anaconda3

I've tried modifying this to use alacritty instead, but none of the alternatives I've tried has worked. For example

    "C:\Program Files\Alacritty\alacritty.exe" -e C:\Users\filip\Anaconda3\Scripts\activate.bat C:\Users\filip\Anaconda3

or

        "C:\Program Files\Alacritty\alacritty.exe" -e "C:\Users\filip\Anaconda3\Scripts\activate.bat C:\Users\filip\Anaconda3"

I get a alacritty window that opens but then quickly disappears.

Any idea how I can manage this?

The contents of ´activate.bat´ are

    @REM Copyright (C) 2012 Anaconda, Inc
    @REM SPDX-License-Identifier: BSD-3-Clause
    @REM Test first character and last character of %1 to see if first character is a "
    @REM   but the last character isn't.
    @REM This was a bug as described in https://github.com/ContinuumIO/menuinst/issues/60
    @REM When Anaconda Prompt has the form
    @REM   %windir%\system32\cmd.exe "/K" "C:\Users\builder\Miniconda3\Scripts\activate.bat" "C:\Users\builder\Miniconda3"
    @REM Rather than the correct
    @REM    %windir%\system32\cmd.exe /K ""C:\Users\builder\Miniconda3\Scripts\activate.bat" "C:\Users\builder\Miniconda3""
    @REM this solution taken from https://stackoverflow.com/a/31359867
    @set "_args1=%1"
    @set _args1_first=%_args1:~0,1%
    @set _args1_last=%_args1:~-1%
    @set _args1_first=%_args1_first:"=+%
    @set _args1_last=%_args1_last:"=+%
    @set _args1=

    @if "%_args1_first%"=="+" if NOT "%_args1_last%"=="+" (
        @CALL "%~dp0..\condabin\conda.bat" activate
        @GOTO :End
    )

    @REM This may work if there are spaces in anything in %*
    @CALL "%~dp0..\condabin\conda.bat" activate %*

    :End
    @set _args1_first=
    @set _args1_last=

I've tried starting the regular Anaconda Prompt and starting alacritty from there, and that works as expected (the `conda` command is available), so perhaps there is a way to run `activate.bat` first and then automatically opening alacritty? The following does not work (`activate.bat` warns about `activate does not accept more than one argument`)

    %windir%\System32\cmd.exe "/K" C:\Users\filip\Anaconda3\Scripts\activate.bat C:\Users\filip\Anaconda3 "/K" alacritty.exe

**Comment by chrisduerr** [comment]
I'm not familiar with bat or anaconda, but if it works when running inside Alacritty but doesn't work when running with `-c` you might need to add a shell.

So something like `alacritty -e sh -c "echo 'test' && sleep 3"`. I'm not sure what the cmd equivalent of `-c` is, but with bash scripts this definitely works.

**Comment by FSund** [comment]
Your hint about adding a shell worked great.

With Target =

    "C:\Program Files\Alacritty\alacritty.exe" -e cmd.exe "/K" C:\Users\filip\Anaconda3\Scripts\activate.bat C:\Users\filip\Anaconda3

I get the Alacritty terminal I wanted. Commands and output isn't colored anymore, but that I can live without. It's also probably something to do with Anaconda, and not an issue with Alacritty.

**Comment by chrisduerr** [comment]
You might have more success with bash or powershell if you want colors. That is indeed a problem the Windows PTY interface has in some instances.

Glad this worked out!
