### ISSUE TITLE
Open the specified path or support AppleScript on macOS

### ISSUE THREAD

**Issue by Ji4n1ng** [jwilm/alacritty#2362]
Is there a way to let Alacritty open the specified path on macOS. As far as I know, we can use `open` command or AppleScript.

For iTerm:

```
tell application "iTerm"
    create window with default profile
    tell current session of current window
        write text "cd /foo/bar"
        end tell
    end tell
```

For Hyper, we can enter the following command in terminal

```
open -a Hyper ~/Desktop
```

**Comment by chrisduerr** [comment]
I'm not sure about the exact syntax anymore, but when I tried it at work something like `open -na alacritty --args --working-directory ~/Desktop` did work.

**Comment by Ji4n1ng** [comment]
It worked. Thank you very much! @chrisduerr
