### ISSUE TITLE
Display becomes corrupted in Emacs when inserting text

### ISSUE THREAD

**Issue by sammoth** [jwilm/alacritty#2363]
I am using Linux, and this happens the same in X or Wayland.

Inserting text before other text in Emacs causes corruption which only goes away when you resize the window.

![recode](https://user-images.githubusercontent.com/3324352/56716228-5b747b00-676c-11e9-89b8-a04320c38ac2.gif)

**Comment by sammoth** [comment]
I have tested back to v0.1.1 and the behaviour has always been the same

**Comment by sammoth** [comment]
After the text becomes corrupted, you can also fix it by telling Emacs to redraw (M-x redraw-display). Not sure if this means it's an Emacs bug?

**Comment by chrisduerr** [comment]
Can you reproduce this in any other terminal emulator like URxvt/Termite/XTerm?

I'd assume Emacs might be using a rare escape sequence that Alacritty does not support. Alternatively if you've changed the tab width in Alacritty that's definitely the issue. If you're not using the Alacritty terminfo that could also be a problem.

In general I think that most people use the Emacs GUI, but I think we should have enough users that something like this shouldn't go completely unnoticed. So I think there might be some config issue.

**Comment by sammoth** [comment]
Ah indeed, I'd changed the tab size and changing it back does fix this. Thanks.

**Comment by chrisduerr** [comment]
@sammoth Please note that you can absolutely change the tab size if you want to, however this requires also changing the tab size in your terminfo. The comment on the config option should explain this.
