### ISSUE TITLE
Mouse buttons stop working after hiding the window on MacOS

### ISSUE THREAD

**Issue by ikicic** [jwilm/alacritty#2364]
OS: MacOS Mojave

This has been bugging me for quite some time, but I finally managed to find a way to reproduce the problem. After hiding the Alacritty window (with Cmd+H), the mouse left/middle/right buttons stop working. Mouse wheel still works.
Tested with the default config file and the latest version from GitHub.

**Comment by chrisduerr** [comment]
Thanks for the report, but looks like this is a duplicate of https://github.com/jwilm/alacritty/issues/1465.
