### ISSUE TITLE
Build error when doing cargo install --git https://github.com/hwilm/alacritty

### ISSUE THREAD

**Issue by Alfro** [jwilm/alacritty#2366]
**Which operating system does the issue occur on?**
Ubuntu 18.04
**If on linux, are you using X11 or Wayland?**
X11

I tried running:
```cargo install --git https://github.com/hwilm/alacritty```
and I got the following error: 
```
error[E0658]: scoped lint `clippy::all` is experimental (see issue #44690)
 --> /home/alfro/.cargo/git/checkouts/alacritty-de74975f496aa2c0/73e7a95/copypasta/src/lib.rs:3:9
  |
3 | #![deny(clippy::all, clippy::if_not_else, clippy::enum_glob_use, clippy::wrong_pub_self_convention)]
  |         ^^^^^^^^^^^
```

What am I doing wrong? :(

Full command log:
[log](https://github.com/jwilm/alacritty/files/3117868/install.log)

**Comment by chrisduerr** [comment]
You need at least version 1.31.0 of Rust to build Alacritty. Please update your Rust toolchain.
