### ISSUE TITLE
Text disappearing in Neovim

### ISSUE THREAD

**Issue by voider1** [jwilm/alacritty#2370]
The issue occurs on MacOS, using Neovim inside of tmux. Alacritty version 0.32. 

When I edit code in Neovim all text below my cursor disappears. This happens at seemingly random moments. When I move my cursor the text reappears and when I move it again it disappears again.

Please tell me if I can provide any more information on the issue.

**Comment by chrisduerr** [comment]
https://github.com/jwilm/alacritty/issues/2353
