### ISSUE TITLE
Open alacritty will open iterm2

### ISSUE THREAD

**Issue by taigacute** [jwilm/alacritty#2373]
## Which operating system does the issue occur on?
macos 10.13.6
alacritty 0.3.2
## Problem
Open iterm2 when i open alacritty. you can see this pic
![term](https://user-images.githubusercontent.com/41671631/56843796-a7dcc980-68d8-11e9-8787-75365ae2a632.gif)

**Comment by chrisduerr** [comment]
Do you have iterm set as your shell in Alacritty? This definitely sounds like a configuration problem on your end that could probably be fixed without too much trouble.

**Comment by taigacute** [comment]
> 你在Alacritty中将iterm设置为你的shell吗？这肯定听起来像你的一个配置问题，可能没有太多麻烦修复。

i remove the `alacritty.yml`,but the problem still.

**Comment by taigacute** [comment]
my iterm2 setting
![iterm2](https://user-images.githubusercontent.com/41671631/56848682-50614c80-691e-11e9-8ae3-2a084da02b7d.png)

this pic show the key which trigger iterm2
![term](https://user-images.githubusercontent.com/41671631/56848712-adf59900-691e-11e9-8f4a-6a18d8cb3681.gif)

**Comment by chrisduerr** [comment]
I'm not quite sure if I'm understanding this correctly, but are you saying that when you run vi and press space inside of it, an iTerm2 window opens up?

Does this happen when running Alacritty with `alacritty --config-file /dev/null`?

**Comment by taigacute** [comment]
how can i use this `alacritty --config-file /dev/null` ?

**Comment by chrisduerr** [comment]
Oh since you're on macos, you'll probably have to find the binary in the `/Applications` folder.

I'm not sure exactly where it is since I don't have an apple device ready right now, but it should be something like `/Applications/Alacritty.app/Contents/alacritty`. It's probably the only binary in the subdirectories of `/applications/Alacritty.app/`.

**Comment by taigacute** [comment]
problem still exist

**Comment by chrisduerr** [comment]
Do you have any system-wide shortcuts to open iTerm or are you using third party software to define custom hotkeys?

**Comment by taigacute** [comment]
didnt set any key to open iterm2，Very strange phenomenon

**Comment by benmp** [comment]
Does this only occur after you open vim?

If that is the case, something in your .vimrc is probably pointed to open iterm2.

**Comment by taigacute** [comment]
i got this.  i set `$SHELL` in my vim
