### ISSUE TITLE
Bad font rendering, look like squares

### ISSUE THREAD

**Issue by Chofito** [jwilm/alacritty#2374]
Which operating system does the issue occur on?
Windows 10 Pro 1809

![Anotación 2019-04-26 212044](https://user-images.githubusercontent.com/15962745/56844165-33b70d00-6869-11e9-83bd-b548d3f2d6af.jpg)

**Comment by chrisduerr** [comment]
Which GPU are you using? This looks like an issue with support for Alacritty's shader version.

**Comment by Chofito** [comment]
![Anotación 2019-04-27 134812](https://user-images.githubusercontent.com/15962745/56854397-22b2de00-68f3-11e9-8143-44b49439b1ce.jpg)

**Comment by chrisduerr** [comment]
There are a lot of Intel HD Graphics out there. Something a little bit more specific would be helpful.

**Comment by Chofito** [comment]
Sorry 😅 
![image](https://user-images.githubusercontent.com/15962745/56854503-d072bc80-68f4-11e9-8183-b56029af5fa6.png)

**Comment by chrisduerr** [comment]
Your GPU does not support the OpenGL version required by Alacritty.

This is a duplicate of #128.
