### ISSUE TITLE
Copy/paste doesn't seem to work on Windows

### ISSUE THREAD

**Issue by steveklabnik** [jwilm/alacritty#2383]
I'm using alacritty 0.3.2, and I cannot copy/paste. The clipboard isn't modified after using `control-c`, middle click, or trying to use right click.

**Comment by chrisduerr** [comment]
The default bindings use ctrl+shift+c/v to copy/paste (see config [here](https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L480-L481)).

Using ctrl+c/v is not possible since ctrl+c is used for sending a signal to peacefully shut down the running application and ctrl+v is used to print raw input character codes.

Middle mouse copy is disabled by default on Windows since only one clipboard exist, though it's possible to enable it in the config in the [config](https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L339).

Middle mouse paste from the primary clipboard should work by default though, but I'm not sure if I've ever verified that on Windows.

**Comment by steveklabnik** [comment]
Did this change? I swear I used control-c previously.

Anyway, it seems that this works, so I'll close :)

**Comment by corndog2000** [comment]
Is there a way to enable right-click to paste?

**Comment by refaelsh** [comment]
> Using ctrl+c/v is not possible since ctrl+c is used for sending a signal to peacefully shut down the running application and ctrl+v is used to print raw input character codes.

@steveklabnik 
Well, I beg to differ please. [Cmder](https://cmder.net/) has it, and even cmd.exe has it.

**Comment by vladinator1000** [comment]
It would make life easier for future users if we changed to defaults to ctrl+c and ctrl+v

**Comment by jbulow** [comment]
Copy/paste is broken on linux as well. Any plans to support copy/paste on any platform in Alacritty?

**Comment by chrisduerr** [comment]
> Copy/paste is broken on linux as well.

It's not.

**Comment by dmelton-gpsw** [comment]
> > Copy/paste is broken on linux as well.
> 
> It's not.

I noticed that ctrl-shift-V works in windows, yes, but after SSH'ing to linux from there, it no longer works

**Comment by alephpt** [comment]
my copy experience on windows is very inconsistent. I can paste just fine, but it basically never actually copies what I have selected in the terminal. I end up having to use PowerShell and right click. 

Maybe I need to install wf-clipboard? 🧇

**Comment by John15321** [comment]
Its still not working on Windows

**Comment by MarcelHB** [comment]
The problem regarding copying on Windows appears to be located inside `winit` or beyond: if you switch the binding for copying to anything but C, it works.

Starting Alacrity with `--print-events`, I see that the key-down of C while holding Ctrl & Shift causes exactly nothing, unlike its key-up or anything else.

**Comment by kchibisov** [comment]
Some applications (AMD GPU driver) add a global binding like `ctrl+shift+c`, winit has nothing to do with that.

**Comment by MarcelHB** [comment]
That solves the mystery for me. 🙂

**Comment by clohrmann** [comment]
> Some applications (AMD GPU driver) add a global binding like `ctrl+shift+c`, winit has nothing to do with that.

THANK YOU. After way too long struggles, this finally solved it for me. I was close to ditching Alacritty because of this issue, while in the end it was some stupid keybinding of the GPU driver, which I never enabled or set up in the first place.

**Comment by zur1el** [comment]
> Some applications (AMD GPU driver) add a global binding like `ctrl+shift+c`, winit has nothing to do with that.

THIS, THANK YOU VERY MUCH.

**Comment by joshrig** [comment]
> Some applications (AMD GPU driver) add a global binding like `ctrl+shift+c`, winit has nothing to do with that.

Thank you!

**Comment by ualacg019** [comment]
> Some applications (AMD GPU driver) add a global binding like `ctrl+shift+c`, winit has nothing to do with that.

THIS OMG
