### ISSUE TITLE
Strange Tmux plus (powerline) font behaviour

### ISSUE THREAD

**Issue by jfdhuiz** [jwilm/alacritty#2384]
If I execute 'open /Applications/Alacritty.app' from Terminal or from the Dock my font is bad in Tmux. The powerline symbols fail to work (they are all underline instead). This only occurs in Tmux. With Fish they work in all 3 terminal applications.

The powerline symbols do work with Tmux in Terminal.app and iTerm2. However if I execute '/Applications/Alacritty.app/Contents/MacOS/alacritty' from Terminal.app or iTerm2 or Alfred the powerline symbols in Tmux also work.

Le me know if you you need more details and/or screenshots.

Which operating system does the issue occur on?
macOS

**Comment by chrisduerr** [comment]
If they don't work when just launching Alacritty, but they do work when launching Alacritty through iTerm2, my strong suspicion is that your locale might be different.

Could you compare the output of `locale` in an Alacritty window spawned by itself vs one spawned inside of iTerm2?

**Comment by jfdhuiz** [comment]
Thank you, that was the problem. Executing in Fish $ set -Ux LC_CTYPE UTF-8 # fixed the problem
