### ISSUE TITLE
Missing input when using a shortcut including `alt` key.

### ISSUE THREAD

**Issue by meengit** [jwilm/alacritty#2390]
Hi all

## System

|                  |                               |
|------------------|-------------------------------|
| Operating System | macOS 10.14.4                 |
| Rust Version     | stable 1.34.1                 |

## Summary

I recently updated from the last version of `0.2.X` to the current release. Now I have particular keyboard regressions when I use `alt`.

## Behavior

Custom keyboard settings in 0.2.X for eg. `|` and `@`:

```yml
  - { key: Key7,     mods: Alt,           chars: "\x7c" }
  - { key: G,        mods: Alt,           chars: "\x40" }
```

In 0.2.X the shortcuts worked as expected. Since I updated to the last version (0.3.X), they don't work anymore.

I've updated my `alactitty.yml` to the latest version of this repository. It doesn't help. However, if I do the mapping with `Command`…

```yml
  - { key: Key7,     mods: Command,           chars: "\x7c" }
  - { key: G,        mods: Command,           chars: "\x40"  }
```

 the characters appearing as expected.

![alacritty](https://user-images.githubusercontent.com/6507355/56958503-c0541a80-6b4a-11e9-9420-9d6e42f4678b.gif)

## Expectation

I need the "default" macOS behavior with `alt`.

## Extra

Maybe issues #458, #1054, #1336 or #1349 are connected in a way and I didn't understand them properly. In this case: Sorry for spam.

**Comment by chrisduerr** [comment]
Does this work when using `alt_send_esc: false` in the config?

**Comment by meengit** [comment]
Hi @chrisduerr 

Setting `alt_send_esc: true` to `alt_send_esc: false` solves the problem. Thank you very much. 

I close this issue.

**Comment by bfqrst** [comment]
Oh thanks for this, it was driving me crazy after upgrading to 0.3.x!
