### ISSUE TITLE
Alacritty freezes on pasting from empty clipboard

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#2392]
When pasting from empty clipboard alacritty gets frozen for 3-4 seconds. 
Arch Linux with  X11
( #2391 doesn't fixed it for me )

**Comment by nixpulvis** [comment]
I can confirm this is happening to me as well, in the same OS environment.

**Comment by nixpulvis** [comment]
Related issue in one of our new dependencies: aweinstock314/rust-clipboard#54.

**Comment by quininer** [comment]
This is a bug in x11-clipboard, I just published 0.3.2 to fix it.

**Comment by chrisduerr** [comment]
@quininer Thanks a lot for that! The fix seems to work great based on my testing.

What is the need for the timeout if this is not intentional? Is there a different way this might timeout?

**Comment by quininer** [comment]
X11 has many different implementations (both client and server) and it's hard to keep them reliable. If the other party panic after sending notify, we may never receive message.
