### ISSUE TITLE
cargo deb yields Str

### ISSUE THREAD

**Issue by Quintasan** [jwilm/alacritty#2393]
Running `cargo deb --install` on Ubuntu 18.04 yields

```
╭─quintasan@shirase ~/sauce/alacritty ‹2.6.2› ‹master› 
╰─$ cargo deb --install
cargo-deb: Str
```

I tried it on `v0.3.2` and it worked flawlessly

**Comment by Quintasan** [comment]
Oh, I'm actually dumb. I had to go to `alacritty` directory inside the repository.

**Comment by Quintasan** [comment]
This could be mentioned in the readme

**Comment by chrisduerr** [comment]
https://github.com/jwilm/alacritty/blob/master/INSTALL.md#debianubuntu-1

**Comment by Quintasan** [comment]
@chrisduerr silly me, was running on master so long I didn't notice until my cursor started disappearing and I wanted to rebuild

**Comment by Quintasan** [comment]
@chrisduerr so yeah
