### ISSUE TITLE
Segfault on start

### ISSUE THREAD

**Issue by Kazimazi** [jwilm/alacritty#2399]
Which operating system does the issue occur on?
Gentoo 

If on linux, are you using X11 or Wayland?
Wayland - Sway wm

Alacritty version: 3.2

When I ran `alacritty` I got `segmentation fault`. `RUST_BACKTRACE=1` didn't add any extra debugging output. when I ran it with sudo:
```
$ sudo RUST_BACKTRACE=1 alacritty
No protocol specified
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /var/tmp/portage/x11-terms/alacritty-0.3.2/work/cargo_home/gentoo/winit-0.19.1/src/platform/linux/mod.rs:450:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: __libc_start_main
   9: <unknown>
```
By the error I thought adding xdg_runtime_dir (`export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir`) would make a difference, and actually it did solve the problem. I tested it with `elogind` session manager (at least I hope it's called that).
What should be done about the issue?
Edit: `elogind` sets `XDG_RUNTIME_DIR=/run/user/1000` but alacritty wouldn't start with it.

**Comment by chrisduerr** [comment]
Am I understanding correctly that you use Gentoo without systemd and the `logind` replacement `elogind` does not set the environment variables to what would be expected with `logind`?

**Comment by Kazimazi** [comment]
Exactly, no systemd. Furthermore I get the same buggy behavior using `consolekit`.

**Comment by chrisduerr** [comment]
It seems like this is a configuration issue. Wayland expects to find its socket in the `XDG_RUNTIME_DIR` and if it is set to a different value it is not possible to detect if Wayland support is present.

So you'll have to make sure that `XDG_RUNTIME_DIR` is set according to what Wayland expects to be able to run native Wayland clients properly.

**Comment by Kazimazi** [comment]
I had a full system update and alacritty seems to just work. I don't know what could be the difference... still `XDG_RUNTIME_DIR=/run/user/1000`
Closing
