### ISSUE TITLE
Bug: Terminfo doesn't update window title

### ISSUE THREAD

**Issue by Limero** [jwilm/alacritty#2401]
If I use alacritty's terminfo files, the window title of terminals only display "Alacritty", but if I use the next default (xterm-256color), it is updated correctly.

What a new terminal window's title looks like with `TERM: xterm-256color`:
username@hostname:~

What it looks like with `TERM: alacritty`:
Alacritty

I'm using:
Arch Linux, Wayland (Sway), alacritty 0.3.2

**Comment by chrisduerr** [comment]
Which program are you expecting to set that title? Your shell?

This might be a bug in your shell if it's matching against your terminfo name to detect capabilities rather than checking terminfo.

**Comment by Limero** [comment]
I just copied `xterm-256color` to `alacritty-test` in `usr/share/terminfo/` and used it. The window title is "Alacritty", which means the problem must be in the shell? I use regular bash, so nothing fancy. Should this be reported upstream?

**Comment by chrisduerr** [comment]
> Should this be reported upstream?

If using `xterm-256color` works, but renaming it doesn't, this is not an Alacritty issue and there's nothing we can do about it. Now if this is done by the shell, or some other part of your profile/rc, I don't know. But it's the 'fault' of whatever is trying to set the title and using the terminfo name to do so.
