### ISSUE TITLE
Can't type anything if failed to parse ~/.XCompose file in Wayland

### ISSUE THREAD

**Issue by fhs** [jwilm/alacritty#2403]
Which operating system does the issue occur on?

Archlinux

If on linux, are you using X11 or Wayland?

Wayland

With ~/.XCompose file below, alacritty opens but I can't type anything in it. This issues only occurs in Wayland, only when I have the ~/.XCompose file. Everything works in X11 (even with the ~/.XCompose file).
```
$ alacritty --version
alacritty 0.3.2
$ cat ~/.XCompose
<Multi_key> <X> <0> <0> <7> <f> : "" U007F
<Multi_key> <X> <0> <0> <8> <0> : "" U0080
<Multi_key> <X> <0> <0> <8> <1> : "" U0081
<Multi_key> <X> <0> <0> <8> <2> : "" U0082
<Multi_key> <X> <0> <0> <8> <3> : "" U0083
<Multi_key> <X> <0> <0> <8> <4> : "" U0084
<Multi_key> <X> <0> <0> <8> <5> : "" U0085
<Multi_key> <X> <0> <0> <8> <6> : "" U0086
<Multi_key> <X> <0> <0> <8> <7> : "" U0087
<Multi_key> <X> <0> <0> <8> <8> : "" U0088
<Multi_key> <X> <0> <0> <8> <9> : "" U0089
$ cage alacritty
xkbcommon: ERROR: /home/fhs/.XCompose:1:39: unrecognized keysym "U007F" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:2:40: unrecognized keysym "U0080" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:3:40: unrecognized keysym "U0081" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:4:40: unrecognized keysym "U0082" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:5:40: unrecognized keysym "U0083" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:6:40: unrecognized keysym "U0084" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:7:40: unrecognized keysym "U0085" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:8:40: unrecognized keysym "U0086" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:9:40: unrecognized keysym "U0087" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:10:40: unrecognized keysym "U0088" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:11:40: unrecognized keysym "U0089" on right-hand side
xkbcommon: ERROR: /home/fhs/.XCompose:11:40: too many errors
xkbcommon: ERROR: /home/fhs/.XCompose:11:40: failed to parse file
libEGL warning: FIXME: egl/x11 doesn't support front buffer rendering.
```

**Comment by nixpulvis** [comment]
I've never used `cage` before. Does running Alacritty as a normal application work as expected?

**Comment by chrisduerr** [comment]
These look like `xkbcommon` errors. I've never used XCompose before, but is the syntax actually correct? `xkbcommon` is telling you that your file contains too many errors, so I'd assume you'd probably want to fix those?

Does this work without any of these faulty binds set?

**Comment by fhs** [comment]
> I've never used `cage` before. Does running Alacritty as a normal application work as expected?

Sorry, `cage` is just an example. I've reproduced the issue in `sway` and (the newly released) `wio`.

> These look like `xkbcommon` errors. I've never used XCompose before, but is the syntax actually correct? `xkbcommon` is telling you that your file contains too many errors, so I'd assume you'd probably want to fix those?
> 
> Does this work without any of these faulty binds set?

The syntax is right. It just does't like the keysyms. It only fails after more than 10 of those errors.

The issue I wanted to raise is that alacritty should provide better diagnostics. It should just exit (with a good error message) if xkbcommon fails with parse error. I don't see the point of opening a window if I can't type in it. It confuses the user on what's going on.

I also find it strange that it works in X11 but not in Wayland.

**Comment by chrisduerr** [comment]
We have absolutely nothing to do with how `xkbcommon` parses its config files.

That also means there's no way for us to tell if things will work or not. If the user breaks his system, there's little Alacritty can do to stop them.

If you desire xkb to handle the XCompose file without failing and falling back to a saner mode of operation by default, this should probably be addressed with xkb.

An error in Alacritty's configuration file should always be properly handled by Alacritty and never lead to failure, but with an error in system setup there's nothing Alacritty has control over.
