### ISSUE TITLE
Alacritty triggers /boot to be mounted by systemd

### ISSUE THREAD

**Issue by Mandragorian** [jwilm/alacritty#2411]
Which operating system does the issue occur on?

If on linux, are you using X11 or Wayland?

Archlinux, X11.

I have an nvidia card, but I do not have the driviers installed, so I am using the Intel graphics.

I have recently noticed that alacritty tries to access the /boot partition when starting up. I noticed this because my /boot filesystem is in a separate partition and I saw in the logs for the boot.automount systemd service, that it was triggered by alacritty.

I am not sure if this is a bug or not, or even related with alacritty at all. Is this expected behaviour?

**Comment by chrisduerr** [comment]
As mentioned in IRC, this is not expected behavior. There's nothing in Alacritty directly trying to access /boot.

Have you tried a different shell and an empty Alacritty config?

**Comment by Mandragorian** [comment]
Thanks for the response.

I straced alacritty and show that it was searching some terminfo files in the /boot filesystem. It did so after searching in other directories for these files and failing to find them. After installing the `alacritty-terminfo` package, provided by archlinux, it can find the files and doesn't try to look for them in the /boot directory anymore.

**Comment by chrisduerr** [comment]
Ah, that's unrelated to Alacritty then and is done by the terminfo library.

Though it's hardly a bug, it's just searching for a terminfo file that doesn't exist and it can't find it.
