### ISSUE TITLE
Advanced shell arguments support?

### ISSUE THREAD

**Issue by dmilith** [jwilm/alacritty#2417]
I'm using OSX 10.14.x (latest):

```
# shell:
#   program: /Software/Zsh/exports/zsh
#   args:
#     - -c /Software/Weechat/exports/weechat
```

Is there any detailed information how to do trick like that? My wish is to autostart weechat with Alacritty on shell start :)

p.s. Thanks for this great project!

**Comment by chrisduerr** [comment]
You can only specify one parameter per line. So `-c` and the string you want to pass to it need to be on separate lines.

**Comment by dmilith** [comment]
Ah! Cool! Thanks!
