### ISSUE TITLE
Message bar messing up PTY

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#2418]
The message bar which is displayed for warnings and errors can apparently mess up applications like Vim. This is likely because the PTY is not resized appropriately.

I was not yet able to reproduce this myself, it has only been reported to me on IRC.

**Comment by kchibisov** [comment]
FYI, I can reproduce this. My neovim after message bar appearing looks like the following ( double airline prompts ). After changing terminal size (e.g. toggle fullscreen layout in awesome wm), everything is fine again.
![Screenshot-Mon_06_May_2019_42](https://user-images.githubusercontent.com/27620401/57226939-ce0d1280-7018-11e9-867e-ad0429bab8b8.png)
