### ISSUE TITLE
Alacritty produce different font and window size depending on Xorg or Wayland

### ISSUE THREAD

**Issue by Porkepix** [jwilm/alacritty#2422]
Which operating system does the issue occur on?
ArchLinux

If on linux, are you using X11 or Wayland?
Both

While testing for another issue and because back when I tried Alacritty some time ago I had some font size issue, I tried opening it in both Xorg and Wayland (Gnome in either cases).

While the hardware nor the configuration file didn't changed (default conf, laptop 14", 1920x1080), font was quite bigger in Xorg and if I remember correctly, window size too.
My feeling is that for identical configuration and screen, it should have the exact same result.

**Comment by chrisduerr** [comment]
DPI is likely different I'd assume.

So if you launch Alacritty with `alacritty -v`, do you get different values for `Device pixel ratio`?

**Comment by Porkepix** [comment]
Here are the results; same computer, same screen (laptop's screen), same Arch install, same (default) config file.

Gnome & Wayland
```
$ alacritty -v
Created log file at "/tmp/Alacritty-11163.log"
[2019-05-06 19:48] [INFO] Welcome to Alacritty
[2019-05-06 19:48] [INFO] Configuration loaded from "/home/clement/.config/alacritty/alacritty.yml"
[2019-05-06 19:48] [INFO] Device pixel ratio: 1
[2019-05-06 19:48] [INFO] Initializing glyph cache...
[2019-05-06 19:48] [INFO] ... finished initializing glyph cache in 0.024090797s
[2019-05-06 19:48] [INFO] Width: 1024, Height: 768
[2019-05-06 19:48] [INFO] Cell Size: 9 x 17
[2019-05-06 19:48] [INFO] Padding: 2 x 2
[2019-05-06 19:48] [INFO] PTY Dimensions: Line(44) x Column(113)
[2019-05-06 19:48] [INFO] Initialisation complete
[2019-05-06 19:48] [INFO] Width: 1024, Height: 738
```

Gnome & Xorg
```
$ alacritty -v
Created log file at "/tmp/Alacritty-12061.log"
[2019-05-06 19:49] [INFO] Welcome to Alacritty
[2019-05-06 19:49] [INFO] Configuration loaded from "/home/clement/.config/alacritty/alacritty.yml"
[2019-05-06 19:49] [INFO] Device pixel ratio: 1.6666666666666667
[2019-05-06 19:49] [INFO] Initializing glyph cache...
[2019-05-06 19:49] [INFO] ... finished initializing glyph cache in 0.037580026s
[2019-05-06 19:49] [INFO] Width: 1707, Height: 1280
[2019-05-06 19:49] [INFO] Cell Size: 15 x 28
[2019-05-06 19:49] [INFO] Padding: 3 x 3
[2019-05-06 19:49] [INFO] PTY Dimensions: Line(45) x Column(113)
[2019-05-06 19:49] [INFO] Initialisation complete
[2019-05-06 19:49] [INFO] Width: 1707, Height: 1016
[2019-05-06 19:49] [INFO] Width: 1920, Height: 1016
```

With Xorg, window was maximized and font way larger, while Wayland had a non-maximized window.

**Comment by chrisduerr** [comment]
Yeah, the DPR is different and as a result it's expected that the font and window will be larger. This is the expected behavior.

**Comment by Porkepix** [comment]
@chrisduerr I don't know what is DPR, but I don't get how it could be expected to get different result with the same hardware and same alacritty configuration…?
So, it means you can't have a configuration working on both graphic servers…?

**Comment by chrisduerr** [comment]
DPR is the DPI scaling factor. On X11 the DPI is detected automatically based on monitor dimensions, in Wayland you might have to configure it yourself.

It's perfectly possible to have the same configuration working on both display servers, but you should also have the display servers configured the same way.

**Comment by Porkepix** [comment]
Mmmmh, my feeling is that you shouldn't need to configure your display servers for such simple and basic things, it should work out of the box.
But I might lack knowledge about display servers resulting in not knowing why it should be "configured".

(I didn't configured anything regarding mines, just installed them and use them as they are without customizing anything).

**Comment by chrisduerr** [comment]
DPI scaling is a very complex and opinionated matter, so it is by no means 'simple'.

However if you have a DPI value of 1 on Wayland and wish to have the same behavior on X11, you can add `WINIT_HIDPI_FACTOR: 1` to the `env` section of your config. That will get you the same font sizes for both display platforms.

**Comment by Porkepix** [comment]
Well, what I don't get is, correct me if I'm wrong, that DPI is calculated considering screen measures (inchs) and resolution (pixels), which lead to calculate the number of pixels in one square inch of screen.
Considering screen size doesn't vary, neither does screen resolution, it seems logical to me to conclude that calculated DPI should always be the same?

**Comment by chrisduerr** [comment]
It's only calculated this way on X11, since it's not possible to set a per-monitor DPI value on X11.

Wayland allows setting per-monitor DPI values, which means that Alacritty does not need to calculate it automatically itself but can just use the per-monitor DPI values set by Wayland.

**Comment by Porkepix** [comment]
Shouldn't those have an impact only on multi-monitor setup?
The way I understand your explanation is that as X11 isn't able to set a per-monitor value, it's going to calculate a mean between the different monitors if you have more than one, but if you only use a single one, it should lead to the same result as a per-monitor one?

**Comment by chrisduerr** [comment]
This is done on X11 regardless of how many monitors are *currently* plugged in.

**Comment by Porkepix** [comment]
It's still a bit unclear to me as I understand that you can only calculate DPI by considering the hardware you're currently running. I don't want to be too much troublesome asking question over question, maybe have you some reading to point out on the topic, letting me understand how each of these servers calculate this and how it can end up with a different result with the exact same parameters?

**Comment by chrisduerr** [comment]
X11 is not able of calculating per-monitor at all by itself, it needs to be done by the Application (Alacritty in this case).

Wayland is able to do this itself, however it often relies on user configuration rather than automatic calculation, so it means you need to specify the correct values.

There are a lot of resources regarding DPI for both Wayland and X11, though I can not give you any concrete reference point. But if you're interested in the topic doing some research yourself will likely yield plenty of results.
