### ISSUE TITLE
alacritty failing to open by itself

### ISSUE THREAD

**Issue by h8ed** [jwilm/alacritty#2432]
Which operating system does the issue occur on? Linux
--
If on linux, are you using X11 or Wayland? X11
--
Since a few days ago, whenever opening alacritty by itself, for example by typing `alacritty` in another terminal emulator, alacritty fails to open, giving me the error message " `[2019-05-09 13:51] [ERROR] Failed to spawn command: No such file or directory (os error 2)`.

However, I'm often in tmux so my keybind in AwesomeWM is to open `alacritty -e tmux`, which works perfectly fine, no errors. Same goes for typing `alacritty -e tmux` in another terminal emulator.

So, is there any idea as to whats causing this issue?

**Comment by chrisduerr** [comment]
Please make sure that tmux is in your path, otherwise this will not work.

**Comment by h8ed** [comment]
I'm confused -- It works fine when called with tmux as an argument with `-e`. The issue is when I try to open alacritty by itself. What would tmux being in my path or not change>

**Comment by h8ed** [comment]
As a side note, uninstalling and reinstalling did nothing.

**Comment by chrisduerr** [comment]
Oh, I think I misunderstood. You're saying that just `alacritty` does not work without tmux involved at all?

Did you modify the configuration file?

**Comment by h8ed** [comment]
Yes, I did, and I think someone figured out the issue -- I had un-commented
```
# shell:
#   program: /bin/bash --login
```
while I was testing different shells. Re-commenting it fixed the issue. I don't remember if I added the `--login` part or not, but that could've been what was causing the issue.
