### ISSUE TITLE
Can't open urls in tmux

### ISSUE THREAD

**Issue by karambaq** [jwilm/alacritty#2437]
MacOS 10.14.4

![Запись экрана 2019-05-12 в 20 30 05](https://user-images.githubusercontent.com/14233969/57585793-9a892700-74f5-11e9-87ef-fd33c74429c2.gif)

Don't sure is it alacritty issue or not. But in iTerm2 it works like expected.

**Comment by chrisduerr** [comment]
Press shift.

**Comment by karambaq** [comment]
@chrisduerr Oh god thank you, is there a way to change it to `control`?
