### ISSUE TITLE
feature request: delayed key_bindings

### ISSUE THREAD

**Issue by gilligan** [jwilm/alacritty#2442]
I would like to be able to use the following bindings:

```
  - { key: LShift,                  chars: "("                               }
  - { key: RShift,                  chars: ")"                               }
```

These mimic what I had previously achieved in a more generic way using [xcape](https://github.com/alols/xcape) but xcape has no effect for wayland backed applications. 

The above binding *does* actually work, the problem is that it will of course map both Shift
keys to "(" and ")" pretty much immediately making it hard to trigger their modifier behavior at all.
xcape defines a default timeout, which can also be configured:

> -t <timeout ms>
> If you hold a key longer than this timeout, xcape will not generate a key event. Default is 500 ms.

Would adding a `timeout` argument be feasible/acceptable for alacritty at all? Thank you.

**Comment by chrisduerr** [comment]
What exactly are you trying to achieve by inserting parenthesis whenever pressing shift?

I'm not sure I understand the usecase here, but I don't think there's much benefit in adding this additional complexity to Alacritty. I don't see it used much in the context of a terminal emulator and it might be better suited for a shell or editor config.

**Comment by gilligan** [comment]
Did you have a brief look at xcape? I guess that would have cleared it up.

The idea is simply to reuse modifier keys as something else when they are not pressed together with a different key.  Obviously you still want to use your modifier keys as such though, hence the timeout.

The only reason i even brought this up is because *(a)* alacrity does have a quite seemingly generic key mapping logic and *(b)* wayland does not currently allow for any such mappings/modifications in a generic way at all.

That being said I completely understand if you say that this is something you’d rather not want to add to as it adds complexity and probably only makes a very few people very happy ;)

**Comment by nixpulvis** [comment]
Hmmm it's unfortunate this isn't possible in wayland if that's the case. But I don't love the idea in the terminal itself.

As an aside, I have a keyboard that uses QMK firmware, and it would allow for this. Open source keyboard firmware is clearly the best way to implement this for me personally, but of course not all keyboards support this.

**Comment by nixpulvis** [comment]
I'm not sure I agree about the timeout though. Ideally there would be no timeouts in my keyboard input. A modifier key down and key up without other key down states detected (either new or existing) should provide an action, instantly.

Am I missing something?

**Comment by gilligan** [comment]
Yes, right..if the modifier is pressed and released again without any other key being pressed should yield the mapped key
