### ISSUE TITLE
support for background images

### ISSUE THREAD

**Issue by taigacute** [jwilm/alacritty#2446]
## FeatureRequest

support for set background images in alacritty. i think its a good feature. i saw this  [issue#565](https://github.com/jwilm/alacritty/issues/565), I hope that you can reconsider this proposal.The background color of the solid color very depressed sometimes。 in iterm2 i can set bg img 。look like this，its very nice when writing  code for me。
![thinkvimnew](https://user-images.githubusercontent.com/41671631/57820822-d572af80-77c0-11e9-9c4f-b7bf9982c4cb.png)

**Comment by chrisduerr** [comment]
Duplicate of #565.

**Comment by taigacute** [comment]
@chrisduerr  hi  why close this issue ? i think reopen it cause we need to discuss it

**Comment by chrisduerr** [comment]
Feel free to leave your opinion below the original issue. Creating a bunch of duplicate issue is just going to make it harder to track interest.

However it is unchanged that there currently is no plan to support this.
