### ISSUE TITLE
Scroll-able window? [Feature Request]

### ISSUE THREAD

**Issue by saifali96** [jwilm/alacritty#2448]
Which operating system does the issue occur on?
`windows` - Windows 10

**Comment by chrisduerr** [comment]
What exactly do you mean? Alacritty supports scrollback.

**Comment by saifali96** [comment]
@chrisduerr please check the image below:
![image](https://user-images.githubusercontent.com/6160857/57862768-3027fd80-77f9-11e9-8413-742c122fbc69.png)

**Comment by saifali96** [comment]
Just FYI, I also tried without `tmux`, the scrollbar option on the right doesn't show up.

Also if you try to just scroll with the trackpad or the mouse, it doesn't scroll either.

**Comment by chrisduerr** [comment]
Alacritty does not show any scrollbar. If you're running tmux, it has a separate scrollback buffer.

Please make sure that you actually have lines in the scrollback, otherwise you obviously won't be able to scroll back.

**Comment by saifali96** [comment]
@chrisduerr thanks, just figured that out. First day with `tmux`.

Closing this issue down.
