### ISSUE TITLE
Changing font breaks the program

### ISSUE THREAD

**Issue by Actalica** [jwilm/alacritty#2455]
I am using Arch Linux x64, Linux 5.1.2 under X11 and I am using i3 (if that makes any difference).

If I try to change the fonts it shows me this: https://i.imgur.com/bu0XDIV.png and if I go to the line that has the problem I see nothing out of the ordinary: https://i.imgur.com/XeR7aHs.png
I haven't changed anything other than the colors.

**Comment by cole-h** [comment]
Looks like you forgot to uncomment `normal:` on line 90. Can you see if that fixes your problem?

**Comment by Actalica** [comment]
That's correct. If I uncomment this line it fixes the problem. Thank you for your time.

1.
