### ISSUE TITLE
Windows 10 - text rendering artifacts after adjusting DPI scaling in Windows settings

### ISSUE THREAD

**Issue by coldiron** [jwilm/alacritty#2456]
On Windows 10, if you adjust DPI scaling down in the OS, and then lower the font size in Alacritty, text will be rendered with artifacts:
![image](https://user-images.githubusercontent.com/4825148/57957522-2fa76980-78c2-11e9-9a42-b84b027952f3.png)

This is built on the latest commit.

If you keep hitting ctrl+= or ctrl--, there are certain sizes that don't have artifacts, but others that do. Eventually, after changing the size enough times, the artifacts disappear altogether, but return after a short while.

**Comment by coldiron** [comment]
This is built on the latest commit.

**Comment by coldiron** [comment]
> Eventually, after changing the size enough times, the artifacts disappear altogether.

Addendum: the artifacts returned again after a short while.

**Comment by chrisduerr** [comment]
Does this only happen to active instances when changing the DPI while they're running or also for new instances when the DPI has been changed?

**Comment by coldiron** [comment]
It only affects active instances.

**Comment by benpye** [comment]
I'll try and take a look at this this weekend since I added the DirectWrite backend - I never tested changing DPI and font size together.

**Comment by chrisduerr** [comment]
> it doesn't seem that we update the rasterizer on a DPI change

That's not correct, at least for the other backends. If you take a look at the rasterizer trait, there should be an `update_dpr` method or something similar:

https://github.com/jwilm/alacritty/blob/master/font/src/lib.rs#L267-L268

**Comment by benpye** [comment]
You are totally right and I'm updating it there.. Hm.

`update_font_size` is being called correctly - and we do clear the cache and get the metrics again. I'm certainly a little more confused.

It seems to me that something is going on beyond the font rasterizer:

I have added some logging to `handle_resize` as that's where we seem to capture resize/DPI change events, specially I have added the following - in addition to logging in the rasterizer's `update_dpr` function.

display.rs:348
```rust
// Take most recent resize event, if any
while let Ok(size) = self.rx.try_recv() {
    new_size = Some(size);

    println!("New size {} {}", size.width, size.height);
}
```

This gives the following output, comments to line up with events:

```
// Started at DPI 1
New size 1904 990
New size 1024 768
// Console is now visible
// Select 125% DPI
New size 817.6 608
DPI Changed to 1.25
New size 1282 962
// Console is now visible at 125% - no artifacts
// Now select 100%
New size 1280 960
DPI Changed to 1
// Reset to 100% DPI - still no artifacts
// Now select 125% DPI
New size 1025.6 769.6
DPI Changed to 1.25
// And broken
```

It seems to me that changing DPI to 125 and back to 100 should result in the same size.

Additionally the fractional size seen when we start seeing artifacts is suspicious.

@chrisduerr @zacps Any ideas?

**Comment by chrisduerr** [comment]
In my experience these artifacting issues usually pop up when the projection doesn't quite match the rendered output. So stretching a 100x100 grid over 200x200 pixels for example.

Some of the reasons that could cause this would be incorrect font metrics, but it's also possible the projection isn't updated correctly.

As a first step I'd verify what the commit was that broke this, assuming that it worked previously. I wouldn't make assumptions that it was directwrite that broke this until it has actually been confirmed.

So my first step would be to bisect the exact commit that caused this issue (or to check if it always has been an issue).

**Comment by benpye** [comment]
Alright, I'll try and work through that - though I've quickly eliminate DirectWrite as the issue, at least exclusively, as 0.3.2 also reproduces the issue.

**Comment by benpye** [comment]
Okay I've investigated a little, it seems that removing the call to `draw_rects` stops us getting any artifacts. This makes me wonder if we're correctly resetting the OpenGL state after the rects are drawn but I can't put my finger on anything specifically.

We do still have a different issue with Windows - changing DPI results in the terminal getting offset.

![Offset term](https://user-images.githubusercontent.com/442623/58060096-8318f200-7b24-11e9-9fe1-e68389c0e4d0.png)

FYI: On master removing this call fixes the artifacting too.

**Comment by chrisduerr** [comment]
We should be correctly resetting things, especially since this issue doesn't exist on Linux or macOS. However additional steps might be necessary on Windows?

**Comment by davidhewitt** [comment]
I've created a PR #2846 to fix the terminal offsetting above. As a side effect seems it seems to also no longer create these artifacts when changing the DPI scaling. Does someone else want to try with that patch and see whether that's solved it for them too?
