### ISSUE TITLE
Key binding `mode`s need docs

### ISSUE THREAD

**Issue by OJFord** [jwilm/alacritty#2457]
The readme/wiki/sample config does not currently explain what `AppCursor`, `AppKeypad`, `Alt`, or the `~` modify mean.

Additionally, the wiki points to the sample config for an explanation, but uses line numbers on master, which have clearly changed since it was written. (If it's going to use line numbers, to highlight the relevant section, then it should point at a specific commit, not master.)

The sample config does not include `Alt`/`~Alt` in available values, though it does use them in a couple of examples.

**Comment by chrisduerr** [comment]
Thanks for the issue. Just to be clear these are terminal  modes like the alt screen mode (`Alt`) which can be used to restrict certain keys to only the normal or alternate screen buffer. `~` matches whenever a mode is **not** active.

Documenting this properly certainly makes sense and of course all valid values should be presented. Though this is likely useless for users and primarily used to make the default bindings work properly.

**Comment by OJFord** [comment]
Thanks, I think `~` is fairly self-evident (a comment would be friendly though) - I was just struggling to see which I needed and eventually found it as Alt in an issue. (The nane makes perfect sense, once you know about 'alt screen'!)

I'd be happy to write something that I think would've helped, but I confess I still don't know what the other two are for!

**Comment by chrisduerr** [comment]
> I confess I still don't know what the other two are for!

There's an escape sequence to switch the Cursor Keys and Keypad Keys between normal and application mode. In these modes the escape sequences sent are different. That's what they are for, since we need to send other escape sequences to comply with the official standard.

**Comment by nixpulvis** [comment]
I've at least started by fixing the Wiki link to be a perma link to the correct place for now.

I'd be interested in making this more clear in the default config. I'll have a PR ready soon, possibly with some questions.
