### ISSUE TITLE
Option to auto-hide mouse when typing

### ISSUE THREAD

**Issue by garyemerson** [jwilm/alacritty#246]
Terminal.app has this feature and I've always liked it. It's probably not for everyone so it'd be cool if it was exposed in the config.

**Comment by TheGreatPanda** [comment]
I'd like this too, it's standard in pretty much every application that deals with text input on macOS.

**Comment by NickeZ** [comment]
Shouldn't your operating system implement this?

**Comment by casey** [comment]
Native cocoa apps on macOS using the text input widgets that apple provides do get this functionality automatically.

However, alacritty does all of its text rendering and input handling itself, so this would need to be provided by alacritty.

**Comment by siiptuo** [comment]
Other terminal emulators on X11 will hide cursor when typing. There are also options like [unclutter](https://wiki.archlinux.org/index.php/unclutter) to do this globally.

**Comment by hhsnopek** [comment]
@siiptuo, as @casey stated, this should also work on osx correct? I've recompiled and added the option in my config, but I'm unable to enable this - any insight?

**Comment by jwilm** [comment]
@hhsnopek I think it might be a bug in Glutin. I've also been unable to get the I-beam cursor working on macOS.

**Comment by DivineGod** [comment]
I think hiding the cursor doesn't work because of winit. https://github.com/tomaka/winit/blob/master/src/platform/macos/window.rs#L477

**Comment by DivineGod** [comment]
I've found a fix for mac in https://github.com/jwilm/alacritty/pull/437 which uses a different call, that seems more appropriate across platforms
