### ISSUE TITLE
Visual Bugs 

### ISSUE THREAD

**Issue by xfbs** [jwilm/alacritty#2464]
Operating System: 

macOS 10.14

I was using Alacritty to edit the config file with NeoVim, and suddenly NeoVim stopped showing. Sometimes it would show a part of NeoVim, sometimes it wouldn't show anything. I screen-recorded the issue. I managed to reproduce this issue a couple times.

See [this video](https://vimeo.com/337559777).

**Comment by chrisduerr** [comment]
https://github.com/jwilm/alacritty/issues/2353.
