### ISSUE TITLE
Cursor movement generates output

### ISSUE THREAD

**Issue by iryan2** [jwilm/alacritty#2471]
Which operating system does the issue occur on? MacOS. Alacritty v0.3.2

When I'm not in tmux, moving the mouse cursor over the Alactritty window outputs (seemingly) one character per pixel of movement. Each character seems to correlate with the cursor's coordinates. See screen recording for example:

![Screen Recording 2019-05-23 at 9 11 22 am](https://user-images.githubusercontent.com/5858312/58215304-92728800-7d3c-11e9-81ed-e5bb1d48aee0.gif)

**Comment by chrisduerr** [comment]
This is intentional. Something in your shell config has sent the escape sequence to notify the shell about all cursor movement, which should normally not be set by default, so this is an issue with your configuration.
