### ISSUE TITLE
Crashes when using --title option

### ISSUE THREAD

**Issue by BigfootN** [jwilm/alacritty#2472]
Hello,

I am using `bspwm` as my wm, running under X11. I am trying to use this command:

`alacritty -e ncmpcpp -t ncmpcpp`

but unfortunately it crashes, without any errors. I tried with `-vvv`.
The command runs without any problem when not using `-t ncmpcpp`.

OS: Archlinux
Alacritty version: alacritty_terminal 0.3.2

Thank you very much in advance for any help.

**Comment by kchibisov** [comment]
Just change the order to `alacritty -t ncmpcpp -e ncmpcpp`.  You can consult `alacritty --help` for more info.

**Comment by BigfootN** [comment]
Oh okay, that simple, thank you very much.
