### ISSUE TITLE
error: SWIFT_VERSION '3.0' 

### ISSUE THREAD

**Issue by alasso** [jwilm/alacritty#2473]
Hi, 

I am installing alacrity on a macOS mojave 10.14.5 and I am receiving this error: 

error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'keyboardSwitcher')

Any help?

Thanks a lot in advance,
Adrian

**Comment by chrisduerr** [comment]
How exactly are you trying to install it?

**Comment by alasso** [comment]
I followed the readme instructions:

brew tap lutzifer/homebrew-tap
brew install keyboardSwitcher

The error ocurres at the second command.

Thanks a lot!

**Comment by cole-h** [comment]
Unless I'm misunderstanding something, this seems unrelated to Alacritty. Maybe you would be better served posting an issue on the `keyboardSwitcher` repo: https://github.com/Lutzifer/keyboardSwitcher

**Comment by chrisduerr** [comment]
Sounds like you got the wrong repository, it seems like what @cole-h linked should be the correct place!
