### ISSUE TITLE
message bar displays ANSI escape codes on warning/error

### ISSUE THREAD

**Issue by oslerw** [jwilm/alacritty#2474]
Which operating system does the issue occur on?

- Fedora 29
- alacritty-0.3.2
- rustup 1.18.3

If on linux, are you using X11 or Wayland?

- X11

---

I am missing `xclip` on my system, so alacritty is (correctly) giving me an error about this in the message bar. However, it looks like the message has ANSI color escapes that aren't being handled:

![image](https://user-images.githubusercontent.com/1066487/58286397-80581000-7d63-11e9-972d-9395df6245a7.png)

I'm guessing these escapes correspond with the color red, since that's what's displayed when I invoke alacrity from another terminal:

![image](https://user-images.githubusercontent.com/1066487/58286454-9ebe0b80-7d63-11e9-8929-1ae4d2d80002.png)

**Expected Behavior**: alacritty should either:
1) Parse the ANSI codes and use the correct color (harder to implement) or
2) Filter out the ANSI escape codes (easier to implement)

**Comment by chrisduerr** [comment]
I think the second suggestion is probably the most reasonable, it should give the best balance.

However, there is a third option: Not using color when logging. If possible the other options should be preferred since they are less limited, but that would obviously be the easiest solution of all of them.

**Comment by nixpulvis** [comment]
I think I kinda like just not printing color when logging. That's how many programs handle this.

Otherwise, option 2 seems better if only because I don't want to deal with contrast on a colored message bar.
