### ISSUE TITLE
hovering over very long lines slows down alacritty

### ISSUE THREAD

**Issue by yorickvP** [jwilm/alacritty#2479]
Which operating system does the issue occur on?

Linux

If on linux, are you using X11 or Wayland?

Wayland

Reproduce:
`head -c81920 /dev/urandom | base64 | tr -d '\n'`

It also seems to happen with /dev/zero

**Comment by WGH-** [comment]
"Slows down" sounds like major understatement: it freezes Alacritty 0.3.2 (on X11) with 100% CPU usage for 20s. The longer the line, the harder it hits: 163840 causes 53 seconds hang.

**Comment by chrisduerr** [comment]
Just to clarify, this should already be fixed by https://github.com/jwilm/alacritty/pull/2413, however that introduces some other problems so I'm not ready to mark this as resolved yet.

Hopefully that PR will end up in a state that automatically resolves this issue too though.
