### ISSUE TITLE
Option to run without the terminal

### ISSUE THREAD

**Issue by tienhv** [jwilm/alacritty#248]
Hi,
I am using Alacritty on Mac. Whenever I launch it, the new iTerm/terminal opens and prints the debug message. Is there any option to disable that and run Alac alone?

**Comment by jwilm** [comment]
Easiest thing to do is start it in a tmux session and background it. This will be resolved when we ship `Alacritty.app`.

**Comment by cema-sp** [comment]
Some kind of temporary solution: `nohup sh -c 'alacritty' &`.

**Comment by brycefisher** [comment]
Cross linking to the PR where work on Alacritty.app is happening:
https://github.com/jwilm/alacritty/pull/301
