### ISSUE TITLE
Alacrity does not allow any input to be typed

### ISSUE THREAD

**Issue by aspen1135** [jwilm/alacritty#2480]
Which operating system does the issue occur on?
Windows 10 64 bit

Hello everyone. I am new to alacrity.

I installed the package via chocolatey package installer since I could not get manual building it to work (probably something to do with dependencies). It installed OK and I can open the executable without problems. It is also detected in my PATH. However, when I launch the terminal window executable, I cannot enter any input into it's field.

Is this a bug? or is there something I am missing?

Also:
Is it possible to read the standard outputs from the alacrity window back using python? I am trying to speed up the string parsing from using a standard command shell by switching to a different terminal. The communicate() method from Python's subprocess module did not work when I tried using another terminal emulator earlier (ConEmu). I'm wondering if I'll have the same issue here with Alacritty.

Thanks! I dig this program (if it works). Seems like a one of a kind terminal!

![image](https://user-images.githubusercontent.com/17952043/58377627-c2d34580-7f39-11e9-939e-07de9cbaf52d.png)

**Comment by chrisduerr** [comment]
This looks like it can't find your shell. Make sure that the shell set in the config actually works on your system and is part of your path (it's powershell.exe by default).

You can trying changing it to cmd.exe or just running `alacritty -e cmd.exe` to see if that maybe helps with things.

**Comment by aspen1135** [comment]
> This looks like it can't find your shell. Make sure that the shell set in the config actually works on your system and is part of your path (it's powershell.exe by default).
> 
> You can trying changing it to cmd.exe or just running `alacritty -e cmd.exe` to see if that maybe helps with things.

When running alacritty -e cmd.exe, I get a window with garbled text. I can enter text into the field, but it isn't readable. Additionally, trying the same process but with powershell.exe gives me the initial problem of a blank cursor without being able to type.

I tried to find where the config file is located. I know if you compiled it from the source it is pretty easy to find. However, I installed it via chocolatey and it put the executable file in C:/tools/alacritty. Where can I find the configuration file? Maybe I can give it the powershell path manually that way.

![image](https://user-images.githubusercontent.com/17952043/58385862-f3ec5e00-7fab-11e9-87d2-27d6e28cb6fc.png)

**Comment by chrisduerr** [comment]
Which GPU do you have? That looks like it doesn't support the Shader version required by Alacritty.

**Comment by aspen1135** [comment]
My laptop uses an older Intel onboard GPU. it is very likely that is the issue then.

 I wanted a faster terminal emulator that could be supported on multiple machines for my program. I might try and use alacrity on my newer desktop, then resort to the default cmd shell if my program detects the system not meeting the shader requirements.

What are the minimum system requirements for alacrity?

**Comment by chrisduerr** [comment]
I believe you should need at least OpenGL versoin 3.2 support, which GPU exactly are you running?

**Comment by aspen1135** [comment]
> I believe you should need at least OpenGL versoin 3.2 support, which GPU exactly are you running?

Hi Chris,
I have good news. I got alacritty up and running on my desktop computer with my Nvidia gtx1060 GPU. I figured this would be more than sufficient.

I have another problem however. I'm not sure if it has a quick resolve but I will close this post and start a new one if it isn't simple.

I am trying to route the standard out of Alacritty to a subprocess pipe using Python code. This would allow me to read/cache the print statements from my Python program.

I noticed there were some flags to increase the verbosity of alacritty, but it seemed to only provide information about the terminal instance itself (ie. window size, font, etc), and not what was printing to the window. Is there a way I can route the printed statements to the standard out?

![image](https://user-images.githubusercontent.com/17952043/58389097-e4850900-7fdb-11e9-98d9-c31af371cc8a.png)

**Comment by chrisduerr** [comment]
There's a difference between a shell and a terminal emulator. You probably want to execute code in a shell, not a terminal emulator, to read from stdout and get everything that has been printed.

The terminal emulator just spawns a shell itself and then reads its output, it doesn't forward it in any way. Things like cmd.exe/powershell.exe might be a bit confusing here, because they are both shell and terminal emulator, but bash and similar make things a little more clear here.
