### ISSUE TITLE
Cannot switch to fullscreen on i3ww

### ISSUE THREAD

**Issue by Hritik14** [jwilm/alacritty#2481]
Which operating system does the issue occur on? Archlinux

If on linux, are you using X11 or Wayland? X11

When switching to fullscreen from tiling, it results is this: 
![1558852226](https://user-images.githubusercontent.com/7457065/58378230-5b0b1200-7fae-11e9-9510-5e1d7530943c.png)

**Comment by chrisduerr** [comment]
Does this get fixed when moving the mouse over the window, or inputting new characters? I'm on i3 myself and I cannot repro.

**Comment by Hritik14** [comment]
Nope. It doesn't get fixed.

**Comment by chrisduerr** [comment]
Which version of Alacritty are you running?

**Comment by Hritik14** [comment]
The one in the official repo: alacritty 0.3.2-2 (x86_64)

**Comment by chrisduerr** [comment]
Could you try to reproduce this with the latest master?

**Comment by seifriedc** [comment]
FWIW, I cannot reproduce this on 0.3.3, i3 version 4.17.1 (gaps-next).

**Comment by chrisduerr** [comment]
There hasn't been a response for a while and I'm using i3 myself without ever running into this. So I think it's safe to say this should be resolved.
