### ISSUE TITLE
Index out of bounds when selecting during `yes`

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#2486]
When creating a selection while running the `yes` command, Alacritty will crash with an index out of bounds exception.

**Comment by cole-h** [comment]
For further info: I can reproduce this using `while 1; do echo no; done` and selecting. Theoretically, any high-output command that induces fast scrolling would cause this.

**Comment by chrisduerr** [comment]
Another interesting detail might be that I *think* I've specifically tested this in the past, so it's possible that there has been a regression and it might be worth bisecting this issue.

**Comment by cole-h** [comment]
You were right. Bisect gives me bf353059a0f10bbccec754deb0e182cec3f6efe0 as the first bad commit. I don't think I'll have enough time to try to fix it this week, but hopefully this helps you or somebody else who wants to fix it.

**Comment by chrisduerr** [comment]
Thanks for bisecting, that should hopefully make troubleshooting a lot simpler!

**Comment by cole-h** [comment]
Doing a bit more testing: the problem appears to stem from the `span.map()` at https://github.com/jwilm/alacritty/commit/bf353059a0f10bbccec754deb0e182cec3f6efe0#diff-7e09fea17462febd06d3b5bdd2b4512aR145. Commenting out both branches makes the problem disappear, and uncommenting either one reveals it again.

I've also noticed that lowering the `history.scrollback` config makes the issue appear earlier (I've been testing at 100 lines).

----

I think I've narrowed it down further... maybe: using `grid[span.{start,end}.line][span.{start,end}.col]` anywhere inside that `map` causes the same issue. Using `span.{start,end}.line` or `.col` in e.g. a tuple, the issue does not manifest.

Maybe there's a problem with indexing the Grid?

**Comment by chrisduerr** [comment]
> Maybe there's a problem with indexing the Grid?

Most definitely. I'd assume that the selection is stored at a specific position and then rotated (moved up) until it leaves the grid. So trying to access it then will lead to an access outside of the grid, leading to an IOOB.

Though I haven't had the time to look at this yet, so this is only a guess.

**Comment by Ben496** [comment]
> I'd assume that the selection is stored at a specific position and then rotated (moved up) until it leaves the grid. So trying to access it then will lead to an access outside of the grid, leading to an IOOB.

I did some testing and this seems to be exactly what the issue is. If I prevent span.{start,end}.line from going larger than the number of lines in the grid then no IOOB will occur.
