### ISSUE TITLE
Crash when restore window from maximized to the original size 

### ISSUE THREAD

**Issue by domb4** [jwilm/alacritty#2488]
#System 
Windows 10 1903

#Summary 
I encounter this issue when the option below is set to true (no problem when it is set to false)
_enable_experimental_conpty_backend: true_

If the window is maximized and the text has scrolled (there is not this issue when the text has not scrolled). When I minimize the window to the original size and that I execute a command (like ls) error message below is display to the bottom of the window:
**out-lineoutput : The Win32 internal error "The parameter is incorrect" 0x57 occurred while writing to the console output buffer at the curre**

Finally the window closes after few seconds.

#Extra 
Please find below the log file created with the command allacritty.exe -vvv
[alacritty.log](https://github.com/jwilm/alacritty/files/3226688/alacritty.log)

**Comment by chrisduerr** [comment]
Which version of Alacritty are you running?

**Comment by domb4** [comment]
I'm running the 0.3.2

**Comment by chrisduerr** [comment]
By 'and the text has scrolled', do you mean that the visible are is currently not at the bottom, or do you mean that at least one full screen of output has been printed?

Also which method of installation did you use?

**Comment by domb4** [comment]
I mean that one full screen of output has been printed.
I made an animated gif with the issue, I think it will be better to understand.

I installed Alacritty with Scoop (https://github.com/lukesampson/scoop)

![Alacritty-issue-01](https://user-images.githubusercontent.com/1105492/58860062-8e832600-86ab-11e9-91f5-60cbd606bf3a.gif)
[Alacritty issue](https://user-images.githubusercontent.com/1105492/58860062-8e832600-86ab-11e9-91f5-60cbd606bf3a.gif)

**Comment by domb4** [comment]
I have tried by launching the shells below, there is not this issue.
- debian.exe with _wsl_
- cmd.exe
- powershell.exe -version 2


This issue seems to appear only with _powershell.exe_ (version 3 and later) and with _pwsh.exe_ (core).

**Comment by chrisduerr** [comment]
That's actually a shell error and not an Alacritty error, which is kinda surprising.

I wouldn't expect it to just hard-crash like that, but it might be worth reporting this upstream to https://github.com/powershell/powershell.

Are you able to reproduce this in any other terminal emulator?

**Comment by domb4** [comment]
You are right I think this issue is not due to Alacritty.

I have tried to launch a _powershell.exe_ under a _debian.exe_ shell (wsl) and with _Terminus_, I have the same issue.

Thank you.
