### ISSUE TITLE
Alacritty Icon Jumping on Mac Dock

### ISSUE THREAD

**Issue by ngklingler** [jwilm/alacritty#2492]
Which operating system does the issue occur on? macOS

If on linux, are you using X11 or Wayland? Not relevant

Version: 0.3.2

On macOS the alacritty icon in the dock will repeatedly jump when alacritty is not focused. It seems most likely to do this if an SSH connection was broken, but even after I change focus to alacritty and run other commands successfully it continues to jump after I change focus. It seems the only way to resolve it is to close and reopen alacritty, which is a bit annoying.

If anyone knows of a solution or knows what in the code is causing this please let me know. Thanks in advance for any and all help!

**Comment by ngklingler** [comment]
To reproduce run alacritty on macOS, SSH into a server, then disconnect your wifi or something to break the connection. When you switch focus to another application the icon should start jumping

**Comment by chrisduerr** [comment]
That almost sounds like an urgent flag is set on the window, without it getting cleared properly.

Can you reproduce this by running `sleep 3 && echo -e "\a"`? That should ring the bell and be a little easier to reproduce than having to use ssh.

Is it correct that Alacritty will just continue to request focus non-stop, or does it stop for some period and then just start again later?

**Comment by ngklingler** [comment]
So when I run what you just mentioned it will request focus, I switch focus to alacritty and that seems to clear it since when I switch focus away it stops jumping. But with SSH when I switch focus to alacritty it stops jumping until I switch away again, and it seems nonstop until I close and reopen alacritty

**Comment by ngklingler** [comment]
FWIW instead of closing and reopening alacritty I can just open a new tmux window and close the previous one, or start a new tmux session. Possible tmux is repeatedly sending the terminal bell when SSH fails?

**Comment by chrisduerr** [comment]
That definitely sounds a bit odd, if it was an Alacritty bug I would have expected the `\a` bell character to cause the same issues.

I'd assume you can't reproduce this with another terminal emulator though?

**Comment by ngklingler** [comment]
Got it somewhat reproduced with another emulator. Terminal.app will jump once when I leave focus, but doesn't repeatedly jump like alacritty does. Regardless it seems like a tmux/ssh issue versus an alacritty issue. In the meantime do you happen to know of a way to disable this behavior? I have set the duration of the visual bell to 0 but it still occurs. If you don't know no worries, you've been super helpful in troubleshooting this issue and I appreciate that.

**Comment by chrisduerr** [comment]
> In the meantime do you happen to know of a way to disable this behavior?

You might be able to remove the `bel` capability from the Alacritty terminfo, but I'm not aware of any straight-forward solution like just disabling it in the config file.
