### ISSUE TITLE
wsl vscode integration with alacritty

### ISSUE THREAD

**Issue by csaket** [jwilm/alacritty#2493]
Windows 10 1903 18362.116 x64
wsl with zsh on ubuntu
vscode 1.35.0-insiders 
Alacritty-v0.3.2-windows-installer.msi installed

I have configured alacritty.yml to have the shell program as wsl.

In vscode, I have  "terminal.integrated.shell.windows": "C:\\Program Files\\Alacritty\\alacritty.exe"

When I open terminal, alacritty pops up outside instead of being embedded like with git bash/cmd/powershell/plain wsl

Is there a way to have alacritty also be embedded? 
Hoping there is!

**Comment by chrisduerr** [comment]
I'm not sure how VSCode handles this, but I'd assume it just embeds a shell in its own terminal emulator.

I don't think it allows rendering another window inside itself and Alacritty is a terminal emulator, not a shell.
