### ISSUE TITLE
Window constantly resizes when opening direcoties in neovim (sway).

### ISSUE THREAD

**Issue by littenup** [jwilm/alacritty#2496]
Which operating system does the issue occur on?
void linux

If on linux, are you using X11 or Wayland?
Wayland (sway 1.0)

When opening a diretory in neovim. Alacritty constantly tries to resize the window and yields sway unusable until I kill it in another TTY. Using classic vim or opening files does not result in any problems. I have also teseted it in X11 mode of alacritty (utilising xwayland on sway) and it resulted in the same problem.

I have also tested it in kitty and it resulted in the same problem. But urxvt only tried to resize once and could be used afterwards.

And here is the output of `alacritty -vv` and `alacritty --print-events` when starting `vim .config/`
[alacritty_debug.txt](https://github.com/jwilm/alacritty/files/3244639/alacritty_debug.txt)
[alacritty_events.txt](https://github.com/jwilm/alacritty/files/3244640/alacritty_events.txt)

**Comment by chrisduerr** [comment]
I'm not sure why Neovim would resize at all when doing anything inside of it. It seems to me like neovim is doing something odd here?

There is an escape sequence to change the window dimensions (`printf '\033[8;40;100t'`), however that is not supported by Alacritty, so I don't see what neovim could be trying to do here, but it feels like this might be something that has to be addressed there.

**Comment by littenup** [comment]
I just found this [neovim issue](https://github.com/neovim/neovim/issues/9806). Apperently they are working on a fix.
Appernently it actually is a [wl-clipboard problem](https://github.com/bugaevc/wl-clipboard).
