### ISSUE TITLE
crash on MacOS when parent shell's window is closed

### ISSUE THREAD

**Issue by coledot** [jwilm/alacritty#250]
Running MacOS Sierra (10.12.2). If I launch Alacritty from another terminal emulator, and close the window used to launch it, Alacritty crashes. Error is reproducible with both bash via Terminal and with fish via iTerm.

Steps to reproduce:

1. Open a terminal window.
2. Run `alacritty` and background it (either via `alacritty &` or Ctrl-Z followed by `bg`).
3. Close the original Terminal/iTerm window.
4. Do something with alacritty, e.g. resize the window or enter input. It immediately crashes.

I can work around this by using `tmux`: open a tmux session, run `alacritty`, detach tmux, close the window. Alacritty will continue to run just fine in this state, until I terminate the tmux session, at which point Alacritty becomes "crashable" (i.e. goto step 4)

**Comment by jwilm** [comment]
This will be resolved when we ship an `Alacritty.app`.
