### ISSUE TITLE
Unicode LOW HALF BLOCK character incorrect rendering

### ISSUE THREAD

**Issue by luizdepra** [jwilm/alacritty#2500]
Hey!

I got a problem with Unicode LOW HALF BLOCK rendering.

![Screenshot from 2019-06-02 13-40-53](https://user-images.githubusercontent.com/1427376/58764395-d0da2500-853c-11e9-8af9-6729bcfe93eb.png)

The character is rendered with a strange space between as you can see in the image. In Gnome Terminal everything render as expected.

![Screenshot from 2019-06-02 13-43-17](https://user-images.githubusercontent.com/1427376/58764397-d3d51580-853c-11e9-93b4-ebf66e7dd62d.png)

I'm using Gnome Manjaro Linux with X11. Both terminals are configurared with the same font, Hack.
Here is my [alacritty.xml](https://github.com/luizdepra/dotfiles/blob/master/alacritty.yml).

**Comment by chrisduerr** [comment]
Does changing the `font.offset.y` value to `-1` fix this issue?

**Comment by luizdepra** [comment]
No, but setting `font.offset.x` to `-1` solved it. But why? What `-1` does?

**Comment by chrisduerr** [comment]
Oh my bad, that's what I meant.

The `font.offset` can be used to change horizontal and vertical font spacing. Sounds like everything's working now?

**Comment by luizdepra** [comment]
Yep. Thank you.
