### ISSUE TITLE
Rendering issues with large amounts of text

### ISSUE THREAD

**Issue by 7415963987456321** [jwilm/alacritty#2503]
Which operating system does the issue occur on?
**Linux**
If on linux, are you using X11 or Wayland?
**Wayland (sway)**

Issuing a command that would spew out large amounts of text, such as using grep or ripgrep to find a common pattern results in rendering errors.  

**Version:**
Latest master of Alacritty.

**Commands tested:**
    
    rg .hs
    rg a 
    grep -r .hs

**Screenshot:**
https://i.imgur.com/BEa1AeO.png

I don't know if this is related to #2353 or if this is maybe some wayland specific render issue.

I seem to be able to restore alacritty to normal by fullscreening the window several times.  Also one of the effects of this bug is that colors for the terminal, generated by pywal, dissappear.  

Please let me know if you need any sort of debug output or whatever else.

**Comment by kchibisov** [comment]
@7415963987456321 does `reset` after your grep resolves the issue?

**Comment by 7415963987456321** [comment]
@kchibisov 
Yes, that solves the issue, using the clear command also resets it to normal.
It also seems that if I fullscreen the alacritty window in question while it is still spewing out text fixes the issue and it continues like normal after that.

**Comment by chrisduerr** [comment]
Is it possible that this rg command spits out some escape sequences? Can you reproduce this in another terminal emulator?

**Comment by 7415963987456321** [comment]
Hmm, yes I can reproduce this with kitty terminal, maybe it's just the output thats broken then. Kitty seems to report some glfw error the moment it goes haywire. 
 
    [glfw error 65544]: Wayland: Window attention request not implemented yet

Alacritty doesn't report much besides spamming "glutin event: Awakened" when run with debug-printing enabled.

**Comment by 7415963987456321** [comment]
It seems like this is already an issue with ripgrep, but they issued a wontfix in https://github.com/BurntSushi/ripgrep/issues/519

I guess I'll just close this then.

**Comment by chrisduerr** [comment]
This isn't really something ripgrep should do, so the wontfix is likely appropriate there.

Since Alacritty has some files with escape codes inside them I've ran into this issue myself before, but I usually just rewrite my query to exclude this files in that case. That's probably the best choice, other than piping it through a separate program to strip escapes.
