### ISSUE TITLE
Tmux multi-line status bars not offsetting cursor position

### ISSUE THREAD

**Issue by kev-zheng** [jwilm/alacritty#2505]
Which operating system does the issue occur on?
OSX Mojave

I'm trying to use tmux's multi-line status bar feature with transparent borders to simulate an invisible top-bar with menu buttons. It looks like Alacritty doesn't recognize the extra lines added by the status bars.

Highlighted text is a full line below my cursor. The tmux status bar is a height of two lines.
here, the red arrow is where I dragged

<img width="842" height="500" alt="Screen Shot 2019-06-04 at 12 07 08 PM" src="https://user-images.githubusercontent.com/24661601/58895166-5ab2fb00-86c1-11e9-940f-c3c9fc4371a1.png">

relevant tmux.conf lines
```
set -g status 2
set -g status-format[0] ""
set -g status-format[1] "#[align=left range=left #{status-left-style}]#{T;=/#{status-left-length}:status-left}#[norange default]#[list=on align=#{status-justify}]#[list=left-marker]<#[list=right-marker]>#[list=on]#{W:#[range=window|#{window_index} #{window-status-style}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#{T:window-status-format}#[norange default]#{?window_end_flag,,#{window-status-separator}},#[range=window|#{window_index} list=focus #{?#{!=:#{window-status-current-style},default},#{window-status-current-style},#{window-status-style}}#{?#{&&:#{window_last_flag},#{!=:#{window-status-last-style},default}}, #{window-status-last-style},}#{?#{&&:#{window_bell_flag},#{!=:#{window-status-bell-style},default}}, #{window-status-bell-style},#{?#{&&:#{||:#{window_activity_flag},#{window_silence_flag}},#{!=:#{window-status-activity-style},default}}, #{window-status-activity-style},}}]#{T:window-status-current-format}#[norange list=on default]#{?window_end_flag,,#{window-status-separator}}}#[nolist align=right range=right #{status-right-style}]#{T;=/#{status-right-length}:status-right}#[norange default]"
```

full tmux.conf
https://pastebin.com/y4KKGrMT

alacritty.yml:
https://pastebin.com/2J3VEYxx

**Comment by chrisduerr** [comment]
What happens when you hold shift to select the cells, does that work properly?

**Comment by kev-zheng** [comment]
Yup that works properly

**Comment by chrisduerr** [comment]
The selection started while holding shift is Alacritty's native selection. The yellow-ish selection inside of tmux is done by tmux. So this is likely a problem with tmux.

Can you check out how this performs in a different terminal emulator?

**Comment by kev-zheng** [comment]
Hmm you're right, I can reproduce this in a different editor. Thanks, I'll close this
