### ISSUE TITLE
RHEL7: Error creating glutin::Window; No backend is available

### ISSUE THREAD

**Issue by toomanycats** [jwilm/alacritty#251]
Now that I have built the binary I'm getting this error when running:

`Error creating glutin::Window; No backend is available`

**Comment by jwilm** [comment]
Can you check that `glxgears` runs on your system?

**Comment by pmatos** [comment]
Same here `fedora 25`. `glxgears` does not run:
```
$ glxgears
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  31
  Current serial number in output stream:  32
```

Might have to investigate why.

**Comment by pmatos** [comment]
This might have to do with my use of the nvidia drivers and how Fedora handles this. Need to investigate.

**Comment by pmatos** [comment]
Solved it with `dnf update` and reboot. Didn't understand what the problem was but it might be that there was some nvidia  driver mismatch of some kind.

**Comment by toomanycats** [comment]
@pmatos 

I'm running RHEL 7 on a managed system although I do have limited `sudo` priv.
Would `yum update` be equivalent ?

**Comment by moosingin3space** [comment]
@toomanycats `yum update` would be the RHEL equivalent of Fedora's `dnf`.

**Comment by toomanycats** [comment]
yum update and a restart fixed the issue.

I have an alacritty term open !
