### ISSUE TITLE
GUI apps launched by Alacritty don't get put in the foreground

### ISSUE THREAD

**Issue by butla** [jwilm/alacritty#2515]
Which operating system does the issue occur on?
Kubuntu 18.04 x64

If on linux, are you using X11 or Wayland?
X11

The problem:
When I launch GUI apps from Alacritty, like Meld or Firefox, their windows get created in the background. If I'm on Konsole or Terminator, the focus immediately switches to that new window, which is quite handy.

I didn't find any configuration options to change that behavior. Does that need to get implemented? Or does it just not work on KDE/Plasma?

**Comment by chrisduerr** [comment]
I can't reproduce this in i3, though that's quite a different desktop setup.

When you talk about launching GUI apps from Alacritty, do you mean running them inside the shell? Which shell have you tested this with?

Also could you maybe try XTerm or URxvt, I'd expect those to perform less magic on their own, so maybe it can be reproduced there?

Lastly, this might be related to how you launched Alacritty. So I'd recommend also testing it with an Alacritty window spawned from Konsole/Terminator (assuming it works when spawning a Konsole/Terminator window from Konsole/Terminator).

**Comment by butla** [comment]
I'm using bash as the shell, but the same thing happens in zsh.

XTerm starts new apps in the foreground.

I was running alacritty from the Plasma application launcher. If I spawn alacritty from terminator or xterm then the applications open in the foreground. Interesting.

I'll try to research this more later.

**Comment by chrisduerr** [comment]
Comparing the Alacritty.desktop to what XTerm/Konsole/Terminator provide might be a worthwhile effort. Please let me know if you find out anything Alacritty might be doing wrong.

**Comment by butla** [comment]
Good idea.

**Comment by butla** [comment]
Couldn't find anything interesting in the .desktop files

`debian-xterm.desktop`:
```
<license>

[Desktop Entry]
Name=XTerm
#GenericName=Terminal
Comment=standard terminal emulator for the X window system
Exec=xterm
Terminal=false
Type=Application
#Encoding=UTF-8
Icon=xterm-color
Categories=System;TerminalEmulator;
Keywords=shell;prompt;command;commandline;cmd;
X-Desktop-File-Install-Version=0.23
```

`terminator.desktop`:
```
[Desktop Entry]
Name=Terminator
Comment=Multiple terminals in one window
TryExec=terminator
Exec=terminator
Icon=terminator
Type=Application
Categories=GNOME;GTK;Utility;TerminalEmulator;System;
StartupNotify=true
X-Ubuntu-Gettext-Domain=terminator
X-Ayatana-Desktop-Shortcuts=NewWindow;
Keywords=terminal;shell;prompt;command;commandline;
[NewWindow Shortcut Group]
Name=Open a New Window
Exec=terminator
TargetEnvironment=Unity
```

Tried getting rid of the entries in alacritty.dekstop that aren't in the other files like a monkey, didn't help (I was checking that the changes were being applied by changing GenericName).

Guess I'd need to check how you spawn windows in Plasma, and how does terminator/xterm do it?

**Comment by chrisduerr** [comment]
Another thing that might be different between Alacritty launched through a DE and Alacritty launched from a different terminal emulator, is the environment variables.

So make sure those match and maybe try adding what's missing when launching Alacritty from the DE.

**Comment by butla** [comment]
I compared the envs and it turns out that alacritty started on its own has DESKTOP_STARTUP_ID env var set. Unsetting that makes apps start in the foreground.

Can't find that variable in this repo, though. So it's weird.

**Comment by chrisduerr** [comment]
```
Communicating from a launcher process to a launchee process
===

To communicate the startup sequence information from a launcher
process to a launchee process, when possible an environment variable
should be used:

 DESKTOP_STARTUP_ID
   value of the "ID" field in the "new" message

It is suggested to unset this environment variable in the launchee
as soon as it's read, to avoid possible reuse by some process started
later by launchee.
```

Source: https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt

It seems like this is a standard for telling a DE about startup state of an application. While it might be possible to support the full standard in Alacritty, I think the only thing really relevant here is that we unset the environment variable.

This should hopefully be trivial and fix that bug, I've taken a look at a few different terminal emulators and both Kitty and gnome-terminal unset the variable (and kitty also gives some information about startup state back).

**Comment by butla** [comment]
should I unset the variable somwhere in https://github.com/jwilm/alacritty/blob/master/alacritty/src/main.rs ?

**Comment by chrisduerr** [comment]
I've fixed this in https://github.com/jwilm/alacritty/pull/2525. I forgot to link it here, sorry.

**Comment by butla** [comment]
Oh, great, thanks. Guess I can close this now.
