### ISSUE TITLE
System clipboard can't be accessed from vim anymore

### ISSUE THREAD

**Issue by Limero** [jwilm/alacritty#2518]
I have `set clipboard=unnamedplus` in my `.vimrc` and that allows my to copy/paste things between vim and other applications. This works as intended with Alacritty 0.3.2.

However, I tried building the latest version of Alacritty from git (after the clipboard rework) and it doesn't work anymore. Are there additional steps that have to be done for vim to access the system clipboard now or is this a bug?

Arch Linux, Sway 1.1.1, Wayland

**Comment by chrisduerr** [comment]
Do you use middle mouse to paste? That's not supported on the latest master yet, though I recommend trying #2519.

I think with the #2519 PR everything should work properly.

**Comment by Limero** [comment]
Issue is still there after the merged PR (I tried latest version from git).

Steps to replicate:
1. Install vim with `+clipboard` support (on Arch I install the gvim package)
2. Add `set clipboard=unnamedplus` to ~/.vimrc
3. Open Alacritty and run `vim`
4. Press `i` to enter insert mode, type a few characters
5. Press `esc` to go back to normal mode
6. Press `Y` to cut the whole row
7. Try to paste it somewhere else

Steps above work as intended on Alacritty before the clipboard rework.

**Comment by chrisduerr** [comment]
I don't think vim actually supports the wayland clipboard, which is nothing Alacritty can help with.

Does this work in any other terminal emulator using native Wayland?

**Comment by Limero** [comment]
I  just tried in kitty and gnome-terminal (both on sway). It works in kitty, but not in gnome-terminal. Is this because kitty/previous Alacritty versions use the xorg clipboard, never the native wayland one?

If so, is it possible to fallback on xorg in Alacritty or will we just have to use neovim?

**Comment by chrisduerr** [comment]
Yes, this is likely a vim issue. As far as I know, neovim also does not support the Wayland clipboard, but since it always uses xclip explicitly that's probably running through XWayland automatically.

You can run Alacritty in XWayland mode using `WAYLAND_DISPLAY= alacritty`.

**Comment by Limero** [comment]
I think neovim uses wl-clipboard on Wayland, so I guess that is the way to go :)
