### ISSUE TITLE
Keyboard shortcut for macOS native fullscreen

### ISSUE THREAD

**Issue by mees-** [jwilm/alacritty#2522]
Hi, I think it would be good to add the default macOS native fullscreen shortcut (⌘+control+f) since the application supports it when clicking the button.

**Comment by chrisduerr** [comment]
If there is a standard shortcut which should work in all (or most) applications and it uses the super/command key to trigger, I don't see why we wouldn't support it by default. Sounds like a good idea.

**Comment by erickgnavar** [comment]
This was added on https://github.com/jwilm/alacritty/commit/e9813031f6e308984cb5547aa1049839cb75745f and it works great :)

**Comment by chrisduerr** [comment]
Oh you're right, I thought this only added the Windows shortcut, thanks!
