### ISSUE TITLE
Logo Not used in Window Frame

### ISSUE THREAD

**Issue by stevensonmt** [jwilm/alacritty#2523]
Which operating system does the issue occur on?
Linux, XFCE, XFWM
If on linux, are you using X11 or Wayland?
X11

See top left of the window. Generic "application" icon is used, not the alacritty icon.

![Screenshot_2019-06-10_21-57-38](https://user-images.githubusercontent.com/8891908/59244809-cbc74680-8bca-11e9-9e39-dc940e4f7512.png)

**Comment by kchibisov** [comment]
Which version of Alacritty are you running? ( `alacritty --version` )

**Comment by stevensonmt** [comment]
version 0.3.2

**Comment by chrisduerr** [comment]
This is fixed in the latest master.

**Comment by stevensonmt** [comment]
sorry if this was a duplicate. I only found references to Windows so wasn't sure this was the same problem.
