### ISSUE TITLE
Add a git tag

### ISSUE THREAD

**Issue by cema-sp** [jwilm/alacritty#253]
It is useful to add a git "version tag" to give users ability to fetch particular versions (even for alpha).
It is also required for homebrew formula.

**Comment by 0X1A** [comment]
A good idea would be to add a `--version` CLI option that would concat both the current version and the SHA the build was off of

**Comment by jwilm** [comment]
Not ready to start adding tags yet, but I'll definitely do that once it makes sense.

**Comment by cweagans** [comment]
Sorry to nag, but I see that the 0.1.0 milestone is empty at this point -- would now be a good time to consider adding a new tag?

**Comment by chrisduerr** [comment]
@cweagans Properly tagging versions is planned and tracked in #1240. Currently I don't think there's any direct focus on which things should be tackled in which order, so I wouldn't expect milestones to be super actively used.
