### ISSUE TITLE
Why use YAML?

### ISSUE THREAD

**Issue by catastrop** [jwilm/alacritty#2532]

**Comment by wookietreiber** [comment]
YAML is awesome!

**Comment by catastrop** [comment]
YAML is harmful. Why don't use **TOML**? 

`cargo` uses TOML.

**Comment by NickeZ** [comment]
dupe https://github.com/jwilm/alacritty/issues/1217

**Comment by NickeZ** [comment]
@catastrop writing "considered harmful" is considered harmful. https://meyerweb.com/eric/comment/chech.html

**Comment by catastrop** [comment]
Use `toml` or ......
