### ISSUE TITLE
⌘+m does not minimize window

### ISSUE THREAD

**Issue by rafaelrinaldi** [jwilm/alacritty#2534]
Which operating system does the issue occur on?
macOS Mojave

Not a big deal but for some reason hitting <kbd>⌘</kbd>+<kbd>m</kbd> does not minimize Alacritty's window. It just sends the character `m` to stdin.

Maybe this is fixable by adding a custom key binding?

**Comment by chrisduerr** [comment]
If your WM does not support this by default, Alacritty currently does not have any way to bind a minimize key without invoking an external command.

Though this should be trivial to add, if someone is interested in contributing.

**Comment by rafaelrinaldi** [comment]
@chrisduerr I might take a stab at it. Can you point me to the direction?

**Comment by chrisduerr** [comment]
Of course!

First of all, the required winit APIs to modify Window minimized state should be these:
https://docs.rs/winit/0.19.1/winit/struct.Window.html#method.show
https://docs.rs/winit/0.19.1/winit/struct.Window.html#method.hide

These probably need to be exposed on the `alacritty_terminar/src/window.rs` first. I think a `hide` method already exists, not sure about showing.

Then to hook it all up, the config.yml documentation and the input handling need to be modified. A good reference would be the existing `ToggleFullscreen` and `ToggleSimpleFullscreen` bindings. Searching this repo should find all instances of them and just copying what they do should be fine.

To go into a bit more detail, you'd need to define an action [like this](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/input.rs#L258) and then bind that action to modify the window [like this](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/input.rs#L304-L306).

That should basically be it, let me know if you need any more info and I can get into a bit more detail. There usually are people in #alacritty on the freenode IRC too if you need more real-time feedback.

**Comment by kchibisov** [comment]
@chrisduerr I think there is no method in `winit` to do it properly atm. The required method to perform `minimize` on `macOs` is [this one](https://developer.apple.com/documentation/appkit/nswindow/1419426-miniaturize?language=objc) ([rust binding for it](https://github.com/servo/cocoa-rs/blob/ea0667fdd2cffbdc442e50bbf6a2977ba7c2d322/src/appkit.rs#L1018)), which is not used in `winit` anywhere. The `minimize` and `hide` actions are different on `macOs`, we already have binding and action for `Hide`, however adding proper `macOs` `minimize` support requires a patch to `winit`.

The patch to `winit` should be very simple, it's about calling mentioned methods on `NSWindow`.

However, I can be wrong about it though.

**Comment by chrisduerr** [comment]
Ah okay, I had to read up on this myself, but it seems like hiding the window will make it invisible without adding it to the dock, while minimizing a window will make it invisible and add it to the dock.

Sounds like it does indeed need a macOS specific patch then.

**Comment by chrisduerr** [comment]
I've created an issue upstream: https://github.com/rust-windowing/winit/issues/983

Looking into this, it might be a good first issue for anyone interested in contributing to winit, assuming that the feature is accepted. I don't think this should be too complicated to implement.

**Comment by rafaelrinaldi** [comment]
I appreciate you looking into this @chrisduerr. Haven't had the time to give this a shot just yet but it is on my list.

**Comment by kkoscielniak** [comment]
What's the state of this issue? I just moved from iTerm2 and quite need that functionality

**Comment by kchibisov** [comment]
@kkoscielniak You can use github notification feature and subscribe to this PR https://github.com/rust-windowing/winit/pull/990 to be always informed about the status of this issue. As soon as it gets merged will add this feature to alacritty.

**Comment by kkoscielniak** [comment]
@kchibisov I use GitHub for around 10 years and never thought of it. Thanks!

**Comment by kchibisov** [comment]
@davidhewitt Is there a standard hotkey on Windows 10 to minimize a window? If "yes", is it working in alacritty right now?

**Comment by davidhewitt** [comment]
I believe Windows + Down Arrow. It's an OS window manager shortcut so I would expect it works. I can test in the morning.

**Comment by kchibisov** [comment]
>I can test in the morning.

It'll be very nice.

**Comment by chrisduerr** [comment]
> I believe Windows + Down Arrow. It's an OS window manager shortcut so I would expect it works. I can test in the morning.

Alt + Enter to fullscreen did not work, so it wouldn't surprise me if this didn't work either.

**Comment by davidhewitt** [comment]
Windows + Down Arrow does indeed work correctly for me. 🎉
