### ISSUE TITLE
Dragged filename with spaces lacks quotes

### ISSUE THREAD

**Issue by cpterry** [jwilm/alacritty#2539]
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | Linux     |
| Rust Version     | stable   |
| Display Server   | X11 |

# Summary
Dragging a file with spaces in the filename into Alacritty produces the filename missing quotation marks.

# Behavior
/mnt/storage/test file with spaces

# Expectation
'/mnt/storage/test file with spaces'

**Comment by chrisduerr** [comment]
Duplicate of https://github.com/jwilm/alacritty/issues/1335.
