### ISSUE TITLE
Vim response time on windows 7

### ISSUE THREAD

**Issue by nico-abram** [jwilm/alacritty#2540]
I'm using windows 7.

I usually use cmd, and hitting esc while in insert mode in vim is instant. When using alacritty there's a delay of ~3 secs after I hit escape until it exits insert mode. If I happen to press an arrow key in that interval vim actually inserts a weird cross shaped character in the text document. I've tried changing the default shell to cmd instead of powershell, but same thing (I also checked if powershell had any noticeable delay - it didn't).

As an aside alacritty uses about 35+kb of ram after I open it without doing anything, and after printing a few "DIR"'s it can easily reach 45+ (While cmd stays at around 1kb), but I'm not too worried about that and it's probably to be expected.

Also unrelated, but I think https://github.com/jwilm/alacritty/issues/1748 is no longer an issue.

As a third unrelated thing, I could not figure out a way to copy the cross shaped character to share here. Is there one (Or are there plans to add one?)? (On windows)

**Comment by chrisduerr** [comment]
> I usually use cmd, and hitting esc while in insert mode in vim is instant. When using alacritty there's a delay of ~3 secs after I hit escape until it exits insert mode

Use ConPTY, this is a Windows bug and there's nothing Alacritty can do (see https://github.com/jwilm/alacritty/issues/1680).

> As an aside alacritty uses about 35+kb of ram after I open it without doing anything

That's just the cost of loading the graphics drivers, after that Alacritty should be fairly conservative on memory usage.

> As a third unrelated thing, I could not figure out a way to copy the cross shaped character to share here. Is there one (Or are there plans to add one?)? (On windows)

If you're asking for a way to copy/paste, it's bound to ctrl+shift+c/v by default, similar to what most other terminal emulators do.
