### ISSUE TITLE
Alignment issues in CLI(ncurses?) programs

### ISSUE THREAD

**Issue by bananarne** [jwilm/alacritty#2542]
Which operating system does the issue occur on?
GNU/Linux (Gentoo)

If on linux, are you using X11 or Wayland?
X11

Things get aligned incorrectly in several programs, namely: alsamixer, htop

If you run those in combination with tmux it gets "corrected". Screenshots would describe this best, i guess:
https://ibb.co/x6gf8pr (upper right: htop without tmux, bottom right: htop with tmux)
https://ibb.co/6gxmyh2 (alsamixer, in shambles)

The config does not seem to matter(as it happens in default configuration)

debug output: http://dpaste.com/1F7RSWK
glxinfo: http://dpaste.com/0NK5XDV
alacritty versions: 0.3.2, 0.3.3_rc1
rust: 1.35.0

**Comment by kchibisov** [comment]
@bananarne What's your `alacritty` version? ( `alacritty --version` ) and your `$TERM` variable ( `echo $TERM` ) when running `alacritty` without config?

I wasn't able to reproduce this on the latest master with default configuration ( tested `xterm-256color` and `alacritty` `terminfo`s ), by running `alacritty` and just openning `alsamixer`/`htop`.

**Comment by bananarne** [comment]
The problem occurred in: 0.3.2, 0.3.3_rc1 both compiled with rust 1.35

my TERM env-variable is xterm-256color aswell.

i don't know what terminfo excatly is, but i compiled alacritty with it.

**Comment by chrisduerr** [comment]
Try setting your `TERM` to `alacritty` please. Also make sure no Alacritty config is present by running `alacritty --config-file /dev/null`.

**Comment by bananarne** [comment]
Yeah, sorry, i was actually sure i checked the config being "clean".

I modified the tab size from 8 to 2 and this results in this behaviour.

Sorry.
