### ISSUE TITLE
There is no root package in cargo metadata

### ISSUE THREAD

**Issue by msaglietto** [jwilm/alacritty#2546]
Which operating system does the issue occur on?
Linux blade-stealth 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

If on linux, are you using X11 or Wayland?
X11

Hey guys .. im trying to install the master version on ubuntu using cargo deb  and I get the following output 
```
alacritty master > cargo deb --install
cargo-deb: There is no root package in cargo metadata
```

Is this an issue of cargo deb or of alacritty?
```
rustc 1.36.0-beta.5 (07a9daea9 2019-06-07)
cargo 1.36.0-beta (c4fcfb725 2019-05-15)
cargo deb --version 1.18.0
```

**Comment by chrisduerr** [comment]
Please see the INSTALL.md for instructions on how to install the Alacritty deb package.

**Comment by msaglietto** [comment]
Sorry my bad I didnt saw the install method was changes  ... Thanks you

**Comment by rkj** [comment]
I am getting the same error following steps from:
https://github.com/jwilm/alacritty/blob/master/INSTALL.md#debianubuntu-1

**Comment by chrisduerr** [comment]
@rkj Are you sure you're in the correct directory when executing the command? Please note that these commands need to be executed in the Alacritty root directory and just `cargo deb --install` is not enough.

**Comment by rkj** [comment]
my bad, sorry for noise! I was executing from the parent directory. What confused me is that Cargo.toml exists in the root of the repo, I thought I should point to that file.
Thanks for working on this awesome terminal!
