### ISSUE TITLE
Cursor in apps with mouse mode doesn't set to `MouseCursor::Text` on shift press.

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#2550]
Linux X11
Alacritty version: `alacritty 0.3.3-rc2 (58e2365)`

In apps like `htop` (with mouse mode) when pressing `Shift` the cursor is left arrow (default one on my system) instead of text. So, text selection is a bit hard. Cursor should probably be `Default` without `Shift` and `Text` with `Shift`.

**Comment by jjsullivan5196** [comment]
Just for reference, this commit just unconditionally sets the cursor to `Text` when the `Shift` modifier is active. Tested with i3 and saw expected results. `Default` is shown in `htop` without `Shift` pressed, and `Text` is shown with `Shift` pressed.
