### ISSUE TITLE
Deprecation warnings on start (0.3.3)

### ISSUE THREAD

**Issue by a-y-u-s-h** [jwilm/alacritty#2558]
Which operating system does the issue occur on?
Arch Linux x86_64

If on linux, are you using X11 or Wayland?
X11

Version: 0.3.3

I get this yellow warning box at the bottom whenever  I launch alacritty, after I updated it to 0.3.3 today.

![2019-06-18_11-53-36_screenshot](https://user-images.githubusercontent.com/19586719/59657965-eb103600-91bf-11e9-8800-54a9f1e4ed98.png)

**Comment by JDTX** [comment]
As the message indicates, you're using an outdated directive `window.start_maximized`

Update your alacritty.yml config to use the new directive `startup_mode:` under `window:`, for an example, see here: https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L63

**Comment by a-y-u-s-h** [comment]
Fixed :+1: Nice DP.
