### ISSUE TITLE
Fonts have strange artifacts and are blurry after monitor upgrade

### ISSUE THREAD

**Issue by Nomad145** [jwilm/alacritty#2559]
>Which operating system does the issue occur on?

ArchLinux
bspwm + compton
alacritty 0.3.3-1
> If on linux, are you using X11 or Wayland?

X11

After upgrading to a new monitor (1080p -> 1440p), my terminal fonts are blurry.  It's difficult to see in a screenshot, but if you open the image below you can see artifacts drawn around each of the characters.  #844 is very similar, but was fixed a long time ago.

![image](https://user-images.githubusercontent.com/530807/59723247-88cd2a80-91eb-11e9-806c-2704f569431b.png)

I'm not sure what information is relevant, but here is my DPI according to `xdpyinfo` and my `font-config` settings:

```
 ~ xdpyinfo | grep dots
  resolution:    108x107 dots per inch
```

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <its:rules xmlns:its="http://www.w3.org/2005/11/its" version="1.0">
    <its:translateRule translate="no" selector="/fontconfig/*[not(self::description)]"/>
  </its:rules>

  <description>Enable sub-pixel rendering with the RGB stripes layout</description>
<!--  Enable sub-pixel rendering -->
  <match target="pattern">
    <!--
      This configuration is available on the major desktop environments.
      We shouldn't overwrite it with "assign" unconditionally.
      Most clients may picks up the first value only. so using "append"
      may simply works to avoid it.
    -->
    <edit name="rgba" mode="append"><const>rgb</const></edit>
  </match>
</fontconfig>
```

It's also worth noting that the same font (Hack) renders fine in other terminals under the same conditions.  I'm also only using one monitor right now, not switching between different DPIs.

Please let me know what other info I can provide.  I apologize in advance if this is a duplicate ticket.  Thanks for all the hard work!

**Comment by chrisduerr** [comment]
Could you try compiling #2438? This artifacting around fonts issue usually appears when the projection is stretched across invalid screen sizes. So Alacritty/Winit might not properly recognize/translate window sizes. So testing the latest winit version with this PR is probably a good idea before further troubleshooting steps.

**Comment by Nomad145** [comment]
Before posting earlier, I realized I was on an `alacritty-git` build from the AUR, so I installed the stable version from the ArchLinux community repository.  It didn't fix my issue then, but after rebooting and tweaking my Xconfig things are back to normal.  I wish I had more info to share than that, but all seems well now.  Thank you for your time, @chrisduerr!
