### ISSUE TITLE
Is WINIT_HIDPI_FACTOR env has deprecated?

### ISSUE THREAD

**Issue by dikiaap** [jwilm/alacritty#2560]
**Ubuntu 18.04, X11**
**Alacritty 0.3.3**

I'm using that env to disable DPI scaling. After upgrading to v0.3.3 the env is not working anymore.

```
cat /tmp/Alacritty-17820.log
[2019-06-19 05:22] [ERROR] Problem with config: invalid type: integer `1`, expected a string; using default value
```

**Comment by chrisduerr** [comment]
I'm not sure which change exactly caused this (potentially an update to the yaml library), but all env variables need to explicitly be strings now.

So using `"1"` instead should work.

**Comment by dikiaap** [comment]
It works by adding the double quotes. Thank you.
