### ISSUE TITLE
window.decorartions: none not working on Windows 10

### ISSUE THREAD

**Issue by benjaminbauer** [jwilm/alacritty#2564]
OS: Windows 10 Enterprise (10.0.17763 Build 17763)
alacritty version: alacritty 0.3.3 (cc3e4d3) 

My config:
```
shell:
  program: arch.exe
font:
  normal:
    family: DejaVuSansMono NF 
colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
window:
  decorations: none
```

It all works fine, until I set the `decorations` attribute to `none`. When I start alacritty with that config, a **window opens without any error, but it is not visible**

Output of alacritty.exe -vv run in Powershell:
```
Created log file at "C:\\Users\\XXXX\\AppData\\Local\\Temp\\Alacritty-18680.log"
[2019-06-19 17:06] [INFO] Welcome to Alacritty
[2019-06-19 17:06] [INFO] Configuration loaded from "C:\\Users\\XXXX\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2019-06-19 17:06] [DEBUG] Estimated DPR: 1
[2019-06-19 17:06] [DEBUG] Estimated Cell Size: 8 x 17
[2019-06-19 17:06] [DEBUG] Estimated Dimensions: None
[2019-06-19 17:06] [INFO] Device pixel ratio: 1
[2019-06-19 17:06] [INFO] Initializing glyph cache...
[2019-06-19 17:06] [INFO] ... finished initializing glyph cache in 0.0247164s
[2019-06-19 17:06] [INFO] Width: 1024, Height: 768
[2019-06-19 17:06] [INFO] Cell Size: 8 x 17
[2019-06-19 17:06] [INFO] Padding: 0 x 0
[2019-06-19 17:06] [INFO] PTY Dimensions: Line(45) x Column(128)
[2019-06-19 17:06] [INFO] Using Winpty agent
[2019-06-19 17:06] [INFO] Initialisation complete
```

**Comment by chrisduerr** [comment]
Could you try running the `window` examlpe in https://github.com/rust-windowing/glutin?

This is the patch you need to apply to disable decorations for the example:

```diff
diff --git a/glutin_examples/examples/window.rs b/glutin_examples/examples/window.rs
index f7da6c4..9ae551b 100644
--- a/glutin_examples/examples/window.rs
+++ b/glutin_examples/examples/window.rs
@@ -7,7 +7,7 @@ use glutin::ContextBuilder;
 
 fn main() {
     let el = EventLoop::new();
-    let wb = WindowBuilder::new().with_title("A fantastic window!");
+    let wb = WindowBuilder::new().with_title("A fantastic window!").with_decorations(false);
 
     let windowed_context =
         ContextBuilder::new().build_windowed(wb, &el).unwrap();
```

You can apply patches using `git apply patch.file` and then run the example using `cargo run --example window`.

**Comment by JDTX** [comment]
@chrisduerr I was able to replicate the problem that was described by the OP. Figured I'd lend a hand.

The glutin example you provided with the patch runs fine on my machine. It just shows a white empty window.

I tested a few Alacritty releases and discovered [0.3.0](https://github.com/jwilm/alacritty/releases/tag/v0.3.0) introduced the bug. [0.3.0 RC3](https://github.com/jwilm/alacritty/releases/tag/v0.3.0-rc3) works fine.


I decided to spot test the commits between 0.3.0 RC3 and 0.3.0 and found that [this commit to window.rs](https://github.com/jwilm/alacritty/commit/6757acbb824e8be9968529a66e9a75a0a2ea2f5d#diff-2ce3f8d26915325bbd02de9e0056281e) caused it.

Every commit before then works fine when `decorations: none` is used.

Hope that helps you.

**Comment by chrisduerr** [comment]
Could you try with #2438?

**Comment by JDTX** [comment]
I got a runtime error trying to run that PR
![image](https://user-images.githubusercontent.com/24833917/59957950-96d9b000-9464-11e9-8703-e3a1e7ac81e6.png)

This is what I ran to get that PR and build it:
`[cygw alacritty]$ git fetch origin pull/2438/head:pr2438
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Total 62 (delta 32), reused 32 (delta 32), pack-reused 29
Unpacking objects: 100% (62/62), done.
From https://github.com/jwilm/alacritty
 * [new ref]         refs/pull/2438/head -> pr2438
[cygw alacritty]$ git checkout pr2438
Previous HEAD position was cd8d537 Add new icon to macOS binary
Switched to branch 'pr2438'
[cygw alacritty]$ cargo build --release`

**Comment by chrisduerr** [comment]
Could you uncomment this line:
https://github.com/jwilm/alacritty/pull/2438/files#diff-65362e8e7fbdb92518e6216cd7f10722R575

I think that's causing the unimplemented error, but it should be irrelevant for working properly.

**Comment by JDTX** [comment]
Did you mean comment the line out instead of uncomment?

If so, I commented it out, got a warning about dead_code, but it compiled.  Running it didn't result in a runtime error, but the problem persists.

**Comment by chrisduerr** [comment]
Since the glutin example was just a white window instead of the rectangle it is supposed to render, I've reported this problem upstream:

https://github.com/rust-windowing/winit/issues/979

**Comment by chrisduerr** [comment]
@JDTX This should have been fixed 4 days ago in winit, I'm not sure if the version you've tested already had that fix in or not.

Could you test the #2438 PR again, I've bumped it again so the IME failure should not arise anymore and the latest winit version should be included. Would be much appreciated.

**Comment by JDTX** [comment]
@chrisduerr I received a compilation error with the latest code from the PR.
```
warning: unused imports: `SizeInfo`, `Term`
  --> alacritty\src\window.rs:38:32
   |
38 | use alacritty_terminal::term::{SizeInfo, Term};
   |                                ^^^^^^^^  ^^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0599]: no method named `with_visibility` found for type `winit::window::WindowBuilder` in the current scope
   --> alacritty\src\window.rs:309:14
    |
309 |             .with_visibility(cfg!(windows))
    |              ^^^^^^^^^^^^^^^ help: did you mean: `with_visible`

error: aborting due to previous error
```

**Comment by felixrabe** [comment]
@chrisduerr That looks like you use the former name of `with_visible` which was renamed in https://github.com/rust-windowing/winit/commit/2b89ddec15c897 on June 12 (almost 2 weeks ago).

**Comment by JDTX** [comment]
@felixrabe Thanks for the information. I ran these two commands against the PR to update them,
```
sed -i "s/with_visibility/with_visible/g" alacritty/src/window.rs
sed -i "s/with_transparency/with_transparent/g" alacritty/src/window.rs
```

@chrisduerr It built with the above changes, and it works now with decorations set to none!
![image](https://user-images.githubusercontent.com/24833917/60081257-0cf54580-96f7-11e9-8f6c-216054d88313.png)

**Comment by chrisduerr** [comment]
Thanks for the help with testing, looks like this will get fixed as soon as the glutin Evlp2 PR is merged.
