### ISSUE TITLE
Unnecessary padding at the top side of terminal window

### ISSUE THREAD

**Issue by miikkas** [jwilm/alacritty#257]
There's some unnecessary padding at the top of the terminal window, before the first text line starts. Changing the DPI or vertical offset doesn't seem to affect this. FWIW I'm using xmonad (a tiling WM).

Attached is a comparison of Irssi running in Alacritty (left) and urxvt (right).

![alacritty_padding_top](https://cloud.githubusercontent.com/assets/1662621/21767517/672e8f58-d67d-11e6-827f-f218f10f4e43.png)

**Comment by Elronnd** [comment]
It seems that a small amount of the bottom of the terminal is cut off.  Probably related.

**Comment by jwilm** [comment]
Resolved in 9316771f64842533181cfb04a27aa9ae809cc435
