### ISSUE TITLE
Weird carat behavior when scrolling

### ISSUE THREAD

**Issue by lovesegfault** [jwilm/alacritty#2570]
Using the latest Alacritty, on Gentoo, and under Sway I see this interesting behavior when scrolling. I think the best way to describe it is to show it:

[![Demo](https://i.imgur.com/Z9PlPfP.gif)](https://i.imgur.com/tLckMYA.mp4)

P.S. Click on image for full video.

**Comment by chrisduerr** [comment]
Can you reproduce this in X or XWayland? Also does setting a different cursor (using `printf '\e[4q'` for example) fix this?

**Comment by kchibisov** [comment]
@chrisduerr If the issue is about cursor, I can reproduce it on X11 with zsh just by opening new `alacritty` instance typing `ls -laF` bunch of times, then `Ctrl + l`, `ls -laF` and scroll up. It only happens when your prompt isn't at the bottom of the screen though (in the middle e.g).

**Comment by chrisduerr** [comment]
Huh, I don't think I was able to reproduce this in bash on macOS at work, but on X11/Arch/zsh I can reproduce it when following your steps.

I'm surprised I haven't noticed this, so my guess would be that this might be a regression. Testing the previous versions and bisecting the broken commit if those work might be a good idea.

**Comment by kchibisov** [comment]
@chrisduerr I'll bisect in a moment.

**Comment by chrisduerr** [comment]
That would be much appreciated, thanks for the help!

**Comment by kchibisov** [comment]
@chrisduerr This one cfc20d4f34dca535654cc32df18e785296af4cc5

**Comment by chrisduerr** [comment]
My best bet would be the following line which hasn't been carried over in the cursor rework:
https://github.com/jwilm/alacritty/commit/cfc20d4f34dca535654cc32df18e785296af4cc5#diff-7b3174257e73247b46a5a32b142d45beL440

I'm not sure *why* it is required, but replacing `self.cursor.line` with `self.inner.line` might be worth investigating. If that's not it, I'd have to look into this a bit more.

**Comment by kchibisov** [comment]
@chrisduerr I've applied the following diff on top of the cfc20d4 and it seems like it resolves the issue.
```
diff --git a/src/term/mod.rs b/src/term/mod.rs
index 9e879ad..2e1236a 100644
--- a/src/term/mod.rs
+++ b/src/term/mod.rs
@@ -378,7 +378,7 @@ impl<'a> Iterator for RenderableCellsIter<'a> {
                     let cell = Indexed {
                         inner: self.grid[self.cursor],
                         column: self.cursor.col,
-                        line: self.cursor.line,
+                        line: self.inner.line(),
                     };
                     let mut renderable_cell =
                         RenderableCell::new(self.config, self.colors, cell, false);
```

**Comment by chrisduerr** [comment]
Huh, that seems like an interesting pitfall. Do you want to send a PR or should I do that later? I think it might be worthwhile to add a comment to this line to state that this is intentional and why it's needed.

**Comment by kchibisov** [comment]
@chrisduerr I'll send it.
