### ISSUE TITLE
Ability to choose fall-back font

### ISSUE THREAD

**Issue by rupor-github** [jwilm/alacritty#2572]
Windows 10

Due to switch to DirectWrite information about fallback font (font linking, windows registry) is ignored. Quoting Microsoft:

"DirectWrite has fallback data that is not read from the registry or in any way configurable. In Windows 8.1, though, APIs have been introduced that allow an app to specify its own fallback. (It's similar to the WPF APIs for creating a composite font definition.)"

Is there a way to specify fallback font explicitly? If not - it will be very helpful to have, it is not always possible to use nerd font patch...

**Comment by chrisduerr** [comment]
This is largely addressed by #957 and mainly just waiting for a reasonable implementation. However other issues have had priority for now, so I can't make any guarantees about when an implementation is going to land.
