### ISSUE TITLE
vim color scheme is not set correctly when you use WinPTY

### ISSUE THREAD

**Issue by YsuOS** [jwilm/alacritty#2578]
This issue is a kind of tip!

I use alacritty 0.3.2 in Windows10
when I open vim, the color of vim is not set correctly.
(I expected the color scheme was 'gruvbox'! but this color was totally different)

![before_vim](https://user-images.githubusercontent.com/30138661/59967875-ce7f4f80-956b-11e9-9f47-ccfefa32967a.PNG)

but I change one parameter; turn on 'enable_experimental_conpty_backend: ture' (default: false), this color is set correctly

![after_vim](https://user-images.githubusercontent.com/30138661/59967885-e9ea5a80-956b-11e9-814f-5acfa06b0521.PNG)

I can't detect why it happens. sorry
anyway,
I'm pleased to help you who have the same problem.

**Comment by chrisduerr** [comment]
WinPTY simply doesn't support some of the things necessary to run all unix programs on Windows properly.

This has already been discussed in the following issues:
https://github.com/jwilm/alacritty/issues/1662
https://github.com/jwilm/alacritty/issues/1792

**Comment by Number7tSeven** [comment]
I am having a similar issue but changing the back-end to ConPTY doesn't help. I can't tell if the issue lies with Alacritty or with Vim. Gvim seems to use the correct colors. When I use Git in terminal the colors look right. Any ideas?
![colors](https://user-images.githubusercontent.com/26388519/60378731-f00d8a80-99f4-11e9-9a38-69f987793a63.jpg)

**Comment by chrisduerr** [comment]
@Number7tSeven GVim uses different colors than terminal vim.

**Comment by cup** [comment]
https://github.com/alacritty/alacritty/issues/2107
https://github.com/alacritty/alacritty/issues/1792
https://github.com/alacritty/alacritty/issues/1662
https://github.com/alacritty/alacritty/issues/2088

https://github.com/alacritty/alacritty/issues/2578
