### ISSUE TITLE
[feature request]: Zmodem(rz, sz) support

### ISSUE THREAD

**Issue by cossonleo** [jwilm/alacritty#2586]
Which operating system does the issue occur on?
linux
If on linux, are you using X11 or Wayland?
x11

please support zmodem.

**Comment by chrisduerr** [comment]
Zmodem is a file transfer protocol, making it completely unrelated to terminal emulators. How exactly should Alacritty support it?

**Comment by cossonleo** [comment]
When I type  rz/sz, there is no dialog pop. Alacritty only shows "rz waiting to receive.**B01000000"

**Comment by chrisduerr** [comment]
That's up to the rz/sz application, not Alacritty.

**Comment by aslatter** [comment]
For anyone finding this later, it looks like `screen` can be configured to receive zmodem transfers: https://www.gnu.org/software/screen/manual/html_node/Zmodem.html

**Comment by FGasper** [comment]
@chrisduerr Some terminal emulators, like iTerm 2 and Tera Term Pro of old, can be configured to recognize the ZMODEM escape sequence and pop up a file-receive dialogue in response.

So it’s quite relevant to terminal emulators. Whether it’s a feature you want to support is another question, of course. :)

**Comment by shuxiao9058** [comment]
how can i setting alacritty to support lrzsz?

**Comment by cossonleo** [comment]
> how can i setting alacritty to support lrzsz?

use zssh for lrzsz

**Comment by liuwenlang** [comment]
https://github.com/trzsz/trzsz-ssh 
可以用;

只需要把ssh修改为tssh, 比如: tssh username@host
