### ISSUE TITLE
Cannot change fonts on OpenSuSE Leap

### ISSUE THREAD

**Issue by Ra0EL** [jwilm/alacritty#2588]
Hi,

I am giving a try to Alacritty on my OpenSuSE Leap 15.1 x64 machine, running KDE / X11.
I have tried to change default fonts but it fails...
By changing default faults, I mean I only uncomment 2 lines in default config file, which eventually results in :
```
font:
   normal:
      family: hack
```
( yes I want to use Hack fonts...)

This what I can see - actually I cannot see anything :smile: - after this only modification :
![Screenshot_20190624_131318_001](https://user-images.githubusercontent.com/8389138/60014835-2f00b080-9682-11e9-9dd9-4e498e625f99.png)

If I keep `monospace` as default font, everything is running fine :
![Screenshot_20190624_131450_001](https://user-images.githubusercontent.com/8389138/60014888-56577d80-9682-11e9-9c11-4607219baf3d.png)

This is what I have with `-vv` option when everything is going fine (default config) :
```
Created log file at "/tmp/Alacritty-52120.log"
[2019-06-24 12:55] [INFO] Welcome to Alacritty
[2019-06-24 12:55] [INFO] Configuration loaded from "/home/dhenry/.config/alacritty/alacritty.yml"
[2019-06-24 12:55] [DEBUG] Estimated DPR: 1
[2019-06-24 12:55] [DEBUG] Estimated Cell Size: 9 x 18
[2019-06-24 12:55] [DEBUG] Estimated Dimensions: None
[2019-06-24 12:55] [INFO] Device pixel ratio: 1
[2019-06-24 12:55] [INFO] Initializing glyph cache...
[2019-06-24 12:55] [INFO] ... finished initializing glyph cache in 0.144904798s
[2019-06-24 12:55] [INFO] Width: 1024, Height: 768
[2019-06-24 12:55] [INFO] Cell Size: 9 x 18
[2019-06-24 12:55] [INFO] Padding: 2 x 2
[2019-06-24 12:55] [INFO] PTY Dimensions: Line(42) x Column(113)
[2019-06-24 12:55] [INFO] Initialisation complete
[2019-06-24 12:55] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-52120.log"
```

and what I have as soon as I changed default font :
```
Created log file at "/tmp/Alacritty-52743.log"
[2019-06-24 12:56] [INFO] Welcome to Alacritty
[2019-06-24 12:56] [INFO] Configuration loaded from "/home/dhenry/.config/alacritty/alacritty.yml"
[2019-06-24 12:56] [DEBUG] Estimated DPR: 1
[2019-06-24 12:56] [DEBUG] Estimated Cell Size: 1 x 1
[2019-06-24 12:56] [DEBUG] Estimated Dimensions: None
[2019-06-24 12:56] [INFO] Device pixel ratio: 1
[2019-06-24 12:56] [INFO] Initializing glyph cache...
[2019-06-24 12:56] [INFO] ... finished initializing glyph cache in 1.160412745s
[2019-06-24 12:56] [INFO] Width: 1024, Height: 768
[2019-06-24 12:56] [INFO] Cell Size: 1 x 1
[2019-06-24 12:56] [INFO] Padding: 2 x 2
[2019-06-24 12:56] [INFO] PTY Dimensions: Line(764) x Column(1020)
[2019-06-24 12:56] [INFO] Initialisation complete
```

Obviously, the problem is with `Estimated Cell Size: 1 x 1` ( plus `PTY Dimensions: Line(764) x Column(1020)`). But no idea how to fix that, neither why it happens, since I am still using default yml file, just changed default fonts.

Actually, I wanted to change default fonts because Alacritty cannot display any Emoji like in Konsole, as illustrated below :
![Screenshot_20190624_132244_001](https://user-images.githubusercontent.com/8389138/60015247-4be9b380-9683-11e9-8fc2-92abff9f67bc.png)

Any idea ?

**Comment by kchibisov** [comment]
Could you post output of `fc-list | grep -i hack`? I've tried your configuration on my system and it worked fine.

FYI `alacritty` doesnt support colored emojis on linux atm #153

**Comment by Ra0EL** [comment]
This is what i have :
```
fc-list | grep -i hack
/usr/share/fonts/truetype/Hack-Bold.ttf: Hack:style=Bold
/usr/share/fonts/truetype/Hack-Italic.ttf: Hack:style=Italic
/usr/share/fonts/truetype/Hack-Regular.ttf: Hack:style=Regular
/usr/share/fonts/truetype/Hack-BoldItalic.ttf: Hack:style=Bold Italic
```

**Comment by chrisduerr** [comment]
Make sure you're using consistent whitespace (preferrably two blanks) in the config file and you're not using tabs.

Generally, this should be a fully functional config file, without anything else necessary:
```
font:
  normal:
    family: Hack
```

**Comment by Ra0EL** [comment]
I know little about YAML syntax, but I would say my config file is sane.
As I said, I did only make sure these 3 lines are uncommented and replace `monospace` value by `hack`.

Just in case you may ask, I run alacritty v0.3.2.

**Comment by chrisduerr** [comment]
Could you share your complete configuration file please?

**Comment by Ra0EL** [comment]
Find file below ( extension changed to `.txt` to upload it on this site ).

[alacritty.txt](https://github.com/jwilm/alacritty/files/3321627/alacritty.txt)

**Comment by chrisduerr** [comment]
Do you have any fontconfig configuration? The configuration file actually seems correct and works on my system with the Hack font too.

What do you get when you run `fc-match Hack`?

**Comment by Ra0EL** [comment]
```bash
# fc-match hack
NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"
```
Only modification in fontconfig is addition of file  `~/.config/fontconfig/conf.d/99-my.conf` with this content :
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match>
    <test name="family"><string>Hack</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Noto Color Emoji</string>
    </edit>
  </match>
</fontconfig>
```

**Comment by chrisduerr** [comment]
So I'd assume if you remove this config, everything works?

**Comment by Ra0EL** [comment]
Good guess. Now it works - should I feel ashamed :confounded: ?

So, knowing that I do need colored emoji as fallback for Hack fonts, for other purposes, how could I correctly set my fontconfig - as the problem lies here...

**Comment by chrisduerr** [comment]
See https://github.com/jwilm/alacritty/issues/153 for an issue about emoji support.

**Comment by kchibisov** [comment]
@Ra0EL You can try something like this.
```
<match target="pattern">
 <test name="family" qual="any">
  <string>Hack</string>
 </test>
 <edit name="family" mode="prepend_first">
  <string>Hack</string>
 </edit>
 <edit name="family" mode="prepend_first">
  <string>Noto Color Emoji</string>
 </edit>
</match>
```

**Comment by Ra0EL** [comment]
@kchibisov :+1: Excellent !
Everything fixed now.
Many thanks to all of you, guys.

**Comment by oblitum** [comment]
I tried that setting on ArchLinux with Monoid Nerd Font + Noto Color  Emoji but it simply didn't work :-/

**Comment by kchibisov** [comment]
@oblitum What do you mean by "it simply didn't work"? Displaying **color** emojis aren't implemented on Linux yet. You should be able to see your `Monoid Nerd Font`, but you can't see emojis from `Noto Color Emoji`, since it simply doesn't have a way to display monochromatic ones. Twitter Color Emoji can be rendered in `alacritty` in monochrome variant though.

If you have problems with writing `fontconfig` file I can help you, just give me instructions on what you want to achieve.

**Comment by oblitum** [comment]
@kchibisov Sorry, I thought the setting was about getting colored emojis working in Alacritty. I do have some monocromatic ones, probably from Nerd Font itself, already present, but not the ones from Noto Color Emoji that work fine on termite.
