### ISSUE TITLE
apt doesn't show properly on debian

### ISSUE THREAD

**Issue by GenaBitu** [jwilm/alacritty#259]
If I try to use apt (not apt-get!) on debian the terminal starts drawing over previous lines, doesn't properly show the progress bar at the bottom and finally clears the whole screen on finish.

**Comment by miedzinski** [comment]
Just did `apt update && apt upgrade`. Alacritty was able to draw progress bar and everything related correctly. I think it may have been fixed.

**Comment by GenaBitu** [comment]
Confirmed, I updated Alacritty and the issue has been resolved
