### ISSUE TITLE
Hangs when pasting from clipboard

### ISSUE THREAD

**Issue by dshoreman** [jwilm/alacritty#2595]
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | Linux     |
| Display Server   | X11 |
| Window Manager   | i3 |
| Compositor       | compton |

# Summary
When attempting to paste from the clipboard, Alacritty hangs for a few seconds (multiplied by the number of times <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd> is pressed). I searched and found a few other clipboard issues but they all seem to affect Wayland rather than X11.

This has only been an issue since updating Alacritty from 0.3.2 to 0.3.3.

# Behavior
If I use Nextshot to take a screenshot then paste the URL into Alacritty, it hangs before oh-my-zsh finally spits out a `bracketed-paste-magic:zle:47: not enough arguments for -U` error and nothing is pasted. If I paste the URL into Firefox, then copy from the address bar back into Alacritty, it works as expected.

# Expectation
Link should be pasted into the terminal without hanging

# Extra
While OMZ spits out an error, plain zsh (with `zsh -f`) and bash hang with no error.

If I run Alacritty with `-vv`, when it hangs I get:
```
Unable to load text from clipboard: Selection timed out
```

This seems to only affect clipboard contents that has a mime type (or specific target?)  set:
![image](https://user-images.githubusercontent.com/1521802/60172610-e7eef880-9804-11e9-8dd6-06f55af95126.png)

As an aside, pasting images from Firefox still displays the `bracketed-paste-magic` error from OMZ, but does not hang. If an image is pasted after being copied with `-t image/png`, it hangs and errors the same as text.

**Comment by chrisduerr** [comment]
How do other terminal emulators behave when trying to paste into them?

**Comment by dshoreman** [comment]
Termite works as expected, as does Alacritty if I downgrade back to 0.3.2. It got a bit confusing with multiple terms, versions, flags and content types so I've put it all in tables.

### Alacritty 0.3.2
| xclip flags     | Content | Behaviour |
| --------------- | ------- | --------- |
| None		      | Text    | Works     |
| `-t text/plain` | Text    | Works     |
| None	    	  | Image   | No hang - `Error: target STRING not available` in shell |
| `-t image/png`  | Image   | No hang - Red Alacritty Error (screenshot below) |


### Alacritty 0.3.3
| xclip flags     | Content | Behaviour |
| --------------- | ------- | --------- |
| None		      | Text    | Works     |
| `-t text/plain` | Text    | Hangs then `bracketed-paste-magic` error*     |
| None	    	  | Image   | No hang, but still gets `bracket-paste-magic` error*     |
| `-t image/png`  | Image   | Hangs then `bracketed-paste-magic` error*      |

> \* `bracketed-paste-magic:zle:47: not enough arguments for -U` happens only in Oh My ZSH.
>   Bash (and ZSH with `-f`) do not display the error, but otherwise behaviour there is the same.

### Termite
| xclip flags     | Content | Behaviour |
| --------------- | ------- | --------- |
| None		      | Text    | Works     |
| `-t text/plain` | Text    | Works     |
| None	    	  | Image   | No hang - fails silently |
| `-t image/png`  | Image   | No hang - fails silently |

---

Alacritty error in 0.3.2 (somewhat expected given it's an image):
![image](https://user-images.githubusercontent.com/1521802/60212008-35488580-9858-11e9-8ab5-b7800fc9b21a.png)

**Comment by chrisduerr** [comment]
I've reported this upstream in https://github.com/quininer/x11-clipboard/issues/13.

**Comment by mastern2k3** [comment]
Bump, getting this too.
Started happening after upgrade from 0.3.2 to 0.3.3

**Comment by marekdedic** [comment]
Hi, I'm still getting this issue.

I'm on alacritty 0.3.3 (14fa026), zsh 5.7.1 (x86_64-debian-linux-gnu) and using OhMyZSH.

When trying to paste, I get:
```
bracketed-paste-magic:zle:47: not enough arguments for -U
```

This didn't happen before a recent update...

**Comment by chrisduerr** [comment]
Is that in Wayland or X11? That sounds like your zsh config might be a bit odd.

**Comment by chrisduerr** [comment]
#2574 #2453.

**Comment by marekdedic** [comment]
That will be it, I've noticed over the day the issue sometimes going away...

**Comment by snuck007** [comment]
I'm getting it just pasting into terminal from putty.

**Comment by anibal-aguila** [comment]
I have the same issue:

```
bracketed-paste-magic:zle:47: not enough arguments for -U
```

**Comment by dshoreman** [comment]
Sorry, I've been a bit busy and haven't had the time to test this until now.

I can confirm the hang is fixed by #2603, but text still does not get pasted when xclip's `-t, -target` option is set to `text/plain`. Under OMZ the bracketed paste error appears on a new line, while "vanilla" Zsh acts as if no keys were pressed at all. Given the upstream commit that fixed the hang, this seems to be expected behaviour.

That said, when no target is passed to xclip, paste remains working without any hang or error so to workaround it I'll simply not set a target under X11 until upstream has support (or I learn Rust, whichever comes first).

**Comment by nixpulvis** [comment]
I can run `xclip -o -t text/plain` without any issues on the latest master. I have xclip 0.13-2 installed on Arch Linux FWIW.

**Comment by dshoreman** [comment]
@nixpulvis 	I'm running the same version of xclip as you (also on Arch).

`xclip -o -selection clipboard -t text/plain` works fine; the issue lies in pasting with ctrl-shift-v after doing `echo foo | xclip -selection clipboard -t text/plain`.

Middle-click works to paste, but that seems to be pulling from the `primary` selection rather than `clipboard` which is what you'd get with the keybinding.

**Comment by nixpulvis** [comment]
@dshoreman ah, sorry I misunderstood you. I can indeed replicate this.

What's somewhat interesting, is that `xclip` is adding a <kbd>ctrl-v</kbd> binding, which works, but doesn't paste the trailing newline, where as, Termite for example does print the trailing newline when using their paste command. Kitty also seems to have this same bug, FWIW.

**Comment by nixpulvis** [comment]
Sounds like we're waiting on x11-clipboard/issues/7 to handle this.
