### ISSUE TITLE
Can't set my own fonts ...

### ISSUE THREAD

**Issue by vaskark** [jwilm/alacritty#2596]
Hi. I can't seem to set my own fonts. I keep getting this error:

`[2019-06-26 16:00] [ERROR] Unable to load config "/home/vaskark/.config/alacritty/alacritty.yml": Problem with config: while parsing a block mapping, did not find expected key at line 139 column 7`

Can anyone offer some advice? Thanks.

Which operating system does the issue occur on?
Ubuntu Disco 19.04

If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment]
Your configuration file is broken. There might be a line commented out or the indentation isn't correct (2 spaces everywhere).

If you can't figure it out, feel free to just post the config and I can take a look.

**Comment by vaskark** [comment]
[https://pastebin.com/avBkrnBG](url)

**Comment by vaskark** [comment]
[https://pastebin.com/acqbh1Gr](url)

**Comment by vaskark** [comment]
[Link](https://pastebin.com/acqbh1Gr)

**Comment by chrisduerr** [comment]
The `normal:` block is commented out (see the `#`). This is the case for the bold and italic block too. Once that's removed, it'll work fine.

Also fyi, the bold and italic blocks are optional if you want to use the same font, so you don't have to specify the `family` there.

**Comment by vaskark** [comment]
It works now. Thanks a lot for your help.
