### ISSUE TITLE
Clipboard contents lost upon closing

### ISSUE THREAD

**Issue by chrisjbillington** [jwilm/alacritty#2597]
I'm on Arch Linux under Xorg.

If I copy text from Alacritty by selecting it and pressing ctrl+shift+c, and then close alacritty, the text is lost and cannot be pasted. If alacritty is still open however, then pasting works fine.

I understand this is how Xorg works without doing extra work, however most applications (or more likely, the GUI toolkits they use) have over the years implemented the extra work required to make copied text still pastable after the application closes, in fact I haven't seen paste data disappear for so long that I forgot about this until a moment of confusion with an empty clipboard after closing alacritty.

It would be a nice improvement for alacritty to do whatever magic is needed for pasting after closing to work for it as well under Xorg.

**Comment by chrisduerr** [comment]
This is solved by a clipboard manager which is shipped by many DEs out of the box already. Alacritty is not the place to reinvent the wheel here.

**Comment by chrisjbillington** [comment]
Ok, no problem.

I've shied away from clipboard managers since they retain histories and things like that, and I don't want to have to think about making sure I don't accidentally store a password or something like that. All I want is this 'don't lose clipboard on close' functionality.

But since I'm on GNOME it looks like there will be a default clipboard manager soon enough, which will probably do something sensible:

https://gitlab.gnome.org/GNOME/mutter/merge_requests/320

so I'll just wait a couple of months probably.

**Comment by chrisduerr** [comment]
> I don't want to have to think about making sure I don't accidentally store a password or something like that

Every half-decent password manager which supports automatically coping to the clipboard should support clearing the clipboard after a timeout.

**Comment by chrisjbillington** [comment]
I know that, but I will have to make sure I configure it correctly. It's more moving parts and makes it more likely I will make a mistake than without one. Nonetheless I am happy to use one, just explaining why I have not used one so far.

**Comment by zim0369** [comment]
I use a tiling window manager and basically would never use a DE. Is there no way to make it work? 

```
autocmd VimLeave * call system("xsel -ib", getreg('+'))
```

This is the trick for vim. the clipboard has the content after closing vim as well as the terminal. Can something similar to this be done?
