### ISSUE TITLE
Scrolling causes prompt to be deletable

### ISSUE THREAD

**Issue by GenaBitu** [jwilm/alacritty#260]
When I have a clean terminal, with the promt like:
```bash
user@machine:~/some/path$
```
and I scroll in the terminal (using a touchpad) instead of scrolling the terminal, I get a bunch of characters entered, something like these lines:
```bash
user@machine:~/some/path$ `;`;`;`;
user@machine:~/some/path$ `5`5`5`5
user@machine:~/some/path$ `I.`I.`I.`I.
```
When I then try to delete those, I can delete parts of path as well, the prompt being left incomplete. Enter fixes that (the new prompt is ok)

Also, when I later use up/down keys, the prompt is messed completely, with the previous wrong inputs replacing parts of it, for example:
```bash
user@machine`;`;`;`;`;`;``>`>`>`>`>`>`¨ortest
```
which i believe was ```colortest``` originally.
Also when I press enter on this invalid line, I get endless lines of the format
```bash
>
```
until I press Ctrl-C.

Could be related to: I was running apt (See #259 , but I restarted Alacritty afterwards) and also the current path has a space in it.

**Comment by GenaBitu** [comment]
Oh I think I nailed it down a bit: It seems like this only happens when I have alacritty maximised, then alt-tab to chromium, enter some text in a text field (like I am doing right now) and then alt-tab back. Then the current Terminal window is "poisoned" and continues doing this even on new lines. Also doesn't happen every time, so there might be something I don't see. Also happens for every path, not just ones with a space in them.

Also: I am running debian testing with gnome, on a Lenovo T460.

**Comment by jwilm** [comment]
This should be resolved

**Comment by GenaBitu** [comment]
Can confirm.
