### ISSUE TITLE
Hangs on broken pipe

### ISSUE THREAD

**Issue by olingern** [jwilm/alacritty#2600]
### Which operating system does the issue occur on?
**OS**: Arch Linux x86_64
**Kernel**: 5.1.12-arch1-1-ARCH

### If on linux, are you using X11 or Wayland?
X11

### Steps to reproduce
1. Open alacritty
2. `ssh` into a remote server
3. Disconnect your wifi / ethernet

Alacritty is now unresponsive. If you reconnect your wifi / ethernet -- it will then spit out all the previous keystrokes made while disconnected.

### Description
If I change connections and have a session on a server, alacritty doesn't handle SIGPIPE ( _it seems_) and end the session. It then becomes unresponsive.

Also, up for sending a PR if it's actually a bug and someone can post a code pointer :mag:

**Comment by chrisduerr** [comment]
> If I change connections and have a session on a server

Which connections do you have? What sessions are you talking about?

**Comment by olingern** [comment]
@chrisduerr I added steps to reproduce and reproduced again.

**Comment by chrisduerr** [comment]
@olingern Why do you think this is an Alacritty bug? As far as I know, this is the expected behavior on all terminal emulators I know.

**Comment by olingern** [comment]
I should be able to issue a SIGINT to exit the session and make alacritty responsive and cannot. If this is not a bug, please go ahead and close.

**Comment by royborgen** [comment]
It is not a big in Alacritty itself, however on i.e. Gnome Terminal you can press `Enter`, followed by `~.` and the hung session will terminate. This does not work in Alacritty.

**Comment by chrisduerr** [comment]
> It is not a bug in Alacritty itself, however on i.e. Gnome Terminal you can press Enter, followed by ~. and the hung session will terminate. This does not work in Alacritty.

That's an SSH feature and has nothing to do with Alacritty. It works in Alacritty too.

**Comment by royborgen** [comment]
ok, is there anything I need to do to get it working, because it is not working for me
