### ISSUE TITLE
New Window?

### ISSUE THREAD

**Issue by ianpan870102** [jwilm/alacritty#2607]
> Which operating system does the issue occur on? macOS

I frequently need new window instances of terminals, and I'd love to see this functionality built-in. Something like Command+N to open a new window should be reasonable.

**Comment by chrisduerr** [comment]
Is [this](https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L476) what you're looking for?

**Comment by ianpan870102** [comment]
Sorry but I can't seem to see where you are pointing at. Do you mind giving me a bit more details? Cheers!

**Comment by kchibisov** [comment]
@ianpan870102 He is pointing to the config section with `action`s that you can bind. There is an action to spawn new instance (called `SpawnNewInstance`). To make use of it you should add the following keybinding (tune it for your needs, in case you don't like `Command + N`).

`- { key: N,  mods: Command, action: SpawnNewInstance }`

**Comment by ianpan870102** [comment]
Thanks @chrisduerr @kchibisov 

The keybindings work now. However, Alacritty actually creates a new instance (should've guessed it from the command's name) instead of supporting multiple windows within the same instance. A side effect (at least on macOS) is that I now have a bunch of Alacritty icons (looks kinda funny).

Is there a specific reason that the developers did not choose to support multiple windows? (E.g. for performance, considering lightweight-ness etc ?)

**Comment by h-michael** [comment]
@ianpan870102 See this https://github.com/jwilm/alacritty/issues/607 :)

**Comment by ianpan870102** [comment]
@h-michael Thanks for the reference, just skimmed through it, so basically... to use Alacritty one is recommended to use tmux? (that sounds like the majority of the comments). In short, alacritty devs are not really interested in implementing this natively?

**Comment by h-michael** [comment]
@ianpan870102 
I don't know current project policy.
But when project started, this project have policy that Alcritty keep be simplicity.

https://jwilm.io/blog/announcing-alacritty/

> Simplicity: Alacritty should be conservative about which features it offers. As we’ve learned from past terminal emulators, it’s far too easy to become bloated. st taught us that it doesn’t need to be that way. Features like GUI-based configuration, tabs and scrollback are unnecessary. The latter features are better provided by a terminal multiplexer like tmux.

But this project does not mean that it will not contain new features.

https://github.com/jwilm/alacritty/pull/1147#issuecomment-422915275

**Comment by chrisduerr** [comment]
Generally, unless an issue is explicitly marked as low priority or it has been explicitly stated, it's usually a safe bet to expect that there's generally nothing major keeping it from being implemented other than a person willing/capable of implementing it. Especially when marked as `help wanted`.

So this is definitely not out of scope, quite the opposite. It's actually necessary to get a properly working application on macOS, which is also why it's one of the pinned issues. It's just that other issues have priority right now. And this issue has a relatively high effort.

**Comment by MacAhmed** [comment]
How would one go implementing something like this? If someone can point me in the correct direction, I am happy to give it a shot. I like alacritty and the major annoyance at this stage is that I can't use it across multiple monitors. Having more than one window would be helpful.

**Comment by chrisduerr** [comment]
The best place would probably be to look at the previous work done by sodiumjoe [here](https://github.com/jwilm/alacritty/pull/1589) and going from there.

**Comment by j0ker70** [comment]
Maybe I am really dumb but I can't seem to find the "Command" key. Can someone help?

**Comment by j0ker70** [comment]
Sorry for my inconvenience. It was the apple key which I was not familiar with.

**Comment by kchibisov** [comment]
For new window it's `CreateNewWindow` though.

**Comment by ret2src** [comment]
> For new window it's `CreateNewWindow` though.

Thanks, updated my answer. At least on KDE Plasma both of them lead to the same _visual_ result, though.

**Comment by iyxan23** [comment]
TOML version for those who might need it:

```toml
[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
```
