### ISSUE TITLE
feature request: Support blink text

### ISSUE THREAD

**Issue by foisonocean** [jwilm/alacritty#2609]
Which operating system does the issue occur on?
macOS

When type something like `echo  -e "\033[33;5mBlink Text\033[0m"`, in other terminals like `Terminal.app` or `iTerm2`, they can render text with blink effect. So I wish Alacritty can also support this feature.

**Comment by nixpulvis** [comment]
I'm assuming this is the same as #302. Closing in favor of that issue. If I'm somehow confused, feel free to reopen.

**Comment by chrisduerr** [comment]
@nixpulvis This is about blinking text (escape sequence `\e[5m` as mentioned in the issue) and not the blinking cursor (which is just a way to indicate focus).

**Comment by nixpulvis** [comment]
@chrisduerr lol, oh boy. I caught a bad case of the Mondays. Sorry for the noise.

**Comment by nixpulvis** [comment]
OK, I was correctly remembering this was a dup, just hastily linked it to the wrong issue.

Closed as a dup of #2365.
