### ISSUE TITLE
macOS: Make thin strokes toggleable

### ISSUE THREAD

**Issue by pikajude** [jwilm/alacritty#261]
iTerm has an option called "Use thin strokes for anti-aliased text" which I have set to Never.

When it's disabled, Hasklig Light looks like this, which is nice and readable on both my retina display and my external standard DPI monitor:

![iterm](https://i.imgur.com/gby76E7.png)

alacritty obviously has no such option, and Hasklig Light looks like [this](https://i.imgur.com/o7WeYiR.png). Similarly, [this is what it looks like when the option is enabled in iTerm](https://i.imgur.com/cLrCrQI.png).

Do you happen to know if the "thin strokes" option is a feature of macOS's font rendering system or if it's specifically an iTerm feature? Would it be feasible to replicate it?

**Comment by jwilm** [comment]
I think thin strokes are used by default on macOS. This should be a configuration option.

**Comment by mitchellhenke** [comment]
I'm on macOS 10.12.1, and do not have thin strokes

**Comment by tcrayford** [comment]
https://github.com/jwilm/alacritty/pull/277

**Comment by tcrayford** [comment]
@mitchellhenke @pikajude this is now merged: https://github.com/jwilm/alacritty/pull/277

**Comment by tcrayford** [comment]
@jwilm should we close this issue?
