### ISSUE TITLE
Regression with scrolling performance

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#2613]
While doing some tests with profile guided optimization, I've noticed that normal scrolling (the type that is done by `yes`), is extremely slow on the latest master.

I've tested this with the version I'm currently running (f002171) and there's no such performance issue there.

So somewhere in between 707f4293667d4d8564ab0afc13128463c2ee7fd5 and f002171 there must have been a change significantly impacting the performance of scrolling content inside of Alacritty.

My best bet would be https://github.com/jwilm/alacritty/commit/0815774cbfb9d1421b8077d5d9d641faf5f818c1, however I haven't bisected it yet, so I'll update this issue when I've got some additional information.

**Comment by kchibisov** [comment]
@chrisduerr I've decided to bisect it (I'm always running `perf` to test for the performance changes, when sending `PR`s, so was a little bit surprised, that I didn't noticed it in a first place). So, af30f37 has introduced the issue. The result of
`perf stat -r 10 vtebench -b 10000000 scrolling` on 0815774 is
```
1.09668 +- 0.00412 seconds time elapsed  ( +-  0.38% )
```
on af30f37
```
6.39654 +- 0.00654 seconds time elapsed  ( +-  0.10% )
```
and on f002171
```
1.09115 +- 0.00399 seconds time elapsed  ( +-  0.37% )
```

**Comment by chrisduerr** [comment]
That definitely makes some sense, though it surprises me the impact is so huge. I'll take a look if there's a good way to resolve this properly. The `occ` of Row might have to be fixed/reworked a bit.
