### ISSUE TITLE
multi-byte chars not shown when use tmux as start shell

### ISSUE THREAD

**Issue by SolaWing** [jwilm/alacritty#2615]
Which operating system does the issue occur on?
Mac OS Mojave 10.14.4

when set tmux as start shell program,  multi-byte char show as __. (though invisible, but can normal copy and paste)

it's ok when use default bash login, and then execute `tmux`

the screenshot is:

<img width="161" alt="图片" src="https://user-images.githubusercontent.com/3897953/60751462-6a3aa200-9fe7-11e9-9731-485a6cdd60f4.png">

after unset shell program and use the default bash login, then attach tmux

<img width="157" alt="图片" src="https://user-images.githubusercontent.com/3897953/60751465-a3731200-9fe7-11e9-9d57-cd35afb1f2c8.png">

**Comment by kchibisov** [comment]
@SolaWing that's the problem with your `tmux`, and not with `alacritty`. Try starting tmux with `tmux -u`. Also what's the output of `locale`?

The `underline`s are placeholders inserted by `tmux`.
