### ISSUE TITLE
How can i change the cursor color in insert

### ISSUE THREAD

**Issue by taigacute** [jwilm/alacritty#2617]
the color of beam same as block. how can i change it?

**Comment by kchibisov** [comment]
@taigacute can you elaborate? Do you want different colors for the different cursors?

**Comment by taigacute** [comment]
@kchibisov   use neovim .  i think the different color between normal mode and insert mode is good.
now . i set the cursor color yellow . when use neovim .  i want cursor color is green in insert mode
normal
![1](https://user-images.githubusercontent.com/41671631/60754465-e1862b00-a013-11e9-811a-2447ff453af6.png)
insert
![2](https://user-images.githubusercontent.com/41671631/60754467-e6e37580-a013-11e9-8ff9-5ce13196a572.png)

**Comment by kchibisov** [comment]
@taigacute Neovim can handle this by default `:help guicursor`. However it seems like the cursor color changing with escape sequence is broken atm.

@chrisduerr This command changes the cursor on `alacritty v0.3.0` `printf '\033]12;#333333\007'` , but doesn't work at all on the latest master. So apps like `neovim` can't change cursor color anymore. I guess this was introduced by cursor rework.

**Comment by taigacute** [comment]
@kchibisov  thanks for your reply. got it.

**Comment by chrisduerr** [comment]
Bisect might be useful on this, I suspect that you're right @kchibisov and this is about the cursor change, however the parsing for this escape has also changed recently. But I think that is less likely to be the problem.
