### ISSUE TITLE
Links without a space after it

### ISSUE THREAD

**Issue by zethra** [jwilm/alacritty#2627]
If there is text after a link with non white space delimiter between them hovering over this text will show the underline under the link and clicking it will open the link but the underline is only under the link not the text.  Additionally if there is a second link in this text it will not detected.

Example:
A markdown link `[http://example.com](http://example.com)`

I'm on macos using 0.3.2

**Comment by chrisduerr** [comment]
I can reproduce, looks like there's a bit of a problem with the combination of brackets here.

> the underline is only under the link not the text

If I understand you correctly, you mean that the [text] part of the URL should get underlined? This is not intended and will not be supported. So I'd like to limit this feature to the incorrect detection of URLs with the combination of brackets here.

**Comment by zethra** [comment]
The correct text is underlined. The bug is that the text after the link when click will cause the link before it to open even though the link wasn't clicked
