### ISSUE TITLE
Vim <C-q> commands not recognized

### ISSUE THREAD

**Issue by jeremydr2** [jwilm/alacritty#2628]
Which operating system does the issue occur on?
MacOS Mojave 10.14.5

Issue:
I have keybinds in vim that let me close with ctrl+q,q:

```vim
inoremap <C-q>q <esc>:q!<cr>
nnoremap <C-q>q :q!<cr>
```

When using alacritty and vim (with or without tmux) I am unable to use this command.
When using Terminal.app and vim (with or without tmux), this command works fine.

Interestingly, 
```vim
inoremap <C-u>q <esc>:q!<cr>
nnoremap <C-u>q :q!<cr>
```

works as expected. The only thing I can find in my alacritty.yml file is `key: q, mods: Command`, which I don't expect to interact. Can you think of anything that would be causing this?

Edit: I have `stty -ixon` in my `.bashrc` which I expect to be able to let me use C-q

**Comment by chrisduerr** [comment]
I'm not able to reproduce this on Linux.

If you add a binding with control + q in your Alacritty config, does that work? Also do other combinations using control work properly?

**Comment by jeremydr2** [comment]
Changing to 

    - { key: Q,        mods: Control, chars: echo "hi" }
    - { key: S,        mods: Control, chars: echo "hi" }

does what I expect in my alacritty config. Changing to

    nnoremap <C-p> :q!<cr>
    nnoremap <C-d> :q!<cr>

in my vimrc works fine.

**Comment by jeremydr2** [comment]
After tinkering more, I found that I am only able to quit on vim with 

    nnoremap <C-q> :q!<cr>

and typing ctrl+q, ctrl+q.

I believe this means something in alacritty is eating my first call of Ctrl+q.

**Comment by jeremydr2** [comment]
This issue is a duplicate of #1359
