### ISSUE TITLE
One character from tmux right pane shows up on left side of left pane

### ISSUE THREAD

**Issue by gavinhoward** [jwilm/alacritty#2632]
Which operating system does the issue occur on?

Linux, Ubuntu 19.04.

If on linux, are you using X11 or Wayland?

X11.

`alacritty` version: current master (also reproducible in 0.3.3 deb)
`tmux` version: 2.9a

Various screenshots:

![Screenshot from 2019-07-09 16-30-21](https://user-images.githubusercontent.com/3172687/60929460-a7fd2c00-a26e-11e9-9ffb-d5aeed78eecf.png)
![Screenshot from 2019-07-09 16-54-34](https://user-images.githubusercontent.com/3172687/60929462-ab90b300-a26e-11e9-8381-a920515455ca.png)
![Screenshot from 2019-07-09 17-23-21](https://user-images.githubusercontent.com/3172687/60929464-adf30d00-a26e-11e9-9004-da6a2b8ced38.png)

Notice the very ***left side*** of the images.

Steps to reproduce:

1. Open `alacritty`.
2. Run `tmux`.
3. Split `tmux` vertically (`C-b %`).
4. Focus on the right pane.
5. Run `tmux select-layout main-vertical`.
6. Run any command that will have output that will overflow a line.

The issue gets fixed when resizing, but after resizing, it happens again. (See image 2.) Note that other text is messed up after resizing. (See the top prompt in image 2.)

This is not related to #1288 or #1295 as there are no Unicode characters on the screen.

**Comment by kchibisov** [comment]
I can't reproduce this issue. Could you provide the following:
- output of `echo $TERM` inside `tmux`,
- output of `echo $TERM` outside `tmux`
- minimal version of your `.tmux.conf` to reproduce the issue

**Comment by gavinhoward** [comment]
Minimal version of `.tmux.conf` is an empty file. However, I also reproduced the issue with the following line in `.tmux.conf`:

```
set-option -g default-terminal "xterm-256color"
```

I also reproduced it with the following in `.tmux.conf`:

```
set-option -g default-terminal "screen-256color"
```

Output of `echo $TERM` outside `tmux`:

```
xterm-256color
```

Output of `echo $TERM` inside `tmux` with an empty `.tmux.conf`:

```
screen
```

Output of `echo $TERM` inside `tmux` with `set-option -g default-terminal "xterm-256color"` inside `.tmux.conf`:

```
xterm-256color
```

Output of `echo $TERM` inside `tmux` with `set-option -g default-terminal "screen-256color"` inside `.tmux.conf`:

```
screen-256color
```

Hopefully, this helps.

**Comment by chrisduerr** [comment]
@gavinhoward Do you use a tiling WM or something that always spawns the window at the same width? If this is just an off-by-one or something like that, it might just be reproducible at one specific width. Can you check that?

**Comment by gavinhoward** [comment]
@chrisduerr I am using a stock installation of Ubuntu with `gnome-shell 3.32.0`. I have `alacritty` set to always start maximized and to not draw a decoration bar. The width is exactly `1920` pixels because it's a `1920x1080` standard monitor.

However, I just tried to reproduce this when `alacritty` is windowed and with a decoration bar. It still does it.

**Comment by kchibisov** [comment]
@gavinhoward, I'm using `tmux` most of the time during work, and I've never seen this issue in `alacritty`. I've tried your options and everything was fine. I'm testing this with `12334**1234` in a `python` and also I've tested `make VERBOSE=1` on llvm project ( It will produce a lot of long oneliners), but steel can't repro.

Can you install `alacritty` `terminfo` (You can find instructions in `INSTALL.md`) and try with the following options ( They are from my config file)? You should also update `env` section in `alacritty.yml` to use `alacritty` as `TERM` in case you've set `xterm-256color` explicitly.

```
set -g default-terminal tmux-256color
set -g terminal-overrides ",alacritty:RGB"
```
I've never had issues with `xterm-256color` in `alacritty`, but I know some people which have problems with `xterm-256color` + Ubuntu + `alacritty` setup (Their `xterm-256color` was a bit different than my on `Arch`/`Gentoo` though), most of the time, their issues was resolved with setting `terminfo` to `alacritty`.

**Comment by gavinhoward** [comment]
@kchibisov I installed the `terminfo` and set everything up as you said, but I still had the problem.

Let's not worry about this right now; I still have `gnome-terminal` I can use, and this bug seems like it can't really be reproduced.

**Comment by gavinhoward** [comment]
After thinking about this some more, I decided to try it in `gnome-terminal`, which for some reason, has never run into this problem before. And when running `tmux` inside of it, it showed the same problem.

Therefore, I think this is a `tmux` problem, and I am closing this issue.

**Comment by brerx** [comment]
@gavinhoward 	Did you find an issue at `tmux` describing this? I got the same problem recently and googling did only lead me here...

**Comment by gavinhoward** [comment]
@brerx no I did not. The `tmux` people don't seem like they are actively working, so I had to switch back to `gnome-terminal` for the time being.

**Comment by brerx** [comment]
@gavinhoward 	FYI: uninstalling and reinstalling tmux (via brew) just fixed the issue for me...

**Comment by nixpulvis** [comment]
@gavinhoward I'm a bit confused. Your [comment from July 11th](https://github.com/jwilm/alacritty/issues/2632#issuecomment-510583100) makes it sound like this issue presents itself in both Alacritty and Gnome Terminal, however you mention now switching back to Gnome's terminal to avoid the issue.

Was this issue fixed for Gnome? What am I misunderstanding?

**Comment by gavinhoward** [comment]
@nixpulvis I apologize for not being clear. There was a workaround for `gnome-terminal`. I can't remember what it was, but I found one, so I stuck with `gnome-terminal`.

**Comment by nixpulvis** [comment]
@gavinhoward thanks for responding with the update. If you ever figure out what the workaround was, I might be curious to hear.

Glad you found a solution that works for you, even if I'm a bit sad it's not using Alacritty.

Cheers.

**Comment by brerx** [comment]
Maybe I can give you some hope: I tried it with tmux 3.0_rc4 yesterday and it seemed to be gone. So maybe just waiting will fix this thing.
