### ISSUE TITLE
Text selection/drag-n-drop on tmux not working on master (Linux/Wayland)

### ISSUE THREAD

**Issue by fsouza** [jwilm/alacritty#2635]
Using the current master, text selection doesn't work in tmux (clicking and scrolling still work, dragging doesn't). The issue seems to be caused by the latest commit (https://github.com/jwilm/alacritty/commit/84aca672964e29b5b4503b7da7bc34fc395f08ab), selection works fine if I check out https://github.com/jwilm/alacritty/commit/7331e89122c464e7b1a73b2e7b20399f832a5913 and rebuild.

### Which operating system does the issue occur on?

Linux (can confirm if the issue also manifest on Mac tomorrow)

### If on linux, are you using X11 or Wayland?

Wayland.

**Comment by kchibisov** [comment]
Can you test #2636?

**Comment by fsouza** [comment]
@kchibisov that works, thanks! :grin:
