### ISSUE TITLE
[OSX] How to set antialias : false

### ISSUE THREAD

**Issue by gabrielbidula** [jwilm/alacritty#2637]
Hi guys,

Does anyone knows how to set something like antialias:false or noantialias for alacritty.

follow a screenshot with macvim on the left using noantialias.

![Screenshot 2019-07-10 at 10 48 23](https://user-images.githubusercontent.com/1028654/60955153-8fd5ed00-a300-11e9-9fba-2adeddd9b425.png)

regards,

**Comment by chrisduerr** [comment]
Usually the recommendation is to rely on system font configuration to handle this kind of stuff. On Linux you could just setup a specific font to your needs, however I'm not sure how macOS handles this.

There has been an RFC lying around for a long while talking about a way to specify certain properties like aliasing for specific fonts (see #957), so this is kinda an extension of that, however it has been stale for a bit and I don't think there's any plan to implement it in the near future (however it is still planned, it will just take some time). I'd recommend following that for updates.

In the meantime, it might be worthwhile to play around with different fonts and weights a bit, sometimes just picking the correct font can help a lot. If you don't want any aliasing at all but you prefer pixel based fonts, maybe looking into a nice bitmap font could be a solution?
