### ISSUE TITLE
Running commands from Alfred

### ISSUE THREAD

**Issue by bmikaili** [jwilm/alacritty#2638]
Anyone have an Applescript to run commands from Alfred in Alacritty?

**Comment by chrisduerr** [comment]
What exactly are you trying to achieve? Do you want to execute arbitrary commands in Alacritty right at startup? You can do that with the `-e` option.

**Comment by bmikaili** [comment]
No, Alfred has a function where you can enter a command and that command will be run in the terminal. So it works as if I would enter a command in spotlight and it gets run in the terminal.

The applescript would look something like this:
```Applescript
on alfred_script(q)
	tell application "Alacritty"
  		activate
 	 	do script {q} in front window
	end tell
end alfred_script
```

**Comment by chrisduerr** [comment]
I don't think that's possible. Alacritty does not have applescript support and I see little reason to add it personally.

**Comment by deanishe** [comment]
You might be able to get it to work with the AppleScript `do shell script` command. Something like:

```applescript
on alfred_script(q)
    do shell script "/usr/local/bin/alacritty -e " & q
end alfred_script
```

**Comment by chrisduerr** [comment]
Yeah, that would be the recommended approach. If you want to try to run something inside of Alacritty from the get-go, that's exactly what the `-e` flag is made for. Of course you can also use the `shell` section of the config, but that would likely require a separate config file and the `--config-file` flag.

**Comment by deanishe** [comment]
> If you want to try to run something inside of Alacritty from the get-go, that's exactly what the -e flag is made for.

It works great for things like `top` or `ssh hostname`, where it's okay—desirable even—for the terminal window to close as soon as the program exits.

The way the Alfred plugin is supposed to behave, however, is much as if you'd opened a terminal and pasted the command into it, i.e. the session isn't supposed to exit when the command does. That doesn't work with `alacritty -e`: if I try to run `df -h`, for example, I never get to see the output.

**Comment by chrisduerr** [comment]
@deanishe There's nothing stopping you from executing a shell with a command without keeping a shell session around. That's perfectly possible with the `-e` command.

**Comment by deanishe** [comment]
Im not sure I follow. The shell is *not* supposed to exit.

**Comment by chrisduerr** [comment]
> The shell is not supposed to exit

I'm aware of that. Nothing is stopping you from keeping the shell around with the `-e` command though. All it does is execute a command, it's up to you what command that's going to be.

If the shell exits or not is completely unrelated to Alacritty, that's just up to the command you specify. If you don't want the shell to exit, just keep it around.

**Comment by deanishe** [comment]
> Nothing is stopping you from keeping the shell around with the -e command though.

Yes, there is: the fact that other plugins do *not* work that way.

We're trying to make a plugin that lets people *transparently* use Alacritty instead of Terminal.app. That's not possible if Alacritty can't be made to behave the same way *with the same command*.

Do you see the problem?

**Comment by chrisduerr** [comment]
> Do you see the problem?

I do not. Alacritty has no goal of ever working exactly the same way as Terminal.app or iTerm. As long as there's a reasonable way to get the same result, I don't see how that would be a problem. Especially if Alacritty's solution is cross-platform, while iTerm's/Terminal.app's only works on their specific target platform.

**Comment by deanishe** [comment]
> As long as there's a reasonable way to get the same result

There *isn't* a reasonable way to get the same result. That's the point.

It is not possible for every Alfred workflow to work around this by special-casing Alacritty and sending a different command because they do not know which terminal emulator is being used.

In any case, I think you can close the issue. I believe @bmikaili has given up on getting Alacritty to work and is using a different terminal emulator instead.

**Comment by nixpulvis** [comment]
The fundamental "issue" here is not unique to this problem. Alacritty is not the default Terminal on any system I'm aware of, and as a result is generally not the target of tools like Alfred. Alfred makes a choice to work in a very specific way, which works with some macOS applications. If Alacrity was itself a macOS app (not a more general cross platform emulator) then there may be a case for adding this level of macOS specific support.

As things stand, we don't generally add features just to fit into specific workflows. We support many workflows, and as noted in this thread the actual functionality is possible, but just might require some additional configuration. I think we all understand that this friction might turn some users away, but I don't see how this is avoidable in general.

As for AppleScript support as this issue is requesting, unless I'm misreading the Apple documentation this would require us to sign our application with Apple. If this is the case I'll refer to #1896 for our stance on that.

**Comment by deanishe** [comment]
I completely understand your reasoning. I wouldn't consider adding AppleScript support, either.

> as noted in this thread the actual functionality is possible, but just might require some additional configuration.

No, it really isn't. It's not possible to write an Alfred plugin for it that works the way it's supposed to. Alacritty simply does not support the features Alfred expects.

I'm not trying to assign any blame here. It's not Alacritty's fault for only having a broad cross-platform method for running commands, nor Alfred's for having an overly Mac-specific one. But they just ain't compatible, and only unreliable hackery could bring them together.

**Comment by nixpulvis** [comment]
@deanishe I must be misunderstanding the integration, sorry. It's a shame Alfred isn't more flexible.

**Comment by deanishe** [comment]
> It's a shame Alfred isn't more flexible.

Yes, it is.

I'm gonna try and get it to work the hacky way by simulating typing the command into a new Alacritty window. With Alacritty's consistently fast startup time, I think that might work reliably enough to be useable.

**Comment by philip1987** [comment]
Sending a terminal command from Alfred to Alacritty can be easily achieved with an Alfred workflow.
How I set up my workflow:

1. Launch Alacritty
2. Wait 0.2sec for Alacritty to launch
3. Copy the the {query} (what you type into Alfred after the keyword) to the system clip board and paste it to Alacritty
4. Wait 0.2sec for the pasting to be finished (Necessary only when in tmux which is a bit slower to paste)
5. Send an 'Enter' keystroke to Alacritty

I am sure this workflow could also be modified to launch a tmux session and paste in a new tmux window, or something like that.


[Alacritty.alfredworkflow.zip](https://github.com/alacritty/alacritty/files/5102790/Alacritty.alfredworkflow.zip)


![Screenshot 2020-08-20 at 13 56 49](https://user-images.githubusercontent.com/58528488/90767208-183d0480-e2ed-11ea-9f11-69de62c52462.jpg)

**Comment by deanishe** [comment]
> Sending a terminal command from Alfred to Alacritty can be easily achieved with an Alfred workflow.

Sure it can, but that doesn't solve the actual problem. Alfred has an AppleScript-based plugin API so its built-in Run Terminal Command works *transparently* with the user's preferred terminal emulator. Workflows don't have to concern themselves with it.

**Comment by philip1987** [comment]
@deanishe You are right, of course. I tried and failed to get it to work trough the built in "Run Terminal Command" function. My solution is at best an incomplete and hacked up way of getting around the limitations of alacritty. I am sure there is a better way to do it.
And I have to admit that I don't fully understand Alfred's API nor how Alacritty really works. For example what does working "transparently" entail?

Lastly out of curiosity what did you end up doing? Did you switch your terminal emulator? Or do you have another workaround for it?

**Comment by deanishe** [comment]
> For example what does working "transparently" entail?

You need to write a plugin script so Alfred's built-in terminal features automatically use Alacritty.

Here's a plugin script that seems to work.

In Alfred Preferences > Features > Terminal, choose Application = Custom and paste the script in the box.

```
on alacritty_win()
    set _running to (application "Alacritty" is running)
    tell application "Alacritty" to activate
    tell application "System Events"
        repeat while (name of first application process whose frontmost is true) is not "alacritty"
            delay 0.05
        end repeat

        set _alacritty to first application process whose frontmost is true
        -- If Alacritty was running, create a new window to run command
        if _running then
            tell _alacritty to set _target to (count windows) + 1
            keystroke "n" using {command down}
        else
            set _target to 1
        end if

        -- Wait for wanted window count
        tell _alacritty
            repeat while (count windows) < _target
                delay 0.05
            end repeat
        end tell
    end tell
end alacritty_win

on alfred_script(q)
    my alacritty_win()
    tell application "System Events"
        keystroke q
        key code 36
    end tell
end alfred_script
```

That should make Alfred's Terminal Command execute your script in a new Alacritty window. It's not ideal, as it simulates typing the command into a new window, which is slow for long commands. But that's probably the best you can do given the limitations.

> Lastly out of curiosity what did you end up doing?

I use iTerm. Always have.

**Comment by philip1987** [comment]
@deanishe That's a way better solution! It worked on my system. I think this is the best hack that can be done under the current limitations. Thank you for your extensive reply.

**Comment by bmikaili** [comment]
@deanishe Thanks a lot for sharing! That seems like the best we're going to get. I am still not sure I understand how it's better than @philip1987 's initial solution?

**Comment by deanishe** [comment]
> what if I ever need to run cmatrix in 8 tmux windows?!!

I keep Alacritty around in case I need the extreme performance. It's not as if it takes up much space.

**Comment by ayroblu** [comment]
Hey all, I didn't really follow this thread, but yeah running alfred + alacritty.

I took the code example from above and adjusted it:

```applescript
on alfred_script(q)
  do shell script "PATH=<copy-paste-my-path-here> /usr/local/bin/alacritty -e alfred-terminal.sh '" & q & "'  > /dev/null 2>&1 &"
end alfred_script
```

Where `alfred-terminal.sh` is a file in my path that contains:

```sh
set -x
zsh -c "${1:-echo "No command passed"}"
{ set +x; } 2>/dev/null
zsh
```

Reasons for the above:

1. PATH - Needs a path variable cause it's not supplied by alfred. Also mac zsh doesn't react well, it doesn't let me type etc. so having path point to the up to date version I installed via homebrew works well
2. `alacritty -e` takes command inputs without quotations? I don't really get this, it's not really like how shells normally handle it e.g. `zsh -c "print hello"`. So I made a small wrapper to do this and quoted the query
3. The `> /dev/null 2>&1 &` on the end is for alfred cause it seems like alfred runs these synchronously, i.e. waits, if I call alfred twice, it waits for the first one to finish then opens the second one after the first closes
4. `set -x` prints the commands, the `{ set +x; } 2> /dev/null` doesn't print disabling. `zsh -c "${1...}"` runs the command (with a default value), and the `zsh` at the end keeps the shell open for viewing, example:

![image](https://user-images.githubusercontent.com/4915682/139597793-39d18876-75d5-4bec-b226-f73fac665dde.png)

Anyways, this seems to work for me, hope it helps the next person!

**Comment by sequencer** [comment]
> Hey all, I didn't really follow this thread, but yeah running alfred + alacritty.
> 
> The big code sample wasn't working for me, so I took the small code example from above that was working and adjusted it:
> 
> ```applescript
> on alfred_script(q)
>   do shell script "PATH=<copy-paste-my-path-here> /usr/local/bin/alacritty -e alfred-terminal.sh '" & q & "'  > /dev/null 2>&1 &"
> end alfred_script
> ```
> 
> Where `alfred-terminal.sh` is a file in my path that contains:
> 
> ```shell
> set -x
> zsh -c "${1:-echo "No command passed"}; zsh"
> { set +x; } 2>/dev/null
> ```
> 
> Reasons for the above:
> 
> 1. PATH - Needs a path variable cause it's not supplied by alfred. Also mac zsh doesn't react well, it doesn't let me type etc. so having path point to the up to date version I installed via homebrew works well
> 2. `alacritty -e` takes command inputs without quotations? I don't really get this, it's not really like how shells normally handle it e.g. `zsh -c "print hello"`. So I made a small wrapper to do this and quoted the query
> 3. The `> /dev/null 2>&1 &` on the end is for alfred cause it seems like alfred runs these synchronously, i.e. waits, if I call alfred twice, it waits for the first one to finish then opens the second one after the first closes
> 4. `set -x` prints the commands, the `{ set +x; } 2> /dev/null` doesn't print disabling. `zsh -c "${1...}; zsh"` runs the command (with a default value), and the `zsh` at the end keeps the shell open for viewing, example:
> 
> ![image](https://user-images.githubusercontent.com/4915682/139597819-6d9e4cac-7cc2-4200-8390-f3cb825fab2b.png)
> 
> Anyways, this seems to work for me, hope it helps the next person!

Thanks for inspiration, I use `tmux`, I think this may help:
`alfred-terminal.sh`:
```
~/.nix-profile/bin/zsh -c " ~/.nix-profile/bin/tmux new-session -ds0 ; ~/.nix-profile/bin/tmux new-window ; ~/.nix-profile/bin/tmux send '$1' ENTER; ~/.nix-profile/bin/tmux a;" 
```
here is my AppleScript:
```
on alfred_script(q)
  tell application "System Events"
    set _running to get name of every process contains "alacritty"
  end tell
  if _running then
  	do shell script "~/.nix-profile/bin/tmux new-session -ds0 ; ~/.nix-profile/bin/tmux new-window ; ~/.nix-profile/bin/tmux send '" & q & "' ENTER;"
  else
    do shell script "~/.nix-profile/bin/alacritty -e ~/.local/bin/alfred-new-terminal.sh '" & q & "' > /dev/null 2>&1 &"
  end if
end alfred_script
```
I'm using alacritty from nix, so command may be different. 

The only question remains is I have no idea how to switch to the workspace where alacritty exist.
