### ISSUE TITLE
Double-click selects trailing tab

### ISSUE THREAD

**Issue by anowlcalledjosh** [jwilm/alacritty#2639]
Run this:

```
$ printf 'select\tme\n'
```

and double-click `select`. Observe that the cell after the word is also highlighted, and pressing ctrl-shift-C will copy the tab character.

Alacritty 0.3.3, Ubuntu 18.04, X11

**Comment by nixpulvis** [comment]
FWIW I've verified this on the latest master branch.

**Comment by Ben496** [comment]
Adding `\t` to `semantic_escape_chars` in alacritty.yml fixes this for me.

**Comment by chrisduerr** [comment]
Sounds like that might be a reasonable change. I don't see why it wouldn't be part of it already, since a normal whitespace is already in there. So likely just an oversight.
