### ISSUE TITLE
Issue while trying to add new ppa

### ISSUE THREAD

**Issue by renannprado** [jwilm/alacritty#2646]
Which operating system does the issue occur on?

Debian 10

While trying to add the new ppa to download alacritty, I got the following error:

```
sudo add-apt-repository ppa:mmstick76/alacritty
 Repository for Ubuntu that provides standalone Alacritty packages built as part of the CI/CD infrastructure for Pop!_OS. Sources currently originate from https://github.com/pop-os/alacritty
 More info: https://launchpad.net/~mmstick76/+archive/ubuntu/alacritty
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpwi5san7s/pubring.gpg' created
gpg: /tmp/tmpwi5san7s/trustdb.gpg: trustdb created
gpg: key 8AC9B4BBBAB4900B: public key "Launchpad PPA for Michael Aaron Murphy" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
```

**Comment by chrisduerr** [comment]
You're running Debian, which does not provide the necessary keys to install packaged signed for Ubuntu. You'll either have to add the key from Ubuntu's keyserver, or build from source.

This is not an Alacritty issue though, but solely lies within your system and trying to install Ubuntu PPAs on Debian. If you need some help, I'll try to answer as best I can (I don't personally use Ubuntu), but alternative channels might be able to help you quicker (like some of the linux IRC channels).

**Comment by renannprado** [comment]
Ah, I see. Understood!

I'll figure it out :)

**Comment by estysdesu** [comment]
```
sudo add-apt-repository "deb http://ppa.launchpad.net/mmstick76/alacritty/ubuntu bionic main"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 5B7FC40A404FAD98548806028AC9B4BBBAB4900B
sudo apt update
sudo apt install alacritty
```

Tested w/ Debian 10 Buster Stable
