### ISSUE TITLE
Pressing tab after command makes it impossible to delete first 3 letters (fish shell).

### ISSUE THREAD

**Issue by micouy** [jwilm/alacritty#2654]
After typing a command and pressing tab for completions I am unable to delete the first 3 letters of this command. I can't delete those letters with Ctrl + U either. It also makes Alacritty ignore them. Even if I press enter without deleting those letters, the command won't execute. Example:

```
$ ls
```

Then I press tab and some completions show up. Sometimes pressing tab first time places four spaces instead of showing completions.

```
$ ls     some-dir
```

Then I delete everything I can and `ls ` is left. After I press enter a new line happens.

```
$ ls 
$
```

I'm using fish shell on MacOS 10.14.1.

**Comment by kchibisov** [comment]
@micouy Can you repro this with `bash`? What is the output of `echo $TERM` and `alacritty --version`?

**Comment by chrisduerr** [comment]
Also please make sure you've tested the default config with `alacritty --config-file /dev/null` to make sure this is not an issue with the `tabspaces` you've set.

**Comment by micouy** [comment]
Can't reproduce it with bash because it only displays completions below the current line. Fish shell puts the first option in the current line. Running it with `--config-file /dev/null` seems to solve the problem but I've just downloaded `alacritty.yml` shipped with `0.3.3` release and it happened again.

`echo $TERM` returns `xterm-256color`.

`alacritty --version` returns `alacritty 0.3.3 (cc3e4d3)`.

`fish --version` returns `fish, version 3.0.0`.

**Comment by chrisduerr** [comment]
If `--config-file /dev/null` fixes it, it's likely an issue with your config. If you download a new config file, please make sure it's getting loaded correctly. I'd recommend just deleting the existing file and letting Alacritty generate one itself, that way it's guaranteed to be the correct config file for the Alacritty version.

For best possible compatability, I'd also recommend running the `alacritty` terminfo instead of xterm-256color, that might fix some issues.

**Comment by kchibisov** [comment]
>  If you download a new config file, please make sure it's getting loaded correctly.

@micouy You can launch `alacritty -v` to find out which config is being loaded.

You can see line similar to this one `INFO] Configuration loaded from "/home/kchibisov/.config/alacritty/alacritty.yml"`

**Comment by micouy** [comment]
It still happens after automatic generation. I checked `alacritty -v` and it loaded it from the correct location.

It works after running `env TERM=terminfo alacritty`. But I usually run it like a normal MacOS app, not from the terminal. Can I also make it work like that?

**Comment by kchibisov** [comment]
You need to add `TERM: alacritty` in `env` section of your config.

https://github.com/jwilm/alacritty/blob/76dd84bef87f77c67bf5c23ee627163e93786b5d/alacritty.yml#L13

**Comment by chrisduerr** [comment]
I do not recommend setting the `TERM` to `alacritty` in the `env` section manually. If it is not loaded with the default config, that means you do not have the terminfo of Alacritty installed. Manually setting it to Alacritty in this case will break things. Instead of setting the `TERM` to `alacritty` yourself, you shouldn't set it to anything and install the terminfo file.

**Comment by kchibisov** [comment]
@chrisduerr do you have any ideas why `--config-file /dev/null` works and generated one doesn't? They should be identical as far as I remember.

**Comment by micouy** [comment]
OK, I think I've installed the terminfo file (I'm not sure if I did it correctly because I'm not familiar with terminfo files) and it works so far.

Thank you :). Closing.

**Comment by micouy** [comment]
Reopening. Alacritty works just fine if I run it like this:
```
open -a /Applications/Alacritty.app
```
or this
```
/Applications/Alacritty.app/Contents/MacOS/alacritty
```
but I didn't realize that the error still occurs if I open it like a normal MacOS app (from Spotlight Search, from Dock or from Finder). Sorry for that. In all cases the config is loaded from the same location. In all cases `echo $TERM` returns `alacritty` (IDK if that's the proper way of checking it so correct me if I'm wrong).

**Comment by kchibisov** [comment]
@micouy Could you provide your outputs of locale when you're starting from `/Applications/Alacritty.app/Contents/MacOS/alacritty` and from "sportlight launch"?

**Comment by micouy** [comment]
Launched like a normal app (faulty):
```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Launched from a terminal:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by kchibisov** [comment]
The first locale is odd, as you can see, don't change these variables for now, we'll come to them latter if you'll have problems.

Try launching your shell as login, since it's macOs.
```
shell:
  program: /usr/local/bin/fish
  args:
    - --login
```

**Comment by kchibisov** [comment]
duplicate #2566 

> @chrisduerr do you have any ideas why --config-file /dev/null works and generated one doesn't? They should be identical as far as I remember.

>  but I didn't realize that the error still occurs if I open it like a normal MacOS app
 
That explains the problem.

**Comment by micouy** [comment]
Changed the config and lauched it again. Nothing happened. `locale` returns the same output. Also there's a difference in displaying Unicode (screenshots from Kakoune).

![obraz](https://user-images.githubusercontent.com/20628866/61669544-b3297080-ace0-11e9-8146-797811c91cb4.png)
![obraz](https://user-images.githubusercontent.com/20628866/61669549-ba507e80-ace0-11e9-8b32-76bda9b881de.png)

**Comment by kchibisov** [comment]
> Also there's a difference in displaying Unicode (screenshots from Kakoune).

It's expected, since your locale doesn't support unicode stuff. As a work around you can add 
`LC_CTYPE: "UTF-8"` to env section in `alacritty.yml`. The second locale seems a little bit odd to me too, so probably some locale issue on your system is already presented, I don't remember how macOs handles it's locale stuff though.

**Comment by chrisduerr** [comment]
Yeah this is a locale issue and the related issues should help out. Setting your locale properly will resolve this. Making sure to always launch a login shell is a good way of making sure your system has a chance to set the locale properly.
