### ISSUE TITLE
How changing the font?

### ISSUE THREAD

**Issue by zwykl3** [jwilm/alacritty#2658]
I have in my system 

"InconsolataGo Nerf Font Mono"
where put this line? Any example how changing font?

**Comment by kchibisov** [comment]
Right here https://github.com/jwilm/alacritty/blob/76dd84bef87f77c67bf5c23ee627163e93786b5d/alacritty.yml#L121

**Comment by butla** [comment]
I think you can close this issue, @zwykl3, since the answer above is OK.

**Comment by chrisduerr** [comment]
If you have any more questions, please let us know @zwykl3 and I can re-open this issue. But @kchibisov's solution should do the job.

**Comment by goyalyashpal** [comment]
oh, found it. glad i looked at siblings `(1)` of the man page `(5)` linked in [this reddit post] lol...

https://github.com/alacritty/alacritty/blob/d4f2f8577f763df059653dfab733dfe6ddc06913/extra/man/alacritty.1.scd?plain=1#L60-L71

[this reddit post]: https://www.reddit.com/r/linuxquestions/comments/ve9gd8/comment/k7u11kz/ "For who looking for the TOML config ..."

<strike>
hi! sorry for necro-bumping, but i really didn't want to open an issue anew.
where does the config file for alacritty go??
i looked at https://alacritty.org/config-alacritty.html but couldn't find any mention of location of env-variable used for config
</strike>
