### ISSUE TITLE
Add the ability to create custom desktop entries

### ISSUE THREAD

**Issue by dtcyganok** [jwilm/alacritty#2663]
When I create custom desktop entry nvim.desktop with the option --class, the window has the same icon as alacritty.

**Comment by kchibisov** [comment]
Whats your wm and ds? You can create custom desktop entries, however its up to your wm how to get app icon. If it uses _NET_WM_ICON ( If this is on `X11`) the icon will always be an `alacritty`s one, since we're building `alacritty` with it. In case it takes icons from `/usr/share/pixmaps`, you can set your own icon here (I've tested this in `rofi`, so its possible).

**Comment by kchibisov** [comment]
If I understood you correctly (from #2662 ) you're on wayland, so net_wm_icon shouldn't work at all. In this case, would you mind sharing your desktop file?

**Comment by dtcyganok** [comment]
My desktop entry `nvim.desktop`
```text
[Desktop Entry]
Type=Application
Name=Neovim
GenericName=Text Editor
Comment=Edit text files
Icon=neovim-circle
Terminal=false
Exec=alacritty --class=nvim -e nvim %F
StartupNotify=false
MimeType=text/plain;
Categories=Utility;TextEditor;
```

Icon saved in `~/.local/share/icons/` directory.

**Comment by kchibisov** [comment]
So, I'm assuming you have nvim.png or something like this in `~/.local/share/icons`?

**Comment by kchibisov** [comment]
So I guess you need `--class=neovim-circle`

**Comment by dtcyganok** [comment]
With LC_ALL=en_GB.UTF-8 it works as expected
```text
Exec=env LC_ALL=en_GB.UTF-8 alacritty --class=nvim -e nvim %F
```

**Comment by chrisduerr** [comment]
Likely a locale issue then. Make sure your LC_ALL, LANG or LC_CTYPE aren't set to an empty string which is an invalid configuration that can cause some issues. If you do not wish to set them, please just unset those entirely. If that solves it for you, please close this issue accordingly.
