### ISSUE TITLE
Mouse cursor flickers between default and Hand shape when hovering URL

### ISSUE THREAD

**Issue by jjsullivan5196** [jwilm/alacritty#2665]
## System
Archlinux kernel 4.19
rust 1.32.0
i3 on x11
alacritty master 76dd84b

## Behavior
When hovering across a highlighted URL, the cursor will flip back and forth between the default cursor for the context and the `Hand` shapes.

## Expectation
Mouse cursor shape should always be `Hand` when on top of an URL.

## Reproduce
Try `echo "https://google.com"` or similar command/input to get an URL
Move mouse cursor across the output, cursor should change shape as described

## Extra
This issue was discovered while trying to make an enhancement to text selection, and is introduced in 84aca67. The behavior described is first seen in a99547c.

More context in this pull #2661

**Comment by kchibisov** [comment]
Could you test #2666?
