### ISSUE TITLE
[ERROR] Problem with config: invalid type: map, expected a string; using default value

### ISSUE THREAD

**Issue by pengux** [jwilm/alacritty#2667]
Which operating system does the issue occur on?
macOS Mojave (version 10.14.5)

Using version 0.3.3 of Alacritty installed through `brew cask install alacritty`, and the default configuration in ~/.alacritty.yml. When starting Alacritty, it shows the error:

`[ERROR] Problem with config: invalid type: map, expected a string; using default value`

is there a way to enable verbose output to show which line in the configuration it complains about?

**Comment by chrisduerr** [comment]
If you post your config, I can take a look. This is likely pretty simple to spot, it might be a field without a value for example.

**Comment by pengux** [comment]
@chrisduerr I used the one provided in this repo, https://github.com/jwilm/alacritty/blob/master/alacritty.yml

**Comment by kchibisov** [comment]
@pengux You've taken the config for the current master branch, which was updated recently. Your `alacritty` version is `0.3.3` so its expected, that it fails with the new config. `alacritty` can generate actual config in case it can't find any of them in default config locations, so you can remove your config and alacritty will generate default one in `~/.config/alacritty/alacritty.yml` or you can grab one for `0.3.3` version by checking out the `tag v0.3.3` on github/your cloned repo.

**Comment by pengux** [comment]
@kchibisov Thanks! That did the trick! `rm ~/.alacritty.yml`
