### ISSUE TITLE
Focus/blur events are not handled correctly in presence of dmenu_run

### ISSUE THREAD

**Issue by farnoy** [jwilm/alacritty#2669]
Linux x11, alacritty 0.3.3

I don't know what it's going on underneath, but when I use `dmenu_run` with an alacritty window open, it affects where keyboard events are send to.

I use i3 with `focus_follows_mouse no`, and it makes window focus work  independently of mouse movements and always sends input to the active window. But with alacritty open and dmenu launched once, the input is somehow re-routed to where me mouse is currently pointed at. I'm not sure how alacritty can affect this, it doesn't mess with which window is focused, that seems to behave the same as with other terminals, only input is affected.

I don't know if I did a good job describing it, it's a very strange effect

**Comment by kchibisov** [comment]
if you launch `dmenu`, type some text in it and press enter, it sometimes inserts to alacritty, am I correct here?

**Comment by farnoy** [comment]
No, that input that I send to dmenu never reaches alacritty, it only happens after dmenu is closed (after launching something or not, does not matter).

I tried gnome-terminal just now and it behaves the same as alacritty. I don't remember it being this strange, I'll try to record alacritty and termite.

**Comment by farnoy** [comment]
Ok, this must be something about i3/dmenu, all terminals and in fact other applications too behave the same way
