### ISSUE TITLE
Adding support for alacritty for macos 10.15

### ISSUE THREAD

**Issue by anhdle14** [jwilm/alacritty#2671]
> Which operating system does the issue occur on? 

Mac OS 10.15 Beta 4

Here is a quick look on `Console.app`

```
Failed to copy signing info for 2140, responsible for file:///Applications/Alacritty.app/Contents/MacOS/alacritty: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

---
Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Alacritty.app/Contents/, NSFilePath=/Applications/Alacritty.app/Contents/PlugIns, NSUnderlyingError=0x7fe11ac23020 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by chrisduerr** [comment]
I don't think there's necessarily something wrong with Alacritty here, I'd suspect that you can still build from source just fine, right? Likely just a compatibility issue with the distributed binary made by CI, which is likely not running 10.15 yet.

**Comment by anhdle14** [comment]
I have recently downgraded to 10.14, so i haven't attempted to build on 10.15. Will try it soon.
I will re-open this if something come up, will close it for now. Thank you!
