### ISSUE TITLE
renderning  error

### ISSUE THREAD

**Issue by Ihindng** [jwilm/alacritty#2673]
Which operating system does the issue occur on?
OS: macOS HighSierra 10.13.6
config: [alacritty.yml](https://gist.github.com/Ihindng/89ace27d325e1d98ff4781bdb1514cba)

![error img](https://imgur.com/download/DWTBZQV)

**Comment by chrisduerr** [comment]
Looks like a duplicate of https://github.com/jwilm/alacritty/issues/1631.
