### ISSUE TITLE
Cargo-deb installation conflicts with ncurses-term package

### ISSUE THREAD

**Issue by rlue** [jwilm/alacritty#2685]
### Environment

Debian testing (11 / bullseye) with X11.

### Issue

Apparently the latest version of `ncurses-term` (6.1+20190713-1) packages its own version of alacritty's terminfo, which conflicts with the same file that alacritty tries to install:

```
$ cargo deb --install --manifest-path alacritty/Cargo.toml
...
Preparing to unpack .../alacritty_0.3.3_amd64.deb ...
Unpacking alacritty (0.3.3) ...
dpkg: error processing archive /home/rlue/tmp/alacritty/target/debian/alacritty_0.3.3_amd64.deb (--install):
 trying to overwrite '/usr/share/terminfo/a/alacritty', which is also in package ncurses-term 6.1+20190713-1
Processing triggers for mime-support (3.62) ...
Errors were encountered while processing:
 /home/rlue/tmp/alacritty/target/debian/alacritty_0.3.3_amd64.deb
cargo-deb: installation failed, because dpkg -i returned error
```

Now that I think about it, perhaps this should be considered a bug on ncurses-term's part... Or perhaps ncurses-term could be listed as a dependency of alacritty's generated .deb package (provided the contents of the terminfo file are never expected to change)? 

At the very least, I wanted to submit this issue so there's a record of what to do when someone else runs into the same problem.

**Comment by rlue** [comment]
FWIW I've [filed a corresponding issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933386) on the `ncurses-term` Debian package.

**Comment by chrisduerr** [comment]
First of all, thanks for reporting this issue. Alacritty's terminfo file has been added to ncurses relatively recently, which is why it was provided with Alacritty until now. Since ncurses did not make an actual release yet, it was not clearly transparent at which point Debian and Ubuntu would update to it.

> FWIW I've filed a corresponding issue on the ncurses-term Debian package.

Please note for future reference, that it's probably a better idea to report things in one place first before creating multiple issues. This is not something where Debian can do much, so it just generates a bit of unnecessary noise and work upstream. Checking here first should be a good way to keep that down, I can usually respond to issues within a day.

> Now that I think about it, perhaps this should be considered a bug on ncurses-term's part... Or perhaps ncurses-term could be listed as a dependency of alacritty's generated .deb package (provided the contents of the terminfo file are never expected to change)?

This is not a bug of ncurses-term. Alacritty's .deb is not an official Debian package, but only built by Alacritty's CI. So there's no way for Debian maintainers to know anything about it. So this is something where Alacritty's .deb file needs to be adjusted.

Adding ncurses-term as a dependency without packaging the terminfo files in the .deb file is likely a good idea.

**Comment by zwenna** [comment]
> First of all, thanks for reporting this issue. Alacritty's terminfo file has been added to ncurses relatively recently, which is why it was provided with Alacritty until now. Since ncurses did not make an actual release yet, it was not clearly transparent at which point Debian and Ubuntu would update to it.
> 
> Please note for future reference, that it's probably a better idea to report things in one place first before creating multiple issues. This is not something where Debian can do much, so it just generates a bit of unnecessary noise and work upstream. Checking here first should be a good way to keep that down, I can usually respond to issues within a day.
> 
> This is not a bug of ncurses-term. Alacritty's .deb is not an official Debian package, but only built by Alacritty's CI. So there's no way for Debian maintainers to know anything about it. So this is something where Alacritty's .deb file needs to be adjusted.

As maintainer of ncurses in Debian, I agree.

> Adding ncurses-term as a dependency without packaging the terminfo files in the .deb file is likely a good idea.

The alacritty terminfo entries have only been added a few days ago in Debian's and Ubuntu's development versions, it will take a while until they reach the wide public in stable releases (Ubuntu 20.04 and Debian 11). So maybe Alacritty's .deb could continue to include these files, but move them under /lib/terminfo where they do not clash with ncurses-term?

BTW, the terminfo installation in Alacritty's .deb is broken: it includes the **source** file as /usr/share/terminfo/a/alacritty rather than feeding it to tic and installing the compiled files. As a result, TERM is set to xterm-256color.

**Comment by chrisduerr** [comment]
> BTW, the terminfo installation in Alacritty's .deb is broken: it includes the source file as /usr/share/terminfo/a/alacritty rather than feeding it to tic and installing the compiled files. As a result, TERM is set to xterm-256color.

I thought the same thing looking at the configuration right now, though I don't have a Debian system to confirm it. I'm surprised this has slipped through, since it has been there for a long time, though at least now we know.

> The alacritty terminfo entries have only been added a few days ago in Debian's and Ubuntu's development versions, it will take a while until they reach the wide public in stable releases (Ubuntu 20.04 and Debian 11). So maybe Alacritty's .deb could continue to include these files, but move them under /lib/terminfo where they do not clash with ncurses-term?

Especially since Debian 10 has been released just recently and even 20.04 is still a bit of time away, this is a very good point. Though as mentioned previously I'd have to setup a Debian VM to test what the best solution would be. On Arch /lib/terminfo is symlinked to /usr/share/terminfo, so it wouldn't work, however if this is not the case on Debian and it's still loaded, that would be a great option.

I think we can just execute `tic` in the `extra/linux/debian/positinst` script, however we'd still have to first copy it somewhere.

**Comment by zwenna** [comment]
> > The alacritty terminfo entries have only been added a few days ago in Debian's and Ubuntu's development versions, it will take a while until they reach the wide public in stable releases (Ubuntu 20.04 and Debian 11). So maybe Alacritty's .deb could continue to include these files, but move them under /lib/terminfo where they do not clash with ncurses-term?
> 
> Especially since Debian 10 has been released just recently and even 20.04 is still a bit of time away, this is a very good point. Though as mentioned previously I'd have to setup a Debian VM to test what the best solution would be. On Arch /lib/terminfo is symlinked to /usr/share/terminfo, so it wouldn't work, however if this is not the case on Debian and it's still loaded, that would be a great option.

On Debian and derivatives, /lib/terminfo will most likely never be a symlink to /usr/share/terminfo (unless the local admin has made one, and then they keep the pieces). 

> I think we can just execute `tic` in the `extra/linux/debian/positinst` script, however we'd still have to first copy it somewhere.

I had thought of running tic at package build time, but that does not seem possible with cargo-deb.  So you would probably have to include alacritty.info in the .deb, say in /usr/share/alacritty, and then use maintainerscripts like these (untested):

postinst:
```
#!/bin/sh
set -e
tic -x -o /lib/terminfo /usr/share/alacritty/alacritty.info
```
prerm:
```
#!/bin/sh
set -e
rm -f /lib/terminfo/alacritty /lib/terminfo/alacritty+common /lib/terminfo/alacritty-direct
```

**Comment by chrisduerr** [comment]
> I had thought of running tic at package build time, but that does not seem possible with cargo-deb. So you would probably have to include alacritty.info in the .deb, say in /usr/share/alacritty, and then use maintainerscripts like these (untested)

This was my thought as well. Without having the ability to generate files in cargo-deb during the installation based on files in the repository, that seems to be the best choice.

**Comment by zwenna** [comment]
I have taken the time to write a patch that should do the trick. However I will not send a pull request, since I have no way to test it.

**Comment by laurentS** [comment]
@zwenna I just built from your commit on debian sid (unstable), and it seems to have fixed the bug. `apt upgrade` was failing on `ncurses-term (6.1+20190713-1)` but it's now happily installed side-by-side with your version of alacritty.
Nice!

**Comment by chrisduerr** [comment]
@laurentS Can you check if the Alacritty terminfo is still provided in lib? And optimally backing up the ncurses-term terminfo, removing the Alacritty from it and then checking if `TERM=alacritty` still works?

**Comment by laurentS** [comment]
@chrisduerr here's what I found on my system (clean install 2 weeks ago, I haven't messed too much with it yet, except for installing alacritty.deb :)
```bash
$ ll /lib/terminfo/
total 56
drwxr-xr-x 2 root root 4096 Jul 23 16:56 a
drwxr-xr-x 2 root root 4096 Jul 23 16:56 c
drwxr-xr-x 2 root root 4096 Jul 23 16:56 d
drwxr-xr-x 2 root root 4096 Jul 23 16:56 E
drwxr-xr-x 2 root root 4096 Jul 23 16:56 h
drwxr-xr-x 2 root root 4096 Jul 23 16:56 l
drwxr-xr-x 2 root root 4096 Jul 23 16:56 m
drwxr-xr-x 2 root root 4096 Jul 23 16:56 p
drwxr-xr-x 2 root root 4096 Jul 23 16:56 r
drwxr-xr-x 2 root root 4096 Jul 23 16:56 s
drwxr-xr-x 2 root root 4096 Jul 23 16:56 t
drwxr-xr-x 2 root root 4096 Jul 23 16:56 v
drwxr-xr-x 2 root root 4096 Jul 23 16:56 w
drwxr-xr-x 2 root root 4096 Jul 23 16:56 x
```
`/lib/terminfo/a/` doesn't contain any alacritty file, nor do the other folders listed above. Also `/lib` is a symlink to `/usr/lib` in case it's useful.

About `TERM=alacritty`, it works after installing the `.deb` (assuming you mean `$ env | grep TERM`, if not, please let me know what to check exactly). And it still seems to work even after I remove the terminfo file from `/usr/share/terminfo/a/` so I suspect I might be doing something wrong.

@zwenna on my system, `tic` compiles the terminfo files to `/lib/terminfo/a/alacritty*` when I run `sudo tic -x -o /lib/terminfo /usr/share/alacritty/alacritty.info` so the `prerm` script probably won't remove them properly.

Hope the above helps. Please let me know if I can test anything else.

**Comment by rlue** [comment]
Chiming in with input for Debian testing.

> I have taken the time to write a patch that should do the trick. However I will not send a pull request, since I have no way to test it.

Confirming that it works. Upgraded alacritty to @zwenna's `terminfo` branch, then upgraded `ncurses-term` with no problems.

> Can you check if the Alacritty terminfo is still provided in lib?

Confirming @laurentS' findings on Debian testing:

* `/lib` is symlinked to `/usr/lib`
* no alacritty terminfo file can be found anywhere under `/lib`.

(FWIW `/lib` is **not** symlinked to `/usr/lib` on Raspbian.)

> ...checking if `TERM=alacritty` still works?

* works with the terminfo file provided by `ncurses-term`
* doesn't work with the alacritty terminfo file removed.
* oddly, did _not_ work with the terminfo file provided by the current version of alacritty.

  Before upgrading `ncurses-term`, I would get the following in an alacritty window:

  ```
  $ echo $TERM
  xterm-256color
  $ file /usr/share/terminfo/a/alacritty
  /usr/share/terminfo/a/alacritty: ASCII text
  $ export TERM=alacritty
  $ infocmp
  infocmp: couldn't open terminfo file /usr/share/terminfo/a/alacritty
  ```

  I'm beginning to get the sense I should have compiled the terminfo file with `tic`.

FWIW I'd been inadvertently using alacritty with `TERM=xterm-256color` this whole time, and had no idea anything was wrong.

**Comment by zwenna** [comment]
> `/lib/terminfo/a/` doesn't contain any alacritty file, nor do the other folders listed above. Also `/lib` is a symlink to `/usr/lib` in case it's useful.

Should not matter if /lib is a symlink to /usr/lib or a directory.

> About `TERM=alacritty`, it works after installing the `.deb` (assuming you mean `$ env | grep TERM`, if not, please let me know what to check exactly). And it still seems to work even after I remove the terminfo file from `/usr/share/terminfo/a/` so I suspect I might be doing something wrong.

The .deb installs the terminfo files under /lib/terminfo, so removing files from /usr/share/terminfo has no effect, that is to be expected.

> @zwenna on my system, `tic` compiles the terminfo files to `/lib/terminfo/a/alacritty*` when I run `sudo tic -x -o /lib/terminfo /usr/share/alacritty/alacritty.info` so the `prerm` script probably won't remove them properly.

Thanks, fixed that and force-pushed my branch.  There should be the following files in /lib/terminfo/a:

After installing the .deb:

alacritty
alacritty+common
alacritty-direct
ansi

Before installing and after removing it:

ansi

**Comment by laurentS** [comment]
I must be doing something wrong, because it looks to me like the `prerm` and `postinst` scripts are not actually packaged in the `.deb` archive. Running `dpkg -e target/debian/alacritty_0.3.3_amd64.deb` just gives me 2 files: `DEBIAN/control` and `DEBIAN/md5sums` but not the scripts. As you can guess, the terminfo file is not installed.

Just to be sure I did the right thing, I removed the entire `target` folder, then
```bash
$ cargo deb --manifest-path alacritty/Cargo.toml
$ sudo dpkg -i target/debian/alacritty_0.3.3_amd64.deb
```
I've triple checked that I'm on the right commit `971191825e`. What did I miss?

**Comment by zwenna** [comment]
> I must be doing something wrong, because it looks to me like the `prerm` and `postinst` scripts are not actually packaged in the `.deb` archive. Running `dpkg -e target/debian/alacritty_0.3.3_amd64.deb` just gives me 2 files: `DEBIAN/control` and `DEBIAN/md5sums` but not the scripts. As you can guess, the terminfo file is not installed.

Huh, indeed.  That the maintainer scripts are completely missing is not new, though.

> I've triple checked that I'm on the right commit `971191825e`. What did I miss?

Try this command:

`sed -i 's/maintainer-scripts/maintainer_scripts/' alacritty/Cargo.toml`

See https://github.com/mmstick/cargo-deb/issues/104.

**Comment by laurentS** [comment]
I had actually tried this after looking into the code for cargo-deb. They use some lib to transform `-` into `_`, so when using `maintainer_script` you get an error from cargo-deb:
```
cargo-deb: unable to parse Cargo.toml
  because: unknown field `maintainer_scripts`, expected one of `name`, `maintainer`, `copyright`, `license-file`, `changelog`, `depends`, `conflicts`, `breaks`, `replaces`, `provides`, `extended-description`, `section`, `priority`, `revisi
on`, `conf-files`, `assets`, `maintainer-scripts`, `features`, `default-features`, `separate-debug-symbols`, `variants` for key `package.metadata.deb`
```

**Comment by zwenna** [comment]
Yes, and missing maintainer scripts have already reported in https://github.com/jwilm/alacritty/issues/2554.

I guess I have to give up at this point and let you sort out the issue.

**Comment by laurentS** [comment]
I had missed that other issue. I just tested by removing the `../` as suggested there in the `maintainer-scripts` line, and it does the job, the package then includes the scripts, and the terminfo files land in `/lib/terminfo/a/` as expected.

I've reported the [inconsistency](https://github.com/mmstick/cargo-deb/issues/105) in `cargo-deb`'s tracker.

**Comment by jbsolomon** [comment]
Sorry if someone has made this obvious already, but is there an established workaround for users at this time?

**Comment by chrisduerr** [comment]
Building from source should work without any issues and I'd assume the PPA will also work. Those are usually much more reliable than the .deb anyways.

**Comment by op** [comment]
This is not an established workaround but a dirty hack;
```
sudo mv /usr/share/terminfo/a/alacritty /lib/terminfo/a/
sudo dpkg --force-overwrite -i /var/cache/apt/archives/ncurses-term_6.1+20190803-1_all.deb
```

**Comment by MagixInTheAir** [comment]
I have this problem today using PPA release. Reopen ?

**Comment by chrisduerr** [comment]
This is about cargo-deb, not about the Ubuntu PPA.

**Comment by GopherJ** [comment]
I think this issue still exits, it shouldn't be closed?

**Comment by chrisduerr** [comment]
It does not. The `.deb` file Alacritty ships does not include the ncurses depedency anymore.

If you're having trouble with any other way of installing Alacritty, that is not related to this issue.
