### ISSUE TITLE
Add escape bindings for multiple combined modifiers

### ISSUE THREAD

**Issue by nifker** [jwilm/alacritty#2688]
Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
AFAIK both

It seems like [Ctrl/Alt]+Shift+Arrowkey doesnt get catched by terminal applications when using alacritty.

See this issue for reference: https://github.com/zyedidia/micro/issues/1335

**Comment by kchibisov** [comment]
Would you mind trying bindings suggested [here](https://github.com/jwilm/alacritty/issues/360#issuecomment-516360460)?

**Comment by chrisduerr** [comment]
Based on some quick testing, it looks like Alacritty does not send the correct escapes when multiple modifiers are held down. We have bindings for shift, alt **or** control, but not combinations of those.

In theory, this is all the combinations we should support:
```
                    Code     Modifiers
                  ---------+---------------------------
                     2     | Shift
                     3     | Alt
                     4     | Shift + Alt
                     5     | Control
                     6     | Shift + Control
                     7     | Alt + Control
                     8     | Shift + Alt + Control
                     9     | Meta
                     10    | Meta + Shift
                     11    | Meta + Alt
                     12    | Meta + Alt + Shift
                     13    | Meta + Ctrl
                     14    | Meta + Ctrl + Shift
                     15    | Meta + Ctrl + Alt
                     16    | Meta + Ctrl + Alt + Shift
                  ---------+---------------------------
```

This is not only the case for the arrow keys, but also for everything else which uses that mechanism like PageUp/PageDown and function keys.

Implementing this is trivial, it's just a matter of adding additional key bindings, however I question whether we do want to have all of that in your configuration file. I feel like the key bindings are at a point, where we would benefit from not actually having all of them listed in the default config.

**Comment by nifker** [comment]
@kchibisov seems to be working for alt Shift+Alt+Arrowkey - just missing the sequences for Shift+Ctrl+Arrowkey

**Comment by kchibisov** [comment]
@nifker try this one
```yml
- { key: Up,       mods: Control|Shift,  chars: "\x1b[1;6A"                }
- { key: Down,     mods: Control|Shift,  chars: "\x1b[1;6B"                }
- { key: Left,     mods: Control|Shift,  chars: "\x1b[1;6D"                }
- { key: Right,    mods: Control|Shift,  chars: "\x1b[1;6C"                }
```

**Comment by nifker** [comment]
That is working. Thanks. Shall I close this one now?

**Comment by kchibisov** [comment]
> That is working. Thanks. Shall I close this one now?

No. It'll be closed when all shortcuts that @chrisduerr mentioned above will be added.

**Comment by dnkl** [comment]
Not sure if you already support this, but you also might want to consider adding escape sequences for "other" keys as well (things like semicolon etc). See xterm's **modifyOtherKeys** setting: https://invisible-island.net/xterm/manpage/xterm.html.

**Comment by andradei** [comment]
@nifker Were you running tmux? On some CLI programs only when it is running. Seems to be related with the fact that tmux changes `TERM` to `screen-256color`, when it was `xterm-256color`.

**Comment by chrisduerr** [comment]
> Not sure if you already support this, but you also might want to consider adding escape sequences for "other" keys as well (things like semicolon etc). See xterm's modifyOtherKeys setting: https://invisible-island.net/xterm/manpage/xterm.html.

I think this is disabled in ncurses by default, right? In which case we should do the same in Alacritty (imho) and not provide any of these bindings. If people want these features, they can always add their own bindings.

**Comment by dnkl** [comment]
They are.

But they can also be enabled (and/or disabled) programmatically with "CSI > Ps ; Ps m" . Emacs uses this to enable more key bindings.

**Comment by dnkl** [comment]
> ncurses

Xterm. This has nothing to do with ncurses.

**Comment by chrisduerr** [comment]
> Xterm. This has nothing to do with ncurses.

Yeah sorry, this was a typo.

> But they can also be enabled (and/or disabled) programmatically with "CSI > Ps ; Ps m" . Emacs uses this to enable more key bindings.

Oh, I don't think we support this escape at all yet? It would likely make sense to open a separate issue for this. This probably requires creating a new mode, adding it as an available mode for key bindings and creating appropriate mouse bindings for just that mode.
