### ISSUE TITLE
KDE: opacity not working

### ISSUE THREAD

**Issue by Bumbadawg** [jwilm/alacritty#2702]
Hi,
on latest KDE, X11 :
the setting `background_opacity: 0.5` doesn't change opacity, remaining opaque. Isn't this setting compatible with Kwin compositor ?

**Comment by kchibisov** [comment]
This is a bug, which is tracked here (#2254) and fixed here #2438 (this pr is a wip FYI).

**Comment by Bumbadawg** [comment]
Alright then, thanks for the fast feedback @kchibisov !
