### ISSUE TITLE
Output is not rendered on time

### ISSUE THREAD

**Issue by Trojan295** [jwilm/alacritty#2704]
Which operating system does the issue occur on?
`Debian Testing on a VirtualBox using VBoxSVGA graphics controller with 256MB of vRAM`

If on linux, are you using X11 or Wayland?
`X11`

Alacritty: 0.3.3

After running some commands in Alacritty it looks like, the output isn't rendered, even the actual command has something written on stdout. It's not connected with specific commands, but from my observation it happens often after for opening a file neovim or running a long-running command.  The output gets rendering after I press a key.
Eg. when I open a file in neovim, then I get a blank terminal and I have to press any button to have the the terminal render.

This happens only on my VirtualBox Debian, so I believe the virtual GPU there could be problematic. glxinfo output:
```
glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 8.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 19.1.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 19.1.2
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```
I think this could be somehow connected with https://github.com/jwilm/alacritty/issues/673, although I'm opening the issue, cause I'm not sure.

**Comment by kchibisov** [comment]
> This happens only on my VirtualBox Debian, so I believe the virtual GPU there could be problematic. glxinfo output:

No, it's a bug in `X11` backend in our current dependencies. The bug is tracked here #2217 and resolved here #2438 (this PR is WIP).

You probably doesn't experience this bug on your host since your mesa is 18.3.* or something similar.
