### ISSUE TITLE
Removing keybindings has no affect

### ISSUE THREAD

**Issue by rgtk** [jwilm/alacritty#2708]
*GNU/Linux (X11)*

1. Copy default `alacritty.yml`
2. Remove defined key bindings:
```
  - { key: Equals,   mods: Control, action: IncreaseFontSize             }
  - { key: Subtract, mods: Control, action: DecreaseFontSize             }
```

3. Save file.
4. In new Alacritty window, press `C--` and `C-=` and see font increase and decrease respectively.

Since key bindings were deleted, this is unintended.

Are key bindings merged with internal default config? If so, how can I remove key bindings I don't want (they clash with my Emacs configuration).

**Comment by rgtk** [comment]
Changing `action` to "Paste" behaves as intended.

**Comment by kchibisov** [comment]
That's probably a little bit odd behavior, but these bindings (as well as other options) a builtin into alacritty during compilation from default config. To unmap them you need the following
```
 - { key: Equals,   mods: Control, action: None             }
 - { key: Subtract, mods: Control, action: None             }
```

**Comment by rgtk** [comment]
@kchibisov Good catch. I revisited default config comments once again and it states clearly:
```
# Bindings are always filled by default, but will be replaced when a new
# binding with the same triggers is defined. To unset a default binding, it can
# be mapped to the `None` action.
```

Thanks.

**Comment by awilkins** [comment]
Arrived here because I wanted Alt-Enter to not do "ToggleFullscreen" on Windows

Setting the binding to `ReceiveChar` means the key does what the key would do normally.

**Comment by notableclutter** [comment]
@awilkins thank you, I was facing this exact issue. Here's the config I ended up using:
```toml
[keyboard]
bindings = [
  { key = "F11", mods = "Shift", action = "ToggleFullscreen" },
  { key = "Enter", mods = "Alt", action = "ReceiveChar" },
]
```
