### ISSUE TITLE
`cat` blocks input

### ISSUE THREAD

**Issue by okuuva** [jwilm/alacritty#271]
After the latest PR merge, Alacritty doesn't crash anymore when running `cat /dev/urandom`. However, I'm unable to cancel the command with `Ctrl+C`, so the only way to quit is to kill the terminal window. For reference, `Ctrl+C` works on gnome-terminal almost immediately, and on urxvt after bashing it for a while. I also tried it with `cat`ing some long text files and they seem to have the same problem, though they respond to `Ctrl+C` after a while.

`<insert a bad pun about long cat being long here>`

I'm at ec339f728a18657f3b47af55fd2afed56ed39a26.

Oh, and I'm on Debian Jessie Stable if that makes any difference.
```
$ uname -a
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
```

**Comment by jwilm** [comment]
Can you try out the `fix-input-blocking` branch and see if that resolves your issue?

**Comment by okuuva** [comment]
I'm not at computer atm, will try it first thing tomorrow.

**Comment by okuuva** [comment]
Got some time to test it out, didn't help. In fact, I wasn't able to cancel `cat`ing the long text file (10M lines of foo used in performance issue #205) like In master. `cat /dev/urandom` was unresponsive too.

**Comment by jwilm** [comment]
Branch was updated. I have higher hopes of it working this time :).

**Comment by okuuva** [comment]
Ok, tried it out now I can abort long `cat` jobs. The command takes a second or two to go through but at least the task is aborted and that could have something to do with my buggy Mesa drivers.

Cancelling `cat /dev/urandom` writes `6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c6c` to the input field but that can be erased normally with `ctrl+u`, so just a minor inconvenience compared to having to kill the whole terminal. Thanks again for the quick response!

**Comment by jwilm** [comment]
@okuuva I think the reason it takes so long to go through is all of the output being written to stderr during that time. If you run `target/release/alacritty 2>/dev/null`, it will probably be *a lot* faster.

The `6c` is part of a response to the identify terminal request. Since other terminals don't display that, it's likely we're doing something wrong.

In any case, I'm going to merge that branch since it seems to fix this issue.
