### ISSUE TITLE
Feature request: multiple colour schemes

### ISSUE THREAD

**Issue by hexadecatrienoic** [jwilm/alacritty#2710]
I like to use a light theme during the day and switch over to a dark theme when the sun goes down. Would it be possible to define multiple colour schemes and toggle between them with a keybind?

**Comment by chrisduerr** [comment]
You can use yaml anchors to have multiple themes in your config file and change between them just by changing a single field.

Then you can just replace the file and the config will be live-reloaded.

This is something that other people have reported to work pretty well in the past. Maybe it will work for you too?

**Comment by hexadecatrienoic** [comment]
This is exactly what I was looking for. I've added a section on the [colour schemes wiki page](https://github.com/jwilm/alacritty/wiki/Color-schemes) for anyone else looking to do the same thing.

**Comment by chrisduerr** [comment]
> I've added a section on the colour schemes wiki page for anyone else looking to do the same thing.

Great idea, thanks!

**Comment by waynr** [comment]
First off, the color schemes wiki and yaml anchor is really great! I recently began using alacritty after years of using `rxvt-unicode`. Just being able to live reload the color scheme for all my open terminals is a revelation for me!

However, I'm wondering what the maintainers think about the possibility of adding support for a `schemes` config option that would enable a user to scroll through color schemes using an action that can be bound to a key or mouse binding.

**Comment by chrisduerr** [comment]
> However, I'm wondering what the maintainers think about the possibility of adding support for a schemes config option that would enable a user to scroll through color schemes using an action that can be bound to a key or mouse binding.

Not interested in the complexity of this. All it would be used for is finding the initial theme and there are plenty of websites showing off colorschemes live.

If you regularly change between schemes, chances are you're just changing between a few and then the yaml anchor solution works pretty well.
