### ISSUE TITLE
Windows: TERM variable doesn't work on WSL

### ISSUE THREAD

**Issue by wight554** [jwilm/alacritty#2711]
Which operating system does the issue occur on?
Windows 10

To reproduce:
1. Set shell.program to wsl and TERM variable in alacritty.conf
2. Open alacritty
3. Check $TERM variable, still default

Tried with alacritty terminfo and xterm, default is xterm-256color

**Comment by chrisduerr** [comment]
Have you checked that you're editing the correct config file? You can see where the loaded config is located by running `alacritty -v`.

Also please share your config to make sure you've set everything up properly.

**Comment by wight554** [comment]
1) I'm sure proper config file is in use and it's modified slightly so I would've noticed if it wasn't
2) My config file https://del.dog/asiquliyuf.sh

**Comment by chrisduerr** [comment]
When you start another WSL shell or Alacritty with `-e wsl.whatever` and prepend `TERM=xterm`, does that do the job?

It's possible that WSL is just setting this environment variable itself after startup, at which point there's nothing Alacritty can do and this needs to be resolved in the WSL config.

**Comment by wight554** [comment]
Sorry, it's a bit unclear what to do to me
Tried running `./alacritty -e wsl TERM=xterm` but it just crashes even with TERM=xterm256-color

**Comment by chrisduerr** [comment]
You're supposed to put it *before* the command, to set the environment variable for that command.

**Comment by wight554** [comment]
Nope, doesn't work as well, still default

**Comment by chrisduerr** [comment]
Sounds like there's nothing Alacritty can do then and it's done by WSL itself at startup. You'll have to set the term variable in your shell config then, that should definitely work.

**Comment by wight554** [comment]
Found the way to workaround this issue
WSL accepts WSLENV variable that can contain env variables divided by : (tested in cmd)
So it can be fixed by:
``set TERM=alacritty
set WSLENV=TERM && wsl``

**Comment by chrisduerr** [comment]
That sounds like the proper way to do this with WSL then. Closing as resolved.

**Comment by wight554** [comment]
Yeah it is but is there any possibility to simplify handling of this?
I can't find fancy way to do this via alacritty config now
And starting alacritty with WSLENV param won't work as well

**Comment by chrisduerr** [comment]
>  I can't find fancy way to do this via alacritty config now

You should be able to put this in Alacritty's `env` section, right?

If WSL sets environment variables on startup, there's absolutely nothing Alacritty can do about it. Alacritty can only suggest environment variables to WSL, but if it ovrrides these that's up to WSL and you'd have to complain to them (they'd likely just tell you to set WSLENV though I'd assume).

**Comment by wight554** [comment]
Couldn't try before, srry
Apparently it works this way:
```
env:
  TERM: alacritty
  HELLO: world
  WSLENV: TERM:HELLO
```

**Comment by runkelstein** [comment]
I tried that with WSL2 but it does not work for me

`env:
  TERM: alacritty
  TEST: test
  WSLENV: TERM:TEST`

I tried it also with appending /w as suffix to the WSLENV

Like described in this article: https://devblogs.microsoft.com/commandline/share-environment-vars-between-wsl-and-windows/
