### ISSUE TITLE
in Vim, `Del` key acts weird

### ISSUE THREAD

**Issue by khaledAX** [jwilm/alacritty#272]
i am using Kubuntu 16.04, and NeoVim with it. just installed Alacritty to check it out, so it's still in defalt settings.

in Vim, whenever i press `del` key (regardless, `insert` mode or `command` mode) , it opens up Vim's help-screen. it don't happen on any other terminal app.

here's the screenshot after it happens ...
![Imgur](http://i.imgur.com/jYY9nzY.png)

**Comment by Libbum** [comment]
This is a neovim issue, not related to alacritty directly I think. Something to do with terminfo rules and is actively being fixed: neovim/neovim#3211.

**Comment by khaledAX** [comment]
i agree with you, @Libbum. Thanks for the pointer, closing the issue.
