### ISSUE TITLE
Alt+Shift+Backslash (Alt+Vertical Bar) not working properly in Kakoune

### ISSUE THREAD

**Issue by micouy** [jwilm/alacritty#2722]
I use `Alt+Shift+Backslash` (`Alt+Vertical Bar`) combination in Kakoune and it doesn't work properly in Alacritty. I know there was an issue about escape codes with multiple modifiers so I assume that's the cause of this problem. I also tested it with config set to `/dev/null`.

I discovered that it can be fixed by adding this line to section `key_bindings` in config:
```
- { key: Backslash, mods: Alt|Shift, chars: "\x1b|" }
```

I filed this issue in case somebody has a similar problem. Sorry if this behavior is expected or it's not caused by Alacritty.

OS: `macOS 10.14.1`
Alacritty version: `alacritty 0.3.3 (cc3e4d3)`

**Comment by chrisduerr** [comment]
This is currently tracked in https://github.com/jwilm/alacritty/issues/2688.
