### ISSUE TITLE
Can't change the icon on the installation

### ISSUE THREAD

**Issue by hrqmonteiro** [jwilm/alacritty#2725]
I built Alacritty exactly as it was on the instructions [here](https://github.com/jwilm/alacritty/blob/master/INSTALL.md#dependencies), but when i get to these steps:

> sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
> sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
> sudo desktop-file-install extra/linux/alacritty.desktop
> sudo update-desktop-database

it doesn't matter which icon i copy to be the Alacritty.svg, the icon turns out to be EXACTLY the same, this one:

![17-08-2019-18:17:17](https://user-images.githubusercontent.com/17055027/63217347-48baf300-c11b-11e9-88c0-df8e69701fd1.png)

I just don't know where does he get it, every since the beginning of the compilation, when i clone the git folder, i already changed the icons on the "extra/logo" folder, but it does nothing at all.

And i just don't want it, i want to change it but no matter what i do, it remains the same. Even tho in the /pixmaps folder the icon is what i copied:

![17-08-2019-18:18:04](https://user-images.githubusercontent.com/17055027/63217350-5d978680-c11b-11e9-868e-e2f63d3213ee.png)

Any suggestions? Please.

**Comment by chrisduerr** [comment]
It depends on where these icons are displayed. If you want to change them in all places you have to change the `.ico` icon file before compiling Alacritty.

**Comment by hrqmonteiro** [comment]
> It depends on where these icons are displayed. If you want to change them in all places you have to change the `.ico` icon file before compiling Alacritty.

Ok, where is the .ico file in the folder? Couldn't find it, please.

**Comment by hrqmonteiro** [comment]
All i can find is this folder:
![17-08-2019-18:29:12](https://user-images.githubusercontent.com/17055027/63217438-f084f080-c11c-11e9-877a-200077614ef7.png)

**Comment by chrisduerr** [comment]
It's in `extra/windows/alacritty.ico`.

**Comment by hrqmonteiro** [comment]
Hm ok, i think i couldn't figure it out that something in the windows folder would have anything to do with the rest, but i will try changing it right now, thanks.

**Comment by hrqmonteiro** [comment]
Yea, that did it. Thank you!

**Comment by chrisduerr** [comment]
> Hm ok, i think i couldn't figure it out that something in the windows folder would have anything to do with the rest, but i will try changing it right now, thanks.

Yeah unfortunately the Windows msi installer configuration is not capable of resolving relative paths so it needs to be in the same directory.
