### ISSUE TITLE
Where could I see the benchmarks within other terminal emulators?

### ISSUE THREAD

**Issue by mkwork** [jwilm/alacritty#2730]
And their results for current stable release.

Thank you in advance.

**Comment by chrisduerr** [comment]
The last in-depth comparison with other terminal emulators has been in the scrollback release announcement. They should still look very similar today unless other terminal emulators have made major strides.

https://jwilm.io/blog/alacritty-lands-scrollback/

**Comment by mkwork** [comment]
Thanks. But there are mostly throughput measurements, and where could I've seen some latency ones? Or it's just common practice?

I understand, that I can peek some average latency from throughput but there are lack of mean or distribution info in such case. Great throughput could be achieved  e.g. with great queues.

I've installed v0.33 and subjective look shows no difference with `gnome-terminal` (still talking about latency), while `gvim` or some other text editors do so. Yep I understand that I should plus any additional vim's latency. But it's a bit correlated with such [benchmarks set](https://lwn.net/Articles/751763/). Have you tried that?

**Comment by chrisduerr** [comment]
The benchmarks listed in the lwn article should be accurate. However measuring latency is tough, especially on platforms like Wayland. So until there is a simple tool which works on all platforms, latency is not actually tested regularly for Alacritty, unless there are some major changes which are likely to affect it.

So we try to make sure no regressions are introduced, however for making improvements and continuous benchmarking some more research into better tooling would be required first.
