### ISSUE TITLE
Class is set improperly

### ISSUE THREAD

**Issue by thoradically** [jwilm/alacritty#2733]
Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
X11

When ran with --class command line flag. class should be set twice
![image](https://user-images.githubusercontent.com/44036082/63302275-5c19ba00-c2e5-11e9-8bcd-6bcc05f96a2e.png)

otherwise it doesn't work as an i3's window criteria, e.g. 
> for_window [class="^scratchpad$"] border 1pixel, move scratchpad

**Comment by chrisduerr** [comment]
Well there's a difference between these. One is the instance and one is the general window class. It's a bit of a shortcoming of i3 I think that this is not supported properly or I might also be missing something.

However, the latest Alacritty does support setting both of these. It just hasn't been released yet officially.
