### ISSUE TITLE
Italic doesn’t work on Windows

### ISSUE THREAD

**Issue by chris-morgan** [jwilm/alacritty#2745]
Started in #894, but I now believe that this is a different issue.

On Windows 10 version 1903 (build 18362.295), alacritty master, `CSI [ 3 m` (italic) and `CSI [ 23 m` (cancel italic) just don’t work. You echo it like this:

```sh
echo -e 'Normal, \x1b[1mbold\x1b[22m, \x1b[3mitalic\x1b[23m, \x1b[1;3mbold italic\x1b[22;23m'
```

… but it disappears before `<alacritty_terminal::ansi::Performer as vte::Perform>::csi_dispatch`.

Reproducible with both WinPTY and ConPTY backends.

I don’t know how WinPTY and ConPTY are structured, but I suspect that they’re meddling, and filtering out things that *they* don’t know about. When I log from `csi_dispatch` when `action == 'm'`, I observe substantial differences between WinPTY and ConPTY—after filtering some things out, WinPTY mostly passes what you asked for, while ConPTY seems to split combined commands up and rewrite some things like bold to add bright text, and turn unbold (22) into reset () if possible—sure looks like there’s something vaguely intelligent in there, which is super annoying for Alacritty, which would much prefer to implement everything itself.

Can anything be done about this? Some ideas:

1. Disable or bypass the bad WinPTY/ConPTY intelligence;
2. Ask Microsoft to allow same;
3. Ask Microsoft to at least pass unknown CSI through;
4. Ask Microsoft to implement `3` and `23` at least enough to pass them through, even if they don’t implement it visually yet. (This is probably a bigger job than I’d like, since the unbold → reset transformation suggests they’re keeping track of active attributes.)

Or I might be completely wrong, and something else is to blame.

I suspect *something* to be possible, since ConEmu [includes this line in its README](https://github.com/Maximus5/ConEmu#description):

> - using normal/bold/italic fonts for different parts of console simultaneously;

But I haven’t actually tried it.

*(Now I have; it looks like it actually achieves that by sacrificing a background colour, reinterpreting specific background colours as bold or italic. Yuck! Maybe there is no current solution, then.)*

**Comment by chrisduerr** [comment]
If Windows PTYs do not send the escape sequence at all, I don't think there's anything we can do.

It might be interesting to see if the new Windows Terminal can handle it though and if it does, how it's doing it.

I'm strongly against introducing some weird hacks that break support for other things to support this, in this case this bug should be propagated up to Microsoft to resolve this properly.

**Comment by chris-morgan** [comment]
Yeah, I *definitely* don’t consider ConEmu’s apparent technique an acceptable workaround—quite apart from the fact that it would prevent italic being combined with other background colours, which renders the trick incompatible with a Vim colour scheme, which is my desired use case for italics.

I just tried installing Windows Terminal, and it doesn’t look like it even supports a bold font—it just switches to the bright foreground colour—so I can’t tell whether the italic SGR code is getting through there or not.

Possibly relevant: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-formatting documents 1 as “Bold/Bright”, “Applies brightness/intensity flag to foreground color”. That list also lacks various other relevant SGR values like 2 (dim) and 3 (italic). I thought the whole idea of ConPTY was to *get away* from that lot, but I’m not at all familiar with how it all works. I scarcely even know what a PTY actually is internally (but I had been under the impression it would be a dumb pipe, which is looking to be incorrect).

**Comment by chrisduerr** [comment]
Looking at some windows terminal issues like https://github.com/microsoft/terminal/issues/355, it definitely seems like bold font should be supported? Maybe it's an issue with your font?

I haven't seen any issue about italics, so I'm not sure if that means it doesn't work and nobody cares or if it should work just fine.

**Comment by chris-morgan** [comment]
No, that’s all about its reinterpretation of 1 as changing the foreground colour to the bright variant, as close examination of the screenshots also confirms.

**Comment by chrisduerr** [comment]
Oh wow, the text was already so bold that it didn't even register to me. :smile: 

You're completely right of course.

**Comment by chris-morgan** [comment]
I [asked about this](https://twitter.com/__chrismorgan/status/1165608412035420160) and as advised have filed https://github.com/microsoft/terminal/issues/2554. Up to you if you want to keep this open to track it or close it since the underlying issue appears to belong to another project.

**Comment by chris-morgan** [comment]
In accordance with https://github.com/microsoft/terminal/issues/2554#issuecomment-547688149, I confirm this to be fixed from build 19013 onwards. As remarked in that comment, in build 19013 it will only work the first time you use it, but that’s enough to confirm that italic and bold italic are working and will work fully in the next major release of Windows 10. No need for this to remain open, then. 🙂

**Comment by habamax** [comment]
I can confirm windows10 2004 has italics

![image](https://user-images.githubusercontent.com/234774/84263465-35549a80-ab28-11ea-8847-688760aa61ad.png)

![image](https://user-images.githubusercontent.com/234774/84263561-60d78500-ab28-11ea-8295-fcc2ba2e2f25.png)
