### ISSUE TITLE
Text doesn't get flushed

### ISSUE THREAD

**Issue by nycex** [jwilm/alacritty#2748]
Which operating system does the issue occur on?
Arch Linux with latest updates (Kernel: 5.2.9-arch1-1-ARCH)

If on linux, are you using X11 or Wayland?
I'm using X11 with i3-gaps.

Alacritty sometimes doesn't flush the output of the terminal anymore, when the display isn't focused. When I hover over it with the mouse again, the text in the terminal will be flushed.

**Comment by kchibisov** [comment]
Your issue is a duplicate of #2217. There is a PR(#2438) that aims to solve this problem and it's quite usable from my testing experience. You can try running it. In case you decide to give it a try, please report any issue you'll face during testing it.

**Comment by nycex** [comment]
I'm unsure if it is a duplicate, because 1. it doesn't happen if i open a tui application but rather if a cat a large file e.g. and 2. not a keypress fixes it, but hovering over it with the mouse

**Comment by kchibisov** [comment]
It's not about opening something, it's about `alacritty` stops rendering after sometime without user interactions on X11.

>  not a keypress fixes it, but hovering over it with the mouse.

Keypress to **focused** `alacritty` instance, which stops updating?

**Comment by nycex** [comment]
Yes, I think you're right, then I'm gonna close this as it's duplicate to #2217
