### ISSUE TITLE
"No backend is available" on NixOS system

### ISSUE THREAD

**Issue by mattdenner** [jwilm/alacritty#275]
I've managed to get alacritty to build on NixOS but I'm seeing the following on running:

```
$ alacritty
Alacritty encountered an unrecoverable error:

        Error creating glutin::Window; No backend is available
```

I've noticed #251 mentions trying `glxgears` and that does run on my system, although it outputs:

```
$ glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
```

I'm running with i3 window manager and I've attached the output from [glxinfo.txt](https://github.com/jwilm/alacritty/files/696092/glxinfo.txt) if that helps.  The `default.nix` file I used to build alacritty is below:

```
let
  pkgs = import <nixpkgs> {};
in pkgs.rustNightlyBin.buildRustPackage rec {
  version = "0.1.0";
  name = "alacritty-${version}";

  buildInputs = with pkgs; [
    cmake
    pkgconfig
    freetype
    fontconfig
    xclip
  ];

  src = pkgs.fetchFromGitHub {
    owner = "jwilm";
    repo = "alacritty";
    rev = "ec339f728a18657f3b47af55fd2afed56ed39a26";
    sha256 = "04xawask22nr6f89q7gvxgc9xjzq4bhdr2wr3w31pppkjjkf34ia";
  };

  depsSha256 = "138bfnrg3j49vl6j2daf1jyyng5r6d088qhsqikhyyqzjx1ih0v2";
}
```

If there's anything else you need or I can try let me know.

**Comment by Senjai** [comment]
@mattdenner I had to use X to load in alacritty, I was not able to start it from another terminal emulator. For gnome I just used the .desktop that was provided after building the project. I'm not sure why this is the case though.

**Comment by mattdenner** [comment]
@Senjai thanks for that but unfortunately that doesn't appear to work either: the same error is now shown in the journald logs.  I put the desktop file in the appropriate place and used `i3-dmenu-desktop` to execute it.

**Comment by mattdenner** [comment]
I think I've tracked this down into `winit` and it seems to be a problem loading the X11 libraries.  For some reason they appear to be missing / not on the load path as I can't even run `cargo run --example window` in the `winit` project itself.  I'll have a bit more of a dig around.

**Comment by mattdenner** [comment]
I managed to track it down: `winit` loads some X11 libraries dynamically through FFI which nixos is a bit unhappy about.  By adding `${HOME}/.nix-profile/lib` to `LD_LIBRARY_PATH` and making sure that the required libraries are available by installing their derivations (`xorg.libX11`, `xorg.libXcursor`, `xorg.libXxf86vm`, `xorg.libXi`) I'm now able to run Alacritty.

**Comment by jwilm** [comment]
Thanks for following up with your workaround @mattdenner. Should glutin/winit be doing something different to better support nixos?

**Comment by mattdenner** [comment]
I think the only comment I would make is that the error is misleading: had it said something about being unable to load libraries then it would have been quicker solve.

**Comment by lheckemann** [comment]
FWIW, I wrote a wrapper looking like this:
```sh
#!/bin/sh
export LD_LIBRARY_PATH=/run/opengl-driver/lib/:$(nix-instantiate --eval -E 'with import <nixpkgs> {}; lib.makeLibraryPath (with xorg; [libX11 libXcursor libXxf86vm libXi])' | tr -d '"')
exec path/to/alacritty
```
which allows it to run just fine, and is a better (more nix-appropriate) solution than adding the libraries to the user profile.
