### ISSUE TITLE
Generic Super / Command mods key binding

### ISSUE THREAD

**Issue by simmel** [jwilm/alacritty#2754]
It would be nice to be able to share the config between OS X and Linux/Windows computers so a generic name for Command / Super which would do the right thing™ in the configuration would be awesome.

I'm also all for not adding anything but just that Super would be equal to Command on OS X and that Command on Linux / Windows would be equal to Super.

**Comment by chrisduerr** [comment]
This should already be the case. Have you tested this out and confirmed that it does not work?

**Comment by simmel** [comment]
I have not! I suspected as much because I couldn't find Super or Command 
in glutin but then again I couldn't find it in alacritty either (but I'm 
just bad at searching I guess).

I'll try it!

**Comment by chrisduerr** [comment]
I'd assume this works fine then. Using either `Command` or `Super` should be identical.
