### ISSUE TITLE
Macos deprecation warning

### ISSUE THREAD

**Issue by CavalloneChen** [jwilm/alacritty#2756]
Which operating system does the issue occur on?
Macos

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/28266566/63725168-2f891380-c88c-11e9-9633-09bbe12a4d1f.png">

**Comment by chrisduerr** [comment]
This warning means the window.start_maximized option has been deprecated and you should use the `window.startup_mode` option instead. This can be fixed in your configuration file in ~/.config/alacritty/alacritty.yml.

**Comment by CavalloneChen** [comment]
Thanks, that resolved my warnings.
