### ISSUE TITLE
"Alacritty quit unexpectedly"

### ISSUE THREAD

**Issue by miguelmota** [jwilm/alacritty#2760]
Alacritty randomly crashes and get this prompt when reopening:

<img width="601" alt="Screen Shot 2019-08-27 at 12 28 13 PM" src="https://user-images.githubusercontent.com/168240/63801870-2f0d6e80-c8c6-11e9-8e1b-fc9cb73ebe18.png">

macOs version:

<img width="604" alt="Screen Shot 2019-08-27 at 12 29 19 PM" src="https://user-images.githubusercontent.com/168240/63802208-ebffcb00-c8c6-11e9-9e66-407df1a26666.png">

**Comment by chrisduerr** [comment]
How frequent is this? Which Alacritty version are you running? Is there any output when you launch Alacritty from a different terminal and it crashes? Also, what does the `Report...` button give you?

**Comment by miguelmota** [comment]
@chrisduerr sorry for the delay, this is the screen after clicking on the 'Report...' button:

<img width="560" alt="Screen Shot 2019-08-30 at 3 36 44 PM" src="https://user-images.githubusercontent.com/168240/64054483-0c848b00-cb3c-11e9-9340-719f8bdf951f.png">

I've launched Alacritty from a different terminal but there is no output when it crashes.

Let me know if there's other places I can get logs from or something to help debug why it keeps quitting unexpectedly

**Comment by chrisduerr** [comment]
> I've launched Alacritty from a different terminal but there is no output when it crashes.

How did you launch it exactly?

**Comment by miguelmota** [comment]
@chrisduerr I used `open -a Alacritty`

**Comment by chrisduerr** [comment]
Yeah, that will not start Alacritty with stdout/stderr hooked up to the shell.

You need to launch it directly from `/Application/Alacritty.app/Content/alacritty`. I'm currently not on macOS, so the path might be slightly different.

**Comment by miguelmota** [comment]
@chrisduerr got it, will launch it from that. The actual path is `/Applications/Alacritty.app/Contents/MacOS/alacritty`

**Comment by miguelmota** [comment]
@chrisduerr here's the crash error

<img width="651" alt="Screen Shot 2019-09-02 at 12 47 41 PM" src="https://user-images.githubusercontent.com/168240/64131800-ec450e00-cd7f-11e9-9093-6e747f9beaa2.png">

```
2019-09-02 12:47:04.860 alacritty[1205:10488] *** Assertion failure in -[NSCGLSurface flushRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.40.119/OpenGL.subproj/NSCGLSurface.m:569
Bus error: 10
```

**Comment by chrisduerr** [comment]
Does this fail 100% of the time?

Also which version of macOS are you on and which exact macOS device are you running? Which GPU does it have?

**Comment by miguelmota** [comment]
> Does this fail 100% of the time?

Alacritty crashes randomly a few times a day. Other terminals like Terminal.app, iTerm.app and KiTTY don't crash

The programs I run are tmux and vim

> Also which version of macOS are you on and which exact macOS device are you running? Which GPU does it have?

Macbook Model [A1398](https://everymac.com/ultimate-mac-lookup/?search_keywords=a1398)

Version: 10.14.4 (18E226)

Memory:
16 GB 1600 MHz DDR3

Graphics:
AMD Radeon R9 M370X 2 GB
Intel Iris Pro 1536 MB

**Comment by chrisduerr** [comment]
Have you run into similar issues with other applications?

It seems like these are spurious system failures exclusive to your system. So there might be software/hardware/driver issues.

**Comment by miguelmota** [comment]
Alacritty is the only application that randomly quits like that. I've resorted to iTerm for the time being 

And yea that's a possibility, need to further diagnose the macbook

Thanks for the help

**Comment by chrisduerr** [comment]
Would be interesting to see if anyone else can reproduce this at all. This has never happened to me in a long time of running Alacritty on macOS.

**Comment by nixpulvis** [comment]
Reading a few threads online about a [similar issue in Sublime Text 3](https://forum.sublimetext.com/t/build-3200-crashing-on-macos-assertion-failure-in-nscglsurface-flushrect/42899) makes me think that @miguelmota's mac is connected to a external DisplayLink display. Is that true?

Anyway, it [sounds like this issue was fixed in macOS 10.14.5](https://bugzilla.mozilla.org/show_bug.cgi?id=1551223#c4) (the version after yours), and now the latest macOS is 10.14.6. I recommend updating your macOS installation and seeing if this solves your issue.

**Comment by miguelmota** [comment]
@nixpulvis thanks for the suggestion. I've updated to 10.15.6 now and will report back here with any issues

**Comment by miguelmota** [comment]
No issues so far! Closing and thanks for the help and support @chrisduerr @nixpulvis

**Comment by westandskif** [comment]
I'm having the same issue, experienced this 3-4 times within 3-4 hours.
However I didn't even get any system popups to report the issue, it feels like `kill -9 ...`

OS X: 10.15.2
Installed today with `brew cask install alacritty`

**Comment by kchibisov** [comment]
@westandskif If you're on v0.4.1 I feel like you're managing to close it somehow due to this bug #3188 and because we have `cmd + w/cmd + q` bindings to close a app.

**Comment by westandskif** [comment]
Thank you! I've set W and Q bindings to None for the time being.
