### ISSUE TITLE
Copy upon mouse selection

### ISSUE THREAD

**Issue by reckoner** [jwilm/alacritty#2768]
Which operating system does the issue occur on?
Windows 10 WSL Ubuntu 18

If on linux, are you using X11 or Wayland?
x11

Upon selection using the mouse, is it possible to trigger the copy using a mouse click or even copy automatically upon selection? 

Thanks!

**Comment by chrisduerr** [comment]
https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L307-L308

**Comment by reckoner** [comment]
For posterity.

```
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true
```

**Comment by grepsedawk** [comment]
@reckoner you're amazing, thank you for including the posterity comment

**Comment by prakash2033** [comment]
@reckoner You're awesome, I recently moved from xterm to alacritty and have been really missing this feature (was using .Xresources for selection to clipboard). Thank you so much.

**Comment by plainee** [comment]
> For posterity.
> 
> ```
> selection:
>   save_to_clipboard: true
> ```

any available config on toml?

**Comment by nixpulvis** [comment]
@plainee it’s the same, so;

```toml
[selection]
save_to_clipboard = true
```

**Comment by plainee** [comment]
> @plainee it’s the same, so;
> 
> ```toml
> [selection]
> save_to_clipboard = true
> ```

thanks
