### ISSUE TITLE
how to fix Problem with config: invalid type: floating point?

### ISSUE THREAD

**Issue by woshichuanqilz** [jwilm/alacritty#2769]
Which operating system does the issue occur on?
   Static hostname: lizhe-pc
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: 203cf1d0f8444b828d515d76d64b72b4
           Boot ID: 8d0458040d43403d8d5e169068ce34ba
  Operating System: Manjaro Linux
            Kernel: Linux 4.19.66-1-MANJARO
      Architecture: x86-64
If on linux, are you using X11 or Wayland?
I dont know yet how to check it? 

I use the config file in this link

https://gist.githubusercontent.com/travisfw/6b022c1ca6aaa1197e12d1dfe011ba84/raw/b1e9906e697191fba8a76a3438acb75c3d2a3069/alacritty.yml

![DeepinScreenshot_select-area_20190901102239](https://user-images.githubusercontent.com/11295355/64070994-88004c80-cca2-11e9-8a4e-e481e04e07bb.png)

Everything works fine, but 
error msg occurs when I start the alacritty at the bottom of the terminal. 
I try to change the 2.0 to 2 in the config file. But after  I change that the font in the terminal squeeze together which means a display problem comes out. 

So how to fix this problem make the error warning not show out again. 

> 
[2019-09-01 09:59] [ERROR] Problem with config: invalid type: floating point `2`, expected i8; using default value
[2019-09-01 09:59] [ERROR] Problem with config: invalid type: floating point `-11`, expected i8; using default value
[2019-09-01 09:59] [WARN] Config render_timer is deprecated; please use debug.render_timer instead

**Comment by chrisduerr** [comment]
> invalid type: floating point -11, expected i8

There's a value `-11.0`, which is expected to be `-11`. This goes for all the floating point related errors.

> Config render_timer is deprecated; please use debug.render_timer instead

The value `render_timer` has moved under the field `debug`.

Generally, it's probably easier to just delete whatever you don't want to change. If it's not in the config, it will use the default value.

**Comment by woshichuanqilz** [comment]
> > invalid type: floating point -11, expected i8
> 
> There's a value `-11.0`, which is expected to be `-11`. This goes for all the floating point related errors.
> 
> > Config render_timer is deprecated; please use debug.render_timer instead
> 
> The value `render_timer` has moved under the field `debug`.
> 
> Generally, it's probably easier to just delete whatever you don't want to change. If it's not in the config, it will use the default value.
> 
> Let me know if you have any more questions, closing this issue since it's not an actual issue with Alacritty but more of a support ticket instead (which should be appropriately answered with this response).

Tnx for you reply bro.

As I said in the first post if you change the -11.0 to 11, the font cant show properly. if you use -11.0 font shows well as the first pic I posted
![DeepinScreenshot_select-area_20190901135358](https://user-images.githubusercontent.com/11295355/64072397-1505ce80-ccc0-11e9-8e5e-df68b078e492.png)

**Comment by chrisduerr** [comment]
> As I said in the first post if you change the -11.0 to 11, the font cant show properly. if you use -11.0 font shows well as the first pic I posted

It shows properly because it's not using any offset by default. If you want it to look the same way it does in your first pic, set it to `0`, not `11` or `-11`.
