### ISSUE TITLE
Cannot start Alacritty on macOS

### ISSUE THREAD

**Issue by lukasbash** [jwilm/alacritty#2770]
Which operating system does the issue occur on?
macOS Mojave 10.14.6 (latest supplemental update)

The terminal tries to start but immediately quits without any error message.
An additional observation from the system logs:
`com.apple.xpc.launchd[1] (io.alacritty.20948[46693]): Service exited with abnormal code: 1`
I tried to install it both, via brew and the precompiled image on github (I guess it is the same installation?).

**Comment by kchibisov** [comment]
Would you mind running `RUST_BACKTRACE=1 /Applications/Alacritty.app/Contents/MacOS/alacritty -vvv` from other terminal emulator and post the output here?

Path to `alacritty` on your system may vary a bit, but you've got an idea.

**Comment by lukasbash** [comment]
> Would you mind running `RUST_BACKTRACE=1 /Applications/Alacritty.app/Contents/MacOS/alacritty -vvv` from other terminal emulator and post the output here?
> 
> Path to `alacritty` on your system may vary a bit, but you've got an idea.

LOL. You saved my day!
Thanks for the quick reply.

It dumps the following:
```
Couldn't find a font with name Hack and style Regular
Please check the font config in your alacritty.yml.
```

After fixing this, it starts up normally.

Do you think there is a way to improve the error handling here (to prevent simple issue like this one in the first place)?

**Comment by kchibisov** [comment]
We've already improved things on master (see e398eb84064c5eac7cb8a97c276494100a37314b), so it ensures that `alacritty` will start at least.

**Comment by chrisduerr** [comment]
Closing since this has been fixed in master.
