### ISSUE TITLE
Vim/neovim + NERDTree The first few mouse double clicks will select the text instead of expanding the directory

### ISSUE THREAD

**Issue by Hentioe** [jwilm/alacritty#2772]
Recorded video demo:

![Peek 2019-09-03 00-37](https://user-images.githubusercontent.com/13946976/64127296-930ec600-cde3-11e9-96b6-3e3746963209.gif)

Note: The first two mouse double click actions.

This problem has existed on my side since many versions. It only appears after the first few mouse double-clicks of vim/neovim.

Other terminals (such as Konsole) do not have this problem.

Alacritty Version: `0.3.3`
OS: openSUSE Tumbleweed (x11)

**Comment by chrisduerr** [comment]
When you say vim/neovim, do you mean you've actually tested both and both show this problem? They're quite different when it comes to mouse handling.

**Comment by kchibisov** [comment]
FYI, I can't repro it with `neovim` + `set mouse=a` + `alacritty`'s terminfo. Anyway `alacritty` selection shouldn't work in mouse mode apps at all, unless you've pressed `shift`.

**Comment by chrisduerr** [comment]
> + alacritty's terminfo

That's actually a very good point. Please make sure you're using the correct terminfo.

This seems like a bit of a strange issue to me, since we don't do selection in vim. This selection is started by vim itself.

**Comment by Hentioe** [comment]
Thanks Reply. I currently use neovim, but when I used vim before, I also had this situation.
Because my vim provided by openSUSE has some problems with the plugin, I will try to reproduce it in a brand new virtual machine system in a few hours.
I don't rule out my configuration or environmental issues.

**Comment by Hentioe** [comment]
I found the reason, it is my mouse problem, it will often generate a double click when clicked. This behavior can occur if you click the left button many times quickly.
It doesn't appear on Konsole because I rarely open neovim on Konsole.
Sorry to bother you.
