### ISSUE TITLE
ctrl-c on w10 / pwsh closes the terminal instead of stopping the running process

### ISSUE THREAD

**Issue by gdoenlen** [jwilm/alacritty#2775]
Which operating system does the issue occur on?

```
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by chrisduerr** [comment]
Potentially related to https://github.com/jwilm/alacritty/issues/1926?

Can you reproduce this with ConPTY?

**Comment by gdoenlen** [comment]
I just set `enable_experimental_conpty_backend: true` in alacritty.yml and yes this still occurs. 

You can reproduce by running `tree` and attempt to stop it via `ctrl-c`

**Comment by chrisduerr** [comment]
If you start Alacritty from another terminal using `alacritty -v`, does it print that it's using `ConPTY`?

**Comment by gdoenlen** [comment]
Starting from pwsh 6:
```
[2019-09-03 11:50] [INFO] Welcome to Alacritty
[2019-09-03 11:50] [INFO] Configuration loaded from "C:\\Users\\george\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2019-09-03 11:50] [INFO] Device pixel ratio: 1
[2019-09-03 11:50] [INFO] Initializing glyph cache...
[2019-09-03 11:50] [INFO] ... finished initializing glyph cache in 0.0292374s
[2019-09-03 11:50] [INFO] Width: 1024, Height: 768
[2019-09-03 11:50] [INFO] Cell Size: 8 x 17
[2019-09-03 11:50] [INFO] Padding: 0 x 0
[2019-09-03 11:50] [INFO] PTY Dimensions: Line(45) x Column(128)
[2019-09-03 11:50] [INFO] Using Conpty agent
[2019-09-03 11:50] [INFO] Initialisation complete
```

**Comment by chrisduerr** [comment]
Ah okay, looks like ConPTY is working properly. Can you reproduce this with another shell? Also do you start pwsh directly or from another shell?

**Comment by gdoenlen** [comment]
In alacritty I have it start `pwsh` directly via the yml config. The above test was starting pwsh directly in windows (which I believe starts conhost.exe).

I did change the shell in alacritty back to the default (windows powershell 5) and ctrl-c works as expected with and without Conpty.

**Comment by gdoenlen** [comment]
Just to add more details I set pwsh 6 as my shell in terminus (https://github.com/Eugeny/terminus) and ctrl-c does stop it correctly, so I do think this it is something specific to alacritty.

**Comment by chrisduerr** [comment]
> I did change the shell in alacritty back to the default (windows powershell 5) and ctrl-c works as expected with and without Conpty.

This seems like powershell might be doing something odd here and it's definitely possible that terminus might have a workaround implemented for that.

If you start `pwsh.exe` from powershell 5, does that kill pwsh.exe but powershell 6 is still running? Also if you start Alacritty with pwsh directly and it quits, does it exit with a 0 exit code and no messages printed to stderr?

**Comment by gdoenlen** [comment]
Starting alacritty from pwsh 6 (conhost):

```
~> alacritty 2>&1
~> $LASTEXITCODE
0
```

>If you start pwsh.exe from powershell 5, does that kill pwsh.exe but powershell 6 is still running? 

I'm not really sure what you're asking here. It behaves exactly as if you were to call zsh from bash or any shell from another. Conhost stays open and you get the pwsh 6 prompt. Exiting that shell returns you to original shell (windows powershell 5).

**Comment by chrisduerr** [comment]
> I'm not really sure what you're asking here. It behaves exactly as if you were to call zsh from bash or any shell from another. Conhost stays open and you get the pwsh 6 prompt. Exiting that shell returns you to original shell (windows powershell 5).

I was just curious if ctrl+c would kill the `pwsh` shell and throw you back to `powershell`, which would be the case if ctrl+c for some reason killed `pwsh`. That would explain why the exit code is zero.

All Alacritty does is forward the signals to the shell, if the shell decides to quit on us, I'm not sure if we can do anything about it.

**Comment by gdoenlen** [comment]
Ok. So starting alacritty from pwsh 6 (conhost) with `alacritty 2>&1`, this will open alacritty which will then start pwsh 6.  Running `tree` and using ctrl-c to stop it early WILL work properly.

The crashing seems to only occur when starting alacrity directly. 

Does alacritty store a log anywhere?

**Comment by kchibisov** [comment]
You can use `alacritty -v` to get a clue on where log is stored and pass `--persistent-logging` to keep it after close.

**Comment by chrisduerr** [comment]
Note that Alacritty's log will only contain information about runtime issues. If Alacritty crashes, that's not written to the log. To do that you need to redirect Alacritty's output to a file.

**Comment by gdoenlen** [comment]
Redirecting output produces a 0 byte log, the log from `--persistent-logging` produces:

```
[2019-09-03 15:02] [INFO] Device pixel ratio: 1
[2019-09-03 15:02] [INFO] Initializing glyph cache...
[2019-09-03 15:02] [INFO] ... finished initializing glyph cache in 0.0291648s
[2019-09-03 15:02] [INFO] Width: 1024, Height: 768
[2019-09-03 15:02] [INFO] Cell Size: 8 x 17
[2019-09-03 15:02] [INFO] Padding: 0 x 0
[2019-09-03 15:02] [INFO] PTY Dimensions: Line(45) x Column(128)
[2019-09-03 15:02] [INFO] Using Conpty agent
[2019-09-03 15:02] [INFO] Initialisation complete
[2019-09-03 15:02] [INFO] wait_object_0
[2019-09-03 15:02] [INFO] Goodbye
```
 
The wait object and goodbye don't occur until I hit `ctrl-c`. I'm afraid I don't have much more to give you.

**Comment by enizor** [comment]
You can use `-vv` and `-vvv` to increase levels of verbosity.

I could not reproduce the issue on my Windows (WinPty, Powershell 5). Hitting `^C` while `tree` is running instantly stops it, as expected on both `v0.3.3` (` cc3e4d3`) and latest master (`db63c31`).

**Comment by chrisduerr** [comment]
@enizor Have you tested this by launching pwsh directly? Or with a different shell?

**Comment by enizor** [comment]
I left blank the shell in the config, it opens powershell by default. Is powershell different from `pwsh`?

**Comment by gdoenlen** [comment]
@enizor Yes. Default powershell on windows is Powershell 5. `pwsh` is the cross platform version (6 or above).

**Comment by chrisduerr** [comment]
I've found a similar issue here: https://github.com/felixse/FluentTerminal/issues/221

Do you use scoop @gdoenlen?

**Comment by gdoenlen** [comment]
I do! Looks like that is the culprit then. I'll try to specify full path in alacritty config instead of just setting `shell: program: pwsh`

**Comment by chrisduerr** [comment]
If that does the job, please let me know so we can close this issue. Very interesting that scoop would affect something like this though.

**Comment by gdoenlen** [comment]
Yep full path to the actual exe did it. Thanks for all the help.

**Comment by bradphelan** [comment]
This is still a bug and easy to reproduce in one line in powershell.

![2019-11-29_08-28-16](https://user-images.githubusercontent.com/17650/69851995-64d64080-1283-11ea-90b6-c25dbad90b24.gif)

If I open a terminal with new **pwsh.exe** and press **^c** all is ok. If I start python and press **^c** it kills the terminal instead of just python.

This **does not** happen with powershell 5 a.k.a **powershell.exe**

**Comment by bradphelan** [comment]
Oops sorry...I've posted this to the wrong github repo !! Cross posted it here. https://github.com/PowerShell/PowerShell/issues/11214

**Comment by jupjohn** [comment]
I've seen the same thing with nushell installed via chocolatey: the shims generated by these package managers seem to be the issue. Repointing my shell path to the real binary instead of the shim fixed the issue (as I've mentioned in https://github.com/nushell/nushell/issues/3937#issuecomment-1888238697)
