### ISSUE TITLE
Wrong window size detected

### ISSUE THREAD

**Issue by SiIky** [jwilm/alacritty#2778]
I searched for "wrong window size" in the issues but haven't found any
relevant.

# System

|                  |                                                                         |
|------------------|-------------------------------------------------------------------------|
| Operating System | Linux 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux |
| Rust Version     | nightly                                                                 |
| Display Server   | X11                                                                     |
| Window Manager   | DWM                                                                     |
| Compositor       | none (?)                                                                |

# Summary

Alacritty detects the wrong window size at startup.

# Behavior

This happens only on my larger monitor (see `xrandr` output below, if
relevant), and even with "split" windows. This does happen very often, but not
everytime, and I haven't figured out why. I started using Alacritty from commit
`f3cc7c4` and, as far as I remember, this only started on a commit from a few
weeks ago.

While writing this I installed `f3cc7c4`, and it's consistently working fine.
I'll keep it for a while just in case.

# Expectation

Alacritty should correctly detect the window size at startup.

# Extra

`xrandr` output:

```
Screen 0: minimum 320 x 200, current 4480 x 1440, maximum 16384 x 16384
DisplayPort-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.89  
   1280x960      60.00  
   1280x800      59.81  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-A-0 connected 2560x1440+1920+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   1920x1200     59.95  
   1920x1080     60.00    50.00    59.94  
   1600x1200     59.95  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1440x900      59.95  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   832x624       74.55  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
DVI-D-0 disconnected (normal left inverted right x axis y axis)
```

Ran `alacritty -v`, hid the status bar (resize Alacritty to "fullscreen"), and
unhid the status bar again. `1195x896` is, I think, the initially detected
(wrong) window size. `2375x1315` should be the detected size after the first
resize (hiding the status bar), but that's not the right size either; the right
size, after hiding the status bar, is the one that's next, `2258x1438`. Window
borders are 1px wide, hence the 2px difference from the resolutions above.

```
[2019-09-05 17:33] [INFO] Welcome to Alacritty
[2019-09-05 17:33] [INFO] Configuration loaded from "/home/siiky/.config/alacritty/alacritty.yml"
[2019-09-05 17:33] [INFO] Device pixel ratio: 1.0833333333333333
[2019-09-05 17:33] [INFO] Initializing glyph cache...
[2019-09-05 17:33] [INFO] ... finished initializing glyph cache in 0.020140466s
[2019-09-05 17:33] [INFO] Width: 1195, Height: 896
[2019-09-05 17:33] [INFO] Cell Size: 8 x 20
[2019-09-05 17:33] [INFO] Padding: 0 x 0
[2019-09-05 17:33] [INFO] PTY Dimensions: Line(44) x Column(149)
[2019-09-05 17:33] [INFO] Initialisation complete
[2019-09-05 17:33] [INFO] Font size changed to Size(18) with DPR of 1.1666666666666667
[2019-09-05 17:33] [INFO] Width: 2375, Height: 1315
[2019-09-05 17:33] [INFO] Width: 2558, Height: 1438
[2019-09-05 17:33] [INFO] Width: 2558, Height: 1416
[2019-09-05 17:33] [INFO] Goodbye
```

You can't see the cursor here, but I selected the text `Nvim is open source and freely distributable`.

![20190905172111](https://user-images.githubusercontent.com/12852780/64362992-76eb6e80-d007-11e9-8712-aa796b8d2131.png)

This is before resizing:

![20190905174858](https://user-images.githubusercontent.com/12852780/64363048-971b2d80-d007-11e9-94ea-3cc7a893089f.png)

And after resizing:

![20190905174906](https://user-images.githubusercontent.com/12852780/64363059-9e423b80-d007-11e9-8e23-d8b221a4bada.png)

This isn't a major issue in my opinion, just a mild annoyance, because
everything works fine after resizing the window. Nevertheless, this a bug, and
I'd like to save a few keystrokes everytime I open Alacritty. :p

This might be a good opportunity for me to try `git bisect` some time. Any tips
are appreciated.

**Comment by chrisduerr** [comment]
Since the description of the issue is a bit confusing to me, I'm going solely off of pictures here, but is it correct that the problem lies with the Alacritty window reserving a tiled 'space', but not completely filling it?

Could you try running #2438?

**Comment by Ckath** [comment]
just out of interest do you have what do you have your `static const int resizehints` set to in config.h of dwm? if you have that enabled(1 instead of 0, also default) its a whole world of pain with anything size and terminal related.

**Comment by SiIky** [comment]
@chrisduerr 
> Since the description of the issue is a bit confusing to me, I'm going solely off of pictures here, but is it correct that the problem lies with the Alacritty window reserving a tiled 'space', but not completely filling it?

I don't think Alacritty can decide window size, DWM does that, but "not completely filling it" is a good description.

Did you see the `alacritty -v` output? Alacritty thinks it's smaller than it actually is. Like on the first screenshot, the window was "maximized", so it should have detected `2558x1416`, but it detected `1195x896` instead.

Also on the first screenshot, did you see the text selection? I ran my mouse over the `Nvim is open ...` line, but it selected the text 5 lines below. The empty window space on top looks like it's about 5 lines aswell. I think both the text selection and window size problems are two manifestations of a single bug.

I'm sorry I can't explain it any better :/

> Could you try running #2438?

Sure thing! I'll also try running DWM in "floating" mode, letting programs decide window size/position on screen, and see what Alacritty does. I'll get back with the results.

@Ckath 
> just out of interest do you have what do you have your `static const int resizehints` set to in config.h of dwm? if you have that enabled(1 instead of 0, also default) its a whole world of pain with anything size and terminal related.

`resizehints` is set to 0 and I haven't changed my config in a while.

**Comment by SiIky** [comment]
@chrisduerr 

Just installed `fc8fcbf` of #2438 and the problem is even worse. The initial size, at startup, is smaller yet, and it doesn't correctly detect after resizing (like with master). Output of running `alacritty -v` "maximized", hiding bar, unhiding bar:

```
[2019-09-06 11:38] [INFO] Welcome to Alacritty
[2019-09-06 11:38] [INFO] Configuration loaded from "/home/siiky/.config/alacritty/alacritty.yml"
[2019-09-06 11:38] [INFO] Device pixel ratio: 1.0833333333333333
[2019-09-06 11:38] [INFO] Initializing glyph cache...
[2019-09-06 11:38] [INFO] ... finished initializing glyph cache in 0.016356258s
[2019-09-06 11:38] [INFO] Cell Size: 8 x 20
[2019-09-06 11:38] [INFO] Padding: 0 x 0
[2019-09-06 11:38] [INFO] Width: 933, Height: 700
[2019-09-06 11:38] [INFO] PTY Dimensions: Line(35) x Column(116)
[2019-09-06 11:38] [INFO] Initialisation complete
[2019-09-06 11:38] [INFO] Width: 2375.2856, Height: 1314.8572
[2019-09-06 11:38] [INFO] Width: 2375.2856, Height: 1335.2858
[2019-09-06 11:38] [INFO] Width: 2375.2856, Height: 1314.8572
[2019-09-06 11:38] [INFO] Goodbye
```

I don't know if this is because of something new on your branch, or because of something that's on master but not yet on your branch. To try this, in the local clone of your fork, I ran:

```sh
git checkout master
git pull https://github.com/jwilm/alacritty/
git merge evlp2
```

and installed Alacritty. Weirdly enough, running `alacritty -v` as above and all that, gives the same output. Did I do something wrong?

**Comment by chrisduerr** [comment]
Pretty sure the glutin rework branch is currently fully up to date with master, so merging master into it will not have any effect.

Could you try running `WINIT_HIDPI_FACTOR=1 alacritty` to see if that fixes it?

**Comment by SiIky** [comment]
@chrisduerr Sorry for the delay and thanks a lot! :) That seems to work with both master and #2438.
