### ISSUE TITLE
Default config has errors

### ISSUE THREAD

**Issue by hamptokr** [jwilm/alacritty#2782]
Which operating system does the issue occur on?
Ubuntu 19.04

If on linux, are you using X11 or Wayland?
X11

On a fresh install, copying the [default config](https://raw.githubusercontent.com/jwilm/alacritty/master/alacritty.yml) into `~/.config/alacritty/alacritty.yml` produces the following error:

`Problem with config: invalid type: map, expected a string; using default value`

I would fix the config if I had even the slightest hint at which value was causing the error. #2752 would help, printing out the incorrect value, etc.

**Comment by kchibisov** [comment]
It seems like you've grab the config for the latest master. Please grab the one for your version from the release page or let `alacritty` generate one for you (just delete config in `.config/alacritty/alacritty.yml` and `alacritty` will generate one for you there).

**Comment by hamptokr** [comment]
Ah that did it, thanks!
