### ISSUE TITLE
0 Width Vertical Block Selections

### ISSUE THREAD

**Issue by nixpulvis** [jwilm/alacritty#2789]
I've uncovered a bug while testing #2719 (as noted there). Basically we shouldn't allow empty vertical block selections of width 0. This can cause a situation where it looks like there is no selection, but in fact there is one. Since a selection prevents actions like clicking a URL, this can lead to strange user interactions.

![block-selection-url-bug-2019-09-07_00 03 52](https://user-images.githubusercontent.com/715947/64469624-18a3b600-d103-11e9-91bb-0f7f675d2fda.gif)

To reproduce on master, create a 0 width N height block selection, and then attempt to click a URL. I believe a proper fix for this is to disallow 0 width block selections, similarly to how other selections disappear.

**Comment by chrisduerr** [comment]
Fix was extremely simple, let me know if https://github.com/jwilm/alacritty/pull/2793 solves all the problems you've found!
