### ISSUE TITLE
OS X: Fullscreen has text cut off at bottom of screen

### ISSUE THREAD

**Issue by aaronarduino** [jwilm/alacritty#279]
### System:

- OS X El Capitan
- Mac Mini (Late 2014)
- **Graphics:** Intel Iris 1536 MB

### Config:

Only thing changed was DPI and Font Size everything else is default.

- **DPI:** 93.0 ( x and y )
- **Font Size:** 17.0

### Alacritty version:

commit ec339f728a18657f3b47af55fd2afed56ed39a26

### Screenshot

![alacritty_bug](https://cloud.githubusercontent.com/assets/321920/21813537/36c4386e-d71c-11e6-952e-ef37659bab64.png)

**Comment by DanielSaunders** [comment]
I would like to add that I am having this exact same problem, but with Ubuntu. This is a fresh version of 16.10 that I installed a few hours ago. I have a GeForce GTX 770 and have not changed the DPI. 

When I use a font size of 11 (the default), I have no problem in fullscreen. However, when I use a font size of 10, I get the same problem as shown in the screenshot. I am using commit https://github.com/jwilm/alacritty/commit/4fb7801ba3515922e3dbb8b27c1c28ec2efaf22b

**Comment by jwilm** [comment]
Sounds like a bug calculating number of cells to use

**Comment by andersevenrud** [comment]
I'm also experiencing this in Xfce when using the `Hide title of windows when maximized` accesibility option. I'm using this because I cannot enter full-screen mode, and it is the closest thing I could get.

I increased my font-size by `.5` and the problem went away.

**Comment by d3rrial** [comment]
I'm experiencing the same thing on Arch with i3wm.

There are a few pixels too many at the top and a few too few at the bottom.

I'm using fontsize 13 with Ubuntu Mono

**Comment by OJFord** [comment]
I don't think it's alacritty's fault @jwilm - I've had to modify the margins in other apps, e.g. Atom editor when I used it for a while when full-screen, I think macOS just does this annoyingly.

**Comment by jwilm** [comment]
Resolved in 9316771f64842533181cfb04a27aa9ae809cc435
