### ISSUE TITLE
Strange characters produced for keys configured in default key_bindings

### ISSUE THREAD

**Issue by varac** [jwilm/alacritty#2797]
I'm using Ubuntu 19.04, Wayland (Sway 1.2), and alacritty 0.3.3 installed as deb from the ppa.

Some default  configured key_bindings produce strange characters pasted, i.e. when I press Super+F5 these char sequence gets pasted in alacritty: `;3~`. Same for Super+F6 up to Super+F12. I also do get other weird sequences with other key_bindings.

I guess something doesn't properly work with escaping ?

**Comment by kchibisov** [comment]
What's exactly weird for you here?

The default bindings for `Super` + `F1-F12` are `CSI 1;3P CSI 1;3Q CSI 1;3R CSI 1;3S CSI 15;3~ CSI 17;3~ CSI 18;3~ CSI 19;3~ CSI 20;3~ CSI 21;3~ CSI 23;3~ CSI 24;3~` respectively. The sequence that was pasted to your shell could be a bit different though (in terms of chars thing). This thing was pasted to fish shell on `Super` + `F1` press: `[1;3P`.

You can try running `cat` without args and try pressing your bindings.

FWIW I'm running the same compositor as you are.

**Comment by chrisduerr** [comment]
Yeah, the escapes for Super + F1-12 are going to change in #2785, however in general this is mostly intentional. We send these escapes to tell terminals about special characters and they're just not handled in some applications which leads to these escapes showing up.

**Comment by varac** [comment]
@kchibisov This is what I get with `cat` and `Super+F1` up to `Super+F7`:

`❯ cat
^[[1;3P^[[1;3Q^[[1;3R^[[1;3S^[[15;3~^[[17;3~^[[18;3~`

I'm just wondering about the purpose of such keybindings, but if they get removed anyway I don't need to understand...

**Comment by varac** [comment]
Hugh, I do think this is a bug though.
Even when trying to setup a custom keybinding like this:

`- { key: F8,            mods: Super,    command: {program: "/home/varac/bin/dark.sh"} }`

I get a `3~` pasted in my terminal each time I press `Super+F8` (dark.sh does gets executed fine).

**Comment by chrisduerr** [comment]
@varac That has been fixed on the latest master.

**Comment by varac** [comment]
@chrisduerr Unfortunatly not. I just compiled latest master and both issues (https://github.com/jwilm/alacritty/issues/2797#issuecomment-531156374 and https://github.com/jwilm/alacritty/issues/2797#issuecomment-531158372) still remain for me.

**Comment by chrisduerr** [comment]
The first one is not a bug, this is intended.

Could you post your configuration? The second one might just be a configuration issue.

**Comment by varac** [comment]
Ok, here are the steps to reproduce with lastest master:

```
wget https://raw.githubusercontent.com/jwilm/alacritty/master/alacritty.yml -O ~/.config/alacritty/alacritty.yml
echo '  - { key: F8,       mods: Super,   command: {program: "/usr/bin/gedit"} }' >> ~/.config/alacritty/alacritty.yml
```

And then press `Super+F8`. `gedit` starts, and `;3~` gets pasted on the command line.

**Comment by chrisduerr** [comment]
You should remove the old binding before adding the new one.

**Comment by varac** [comment]
@chrisduerr Ah, my fault - but is this intended behaviour that muliple definitions of the same key binding append each other ? I though they rather replace the preceding.

Could you please document those default keybings which are not self-explanatory ? Thanks !

**Comment by chrisduerr** [comment]
The default keybindings are listed in the default configuration. What they do is presented there exactly. If you want to understand what these mean, you'll have to check out the terminal specifications listed in our wiki, but generally they just tell the shell which key has been pressed.

And I'm not sure what you'd expect when multiple keybindings are defined, we have to be able to make it possible to define multiple bindings for the same key. If you don't want any of the default bindings, there's documentation on how to get rid of them in the default config.

I don't think there's any need for action here, everything is working exactly as I would expect it to.

**Comment by nixpulvis** [comment]
Actually I think I've missed an update to our default `alacritty.yml` when I made a batch of changes to the comments a while back.

https://github.com/jwilm/alacritty/blob/1067fa609b6a5a0017814cb96d8b21b39b2f83f2/alacritty.yml#L537-L539

The first sentence of this paragraph seems wrong now.

**Comment by chrisduerr** [comment]
@nixpulvis What about that is incorrect? It seems right to me.
