### ISSUE TITLE
Nerd fonts not showing icons

### ISSUE THREAD

**Issue by giovannigiordano** [jwilm/alacritty#2804]
I'm using alacritty 0.3.3 on MacOS and using FuraCode Nerd Font.
The icons are not showing up, but only for Alacritty, in iTerm the icons are shown correctly.

Alacritty
![Alacritty](https://i.imgur.com/erSVPqp.png)

iTerm
![iTerm](https://i.imgur.com/dvTNK4U.png)

**Comment by kchibisov** [comment]
It seems like you’ve misspelled font name in alacritty, since fonts are different.

**Comment by giovannigiordano** [comment]
@kchibisov it's not a mispelling problem, I have tried all the combinations to make working the fonts, but it's not working.

**Comment by kchibisov** [comment]
And you've actually got correct font in the end? I was using the same font on macOS without any problem in the past. I was judging by the screenshot you've posted, since fonts are different on it. In iterm it's Fira, but alacritty has Menlo or something.

**Comment by giovannigiordano** [comment]
@kchibisov I'm sorry, the name was correct, but I had an hash in config file which breaks it. Sorry.

**Comment by barrydevp** [comment]
@giovannigiordano how do you fix this problem?

**Comment by Goralive** [comment]
> @giovannigiordano how do you fix this problem?

I'm create a config for alacrity vim ~/.config/alacritty/alacritty.yml and there specified a font that I get. In my case on macOS I opened 'Font Book' and search for nerd fonts. So I specified in YAML 
`font:
  normal:
    family: Hack Nerd Font Mono
`

**Comment by barrydevp** [comment]
@giovannigiordano late reply :)), I have switched to kitty instead.

**Comment by ical10** [comment]
> 

Can confirm that this works for me. Thanks.

**Comment by ical10** [comment]
> > @giovannigiordano how do you fix this problem?
> 
> I'm create a config for alacrity vim ~/.config/alacritty/alacritty.yml and there specified a font that I get. In my case on macOS I opened 'Font Book' and search for nerd fonts. So I specified in YAML `font: normal: family: Hack Nerd Font Mono `

This works for me. Thanks.

**Comment by burakhanaksoy** [comment]
I had the same issue and finally had it working using Hack Nerd Font Mono
