### ISSUE TITLE
some question occur while using two screen

### ISSUE THREAD

**Issue by fgheng** [jwilm/alacritty#2805]
Which operating system does the issue occur on?
arch linux
If on linux, are you using X11 or Wayland?
x11 and use nvidia

---
problem show in the gif, if i has two screen, some problem occured

![Peek 2019-09-17 20-13](https://user-images.githubusercontent.com/50551377/65040763-b7dc6f00-d987-11e9-995c-cf8fecd7661d.gif)

**Comment by fgheng** [comment]
this gif is screened in second screen

**Comment by chrisduerr** [comment]
If I understand your issue correctly, it seems like your issue is the same as https://github.com/jwilm/alacritty/issues/1631.

If you have Rust installed, you can give #2438 a shot and let me know in #1631 if that helps.
