### ISSUE TITLE
If an SGR escape sequence sets the background color to the terminal background color, it is not opaque

### ISSUE THREAD

**Issue by xPMo** [jwilm/alacritty#2814]
> Which operating system does the issue occur on?

Arch Linux

> If on Linux, are you using X11 or Wayland?

Wayland

---

I realized this when a [truecolor program](https://gitlab.com/xPMo/snippets/blob/master/c/truecolors.c) I wrote appeared with a noticeable hole in it. Because I use opacity in my terminal, I can see the background through it, instead of it being completely opaque due to the escape code.

Example using `0x303030` background with opacity `0.0`:

![iExample](https://i.imgur.com/9NgL3Am.png)

As you can see, when `\e[48;2;48;48;48m ` is printed, instead of a solid grey, it is completely transparent.

**Comment by kchibisov** [comment]
It’s a known thing and not a bug, since it was done intentionally iirc. The main problem with this behavior is that it’s not documented in config file. This thing exist for achieving transparency in alt-screen apps like alsamixer/vim/mutt etc.

If you dont want this behavior just change background color a bit.

**Comment by xPMo** [comment]
> This thing exist for achieving transparency in alt-screen apps like alsamixer/vim/mutt etc.

Ah, I'm used to urxvt, which does not do this.  I understand why this behavior exists; a program explicitly setting the background to the same as its default color probably has the intention of resetting the background.

The program I was using broke this assumption, since it intends to print arbitrary colors. [`pixterm` is another program](https://github.com/eliukblau/pixterm) which will have this issue; if an image is printed which happens to have a pixel match the background color, a noticeable hole will appear.

I would like to disable this behavior completely for this reason, or even better change it so that only the 16-color black causes this. I'll try and patch this myself, so leave this issue closed unless someone else wants this behavior.

**Comment by kchibisov** [comment]
> I would like to disable this behavior for this reason, or even better change it so that only the 16-color black causes this. I'll try and patch this myself, so leave this issue closed unless someone else wants this behavior.

As I said, just slightly change background your color, you're already using opacity setting, so you shouldn't notice it. Otherwise you have to change how alacritty rendering works.

**Comment by xPMo** [comment]
> slightly change your background color ... you shouldn't notice it

If I'm understanding you correctly, you're talking about something like setting `black: '0x000020'` and `background: '0x00001F'`, right? That way `\e[40m` will display in `#000020`, and not trigger the opacity setting.


This won't help if I want to use `pixterm` or a similar program.  If my background is `0x000020`, then I'll see a hole whenever pixterm displays an image with `#000020`. If I slightly change it to `0x00001F`, then I'll see a hole whenever pixterm displays an image with `#00001F`.  I could view any image with any colors in pixterm, so any background will cause this papercut somewhere.

**Comment by chrisduerr** [comment]
While setting the color to the background color should give transparency, specifying a truecolor should not cause any transparency. @nixpulvis is already working on a patch to fix this, so hopefully we can get the best of both worlds here again (seems like there was a regression in e964af8a5ea390d96667e80873060d33079134fd).
