### ISSUE TITLE
Wrong alt-i key esc seq in macOS

### ISSUE THREAD

**Issue by vbauerster** [jwilm/alacritty#2816]
I'm having trouble with following `alt-i` mapping in macOS.
```
  - { key: I,         mods: Alt,       chars: "\x1bi" }
```
following is `cat` output when pressing `alt-i` followed by `shift q`:
```
^[i^Q
```
The problem is that there is unnecessary `^` put in between `i` and `Q`.
`iTerm2` correctly outputs `^[iQ` by the way.
Extra `^` gets inserted with any alphabetical letter right after `alt-i`.
Because of this issue I cannot use `kakoune` text editor inside alacritty.

**Comment by vbauerster** [comment]
I forgot to mention, that I've built alacritty from master 856cddc

**Comment by chrisduerr** [comment]
Do you have `alt_send_esc` enabled or disabled? And does changing it help?

Also are we talking about a literal `^`, or about the terminal escape sent when pressing control and a button?

And I'd assume you're letting go of alt in between keys?

**Comment by vbauerster** [comment]
`alt_send_esc` didn't work for me, I mean with default config where it's enabled, I had diacritic letters instead of esc seq. So I decided to map manually in config then.

I get same result `^[i^Q` with `alt_send_esc` enabled or disabled, changing it doesn't help.
I don't press any control after `alt-i` it gets inserted with any letter.

**Comment by vbauerster** [comment]
I have to mention that `^` gets inserted once after `alt-i`, next letter is ok. For example pressing `alt-i` followed by `qq` outputs `^[i^qq`, should `^[iqq`.

**Comment by chrisduerr** [comment]
How exactly are you testing which characters are received? Do you use Ctrl+V/cat -v or something entirely different?

**Comment by vbauerster** [comment]
First I noticed that some `kakoune`'s shortcuts didn't work, where they work in iTerm2.
Then I simply type `cat` and press this shortcut in order to see what is the output. I used stardard `cat` command available in macOS command line.

**Comment by vbauerster** [comment]
Looks like it's the same issue as in #2017
