### ISSUE TITLE
Remove automatic config generation

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#2818]
Alacritty can work without any configuration file being presented, so generating one for user in `$HOME/.config/alacritty/alacritty.yml`(1) by default is a bad practice, since users don't expect alacritty to generate configuration file for them (just look at the number of issues with default config, most of the time it's being obtain from github.com etc). Moreover some users are running Alacritty without any additional configuration, so they don't need it anyway. In addition, our config file is a big YAML file and lots of it sections are optional, so advertising default config is bad for migration.

I'm proposing to remove automatic config generation entirely. This approach has a drawback of forcing users to obtain *right* config from external resources (e.g. github.com), however we can add command line option to generate default configuration file and put it in specified path (user have to put generated file to a proper location themself).

(1) This is an example for macOS/Linux systems, the same thing applies to Windows.

**Comment by chrisduerr** [comment]
> we can add command line option to generate default configuration file and put it in specified path

I'm not 100% sure if we should do that tbh, other than that I think I agree.

macOS/Windows users who do not have a package manager will likely have to visit github anyways, so the default config is right there.

On Linux, I think shipping the default config with the package manager seems reasonable, similar to what something like sshd_config does.

The primary question would be if such a config should have all fields commented out by default or not. The advantage of commenting options out is that it makes it very obvious which configuration options have been changed by the user, so migrating to a new config is a little easier.

**Comment by kchibisov** [comment]
> I'm not 100% sure if we should do that tbh, other than that I think I agree.

The goal is to provide default config for your version, you have always a change to grab a wrong one from github.

> On Linux, I think shipping the default config with the package manager seems reasonable, similar to what something like sshd_config does.

iirc Arch Linux is shipping our default config in `/usr/share/doc/alacritty/example/alacritty.yml` and I think it's the right place for it. I'm against of adding config to `/etc/*` and reading anything from it.

I think our default config should have all fields commented out, but we should change our tests then to handle such thing properly (we're relying on things being uncommented atm).

**Comment by chrisduerr** [comment]
> The goal is to provide default config for your version, you have always a change to grab a wrong one from github.

In the github releases where people are likely to download their versions, the configuration file is always archived for each specific release. This was specifically setup for this purpose.

> iirc Arch Linux is shipping our default config in /usr/share/doc/alacritty/example/alacritty.yml and I think it's the right place for it. I'm against of adding config to /etc/* and reading anything from it.

Yeah, seems like it does and I agree with everything you said. This is not about reading it from the systemwide directory, but just about providing it as documentation. In this case `/usr/share/doc` is even better, though I wasn't aware that Arch was commonly using this. So that sounds perfect for us.

> I think our default config should have all fields commented out, but we should change our tests then to handle such thing properly (we're relying on things being uncommented atm).

Yeah, the biggest issue with having stuff commented out is that we cannot make sure the config is correct anymore by parsing it and checking it against the default. However I think commenting things out by default is the best choice and it's what other configuration files do too.

**Comment by NickeZ** [comment]
> In this case /usr/share/doc is even better, though I wasn't aware that Arch was commonly using this.

Same in debian-based distros, you'll find the default config for a bunch of applications there.

**Comment by nixpulvis** [comment]
> I think our default config should have all fields commented out, but we should change our tests then to handle such thing properly (we're relying on things being uncommented atm).

I think the only things that should be commented out are A) incompatible examples of setting values with uncommented values or B) platform specific values.

**Comment by chrisduerr** [comment]
> I think the only things that should be commented out are A) incompatible examples of setting values with uncommented values or B) platform specific values.

Why do you think that? I feel like for a configuration file at least on Linux it's pretty standard to have everything commented out, because it allows checking which options have manually been changed or not when migrating.

**Comment by kchibisov** [comment]
All things commented out is very good idea for config migration and managing stuff, since your config will likely has minimum amount of uncommented section.

**Comment by nixpulvis** [comment]
> on Linux it's pretty standard to have everything commented out ...

Yea fair enough. :+1: 

I was just imagining users copying this file, un-commenting a few things, and leaving massive amounts of "cruft" around in their `~/.config/alacritty/alacritty.yml` file. Which I suppose is something many people would actually consider a feature... though I'd always rather refer to the `/usr/share` template personally.

**Comment by chrisduerr** [comment]
> I was just imagining users copying this file, un-commenting a few things, and leaving massive amounts of "cruft" around in their ~/.config/alacritty/alacritty.yml file. Which I suppose is something many people would actually consider a feature...

I think even without having this commented out, this is an issue though. It's just that the unnecessary stuff isn't commented out there, but behavior is the same.

I'm all for encouraging minimal configuration files though and I think not spawning a config at all is a good first step.

**Comment by waynr** [comment]
Just to add a dissenting voice, I found the automatic config file generation particularly useful. The first thing I wanted to do when I tried Alacritty the other day was learn what settings I could tweak, but the only related documentation on the github README tells me where Alacritty looks for its configuration files and that one is generated automatically. Great -- all I have to do is look at the automatically-generated config.

If this is no longer going to be the case, where will users look to figure out how to configure Alacritty? I don't think it's a good idea to leave it up to random config files found littered about the internet since those are inevitably going to be specific to different versions of Alacritty.

**Comment by kchibisov** [comment]
> If this is no longer going to be the case, where will users look to figure out how to configure Alacritty? I don't think it's a good idea to leave it up to random config files found littered about the internet since those are inevitably going to be specific to different versions of Alacritty.

You should always grab your config file from `release` page on GitHub (in case you're installing it from GitHub, otherwise from your package). We'll add notes on where to get your config file. With automatic config file generation you're lucky enough to find it. I wasn't able to find it myself on Windows for e.g. and I don't even remember it's initial location (was using `alacritty -v` to get location info).

**Comment by kchibisov** [comment]
> But the only related documentation on the github README tells me where Alacritty looks for its configuration files

"There is a default alacritty.yml at the Git repository root." - line from our README.

**Comment by chrisduerr** [comment]
> the only related documentation on the github README tells me where Alacritty looks for its configuration files and that one is generated automatically

The configuration file is right there in the repo tree next to the README, so it really shouldn't be an issue I think. Ideally people would look at the config file for their specific release of course, but usually even that's not a huge issue.

And of course our readme documentation should be updated to point out where to find the configuration file for the release you're using. But it's all there already, if anything needs to be changed it's only documentation pointing the user in the right direction.

**Comment by nixpulvis** [comment]
I think we need a solid plan for how to get the template configuration shipped with alacritty by the various package managers.

The two main issues I see are:

1. Will package managers really all make this change?
2. How can we point to this location in our man/help info? Would something like "Check /usr/local/share/ or similar" be good enough?

Alacritty can be aware of the `XDG_DATA_DIRS` location which, unless I'm misinterpreting things, is the correct location. But even still, I'm not sure I'd want alacritty itself to create a file for me. This is **really** something I expect my package manager to do.

**Comment by chrisduerr** [comment]
> Will package managers really all make this change?

Why wouldn't they? And they don't need to, it's just a nice thing to have.

> How can we point to this location in our man/help info? Would something like "Check /usr/local/share/ or similar" be good enough?

I don't think we necessarily need to link to it in the manpage. I don't think we do right now?

> Alacritty can be aware of the XDG_DATA_DIRS location which, unless I'm misinterpreting things, is the correct location.

How is this related to `XDG_DATA_DIRS`? They aren't really related to configuration at all, they're for application data, just like the name suggests.

**Comment by travankor** [comment]
As a new alacritty user, I find that the three most annoying issues with the configuration are:
1) The default config is too bloated (this issue, sort of). Having lots of commented out options is also annoying, so ideally only really important things are shown as commented out (if at all). The github page can have a detailed, annotated config (or a website/wiki page for documentation), but I would like the shipped config (if one is shipped at all) to be minimal (ie: principle of sane defaults).
2) Nested configuration (and forced indentation). Alacritty isn't complex enough for nested configuration IMO.
3) Alacritty gives poor warning diagnostics when you have errors in your config (ie: wrong indentation).

**Comment by nixpulvis** [comment]
@travankor this issue is explicitly about your first point. And we're deciding on how best to remove the default config altogether. So you'd have no bloat other than what you've added. The reference `alacritty.yml` will still contain a (more or less) complete reference.

Hopefully this will help address some of your issues. As for 2, well we may disagree, and for 3, I couldn't agree more, and personally dislike the way YAML works in general. But we're unlikely to change these things in the near future.
