### ISSUE TITLE
support for "disable line wrap" escape sequences

### ISSUE THREAD

**Issue by oconnor663** [jwilm/alacritty#282]
From this list: http://www.termsys.demon.co.uk/vtansi.htm

```
Reset Device		<ESC>c
    Reset all terminal settings to default.
Enable Line Wrap	<ESC>[7h
    Text wraps to next line if longer than the length of the display area.
Disable Line Wrap	<ESC>[7l
    Disables line wrapping.
```

Very understandable if obscure ANSI escape sequences aren't high on the priorities list yet :)

For examples of apps using these codes in the wild, see [`buck`](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/util/Ansi.java#L58-L59) and [`peru`](https://github.com/oconnor663/peru/blob/master/peru/display.py#L27-L28). An easy-to-repro peru example would be:

```bash
$ pip install peru  # in a virtualenv is fine
...
$ git clone https://github.com/oconnor663/dotfiles
...
$ cd dotfiles
$ peru sync
... [fancy output]
$ git clean -dfx && peru sync  # to clear the cache and see the whole thing again
... [fancy output]
```

With nowrap support, the fancy output looks like [this gif](https://github.com/buildinspace/peru#peru---) made in gnome-terminal. Without support, and with a narrow enough terminal, it overflows the line and leaves a bunch of junk above the prompt like this:

![image](https://cloud.githubusercontent.com/assets/860932/21825406/987a0d10-d751-11e6-9975-4b8fb6f38991.png)

**Comment by oconnor663** [comment]
I'd actually be really happy to work on this myself, if someone had time to point me to the places that would need to change.

**Comment by mbrumlow** [comment]
I put a PR up (sorry) I did not realize you wanted to work on this, only read the top :/

**Comment by jwilm** [comment]
Thanks for the repro @oconnor663. Looks like this is fixed on master thanks to @mbrumlow.

**Comment by oconnor663** [comment]
Works great! Thanks @mbrumlow!
