### ISSUE TITLE
Use $HOME variable in alacritty.yml in shell -> program

### ISSUE THREAD

**Issue by jonlorusso** [jwilm/alacritty#2821]
Which operating system does the issue occur on? MacOS

I share my alacritty.yml across multiple machines, each with a different $HOME dir.  My shell.program happens to be `fish`, but due to the fact that I am using nix, this binary is installed in `$HOME/.nix-profile`, rather than /usr/local/bin. 

I see that the unix tty code [sets the HOME](https://github.com/jwilm/alacritty/blob/5d173f6df3b20308eb318cef4b58147b2197d5f9/alacritty_terminal/src/tty/unix.rs#L191) variable when invoking shell.program, but it doesn't seem to expand that variable when I specify my program as follows:

```
shell:
  program: /home/user1/.nix-profile/bin/fish
  #    args:
  #  - --login
```

Is it possible to reference home from within alacritty.yml?  I could create a symlink, but I'm reluctant to do so. 

Thanks!

**Comment by chrisduerr** [comment]
The program is a path to an executable and not wrapped in a shell script. If you want shell script expansion, please start a shell script around your program like this:

```
shell:
  program: bash
    args:
     - -c
     - $HOME/.nix-profile/bin/fish --login
```

Though the far better solution would be to just add this directory to your $PATH. If there's an executable you want to be able to open from arbitrary locations, using the full path usually isn't ideal. But if you add this to your $PATH everywhere you can just use `fish` and you're good to go. That's much, much easier and will likely save you a bunch of trouble anyways.
