### ISSUE TITLE
Support for startup notification protocol

### ISSUE THREAD

**Issue by aalhitennf** [jwilm/alacritty#2824]
Which operating system does the issue occur on?
linux

If on linux, are you using X11 or Wayland?
X11

Looks like alacritty doesn't support freedesktops [startup notification protocol](https://www.freedesktop.org/wiki/Specifications/startup-notification-spec/).

This causes problems i.e. in window managers which allows you to spawn programs with custom rules.

**Comment by nixpulvis** [comment]
(Let it be known, I'm in a particular mood ATM)

I'm a bit frustrated by the existence of this spec altogether. This is mainly so the desktop environment (I don't even use one) can make a little pinwheel to tell you the application you opened is in fact opening... This alone is madness in my humble opinion. An application that can't open in time to at least indicate it's own status has a **performance bug**! Furthermore, let's look at this spec:

```
  DESKTOP 

          the desktop on which the application should appear, 
          counting from 0, as in _NET_WM_DESKTOP. However, 
          this value should never override a _NET_WM_DESKTOP
          property set on window that's being mapped.
          This desktop is relative to the screen provided by 
          the SCREEN key.
```

Interesting, my window manager *manages* to do this without asking anything of my applications:

```
# ~/.config/i3/config
assign [class="Alacritty"] 2
```

Then there's something about preventing user interaction for some time after opening the application:

```
  TIMESTAMP

          X server timestamp of the user action that caused this
          launch. For example window manager that doesn't allow
          stealing of focus by newly mapped windows while the user
          works in an application can use this timestamp for windows
          that have matching _NET_STARTUP_ID property if they don't
          have any _NET_WM_USER_TIME property set or if it's older.
          See the description of _NET_WM_USER_TIME in the WM spec
          for details.
```

Shouldn't you wait to open an application until you're ready to use it? What horrible Adobe products are you trying to open over there?

OK, enough of my bashful ranting.

-----

Honestly I'm not sure if we'll decide to support this or not. We have made some changes to support this overly invasive environment before (see #2525), but IDK about this.

@aalhitennf can you be more specific about what problems this is causing you, so we can accurately asses how bad things are without this extra functionality?

**Comment by aalhitennf** [comment]
Thanks for your time and answer. 

I use awesomewm and it has ability to give new client/window rules via startup notification protocol. https://awesomewm.org/apidoc/libraries/awful.spawn.html -> Spawning applications with specific properties.

This i.e. allows spawning window in floating mode even global setting is set to tiling. In my case super+return should open alacritty normally and it gets tiled, super+shift+return to open alacritty in floating mode. Currently any of these spawn rules don't work with alacritty.

**Comment by kchibisov** [comment]
You can easily achieve this in by writing rules and starting `alacritty` with a different `class`. (awful.rules.rules) and (alacritty --class "Alacritty-floating")

**Comment by aalhitennf** [comment]
@kchibisov thanks, that worked!  awesomewm rule needed to be based on instance:

```
{ rule = { instance = "Alacritty-floating" },
  properties = { floating = true } }
```
because --class changes classname, not class:
`WM_CLASS(STRING) = "Alacritty-floating", "Alacritty"`

**Comment by kchibisov** [comment]
You can try passing alacritty --class hello,hello

**Comment by chrisduerr** [comment]
I can see how someone might want to know when Alacritty is initialized, though I don't see any concrete usecase for this. As pointed out, the issue mentioned here is better solved with an alternative solution.

For now I'm open to collect feedback on this, though unless there's a good practical reason to support it I don't really see any need to step to action or accept PRs on this matter. So feedback would be much appreciated if anyone is interested in seeing this land in Alacritty.
