### ISSUE TITLE
Incompatible with gnome shell Clipboard Indicator

### ISSUE THREAD

**Issue by kevinhwang91** [jwilm/alacritty#2825]
Using Linux X11.

Clipboard indicator is a clipboard manager in gnome. It works fine in other applications but not Alacritty.

When switching clipboard content in Clipboard Indicator, Alacritty can't paste the updated clipboard content. It seems nothing happens in Alacritty(paste empty content).

**Comment by chrisduerr** [comment]
Which version of Alacritty are you running?

**Comment by kevinhwang91** [comment]
> Which version of Alacritty are you running?

0.3.3-3

**Comment by chrisduerr** [comment]
Could you try to run the following diff and tell me if it prints anything to stdout when trying to paste?

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 2e8fd4d..3c0cb01 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -14,3 +14,4 @@ incremental = false
 
 [patch.crates-io]
 servo-freetype-sys = { path = "servo-freetype-proxy" }
+x11-clipboard = { git = "https://github.com/chrisduerr/x11-clipboard" }
```

**Comment by kevinhwang91** [comment]
> Could you try to run the following diff and tell me if it prints anything to stdout when trying to paste?
> 
> ```diff
> diff --git a/Cargo.toml b/Cargo.toml
> index 2e8fd4d..3c0cb01 100644
> --- a/Cargo.toml
> +++ b/Cargo.toml
> @@ -14,3 +14,4 @@ incremental = false
>  
>  [patch.crates-io]
>  servo-freetype-sys = { path = "servo-freetype-proxy" }
> +x11-clipboard = { git = "https://github.com/chrisduerr/x11-clipboard" }
> ```

I follow your patch and build the source code manually. It generates the target directory and then I run the bin whose name is alacritty.
Unfortunately, the result is the same as what I describe above and the stdout outputs nothing when pasting.

**Comment by chrisduerr** [comment]
>  Unfortunately, the result is the same as what I describe above and the stdout outputs nothing when pasting.

Thanks, so this is unrelated to #2811.

You're running fully on X11 though, right? No X11/Wayland combination?

Also did the 0.3.2 version still work for you?

**Comment by kevinhwang91** [comment]
> > Unfortunately, the result is the same as what I describe above and the stdout outputs nothing when pasting.
> 
> Thanks, so this is unrelated to #2811.
> 
> You're running fully on X11 though, right? No X11/Wayland combination?
> 
> Also did the 0.3.2 version still work for you?

Yes, I'm running fully on X11.

I downgrade the 0.3.2-2 version and switch clipboard content in Clipboard Indicator, Alacritty still can't paste the updated clipboard content. But the stdout outputs the message "Error: target STRING not available".

**Comment by chrisduerr** [comment]
> I downgrade the 0.3.2-2 version and switch clipboard content in Clipboard Indicator, Alacritty still can't paste the updated clipboard content. But the stdout outputs the message "Error: target STRING not available".

That's extremely strange, because it means that not only Alacritty is having this issue, but a completely separate program (xclip) also can't read from the clipboard (or at least it thinks it's empty).

Which programs have you tested this on? Exclusively GTK applications? Have you tried non-GTK terminal emulators like XTerm or URxvt?

**Comment by kevinhwang91** [comment]
> > I downgrade the 0.3.2-2 version and switch clipboard content in Clipboard Indicator, Alacritty still can't paste the updated clipboard content. But the stdout outputs the message "Error: target STRING not available".
> 
> That's extremely strange, because it means that not only Alacritty is having this issue, but a completely separate program (xclip) also can't read from the clipboard (or at least it thinks it's empty).
> 
> Which programs have you tested this on? Exclusively GTK applications? Have you tried non-GTK terminal emulators like XTerm or URxvt?

Either GTK or QT(vlc and VirtualBox, etc.) applications work fine. 

I had tested some terminal emulators.

Gnome-terminal and Termite work fine. The result of Xterm and Urxvt and Kitty are the same with Alacritty.

**Comment by chrisduerr** [comment]
> Gnome-terminal and Termite work fine

Those are both the same terminal emulator basically, so that doesn't surprise me.

If neither XTerm, URxvt or Kitty can get this to work, I feel inclined to believe that this is not Alacritty's fault.

**Comment by aasutossh** [comment]
I was about to post this issue, ready to click on `Submit new issue`.
So, how do we go around it?
