### ISSUE TITLE
Windows 10: wrong Title bar color

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [jwilm/alacritty#2829]
Windows 10 with dark theme every program are black title bar except Alacritty.
![image](https://user-images.githubusercontent.com/38637268/65811020-8875ff80-e1dc-11e9-83cc-514a7e16fb61.png)

**Comment by chrisduerr** [comment]
Thanks for the report, I've created a tracking issue upstream:
https://github.com/rust-windowing/winit/issues/1193

**Comment by Cyl3el2Cleal2** [comment]
I just noticed all terminal programs have White title with official windows title bar exclude hyper.js
![image](https://user-images.githubusercontent.com/38637268/65822610-6ed2c780-e271-11e9-8abf-013961706e58.png)

**Comment by chrisduerr** [comment]
As long as other programs that are not made by Microsoft can recognize and use the dark theme, Alacritty should be able to do it too. I'm not super familiar with Windows, but a terminal emulator certainly isn't different from any other window in this regard.

**Comment by TheDecryptor** [comment]
For me the titlebar only goes white when Alacritty loses focus, but strangely enough I don't see that with the default command prompt windows (Powershell or cmd) unlike your screenshot.

**Comment by davidhewitt** [comment]
I had a hacking session and managed to get a beautiful dark title bar working in Alacritty. It was inspired by [this api call](https://github.com/microsoft/terminal/blob/9b92986b49bed8cc41fde4d6ef080921c41e6d9e/src/interactivity/win32/windowtheme.cpp#L42) used by Windows Terminal. Unfortunately, that flag `DWMWA_USE_IMMERSIVE_DARK_MODE` isn't in the official MSDN docs so I'm a bit nervous about adding support for it to Glutin, lest it break.

![image](https://user-images.githubusercontent.com/1939362/66231491-8b8e5580-e6de-11e9-9ecd-d097c220aa6e.png)

I propose we put in support for this directly in Alacritty for now, and I'll update the linked Glutin issue to watch out for the flag becoming permanent (maybe it'll happen with Windows 10 19H2 release?). We can revisit and tidy at that point.

**Comment by chrisduerr** [comment]
> Unfortunately, that flag DWMWA_USE_IMMERSIVE_DARK_MODE isn't in the official MSDN docs so I'm a bit nervous about adding support for it to Glutin, lest it break.

That seems interesting. There must be a way for applications which are not created with their Windows store stuff to use dark decorations, right? I can't imagine this would just be impossible.

> I propose we put in support for this directly in Alacritty for now, and I'll update the linked Glutin issue to watch out for the flag becoming permanent (maybe it'll happen with Windows 10 19H2 release?). We can revisit and tidy at that point.

I'm not sure if it makes more sense to add this in Alacritty first and then go through the process of upstreaming it and removing the code again. I really don't like windowing extensions living directly inside of Alacritty.

If this works and is suitable for 'production' use, then I'd propose it to winit. I don't see why we'd be more likely to add it than them?

**Comment by davidhewitt** [comment]
> That seems interesting. There must be a way for applications which are not created with their Windows store stuff to use dark decorations, right? I can't imagine this would just be impossible.

As far as I can tell from research online the Dark Mode support is pretty shoddy for win32 applications. Most articles talk about UWP apps using XAML, where your "Dark" theme is automatically used by Windows when appropriate. If this is the way Microsoft employees have built dark support into Windows Terminal, then I would infer this is the best they've got right now.

My caution about upstreaming is that if it's an undocumented API, there's more projects potentially affected if this undocumented API suddenly stops working.

I do however take your point that it's a lot of work to build into Alacritty then subsequently upstream. I'll submit a PR to winit and see how we go...

**Comment by chrisduerr** [comment]
Thanks for the work, linking the PR here would also be appreciated.

I see no reason why we wouldn't at least try to upstream it. They can make the decision if it's worth it or not themselves. If that doesn't work out, we can always try for an Alacritty solution after that.

**Comment by davidhewitt** [comment]
Upstream at https://github.com/rust-windowing/winit/pull/1217

The PR I've submitted would theme the title bar automatically, so if it lands, Alacritty won't need any code changes to support.

**Comment by davidhewitt** [comment]
The winit PR was merged yesterday, so after the next winit version bump (presumably to `0.20.0` after that releases) then we'll have this for free!
