### ISSUE TITLE
`˜` character get inserted in the prompt when using  `alt+n` when inside tmux

### ISSUE THREAD

**Issue by meain** [jwilm/alacritty#2830]
- OS : **macOS High Sierra**
- Version: **alacritty 0.3.3 (cc3e4d3)**

I use `alt+n` to switch windows in tmux. When I use `alt+n`, it does switch the windows, but it inserts and extra char `˜` into the prompt. I seems to only happen with `alt+n`.

I did test with other terminal emulators (kitty and iTerm). Those don't seem to have to this problem.

I have this in my config for `key_bindings`. My full config is available [here](https://github.com/meain/dotfiles/blob/master/alacritty/.config/alacritty/alacritty.yml)

```yaml
  - { key: N,         mods: Alt,       chars: "\x1bn"                      }
```

---

- [tmux config](https://github.com/meain/dotfiles/blob/master/tmux/.tmux.conf)

```
bind -n M-n previous-window
```

**Comment by chrisduerr** [comment]
Can you try out what alt+n does in a non-terminal application? I think this is just the way macOS handles inputting special characters, so this is related to #62.

> I have this in my config for key_bindings. My full config is available here

So things don't work even with that config option set?

**Comment by meain** [comment]
On non terminal application it inserts that character, but so does every other `alt+<key>`.

I tries using alacritty with that keybinding disabled, in that it just inserts that char without sending the input to tmux.

**Comment by chrisduerr** [comment]
> I tries using alacritty with that keybinding disabled, in that it just inserts that char without sending the input to tmux.

I'm not quite sure what you mean here. If I add that binding to Alacritty, it does not print the `~` anymore (as one would expect). Are you saying it sends **only** the `~` char in that case for you, without the escape?

**Comment by meain** [comment]
without the keybinding, it just sends that char. 
with the keybinding it changes my tmux window and sends the char

**Comment by meain** [comment]
also, ~ only gets printed once I type any other key (not a+<key>) when I have the keybinding in the config

**Comment by chrisduerr** [comment]
Ah, gotcha. This is tracked upstream in https://github.com/rust-windowing/winit/issues/768 and you'll be able to find a couple of other Alacritty issues linked there.

Closing this as a duplicate since we already have plenty of issues to track this.

**Comment by falood** [comment]
@meain 
I got the same issue, and I have a hack fix https://github.com/jwilm/alacritty/issues/2873
holp it's helpful
