### ISSUE TITLE
alacritty seems to have config issues when ssh'd by default

### ISSUE THREAD

**Issue by james-lawrence** [jwilm/alacritty#2838]
arch linux - fully up to date. wayland.

when sshing into server boxes using alacritty i run into a few errors.

setting the environment variable TERM=xterm seems to resolve the issues. having to set the environment variable is unexpected.

1. htop seems to choke trying to start alacritty?
```
~$ htop
Error opening terminal: alacritty.
```
2. systemd claims the terminal isn't fully functional
```
systemctl status nginx
WARNING: terminal is not fully functional
-  (press RETURN)
```

**Comment by chrisduerr** [comment]
> setting the environment variable TERM=xterm seems to resolve the issues. having to set the environment variable is unexpected.

Why is this unexpected? Alacritty uses the `alacritty` terminfo by default. So if you ssh into another machine, you'll have to install the Alacritty terminfo there too.

I don't do a lot of work over ssh myself, so I just got it aliased to `TERM=xterm-256color ssh`, but to get all features out of Alacritty you should install the terminfo on the remote host.

**Comment by james-lawrence** [comment]
yikes, TIL about terminfo. what a nightmare for everyone.

**Comment by chrisduerr** [comment]
That's one way to put it, yeah. There have been some discussions about a replacement, though it's difficult to replace something that has been around for so long.

**Comment by realSConway** [comment]
> I don't do a lot of work over ssh myself, so I just got it aliased to `TERM=xterm-256color ssh`, but to get all features out of Alacritty you should install the terminfo on the remote host.

How do I install terminfo on remote computer?
From https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo

If I run `tic -xe alacritty,alacritty-direct extra/alacritty.info` on remote computer I get a error:
```
-bash: tic: command not found
```

**Comment by kchibisov** [comment]
you should install tic, should come from ncurses package.

**Comment by BlueCannonBall** [comment]
I get `tic: extra/alacritty.info No such file or directory` when trying to install the terminfo on a Debian 9 server.

**Comment by contyk** [comment]
> I get `tic: extra/alacritty.info No such file or directory` when trying to install the terminfo on a Debian 9 server.

If you read the error message, you'll discover that the file does not exist. You need to be in your alacritty code checkout directory. Or specify the correct path to the terminfo file.

**Comment by BlueCannonBall** [comment]
This worked, thanks!

**Comment by ramonnr** [comment]
A workaround is using tmux on your host. Don't know why it works, but does the trick for me

**Comment by contyk** [comment]
It works because it sets you TERM to tmux.

**Comment by phiresky** [comment]
One-liner since you have to do this on every new server you connect to:

```
wget https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info && tic -xe alacritty,alacritty-direct alacritty.info && rm alacritty.info
```

**Comment by Nate-Wilkins** [comment]
If you don't want to set this for every host you connect to you can do this conditionally with the `.ssh/config` file.

```
Host 192.168.100.2
  PORT 22
  SetEnv xterm
  IdentityFile ~/.ssh/id_rsa
  IdentitiesOnly yes
```

I was thinking about writing something to copy over a compiled terminfo but it doesn't make sense if the remote machine compiles terminfos differently than yours...

**Comment by teunissenstefan** [comment]
Nobody seems to point out that this is unfeasible or even impossible if you work in a bigger company with a lot of servers, especially if you don't really have permission to install terminfo.

**Comment by james-lawrence** [comment]
@teunissenstefan the issue documents the problem and how to workaround it and the workaround works perfectly well even at larger companies. what its missing is how to *apply* the work around on your local system so it applies to remote hosts.

```
Host example.com
	SetEnv TERM=xterm
```

**Comment by fidelsalz** [comment]
... or just use another terminal when sshing, in my case I had konsole installed.

**Comment by JorenRothman** [comment]
I've created (with Chat Gippity help) an alias/function for ZSH.

```
# Function to check TERM and SSH with appropriate TERM value
ssh_dynamic_term() {
    local host="$1"
    shift

    local term_to_use="alacritty"

    # Check if alacritty terminfo exists on the remote host
    if ! ssh -q "$host" 'infocmp alacritty > /dev/null 2>&1'; then
        term_to_use="xterm-256color"
    fi

    # Use the determined TERM
    env TERM="$term_to_use" command ssh "$host" "$@"
}

# Alias to use the function
alias ssh='ssh_dynamic_term'

# Enable autocompletion for the ssh_dynamic_term function
compdef ssh_dynamic_term=ssh
```

PS: This could be terrible

**Comment by chrisduerr** [comment]
If you already have Alacritty installed, the best way is usually to just copy it over from the local machine.

**Comment by sgon00** [comment]
What's wrong by setting `TERM = "xterm-256color"` in `.alacritty.toml`? It should be the easiest solution.

**Comment by chiefMarlin** [comment]
> What's wrong by setting `TERM = "xterm-256color"` in `.alacritty.toml`? It should be the easiest solution.

Exactly what @sgon00 said, adding 
```
[env]
TERM = "xterm-256color"
```
 to alacritty.toml does the trick.

**Comment by rieje** [comment]
> What's wrong by setting `TERM = "xterm-256color"` in `.alacritty.toml`? It should be the easiest solution.

Literally in the first reply to this issue is the answer: 

> I don't do a lot of work over ssh myself, so I just got it aliased to TERM=xterm-256color ssh, **but to get all features out of Alacritty you should install the terminfo on the remote host.**

@sgon00 
@chiefMarlin

**Comment by Ehab-Ibrahim** [comment]
It's also possible to copy the `alacritty` terminfo from your local machine to the server using the following command:

```bash
infocmp -x alacritty | ssh YOUR-SERVER -- tic -x -
```

I found out about this method from `ghostty` docs:
https://ghostty.org/docs/help/terminfo#ssh
