### ISSUE TITLE
Running vi Changes Line Cursor to Block Cursor

### ISSUE THREAD

**Issue by AdamDanischewski** [jwilm/alacritty#2839]
Which operating system does the issue occur on?
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

If on linux, are you using X11 or Wayland?
`X11 `

I use a thin cursor - everytime I fire up `vi` when I exit the cursor is changed to a block cursor. 
![alacrit](https://user-images.githubusercontent.com/10157303/66067264-39e89e00-e519-11e9-87b4-8489f98f1cda.gif)

**Comment by kchibisov** [comment]
This is expected, terminal apps can set your cursor with escape sequence. You can setup your editor to change cursor back to normal or execute `reset`.

**Comment by chrisduerr** [comment]
Manually sending the escape `\e[0 q` on exit will fix this, but there's nothing we can do about this.

**Comment by AdamDanischewski** [comment]
> This is expected, terminal apps can set your cursor with escape sequence. You can setup your editor to change cursor back to normal or execute `reset`.

I suppose it is vi's fault, when I reset the terminal the block cursor remains: 
$> reset
Stays a block cursor. 
For now I use: `printf '\033[6 q'` (to put it back to a Line Caret / I-Beam).

**Comment by chrisduerr** [comment]
How do you set it to the I-Beam cursor by default? Does the escape I've commented earlier work? Might just be a configuration issue on your end.

**Comment by AdamDanischewski** [comment]
I set the I-Beam cursor in **~/.config/alacritty/alacritty.yml**: 
```
cursor:  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Beam

```
Escape sequence `\e[0 q` didn't work for me, maybe something is going on - `reset` also doesn't reset my cursor.

**Comment by kchibisov** [comment]
What's your terminfo (echo $TERM)?

**Comment by AdamDanischewski** [comment]
`screen` I'm using tmux

**Comment by kchibisov** [comment]
Are you properly overriding terminfo?

**Comment by AdamDanischewski** [comment]
Probably not, I just tried xterm and it's the same deal. Any suggestions?

**Comment by kchibisov** [comment]
Oh, I've forgot that you're running inside tmux(another terminal emulator), so it resets to whatever thing tmux likes, at least it seems so, since I can repro your issue with gnome-terminal + tmux. I'm not sure if we can do something about it in alacritty.

**Comment by AdamDanischewski** [comment]
I've turned off tmux for now and tried playing around - dumped the current terminfo db with infocmp and found `cnorm=\E[34h\E[?25h`

When I do, `tput civis` cursor disappears and then I `tput cnorm` or `reset` and cursor is back to I-Beam but if I do a vi I've got a block cursor and if I `tput cnorm` or `reset` my cursor stays on block. If I `tput civis` it disappears again but `reset` or `tput cnorm` put back the block cursor. 

Seems like vi does something to override my terminfo db. A useful [web page.](http://linuxcommand.org/lc3_adv_tput.php)

**Comment by chrisduerr** [comment]
Yeah, since `tmux` is a different terminal emulator basically, it doesn't know what the default cursor is for Alacritty. So resetting it with `CSI 0 q` might not behave as intended.

**Comment by AdamDanischewski** [comment]
If I set `TERM=tmux-256color` instead of `screen` it fixes the problem, my cursor stays I-Beam in nvim and after exiting. Not sure exactly what's going on but it looks like the TERMINFO for tmux-256color is telling nvim what cursor to use.

**Comment by chrisduerr** [comment]
> Not sure exactly what's going on but it looks like the TERMINFO for tmux-256color is telling nvim what cursor to use.

Neovim checks the `TERM` name (not terminfo capabilities) to determine if the reset cursor sequence is supported. I had to send a patch to get support for Alacritty itself, it's a bit suboptimal.

**Comment by fuadnafiz98** [comment]
### I found a solution that anyone can try 

* Create a folder in root dir `cursor-reset`

```bash
#!/bin/bash

printf '\033[6 q'
```

* Make it executable 

`sudo chmod +x ~/cursor-reset`


* Write this in the end of your `.vimrc` 

`:autocmd BufWinLeave * !~/cursor-reset %:p`

**Now each time you leave vim it will reset the cursor :)**

**Comment by bgrosse-midokura** [comment]
For me
```augroup RestoreCursorShapeOnExit
    autocmd!
    autocmd VimLeave * set guicursor=a:hor20-blinkwait400-blinkoff400-blinkon400
augroup END```
did it. You'll have to tweak `guicursor` to match alacritty's.

**Comment by SLAYER-CODE** [comment]
Fish:
For me in .vimrc
:autocmd BufWinLeave * !echo -e "\e[0 q"

**Comment by Lassebq** [comment]
Kitty resets cursor properly without any changes to neovim/vim, so why isn't it a bug? Pretty sure it is, imo

**Comment by kchibisov** [comment]
Log `-vvv`, if you don't see a `reset` on exit then it's not our bug.
