### ISSUE TITLE
Add support for saving window title on stack

### ISSUE THREAD

**Issue by daanjderuiter** [jwilm/alacritty#2840]
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
Observed on both

I noticed that when I am using either Vim or NeoVim in Alacritty, the titlestring remains active even after the editor has been closed. I also tested this for other terminal emulators but they all behaved as expected. This occurs both under X and Wayland, I have tested swaywm and i3-gaps. See also the attached video example. The dynamic_title setting is set to true. How could I modify my setup so that Alacritty's default title is restored after exiting Vim?

![alacritty-title](https://user-images.githubusercontent.com/7713825/66077774-ebf78880-e560-11e9-8d7c-08d6febdcb62.gif)

**Comment by chrisduerr** [comment]
> I noticed that when I am using either Vim or NeoVim in Alacritty, the titlestring remains active even after the editor has been closed.

All Alacritty does is update the title when an application requests it. If the application doesn't reset it on exit, there's nothing Alacritty can do. Alacritty itself has no idea about which application is running inside the shell.

Does any other terminal emulator behave differently?

**Comment by daanjderuiter** [comment]
I have quite a few terminal emulators installed on this machine - only Alacritty exhibits this behaviour. That combined with the fact that both vim and nvim have this issue lead me to file the issue here

**Comment by chrisduerr** [comment]
Which terminfo are you using? And does running `alacritty -vv` print any mentions of unsupported escapes?

**Comment by daanjderuiter** [comment]
I have alacritty-terminfo installed and am using the default `TERM` varaible. Running `alacritty -vv` gives no helpful messages, only lines saying `[2019-10-02 23:13] [DEBUG] [Unhandled CSI] action='t', args=[22, 0, 0], intermediates=[]` when opening or closing the editor.

**Comment by chrisduerr** [comment]
When leaving, do you get `23` as first parameter to `args` instead of `22`?

`CSI 22 ; 0` is used to push the window title on the stack and `CSI 23 ; 0` is used to pop it off again. Alacritty doesn't support any of these escapes, so that would likely be the issue.

However without `CSI 23 ; 0`, it will not correctly restore.

**Comment by daanjderuiter** [comment]
This is what I am getting:
![alacritty-title-vv](https://user-images.githubusercontent.com/7713825/66113792-c81e5c00-e5cd-11e9-9613-3a9cc7a7865b.gif)

**Comment by chrisduerr** [comment]
Yeah, if you look at the output, that's exactly what I'm talking about. You first get a `CSI 22 ; 0` and then a `CSI 23 ; 0` on exit.
