### ISSUE TITLE
MacOS - 'zsh: character not in range'

### ISSUE THREAD

**Issue by Timoses** [jwilm/alacritty#2848]
Which operating system does the issue occur on? MacOS Mojave 10.14.6

If I open Terminal and
```
printf '\u2388'
⎈           
```

In Alacritty I get:
```
printf '\u2388'
zsh: character not in range
```

Not sure what the source of this is.

**Comment by kchibisov** [comment]
What's your output of `locale`?

**Comment by Timoses** [comment]
Terminal:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Alacritty:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```


Looks suspicious ..

**Comment by kchibisov** [comment]
Would you mind trying to put `LC_CTYPE: "UTF-8"` in alacritty.yml `env` section?

**Comment by Timoses** [comment]
That does the trick. Thanks!

**Comment by kchibisov** [comment]
duplicate of #2566
