### ISSUE TITLE
alacrity fancy icon!

### ISSUE THREAD

**Issue by jankun** [jwilm/alacritty#285]
It nagged me the whole afternoon that Alacritty does not have a fancy icon,
so I made one. If you like it - let me know. I kind of do - but thats not good enough.
Now since I can look at it- its not nagging me anymore ;-)

[Preview 01](http://pasteboard.co/kIrULs44F.png)
[Preview 02](http://pasteboard.co/kIsyFpFFO.png)
[Preview 03](http://pasteboard.co/kItyGJHao.png)
[Preview 04](http://pasteboard.co/24rOhrIdT.png)
[Preview 05](http://pasteboard.co/kIuAnbFV6.png)
[Preview 06](http://pasteboard.co/kIwjRvijI.png)

**Comment by d3rrial** [comment]
In my opinion, as an **uninvolved bystander**, maybe a rust-brown version of the logo would look cool, and give a nod to its "written in Rust" nature?

Your designs look pretty nice, tho!

**Comment by jankun** [comment]
Good point - I forgot about the rusty roots- was all winter cheerful and didn't though about the cog. Will do.

**Comment by jankun** [comment]
Here some more **rust**y approach:
![alacritty4](https://cloud.githubusercontent.com/assets/1571074/21848782/e32de6e0-d802-11e6-9df7-d22aa5b62898.png)
![alacritty_rust3](https://cloud.githubusercontent.com/assets/1571074/21848783/e32e111a-d802-11e6-8cc6-64a59962fe8e.png)
![alacritty_rust2](https://cloud.githubusercontent.com/assets/1571074/21848780/e32d4212-d802-11e6-923b-7d1dad170287.png)
![alacritty_rust](https://cloud.githubusercontent.com/assets/1571074/21848781/e32daedc-d802-11e6-984b-3c77c7dfcf80.png)

**Comment by jankun** [comment]
Just for clarity. This is unofficial- I'm not the project owner, and my 'relationship' is what you see above. Let's see what the authors says, maybe this is just unnecessary and he got's his own idea (and rightly so if he does). If not then other could give more feedback and I can smooth out the kinks to make it offical if approved.

**Comment by jwilm** [comment]
I'm actually interested in soliciting the community for input here, and I like your abstract A.

WRT including Rust branding, I'm strictly against that. Although the project benefits greatly from being written in Rust, and I will continue using the project to promote the language and vis-versa, Alacritty is interesting in its own right.

In my imagination, I am hoping for a more interesting take on a standard terminal icon with something like your A.

**Comment by jankun** [comment]
Hi Joe, Thanks for your feedback. Huh, funny- You more or less wrote what I thought initially. Alacritty might not want to be seen as a PR around Rust, and Rust is "just" the language used. 

I also like the flipped prompt > :) I'll play with it further and will expand the word. The "cog icon", can be a nice sticker or stamp- a simple addition the main project 'branding' 

Thanks for your input. That clears the topic. I'll come with further proposals once I chew on this.

**Comment by okuuva** [comment]
Although I really like the abstract A inside the Rust cog, I totally understand the reason why you guys don't fancy it. While all the logos look really nice to me, I really like the colors in first two with "more rusty approach".

Just my two cents :)

**Comment by d3rrial** [comment]
I think this should be in jwilm's hands, I just hope jankun doesn't throw away the rusty approach, so that it remains as an alternative ;)

**Comment by jankun** [comment]
No worries, I'll post further designs in the next 2 days- need some time to sit down over the weekend and sketch the ideas.

**Comment by brycefisher** [comment]
@jankun -- I was bothered the same way! A project this cool _must_ have a great icon.

I'd vote for the the all black rotated > in the cog (2nd option in the 2nd batch)

**Comment by jansol** [comment]
I really like the rusty color scheme of the ^ in 1st one in the cog series, but the cog itself IMHO doesn't really fit in there.

**Comment by simonmurdock** [comment]
The minimal ones with some internal shadows look great!

**Comment by richiejp** [comment]
I really like the none rusty ones. The minimalism seems appropriate. However they do look very similar to the logo for Autodesk, but without the flick at the bottom, which could be a problem depending on how bored their lawyers are. :-)

**Comment by leavengood** [comment]
Obviously this is one of those major bike shed type of issues, but nonetheless I'll add my input: I think the icon should encapsulate the principles of alacritty: fast, minimal, terminal emulator. Possibly some reference to using the GPU. I agree with others above that Rust should not necessarily be featured in the icon.

Fast can be represented with speed lines, like in this:

https://cdn3.iconfinder.com/data/icons/hero/500/fast-512.png

Minimal can be represented by keeping the icon minimal.

Lastly I think the overall icon shape should be a terminal.

So maybe a terminal shape with the A shape from @jankun inside, that has speed lines coming off it.

**Comment by impowski** [comment]
I like all icons in the first post.

**Comment by brycefisher** [comment]
Seems like this (super exciting) issue has stalled a bit. I for one would be delighted to have any of the icons herein available for use in Alacritty by default, with (perhaps) a README or Wiki entry describing how to change out the icon. Does anyone on this thread feel super strongly any particular option presented?

**Comment by jankun** [comment]
I'm sorry for not-updating, something come along and well... lame excuse. I'm gonna do this in few days and post the "source" files somewhere for anyone who would like to fiddle with them.

**Comment by net** [comment]
Not a fan of the first ones—too much corner radius. The Rust ones like *really* nice.

**Comment by robertgzr** [comment]
I adapted @jankun 's design to look more native on mac

![alacritty_new_no_gear](https://cloud.githubusercontent.com/assets/3930615/26742977/46b9ba70-47e0-11e7-9835-d6afc239ef7a.png)
I personally like the only barely visible rust gear...
![alacritty_new_gear](https://cloud.githubusercontent.com/assets/3930615/26742974/43bf2440-47e0-11e7-9236-f81785503413.png)

I think the 'A' shape could be used as the project logo and then every platform should have it's own application icon with it.

**Comment by Determinant** [comment]
What about making this abstract "A" horizontal: something like ">" also suggests a terminal prompt.

**Comment by MaximDeloof** [comment]
Used the idea of speed lines of @leavengood and went for a retro aesthetic.
![alicritty_logo_small](https://user-images.githubusercontent.com/20443795/28165952-52885378-67d6-11e7-8348-295ed41054a9.png)
Is this something that feels appropriate or is it too much 80's neon?

**Comment by robertgzr** [comment]
@MaximDeloof I think the A with speed lines is really fitting as a logo and the colors are awesome.

Looks like you also used the mac icon template? any chance you can share a link to the `.icns` file?

**Comment by MaximDeloof** [comment]
@robertgzr Sure!

`.icns` file: [https://www.dropbox.com/sh/5v2sn3ck5z9yn7g/AABRe_cvnwQz_V-daW8QdZnAa?dl=0](url)

I didn't use the mac icon template, but I did try to emulate the terminal shape used on other icons.

**Comment by MaximDeloof** [comment]
@robertgzr Sure!

`.icns` file: [https://www.dropbox.com/sh/5v2sn3ck5z9yn7g/AABRe_cvnwQz_V-daW8QdZnAa?dl=0](https://www.dropbox.com/sh/5v2sn3ck5z9yn7g/AABRe_cvnwQz_V-daW8QdZnAa?dl=0)

I didn't use the mac icon template, but I did try to emulate the terminal shape used on other icons.

**Comment by MaximDeloof** [comment]
Made some refinements and created a couple of variations.

![alacritty_logo_board](https://user-images.githubusercontent.com/20443795/28214507-ce7d66b0-68aa-11e7-87f8-41aca30aa317.png)

The `.icns` files for all of them can be found here:
**[https://www.dropbox.com/sh/5v2sn3ck5z9yn7g/AABRe_cvnwQz_V-daW8QdZnAa?dl=0]()**

**Comment by jwilm** [comment]
@MaximDeloof I really like the direction you've gone with it! Would it be easy to see a variation where the speed line triangles are flat at the bottom instead of the top?

**Comment by jansol** [comment]
Maybe try this design with a triangle mesh wireframe?

**Comment by MaximDeloof** [comment]
With speed line triangles flat at the bottom ( @jwilm )

![alicritty_logo_variation_slant](https://user-images.githubusercontent.com/20443795/28220124-9c125fe6-68be-11e7-97f2-7b5562acffa6.png)

With triangle mesh wireframe ( @jansol ).

![alicritty_logo_variation_wireframe](https://user-images.githubusercontent.com/20443795/28220203-ea35e8dc-68be-11e7-8fa8-f8b977d5527a.png)

**Comment by jwilm** [comment]
@MaximDeloof 
Thanks for showing that version. My only concern is that it looks/feels like the triangles aren't actually flat but instead angled away slightly. Could you show one more version where the triangles are not flat on either side?

**Comment by MaximDeloof** [comment]
@jwilm I see what you mean. So like this?

![alacritty_logo_slant_middle](https://user-images.githubusercontent.com/20443795/28223561-32eb3aac-68cc-11e7-8c2d-964c5428eeba.png)

**Comment by jwilm** [comment]
Yeah, exactly like that. I feel this looks better!

As far as colors, I like scheme 1 and 8 the best. Probably 1 is my top pick.

**Comment by MaximDeloof** [comment]
I agree, it does look better!

I've made a new folder including `.icns` and `.png` files of both scheme 1 and 8 with adjusted triangles. You can find it here:
 
[https://www.dropbox.com/sh/s3pfr3f4mwj4ttb/AAAGxEoFUiNy4ZT48QekZA6Aa?dl=0](https://www.dropbox.com/sh/s3pfr3f4mwj4ttb/AAAGxEoFUiNy4ZT48QekZA6Aa?dl=0)

If you need any other formats just let me know.

**Comment by jansol** [comment]
I'm a bit bothered by how the speed lines aren't strictly centered on the scanlines as they fade out. Introducing "aliasing" would somewhat break the triangle look but would play nicer with the retro look I think.

**Comment by jansol** [comment]
Or maybe the speed triangles could even adhere to the same scanline style as the A for betterconsistency and a slightly pixelated look..

**Comment by MaximDeloof** [comment]
@jansol So more like this?
![alacritty_logo_v2](https://user-images.githubusercontent.com/20443795/28238722-2d25c112-695a-11e7-8bba-9ada04dcb007.png)

**Comment by net** [comment]
@MaximDeloof that looks great!

I felt inspired by the retro icons so I made my own—

<img width="1280" alt="icon-presentation" src="https://user-images.githubusercontent.com/6983821/28238856-0fd99ebe-692b-11e7-8705-5416b9beb083.png">

<img width="1280" alt="icon-presentation-dark" src="https://user-images.githubusercontent.com/6983821/28238857-1461b778-692b-11e7-91d9-d7e3263125ab.png">

<img width="986" alt="icon-website" src="https://user-images.githubusercontent.com/6983821/28238859-1b3fcab2-692b-11e7-892f-cdd64b33060f.png">


[.icns if you want to download it and try it out](https://github.com/jwilm/alacritty/files/1150258/Icon.zip) (zipped because GitHub doesn't support .icns)

**Comment by jansol** [comment]
@MaximDeloof yeah, although the rounded ends in the original looked good and would work here as well. The other thing I was thinking of was making the speed lines fade out and get thinner at the same time, kinda like the right one [here](http://caffeinalab.github.io/SiriWaveJS/) with a healthy dose of glow.

@net hey that's a pretty neat design. Especially as it would be easily recognisable at low resolutions too! (and I mean low as in 8x8-low, maybe even 5x5)

**Comment by iology** [comment]
I'm in!

<img title="Avenue to Alacritty" alt="demo" src="https://user-images.githubusercontent.com/23622455/28243416-09a47d90-69fb-11e7-9d5a-3f1232d05dec.png" width="256"><img title="Avenue to Alacritty" alt="Avenue to Alacritty" src="https://user-images.githubusercontent.com/23622455/28243408-c44da50a-69fa-11e7-85bf-f7fd6b2c1c22.png" width="256">

**Comment by robertgzr** [comment]
@net That looks fantastic too! Could you maybe try to somehow incorporate the blue from @MaximDeloof 's version?

**Comment by jwilm** [comment]
@MaximDeloof could we see a fuzzier version of your most recent image? I like the full bars but miss the fuzz from earlier options.

**Comment by jwilm** [comment]
@net digging that website mock-up 😁

**Comment by net** [comment]
@robertgzr 

![background](https://user-images.githubusercontent.com/6983821/28308688-ffe26c2e-6b74-11e7-87e5-3f38b428f3fc.png)

[.icns zip](https://github.com/jwilm/alacritty/files/1155228/icons.zip)

**Comment by asilvadesigns** [comment]
@net these are sweet, I wonder if removing that top color bar would add more contrast, make the 'a' take the focus, could be nice.

I like the blue : )

Site mock is nice too, @jwilm we could add it in a 'mockups' folder on the gdrive?

**Comment by MaximDeloof** [comment]
@jwilm Here comes the fuzz

![alacritty_logo_v2_fuzzy_sharp](https://user-images.githubusercontent.com/20443795/28333586-a55ecd04-6bf8-11e7-8cbc-d8dc1d7e6fc4.png)

With more rounded edges

![alacritty_logo_v2_fuzzy_round](https://user-images.githubusercontent.com/20443795/28333603-b31248a4-6bf8-11e7-8ac8-368b39ad9e34.png)

**Comment by martinlindhe** [comment]
Very nice icons! I'd just like to add my 2 cents.
It would be good if the winning icon have a good outline, so the icon is clearly visible when on dark background.
This is how the current icon looks on my setup (4th icon from the top)

![screen shot 2017-08-07 at 02 42 58](https://user-images.githubusercontent.com/181531/29008642-da7cd75c-7b1a-11e7-8c17-3f51417595b2.png)

It is hardly visible (and flu.x makes it even harder to make out ;-)

**Comment by sagebind** [comment]
Very last one by @MaximDeloof with the rounded edges is my favorite one of all of them in this thread so far.

**Comment by dsego** [comment]
Unfortunately, the retro scan lines kinda get lost in the smaller version  :/

<img width="384" alt="screen shot 2017-08-24 at 10 12 02 pm" src="https://user-images.githubusercontent.com/578557/29686508-8217867c-8919-11e7-9dfa-d2dbbf13e281.png">

**Comment by jansol** [comment]
You can pass it off as dithering. "it's supposed to not be visible when you squint"

**Comment by jwilm** [comment]
I think I'd like to move forward with @net's rocket icon. Although the retro flaming A is a lot of fun, I don't think it's quite right for the project logo. Thanks @MaximDeloof for all of the iterations on it.

Copy of image to be completely unambiguous:

![image](https://user-images.githubusercontent.com/4285147/29689079-c428d0fe-88d6-11e7-96ef-32eeef13ea55.png)

@net -- Are you willing to release the icon source files under the project license? Would also love to talk about the website mockup -- I really like it!

**Comment by leavengood** [comment]
FWIW I have been using the @net icon now for several weeks and I think it is great. The web design he made is also very nice.

**Comment by net** [comment]
@jwilm Glad you like it. I'm absolutely willing to release the icon under the project's license. Is an SVG sufficient?

We can definitely improve upon the website mockup.

**Comment by typekpb** [comment]
@jwilm Any chance to move icon stuff on?
I'd love to see the icon in my gnome dock. Otherwise I just keep searching for terminal every time I need it.

@dsego Maybe in the meantime, any chance for instructions on getting @net icon used locally?

**Comment by jwilm** [comment]
@net SVG works for me.

@typekpb heh, just need to make time myself or for someone to send a PR.

**Comment by trevordmiller** [comment]
@net @jwilm Is there an .svg of the logo available? I can't find one. Trying to add it to https://trevordmiller.com/projects/nova plugins list.

**Comment by chrisduerr** [comment]
Net has not responded since sharing the icon, so unless he does we'll probably have to look for something else.

**Comment by MarioRicalde** [comment]
What's the status on this one? I'm here to offer help with the website or the logo if needed.

**Comment by chrisduerr** [comment]
I've converted the logo to an SVG here: https://github.com/jwilm/alacritty/pull/1451

However it still has a few issues and needs some finishing touches. Unfortunately I'm not very comfortable with image/svg editors, so it has been on the backburner for a while.

**Comment by MarioRicalde** [comment]
@chrisduerr if you provide with some clear instructions for what you want, I can probably help with the SVG polishing. Let me know.

**Comment by chrisduerr** [comment]
@MarioRicalde You can see the SVG version here:
https://github.com/jwilm/alacritty/issues/967#issuecomment-397145025

The SVG files are all available in the PR I believe. We have permission to modify this icon to our liking.

The original icon by net looks like this:
![icon](https://user-images.githubusercontent.com/6983821/31856966-faa8846c-b69e-11e7-9932-fe49e750726a.png)

While I've tried reproducing this icon, it's not quite 100% there and the icon designed by net still looks a bit better. The biggest issue with net's icon though is that the border with the gradient makes things really hard to see on some backgrounds, so the goal would be to change the border to fix this and make this icon easily recognizable on all backgrounds. The linked issues have some more details.

The SVG I've created might not look great, however it should be very clean and simple to work with, so hopefully that will help with getting anyone started.

**Comment by andrewbanchich** [comment]
I noticed Alacritty doesn't have an icon when I install on Arch Linux, but it does when I install on macOS from Homebrew. Is Mac just testing this icon? Or is something in my install not configuring the icon correctly for GNOME?

**Comment by chrisduerr** [comment]
The proposed icon has not yet been converted to SVG successfully. While some distributions and package managers have already taken what is available, unfortunately it hasn't been standardized yet.

Unfortunately I'm no artist myself and there are definitely still some finishing touches required. So until that is done there won't be an 'official' icon available in standard formats.

**Comment by samholmes** [comment]
> @jwilm Here comes the fuzz
> 
> ![alacritty_logo_v2_fuzzy_sharp](https://user-images.githubusercontent.com/20443795/28333586-a55ecd04-6bf8-11e7-8cbc-d8dc1d7e6fc4.png)
> 
> With more rounded edges
> 
> ![alacritty_logo_v2_fuzzy_round](https://user-images.githubusercontent.com/20443795/28333603-b31248a4-6bf8-11e7-8ac8-368b39ad9e34.png)

It needs to be more square and bezeled like all the new macOS icons.

**Comment by karlpothast** [comment]
Couple I came up with - one is Dark Side of the Moon-ish and one is kind of take off of one of original Star Wars - A New Hope posters.  
![ala6](https://user-images.githubusercontent.com/13120778/210284164-12f42ab9-ec35-4eae-99e7-4f2e5e2387ef.png)
![alacrity](https://user-images.githubusercontent.com/13120778/210284990-a6d36136-587c-47f3-a96f-859444ce33f6.png)

**Comment by inoperable** [comment]
Pardon me asking, but what the f***k has a teletype terminal common with Star Wars - force allegiances aside? Maybe I missed something but I do not recall Death Star run on VT100

**Comment by karlpothast** [comment]
> Pardon me asking, but what the f***k has a teletype terminal common with Star Wars - force allegiances aside? Maybe I missed something but I do not recall Death Star run on VT100

John Williams wrote the score for the VT100 in 1978 after Star Wars in '77....little known fact.

**Comment by chrisduerr** [comment]
> Maybe I missed something but I do not recall Death Star run on VT100

```
telnet towel.blinkenlights.nl
```

**Comment by inoperable** [comment]
Ohh I am sorry, that's beyond my capacity to reason about. Need a pointer to the uhmm original, little known ASCII Music notation probably known in very exclusive circlesl, especially if John Williams send his  compositions around orginally in 78 for a 77 released movie.
