### ISSUE TITLE
Displaying Shades Unicode characters

### ISSUE THREAD

**Issue by dolsem** [jwilm/alacritty#2854]
Which operating system does the issue occur on? Ubuntu Linux 19.04

If on linux, are you using X11 or Wayland? X11

I have a progress bar that uses full block (U+2588) character to draw completed portion and light shade (U+2591) character to draw portion that has not been completed.
In GNOME Terminal it looks like this:
![Screenshot from 2019-10-06 12-12-02](https://user-images.githubusercontent.com/14323955/66272028-8f32f100-e832-11e9-9cdb-20fa3fae8ff6.png)
In Alacritty it looks like this:
![Screenshot from 2019-10-06 12-12-44](https://user-images.githubusercontent.com/14323955/66272038-b1c50a00-e832-11e9-83bd-57b8545e24ee.png)
They both use the same font (Fira Code), and it seems to be independent of the font itself. I really enjoy the smoothness of GNOME Terminal overall and in this instance in particular. Can something like that be implemented in Alacritty, ideally as a togglable option?

On a different note, I had to set y offset to 8 pixel to get it displayed without overlapping the lines above and below. GNOME Terminal scales it just fine automatically. I've seen a config option in Kitty to set custom scaling for specific Unicode characters. Would be nice to have something like that in Alacritty.

**Comment by chrisduerr** [comment]
This is a font glyph and as such it's not up to Alacritty to define its shape but up to the font.

There's absolutely no reason why we'd try to render a glyph like that ourselves, if you're interested in rendering arbitrary colored cells, you should use truecolor support instead.

**Comment by nixpulvis** [comment]
In case anyone was curious more about why Gnome Terminal (or VTE in this case) looks better: https://askubuntu.com/questions/763947/terminal-how-to-display-shades-unicode-characters-properly

**Comment by dolsem** [comment]
@chrisduerr As I've mentioned in my first comment, this is not simply a font glyph. Both of my screenshots use the same font, Fira Code. Moreover, the look of this character stays virtually the same on any font and gets rendered like this in Gnome Terminal. In fact, Gnome Terminal renders different shades as semi-transparent versions of full block, and you can see the terminal background underneath. It's not something that can be accomplished with a font glyph.

I bring this up cause instances like this make Gnome Terminal feel very refined, and it would be great to bring something like that to Alacritty.

**Comment by chrisduerr** [comment]
> As I've mentioned in my first comment, this is not simply a font glyph.

VTE pretends it's not, but this is false.

> I bring this up because instances like this make Gnome Terminal feel very refined, and it would be great to bring something like that to Alacritty.

I'd say it's more hacky than anything else.

**Comment by nixpulvis** [comment]
It's funny, I agree with both of you to some extent.

From a user perspective, hijacking the underlying font's █ (U+2588) and ░  (U+2591) leads to a cleaner look in many cases. However, as a user I think I'd expect my terminal to respect the font I have chosen, which this is not doing. As @chrisduerr mentioned, applications using these block glyphs could be updated to use truecolor to the same effect. Even without truecolor, I can make something pretty nice looking with:

```sh
echo -e "\e[47m     \e[107m           \e[0m"
```
