### ISSUE TITLE
Alacritty lacks option like -into (xterm) or -embed (urxvt)

### ISSUE THREAD

**Issue by Egosummiki** [jwilm/alacritty#2859]
As Alacritty doesn't support tabs it would be useful to have an option to embed its window into other applications.

**Comment by kchibisov** [comment]
Alacritty already supports this option, however you have to update to the latest master to get it.

**Comment by nixpulvis** [comment]
Yep this was merged in #2786 about 15 days ago.

@Egosummiki let us know if this doesn't work for you.
