### ISSUE TITLE
Increase / Decrease font size while running

### ISSUE THREAD

**Issue by nhellwig** [jwilm/alacritty#286]
For presentation and working in pairing, it would be very helpful to be able to increase / decrease the font-size while running alacritty.

Similar to Command + "+" and Command + "-" on most mac os terminal implementations.

**Comment by jwilm** [comment]
Agreed! I feel like there's an issue for it already, but I'm struggling to find it.

**Comment by apexo** [comment]
#121

**Comment by panda** [comment]
For my google brothers who ran into this issue and use KDE Plasma

Two ways you can fix this, one is setting the DPI in your X configuration or if you are using KDE make sure "Force font DPI:" is enabled in System settings

![image](https://user-images.githubusercontent.com/7886355/127420071-be91a839-8ad5-45b6-97b5-dbb92b510fee.png)

**Comment by chaseadam** [comment]
direct link to added feature https://github.com/alacritty/alacritty/pull/625

**Comment by mabushey** [comment]
Why is this closed? Is changing the font size just something that's not going happen?

**Comment by kchibisov** [comment]
>Why is this closed? Is changing the font size just something that's not going happen?

Try pressing `ctrl +/-` or `cmd +-`. If you want some other binding to change font size can consult alacritty.yml.

**Comment by Andrej-Marsic** [comment]
Is there a way or a shortcut even to return the size back to normal?

**Comment by xliiv** [comment]
ctrl+0, works for me

**Comment by valeratrades** [comment]
This should be possible to access programmatically, similar to how tmux keybinds just implicitly call existing tmux functions.
It would be amazing to be able to do
```sh
alacritty session -x IncreaseFontSize
```

**Comment by chrisduerr** [comment]
You can do `alacritty msg config font.size=30`.
