### ISSUE TITLE
Problem with config: EOF while parsing a value

### ISSUE THREAD

**Issue by dewijones92** [jwilm/alacritty#2865]
Mac OS

[2019-10-10 11:33] [ERROR] Unable to load config "/Users/dewijones/Dropbox/Coding/alacritty/alacritty.yml": Problem with config: EOF while parsing a value

It might be to do with this file commented out
https://github.com/jwilm/alacritty/blob/24651a6144e5071f0a72d991734a9b380255156e/alacritty.yml

**Comment by kchibisov** [comment]
@dewijones92 You should grab config file for your version. This is related to the file commented out, however this is not a problem on the latest master, since we're silencing this error (This is a `serde` bug iirc).
