### ISSUE TITLE
Show version / build

### ISSUE THREAD

**Issue by d3rrial** [jwilm/alacritty#287]
Can you add a version counter in the software somewhere that can be called with

```zsh
./alacritty --version
```
or something similar?
This command should (in my opinion) not open a new shell, it should only print the version number in whatever shell that called it.

Whether the flag should be called "--version" is debatable, I don't know if conventions for this kind of thing exist.

urxvt does not have something like this, as far as I know, but when I put something random as an option, this will print:

```zsh
urxvt: "asdf": unknown or malformed option.
rxvt-unicode (urxvt) v9.22 - released: 2015-10-11
[...]
```

I hope I'm not the only one who thinks that this can be useful?

Edit:

Here's an extremely crude implementation: https://github.com/d3rrial/alacritty/commit/60121301923a64ab9af5ee4ffc3b3551913fd135

**Comment by NickeZ** [comment]
A less crude implementation would use

```rust
const VERSION: &'static str = env!("CARGO_PKG_VERSION");
```

**Comment by d3rrial** [comment]
I'm a crude kind of person, I don't know how to implement something sophisticated, but that looks good!

**Comment by NickeZ** [comment]
btw, I think we should have `-h | --help` as well.

**Comment by jwilm** [comment]
@NickeZ agreed; we're starting to collect more switches. Probably a good time to switch to a real command line options library like [clap](https://crates.io/crates/clap).

As for the version string, I think it makes sense to use the git revision for now instead. Actually, it probably makes sense to have both. Something [like this](https://github.com/cstorey/git-build-version/) would work for the git rev.

**Comment by lukaslueg** [comment]
I'll add this

**Comment by NickeZ** [comment]
@lukaslueg Will you do the [clap](https://crates.io/crates/clap) integration?

**Comment by lukaslueg** [comment]
I'll add a new module `versions` (?) that includes the version number of alacritty and some build-time information. This is mainly useful for debug output and `--version | -V` on the commandline.

I would suggest we track `versions` here and open a new issue for clap integration. As a sidenote I'm not sure if we need clap at all: The cli options for a terminal emulator should be fairly minimal, given that it is usually not started from within a shell but with a Desktop-link and a config file.

**Comment by NickeZ** [comment]
> The cli options for a terminal emulator should be fairly minimal, given that it is usually not started from within a shell but with a Desktop-link and a config file.

The first time I tried to run it I ran `alacritty --help` and that wasn't very helpful at all. I still think that if we use clap it will be more maintainable code in the end. I would say that argument parsing has a lot of corner cases.

**Comment by lukaslueg** [comment]
@jwilm I will create a small crate with minimal dependencies that serializes all kinds of build time information into a new module. This crate gets to be a new build time dependency. Are you ok with this?

**Comment by jwilm** [comment]
@lukaslueg what sort of build time info are you hoping to include? I was just thinking about adding the git revision for now which is already available from another crate.

**Comment by lukaslueg** [comment]
I have a mod ready that provides crate version, target-triplet, used profile, enabled features and compiled-in dependencies and their versions. I was thinking this might be useful on INFO and above

**Comment by lukaslueg** [comment]
@jwilm here is [some code ](https://github.com/lukaslueg/alacritty/tree/build_info)that serializes various build-time information.

This outputs version, git version, profile, features and dependencies and their versions. Without the logging-module, the output is too verbose.

> Welcome to alacritty 0.1.0a2cd4b6 debug.
> I was compiled for x86_64-apple-darwin using bitflags 0.7.0, cgmath 0.7.0, clippy 0.0.104, copypasta 0.0.1, errno 0.1.8, font 0.1.0, git2 0.6.3, gl_generator 0.5.2, glutin 0.6.1, lazy_static 0.2.2, libc 0.2.18, mio 0.6.1, notify 2.6.3, parking_lot 0.3.6, serde 0.8.19, serde_derive 0.8.19, serde_json 0.8.4, serde_yaml 0.5.0, toml 0.2.1, vte 0.2.1, xdg 2.0.0
> Enabled features are DEFAULT, ERR_PRINTLN
> device_pixel_ratio: 2
> device_pixel_ratio: 2
> width: 2048, height: 1536
> 

Requesting for comments. The branch also caches the gl_bindings; I'm unsure about this.

**Comment by chrisduerr** [comment]
With the help of #340, Alacritty has now supported `alacritty --version` for a long time. So it seems like this issue should be resolved.
