### ISSUE TITLE
Text Refresh Issue

### ISSUE THREAD

**Issue by tinder-falood** [jwilm/alacritty#2874]
Which operating system does the issue occur on?
Macos 10.14.5

I use alacritty with [yabai window manager](https://github.com/koekeishiya/yabai).
when I open a new alacritty instance, yabai will automatically resize and tiling existing windows.

Here's my original alacritty window, everything looks good.
![image](https://user-images.githubusercontent.com/56088860/66703998-06ea9b00-eccd-11e9-88a3-f5553893fce3.png)

but when I open a new one, the UI looks like this
![image](https://user-images.githubusercontent.com/56088860/66704005-19fd6b00-eccd-11e9-8c84-a20fd6daa570.png)
It will back to normal when I reactive the window.
![image](https://user-images.githubusercontent.com/56088860/66704014-2ed9fe80-eccd-11e9-9ee6-1bf1e080de6c.png)

is there a way to make the window fresh automatically?

Thanks!

**Comment by chrisduerr** [comment]
Fixed on the latest master.

**Comment by tinder-falood** [comment]
@chrisduerr Thanks
