### ISSUE TITLE
Allow arbitrary input for -e/--command

### ISSUE THREAD

**Issue by Clyybber** [jwilm/alacritty#2878]
This would allow one to use functions and similar constructs there.
Currently trying to do for example `alacritty -e 'echo test; sleep 3'` will error with
```
[2019-10-14 17:18] [ERROR] Failed to spawn command: No such file or directory (os error 2)
```
`xterm` already allows/handles this.

**Comment by kchibisov** [comment]
You need to run it in shell. So you should use alacritty -e sh -c 'echo test; sleep 3'. It fails because you're giving it a command `echo test; sleep 3`(Thats a full command name), e.g. `command -e echo test` is fine (`echo` is a command and `test` is its argument), the `;` is a shell thing so without running `sh`,`bash`, etc it's not possible.

**Comment by nixpulvis** [comment]
@Clyybber would it be fair to rename this to "Allow Shell commands for -e/--command"?

While `xterm` does allow this, other don't. I might be interested to hear how others think this should work. I feel like it might re reasonable to launch a shell here myself.

**Comment by kchibisov** [comment]
@nixpulvis What should we do on Windows in this case (like you're running wsl or whatever)? What shell should we run? What if your shell doesn't use `;` as a separator for multiple commands. What should we do about `&&` and `||` stuff? There are more questions then answers in my opinion, so I think I do understand why no one other then xterm support it. We can implicitly use shell's `-c`, but if it's not presented?

**Comment by chrisduerr** [comment]
This has been asked before and I don't think we should ever change this.

If we automatically spawn a shell, there's no way not to. If we don't, the user can always spawn a shell themselves. If the user understands what's going on, our solution is just better for picking exactly what you want. The only drawback would be brevity and `sh -c` is hardly too much to ask for.

Especially since the userbase of Alacritty is a bit different than something like gnome-terminal, which comes preinstalled on many systems, I think we should be confident in the ability of our users in this regard.

**Comment by nixpulvis** [comment]
We should improve the error message then, so people don't keep opening this kind of issue.

We at least need to show the string we failed to execute ideally.

**Comment by chrisduerr** [comment]
> We should improve the error message then, so people don't keep opening this kind of issue.

There's not necessarily going to be an error. And I think 'no such file or directory' should already be pretty clear for everyone familiar with unix. If we change that to something we might find more user-friendly, we just risk changing it to something users are unfamiliar with.

**Comment by kchibisov** [comment]
I think our error message is fine. Every other terminal reports the same thing, some of them less clear(gnome-terminal). We already have clear `--help` output
```
 -e, --command <command>...                     Command and args to execute (must be last argument)
```

**Comment by chrisduerr** [comment]
> We at least need to show the string we failed to execute ideally.

Just to add on my previous message, this would be no problem. Sounds like a good idea to me and would be a trivial change.

**Comment by chrisduerr** [comment]
@nixpulvis Fixed it here: https://github.com/jwilm/alacritty/pull/2879, let me know if that's what you're talking about.

**Comment by Clyybber** [comment]
For context, I'm trying to use alacritty to launch a program with setsid, in this example alacritty.
I want alacritty to echo something, spawn a new alacritty instance, and exit/close without waiting for the spawned alacritty to terminate.
Unfortunately this doesn't work with the pattern `alacritty -e sh -c "echo something; setsid alacritty; exit"`. In xterm I tried it with `xterm -e "echo something; setsid xterm; exit"; this works, leading me to believe it was an issue with the aforementioned pattern, which it is not. I'm sorry for that.
So the actual issue is in my snippet and xterm was just behaving a tad bit different to alacritty with setsid.

**Comment by NickeZ** [comment]
Maybe `setsid alacritty&` works? I guess xterm backgrounds itself when it launches.

**Comment by Clyybber** [comment]
@NickeZ Yeah thanks that works, although for some reason it only works for me (having fish as the default shell) using `alacritty -e fish -c "echo something; setsid alacritty &; sleep 1; exit"` and not using `alacritty -e sh -c "echo something; setsid alacritty &; sleep 1; exit"`...
Also because it is setsid that is started in the background I have to insert a sleep so that it doesn't get killed too early to actually start the process, though I'm sure theres a better way to accomplish that.
