### ISSUE TITLE
Very short idle timeout ??

### ISSUE THREAD

**Issue by wsphillips** [jwilm/alacritty#2880]
Which operating system does the issue occur on? Ubuntu 18.04 and Fedora 30. Happens on three different installs I have tried using the latest stable build.

If on linux, are you using X11 or Wayland? X11

I've noticed Alacritty stops updating/rendering after what seems to be 30 seconds or less of no interaction. For instance, long running build processes will appear to have hung, but any keypress updates the output. 

My guess is its happening after some sort of idle threshold time? Is this intended behavior? Is there a way to disable it or prolong it so that the terminal always prints whatever is coming out of stdout regardless of whether the window has been interacted with?

**Comment by kchibisov** [comment]
Fixed on the latest master. dup of #2217.
