### ISSUE TITLE
gnome thumbnails in the app switcher are broken

### ISSUE THREAD

**Issue by vrischmann** [jwilm/alacritty#2887]
> Which operating system does the issue occur on?

Fedora 30 using Gnome

> If on linux, are you using X11 or Wayland?

X11

Since commit 401c2aab964b60e8c3b072e5098ba8e366d04944 thumbnails in the Gnome app switcher are broken.

It's easier to describe the problem with screenshots.

Here's what I get when using Alt-Tab, then moving over Alacritty and using the arrow to move down (or using the "Switch applications" shortcut)  with commit 3475e449870b382cda4ea6d48f980577cd8c929e:

![alacritty_ok](https://user-images.githubusercontent.com/1916079/67001535-49034a80-f0da-11e9-85a8-afda37a4a7f7.jpg)

and here's what I get with the same process as described above, since commit 401c2aab964b60e8c3b072e5098ba8e366d04944:

![alacritty_bad](https://user-images.githubusercontent.com/1916079/67001942-1a39a400-f0db-11e9-80bb-120e74effd6d.jpg)

the thumbnails are missing for some reason.

Additional information:

* the configuration file doesn't change
* the desktop file doesn't change

Let me know if you have any question.

**Comment by chrisduerr** [comment]
It seems unlikely that the commit you've linked actually broke it. Can you verify exactly which commit broke this or verify that the previous commit actually still works?

**Comment by chrisduerr** [comment]
If 3475e44 broke things that would have made some sense, but 401c2aab964b60e8c3b072e5098ba8e366d04944 changed absolutely nothing related to this other than the window title. So unless a weird window title breaks things here, I don't understand why this commit would break things.

Unfortunately the errors linked are just a bunch of broken JavaScript crap that doesn't clearly indicate any issue other than JavaScript's typesystem. So we'd have to actually check the sources to see what causes this. Maybe it can't handle a specific title?

**Comment by vrischmann** [comment]
The code that fails seems to be [this](https://sourcegraph.com/github.com/GNOME/gnome-shell@3.32.2/-/blob/js/ui/altTab.js#L896-908).

And it is indeed a problem with the title, I didn'tt realize this before but with 401c2aab964b60e8c3b072e5098ba8e366d04944 I have no title in the title bar.

By setting this:

```yaml
window:
  title: Alacritty
```
in the configuration file it works as before.

**Comment by DSpeckhals** [comment]
I'm wondering if the `window` being commented out or not-existent in the config file causes this. In this case, the default for `window.title` would be an empty string, which would cause this error.

**Comment by DSpeckhals** [comment]
I can see what I can do to fix this. "Alacritty" should be default if `title` is undefined, not an empty String. I think this would make the tiles show properly with alt-tab.
