### ISSUE TITLE
Alacritty doesn't close unless it's active

### ISSUE THREAD

**Issue by for-coursera** [jwilm/alacritty#2894]
(As suggested [here](https://github.com/jwilm/alacritty/issues/2851) by @kchibisov, I open this separate issue.)

**OS**: macOS 10.11
**Alacritty**: a75e949 (the latest master)

**To reproduce**: Run "sleep 3 && exit" and then switch to another application. Alacritty won't close itself after 3 seconds, like it should, until the cursor moves back to it.

https://i.imgur.com/dKx5XP5.gif

**Notes**: as pointed out by @kchibisov, this doesn't happen with 0.3.3 release (cc3e4d3), so it must be some sort of regression.

**Comment by kchibisov** [comment]
likely related to https://github.com/rust-windowing/winit/issues/1117.

**Comment by kchibisov** [comment]
Could you test #2910?

**Comment by for-coursera** [comment]
Seems to work OK, thanks!

You / me are closing this?
