### ISSUE TITLE
Refactor mouse position handling

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#2898]
Currently there are some problems with handling of mouse position when it comes to padding and the message bar. This is mainly caused by a lack of clear distinction between moving inside the window, outside the window and inside the padding.

One of the issues that is present in the latest master is that when moving from the message bar's close button to the padding, the mouse cursor will not be reset.

However this also creates problems with https://github.com/jwilm/alacritty/pull/2896, since the column/line is always set even in the padding, URLs are highlighted when moving from URL directly to the padding.

Leaving the viewport currently also isn't tracked correctly. While the mouse is outside the window, the stored mouse positions still present it as within the window boundaries.

**Comment by nixpulvis** [comment]
@chrisduerr sorry I never really had the chance to take a look at this in depth before you merged it. I was hoping that this would fix the issue of the mouse cursor and underline updating without the mouse moving, but it still seems to be a bit off:

![url-issue](https://user-images.githubusercontent.com/715947/68354403-480e7900-00da-11ea-91fa-4410ebfd42f7.gif)
