### ISSUE TITLE
Modifier state is wrongly set while switching between windows

### ISSUE THREAD

**Issue by juchiast** [jwilm/alacritty#2906]
Which operating system does the issue occur on? Linux, Fedora 30.

If on linux, are you using X11 or Wayland? X11, i3.

I'm using latest master branch. Sometime, randomly, the up arrow key doesn't work. Switching focus to another window and focus back again fix the issue. I saw this issue since #2438 , I also remember some guy mentioned it in the discussion.

EDIT:
Scenario: I use i3wm, switching between windows is done by Logo+L. Which certain timing of Logo+L, logo modifier is turn on when it should not be, this can be seen in --print-events.

The state was wrong right after it was passed from glutin in the event loop, this suggests the bug is of glutin.

**Comment by juchiast** [comment]
While using Vim, `k` doesn't work as well, not only up arrow.

**Comment by chrisduerr** [comment]
@nixpulvis I think you've run into this before, right?

> While using Vim, k doesn't work as well, not only up arrow.

This sounds interesting, does the key not work at all, so is it just swallowed? Can you reliably reproduce this?

**Comment by nixpulvis** [comment]
@chrisduerr I did notice an issue with the up arrow key once, but never anything with 'k'.

This does indeed sound like the same issue, sadly I haven't noticed it again in a while, and I have no idea how to reproduce.

**Comment by kchibisov** [comment]
@nixpulvis I recommend you to read though #2907. Since this issues are identical imho.

**Comment by kchibisov** [comment]
@juchiast would you mind to post `print-events` logs, since iirc you can reliably repro this issue now? Also type some random character(e.g. `a`) for us to understand when the issue start happening.

**Comment by juchiast** [comment]
[Alacritty-8292.log](https://github.com/jwilm/alacritty/files/3767026/Alacritty-8292.log)

[Alacritty-8293.log](https://github.com/jwilm/alacritty/files/3767029/Alacritty-8293.log)

The bug happens on Alacritty-8292.log. 8293 is the other terminal that I use to reproduce the bug. The bug happens on the section after the last `Focused(true)`.

**Comment by juchiast** [comment]
Updated the description, I think this can be reproduced with glutin-only.

**Comment by kchibisov** [comment]
I was also able to repro it occasionally, while I was using X11, pretty strange issue though.

**Comment by chrisduerr** [comment]
Reported upstream in https://github.com/rust-windowing/winit/issues/1259.

**Comment by ranisalt** [comment]
Well, I have a similar issue on Wayland.

**Comment by chrisduerr** [comment]
> Well, I have a similar issue on Wayland.

Could you go into more detail?

**Comment by ranisalt** [comment]
> Could you go into more detail?

After switching to another window using Alt+Tab, going back to Alacritty (via Alt+Tab or not) gives this issue where I can't type properly, as if Alt is locked in. Pressing Alt fixes it back after releasing the key.

I'm on GNOME 3.34.1 Wayland using alacritty latest commit.

**Comment by kchibisov** [comment]
@ranisalt Are you running `alacritty` natively or under Xwayland? I wasn't able to repro this issue under 40 minutes by pressing alt-tab in GNOME Wayland with a native client.

**Comment by kdeberk** [comment]
I have the same issue since I pulled and built from master today (679e67d0). After I alt-tab to alacritty, I need to press Alt again to get anything to work.

I'm using gnome with Wayland. If I start alacritty with `env WINIT_XINIT_BACKEND=x11 alacritty` I still have the same problem.

**Comment by ranisalt** [comment]
> Are you running `alacritty` natively or under Xwayland?

Natively. Is there a way to force it and be 100% sure, though?

**Comment by kchibisov** [comment]
For folks on `Wayland`, could you try the following patch and see what you're getting, when you feel like your modifiers are wrong (the last line). winit didn't changed much in modifiers handling, so it's likely an old bug.


```
diff --git a/alacritty/src/event.rs b/alacritty/src/event.rs
index 2cee37f..28e41d3 100644
--- a/alacritty/src/event.rs
+++ b/alacritty/src/event.rs
@@ -402,7 +402,7 @@ impl<N: Notify> Processor<N> {
                 input::Processor::new(context, &self.display.urls, &self.display.highlighted_url);

             for event in event_queue.drain(..) {
-                Processor::handle_event(event, &mut processor);
+                Processor::handle_event(event, &mut processor, _event_loop.is_x11());
             }

             // TODO: Workaround for incorrect startup DPI on X11
@@ -464,6 +464,7 @@ impl<N: Notify> Processor<N> {
     fn handle_event<T>(
         event: GlutinEvent<Event>,
         processor: &mut input::Processor<T, ActionContext<N, T>>,
+        is_x11: bool,
     ) where
         T: EventListener,
     {
@@ -597,7 +598,11 @@ impl<N: Notify> Processor<N> {
                     | Touch(_)
                     | Moved(_) => (),
                     // TODO: Add support for proper modifier handling
-                    ModifiersChanged { .. } => (),
+                    ModifiersChanged { modifiers: mods } => {
+                        if !is_x11 {
+                            println!("{:?}", mods);
+                        }
+                    },
                 }
             },
             GlutinEvent::DeviceEvent { .. }
```

**Comment by kdeberk** [comment]
```
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Control, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Control, ignoring Lock
ModifiersState { shift: false, ctrl: false, alt: true, logo: false }   <- I alt-tab away
ModifiersState { shift: false, ctrl: false, alt: false, logo: false }  <- I alt-tab back
ModifiersState { shift: false, ctrl: false, alt: true, logo: false }   <- I press alt again to reset the modifier state
ModifiersState { shift: false, ctrl: false, alt: false, logo: false }
```
One thing that could explain the first two lines: I've mapped Caps Lock to Control.

**Comment by kchibisov** [comment]
As you can see, after alt-tab your modifiers state is correct. On Wayland we're getting this events from your compositor (GNOME) and then using them to send keys. So, according to your log everything is fine, since there is no way winit can send keys with `alt` modifier (true), after it said to you that it's state is false. You're likely entering some mode in shell after alt or whatever. You could verify that keys are being received without alt by using `alacritty --print-events` and I also recommend you to fix your xkb settings.

**Comment by ranisalt** [comment]
> I've mapped Caps Lock to Control because that makes using emacs easier.

Oh. I've done that too.

**Comment by wsphillips** [comment]
Hey came here to say I am getting the same/similar behavior. If I Alt + Tab focus out of alacritty and then back input gets locked up/erratic. Pressing Alt by itself resolves the issue. I experience this on multiple Linux distros, most recent master branch build and with no custom keybindings in alacritty.yml

**Comment by mdkcore0** [comment]
I have the same issue, on X11/i3wm

alt is my modifier key, so I'm experiencing it a lot :/

**Comment by jodh-intel** [comment]
Thanks for updating. However, I'm still seeing the incorrect behaviour. I'm running with the latest HEAD (561063b) and `WAYLAND_DISPLAY=""` set on Fedora 31.

**Comment by kchibisov** [comment]
@jodh-intel Ok, I was able to repro your issue, but its something related to XWayland and how winit tracks things, I guess running natively on Wayland or natively on X11 is fine.

**Comment by mdkcore0** [comment]
on my setup (X11/i3) #2967 fixed the issue

**Comment by jodh-intel** [comment]
I'd set `WAYLAND_DISPLAY=""` when I first discovered alacritty as I couldn't run without it. However, I hadn't really dug into why it wasn't working. A bit of digging showed the problem: #2980. The good news it that the alt bug is now fixed for me as I'm now running with Wayland.
