### ISSUE TITLE
Background is semi opaque during visual bell animation

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#2911]
Arch Linux, Wayland(sway) and X11 (i3 + compton)

During visual bell animation background is transparent(not fully though) with disabled transparency.

Edit:
Was able to repro on v0.3.3, so probably an old bug.

**Comment by kennylevinsen** [comment]
Also note that the animation does not finalize.

1. Set duration to 500ms
2. Cause bell to trigger
3. Observe 3 draws with opacity ~0.8, ~0.7 and ~0.4
4. Observe that no further draw calls is made, resulting in an unfinished animation. Typing will cause the animation to progress (however, it doesn't always finalize completely).

terminal.dirty is still true, so it would appear that the event loop is stalled. Maybe we need to force a draw event somehow if the terminal is still dirty.

**Comment by chrisduerr** [comment]
This is a bit surprising to me since we draw our visual bell *above* the normal terminal background.

There might be an issue with the operations we perform (say we render in replace, instead of merging).

> terminal.dirty is still true, so it would appear that the event loop is stalled. Maybe we need to force a draw event somehow if the terminal is still dirty.

The terminal's `dirty` flag shouldn't be cleared when an animation is still going on. You can see that in `event.rs` pretty clearly.

**Comment by kennylevinsen** [comment]
> The terminal's dirty flag shouldn't be cleared when an animation is still going on. You can see that in event.rs pretty clearly.

As I said, the terminal is set to dirty, but no further draw calls are made. Either something else ends up clearing the bit outside of the assignment in event.rs, or the event loop has stalled. I did not investigate further yesterday.

**Comment by kennylevinsen** [comment]
Split out as #2914

**Comment by chrisduerr** [comment]
> As I said, the terminal is set to dirty, but no further draw calls are made. Either something else ends up clearing the bit outside of the assignment in event.rs, or the event loop has stalled. I did not investigate further yesterday.

Yeah, I didn't understand what you meant with your initial comment, however it seems like you've already figured it out. Thanks.
