### ISSUE TITLE
Window is transparent during startup, breaking compositor fade in animations

### ISSUE THREAD

**Issue by p4block** [jwilm/alacritty#2912]
Running Arch with X11 and compton on bspwm.

In the instant before Alacritty is displayed (w/ zsh prompt et al) the window exists, has a border, but is completely transparent. After a few tenths of a second it finishes loading and suddenly pops. 

This breaks the fade in animation as the compositor fades the background picture into the background picture, instead of Alacritty's configured background color. Easily noticeable comparing ie. Termite and Alacritty with a long fade in animation in Compton, 

I think that the window should be filled with the configured background color so there is something displayed while the actual terminal loads. 

I don't know if it's even possible to implement, just leaving this issue there if someone else notices the same.

**Comment by kchibisov** [comment]
Could you test the latest master?

**Comment by p4block** [comment]
Fixed in master. My bad. Awesome work!

**Comment by chrisduerr** [comment]
Duplicate of #2254.

**Comment by kchibisov** [comment]
it's not a duplicate though, it was probably fixed by #2580, since we're showing window without feeling it on v0.3.3 .

**Comment by chrisduerr** [comment]
Oh, good point, since this isn't about permanent opacity issues but instead just at startup.
