### ISSUE TITLE
Visual bell animation stalls

### ISSUE THREAD

**Issue by kennylevinsen** [jwilm/alacritty#2914]
The event loop stalls before completion of visual bell animation, even when the dirty bit is still set.

**Comment by virtualdxs** [comment]
I'm still seeing (what I think is) this issue on 0.4.0. I cause a bell, it mostly finishes the animation, but there's still an overlay of red (bell color) until I type another key. The opaqueness varies from bell to bell.

Using Xorg version 1.20.6

GPU:

    08:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 710] (rev a1)

Bell config:

    visual_bell:
      animation: Linear
      duration: 200
      color: '0xff0000'

**Comment by virtualdxs** [comment]
Note: I'm able to reproduce this on one computer with the above information, but not my laptop.

**Comment by chrisduerr** [comment]
@virtualdxs Would you mind opening a separate issue for this?

**Comment by virtualdxs** [comment]
Will do.
