### ISSUE TITLE
Alacritty background_opacity only darkens background, does not change opacity

### ISSUE THREAD

**Issue by idlys** [jwilm/alacritty#2923]
This is on Void Linux using X11.

I have using Alacritty along with Compton. Rather than changing the opacity of the window, the background_opacity option in alacritty.yml simply darkens the background to black.

I have verified that Compton is running correctly by checking other programs with background opacity settings, and it seems to only be Alacritty which is having problems.

**Comment by kchibisov** [comment]
@idlys Are you on the latest master? if not try updating to it and retest.

**Comment by idlys** [comment]
@kchibisov 
Looks like it is fixed on master, thank you for the help.

**Comment by voider1** [comment]
Having the same issue on Pop!_OS running i3.

**Comment by chrisduerr** [comment]
@voider1 i3 requires a compositor like compton for transparency.

**Comment by ghaerdi** [comment]
I have the same issue on arcolinux running leftwm with picom, in others terrminals the transparency works well
