### ISSUE TITLE
Regression: Zsh autocompletion over ssh is dodgy

### ISSUE THREAD

**Issue by tecosaur** [jwilm/alacritty#2928]
I'm running an up to date Solus install (linux `5.2.20-130`) on X11.

#### The Issue
Zsh autocompletions over ssh are … dodgy
![ssh-zsh-a](https://user-images.githubusercontent.com/20903656/67692964-e82e1900-f9db-11e9-9c2a-2813f7fb52df.gif)
Reffer to me doing the same locally (just a different prompt style):
![local-zsh-a](https://user-images.githubusercontent.com/20903656/67693058-0c89f580-f9dc-11e9-920a-4802b5280293.gif)
The gnome terminal has no such issue
![gt-ssh-zsh-a](https://user-images.githubusercontent.com/20903656/67693231-58d53580-f9dc-11e9-84b8-97517fea91af.gif)

Both systems are running the same version zsh (`5.7.1`), and `zsh-autosuggestions`.

#### Regression?
This is something I didn't have a problem with a few months ago, I'm afraid I'm not sure exactly when the issue started.

**Comment by kchibisov** [comment]
If you feel like its a regression, then try bisecting.

**Comment by chrisduerr** [comment]
What terminfo are you using to ssh into the remote? If it's Alacritty, does the remote have the Alacritty terminfo installed?

**Comment by tecosaur** [comment]
How do I get the current terminfo?

**Comment by chrisduerr** [comment]
Terminfo for releases is in the releases page, current terminfo is in the repo tree.

**Comment by tecosaur** [comment]
Hmmm. I'm going to guess it's `/usr/share/terminfo/a/alacritty`, in which case that definitely doesn't exist on the server (all it has beginning with `a` is `ansi`).

**Comment by tecosaur** [comment]
Oh actually, that was all it had under `/lib/terminfo/`, under `/usr/share/terminfo/a/` it has another 320, but no `alacritty`.

**Comment by chrisduerr** [comment]
Does `TERM=xterm-256color ssh <REMOTE>` work?

**Comment by tecosaur** [comment]
It does indeed. That's a simple fix. Now I feel a bit sily.

**Comment by chrisduerr** [comment]
The terminfo you're trying to use needs to be installed on the remote. So either Alacritty needs to be installed on the remote, or you need to run ssh with a different terminfo.

> That's a simple fix. Now I feel a bit sily.

Now worries, glad we would figure it out so quickly.
