### ISSUE TITLE
Windows: Pressing Ctrl + W (or ^W) or Ctrl + Backspace does nothing.

### ISSUE THREAD

**Issue by jens1o** [jwilm/alacritty#2930]
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | Windows     |
| Binary Version     | 0.3.3   |

# Summary
Pressing Ctrl + W (or `^W`) or `Ctrl + Backspace` does nothing.

# Behavior
The last word is not removed from shell. Instead, `^W` is written to the output.

# Expectation
Remove the last word instead.

**Comment by chrisduerr** [comment]
Which shell? If `^W` is written to the stdin of the shell, it seems like everything is working as intended.

**Comment by jens1o** [comment]
Powershell, but I expected it - like in the linux word - to just remove the last word?

**Comment by chrisduerr** [comment]
> Powershell, but I expected it - like in the linux word - to just remove the last word?

This is something that Bash does for you, it's not something the terminal emulator provides. We just tell it what key has been sent.

So if it doesn't work in cmd/powershell, it won't work in Alacritty either.

**Comment by davidhewitt** [comment]
`crtl+w` works perfectly for me with Powershell core preview 7.0.0-preview.5 . Both in Alacritty and the native terminal.

The builtin Windows powershell is... old! 😄

**Comment by chrisduerr** [comment]
Oh yeah, that's definitely a factor too. And cmd.exe is even older and supports even less unix-y features. But generally if the shell supports it, Alacritty shouldn't be stopping things from working properly. And if you can see ^W, that's a good sign that things should work.

**Comment by Sl-L** [comment]
I'm having the same issue, but Ctrl + Backspace works in cmd but not in alacritty

**Comment by vimsux** [comment]
Ctrl-Backspace does not work for me for either the PowerShell v5.1 (Win10 default) or v7.1.4
It does not  print anything, just deletes a single character.

**Comment by dominicpalmer** [comment]
Issue is still present. Ctrl+W and Ctrl+Backspace are printing "^W" to stdin via Alacritty, but from a Powershell window the same commands delete a word backwards - the intended result.

**Comment by maxreuben** [comment]
In alacritty, at least in Linux, the keybinding for delete previous word is Alt+Backspace, not Ctrl+Backspace. It'd be nice if there was a way to switch that though. If anyone knows how to, please let us know.

**Comment by arclaxton** [comment]
On my system, powershell would delete words when I pressed `ctrl+backspace` but not `ctrl+w`.
Alacritty had no problem relaying the `ctrl+w` sequence (which my powershell did nothing with) but `ctrl+backspace` from alacritty only deleted a single character.

I was able to teach powershell about `ctrl+w` by adding the following to my profile.ps1:
`Set-PSReadLineKeyHandler -Chord ctrl+w -Function BackwardDeleteWord`
Now I can delete words using powershell with alacritty. I think it is still an issue that `ctrl+backspace` works in plain PS but not from alacritty, but I am happy using the bash-flavored shortcut.

**Comment by tahir-hassan** [comment]
# To bind Control-BackSpace to End-of-Transmission-Block

I got this solution from https://github.com/microsoft/terminal/issues/755:

```
  - { key: Back, mods: Control, chars: "\x17" }
```

This works in both PowerShell, and when you launch Neovim too.

# Other useful PowerShell-related Key-bindings

```
  - { key: Space, mods: Control, chars: "\x00" }
  - { key: Back, mods: Control, chars: "\x17" }
  - { key: Home, mods: Shift, chars: "\x1b[1;2H" }
  - { key: End, mods: Shift, chars: "\x1b[1;2F" }
```

# How to find Keybindings

To find the keybindings, if you install XTerm on WSL, and do `showkey -a`, after pressing Shift+Home for example, it will print `^[[1;2H` together with the individual character codes.  You replace the beginning `^[` with `\x1b` and keep the rest.  For Control+W, `showkey` will print, in the last column, `0x17` (replace `0x` with `\x`), and that is what you want to map Control+Back to.
