### ISSUE TITLE
spacemacs no-window mode displays messy codes

### ISSUE THREAD

**Issue by SchrodingerZhu** [jwilm/alacritty#2933]
Which operating system does the issue occur on?
ArchLinux 5.3.7-arch1-1-ARCH

If on linux, are you using X11 or Wayland?
X11, both nvidia-xrun mode and normal x11 with intel driver.

![codes](https://user-images.githubusercontent.com/20108837/67740932-8066e500-fa52-11e9-80a4-6dc3acd4c1c7.png)

**Comment by chrisduerr** [comment]
These characters are usually used for box drawing. If Alacritty wouldn't be able to handle them, they'd render as missing glyphs, but for you it looks like the shell is printing placeholders intentionally.

Have you tried this setup in other terminal emulators?

**Comment by SchrodingerZhu** [comment]
Konsole seems to yield the same as Alacritty.

Spacemacs should output "Spacemacs" at these points using box making characters.

**Comment by chrisduerr** [comment]
> Possibly an issue of spacemacs?

Yes, that's not unlikely. Though I'm not sure if spacemacs makes any attempt to work in no-window mode.
