### ISSUE TITLE
Window can't restore or minimize after Command+H on macOS

### ISSUE THREAD

**Issue by pass86** [jwilm/alacritty#2934]
# System
macOS

# Summary
Window can't restore or minimize after Ctrl+H on macOS

# Behavior
Open Alacritty
Command + H
Click Alacritty icon on Dock, window can't restore
Click the yellow minimize button, window can't minimize

**Comment by chrisduerr** [comment]
This is a duplicate of https://github.com/jwilm/alacritty/issues/1465.
