### ISSUE TITLE
Ctrl+Shift shortcuts not working in tmux

### ISSUE THREAD

**Issue by zkaiwen** [jwilm/alacritty#2940]
Which operating system does the issue occur on?
macos and linux

If on linux, are you using X11 or Wayland?
X11

I have a shortcut with Ctrl+shift+arrow keys to easy adjust and resize window panes but the shortcut isn't working. It works on iterm and the default regular linux terminal.

**Comment by chrisduerr** [comment]
Which version of Alacritty are you using? I'm pretty sure this shouldn't happen in the latest master anymore.

**Comment by zkaiwen** [comment]
Latest release. 0.33

**Comment by chrisduerr** [comment]
This has been fixed in https://github.com/jwilm/alacritty/issues/2688.
