### ISSUE TITLE
Alacritty is fuzzy after screen lock

### ISSUE THREAD

**Issue by agriffis** [jwilm/alacritty#2941]
> Which operating system does the issue occur on?

Fedora 31 with alacritty built from git (v0.3.3-98-gb3afb97)

> If on linux, are you using X11 or Wayland?

Wayland with fractional scaling enabled on GNOME 3.34

```
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
```

and then set scaling factor to 150% in GNOME settings.

Here is how a terminal looks when I start it:

![Screenshot from 2019-10-31 12-41-50](https://user-images.githubusercontent.com/50637/67968378-a53b9380-fbdd-11e9-85c4-cd72c678db8d.png)

and here is how it looks after the screen locks and shuts off, then comes back after unlocking:

![Screenshot from 2019-10-31 12-41-27](https://user-images.githubusercontent.com/50637/67968429-bdabae00-fbdd-11e9-9449-31503dc3c97d.png)

You have to open those full-size and you'll see the difference in the text rendering at the top left of the terminal.

Also the terminal originally had 75 lines and after unlocking the screen only has 73 lines...

**Comment by chrisduerr** [comment]
I'd assume this gets fixed when the window is resized in any way?

**Comment by agriffis** [comment]
> I'd assume this gets fixed when the window is resized in any way?

Sometimes this fixes it, sometimes not.

> Does this happen without fractional scrolling enabled?

Not sure. I disabled fractional scaling, and it hasn't happened yet.

However here's another case where it happens, without fractional scaling:
1. start alacritty with scaling set to 100%
2. change scaling to 200%
3. alacritty is fuzzy, and resizing **doesn't** fix it

**Comment by chrisduerr** [comment]
This sounds a bit like https://github.com/jwilm/alacritty/issues/2886 but for Wayland.

Can you share the output of `alacritty -v` when trying to change the DPI while it's running?

**Comment by kchibisov** [comment]
This is a known upstream bug https://github.com/Smithay/client-toolkit/issues/81

**Comment by kchibisov** [comment]
probably dup of #1801
