### ISSUE TITLE
Selecting a block doesn't work

### ISSUE THREAD

**Issue by varac** [jwilm/alacritty#2949]
> Which operating system does the issue occur on?

Ubuntu 19.10

> If on linux, are you using X11 or Wayland?

Wayland (Sway)

I can't select a block of text using Ctrl+Shift+left mouse button. In other terminals it works like this.

**Comment by chrisduerr** [comment]
Have you tested the latest master?

**Comment by varac** [comment]
@chrisduerr No I haven't, I'm using `0.3.3~1560809133~19.04~fdf1b7c` from the deb repo - should this be fixed in latest master, or does it work for you ?

**Comment by chrisduerr** [comment]
> should this be fixed in latest master

Yes, that's correct.

**Comment by varac** [comment]
@chrisduerr Do you mind releasing a newer version ? Latest release 0.3.3 is from Jun 16th. Thx !

**Comment by chrisduerr** [comment]
We're working on it.
