### ISSUE TITLE
Prompt skips after first Lose Window Focus event on latest master (93e87eb)

### ISSUE THREAD

**Issue by pappasam** [jwilm/alacritty#2953]
Which operating system does the issue occur on? Linux Mint 19.2

If on linux, are you using X11 or Wayland? X11

Shell: Zshell

After the first lose-focus event, input events aren't properly handled by alacritty. Regular keystrokes are generally lost and the terminal experience becomes quite stuttered.

Please see below for screen / key cast for a simple example of how "Enter" is affected after the first Lose Window Focus event:

![prompt-skips](https://user-images.githubusercontent.com/3723671/68127413-d8369d80-fee3-11e9-9629-e43a0e2d73a6.gif)

**Comment by kchibisov** [comment]
btw, could you repro by changing focus only with mouse?

**Comment by pappasam** [comment]
@kchibisov Great suggestion! Just tried it, and no, this cannot be reproduced by changing focus only with the mouse. It seems to be a keyboard-only focus-change issue.

**Comment by kchibisov** [comment]
Does pressing `alt`(just without anything) after switching to alacritty fixes the issue?

**Comment by pappasam** [comment]
@kchibisov yes, it does!

**Comment by kchibisov** [comment]
duplicate #2906
