### ISSUE TITLE
Incorrect rendering on launch when offset is set

### ISSUE THREAD

**Issue by tonyfinn** [jwilm/alacritty#2958]
Which operating system does the issue occur on?

macOS Catalina

I'm running alacritty 0.3.3 installed from homebrew. I had adjusted offset in the config file to increase line spacing. Since upgrading from 10.14 to 10.15.1, alacritty now renders incorrectly. The initial text is cut off, and running a command indicates several lines are missing. e.g., here is `ls` output with offset.y = 4 and a config file with the only other edits being to colours: 

![Screenshot 2019-11-05 at 11 00 12](https://user-images.githubusercontent.com/1097073/68202411-9842e980-ffbb-11e9-950b-78bd4b1ebf79.png)

It may also be worth noting that the text appears vertically stretched. Setting offset.y back to 0 prevents this issue. This can also be worked around by increasing then decreasing font size with the cmd-+/cmd-= shortcut, as with https://github.com/jwilm/alacritty/issues/2679 (which is about the same issue occuring with SimpleFullScreen, which I have not enabled). It did not occur on 10.14

**Comment by chrisduerr** [comment]
Could you try the latest master? It's possible that 0.3.3 can't handle DPI correctly.

**Comment by tonyfinn** [comment]
I built the latest master and it appears to be working correctly.

**Comment by chrisduerr** [comment]
Yeah, that's what I would have expected. Will be fixed with the next release then, thanks for the feedback!
