### ISSUE TITLE
Arrow keys suddnely stop working.

### ISSUE THREAD

**Issue by ngortheone** [jwilm/alacritty#2959]
Archlinux, X11, i3
Latest master build

Once in a while I notice that arrow keys just stop working. While they still work in other instances of Alacritty and in other applications. So far I did not find any workarounds, so I just close and re-open the terminal.

**Comment by kchibisov** [comment]
Duplicate #2906 

Just press your latest modifier to fix this.

**Comment by ngortheone** [comment]
thanks
