### ISSUE TITLE
Modes. 

### ISSUE THREAD

**Issue by mbrumlow** [jwilm/alacritty#296]
I am working on cursor movements in vttest and need to add some more terminal modes. Right now modes are one of 8 bits. @jwilm do you have any issue if I bump that to 32bits? Or do you think this should be handled some other way?

**Comment by jwilm** [comment]
You can totally increase that to whatever size needed. The terminal mode is only kept on the `Term` struct (one instance) whereas cell mods are repeated per `Cell`.

**Comment by jwilm** [comment]
Were you talking about the 80 and 132 column modes? I'm not interested in supporting those, and it seems even modern xterm doesn't.

Aside from those modes, we are currently passing cursor movement tests, and most of the screen feature tests (no "light" mode).

**Comment by jwilm** [comment]
Anyway, I think this can be closed since yes, we can definitely add more modes to the term::Mode flags.
