### ISSUE TITLE
[need advice] Suddenly, Alacritty stopped displaying italics

### ISSUE THREAD

**Issue by for-coursera** [jwilm/alacritty#2963]
*OS*: macOS 10.11

Most likely, it has nothing to do with Alacritty but I just hope that someone with experience will be able to point me somewhere...

The problem: I use `terminfo` entries generated pretty much the usual way (described [here](https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/), for example), everything was OK, and then suddenly today I noticed that Alacritty stopped displaying italics. The very same setup works just fine with iTerm (and, of course, both Alacritty and iTerm have the same `$TERM` set, `xterm-256color-italic`).

Also, possible tests, like `echo -e "\e[3mitalics\e[23m"` or ```echo `tput sitm`italics`tput ritm` ```   fail in Alacritty. As well as for, example, [this testing script](https://gist.githubusercontent.com/hellricer/e514d9615d02838244d8de74d0ab18b3/raw/7e5be20969b7274d64a550b9132fee5268cff2d8/terminal-testdrive.sh) – while bold, dim, underline, reverse, strikethrough and invisible entries are absolutely fine.

So, my question would be the following: what do yo think, what can it be? I'm almost certain it is my configuration to blame but hell, where should I start looking? :) Some cache may be?

(Another problem is that  don't use Alacritty on a daily basis, so I can't really say when did this happen...)

Thanks.

**Comment by kchibisov** [comment]
Could you try installing `alacritty` terminfo (take a look at INSTALL.md on how to install it), then run `alacritty --config-file /dev/null` and retest?

Basically there could be two problems:
- 1 Bad terminfo
- 2 Font doesn't have italics or you've misspelled font style for italics in case you've added it explicitly.

**Comment by for-coursera** [comment]
It seems like the culprit was me setting the style to `style: Italic` instead of `style: Regular Italic`.

Thanks for the info on `alacritty` terminfo and for the hint with `--config-file /dev/null`: I thought I was going insane, and these did help me to test the situation and to then to locate the problem :)
