### ISSUE TITLE
Could we have a flag to generate the default config file

### ISSUE THREAD

**Issue by lespea** [jwilm/alacritty#2968]
Which operating system does the issue occur on? N/A

Since the config is no longer generated by default (#2820) could we get a flag that generates it in the proper location?  It's pretty annoying have to find the most recent config in github and put it in the right place (especially on windows).

**Comment by chrisduerr** [comment]
I'd say it's actually not encouraged to copy over the whole default configuration file. Especially if you don't have the desire to change it at all.

You also make it sound like a regular thing, is that the case? If so, why do you need to do this regularly?

**Comment by kchibisov** [comment]
This idea was discussed and rejected.

I don't really think that this option make sense for end users honestly, since you're likely obtain your config once and just sync it on demand (and also keep minimum things in it). I also don't think that it's really hard to copy destination location for Windows from our README.

**Comment by lespea** [comment]
I setup new machines pretty regularly, I guess maybe most people don't.  Imo it's much easier for people to tweak the settings they want by scrolling through the default config and changing what they want instead of trying to find just the settings they want to change (which they probably don't even know what's all available).  If you're against it it's fine I'll continue to just do it manually; just figured I'd open an issue to have the discussion.

**Comment by kchibisov** [comment]
You can always write a simple script to setup new machines, so remembering a config location wouldn't be a problem here. I also think that you're carrying "your" config and not a default one. In case your fully relying on default, then you don't even need to copy it.
