### ISSUE TITLE
Content doesn't resize when Amethyst changes window size

### ISSUE THREAD

**Issue by adamtabrams** [jwilm/alacritty#2969]
Which operating system does the issue occur on?
**Mac OS**

I'm using the Amethyst tiling window manager. When I spawn a new instance, focus shifts to the new window, and the original window is sized down. But the font remains squished on the original window until I put focus back on the original. This does not happen with other terminals (Terminal.app and iTerm2). 

Here are some screenshot of the issue:
![ScreenBefore](https://user-images.githubusercontent.com/39201397/68606143-6924f000-0473-11ea-9128-c3265e565a1d.png)
![ScreenAfter](https://user-images.githubusercontent.com/39201397/68606153-6cb87700-0473-11ea-8357-afb2d30eaf25.png)

**Comment by chrisduerr** [comment]
Can you reproduce this on the latest master?

**Comment by adamtabrams** [comment]
@chrisduerr I just installed from the latest master, and I cannot reproduce the issue 👍. Do you know which release likely fixed this? And do you know when that might be available via Brew Cask?

**Comment by chrisduerr** [comment]
> Do you know which release likely fixed this?

This hasn't been released yet, however we're actively working on making a new release within the next ~2 weeks I'd say (definitely under a month).

> And do you know when that might be available via Brew Cask?

The cask is not maintained by any Alacritty collaborator, but instead an external maintainer. I would expect it to update once the new version is released, however it might be delayed until the maintainer has time to test Alacritty sufficiently.

**Comment by chrisduerr** [comment]
This was originally handled in https://github.com/jwilm/alacritty/issues/1125.
