### ISSUE TITLE
All colored, bold text displayed as bright (Windows)

### ISSUE THREAD

**Issue by markuspeloquin** [jwilm/alacritty#2979]
Which operating system does the issue occur on? Windows 10, Alacritty 0.3.3. (I'm pretty sure this is a Windows issue since Alacritty on my Linux host works fine.)

I've fiddled with `draw_bold_text_with_bright_colors`, setting it to `false`, which it obviously always should be. Bold text works fine, and so does colored text. The 256 ANSI colors all work as expected (normal, bright, 6x6x6, greys).

But combining bold and any color 0--7 produces the bright color in 8--15. This is super annoying with Solarized, which uses the 'bright' colors for additional greys, plus orange and violet.

```sh
print '\e[1mbold \e[0;34mblue \e[1mbold blue'
```

![bright](https://user-images.githubusercontent.com/75588/68847095-ed998d80-0682-11ea-85d2-53edf805cc97.png)

Honestly, I'd rather not have bold. I also tried switching `enable_experimental_conpty_backend` to `true`, but it didn't help: uncolored bold is invisible, bold+colored becomes bold+bright, and somehow `\e[1;38;5;4mbold blue` does actually work correctly.

**Edit** Also worth noting, I'm starting it with the arguments `--command wsl ~ --distribution Debian`, which starts a Zsh login shell in my WSL home directory. My TERM ends up set to xterm-256color.

**Comment by kchibisov** [comment]
The interesting part is why your text is neither blue, nor bold on a screenshot. I can't repro this issue with your escape on Linux, so I guess it's something Windows related. Could you post a `ref-test` (`alacritty --ref-test`, only recording part)?

**Comment by chrisduerr** [comment]
> I also tried switching enable_experimental_conpty_backend to true

When running Alacritty using `alacritty -v` it should provide a log message that says which backend (conpty/winpty) was actually initialized. Could you check that to confirm ConPTY was actually used?

**Comment by markuspeloquin** [comment]
> The interesting part is why your text is neither blue, nor bold on a screenshot. I can't repro this issue with your escape on Linux, so I guess it's something Windows related. Could you post a `ref-test` (`alacritty --ref-test`, only recording part)?

@kchibisov It actually **is** bright blue, which in Solarized is sort of a red-shifted grey: https://www.google.com/search?q=%23839496 . (I can't say I understand what's going on with the 'bright' Solarized colors but I love the normal ones; good for Solarized-specific themes, I suppose.) But yeah, still not bold. I think it probably is windows, since it seems Alacritty uses [winpty](https://github.com/rprichard/winpty) or [ConPTY](https://github.com/microsoft/terminal/tree/master/src/winconpty) to render text/colors. And those are obviously Windows-specific.

I'll run the command when I get home.

>> I also tried switching enable_experimental_conpty_backend to true
> 
> When running Alacritty using `alacritty -v` it should provide a log message that says which backend (conpty/winpty) was actually initialized. Could you check that to confirm ConPTY was actually used?

@chrisduerr I'll confirm when I get home, but the screenshot above was definitely winpty (ConPTY was disabled in the options). I observed different behavior when I set the ConPTY flag. I will also attach a screenshot of the ConPTY behavior.

**Comment by chrisduerr** [comment]
> it seems Alacritty uses winpty or ConPTY to render text/colors

WinPTY and ConPTY are as the name suggests PTYs, they have nothing to do with rendering at all. However while attempting to emulate POSIX PTYs to some degree, it appears that WinPTY/ConPTY do some non-transparent mingling in the middle, leading to them interfering with the escapes that are actually sent to Alacritty.

> I'll confirm when I get home, but the screenshot above was definitely winpty (ConPTY was disabled in the options). I observed different behavior when I set the ConPTY flag. I will also attach a screenshot of the ConPTY behavior.

You definitely do not want to use WinPTY if you have the option not to use it. ConPTY is just the better backend if it's available.

**Comment by markuspeloquin** [comment]
I tried `alacritty -v --ref-test --command wsl ~ --distribution Debian` with both values for `enable_experimental_compty_backend`. The log is below. The only difference was when using ConPTY, it said 'Conpty' instead of 'Winpty':

```
[2019-11-14 22:14] [INFO] Welcome to Alacritty
[2019-11-14 22:14] [INFO] Configuration loaded from "C:\\Users\\markus\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2019-11-14 22:14] [INFO] Device pixel ratio: 1
[2019-11-14 22:14] [INFO] Initializing glyph cache...
[2019-11-14 22:14] [INFO] ... finished initializing glyph cache in 0.0202888s
[2019-11-14 22:14] [INFO] Estimated DPR correctly, skipping resize
[2019-11-14 22:14] [INFO] Width: 568, Height: 398
[2019-11-14 22:14] [INFO] Cell Size: 7 x 13
[2019-11-14 22:14] [INFO] Padding: 4 x 4
[2019-11-14 22:14] [INFO] PTY Dimensions: Line(30) x Column(80)
[2019-11-14 22:14] [INFO] Using Winpty agent
[2019-11-14 22:14] [INFO] Initialisation complete
```

I also tried a more thorough test of bold/color, so all the inconsistencies are visible. I'm referring to 4-bit color as using the value 30-37 or 90-97, and 8-bit color as using 38;5;0-15. I also use the `0` code each time to reset. In order:

1. bold
2. 4-bit blue
3. 8-bit blue
4. bold, 4-bit blue
5. bold, 8-bit blue
6. 4-bit bright blue
7. 8-bit bright blue
8. bold, 4-bit bright blue
9. bold, 8-bit bright blue

```sh
print '\e[0;1mBOLD \e[0;34mBLUE-0 \e[0;38;5;4mBLUE-1 \e[0;34;1mBOLD-BLUE-0 \e[0;38;5;4;1mBOLD-BLUE-1 \e[0;94mBR-BLUE-0 \e[0;38;5;12mBR-BLUE-1 \e[0;94;1mBOLD-BR-BLUE-0 \e[0;38;5;12;1mBOLD-BR-BLUE-1'
```

![terminals](https://user-images.githubusercontent.com/75588/68921209-cd260d80-072c-11ea-948e-c2b0a9f3d9ba.png)

The terminals shown above are respectively WSLtty, Alacritty+winpty, Alacritty+ConPTY.

A final thing I tried was to set `TERM: alacritty` in alacritty.yml (I do have a terminfo entry for Alacritty), but this doesn't make it to my shell. I guess I'm sticking to WSLtty for the foreseeable future.

**Comment by kchibisov** [comment]
@markuspeloquin `--ref-test` should create a file called `alacritty.recording` in the directory where you've launched alacritty, so we need it from `winpty` and from `conpty`.

**Comment by Perlence** [comment]
I noticed several issues with the ConPTY backend, one of them is aforementioned bold text rendering. I started `wsl` in Alacritty and executed `termcolors`, source code of which you can check in [this gist](https://gist.github.com/Perlence/b841999bb2ce00a62d42f5dbd7ca74c5). On the left is Alacritty 0.4.0, and on the right is mintty 3.0.6. Mintty has **Text** -> **Show bold as colour** disabled.

![image](https://user-images.githubusercontent.com/1044300/69659884-33e1ea00-1090-11ea-8085-f0d7487085d6.png)

Here's the `alacritty.recording` with ConPTY enabled: [alacritty.txt](https://github.com/jwilm/alacritty/files/3893351/alacritty.txt)

Here's my `alacritty.yml`:
```yml
font:
  normal:
    family: Iosevka Term
    style: Regular
  italic:
    family: Iosevka Term
    style: Italic
  size: 9.0
draw_bold_text_with_bright_colors: false
colors:
  primary:
    background: '0xfdf6e3'
    foreground: '0x657b83'
  normal:
    black:   '0x002b36'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'
  bright:
    black:   '0x073642'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
selection:
  save_to_clipboard: true
enable_experimental_conpty_backend: true
```

**Comment by chrisduerr** [comment]
If you look at the `alacritty.txt`, you can clearly see that the PTY is sending `\e[1m\e[97m` to us, which means it's actually requesting us to use the bright colors. So this is an issue that needs to be fixed in ConPTY.

Can you try to use `TERM=cygwin` @Perlence? That has resolved some issues in the past. If that doesn't work though, there's nothing Alacritty can do.

**Comment by Perlence** [comment]
Do you mean that ConPTY sees `\e[1m` and adds `\e[97m` based on some internal logic? Meaning that this logic needs to be fixed.

Unfortunately, setting `TERM=cygwin` didn't help.

**Comment by chrisduerr** [comment]
> Do you mean that ConPTY sees \e[1m and adds \e[97m based on some internal logic? Meaning that this logic needs to be fixed.

Exactly and this wouldn't be the first time. So it has to be reported upstream.
