### ISSUE TITLE
Don't delete lines above the cursor on CSI Ps M

### ISSUE THREAD

**Issue by kchibisov** [jwilm/alacritty#2984]
`Alacritty` should clamp `Ps` to not go above cursor, so if you're on the bottom line, typing `echo -e '\e[1000;M'` shouldn't delete all the thing above and should be clamped to `1`.

P.s. All the other terminals clamp it(vte based, xterm, kitty).

**Comment by nixpulvis** [comment]
Ah, interesting, thanks for investigating this.

**Comment by chrisduerr** [comment]
Should be fixed in https://github.com/jwilm/alacritty/pull/2985.
