### ISSUE TITLE
Windows Performance - Initial Stuttering on New Input

### ISSUE THREAD

**Issue by CypherZealot** [jwilm/alacritty#2991]
**Which operating system does the issue occur on?**
Windows 10 Pro version 1909

## Summary

Seeing a performance issue where initial input will _"stutter"_ and then smooth out. Same behavior for WinPTY and ConPTY backends.

## How the issue was verified

1. Use a minimal `alacritty.yml`
2. Hold any alphanumeric key to repeat its input into any shell prompt
3. Backspace what was printed
4. Repeat 2 and 3

With the above steps the observed behavior is that the initial keyboard input will _"stutter"_ and then smooth out if the key is pressed is held.

Another way to observe this _"stuttering"_ is when moving the Alacritty.exe window with the mouse (especially on a high-refresh-rate monitor). Initially when the window is moved it will appear to stutter and if the user continues to move the window around, without unclicking it, the movement of the window will begin to smooth out.

In contrast, this _"stuttering"_ is **not** observed when using the native Windows conhost.exe/cmd.exe terminal, with _any_ shell.

### What was tried

1. Tried to disable all dynamic behavior configuration options
2. Tried increasing the priority of process and subprocesses
3. Running process as administrator

Tried all variations of the following boolean config values trying to stop any dynamic configuration. 

```yaml
# alacritty.yml

enable_experimental_conpty_backend: true
dynamic_title: false
live_config_reload: false

mouse:
  hide_when_typing: false
```

#### A strange workaround

Strangely, I went to record this behavior with OBS and, atleast with the keyboard input, the _"stuttering"_ did not occur simply by OBS having been a running concurrent process (not even setup with _any_ sources, i.e. not capturing or recording anything).

Even when I close OBS, any Alacritty.exe processes that were running when OBS was running continue to perform better. If I start a new Alacritty.exe process, the new window will have the same stuttering behavior but the previous instances will continue to perform better.

The behavior described above where moving the window with the mouse initially stutters and smooths out does still occur when OBS is capturing the window, but that is not a big deal as long as keyboard input is performant.

---

Any idea what is going on here?

I will test on other systems soon, but the one initially tested is the most graphically powerful.

---

**EDIT 1:** The behavior with OBS is not consistent. Now I am only seeing a performance benefit to OBS if it is a foreground application (not minimized).

**Comment by CypherZealot** [comment]
The behavior with OBS is not consistent. Now I am only seeing a performance benefit to OBS if it is a foreground application (not minimized).

**Comment by CypherZealot** [comment]
I disabled G-Sync and the issue went away entirely.

**Comment by kchibisov** [comment]
Maybe driver is doing something? We already had some problems from nvidia driver on windows like this https://github.com/jwilm/alacritty/issues/2287 , could you try to tweak its setting for alacritty, idk. You couldn't see this issue with cmd.exe because it doesn't use GPU, probably.

**Comment by CypherZealot** [comment]
I tend to have to disable G-Sync in everything except games, even Firefox performance is poor with G-Sync enabled (e.g. screen tearing when scrolling pages).

I am going to close this, I don't think there is any improvement to be made here.
