### ISSUE TITLE
Panic on starting on Windows

### ISSUE THREAD

**Issue by edyu** [jwilm/alacritty#2999]
Which operating system does the issue occur on? I've tried both on 0.3.3 and 0.4.0-rc2. I've also tried both using chocolatey or download standalone.

Windows 10

This is on v0.4.0-rc2

panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1165:5

**Comment by edyu** [comment]
This is how it was run:
<pre>
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> dir


    Directory:
C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable       
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/20/2019  3:22 PM        5419520 alacritty.exe      -a---          11/20/2019  3:22 PM         727552 winpty-agent.exe   
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> .\alacritty.exe
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1165:5
</pre>

**Comment by chrisduerr** [comment]
Are you running ConPTY or WinPTY? Is this a regression, or has this been broken before?

If you are using WinPTY, please make sure you've got winpty installed as documented in the instructions.

**Comment by edyu** [comment]
I'm using ConPTY.
I'm not sure whether this is related:
I had rust and alacritty both installed using chocolatey.
I removed rust (or at least tried to because I realized I need a newer version so wanted to install rustup instead). Somehow, alacritty stopped working.
I then removed alacritty on chocolaty and downloaded alacritty from github directly. In both cases, I have the same error.

**Comment by edyu** [comment]
I ran into some problems when removing rust using chocolatey as it just hangs for a long long time. I had to manually remove rust. As I said, I'm not certain this is related but it could be. Just giving enough context.

**Comment by chrisduerr** [comment]
Can you run the Alacritty executable from powershell with the `-v` flag and verify that ConPTY is actually used?

**Comment by edyu** [comment]
<pre>
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> dir


    Directory:
C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable       
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          11/20/2019  3:22 PM        5419520 alacritty.exe      -a---          11/20/2019  3:22 PM         727552 winpty-agent.exe   
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> .\alacritty.exe
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1165:5
</pre>

**Comment by edyu** [comment]
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> .\alacritty.exe -v
PS C:\Users\edlyu\Downloads\Alacritty-v0.4.0-rc2-windows-portable> created log file at "C:\Users\edlyu\AppData\Local\Temp\Alacritty-17268.log"
[2019-11-20 15:43] [INFO] Welcome to Alacritty
[2019-11-20 15:43] [INFO] Configuration loaded from "C:\Users\edlyu\AppData\Roaming\alacritty\alacritty.yml"
[2019-11-20 15:43] [INFO] Device pixel ratio: 1.25
[2019-11-20 15:43] [INFO] Initializing glyph cache...
[2019-11-20 15:43] [INFO] ... finished initializing glyph cache in 0.089602s
[2019-11-20 15:43] [INFO] Cell Size: 12 x 32
[2019-11-20 15:43] [INFO] Padding: 0 x 0
[2019-11-20 15:43] [INFO] Width: 1824, Height: 1121
[2019-11-20 15:43] [INFO] PTY Dimensions: Line(35) x Column(152)
panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1165:5

**Comment by chrisduerr** [comment]
@edyu Which version of Windows 10 are you running and do you have the winpty executable in the same folder as the Alacritty executable?

**Comment by edyu** [comment]
@chrisduerr I'm running Windows 10 Home 1903. OS build 19025.1. Yes I do hae the winpty in the same folder as Alacritty executable.

**Comment by edyu** [comment]
Interestingly that once I removed my alacritty.yml it started working. Let me figure out what config is causing it to panic.

**Comment by edyu** [comment]
I found the culprit.
I set the working_directory: '~'
which caused the error. I assume this is human error? I guess wsl is technically under windows and windows probably don't understand '~'.

**Comment by chrisduerr** [comment]
The working directory is the working directory of Alacritty, not the shell. Alacritty launches the shell, so when launching Alacritty on Windows, the working directory will have to be a valid Windows path.

Also `~` is not an actual path on unix either, the shell just expands it to the user's home directory before passing it to the application. So `alacritty --working-directory '~'` doesn't even work on unix, since that's not a valid path. However since this is usually executed from a shell, the expansion is done for you.
