### ISSUE TITLE
Selection snapping with clicks

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#30]
Double clicking should highlight a word, triple clicking should highlight a line.

**Comment by dannydulai** [comment]
Note that dragging after those clicks should stay in that mode until you let go.

When selecting a word, make sure you add a config item to determine which characters cause word-breaks.

**Comment by jwilm** [comment]
Thanks for the tip; I would not have known to do that.

**Comment by dannydulai** [comment]
It's also noteworthy that tmux has this same problem. Someone is working on a patch for tmux already.

**Comment by theothermike** [comment]
Also, the action of highlighting should put it in the system clipboard so I can easily paste to other apps same way I paste the highlighted content inside alacritty

**Comment by dannydulai** [comment]
@theothermike -- that should be an option, not everyone wants that to happen automatically.

**Comment by theothermike** [comment]
@dannydulai  agreed, should definitely be an option

**Comment by samdphillips** [comment]
Some terminals that I have used use a regular expression to let the user define what a word is for double-click selection.

**Comment by lord-re** [comment]
This feature is implemented.
Time to close this issue ?

**Comment by jwilm** [comment]
Ah, yeah. Thanks @lord-re
