### ISSUE TITLE
Alacritty crashes on lock screen event

### ISSUE THREAD

**Issue by rbjorklin** [jwilm/alacritty#3004]
I'm running Alacritty built on commit 5ea4fb6034fe under Wayland on Fedora 31 and I'm seeing crashes every time I lock the screen for a couple of minutes.

How would I go about providing more information?

**Comment by kchibisov** [comment]
Try`coredumpctl gdb alacritty` and then provide us the output of `bt full`

**Comment by kchibisov** [comment]
I feel like it's a duplicate of #2156 .

**Comment by rbjorklin** [comment]
I agree, my github issue search foo is apparently not strong enough. Thanks for pointing me in the right direction @kchibisov!
