### ISSUE TITLE
Dock Icon too Big on macOS

### ISSUE THREAD

**Issue by kcmannem** [jwilm/alacritty#3005]
Which operating system does the issue occur on?
macOS

The app icon that appears in the dock is much larger then other icons. Here's a comparison of it along side other terminal apps. It looks out of place.

![Screen Shot 2019-11-21 at 7 50 38 PM](https://user-images.githubusercontent.com/9054726/69388864-50e57a00-0c98-11ea-8bf5-c8d84c0691da.png)

**Comment by chrisduerr** [comment]
I haven't noticed this myself yet, but why does Alacritty's icon need to be the exact same size as iTerm or other terminal icons? I don't see the connection here.

Every icon has a certain amount of space it can use and I don't see why there would be anything wrong with Alacritty using all the space it has, instead of artificially introducing transparent borders.

**Comment by kcmannem** [comment]
@chrisduerr if you compare it to other apps on the dock, it feels out of place and stands out.

![Screen Shot 2019-11-21 at 8 08 23 PM](https://user-images.githubusercontent.com/9054726/69389674-bcc8e200-0c9a-11ea-8114-a6c5c56bab65.png)

**Comment by chrisduerr** [comment]
Well it's not a round icon, so obviously it's going to take up more surface area than the round icons. However, when looking at the height of the icons, I don't see much difference for example.

There are boundaries setup by macOS and Alacritty lies flat within those. I'm not sure why we'd introduce any other artificial restrictions. If other applications decide to be a bit smaller, than that's their choice, just how we should be able to take up all the place we want.

I don't see why we'd let the design of other icons affect our choices.

**Comment by kcmannem** [comment]
I don't know if Apple provides any guidelines on icon sizes and how to use negative space. But just noticing the other square-ish icons Apple designs it self, it sizes them by weight to be uniform with the rest of the possible icon shapes(square, circle, objects) present in the default apps.

**Comment by Ckath** [comment]
if you dont like the default icons why dont you just use a custom icon pack of some kind? that way you can have everything looking uniform.

**Comment by chrisduerr** [comment]
I don't really see any reason for action here. Our icon is not exceeding the limits set by macOS and what other icons decide to do shouldn't be our business.
