### ISSUE TITLE
Unable to render text colors

### ISSUE THREAD

**Issue by jerryc05** [jwilm/alacritty#3010]
- Which operating system does the issue occur on?
Windows 10 + Alacritty `v0.4.0-rc4`

When executing `rustup default nightly`, I get
```console
?[1minfo: ?[0musing existing install for 'nightly-x86_64-pc-windows-msvc'
?[1minfo: ?[0mdefault toolchain set to 'nightly-x86_64-pc-windows-msvc'

  ?[1mnightly-x86_64-pc-windows-msvc unchanged?[0m - rustc 1.41.0-nightly (0f0c640e0 2019-11-17)
```

**Comment by chrisduerr** [comment]
Are you running in ConPTY mode?

**Comment by jerryc05** [comment]
@chrisduerr 

> Are you running in ConPTY mode?

i think i'm running in "default" mode. 
how can i check?

**Comment by chrisduerr** [comment]
In the configuration file, there's an `enable_experimental_conpty_backend` config that you want to set to `true`.

Then try running `alacritty -v` from a terminal and it will print at startup which backend is actually loaded (to make sure your system supports it).

**Comment by jerryc05** [comment]
@chrisduerr Setting `enable_experimental_conpty_backend` to `true` fixed the problem. thx!
