### ISSUE TITLE
Chinese file name displayed as '?' under MacOS Mojave

### ISSUE THREAD

**Issue by cxlab1** [jwilm/alacritty#3015]
MacOS Mojave 10.14.6, tried both prebuild version and build from source, all the Chinese are displayed as '?', is there any other configuration needed ?

**Comment by chrisduerr** [comment]
That sounds like you might not have any fonts installed which can display these chinese characters, which would surprise me under macOS.

Which shell are you using and could you share a screenshot, just to confirm that what I think you're seeing is correct?

The most likely explanation would probably be locale, which can be tested by starting Alacritty from iTerm. Could you try that?

**Comment by cxlab1** [comment]
Thanks Chrisduerr, just tried launch it from iTerm and it works, all Chinese displayed perfectly, so how to fix the locale issue? by the way I am using bash.

**Comment by chrisduerr** [comment]
Do you have a custom shell setup, or are you running with the default configuration file without any command line arguments?

**Comment by cxlab1** [comment]
There is only some path export in my ~/.bash_profile, should be no special shell setup, and also iTerm works fine since they will use the same shell setup.

I tried prebuild dmg package and by default it should not have command args, and also the default config file is ~/.config/alacritty/alacritty.yml, I tried remove this config but still same issue.

**Comment by cxlab1** [comment]
By compare the env output of iTerm and Alacritty, there is missing variable as below.
LC_CTYPE=UTF-8

It works fine once add this variable.
