### ISSUE TITLE
Text rendering looks wrong

### ISSUE THREAD

**Issue by dewijones92** [jwilm/alacritty#3017]
Which operating system does the issue occur on? Arch linux

If on linux, are you using X11 or Wayland? X11

Please help :D 

![2019-11-25_11-15](https://user-images.githubusercontent.com/659767/69536770-8cbd5f80-0f76-11ea-8d11-3c86ce506817.png)

**Comment by kchibisov** [comment]
You're using non monospace font, please use a monospace one. Like `DejaVu Sans Mono` or use an alias name `monospace` to request system default monospace font.
