### ISSUE TITLE
Copy no longer works with tmux

### ISSUE THREAD

**Issue by fxha** [jwilm/alacritty#3021]
- OS: Fedora 30 on Wayland
- Last known working version: alacritty 0.3.3 (cc3e4d3)
- Current: alacritty 0.4.1-dev (9406895)

I cannot longer copy text from the terminal after updating Alacritty, neither by my shortcut or selecting text via mouse cursor. Just launch `alacritty` (or `env LC_CTYPE=en_US.UTF-8 WINIT_HIDPI_FACTOR=1.0 WAYLAND_DISPLAY= alacritty` on Wayland) and try to copy text from terminal.

**Comment by chrisduerr** [comment]
Was copy-pasting working correctly for you with 0.3.3, across Wayland applications?

Also could you please state which Wayland compositor you are using?

**Comment by kchibisov** [comment]
>env LC_CTYPE=en_US.UTF-8 WINIT_HIDPI_FACTOR=1.0 WAYLAND_DISPLAY= alacritty on Wayland

Wait XWayland copy also don't work for your right?

**Comment by fxha** [comment]
> Was copy-pasting working correctly for you with 0.3.3, across Wayland applications?

Yes both worked fine but there was some issue with `xkbcommon` without setting `WAYLAND_DISPLAY=` that seem to be solved with v0.4.x.

> Also could you please state which Wayland compositor you are using?

GNOME 3.32.2

**Comment by chrisduerr** [comment]
So currently it is broken with both Wayland and XWayland mode then, right?

Could you start Alacritty from a different terminal and check if there's any output to stderr?

**Comment by fxha** [comment]
I forgot to mention, pasting still works fine but unfortunately not copying.

> So currently it is broken with both Wayland and XWayland mode then, right?

I'm not familiar with Wayland stuff but copying doesn't work raw and also not with `WAYLAND_DISPLAY=`.

> Could you start Alacritty from a different terminal and check if there's any output to stderr?

That was my first try but no error occured.

**Comment by cole-h** [comment]
Running sway `1.2-3334d11a (Nov 25 2019, branch 'master')` built with wlroots `0.8.1.r50.g5cde3592-1` I don't encounter this problem. I can copy/paste between Alacritty instances and between Alacritty and Firefox. This makes me think it's a GNOME-specific issue.

**Comment by Hau-Hau** [comment]
Same issue on Debian with xfce 4.12, Alacritty 0.4.0 (b115b90).
@kchibisov Your solution works but isn't compatible with tmux. 
On 3.3.0 coping was working without any issues.

**Comment by kchibisov** [comment]
@Hau-Hau could you try the latest master?

**Comment by fxha** [comment]
@Hau-Hau You are right, I totally forgot to mention that I'm using tmux and the issue only occur with tmux with and without Wayland on GNOME.

**Comment by chrisduerr** [comment]
> @Hau-Hau You are right, I totally forgot to mention that I'm using tmux and the issue only occur with tmux with and without Wayland on GNOME.

Oh, that makes a huge, huge difference. See https://github.com/jwilm/alacritty/pull/3038 and the original issue https://github.com/jwilm/alacritty/issues/3037.
