### ISSUE TITLE
RAM consumsion incresed in v0.4

### ISSUE THREAD

**Issue by tim77** [jwilm/alacritty#3025]
Which operating system does the issue occur on?
- Linux

If on linux, are you using X11 or Wayland?
- X11

GPU and video driver:
- [GeForce GTX 1060 6GB] driver: nvidia v: 440.31

Package:
- From [Copr](https://copr.fedorainfracloud.org/coprs/atim/alacritty/)

I did quick search and can't find similar issue, i hope not duplicate. What is worried me is that v0.4 now using more RAM. Previous version v0.3.X was around 60 Mb, new one 122 Mb right from start. Increased cache or this is a trouble somewhere?

**Comment by chrisduerr** [comment]
Could you share your configuration file? Doubled memory usage does seem significant so it's unlikely that this is just normal fluctuation between releases.

If you're willing to invest a bit more time, bisecting this would likely be very helpful, assuming that it was introduced in one specific commit.

First of all I'd like to know your output of `alacritty --version` though, does it print `alacritty 0.4.0 (b115b90)`?

**Comment by tim77** [comment]
> First of all I'd like to know your output of alacritty --version though, does it print alacritty 0.4.0 (b115b90)?

My build: alacritty 0.4.0 https://github.com/jwilm/alacritty/commit/b115b9038566d6ce0ed56f4a50c428c98e04b51a

Also i noticed this earlier, in RC versions. Just waited for final release to be sure.

> Could you share your configuration file?

Oh, this could be a reason. I noticed that now we should not ship config file and i am using my old one. Will check this soon...

**Comment by chrisduerr** [comment]
> Also i noticed this earlier, in RC versions. Just waited for final release to be sure.

Just to clear any potential misunderstandings, feel free to complain about things in RC versions! That's exactly what they are there for. :smile: 

> Oh, this could be a reason. I noticed that now we should not ship config file and i am using my old one. Will check this soon...

I'm specifically asking because of the maximum scrollback option. If the number of lines in scrollback is changed, that will of course negatively affect memory usage if those lines are ever filled.

**Comment by tim77** [comment]
@chrisduerr look like delete my old config solve this issue. But old one was almost default, just font changed and shell to fish. Now it Alacritty start with 55 Mb and keep < 70 Mb. I'll continue to watch and if everything is fine i close this issue if you don't mind. Maybe this could help other users who updated from old versions. :)

**Comment by chrisduerr** [comment]
Do you still have the old issue around? I'd be curious to take a look.

**Comment by tim77** [comment]
My old config file (converted to TXT for github support:
[alacritty-old.txt](https://github.com/jwilm/alacritty/files/3889427/alacritty-old.txt)

**Comment by chrisduerr** [comment]
Hmm, that looks pretty tame to me. I'd definitely like to compare it myself again though against the last release (0.3.3), potentially even on a few different platforms.

It looks like it could be slightly higher based on the memory usage I'm observing on my system, however it has been a while since I've run 0.3.3 and it's definitely not as big of a jump as it was for you.

**Comment by chrisduerr** [comment]
I've looked into this a bit more and I don't think there should be any issue present.

Comparing the latest master to v0.3.3 gives me a memory increase of around ~3-4MB, which is consistent with a memory increase of ~3-4MB with the windowing library we're using (glutin). These kind of changes are within reasonably fluctuations I would say, so there's no direct issue to report upstream, I'd assume that the driver changes might have affected this.

These results are consistent both for an empty and a filled grid and as far as I can tell no changes in Alacritty have lead to any significant memory increase. However thanks to changes made by @nixpulvis I believe a `reset` now clears more memory than before, saving about ~30MB when a terminal is reset after runnig `yes` in my tests.
