### ISSUE TITLE
Glitch while clearing screen (0.4.0)

### ISSUE THREAD

**Issue by faultable** [jwilm/alacritty#3026]
> Which operating system does the issue occur on?
> - Mac OS 10.14 Mojave (10.14.6)
>
> If on linux, are you using X11 or Wayland?
> - N/A

Just tested Alacritty 0.4.0 but there is some glitch while clearing screen (by using CTRL+L)

![ScreenFlow](https://user-images.githubusercontent.com/6561394/69586031-f2135e00-1013-11ea-9875-fcecd9ae27a8.gif)

Is this a bug or a feature? This problem not occurs on 0.3.0.

Config file: [`.alacritty.yml`](https://github.com/faultable/setup/blob/master/desktop/alacritty.yml)

**Comment by chrisduerr** [comment]
I'd assume this is fixed when removing the padding from your configuration file? It looks like the padding is getting reset to `0` temporarily.

**Comment by chrisduerr** [comment]
This is also probably related: https://github.com/jwilm/alacritty/issues/2226

**Comment by faultable** [comment]
> I'd assume this is fixed when removing the padding from your configuration file? It looks like the padding is getting reset to `0` temporarily.

Yes, everything is okay when I reset it to `0`. Any option to add the padding or just leave it like that?

**Comment by chrisduerr** [comment]
This seems to only be an issue no macOS, which seems a bit strange to me. I'll have to look into testing this at work where I have access to a macOS machine.

I was able to confirm #2226 on macOS, but don't think I've seen this just happen whenever the screen is cleared, so that seems a bit strange to me.

**Comment by chrisduerr** [comment]
I've tested this again on my macOS machine and while I'm still able to reproduce #2226, I'm not able to make this occur with ctrl+L.

Could you try running this simplified configuration file without any other settings?

```yml
window:
  padding:
    x: 20
    y: 20
```

**Comment by brandoniffert** [comment]
@chrisduerr I'm able to reproduce this with that simplified config. I'm on Alacritty 0.4.0 and macOS 10.15.1. Also happens when I hit cmd-0 (ResetFontSize), it will temporarily reset padding to 0 until I hit another key.

**Comment by chrisduerr** [comment]
While I'm not able to identify it 100% since I'm not able to reproduce this specific issue, I think it makes sense to track this in https://github.com/jwilm/alacritty/issues/2226, just so we don't have multiple issues sitting around.

So hopefully once I get around fixing that, we should be good.

**Comment by chrisduerr** [comment]
Oh, one additional bit of information that might be useful, what happens when running `clear`? Does that cause the same issue as Ctrl+L?

**Comment by faultable** [comment]
> Oh, one additional bit of information that might be useful, what happens when running clear? Does that cause the same issue as Ctrl+L?

its not, fortunately.

I will try to reproduce it and hopefully can send the patch. For now I will stick with this behavior since this only occurs to me.

**Comment by chrisduerr** [comment]
I'd be curious if the following binding fixes it:
```yml
  - { key: L, mods: Control, chars: "\0x0c" }
```

**Comment by faultable** [comment]
> I'd be curious if the following binding fixes it:
> 
> ```yaml
>   - { key: L, mods: Control, chars: "\x0c" }
> ```

Wow yes, but only when I commented this line:

```diff
- - { key: L, mods: Control, action: ClearLogNotice }
+ # - { key: L, mods: Control, action: ClearLogNotice }
  - { key: L, mods: Control, chars: "\x0c"  }
```

thanks!

**Comment by chrisduerr** [comment]
Good to know, thanks. Looks like `ClearLogNotice` triggers some kind of redraw/reset then, which messes things up. So just clearing the screen should resolve it for now.
