### ISSUE TITLE
select current line using keyboard without TMUX?

### ISSUE THREAD

**Issue by reckoner** [jwilm/alacritty#3027]
Which operating system does the issue occur on?

windows

If on linux, are you using X11 or Wayland?

Is it possible to use a keyboard combination like shift+Left/Right to select the text on the current input line without using TMUX?

**Comment by chrisduerr** [comment]
This will be solved with #262. It goes beyond just selection on the current line though.

There are currently some higher priority issues, but I'm personally very interested in this, so hopefully I'll be able to work on this in the nearer future.
