### ISSUE TITLE
highlighted text in ncdu over ssh

### ISSUE THREAD

**Issue by jeLee6gi** [jwilm/alacritty#3028]
> Which operating system does the issue occur on?
> * Archlinux (local)
> * Fedora (remote)
>
> If on linux, are you using X11 or Wayland?
> * Wayland

Title and selected line are highlighted on my local machine 

![2019-11-26-025917_grim](https://user-images.githubusercontent.com/9397810/69593758-7822ab00-0ffa-11ea-9e0b-419923ed7d1c.png)

but over ssh I cannot see which line is selected

![2019-11-26-030030_grim](https://user-images.githubusercontent.com/9397810/69593763-7e188c00-0ffa-11ea-94e3-44554b564f9d.png)

When I run ncdu in tmux, the highlighted text is rendered correctly

**Comment by jeLee6gi** [comment]
Oh also `6c` is printed to the command line after exiting, so I guess ncdu sends escape sequences alacritty does not understand

**Comment by chrisduerr** [comment]
Does this work when running ssh using `TERM=xterm-256color ssh`?

**Comment by jeLee6gi** [comment]
No, same problem.

My local TERM currently is `alacritty` and the remote one is `xterm-256color`, but I had them both set to `xterm-256color` before with the same effect.

**Comment by chrisduerr** [comment]
If you run it locally with `TERM=xterm-256color`, do you get the same result?

**Comment by jeLee6gi** [comment]
Yes, it works locally with both `alacritty` and `xterm-256color`

**Comment by chrisduerr** [comment]
I can not reproduce this myself, running `ncdu` on a remote Debian system from an Archlinux host.

Please make sure that both systems are up to date.

When starting `TERM=xterm-256color ssh remote`, please also make sure that after you're in the remote, `echo $TERM` actually gives you `xterm-256color`.

**Comment by jeLee6gi** [comment]
I was on 0.3.3 but the update just showed up in the official repositories so now I'm on 0.4.0 too

The highlighting problem is still there, the only difference I can see is that it doesn't print `6c` anymore but the more I look at it, the more it seems that it's just some funky configuration on the remote and it silently falls back to ansi. I still have to investigate but I don't think it's a bug with alacritty. Thank you for your help!
