### ISSUE TITLE
`startup_mode: Maximized` doesn't work on macOS 10.15.1 since 0.4.0

### ISSUE THREAD

**Issue by foray1010** [jwilm/alacritty#3029]
Which operating system does the issue occur on?
`macOS 10.15.1`

when set `startup_mode: Maximized`, error `Alacritty quit unexpectedly.` will be prompted

**Comment by ioagel** [comment]
I haa the same problem.
Try to change window.decorations from **'none'** to one of the other options. It is a temporary fix, at least in macOS 10.14.6

**Comment by foray1010** [comment]
@ioagel I can confirm setting `window.decorations` to default value fixed the problem, but only the height is maximized unlike previous version (both height & width are maximized).

**Comment by ioagel** [comment]
@foray1010 do you have more than one monitor?
I have 3 monitors, and in the one with the largest resolution (4K), **Maximized** is inconsistent. Sometimes it works properly, other times neither height nor width are maximized!

**Comment by foray1010** [comment]
@ioagel yes I have 2 monitors, same as you it sometimes works properly!

**Comment by chrisduerr** [comment]
See #2877 and #2905.
