### ISSUE TITLE
Issue and PR template

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#3031]
The current issue template should ask `alacritty --version`, since that's asked in almost every issue these days. There might also be formatting and other information that can help with improving this.

The PR template should at least mention the changelog, maybe even link to the contributing guidelines.

In general I think we shouldn't restrict the form too much, I'm personally really annoyed usually when I have to read through a huge block of text just for asking a simple questions. We should strive to help people find the information they want to provide, rather than forcing them to spend time on collecting irrelevant information.

**Comment by nixpulvis** [comment]
> In general I think we shouldn't restrict the form too much...

100% agree. Prompting the issue with a million *potentially* relevant questions is a pain. Issues then get submitted with some fraction of the questions answered, and it's potentially confusion.

The template we already have in `CONTRBUTING.md` seems pretty damn good for issues. So the question in my mind is how to translate that for PRs. Should honestly be pretty similar except without the machine specific information.
