### ISSUE TITLE
File URLs not working with leading `/`

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#3034]
Currently file paths do not work properly, since our URL parser allows only either zero or two slashes in the scheme. So a scheme like `file:/` or `file:///` is not allowed, however these are required for absolute paths (like `file:/root` or `file:///root`).

So we need to special case the logic for the `file` scheme and allow 0, 1, 2 and three slashes as scheme separators. We might potentially just want to throw out this check completely for paths.

**Comment by nixpulvis** [comment]
I think I'd be in favor of just removing the path check altogether. I'd think if we find one of our schemes (e.g. `https`, `file`, `mailto`, etc) in the form `<scheme>:` I'd expect to be reading the path next. Some schemes seem to have restrictions on what that path can be, or must be. For example `https:` must be followed by `//`, however IDK if we want to go to this level of validation.

**Comment by chrisduerr** [comment]
> For example https: must be followed by //

I'm not sure that's true?

But since `/` are legal characters inside of URLs, I don't think I'm entirely against using only `:` for separation.

Thinking about it, there shouldn't be any problems with over-reporting URLs because of this, because the most likely case would be `:` separator without any `/`, which is already legal. So the only thing that is not legal is `:/` or `:///` (or more slashes). I personally can't think of any case where people would be upset when excessive slashes are recognized as URLs.

**Comment by nixpulvis** [comment]
> I'm not sure that's true?

Yea it's not. :sweat: And technically the first slash isn't part of the path either.

But the details of this here aren't as important for our applications since we aren't trying to parse out each component of the URL to spec. We simply want to recognize a URL when we see one.
