### ISSUE TITLE
OSC52 and tmux set-clipboard does not work

### ISSUE THREAD

**Issue by yiyangc91** [jwilm/alacritty#3037]
Which operating system does the issue occur on? Arch Linux
If on linux, are you using X11 or Wayland? X11

tmux sends OSC 52 to Alacritty without the c parameter, i.e. the first parameter here %p1%s is blank.

```
Ms: (string) \033]52;%p1%s;%p2%s\007
```

This is the equivalent of running:

```
printf "\033]52;;$(printf "%s" "blabla" | base64)\a"
```

(if you hit Ctrl+Shift+V afterwards, your clipboard should not change)

However this works with the %p1%s parameter set to 'c'.

```
printf "\033]52;c;$(printf "%s" "blabla" | base64)\a"
```

(if you hit Ctrl+Shift+V afterwards, your clipboard should have 'blabla' in it)

Alacritty doesn't accept an empty parameter which is supposedly allowed in the spec. If we could add support for this, that would be awesome!

For tmux users, the workaround is to override the terminfo for alacritty:

```
set-option -ga terminal-override ',alacritty:Ms=\E]52;c;%p2%s\007'
```

**Comment by yiyangc91** [comment]
Anyway the code in tmux that spits out the escape sequence is doing something like

```
		bufferevent_write(wp->event, "\033]52;;", 6);
```

Xterm apparently defaults to 's 0' if this field is empty, St just sets both the clipboard and selection buffers. Haven't investigated other terminals.

**Comment by chrisduerr** [comment]
@yiyangc91 Did this work in a previous release? I feel like I might have broken that in a recent refactoring, I probably missed the `zero or more` in the spec, but you're completely right.

We can probably just default to `c`, or the primary clipboard. I think that makes the most sense.

**Comment by chrisduerr** [comment]
Fixed in https://github.com/jwilm/alacritty/pull/3038.

**Comment by yiyangc91** [comment]
@chrisduerr I didn't actually test this with a previous release - I just started using alacritty a day ago haha.

Thanks for the super fast response though! That's so awesome.

**Comment by benknoble** [comment]
PS: It looks like the terminfo entry that comes with the Homebrew installation of Alacritty does not include an `Ms` entry; is this intentional?

**Comment by benknoble** [comment]
My apologies: I was still using a previous version. Will update (which should fix it).
