### ISSUE TITLE
Explanation request

### ISSUE THREAD

**Issue by SRGOM** [jwilm/alacritty#3040]
```
UTF-8 mouse mode escape sequence (CSI ? 1005 h / CSI ? 1005 l)
Escape for reading clipboard (OSC 52 ; <s / p / c> ; ? BEL)
Set selection clipboard (OSC 52 ; <s / p> ; <BASE64> BEL)
```

What do the above 3 lines mean?

**Comment by chrisduerr** [comment]
Great question!

This is essentially how applications inside terminal emulators function and communicate with the terminal to instruct it to do certain things.

For example to get the red text `TEST` on screen, you'd do `printf "\e[31mTEST"`. So the `\e[31m` is used here to tell the terminal to color it red.

There are multiple different types of escape sequences, which are separated by specific byte(s) at the start of it. These are:
 - `ESC` -> `\e`
 - `CSI` -> `\e[`
 - `OSC` -> `\e]` 
 - `DCS` -> `\eP`

So in the changelog the `CSI` is just a short form for one of these control sequence introductions.

The rest of the syntax are usually the exact bytes of the escape sequence, or placeholders for positions where values can be specified. The whitespace in between is just a distinction for making things easier to read and separate token, those are not printed.

So if you want to set the clipboard from the terminal, you can for example use the following:
```bash
printf "\e]52;s;$(printf 'test' | base64);\a"
# \e] -> OSC
# ; -> separator
# s -> selection clipboard (you can paste this with middle mouse on linux)
# ; -> separator
# $(printf 'test' | base64) -> encode the string 'test' in base64
# \a -> mark end of escape sequence
```

The same thing applies for the other three escapes, example uses of those would be `printf "\e[1005h"`, `printf "\e[1005l"` and `printf "\e]52;s;?\a"`.

Now that should hopefully suffice as a basic introduction on how escape sequences work, if you have any more questions please let me know.

If you want to know what other fun escape sequences there are, there's a great resource for all of them [here](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html). This lists pretty much every ESC, OSC, CSI and DCS escape there is, though not all of them are supported by all terminal emulators.

**Comment by dnkl** [comment]
> This is essentially how applications inside terminal emulators function and communicate with the terminal to instruct it to do certain things.
> text text text

This. This is why I love this project. Keep up the good work @chrisduerr

**Comment by SRGOM** [comment]
Thank you for the detailed explanation.
