### ISSUE TITLE
-e flag ignores .bashrc

### ISSUE THREAD

**Issue by Zarhult** [jwilm/alacritty#3044]
Which operating system does the issue occur on?
Arch Linux
If on linux, are you using X11 or Wayland?
X11

I'm setting my terminal colors via pywal by running a `(cat ~/.cache/wal/sequences &)` in ~/.bashrc. All works well except I've discovered that when I try to launch something in alacritty with the -e flag (in my case `alacritty -e ncmpcpp`), the colors reset to the default. It seems that the -e flag does not respect .bashrc, because if I add e.g. `sleep 5` to .bashrc, I get the expected 5 second wait when I launch alacritty normally, but no such delay when I run it with the -e flag.

Just in case my config was somehow causing this, I double checked and the problem still happens without a config file.

**Comment by NickeZ** [comment]
Isn't that the whole point of `-e`? Does this work as intended? `alacritty -e bash -c ncmpcpp`?

**Comment by NickeZ** [comment]
Actually you probably need `alacritty -e bash -c '. ~/.bashrc; ncmpcpp'` because rc isn't loaded in non-interactive instances of bash.

**Comment by Zarhult** [comment]
Ah, I wasn't quite sure whether or not this was expected functionality. Thanks for the help with the command, `alacritty -e bash -c '. ~/.bashrc; ncmpcpp'` wasn't quite enough but I got it to work with `alacritty -e bash -i -c ncmpcpp`. I'll close the issue.
