### ISSUE TITLE
Shift-Delete in vim's command mode isn't working as expected

### ISSUE THREAD

**Issue by nixpulvis** [jwilm/alacritty#3046]
When I enter command mode `:` in vim, and type something, then start deleting with shift pressed, it simply moves the cursor instead of deleting the characters. I've tested this with both `alacritty` and `xterm-256color` as my `$TERM`.

I'm curious why it works in insert mode, or generally everywhere else, just not in command mode. Other terminals don't seem to have this behavior.

**Comment by chrisduerr** [comment]
I can't reproduce this in neovim, so I'd assume it's vim specific.

Do you get any different output when pressing shift+del in Alacritty vs a different terminal, when pressing ctrl+v to print the raw key escape?

**Comment by kchibisov** [comment]
FWIW I can repro in neovim.
