### ISSUE TITLE
Warning while compiling on rustc 1.16

### ISSUE THREAD

**Issue by okuuva** [jwilm/alacritty#305]
Compiler gives the following warning on macOS Sierra 10.12.2 (16C67):

```
warning: this feature has been stable since 1.15.0. Attribute no longer needed, #[warn(stable_features)] on by default
  --> src/lib.rs:25:12
   |
25 | #![feature(proc_macro)]
   |            ^^^^^^^^^^
```

The same warning doesn't appear on Debian Jessie stable.
I'm on 67aba7f4e4758c5fcb7eda50f083b138017fbfdb.

**Comment by lukaslueg** [comment]
What's your `rustc --version`? :-)

**Comment by okuuva** [comment]
After running `rustup update`:

```
$ rustc --version
rustc 1.16.0-nightly (1a2ed98d3 2017-01-13)
```

The warning persist.

**Comment by okuuva** [comment]
I confirmed this warning comes up with Debian Jessie Stable too when using rustc version 1.16.
