### ISSUE TITLE
Redraw stops until mouse is brought over the terminal

### ISSUE THREAD

**Issue by theOperand** [jwilm/alacritty#3052]
Which operating system does the issue occur on? Arch Linux

If on linux, are you using X11 or Wayland? X11

Occasionally, the terminal will stop redrawing until I hover my mouse over it. I've only noticed this while doing things that produce output over a large amount of time (e.g. system updates). I haven't been able to consistently reproduce it, though.

It's pretty annoying to think `apt` or `pacman` has hung only to discover it finished five minutes ago when I move my mouse over the window. A friend of mine has encountered it while tailing logs.

I'm pretty sure this isn't #824, as it's pretty much the opposite issue: it's resolved by moving the mouse over the terminal rather than a keypress. I did a little bit of searching but wasn't able to find a similar bug, sorry if I missed it.

**Comment by kchibisov** [comment]
Are you on `v0.3.3`, in case you're on it, please update to `v0.4.0`, this bug should be solved on it.

**Comment by liamdiprose** [comment]
Updated alacrity and tailed my logs for hours without this bug occurring.

Looks like @kchibisov is right :tada:

**Comment by theOperand** [comment]
Aah, you're right, can't seem to reproduce it anymore so it must be gone. My bad and thanks a lot!

**Comment by chrisduerr** [comment]
The original issue is #2217.
