### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by wieczorek1990** [jwilm/alacritty#3056]
Which operating system does the issue occur on?
MacOS Catalina
If on linux, are you using X11 or Wayland?
Not on linux.

Did you pay for security? If not I'm stopping using this greatest terminal ever.

**Comment by chrisduerr** [comment]
If you don't feel comfortable running software written by people in their free time for no money at all, it's perfectly fine to use a different terminal emulator instead. Though I do not see how 'paying for security' would help this project.

**Comment by wieczorek1990** [comment]
@chrisduerr
Maybe we should use Ko-fi money for real software security engineers?

**Comment by wieczorek1990** [comment]
Where is the webfoot scaling source code?

**Comment by wieczorek1990** [comment]
Where is the clear command source code?

**Comment by wieczorek1990** [comment]
>> Though I do not see how 'paying for security' would help this project.

What does it mean?

**Comment by Ckath** [comment]
the chance of another intel or apple security issue coming up is far higher than anything huge ever coming up in alacritty. I think the terminal emulator is the least of your worries.

**Comment by wieczorek1990** [comment]
@Ckath
Thank you.
I have some strange BIOS in my ThinkPad T410, Ethernet connected, Apple MacOS Catalina. Can you help evermore?

**Comment by Ckath** [comment]
> Ethernet connected
pretty much no hope of a secure system

**Comment by wieczorek1990** [comment]
@Ckath
I don't understand.

**Comment by nixpulvis** [comment]
@wieczorek1990 I can't help but wonder what you want. I'm going against my better judgment even spending the time to respond, but...

If your saying we should pay for a security audit, I'd say: we'll gladly accept patches that fix problems from anyone you hire for us.

If you're saying that we should pay for some kind of certification, I'd say: we're implementing well defined specifications, and that if there's any problems with them than you've got the same issues in other terminal emulators.

If you're just generally worried about security, I'm curious why you assume that if we "pay for security" we'll somehow be more secure. When I hear someone say things like that, first thought that comes to my head is the mafia offering "insurance" or "protection". Real security doesn't come so simply.

I too worry about security quite a lot, but I don't see what you'd like us to do here.

> greatest terminal ever.

Thanks :heart:

**Comment by wieczorek1990** [comment]
Thank you!
Security bugs here.

> Greatest terminal ever

**Comment by wieczorek1990** [comment]
I CHANGE.
Was Alacritty tested on BSD?

**Comment by chrisduerr** [comment]
I don't see this going anywhere.
