### ISSUE TITLE
Ubuntu install not working on clean 19.10 

### ISSUE THREAD

**Issue by HalfVoxel** [jwilm/alacritty#3065]
Running

```
sudo add-apt-repository ppa:mmstick76/alacritty
sudo apt update
sudo apt install alacritty
```

Fails with the message

```
E: The repository 'http://ppa.launchpad.net/mmstick76/alacritty/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

This should probably be fixed.

### System

OS: Ubuntu 19.10
X11

### Workaround

One can trick Ubuntu to read from an earlier distribution.
What worked for me was to edit the apt repository as described here https://askubuntu.com/questions/293203/how-can-i-add-a-ppa-from-a-previous-release to use the distribution "bionic". Doing this and then running `sudo apt update` and `sudo apt install alacritty` worked for me.

**Comment by chrisduerr** [comment]
The maintainer of this ppa is @mmstick. Maybe he can shed some light on it.

Officially, this PPA is only supported on popos, but as far as I know that is already on 19.10, so there should be a package available.

It's possible that the PPA just needs to be updated and mmstick has been too busy to get around to it.

**Comment by mmstick** [comment]
I may have forgotten to push to that repo

**Comment by mmstick** [comment]
Fret not, for I have pushed the 0.4.0 packages to the Alacritty PPA. This can be closed now.

**Comment by chrisduerr** [comment]
Thanks for your quick reply and action, very refreshing.

**Comment by noelleleigh** [comment]
@mmstick I'm getting this same issue on Debian 10 via [Crostini](https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md).

```
noelle_leigh@penguin:~$ sudo add-apt-repository ppa:mmstick76/alacritty
 Repository for Ubuntu that provides standalone Alacritty packages built as part of the CI/CD
 infrastructure for Pop!_OS. Sources currently originate from https://github.com/pop-os/alacr
itty
 More info: https://launchpad.net/~mmstick76/+archive/ubuntu/alacritty
Press [ENTER] to continue or ctrl-c to cancel adding it
gpg: keybox '/tmp/tmpjsta999j/pubring.gpg' created
gpg: /tmp/tmpjsta999j/trustdb.gpg: trustdb created
gpg: key 8AC9B4BBBAB4900B: public key "Launchpad PPA for Michael Aaron Murphy" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
```

```
noelle_leigh@penguin:~$ sudo apt update
...                           
Err:12 http://ppa.launchpad.net/mmstick76/alacritty/ubuntu focal Release 
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mmstick76/alacritty/ubuntu focal Release' does no
t have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by defau
lt.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

After trying the workaround and editing `/etc/apt/sources.list.d/mmstick76-ubuntu-alacritty-focal.list`

```
noelle_leigh@penguin:~$ sudo apt update
...
Err:7 http://ppa.launchpad.net/mmstick76/alacritty/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_P
UBKEY 8AC9B4BBBAB4900B
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/mmstick76/alacritty/ubuntu bionic InRelease: The follo
wing signatures couldn't be verified because the public key is not available: NO_PUBKEY 8AC9B
4BBBAB4900B
E: The repository 'http://ppa.launchpad.net/mmstick76/alacritty/ubuntu bionic InRelease' is n
ot signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by defau
lt.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Visiting <https://ppa.launchpad.net/mmstick76/alacritty/ubuntu/> throws a certificate error: 
> **NET::ERR_CERT_COMMON_NAME_INVALID**
> This server could not prove that it is **ppa.launchpad.net**; its security certificate is from **private-ppa.launchpad.net**. This may be caused by a misconfiguration or an attacker intercepting your connection.

Is there some Launchpad configuration that needs to happen?

**Comment by mmstick** [comment]
@noelleleigh You need to add my GPG key to apt's keyring:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8AC9B4BBBAB4900B
```

As for Ubuntu Focal support, we aren't yet building packages for focal.

**Comment by noelleleigh** [comment]
> @noelleleigh You need to add my GPG key to apt's keyring:
> 
> ```
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8AC9B4BBBAB4900B
> ```
> 
> As for Ubuntu Focal support, we aren't yet building packages for focal.

The `add-apt-repository` command already added your key as part of the installation process. Adding the key separately resulted in the same behavior.

Also, `focal` is the release that is specified by default after adding the PPA:

```bash
noelle_leigh@penguin:~$ cat /etc/apt/sources.list.d/mmstick76-ubuntu-alacritty-focal.list 
deb http://ppa.launchpad.net/mmstick76/alacritty/ubuntu focal main
# deb-src http://ppa.launchpad.net/mmstick76/alacritty/ubuntu focal main
```

Would you expect it to choose something different?
