### ISSUE TITLE
Ubuntu snap package crashes on start

### ISSUE THREAD

**Issue by HalfVoxel** [jwilm/alacritty#3066]
Running

```
sudo snap install alacritty
alacritty
```

Fails with the message

```
thread 'main' panicked at 'Failed to initialize any backend!
    Wayland status: NoCompositorListening
    X11 status: LibraryOpenError(
    OpenError {
        kind: Library,
        detail: "opening library failed (/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26\' not found (required by /lib/x86_64-linux-gnu/libX11.so.6)); opening library failed (libX11.so: cannot open shared object file: No such file or directory)"
    }
)
', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/linux/mod.rs:428:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This should probably be fixed.

### System

OS: Ubuntu 19.10
X11

**Comment by chrisduerr** [comment]
We have no control over the snap package as it is not maintained by us. It seems like it is seriously outdated too.

Please choose an alternative installation method, that will most likely fix the problem.

**Comment by HalfVoxel** [comment]
Ah. I understand.
Is there any way to either get it updated or at least take the snap package down? Having an outdated snap package probably hurts more for new users than not having it at all.

**Comment by chrisduerr** [comment]
> Is there any way to either get it updated or at least take the snap package down?

You'd have to contact the snap maintainer. Alacritty does not have any control over it.

**Comment by rkochar** [comment]
Glad I found this very quickly, might have spent a lot of time debugging it.
