### ISSUE TITLE
Fedora COPR not updated with 0.4.0

### ISSUE THREAD

**Issue by Will-W** [jwilm/alacritty#3067]
For convenience I use alacritty via the Fedora COPR repository kindly provided by @pschyska , and described in the README. The repository hasn't been updated to provide the latest release - 0.4.0, which provides some much needed fixes for those of us on Wayland.

Are there plans to update that repo, or is an alternative Fedora packaging process needed?

I'm on Fedora 30 and Fedora 31 across several machines (which is why I prefer packages to a more 'manual' approach).

**Comment by pschyska** [comment]
Hey @Will-W, I will trigger a re-build shortly.

**Comment by pschyska** [comment]
Hey @chrisduerr, I've got a problem. The v0.4.0 tag doesn't build, and I think I'd need to update the spec to fix it. Which would mean it would (maybe) work for v0.4.1 as 0.4.0 is already closed. I didn't think this through when I sent my initial PR. I think the packaging living on the repos can only work when it's integrated in CI, constantly tested, and might be just a bad idea in general.
I think I'm gonna move to a separate repo just for the spec, so I don't need to burden this repo with the rpm packaging noise. Would you agree?

**Comment by chrisduerr** [comment]
Could you elaborate on why it doesn't build?

**Comment by pschyska** [comment]
It does build, I interpreted something incorrectly, sorry.
There are some issues in the specfile though that @zenofile made me aware of, so I planned to update the spec. I could open a new PR here when I'm done, or just make a new repo. If you prefer the latter, I'd make a PR just removing the RPM packaging bits.

**Comment by pschyska** [comment]
@Will-W The 0.4.0 package is now available, please test.

**Comment by JamesDingle** [comment]
Tested here from Fedora (fc29, don't ask) COPR.

Seems to be working okay other than a slight change in configuration needed. Removing the faux_multiplier line removed the warning message and everything still seems to work fine.

`[2019-12-05 14:45] [WARN] Config scrolling.faux_multiplier is deprecated; the alternate scroll escape can now be used to disable it and `scrolling.multiplier` controls the number of scrolled lines`

**Comment by pschyska** [comment]
Yes, scrolling.faux_multiplier is not in the defaults /usr/share/alacritty.yml anymore, but you probably had a .config/alacritty/alacritty.yml that still listed that (that file used to be auto-generated)

**Comment by chrisduerr** [comment]
> I could open a new PR here when I'm done, or just make a new repo. If you prefer the latter, I'd make a PR just removing the RPM packaging bits.

Whatever floats your boat, I'm fine with either.

**Comment by Will-W** [comment]
Have just tested with Fedora 30. Encountered the same config file issue. I'm also encountering an issue where it's positioning the window incorrectly at startup when configured for fullscreen. It's not a deal breaker, and I'll file a separate issue.

**Comment by Will-W** [comment]
Filed as #3070
