### ISSUE TITLE
Copy & paste shortcuts don't work on gnome

### ISSUE THREAD

**Issue by GenaBitu** [jwilm/alacritty#307]
The default shortcuts for copy & paste are AFAIK Win+c and Win+v (Linux guy here). This is:
a) confusing as the usual shortcuts are Ctrl-Shift-c and Ctrl-Shift-v
b) doesn't work on gnome (I am on debian-testing) as the Win-v shortcut opens the notifications & calendar

Yes, I know I can remap these easily and that's not my point - there should be more sensible defaults IMHO.

**Comment by impowski** [comment]
You need to copy `alacritty.yml` to `~/.alacritty.yml`, I guess the default ones were meant to be for macOS so just remap them.

**Comment by jc00ke** [comment]
I was able to successfully remap `Command C/V` to `Control|Shift C/V` and it's quite nice.

I'm also working on addressing the difference between `Paste` and `PasteSelction`. PR to drop soon, once I learn Rust and clean up the duplication :wink:

**Comment by jwilm** [comment]
We have a separate config file for macOS/Linux defaults. Seems like the Linux ones need to be changed.

**Comment by robinduckett** [comment]
Although I have managed to remap Command C/V to Control|Shift C/V, it doesn't stop the escape character ^C from being sent. I'm hoping I've just configured my mappings incorrectly, because this is far from ideal.

```
key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste                  }
  - { key: C,        mods: Control|Shift, action: Copy                   }
  - { key: Q,        mods: Control|Shift, action: Quit                   }
  - { key: W,        mods: Control|Shift, action: Quit                   }
```

**Comment by jc00ke** [comment]
I'm on 715d4f8 and `Control+C` works to copy selected text and `Control+V` works to paste it.

I have the same mappings, but... as I test in `tmux`... yeah, it's not working correctly. Might you have a `tmux` binding that's getting in the way?
