### ISSUE TITLE
Incorrect position for fullscreen startup

### ISSUE THREAD

**Issue by Will-W** [jwilm/alacritty#3070]
My configuration has `decorations: full` and `startup_mode: Maximized`.

Opening alacritty (via any normal Gnome method) results in incorrect positioning. The window is the correct size, but positioned too high by the height of the window chrome. This means that the chrome is fully hidden (behind the gnome top bar), and there is a gap at the bottom exposing the window behind:
![bad](https://user-images.githubusercontent.com/997500/70255225-535ad000-177e-11ea-8c50-78ac3d059f86.png)

The same thing happens if it opens on the other monitor, except that the chrome is off the top of the screen.

If I reposition the window (e.g. swap screen and swap back using shortcut keys) it then positions correctly:
![good](https://user-images.githubusercontent.com/997500/70255255-5fdf2880-177e-11ea-9d8a-af33ecd0eb88.png)

### System

OS: Fedora 30
Version: 0.4.0 from COPR repsitory
Linux/BSD: Gnome Wayland

**Comment by chrisduerr** [comment]
Is it actually positioning the window too high, or is it just not rendering any window decorations?

**Comment by Will-W** [comment]
I think it is a positioning issue - if I hit the super key to show the Gnome Activities Overview, the preview of alacritty includes the window decorations (and then when I hit it again, it returns to the incorrect position).

**Comment by chrisduerr** [comment]
I feel like this might be an issue with Gnome specifically, because of their SSD/CSD approach.

Could you test decorations `none`, to see if the window is still positioned incorrectly or if that "fixes" it (though without decorations showing at all then obviously).

**Comment by Will-W** [comment]
That appears to behave correctly - prompt is at the top, window fills the screen.

**Comment by Will-W** [comment]
BTW - happy to do some more detailed digging/fix attempts if you can suggest where to start looking.

**Comment by chrisduerr** [comment]
It would be very helpful if you could try the example of https://github.com/rust-windowing/glutin.

You can just run `cargo run --example window` in that repository and check if the issue exists there too.

**Comment by Will-W** [comment]
I had to tweak that example to get it to start up maximised (added `.with_maximized(true)` to the `WindowBuilder` line).

Running that, it does not show the same issue. It starts up maximised as expected, filling the screen, showing the decoration at the top and with not gap at the bottom.

[FYI - this is actually my other machine because I'm at home now, so Fedora 28. Alacritty 0.4.0 is showing the same bug as originally described on here though]

**Comment by chrisduerr** [comment]
That's very helpful actually, thanks for testing that.

Could you test with https://github.com/chrisduerr/glutin? It's a fork of mine which should run against a more up to date winit version.

**Comment by Will-W** [comment]
Ahhh. That is showing the incorrect behaviour. Something in winit causing a regression then?

**Comment by chrisduerr** [comment]
> Something in winit causing a regression then?

I'd assume so. I'll report it upstream immediately.

**Comment by chrisduerr** [comment]
I've reported it upstream in https://github.com/rust-windowing/winit/issues/1312. If you want to help out, checking the exact commit which broke this might help, but it might be good to wait on feedback from the winit people.

If you subscribe to the upstream issue, that should make the feedback loop a bit shorter, then you can answer to them directly.
