### ISSUE TITLE
[Question] Why use Alacritty on Windows?

### ISSUE THREAD

**Issue by VideoPlayerCode** [jwilm/alacritty#3075]
There are no tickets, or discussions anywhere on the internet, that discuss this important question.

It's an incredible, GPU-accelerated Terminal for Linux and Mac, where it definitely adds performance.

But on Windows, the amount of bug tickets and pull requests shows that it isn't very stable (ctrl-c terminating the whole shell, bad formatting after minimizing windows, etc).

What is the point compared to just launching `powershell` directly? Which is a very stable shell, and can be made beautiful with the Microsoft `ColorTool` utility, for example mine looks like this: https://github.com/dracula/powershell

Furthermore, even in the realm of GPU accelerating, Microsoft themselves are making a new Terminal application: **Windows Terminal**. See https://github.com/microsoft/terminal

Their GitHub summary is:

> Windows Terminal is a new, modern, feature-rich, productive terminal application for command-line users. It includes many of the features most frequently requested by the Windows command-line community including support for tabs, rich text, globalization, configurability, theming & styling, and more.
> 
> The Terminal will also need to meet our goals and measures to ensure it remains fast and efficient, and doesn't consume vast amounts of memory or power.

And here is [their Windows Store summary](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab), which says:

> The Windows Terminal is a new, modern, fast, efficient, powerful, and productive terminal application for users of command-line tools and shells like Command Prompt, PowerShell, and WSL (Windows Subsystem for Linux). Its main features include multiple tabs, Unicode and UTF-8 character support, a GPU accelerated text rendering engine, and custom themes, styles and configurations.

Here is their introductory video:

- https://www.youtube.com/watch?v=8gw0rXPMMPE

And here are some related reviews and developer talks:

- https://www.youtube.com/watch?v=KMudkRcwjCw
- https://www.youtube.com/watch?v=B6_vo36bvyM
- https://www.youtube.com/watch?v=sckbApgo4Fk

Given the situation, what are the benefits of using Alacritty on Windows? It seems like Windows 10 users would be better off using the new Windows Terminal?

This is no criticism of Alacritty. It's amazing on Linux and Mac.

**Comment by kchibisov** [comment]
>There are no tickets, or discussions anywhere on the internet, that discuss this important question.

I don't find a question on what people should use important, since it's up to them, and you shouldn't be driven by what other people do in a daily life. Anyway let me expose my vision on this question.

>But on Windows, the amount of bug tickets and pull requests shows that it isn't very stable (ctrl-c terminating the whole shell, bad formatting after minimizing windows, etc).

The windows support was initially a community driven, that being said the Windows wasn't a main goal iirc, however I don't see any problem with having it here and I find it very useful, will explain later. The main problem with windows is windows and how it differs from everything else, however alacritty performance was way better then what default windows provided me with last time I checked, and since the project is still in "beta level of readiness" bugs are expected (read README), also having bugs doesn't mean that they wouldn't be solved in a future. I personally want the same terminal experience on all platforms I could use and the projects that is fun to work on, and alacritty has both of these checkboxes are filled for me. Anyway users should use whatever they want and having more options is always better.

But there's a reason to use it in my opinion for rust folks in my opinion. Alacritty is a giant `winit`/`glutin` consumer and it helps with its evolution and quality a lot (just see the amount of bugs from alacritty folks in it).

P.s.
Alacritty were before new Windows terminal though.

**Comment by VideoPlayerCode** [comment]
Thanks for your answer @kchibisov!

- "Windows wasn't a main goal": True, yesterday I was reading through many discussions from when the windows support was added, since I was trying to figure out why it was useful on Windows. And it seemed like a "well, nice feature to have!" was the motivation for it.
- "The main cause of bugs is that Windows differs from Mac/Linux": Yep, can't argue with that.
- "Performance is way better than default Windows Console": Yeah, text rendering is faster in alacritty than the old Windows Console, for sure. Although I am not sure what workloads people are using where text rendering speed has an effect? I've seen tech demos that render swirly colors, but that's not a real workload. Something like editing text in vim or listing files in a directory doesn't seem to take advantage of GPU acceleration, since those types of workloads have a very tiny amount of data transfer. So they are instant on any terminal.
- "Having bugs won't mean they are not solved in the future": Very true. I expect that alacritty will evolve to be super stable on Windows.
- "I personally want the same terminal experience on all platforms I could use": Okay but I don't understand this point... Isn't Alacritty just doing the text rendering and you still have to run a shell program underneath Alacritty (such as bash-windows, or powershell). I could see a point about running bash on Windows through Alacritty, to get a bunch of Unix terminal commands like rm and cat etc. Kinda like the git-bash app that ships with Git for Windows. Is that what you are referring to? I come from a Linux and Mac world and actually have been opening git-bash quite a lot to be able to do familiar stuff with built-in Linux commands like find and grep. (Although with time I found Windows replacements for that, via ripgrep in powershell etc.)
- "Having more options is better": True!
- "Alacritty is a giant winit/glutin consumer and helps evolve those projects": Yeah I noticed that in all the tickets and pull requests going upstream. That's great! I am going to get into programming Rust and it's great to see that those libraries are evolving.
- "Alacritty for Windows came out before the new Windows Terminal": Ah, I expected that was the case. So it had a lot more purpose before the new GPU-accelerated terminal was announced.

**Comment by chrisduerr** [comment]
Besides all the points that @kchibisov has rightfully mentioned, I'd like to bring up that a huge number of the issues reported with Alacritty on Windows are not actually Alacritty issues. They're issues with Windows' terminal API and complaints about its stability should probably go straight to Microsoft.

The Windows shells are also pretty much useless as interactive shells when used like a Linux shell, so back when my work machine was still using Windows, there was no way around using one of the unix shells and that combined with Alacritty definitely makes the horrible state of Windows terminals at least a little bit better.

**Comment by VideoPlayerCode** [comment]
@chrisduerr Thanks for the reply. Good to hear that tons of the issues are caused by upstream libraries and Windows itself and its ConPTY API etc.

And yeah, the shell situation on Windows isn't good. `cmd` is laughable trash. `powershell` is decent and I have been forcing myself to like it. But Linux shells are so much better. I may install Alacritty and run git-bash inside of it. I'm also going to do the same with the new Windows Terminal (running git's `bash.exe` inside of it).

Thanks for all the helpful answers. I just wanted to check if I was missing some huge benefit of Alacritty on Windows. :-)

**Comment by kchibisov** [comment]
> I am not sure what workloads people are using where text rendering speed has an effect?

Compilation in verbose mode (I use it quite often and don't want to redirect things into a file), scrolling in editors like vim/emacs, `cat` on large file, etc.

>"I personally want the same terminal experience on all platforms I could use": Okay but I don't understand this point... Isn't Alacritty just doing the text rendering and you still have to run a shell program underneath Alacritty (such as bash-windows, or powershell).

It's not only about text rendering. It's about features like hotkeys, configuration (colors, etc), clickable urls, and so on. So my workflow is always the same for all platforms: downloads my config, install alacritty, change config to use a proper shell if the platform is odd. Yeah, the windows is a bit different with shells, but I was running wsl in alacritty, so things were similar to Linux, though me running Windows is an exception most of the time (like test things in alacritty, etc).

**Comment by VideoPlayerCode** [comment]
@kchibisov 

> Compilation in verbose mode (I use it quite often and don't want to redirect things into a file), scrolling in editors like vim/emacs, cat on large file, etc.

True. That happens sometimes. Good point!

> It's not only about text rendering. It's about features like hotkeys, configuration (colors, etc), clickable urls, and so on. So my workflow is always the same for all platforms: downloads my config, install alacritty, change config to use a proper shell if the platform is odd.

Ah yes, that is a very good point. Using the same config on all systems is excellent with Alacritty! :-)

Anyway, since I only have one machine and only use Windows, I decided to try the new Windows Terminal. It has GPU-acceleration and hotkey support, color scheme support etc.

- Using https://github.com/p-e-w/ternimal in "rainbow mode" for performance stress-testing. Compiled with rust-msvc.
- Screen refresh rate was faster than Alacritty. Although both are super fast. :-)

---

For Chocolatey users, getting PowerShell Core 6 + Git + Windows Terminal is this easy:

```
choco install microsoft-windows-terminal
choco install powershell-core
choco install git
```

And here's the "Settings"-menu config for Windows Terminal, which adds https://github.com/PowerShell/PowerShell (PowerShell Core 6), and Git Bash:

```json
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
    "profiles": [
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore",
            "hidden": false,
            // "startingDirectory": "%USERPROFILE%",
            "startingDirectory": ".", // Launch in current working directory.
            "closeOnExit": true,
            "colorScheme": "Dracula",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Lucida Console",
            "fontSize": 13,
            "historySize": 9001,
            // "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png", // Commented out to use real icon.
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "useAcrylic": false
        },
        {
            "guid": "{6921115e-14c7-4e84-badf-2bc31e537f9b}",
            "name": "Git Bash",
            "commandline": "\"%PROGRAMFILES%\\Git\\usr\\bin\\bash.exe\" -i -l",
            "hidden": false,
            // "startingDirectory": "%USERPROFILE%",
            "startingDirectory": ".", // Launch in current working directory.
            "closeOnExit": true,
            "colorScheme": "Dracula",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Lucida Console",
            "fontSize": 13,
            "historySize": 9001,
            // "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png", // Use "cmd" icon.
            "icon": "%PROGRAMFILES%\\Git\\mingw64\\share\\git\\git-for-windows.ico", // Use "Git Bash" icon.
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "useAcrylic": false
        },
        {
            // Make changes here to the powershell.exe profile
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell",
            "commandline": "powershell.exe",
            "hidden": true,
            // "startingDirectory": "%USERPROFILE%",
            "startingDirectory": ".", // Launch in current working directory.
            "closeOnExit": true,
            "colorScheme": "Dracula",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Lucida Console",
            "fontSize": 13,
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{61c54bbd-c2c6-5271-96e7-009a87ff44bf}.png",
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "useAcrylic": false
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false,
            // "startingDirectory": "%USERPROFILE%",
            "startingDirectory": ".", // Launch in current working directory.
            "closeOnExit": true,
            "colorScheme": "Dracula",
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "fontFace": "Lucida Console",
            "fontSize": 13,
            "historySize": 9001,
            "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
            "padding": "8, 8, 8, 8",
            "snapOnInput": true,
            "useAcrylic": false
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure",
            "hidden": true
        }
    ],
    // Add custom color schemes to this array
    "schemes": [
        {
            "name": "Dracula",
            "background": "#272935",
            "black": "#272935",
            "blue": "#BD93F9",
            "brightBlack": "#555555",
            "brightBlue": "#BD93F9",
            "brightCyan": "#8BE9FD",
            "brightGreen": "#50FA7B",
            "brightPurple": "#FF79C6",
            "brightRed": "#FF5555",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#F1FA8C",
            "cyan": "#6272A4",
            "foreground": "#F8F8F2",
            "green": "#50FA7B",
            "purple": "#6272A4",
            "red": "#FF5555",
            "white": "#F8F8F2",
            "yellow": "#FFB86C"
        }
    ],
    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}
```

Anyway, I completely understand the value of Alacritty and having the same config on every system too. So that's cool. Thanks for your answers!

If it's not annoying people too much, could I ask which bash shell you are using for Windows? I'm using git-bash which comes with prebuilt msys2 versions of most Linux tools (grep, curl, cat, etc). Seems like a safe and well-maintained choice.

**Comment by chrisduerr** [comment]
> Using https://github.com/p-e-w/ternimal in "rainbow mode" for performance stress-testing

That's probably far too slow to stress a terminal, there's not enough changes at any time.

> Screen refresh rate was faster than Alacritty. Although both are super fast. :-)

In the benchmarks we've performed, the windows terminal was slower than Alacritty. However we had to switch off of ntfs because that was painfully slow and there were still bottlenecks that didn't allow Alacritty to perform anywhere close to its Linux/macOS performance.

Generally it should be far, far, faster on Windows, however Windows makes it incredibly difficult to find a good way to verify that without running into silly limitations by Windows itself.

**Comment by VideoPlayerCode** [comment]
@chrisduerr Ahh, okay! Perhaps I should use a bash shell and `time cat <100mb file>` :-)

**Comment by chrisduerr** [comment]
> Perhaps I should use a bash shell and time cat <large file> :-)

Depends on your storage solution and filesystem, as mentioned before.

**Comment by VideoPlayerCode** [comment]
@chrisduerr Thanks for letting me know that the worm test wasn't a good benchmark. I've now used a 10mb file (small enough to minimize filesystem impact). The result was as follows, with Windows Terminal being 17.6% slower. They're both ultra fast though.

Alacritty is set to ConPTY and the Git-bash shell (same as in Windows Terminal).

![res](https://user-images.githubusercontent.com/38923130/70361730-d7967b80-1882-11ea-889f-0ffcabfe434e.jpg)

**Comment by chrisduerr** [comment]
> The result was as follows, with Windows Terminal being 17.6% slower. They're both ultra fast though.

That is not actually ultra fast by Alacritty's standards. A testfile with 569M takes me about 8.663 seconds on Linux.

We've looked into it in the past and there are a bunch of things you can do to improve it (iirc wsl was actually faster than Windows itself?), but generally you're fighting a tough fight against the operating system on Windows.

Potentially the WSL2 will solve this, since it just runs a Linux VM, getting rid of all the slow Windows stuff, but I'd have to give it a try myself to verify the performance of that.

**Comment by VideoPlayerCode** [comment]
> That is not actually ultra fast by Alacritty's standards. A testfile with 569M takes me about 8.663 seconds on Linux.

Yikes. How can the pipes be so inefficient on Windows?! :-O Shocking.

Also turns out I made a big mistake. ConPTY was set to false in Alacritty during the test. Here's the corrected result, for comparing their performance on Windows:

- If both Windows Terminal and Alacritty use `ConPTY` backend, the results are 27.442s for Windows Terminal and 39.307s (42.23% slower) for Alacritty.
- If Alacritty uses WinPTY, it is 23.335s (which is 17.6% faster than Windows Terminal).
- So clearly the WinPTY backend is pretty optimized.

![res](https://user-images.githubusercontent.com/38923130/70362548-a53a4d80-1885-11ea-96b2-862ea9bceb99.jpg)

**Comment by hyphenrf** [comment]
Something that I haven't seen mentioned here yet:  

It's probably the best option for Windows !(10). Windows Terminal is naturally better integrated with its system, but it only supports Win10. In the odd days I do have to fire up a windows machine, (mine is 8.1), Alacritty has *much* better startup times than Powershell's native GUI, and is more user-friendly than CMD (selecting text, copy-paste, etc..).  
It's way less bloated than cygwin's terminal and can run more shells than git-bash.  
These are all options I've tried so I'm vouching from my personal experience.  
The rest of Windows !(10)'s selection is Electron-based toy stuff that's only usable if your machine can absorb the loss in resources that come with the framework.  \

Not all Windows is Windows10 @VideoPlayerCode

**Comment by yabb85** [comment]
Because the Windows terminal is not available on windows 10 ltsc, and powershell have not tab?

**Comment by bernastoc** [comment]
@VideoPlayerCode I just spent a week mucking about with Windows Terminal and am now an Alacritty convert. WT's font rendering is absolutely abysmal, nigh unusable for me (for coding at least).

**Comment by spudlyo** [comment]
For me, I want to configure my terminal once, on Windows, Linux, and macOS. Alacritty is cross platform and has all  As a hardcore Tmux user, Alacritty works the way I want my terminal to work, in that by default it doesn't have tabs, scrollbars, multiple windows or any of that jank I consider unnecessary. It's fast, and has most of features I care about, like direct color, OSC-52, and is easily configurable in a single file.

**Comment by chichid** [comment]
I recommend using wezterminal everywhere not just windows, its performance is comparable to that of Alacritty and in addition to that has a lot of the necessary features you'd expect from a terminal emulator.

**Comment by nonetrix** [comment]
I use windows in a VM with GPU passthrough and I also use ltsc because it's the only version on windows that doesn't suck and it doesn't support windows terminal since it is too out of date with APIs and etc

**Comment by Elfatih632** [comment]
Could you please stop sending me this email

**Comment by nixpulvis** [comment]
@Elfatih632

![screenshot-2021-04-12T16:24:56Z](https://user-images.githubusercontent.com/715947/114428378-1da3d380-9b8a-11eb-98d1-756bd02775bc.png)

Does this not work for you? I ask honestly, because I have ended up subscribed to GitHub threads which got bugged out before, but it's been **very** rare.

**Comment by sisrfeng** [comment]
> you may prefer iTerm2 on OSX, kitty on Linux, and Windows Terminal on Windows) 
but it's definitely the best terminal that works on all three platforms.

Configuraion of Alacrity is more annoying than Windows termial for me.  
And Windows terminal has multi tabs.

**Comment by 3N4N** [comment]
For me, difficulty of configuration isn't a problem.  But the lack of tabs honestly confuses me when I read through this thread and read people saying they use Alacritty on Windows.  I use a tabless terminal emulator on Linux (Suckless Terminal) because I have tmux there.  Windows has no tmux.  How are you guys using terminal that you don't need tabs even without tmux?

**Comment by nzbart** [comment]
@3N4N I run WSL (Windows Subsystem for Linux), launch tmux within WSL, and then run `powershell.exe` in tmux Windows. Everything works as expected, and I have access to Linux or PowerShell tmux panes in the same window. I don't use tabs in the terminal emulator.

**Comment by rikaisu** [comment]
> How are you guys using terminal that you don't need tabs even without tmux?
Tiling window managers. You don't need tabs at all if you use one. For Windows, there's [workspacer](https://github.com/workspacer/workspacer) which I personally use.

**Comment by a-amr** [comment]
> @3N4N I run WSL (Windows Subsystem for Linux), launch tmux within WSL, and then run `powershell.exe` in tmux panes. Everything works as expected, and I have access to Linux or PowerShell tmux panes in the same window. I don't use tabs in the terminal emulator.



this is exactly what i'am doing, really neat setup, i even use server's tmux inside tmux with ssh so c-b c-b to access the ssh tmux and c-b to access the wsl main one.
 not the fastest way but easy to use if you login into a lot servers with the default conf .
