### ISSUE TITLE
Incorrect font rendering

### ISSUE THREAD

**Issue by Alexander-Miller** [jwilm/alacritty#309]
http://i.imgur.com/lUEFvTL.png

In the link above you see xfce terminal on the left vs alacritty on the right, both set to use Fantasque Sans Mono 12.

In the top row alacritty fails to render Font Awesome's ❯ character. This is font dependent, as the issue sppears when using Fantasque Sans and Terminus, but not monospace.

In the middle you see ncmpcpp's lines turned into q's. The used font does not seem to matter here, however the rendering is correct if you run ncmpcpp in tmux.

I'm running a release build of the master branch, compiled today, using rustc 1.16.0-nightly.

**Comment by jwilm** [comment]
Thanks for the report!

The first issue sounds like fallback fonts #45, and the second part is a lack of graphics drawing which is actively being worked on in #292.

We can leave this open so you get updates.

**Comment by Alexander-Miller** [comment]
I've subscribed to the threads you linked, no need to clutter up the issue tracker with known and worked-on problems.
