### ISSUE TITLE
Permission error on ~/Desktop with Alacritty but not Terminal.app

### ISSUE THREAD

**Issue by n8henrie** [jwilm/alacritty#3090]
This seems bizarre.

MacOS 10.15.1, alacritty 0.4.0 (b115b90)

I can't access my desktop from Alacritty (permission error), but I can access other directories, and I can access the desktop from Terminal. Permissions seem reasonable.

Any idea what in the world is going on?

EDIT: In the screenshot, Terminal.app is left and alacritty is right.

![screenshot 2019-12-11 at 10 27 36 PM](https://user-images.githubusercontent.com/1234956/70685149-b4464480-1c65-11ea-811f-07b0d4dccaeb.jpg)

EDIT2: I noticed the error trying to rsync something to my desktop, so it's not just `ls`. Worked in Terminal, in Alacritty I get:

```plaintext
rsync: getcwd(): No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at util.c(1139) [Receiver=3.1.3]
```

**Comment by chrisduerr** [comment]
When you start Alacritty from Terminal.app, is it fixed?

**Comment by n8henrie** [comment]
Hmmm. The error is gone now. I haven't rebooted, changed any permissions, or even closed Alacritty. Very odd. I'll reopen if it comes back.

**Comment by chrisduerr** [comment]
Generally Alacritty has nothing to do with the applications that run inside it. It just provides a 'frontend' for these applications to render to.

So if applications behave differently, chances are something in `env` is different, which is why I suggested starting from Terminal.app since Alacritty will inherit Terminal.app's environment then.

**Comment by n8henrie** [comment]
That makes sense, though the screenshot above is from a fresh window on each (terminal and Alacritty), which I opened specifically for the screenshot after noting the issue in a different window. If env were the issue, I would have expected both of these fresh windows to have a different environment than the other alacritty window where I first noted the error (and multiple new windows I had opened to try to figure out what in the world was going on with rsync earlier in the day), and I would think that both of these fresh windows would source my dotfiles similarly and have the same resulting env.

After opening a new window and `env > foo.env`:

```console
$ diff alacritty.env terminal.env 
3d2
< COLORTERM=truecolor
6a6
> TERM_PROGRAM_VERSION=433
8a9
> TERM_SESSION_ID=8967E87E-16A8-498D-ABCC-8994DA201004
10c11
< GPG_TTY=/dev/ttys030
---
> GPG_TTY=/dev/ttys031
36c37
< SHLVL=1
---
> SHLVL=2
45d45
< ALACRITTY_LOG=/var/folders/xv/gqk_1btj70v8gfz8xb0ydw940000gn/T/Alacritty-30309.log
47c47
< __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
---
> TERM_PROGRAM=Apple_Terminal
```

If it happens again, I'll make sure to launch alacritty from Terminal and report back. Thanks again.

**Comment by n8henrie** [comment]
Happened again. New alacritty windows have the problem, but running the alacritty binary directly from Terminal works:

![screenshot 2019-12-12 at 9 52 25 AM](https://user-images.githubusercontent.com/1234956/70732178-30bc4000-1cc5-11ea-9473-0e05b3356b29.jpg)
```console
$ diff broken.env working.env
7c7
< TMUX=/private/tmp/tmux-501/default,21770,0
---
> TERM_PROGRAM_VERSION=433
10c10
< TMUX_PLUGIN_MANAGER_PATH=/Users/n8henrie/.tmux/plugins/
---
> TERM_SESSION_ID=647BA634-8AE4-4ECC-8886-2E351DDEEE6A
12c12
< GPG_TTY=/dev/ttys031
---
> GPG_TTY=/dev/ttys033
18d17
< LaunchInstanceID=71187E4F-FB71-462A-BA15-5AD816B3E378
27c26
< SECURITYSESSIONID=186a6
---
> SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS=/Users/n8henrie/Library/WebKit/Databases
34d32
< TMUX_PANE=%2
39c37
< SHLVL=3
---
> SHLVL=2
48c46
< ALACRITTY_LOG=/var/folders/xv/gqk_1btj70v8gfz8xb0ydw940000gn/T/Alacritty-47740.log
---
> ALACRITTY_LOG=/var/folders/xv/gqk_1btj70v8gfz8xb0ydw940000gn/T/Alacritty-48178.log
50a49
> TERM_PROGRAM=Apple_Terminal
```

Curiously, those log files don't seem to exist:

```console
$ env | grep ALACRITTY_LOG
ALACRITTY_LOG=/var/folders/xv/gqk_1btj70v8gfz8xb0ydw940000gn/T/Alacritty-48178.log
$ ls -l "$(env | grep ALACRITTY_LOG | sed 's/ALACRITTY_LOG=//')"
ls: cannot access '/var/folders/xv/gqk_1btj70v8gfz8xb0ydw940000gn/T/Alacritty-48178.log': No such file or directory
```

**Comment by n8henrie** [comment]
Trying to clear out all env:

```console
$ export FOO=bar
$ env | grep FOO
FOO=bar
$ bash
$ env | grep FOO
FOO=bar
$ exec bash
$ env | grep FOO
FOO=bar
$ exec env --ignore-environment /bin/bash
bash: shopt: globstar: invalid shell option name
bash: shopt: direxpand: invalid shell option name
mkdir: cannot create directory '/.rbenv': Read-only file system
mkdir: cannot create directory '/.rbenv': Read-only file system

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
$
$ env | grep FOO
$ ls Desktop
ls: cannot open directory 'Desktop': Operation not permitted
```

**Comment by n8henrie** [comment]
Hmm. I just gave Alacritty Full Disk Access in System Preferences, and the error went away (in the same window, no change in env).

Seems odd that this suddenly popped up yesterday. No system updates or reboots to my knowledge.

**Comment by here** [comment]
MacOS 10.15.5 Catalina
System Preferences -> Security & Privacy -> Privacy -> Full Disk Access -> Check Alacritty in the list of allowed apps.

**Comment by nag-anoop** [comment]
@here Thanks it worked for me!

**Comment by JellyApple102** [comment]
> MacOS 10.15.5 Catalina System Preferences -> Security & Privacy -> Privacy -> Full Disk Access -> Check Alacritty in the list of allowed apps.

@here do you have any more information? I have tried everything under the sun and not even this works. Precompiled manually compiled, adding the binary to full disk access, resetting privacy permissions across the board, countless reboots, etc. File permissions work like normal for every other app I have, just not Alacritty for some reason. I can run the binary from Terminal.app and it will work, but ideally I should just be able to run Alacritty.app and have it work properly.

**Comment by chrisduerr** [comment]
@JellyApple102 Sounds like an issue where you might be able to fix things by looking into signing issues (https://github.com/alacritty/alacritty/issues/5776#issuecomment-1015267870).
