### ISSUE TITLE
Alacritty becomes very slow after changing scaling with xrandr

### ISSUE THREAD

**Issue by Yumasi** [jwilm/alacritty#3095]
I have a setup with a laptop and an external screen. My laptop screen is high DPI and DPI is set globally on my system so I change it for my external screen with `xrandr --output HDMI --scale 2x2`. After this command Alacritty becomes really slow, even in new instances.

This slowness occurs only when Alacritty is started with i3 in tiling mode with Firefox also open on the same i3 desktop. This does not occur with other applications like Discord or Slack. The problem also goes away if I switch i3 to tab mode or stacked mode. Also, this does not occur if I don't fiddle with my display scaling with xrandr.

### System

OS: Linux Nixos 19.09 unstable
Version: alacritty 0.4.0
X11, i3

**Comment by nixpulvis** [comment]
@Yumasi I'm curious why you closed this. Did you determine it to be a bug elsewhere? I can replicate this myself in the same environment (X11,i3).

**Comment by Yumasi** [comment]
@nixpulvis Yes, I could reproduce the issue with other applications, not only Alacritty. I eventually fixed it accidentaly by switching my graphics driver from `modesetting` to `intel`.

**Comment by TuM0xA-S** [comment]
same problem, disabling DRI3 helped
