### ISSUE TITLE
ranger's color isn't right when TERM=alacritty-direct

### ISSUE THREAD

**Issue by AmaiKinono** [jwilm/alacritty#3097]
When `TERM=alacritty-direct`:

![2019-12-14-024616_1000x750_scrot](https://user-images.githubusercontent.com/28714352/70824138-848d6d00-1e1c-11ea-87c4-8ce893bbebd6.png)

When `TERM=alacritty`, the colors are right:

![2019-12-14-024659_1000x750_scrot](https://user-images.githubusercontent.com/28714352/70824178-9a029700-1e1c-11ea-9642-03b6e961e1de.png)

OS: Manjaro Linux 18.1.4 with kernel 4.19.88
Version: alacritty 0.4.0
Desktop: X11, i3wm, compton-tryone

**Comment by dnkl** [comment]
Looks like ranger doesn't support 24-bit color: https://github.com/ranger/ranger/issues/690

Many applications, typically ncurses based ones, don't. What I do is use a 256-color terminfo by default, and a 24-bit one only when I know the application supports it.

**Comment by AmaiKinono** [comment]
I see, Thanks!
