### ISSUE TITLE
Real text underline support

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#31]
As part of shipping 0.1, underline support was hacked in by rendering an underscore in the same cell as the character.

**Comment by tcrayford** [comment]
@jwilm if I'm reading this right, this is going to require adding things to https://github.com/servo/core-foundation-rs. Is that right?

**Comment by jwilm** [comment]
Maybe? I haven't looked into it at all. With FreeType, they tell you where to draw the underline and how thick to make it.

**Comment by tcrayford** [comment]
@jwilm looking a bit into core text, http://foobarpig.com/iphone/coretext-set-text-font-and-alignment-to-cfattributedstring.html seems like a roughly correct C version of doing underlines. This would require some stuff added to core-foundation-rs, like `CFMutableAttributedStringRef` and a few other types.

**Comment by voxadam** [comment]
Is this the reason that underlined text appears such that each character is underlined individually instead of rendering the underline on word as whole?

Alacritty:
![image](https://cloud.githubusercontent.com/assets/108151/24020380/2ff17644-0a59-11e7-99fc-71adcb24ef84.png)
Gnome Terminal:
![image](https://cloud.githubusercontent.com/assets/108151/24020429/5cc7ddca-0a59-11e7-8443-c1e1c72361f9.png)

**Comment by jwilm** [comment]
@voxadam yep! Most fonts provide an underscore that will be the right width so it's not such an obvious looking hack.

**Comment by DarkDefender** [comment]
Any progress on this? With the font I'm using, it becomes quite annoying because the underscore hack makes the line go through the text:
(urxvt on the left and alacritty on the right)
![underline](https://user-images.githubusercontent.com/312503/27094945-36a5d792-506c-11e7-8601-0a9b08871dda.png)

**Comment by maximbaz** [comment]
Also, just to point this out, now there are two cases where drawing of a real line is requested, here for underlined text and in #608 for cursor shapes. It's likely that the same approach could resolve both issues.

**Comment by jwilm** [comment]
@maximbaz I was actually thinking about cheating in the case of those cursor glyphs. The glyphs are supposed to be a fractional cell fill. It would be pretty easy to stick our own appropriately dimensioned buffers into the glyph cache for that case. This keeps cursors relatively simple, and means that line drawing only needs to support a single use case.

For the underline text decoration, I think we should actually implement some sort of line drawing. The rasterizer can just collect underline decorations into spans and make an extra draw call after the grid has been drawn.

**Comment by pvaibhav** [comment]
Hi guys, for anyone looking for a quickfix, use the Iosevka font and change the underline character in src/renderer/mod.rs to `⎽` (unicode Horizontal Scan Line 9, iirc). Other fonts might have this glyph too.

My fork has this change. Or just patch this: https://github.com/pvaibhav/alacritty/commit/4695a9d7f400224d557f3cf542325d7d627d9dce

**Comment by jwilm** [comment]
@maximbaz The renderer is very efficient at drawing quads and mapping textures onto them. Additionally, by making the cursor just another glyph, all the existing drawing machinery can be reused for the cursor.

For line drawing, there's just more work to be done. Luckily, we only care about horizontal and vertical lines, and we can get away with simply drawing long, narrow quads. To implement this, we would need the renderer to collect spans when detecting underline start/ends, draw glyphs, (potentially) swap shaders, and finally flush the line spans.

Cursors could also be drawn in that fashion (and maybe should be long term), but the outcome would be the same as described above. The only potential problem with the cursor solution in a previous comment is that we're not reading those glyphs from the font, and it *might* cause issues in uncommon cases. Seems unlikely to be a problem in practice, though.

"Real" line drawing (ie. arbitrary paths) gets really complicated, and it's completely out of scope for the project.

**Comment by DarkDefender** [comment]
@pvaibhav Thanks that fixed it for me!

@jwilm For me atleast, the underline stuff would be solved by changing the char to `⎽` instead.

I think that your current solution is the same that is used in urxvt. Underline and the different cursor shapes looks the same to me now atleast. So I don't think that it is inherently bad.

Perhaps add the shapes/chars to the config file if people want to change the default to something else.

**Comment by inducer** [comment]
"⎯" (https://codepoints.net/U+23AF) is another option. (Doesn't look that low on the web, but works nicely with Iosevka.)

**Comment by FichteFoll** [comment]
I also patched my alacritty to use `⎽` instead of `_`, as that is implemented in the font I use and just looks *significantly* better.

Have a comparison below:

![img](https://x0.at/MZc.png)

**Comment by tiziano88** [comment]
If there is genuinely no consensus on what glyph to use, would it be worth introducing a setting to allow overriding it? Or, could we try the various glyphs suggested in this thread in order until a non-empty one is found?

**Comment by chrisduerr** [comment]
If someone wants to change this behavior, it should probably just be done right.

I could've added a workaround similar to my PR  #937, but that would have just replaced one hack with another. At this point it's just a matter of taking the time to do it right and adding actual line drawing, instead of searching for glyphs that might work better.

**Comment by chrisduerr** [comment]
One thing I've noticed is that when running `echo -e "\e[4m testing" && sleep 10` at the bottom of the terminal, underline doesn't seem to work properly:
![](https://u.teknik.io/cJru8.png)

**Comment by Rukenshia** [comment]
Any update on this @chrisduerr ? I just came back to check out alacritty and with the font i'm using (Iosevka) the underlines look pretty bad and more or less clip into the text.

**Comment by chrisduerr** [comment]
The PR is still open. It will take a bit until it can be merged though since other PRs take priority.
