### ISSUE TITLE
Very slow rendering in tmux (split-mode or multi-attached mode) (Linux)

### ISSUE THREAD

**Issue by d3rrial** [jwilm/alacritty#310]
When in tmux with a split pane, running 
```zsh
ls -al
```
in a folder with a few hundred files, alacritty needs 1-2 seconds to render it. If I do the same in urxvt, it's almost immediate.
If I use alacritty and urxvt side by side, both attached to the same tmux session but without split panes, urxvt also finishes drawing almost immediately, while alacritty takes quite a long while.

Running the same command in the same folder without using tmux, alacritty renders much faster

The speed is does not noticably change when comparing split vs. attached vs. attached&split

I'm using mesa drivers (in case it's relevant)

My system:
![neofetch](https://cloud.githubusercontent.com/assets/3718129/21955386/8f40b6c4-da6a-11e6-92f3-074c9899c743.png)

**Comment by NickeZ** [comment]
Does urxvt implement margins (DECLRMM)? Margins essentially allow the application to only render the half of the screen that is updated.

Do you see the same speed difference when splitting horizontally?

**Comment by d3rrial** [comment]
No I don't. It's quite fast when split vertically, but very slow when splitting horizontally.

No difference for not split but tmux dual-attached tho.

**Comment by jwilm** [comment]
Sounds like the problem here is Mesa drivers. Really need to figure out what's going so wrong there....

cc #125

**Comment by jwilm** [comment]
@d3rrial we landed #410 recently. Mind giving this test a try on the latest master?

**Comment by d3rrial** [comment]
I'd say the limiting factor is tmux now.

I've just run it head to head against urxvt and st, and without timing tools I couldn't tell the difference when running `journalctl |cat` on a 2 year old system with verbose logging.

If anything it's a bit faster. (not by much, with my phone's stopwatch I measured st with 6.4 seconds, urxvt with ~7 seconds and alacritty with ~6.0 seconds.)
the time command gives me:
Alacritty:
journalctl  5.85s user 0.55s system 99% cpu 6.406 total
cat  0.12s user 2.26s system 37% cpu 6.406 total

Urxvt:
journalctl  6.62s user 0.55s system 99% cpu 7.179 total
cat  0.13s user 2.40s system 35% cpu 7.179 total

st:
journalctl  5.99s user 0.56s system 99% cpu 6.558 total
cat  0.10s user 2.29s system 36% cpu 6.558 total

The comparison isn't very fair, since I have urxvt running at a much smaller font-size and I'm having other applications running in the background tainting the results, but it's a good enough approximation.

**Comment by jwilm** [comment]
Sounds like there's no further action required here
