### ISSUE TITLE
Colors from config file not working on Ubuntu

### ISSUE THREAD

**Issue by atelierbram** [jwilm/alacritty#3103]
For colors, only the background-color and maybe cursor color seems to load from the `alacritty.yml` config file (_other things like font-size and padding is behaving as expected_). 

### System

OS: Linux/Ubuntu Mate 18.04.3 LTS 64-bit (no WM)
Version: 0.4.0

**Comment by chrisduerr** [comment]
What are you using to test this? There's no doubt that this is working, so it's likely something specific to your setup where the colors are loaded in Alacritty, but your application inside of the terminal doesn't make use of them.

**Comment by atelierbram** [comment]
I'm just using the Alacritty app itself, nothing else. It is the strangest thing, can't figure it out, tried all sorts of things like temporarily disabling my `.bashrc` ...

**Comment by chrisduerr** [comment]
> I'm just using the Alacritty app itself, nothing else.

The Alacritty app itself does not do anything. You need to run something inside of Alacritty (like a shell) to do some of the heavy lifting.

I'm just curious what you use to read the colors, `echo "\e[31mTEST"` or something like that?

**Comment by atelierbram** [comment]
@chrisduerr  Clicking on the Alacritty icon gives me the app, ... so there is some shell running inside of it, ... Bash? 
Sorry for this but I really don't get it. Echoing out some text-string in a terminal ...? Can you maybe expand on this test code?

**Comment by kchibisov** [comment]
@atelierbram , there was a typo, you should run `echo -e "\e[31mTEST"`, the color of `TEST` should be your red color from a config.

The string you're echoing is an "escape sequence", the '\e[31m" thing tells us to draw everything in red after it.

>Clicking on the Alacritty icon gives me the app, ... so there is some shell running inside of it, ... Bash?

Alacritty is just a terminal emulator. So clicking on an icon just runs your default shell in it (unless you've changed it to run a different program). We're just rendering things for you, no more, no less.

**Comment by atelierbram** [comment]
Thanks for this, the test works as expected: after echoing the test snippet it does show all of the following text in the red color from the config. What does this tell us?

**Comment by kchibisov** [comment]
@atelierbram it tell us that we've reading the colors from the config.

**Comment by kchibisov** [comment]
I mean there a lot of ways to color things in terminals. Apps can use truecolors which we honor and draw as they requested(they send a sequence which rgb color to use). There's also indexed colors (256colors) which you can set in a config (alacritty.yml) or change dynamically from your shell.

**Comment by atelierbram** [comment]
But why - if it can read the colors from the config - is it not outputting these colors (except background and default foreground and cursor colors which do work) in this Ubuntu environment? 
So what shall I do, remove Alacritty and try to reinstall it from source?

**Comment by kchibisov** [comment]
@atelierbram I don't understand you. You said that escape sequence gave you the **right** color. Then it's using the colors from config. What are you using to test colors? `ls`?

**Comment by atelierbram** [comment]
Yes, this is the whole point, and I also don’t understand. Am I missing out on something here?
I use `ls -a` to also see the hidden “.dotfiles”.
I also tested themes in Alacritty on MacOs, so I do know what to expect when the colors _are_ rendered. But if you want I can also make a few screenshots.

**Comment by cole-h** [comment]
A few screenshot or two would be helpful for us (or at least me) to visualize what you mean. Also a gist of your config would help as well, in the off chance you are missing indentation in your color section or something.

**Comment by chrisduerr** [comment]
I'd assume that you're running `dircolors` in your shell rc or profile, which does not properly support modern terminals. Setting the colors directly using `LS_COLORS` is a better idea.

**Comment by atelierbram** [comment]
@chrisduerr Thanks I'm going to look into this. 
For this screenshot I temporarily removed `.bashrc` to be sure only the `alacritty.yml` config file is used as a source, but maybe something else is also affecting it?<br>
![screenshot Alacritty on Ubuntu Mate 18.04.3 LTS 64-bit](https://i.imgur.com/NHCpqn0.png)

I tried different themes, some of my own  which I first tested on MacOS, where they do work:

- [Base2Tone-alacritty](https://github.com/atelierbram/base2tone-alacritty) 
- [Base4Tone-alacritty](https://github.com/atelierbram/base4tone-alacritty)
- [Atelier-Schemes-alacritty](https://github.com/atelierbram/atelier-schemes-alacritty)

**Comment by chrisduerr** [comment]
There are multiple RC files on the system, including some to which only `root` has access to.

Though it does seem interesting that there are no colors at all, which shell do you use?

**Comment by chrisduerr** [comment]
Could you try `ls --color=auto`?

**Comment by atelierbram** [comment]
Yes, this does show some colors (_don't know where they come from_), with the default theme:<br>
![screenshot Alacritty on Ubuntu Mate 18.04.3 LTS 64-bit](https://i.imgur.com/S8sB8QE.png)<br>
with Base4Tone-Modern-N theme:<br>
![screenshot Alacritty on Ubuntu Mate 18.04.3 LTS 64-bit](https://i.imgur.com/2KBsmy3.png)

**Comment by chrisduerr** [comment]
> Yes, this does show some colors

So colors are working correctly then.

> don't know where they come from

Colors in `ls` are taken from the `LS_COLORS` environment variable and populated with reasonable defaults if that is missing.

I'd assume that whatever you were using previously was either setting their own variables (which is a bad idea), or using something like `dircolors` (which is too old and doesn't work with Alacritty).
