### ISSUE TITLE
Clipboard cleared on alacritty window close

### ISSUE THREAD

**Issue by azazar** [jwilm/alacritty#3107]
Clipboard cleared when Alacritty window is closed.

### System

OS: Linux (Ubuntu 18.04.3 LTS)
Version: alacritty 0.4.0
Linux/BSD: X11 Xfce 4

### Workaround

https://wiki.ubuntu.com/ClipboardPersistence#Workaround:_Clipboard_Managers

**Comment by chrisduerr** [comment]
It's working as intended. X11 is designed to handle things this way, if you don't like it, you have to run a clipboard manager.
