### ISSUE TITLE
Alacritty v0.4.0 crashes on macOS when maximized with no decorations in alacritty.yml

### ISSUE THREAD

**Issue by gabebw** [jwilm/alacritty#3110]
This works fine in v0.3.3.

### System

OS: macOS
Version: alacritty 0.4.0 (b115b90)

I just installed via the DMG on the [releases page](https://github.com/jwilm/alacritty/releases/tag/v0.4.0).

### Logs

The output from `/Applications/Alacritty.app/Contents/MacOS/alacritty -vv`

```
Created log file at "/var/folders/4l/52prl3_54bxfpsqpnllff_ch0000gp/T/Alacritty-14660.log"
[2019-12-18 13:09] [INFO] Welcome to Alacritty
[2019-12-18 13:09] [INFO] Configuration loaded from "/Users/gabe/.config/alacritty/alacritty.yml"
[2019-12-18 13:09] [DEBUG] Estimated DPR: 2
[2019-12-18 13:09] [DEBUG] Estimated Cell Size: 13 x 26
[2019-12-18 13:09] [DEBUG] Estimated Dimensions: None
zsh: illegal hardware instruction  /Applications/Alacritty.app/Contents/MacOS/alacritty -vv
````

I reduced the issue to the following `~/.config/alacritty/alacritty.yml` file:

```yml
window:
  startup_mode: Maximized
  decorations: none
```

If I change either setting (e.g. if I set `startup_mode` to `Fullscreen`, or if I change `decorations` to `buttonless`), it works fine.

**Comment by kchibisov** [comment]
duplicate of #2877

**Comment by gabebw** [comment]
Yep, you're right. Closing. Thanks @kchibisov!
