### ISSUE TITLE
macOS: GNU Readline shortcuts & tmux prefix binding

### ISSUE THREAD

**Issue by cmacrae** [jwilm/alacritty#3123]
### System
OS: macOS 10.15.2
Version: 0.4.0

### Description
Hey there! 👋 Thanks very much @jwilm and all the others that work on Alacritty - it's awesome!  

I have some questions regarding keybindings for macOS.  

#### GNU Readline
I want to be able to use [GNU Readline](https://readline.kablamo.org/emacs.html) shortcuts for zooming around my shell. Particularly: `Alt+f`, `Alt+b`.  

At the moment, Alacritty will just interpret these as inputs for the following chars respectively: `ƒ`, `∫` . 
How can I tell Alacritty to interpret these as such? For instance, the native macOS Terminal.app has
>Use Option as Meta key

to do exactly this.

#### tmux prefix binding
When using tmux in Alacritty, it seems it ignores my prefix binding - I use `C-q`.  
When pressing `C-q` to interact with tmux, it gets ignored, and subsequent inputs that are supposed to be interpreted by tmux simply fall through and are inputted.  

What configuration do I need to pass to Alacritty to interpret this properly?

Many thanks in advance for any help on this! 🙏

**Comment by chrisduerr** [comment]
Thi alt issue is a duplicate of #62. Unfortunately due to how macOS handles key bindings, this is a bit of a mess.

The `C-q` mapping might already be fixable though. What do you get when pressing ctrl+v -> ctrl+q?

**Comment by cmacrae** [comment]
Thanks for the prompt response @chrisduerr ! 🙌   
Okay, thanks for the heads up - I'll read over that issue.  

As for tmux, yes `C-v` -> `C-q` does indeed work! How can I set it to not need the `C-v`?  
I should mention, I use the same configuration on Linux, and the `C-v` isn't necessary (`C-q` is correctly passed to tmux).

**Comment by chrisduerr** [comment]
> As for tmux, yes C-v -> C-q does indeed work! How can I set it to not need the C-v?

All ctrl+v does is make your shell print the raw code, rather than interpreting the escape. If ctrl+v -> ctrl+q does correctly print `^Q`, I'd assume that your shell binding might not be working, since Alacritty seems to be forwarding the escape correctly.

**Comment by cwlin** [comment]
@cmacrae 
Try adding the following settings into key_bindings:
```
  - { key: Q,        mods: Control, chars: "\x11"                        }
  - { key: F,        mods: Alt,     chars: "\x1bf"                       }
  - { key: B,        mods: Alt,     chars: "\x1bb"                       }
```

**Comment by cmacrae** [comment]
@chrisduerr Ah okay that makes sense 👍  
@cwlin Wahoo! This works! Thank you very much.  

I'll close this off, given that there is already chatter around it on that other issue.  
I would like to ask, though: is there a good page where these character sequences (`\x1bb`, `\x11`, etc.) are documented with their input/action?
