### ISSUE TITLE
Alacritty not displaying colours correctly when running fish

### ISSUE THREAD

**Issue by docbiz** [jwilm/alacritty#3128]
Alacritty does not seem to behave in the expected way with fish: colours look as though they're mapped to the nearest neighbour within a smaller subset of 24-bit colour space. The following image is one example of this:

<img width="659" alt="colours" src="https://user-images.githubusercontent.com/10088591/71544092-9f122b00-2972-11ea-8036-0b5f2ee925af.png">

[I raised the issue with fish](https://github.com/fish-shell/fish-shell/issues/6455); @faho wrote that:

> Not a fish issue, I'm afraid.
> 
> When $fish_term24bit is set to 1, that causes fish to emit RGB sequences:
> 
> ```fish
> $ set_color 859900 | string escape
> \e\[38\;2\;133\;153\;0m
> ```
> 
> (133 is decimal for 0x85, 153 for 0x99)
> 
> Once that's done, the terminal interprets those sequences however it wants, and in this case it seems alacritty doesn't want to pick that exact color. I know xterm maps RGB sequences back to its 256 color palette, it's possible alacritty does something similar.
> 
> Anyway, the cause is alacritty.

Do you have any ideas?

I am running:
- fish 3.0.2,
- alacritty 0.4.0, and
- macOS 10.14.6 (Mojave).

**Comment by kchibisov** [comment]
>Once that's done, the terminal interprets those sequences however it wants, and in this case it seems alacritty doesn't want to pick that exact color. I know xterm maps RGB sequences back to its 256 color palette, it's possible alacritty does something similar.
>
>Anyway, the cause is alacritty.

Alacritty doesn't do any approximation about colors. You give it proper escapes it draws proper colors, that simple. The escapes seems correct.

**However**, are you using tmux/screen or similar software?

**Comment by docbiz** [comment]
Yes: tmux 3.0a.

**Comment by kchibisov** [comment]
Then your terminal emulator here is tmux. So colors, etc is up to tmux at first place, and then everything goes to alacritty. So if your tmux isn't setup for truecolors it wont work. Could you repro your ussie outside of tmux? Also, please,  test things on a background and not on foreground, since it's less pixel hunt (just use `set_color -b 859900; echo "       "`).

**Comment by docbiz** [comment]
I had no idea that it was tmux's responsibility—thanks for explaining that to me.

For completeness: outside of tmux, the colours are produced correctly (both in fish and zsh); inside of tmux, the colours are not produced correctly (that is, the colours are more coarsely discretised). I tested this by running the following:

```bash
#!/bin/bash
# Based on: https://gist.github.com/XVilka/8346728

awk -v term_cols="${width:-$(tput cols || echo 80)}" 'BEGIN{
    s="/\\";
    for (colnum = 0; colnum<term_cols; colnum++) {
        r = 255-(colnum*255/term_cols);
        g = (colnum*510/term_cols);
        b = (colnum*255/term_cols);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum%2+1,1);
    }
    printf "\n";
}'
```

I'll find what I need to change, update this issue with said fix (for any people as lost as I am), and then close the issue.

Thanks for your help!

**Comment by kchibisov** [comment]
To fix your issue you should setup tmux correctly to handle such things. Try putting the following lines into your tmux config.

```
set -g default-terminal screen-256color # You can use tmux-256color, however it's not installed by default on macOS
set -ga terminal-overrides ",alacritty:RGB" # if your echo $TERM outside of alacritty isn't alacritty, place this $TERM thing instead(it should be xterm-256color otherwise)
```

**Comment by docbiz** [comment]
That works beautifully—thanks again for your help!
