### ISSUE TITLE
Document performance testing guidelines

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#3136]
Most of the time we use vtebench to validate the performance of Alacritty, however that's not necessarily straight-forward and there are a few pitfalls that can invalidate the results.

Over time, a relatively reliable process has been established, however it is not properly documented anywhere. We should probably document it in the Alacritty or vtebench repository and guide people on proper benchmarking procedure in our `CONTRIBUTING.md`.

**Comment by chrisduerr** [comment]
It might also make sense to mention some other tools in use, like https://github.com/pavelfatin/typometer for latency.

**Comment by kchibisov** [comment]
I think we can reuse a lot from https://www.llvm.org/docs/Benchmarking.html

**Comment by chrisduerr** [comment]
Yeah, that's a great point. I'd probably just link to it.
