### ISSUE TITLE
Alt+Backspace does not work in fish shell

### ISSUE THREAD

**Issue by Alexander-Miller** [jwilm/alacritty#315]
Alt+Backspace is supposed to backwards delete entire words, and it works just as I'm used to in bash, however using fish shell what happens instead is that the cursor goes back a single character and fish switches to its version of vi normal mode, as if I had pressed ESC.

**Comment by jonhoo** [comment]
For what it's worth, adding the following to `key_bindings` in `.config/alacritty.yml` fixes that for me:
```yaml
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                   }
```
It basically emulates `ESC` followed by backspace, which is the "real" command for this.

**Comment by bosslady6880** [comment]
Sent from Alto

On Sunday, January 15, 2017 at 10:44 AM Alexander-Miller <notifications@github.com> wrote:

Alt+Backspace is supposed to backwards delete entire words, and it works just as I'm used to in bash, however using fish shell what happens instead is that the cursor goes back a single character and fish switches to its version of vi normal mode, as if I had pressed ESC.
