### ISSUE TITLE
Alacritty reporting wrong config file location on Windows

### ISSUE THREAD

**Issue by Osspial** [jwilm/alacritty#3154]
On Windows, the configuration file path reported by `alacritty --help` is wrong. I'd expect to see this:

```
OPTIONS:
        --class <class>                            Defines window class on Linux [default: Alacritty]
    -e, --command <command>...                     Command and args to execute (must be last argument)
        --config-file <config-file>
            Specify alternative configuration file [default: %APPDATA%\alacritty\alacritty.yml]
```

But instead I see this:

```
OPTIONS:
        --class <class>                            Defines window class on Linux [default: Alacritty]
    -e, --command <command>...                     Command and args to execute (must be last argument)
        --config-file <config-file>
            Specify alternative configuration file [default: $XDG_CONFIG_HOME/alacritty/alacritty.yml]
```

### System

OS: Windows
Version: `alacritty 0.4.0 (b115b90)`
Windows: WinPTY

**Comment by chrisduerr** [comment]
This is also incorrect on macOS I believe, since `XDG_CONFIG_HOME` is Linux specific. So it would just be `~/.config/alacritty/alacritty.yml` on macOS I think.

**Comment by chrisduerr** [comment]
This path is also present in the manpage, however I don't think there's any good way to differentiate between platform there. So I think the best choice is to just keep it the way it is in the manpage.

**Comment by nixpulvis** [comment]
Or `$HOME/.config/alacritty/alacritty.yml`, which I think I prefer since it looks more uniform across platforms (comparing to `%APPDATA%`).

**Comment by chrisduerr** [comment]
That's not correct though. Since `.config` doesn't exist on Windows and the default Alacritty config is not in `$HOME/.config` when the `XDG_CONFIG_HOME` is set to something else on Linux.

**Comment by nixpulvis** [comment]
@chrisduerr i know, I was referring specifically to the macOS string.

**Comment by chrisduerr** [comment]
Ah, that's a good point. That does exist on macOS too, so let's go with that.
