### ISSUE TITLE
Double-Click IPv6 highlighting

### ISSUE THREAD

**Issue by liamdiprose** [jwilm/alacritty#3156]
It would be quite neat to be able to double click IPv6 addresses and have the entire address highlighted for copying, etc. 

Currently, only a single IPv6 address block is highlighted; the colon `:` terminates the highlight.

**Comment by chrisduerr** [comment]
You can remove `:` from your [semantic escape characters](https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L296), if you would prefer that a colon doesn't stop the selection.

**Comment by liamdiprose** [comment]
Well that was just too easy :1st_place_medal:
