### ISSUE TITLE
[Question] Is it possible to get a modifier mapping (ie. using alt key) working in vim?

### ISSUE THREAD

**Issue by doums** [jwilm/alacritty#3158]
### System

OS: Arch Linux `Linux x1c6 5.4.7-arch1-1 #1 SMP PREEMPT Tue, 31 Dec 2019 17:20:16 +0000 x86_64 GNU/Linux`
Version: alacritty 0.4.0
X11, XFCE4, compositor: picom (fork of compton)

Hi,

I noticed that under vim, all my mapping using a modifier key like alt does not seems to be recognized by vim.
Vim mapping example:
```
noremap <A-j> something
" or
noremap <M-j> something
```
Looking in the vim help `h :map-alt-keys`, it says:
```
If the terminal supports the modifyOtherKeys mode and it has been enabled,
then Vim can recognize more key combinations, see |modifyOtherKeys| below.

By default Vim assumes that pressing the ALT key sets the 8th bit of a typed
character.  Most decent terminals can work that way, such as xterm, aterm and
rxvt.  If your <A-k> mappings don't work it might be that the terminal is
prefixing the character with an ESC character.  But you can just as well type
ESC before a character, thus Vim doesn't know what happened (except for
checking the delay between characters, which is not reliable).
```
By default Alacritty is configured to send the escape sequence on modifier key pressed before the following typed character.
We can turn off this behavior within the `alacritty.yml`config file:
```
alt_send_esc: false
```

I thought disabling this option would cause Alacritty to sets the 8th bit of a typed character when pressing a modifier key, as vim expects it.
But it seems not because the mapping still unrecognized.

Is there a solution ?

**Comment by dnkl** [comment]
See https://github.com/jwilm/alacritty/issues/3101

**Comment by chrisduerr** [comment]
Also note that this seems to work just fine in neovim, by using the escapes we already send.

**Comment by dnkl** [comment]
Since most other applications expect alt/meta to send an escape character first, it's probably not a good idea to set that to false.

I'm not a vim user, but
```vim
set <m-j>=<press Ctrl-V><press Meta-J>
map <m-j> something
```
seems to work.

I'm not sure why setting `alt_send_esc=false` doesn't work. Possibly related to your locale being UTF-8, but I couldn't find anything related to that.

**Comment by chrisduerr** [comment]
The `alt_send_esc` binding is for users that need alt to send special characters like separate languages.

As described in the comment, no escapes will be sent at all when that option is active. So it will be impossible for any application to know about alt being pressed at that point.

**Comment by dnkl** [comment]
Ah, _now_ I see... I (ignorantly) assumed turning `alt_send_esc` off would make alacritty emit bytes with the 8:th bit set.

**Comment by doums** [comment]
@chrisduerr I asked fr vim, not for neovim and yes I'm aware that Meta keys works in neovim.

**Comment by jzbor** [comment]
Whilst Alt works fine with me in neovim I do have trouble binding Shift+Enter. I am not sure, whether that is the same problem or the result of a different option/behavior, but I would really like to be able to map this combination. ;)

**Comment by kchibisov** [comment]
>Whilst Alt works fine with me in neovim I do have trouble binding Shift+Enter. I am not sure, whether that is the same problem or the result of a different option/behavior, but I would really like to be able to map this combination. ;)

Shift + enter and enter refer to the same chars. I'm not sure if there's a known special key for shift + enter. At least all terminals I'm aware of are sending the same chars for both of them.

**Comment by jzbor** [comment]
> > Whilst Alt works fine with me in neovim I do have trouble binding Shift+Enter. I am not sure, whether that is the same problem or the result of a different option/behavior, but I would really like to be able to map this combination. ;)
> 
> Shift + enter and enter refer to the same chars. I'm not sure if there's a known special key for shift + enter. At least all terminals I'm aware of are sending the same chars for both of them.

At least according to [this wiki article](https://vim.fandom.com/wiki/Avoid_the_escape_key#Using_the_Enter_key) there seem to be terminal emulators that pass the combination on to vim

**Comment by kchibisov** [comment]
Just fyi vim can be run outside of the terminal so such combination can be run there.

It's the same as ctrl + shift + KEY and ctrl + KEY, since those are also the same for all keys as far as I'm aware of, and that's the reason why ctrl + shift + key is used for terminal specific bindings, since those are free.

**Comment by dnkl** [comment]
XTerm with `modifyOtherKeys=1|2` will emit this for <kbd>Shift</kbd>+<kbd>Return</kbd>:
```
^[[27;2;13~      27 0033 0x1b
         91 0133 0x5b
         50 0062 0x32
         55 0067 0x37
         59 0073 0x3b
         50 0062 0x32
         59 0073 0x3b
         49 0061 0x31
         51 0063 0x33
        126 0176 0x7e
```

**Comment by jzbor** [comment]
With alacritty i get
```
^M 	 13 0015 0x0d
```
from `showkey -a` when wntering Shift+Return

**Comment by jzbor** [comment]
Okay it works with Control+Shift+Space. But I am still wondering whats up with Space+Return. Is there any way to get it through to vim/nvim?

**Comment by jzbor** [comment]
Okay I am very sorry for not testing this before, but it doesn't work in the tty either so it probably isn't even about alacritty... Thank you for your support though and have a nice day ;D

**Comment by kchibisov** [comment]
@jzbor this requires https://github.com/alacritty/alacritty/issues/3101 to be implemented.

**Comment by jzbor** [comment]
Okay. This is how I made it work in the meantime (very hacky...):
```
key_bindings:
  - { key: Return,   mods: Shift, chars: "\x1bo" }
```

**Comment by rafi** [comment]
@jzbor this works for me:
```yaml
key_bindings:
  - { key: Return,     mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return,     mods: Control, chars: "\x1b[13;5u" }
```
