### ISSUE TITLE
Key bindings broken with the latest master (183ceee3adf4ac5a889db3ed904e7adbf9ccb4f1)

### ISSUE THREAD

**Issue by okuuva** [jwilm/alacritty#3160]
After updating to the latest master this morning my key bindings stopped working and I get the following message to the Alacritty logs:

```
[2020-01-07 08:17] [ERROR] Problem with config: unknown variant `I`, expected `Scancode` or `Keycode`; using default value
```

So it seems to me that for some reason Alacritty doesn't recognize `I` as keycode. No idea why, it's a letter amongst the others and have worked fine up until now. Maybe a bug in the config parser or some invisible character in my config that breaks things?

Like said I'm running latest master on macOS Mojave 10.14.6 with 1.14.0 rustc installed using rustup.rs.

```
08:39:20 in alacritty on  master [$] via 𝗥 v1.40.0 •100%
[I] > ~/gits/alacritty/target/release/alacritty --version
alacritty 0.4.2-dev (183ceee)
```

Here's my configuration:
https://l.termbin.com/o0bx

**Comment by RobertAudi** [comment]
Same problem here, and it looks like it was introduced by https://github.com/jwilm/alacritty/commit/183ceee3adf4ac5a889db3ed904e7adbf9ccb4f1.

I compiled the app with https://github.com/jwilm/alacritty/commit/18836f20ddad440a059989076e782b9633d95f39 (the previous commit) and it works fine.

**Comment by okuuva** [comment]
> Same problem here, and it looks like it was introduced by [183ceee](https://github.com/jwilm/alacritty/commit/183ceee3adf4ac5a889db3ed904e7adbf9ccb4f1).
> 
> I compiled the app with [18836f2](https://github.com/jwilm/alacritty/commit/18836f20ddad440a059989076e782b9633d95f39) (the previous commit) and it works fine.

Can confirm, the previous commit seems to be working just fine. So 183ceee definitely broke key binding parsing.
