### ISSUE TITLE
mouse interactions busted after unhandled CSI action ('h')

### ISSUE THREAD

**Issue by sanga** [jwilm/alacritty#3161]
Sorry this is a little bit of a vague bug but I'll update it as I track down what triggers it. When I open a new alacritty window my mouse works just fine (mouse scrolling, selecting and middle mouse button pasting etc). However after some time (or presumably event that happens eventually) mouse mode is busted i.e. mouse pasting will paste random text and mouse wheel scrolling will insert random text.

Running `alacritty -vv` just now, the breakage appears to happen after I see the following message in the logs: `[DEBUG] [Unhandled CSI] action='h', args=[1015], intermediates=[63]`

### System

OS: Linux
Version: alacritty 0.4.1-dev (77acb26)
Linux/BSD: Wayland (sway)

**Comment by chrisduerr** [comment]
URxvt mouse mode is not supported and I'm not aware of many applications that only support that. The best mouse mode is usually SGR and Alacritty also supports both the X10 and UTF-8 mouse protocol.

Which application is sending that escape?

**Comment by sanga** [comment]
So the app in question is skim (www.github.com/lotabout/skim) This used to work just fine however I'm not entirely sure if a skim update or alacritty update broke it. I'll do a little bisecting

**Comment by sanga** [comment]
This was skim's fault. Apologies for the noise
