### ISSUE TITLE
Alacritty does not launch

### ISSUE THREAD

**Issue by lewisdiamond** [jwilm/alacritty#3165]
### System

OS: Linux
Version: 0.4.0
Linux/BSD: X11

Due to https://github.com/rust-windowing/glutin/pull/1256
Fixed in 0.22.0 of glutin.

**Comment by chrisduerr** [comment]
Can you verify that https://github.com/jwilm/alacritty/pull/3164 fixes this?

**Comment by lewisdiamond** [comment]
Yes, that fixes it.

**Comment by Polyhistor** [comment]
Just as a side note, Alacritty can fail to boot up if the value of the `$SHELL` variable is set to another shell scripting variant that you removed earlier. 

For instance, you may have installed `Zsh` and then set your `$SHELL` to point to it, and after you removed `ZSH`, you forgot to set `$SHELL `to point back to `/bin/bash`. 

In this case, Alacritty, won't boot up till you do the following:

1. `sudo chsh -s bin/bash yourUserName`
2. log out and login for the $SHELL the be populated again.

Hope it saves you sometime, and you don't have to figure it out like how I did :)

**Comment by sebvu** [comment]
@Polyhistor your explanation fixed my issue for a slightly different reason! I checked my configuration and found out I specified bin/bash instead of /bin/bash. Thank you so much three years later.
