### ISSUE TITLE
Running alacritty within conemu on Windows

### ISSUE THREAD

**Issue by zingmars** [jwilm/alacritty#3173]
I'm trying out Alacritty on Windows, and was wondering if there was a way to get Alacritty to run within [ConEmu](https://conemu.github.io/). While ConEmu itself is a terminal emulator, it also allows applications to be embedded within it, allowing the user to run other terminal emulators like [mintty](https://mintty.github.io/) and [putty](https://www.putty.org/) inside it. Unfortunately Alacritty doesn't appear to work this way - when started, it ALWAYS opens in a new window -

![image](https://user-images.githubusercontent.com/917126/72073102-e942c700-32f7-11ea-92b4-44e928a2799b.png)

Do you think there's a way to get it to work inside ConEmu?

**Comment by chrisduerr** [comment]
Of course Alacritty always starts in a new window. It's a terminal emulator and not a shell.

I can't tell you how embedding works in `ConEmu`, but you're likely just running different shells inside it and Alacritty is a terminal emulator, not a shell.

I also don't see *why* you would be trying to do this. It makes little to no sense to try and embed multiple terminal emulators into each other.

**Comment by zingmars** [comment]
> It's a terminal emulator and not a shell.
Neither are PuTTY and mintty, and yet ConEmu is somehow able to lock them inside its window (usually they start a new window as well).

> but you're likely just running different shells inside it
No, they're actual emulators as far as I can tell. Mintty in particular can be used to run msys, mingw, cmd, powershell and other shells.

> I also don't see why you would be trying to do this.
It allows me to use a single app to have multiple tabbed console windows within it (which I can then handily hide/show using the quake-style hiding feature it has).

**Comment by chrisduerr** [comment]
> usually they start a new window as well

So does cmd.exe and powershell.exe. But neither of those two are terminal emulators. They are shells that come with their own terminal emulator when launched without a host.

> No, they're actual emulators as far as I can tell. Mintty in particular can be used to run msys, mingw, cmd, powershell and other shells.

I'm not familiar with ConEmu, but if you can run Word inside of it, you can run Alacritty. If you can't run Word inside of it, but just specific applications and all the Windows of those applications look identical, then they're probably just different shells.

The word shell might be confusing a bit, since not only bash/zsh/fish and such can be executed inside terminal emulators as 'shells'. Something like tmux is also a 'terminal emulator', but it can be executed only inside another terminal emulator. However Alacritty is in a different category, it's purely a graphical application, with no 'text mode' to run in (that wouldn't make any sense for Alacritty anyways).

So if you get Word to run inside of it, then sure we can probably get Alacritty working too. But unless *all* graphical applications run inside of it, Alacritty probably won't be able to work.

**Comment by enizor** [comment]
> So if you get Word to run inside of it, then sure we can probably get Alacritty working too. But unless all graphical applications run inside of it, Alacritty probably won't be able to work.

It's [a little more complicated](https://conemu.github.io/en/ChildGui.html) than that (and a lot more confusing).

But alacritty definitely can work inside ConEmu:

![image](https://user-images.githubusercontent.com/25256520/72089105-bb677d80-330b-11ea-8055-07a6277e3870.png)

**Comment by chrisduerr** [comment]
Fair enough, as stated if ConEmu allows running any GUI application inside of itself, it will be able to run Alacritty too. But that doesn't help answering the question why anyone would want that.

**Comment by zingmars** [comment]
Interesting. I'm able to attach to an existing alacritty window just fine, but when I start a new one it just creates a new window no matter what (with or without winpty). Now I'm wondering if there's a ConEmu setting that I've set that messes with it. I'll take a look.

**Comment by kchibisov** [comment]
@chrisduerr I guess the idea is to have tabs.

**Comment by zingmars** [comment]
> But that doesn't help answering the question why anyone would want that.
I already answered. Multiple tabbed / paned terminals inside a single window of various origins (whether it's cmd using windows' default terminal emulator, or mintty (which IS a separate terminal emulator)) .

Linux users use tmux. Windows users use ConEmu.

**Comment by chrisduerr** [comment]
> @chrisduerr I guess the idea is to have tabs.

Yeah, but then you should probably run a multiplexer.

**Comment by zingmars** [comment]
Ok, I found the issue. I had installed alacritty using chocolatey and when trying to run alacritty from shell it used the executable in `C:\ProgramData\chocolatey\bin` (it seems to work as some kind of shortcut?). Actual alacritty executable gets placed in `C:\tools\alacritty`, and I can use it just fine.

> Yeah, but then you should probably run a multiplexer, that's a much better approach.

In this case cmder acts as the multiplexer. If you know a better alternative on Windows, feel free to share, otherwise you're not really adding anything here.

**Comment by nixpulvis** [comment]
@zingmars I would be interested in a similar approach as #1544 for Windows. This issue seems very much like #631 for X11.

Generally speaking Alacritty should be happy to work *with* other applications for things like tabs, but we're not interested in maintaining a tabs feature inside Alacritty itself.

**Comment by zingmars** [comment]
Well as far as a native approach goes, [Microsoft shelved it](https://www.zdnet.com/article/windows-10s-sets-feature-is-gone-and-not-expected-to-return/). The closest thing you might find is [Stardock Groupy](https://www.stardock.com/products/groupy/), but I haven't tested and it's paid software. Sadly, I don't seem to be able to find any good alternatives to using ConEmu on Windows right now.

**Comment by phanirithvij2000** [comment]
@enizor were you able to get it to work exactly?
In your screenshot, I see that alacritty looks like it is embedded in ConEmu.
Or did you configure alacritty to be borderless and adjust its dimensions?

For me, ConEmu still opens alacritty in a new window but just shows the alacritty.exe tab in the list of the tabs.
[Screenshot](https://user-images.githubusercontent.com/32328392/140609451-4f83aefd-620f-4b4d-be0d-660dd513dad9.png)

`Alt+Tab` changes focus back to ConEmu with an empty tab and a blinking cursor and also when in alacritty `CTRL+Tab` doesn't switch tabs.

I know this is all ConEmu related and not alacritty related but as you've achieved it I'm asking what you exactly did step by step.

**Comment by enizor** [comment]
I don't remember doing anything.
The relevant alacritty.yml config entries are:
```yaml
window:
  decorations: full
  startup_mode: Maximized
```
Still working with Alacritty 0.10.0-dev(33db289) and ConEmu 210912

**Comment by adrianog** [comment]
@chrisduerr you can have a multiplexer inside each of the tabs (e.g. each tab is an ssh connection to a different server)
