### ISSUE TITLE
Use tty-rs

### ISSUE THREAD

**Issue by l0kod** [jwilm/alacritty#318]
Alacritty could benefit from the thread-safe implementation of openpty(3) from [tty-rs](https://github.com/stemjail/tty-rs). I'll be happy to make a pull request but I can't test tty-rs on macOS.

**Comment by jwilm** [comment]
> Alacritty could benefit from the thread-safe implementation of openpty(3) from tty-rs

Maybe true, but the library is doing more than providing a nice API on top of `openpty`. For example, I don't really want 4 extra threads to splice a pipe to the pty client.

It also wouldn't be that much effort to make Alacritty's pty API thread-safe.

> but I can't test tty-rs on macOS

This is sort of a deal breaker; you're asking me to be responsible for more code that I'm unfamiliar with.

**Comment by l0kod** [comment]
> Maybe true, but the library is doing more than providing a nice API on top of openpty. For example, I don't really want 4 extra threads to splice a pipe to the pty client.

Agree for the 4 threads. This was design two years ago, long before nice async crates like Futures. tty-rs should migrate to async in the future.

Anyway, you don't need the high-level part, only the [FFI module](https://docs.rs/tty/0.5.0/tty/ffi/index.html) which expose a safe openpty(3).

If you can't test the FFI part for macOS, I'll try to find someone else and I'll come back here if that's OK with you. :)

**Comment by jwilm** [comment]
It looks like `openpty` is thread safe according to the man page. Looking at the impl in the tty-rs crate, it seems like it wouldn't be very portable in the current incarnation. Several ioctls are defined which almost certainly take on different values for BSD flavors.

I just see this feature request being maintenance heavy in the long term, and we don't have problems with the current implementation.

Thanks for the suggestion, but I think I'm going to pass on this.

**Comment by l0kod** [comment]
FYI `openpty` is not thread-safe according to the libc's code (or only it's API). It use a fixed-length and static buffer to deal with the TTY name. Moreover it open the file-descriptor without O_CLOEXEC. Because of this and to have a nice API I rewrote it (cf. https://github.com/stemjail/tty-rs/commit/b7826962649f59dff2249e67ec0430f7240ee08a).

**Comment by jwilm** [comment]
You've convinced me that an alternative implementation of `openpty` is desirable. The thing that sounds right for Alacritty is an API-compatible reimplementation of `openpty`. This would make it a drop-in with the rest of Alacritty's pty handling code.

**Comment by l0kod** [comment]
The tty-rs FFI module offers a safe Rust typed API reimplementation of `openpty`. Feel free to send a pull request if you find some room for improvement. :)
