### ISSUE TITLE
Middle mouse button doesn't Paste or PasteSelection on Mac OSX Yosemite

### ISSUE THREAD

**Issue by samdphillips** [jwilm/alacritty#325]
Relevant config option:
```
mouse_bindings:
  - { mouse: Middle, action: Paste }
```

I have tried with `Paste` and `PasteSelection`, neither pastes.  ~~I've also tried switching the action to the Right mouse button, and it is not working.~~ I was changing the wrong config file.  Right mouse button does work.

Command-V does work at pasting.

**Comment by samdphillips** [comment]
Strategically placed `println!` in `input.rs` I don't see the middle mouse events making it to [Processor::mouse_input](https://github.com/jwilm/alacritty/blob/master/src/input.rs#L323)

**Comment by samdphillips** [comment]
Hrm.  Middle mouse button may not be exposed in [glutin/winit for Mac OSX](https://github.com/tomaka/winit/blob/master/src/platform/macos/mod.rs#L735).

**Comment by samdphillips** [comment]
Found where this needs to be fixed in the custom branch of glutin.

**Comment by jwilm** [comment]
Thanks for putting this together!

I'll add this to my branch, but it should also be contributed to [winit](https://github.com/tomaka/winit). Hopefully Alacritty will not need the glutin branch for much longer.

> And learned too much about OSX.

I know that feeling :rofl:

**Comment by samdphillips** [comment]
Yep.  I initially put together a change for [winit](https://github.com/tomaka/winit), but then remembered that alacritty uses a custom glutin when my build blew up. :)

**Comment by jwilm** [comment]
Duplicate of #234 at this point
