### ISSUE TITLE
x-offset is to low

### ISSUE THREAD

**Issue by Elronnd** [jwilm/alacritty#333]
I'm not sure if this is only a problem on non-retina monitors, but the characters were very squashed together and hard to read.  I had to change the x offset from 2.0 to 3.0 in the default config file.

**Comment by jwilm** [comment]
The default monospace font changes between Linux distros. Or are you on macOS?

**Comment by Elronnd** [comment]
I'm on linux, but two different fonts on two different linuces were too squished together.  It's probably a retina thing.

**Comment by jwilm** [comment]
We've improved our use of font metrics so that 0 offsets can typically be used.
