### ISSUE TITLE
Need to install more packages under arch

### ISSUE THREAD

**Issue by Elronnd** [jwilm/alacritty#337]
On arch, I also had to install `make` and `pkgconfig` to get alacritty to build.

**Comment by SyrupThinker** [comment]
> Packages in the AUR assume that the base-devel group is installed, i.e. they do not list the group's members as dependencies explicitly.
\- [Arch Wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages)

Also the package is maintained by a third party so you would file an issue on the AUR package itself.

**Comment by Elronnd** [comment]
I wasn't installing from the AUR, I just clone the github repo and installed the packages the README said to install.

**Comment by polyzen** [comment]
Duplicate of #294. See https://github.com/jwilm/alacritty/pull/314/files

**Comment by Elronnd** [comment]
@polyzen Alright.  Closed.
