### ISSUE TITLE
If a job is running in the background, the terminal won't exit

### ISSUE THREAD

**Issue by Elronnd** [jwilm/alacritty#339]
If I do, for example, this:

    xclock & disown

and then exit, the terminal gets unresponsive and won't exit; and I have to use my WM's "destroy" utility to get rid of it.

**Comment by jwilm** [comment]
Sounds like a bug; thanks for the report!

**Comment by lukaslueg** [comment]
In this case, `io_thread.join()` in `main.rs` never actually joins. After `join()` is called, we receive one more event of kind `is_hup()` which (as far as I can see) we should respond to by shutting down the event loop. We currently just loop again, which in turn causes the event loop to wait forever and never allow it to join to the main thread. Hilarity ensues.

**Comment by jwilm** [comment]
@lukaslueg I'm not seeing the same thing you are

```rust
if kind.is_hup() {
    break 'event_loop;
}
```

This breaks the outermost loop, and the thread function returns.

**Comment by lukaslueg** [comment]
Yes. My goggles, they do nothing.

But `join()` never returns...
