### ISSUE TITLE
Proper full screen support

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#34]
Currently there's no full screen support in Alacritty. Doing to with `glutin` requires recreation of the window and thus recreation of the OpenGL context.

**Comment by jwilm** [comment]
At least on macOS, there's the automagical full screen button that does the trick. It does occupy another workspace, however, and it doesn't allow stacking the full screen application on top of other apps.

**Comment by davesque** [comment]
I can't get the fullscreen button to work on OS X 10.11.6.

**Comment by jwilm** [comment]
@jimeh That's precisely what this issue is for :)

**Comment by jimeh** [comment]
@jwilm Good good :)...  I just wanted to point out that the native full screen implementation on OSX sucks... lol

**Comment by jedahan** [comment]
@jimeh @jwilm you can maybe take inspiration from https://github.com/mpv-player/mpv/pull/4676/files

**Comment by caiocutrim** [comment]
Well, it was implemented? It seems that is not working in ubuntu when I hit f11...

**Comment by jedahan** [comment]
@caiocutrim since the issue is still open I assume no one has taken a crack at it yet.

**Comment by TaylorDennisLee** [comment]
For what it is worth, on Linux, you can install `wmctrl` which allows you to control windows from the terminal. In my .zshrc, I have an alias: `alias wq='wmctrl -r 'Alacritty' -b toggle,fullscreen'` which allows you to toggle fullscreen with the command `wq`. If you use tmux, you can bind this command to F11 by putting the following into your `.tmux.conf`:

`bind -n F11 run-shell 'wmctrl -r 'Alacritty' -b toggle,fullscreen'`

Notice that this works because 'Alacritty' is the title of the window. So, if your tmux config changes the title, you have to be aware of this and adjust either the new title or the key-binding/alias to match.

Also, I have found trying to invoke an alias with a tmux key-binding does not work, so just type in the entire command it references instead.

`wmctrl` is pretty legit. Type in `wmctrl  -l` to get a listing of all your windows to see what to target with it. You may be able to hit Alacritty in other ways besides with the window title. I don't know what the OS X equivalent it, but if we are preserving the 'purity' of Alacritty by farming out scrollback to tmux, we might consider trying to use wmctrl for as much functionality as we can.

What are your thoughts on binding shell commands to the keys in the Alacritty config? Can you do that with other terminal emulators?

I really witsh we could change the font size without restarting Alacritty. Maybe we could think of giving the `alacritty` command some functionality the way the `tmux` command can be used within tmux to detach sessions, split panes etc. I like the 'the best UI is no UI' approach. We should remain very opposed to cluttering the UI.

**Comment by jwilm** [comment]
@TaylorDennisLee font resizing is available on latest master. You should actually be able to run arbitrary commands through Alacritty key bindings as well. The default [_alacritty.yml_](https://github.com/jwilm/alacritty/blob/567d7273fa010398e6a6ff39e97a72ceb5682621/alacritty.yml) should have an example.

**Comment by botverse** [comment]
@TaylorDennisLee thanks for that, you can still do it not knowing the window name using the id instead, with xdotool:

.tmux.conf

```
bind -n F11 run-shell 'wmctrl -ir `xdotool getwindowfocus` -b toggle,fullscreen'
```

@jwilm I didn't manage to do that in the alacritty.yml file, I guess because of the nested command

```
# this does not work
key_bindings:
  - { key: F11, command: { program: "wmctrl", args: ["-ir", "`xdotool getwindowfocus`", "-b", "toggle,fullscreen" ] } }
```

**Comment by yech1990** [comment]
@botverse 

It seems that alacritty only support full path program.

Only changing the key mapping to full path will work for me.

```json
  - { key: F11, command: { program: "/home/xxx/.local/bin/fullscreen/fullscreen" } }
```

**Comment by botverse** [comment]
@yech1990 I have ~/.local/bin in my $PATH and seems to work

**Comment by yech1990** [comment]
@botverse 
It is weird. I add ~/.local/bin in to my path too.

**Comment by TaylorDennisLee** [comment]
Good call @botverse your approach is much cleaner. It would be kind of cool if we could write inline scripts right in the `alacritty.yml` file, maybe with a keyword argument for what interpreter we want to run on it, kind of like with hashbangs at the beginning of scripts.

```- {key: F11, command: {interpreter:"/usr/bin/env python3", script:"import os; print(os.uname()[1]+'\n')"}```

And the `stdout` would go right into that Alacritty window's output. Maybe it makes less sense to use python in such an instance, but there are a lot of things you can do with Bash one-liners, and it would be cool if you could avoid having to write a script to do them, as @botverse tried to do above. The default `stdin` for one of these commands could be everything currently displayed in the Alacritty window.

I say make Alacritty as versatile and powerful as possible, just don't give it a drop-down menu or any kind of gui anything.

**Comment by chrisduerr** [comment]
@TaylorDennisLee You should already be able to do this, you could for example use `sh` as `command` and then execute any command you want to execute.

**Comment by Sas-18** [comment]
`program: "wmctrl", args: ["-r", ":ACTIVE:", "-b", "toggle,fullscreen" ]`

For what it's worth, this code above also works directly from `alacritty.yml`, no external script nor xdotool required; it's the `:ACTIVE:` option for wmctrl which allows to avoid using xdotool to get our window ID. If nothing else, this should be a bit quicker, with fewer 3rd parties involved. :)

Also, unsure if it's still an issue (or ever was) but an absolute path to wmctrl isn't required here, since wmctrl is (should be) in my/your $PATH.

**Comment by martinezhermes** [comment]
Is there a way to map the full screen green button functionality to a key combo shortcut in the alacritty.yml?

**Comment by chrisduerr** [comment]
@martinezhermes There is no way to do that right now.

**Comment by merqurio** [comment]
Well, you can @martinezhermes, @chrisduerr. I created an Applescript that it's called just as any other command would be called:

```applescript
tell application "Alacritty"
	activate
	delay 0.5
	tell application "System Events" to tell process "Alacritty"
		if front window exists then
			tell front window
				if value of attribute "AXFullScreen" then
					set value of attribute "AXFullScreen" to false
				else
					set value of attribute "AXFullScreen" to true
				end if
			end tell
		end if
	end tell
end tell
```

And then just bind it in `alacritty.yml`:
```yaml
key_bindings:
  - { key: F,        mods: Command, command: { program: "osascript", args: ["/usr/local/bin/a-full"] }}                          
```

**Comment by shsms** [comment]
The wmctrl and xdotool based solutions above work great when used on X11.   Are there any solutions for Wayland?

**Comment by khmelevskii** [comment]
@merqurio thank you for script! It would be great to disable native fullscreen animation. Maybe you can know how to do this?

**Comment by keenahn** [comment]
@merqurio this solution no longer works in 0.29

**Comment by iryan2** [comment]
The green "maximise" button does what I want it to, but does anyone know a way to trigger it with a keyboard shortcut? It's annoying having to reach for the mouse to enter fullscreen.

**Comment by chrisduerr** [comment]
Not yet possible (other than system shortcuts which are already available on macos and linux). However #2012 is likely to add something like this.

**Comment by fchpr** [comment]
> Wayland

How it's supossed to do this?

**Comment by kaimast** [comment]
Is the F11 key on Wayland supposed to work at this point? Because it does not seem to work for me...

**Comment by kchibisov** [comment]
There's no default binding to toggle fullscreen, so define it yourself. `ToggleFullscreen` action in config.

**Comment by glaudiston** [comment]
> ```
> # this does not work
> key_bindings:
>   - { key: F11, command: { program: "wmctrl", args: ["-ir", "`xdotool getwindowfocus`", "-b", "toggle,fullscreen" ] } }
> ```
This worked for me in linux:
```
  - { key: F11, command: { program: "/bin/sh", args: ["-c", "wmctrl -ir $(xdotool getwindowfocus) -b toggle,fullscreen" ] } }
```

**Comment by Narven** [comment]
@akccakcctw that works for me on macOS Big Sur 11.5.2 with alacritty: 0.9.0

**Comment by akshit2649** [comment]
@akccakcctw Thanks it works on linux with alacritty 0.10.0 :)

**Comment by Jay-flow** [comment]
> As @kchibisov said, you only need to define F11 as a key binding in `alacritty.yml` (tested in linux):
> 
> ```yaml
> key_bindings:
>   - { key: F11, action: ToggleFullscreen }
> ```

It's awesome thx :)

**Comment by iysheng** [comment]
After I add 
```
key_bindings:
  - { key: F11, action: ToggleFullscreen }
```
in ``alacritty.yml``, I can toggle fullscreen , but there still a tab extra on the bottom window with tmux.
[![zQyN1s.png](https://s1.ax1x.com/2022/11/21/zQyN1s.png)](https://imgse.com/i/zQyN1s)

**Comment by jwilm** [comment]
@iysheng This is likely due to having leftover pixels that don't quite add up to a column worth of space. You might like enabling `window.dynamic_padding` to spread out the extra space to the top.

**Comment by iysheng** [comment]
> `dynamic_padding`

thanks, it's ok now. 😊

**Comment by iysheng** [comment]
> 

thanks for your replay, it's pretty better now.

**Comment by adyotag** [comment]
I tried
`- { key: F11, action: ToggleFullscreen }`
on Windows 10, but it doesn't work. My version is 0.12.3

**Comment by devlopersabbir** [comment]
Here is my `.toml` file code to make full-screen on the initial open

```toml
[window]
startup_mode = "Fullscreen"
```

If you want to get my full `alacritty.toml` file code see this,, lol

```toml
[font]
size = 22
offset = { x = 3, y = 3 }
normal      = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold        = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic      = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

[colors.primary]
background = "#181818"
foreground = "#00FF00"

[window]
decorations = "Transparent"
dimensions = { columns =  10, lines = 10 }
opacity = 0.5
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"
option_as_alt = "Both"
padding = { x = 7, y = 7 }
blur = true  # Default: false
title = "Sabbir Hossain Shuvo - Alacritty"  # Default: "Alacritty"

[bell]
color = "#003300"
duration = 32
animation = "Ease"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 300
blink_timeout = 7

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
```

**[Don't forget to check out my repository about my env](https://github.com/coderboy-organization/vs-code-as-astrovim)**
