### ISSUE TITLE
"-e command" cli option

### ISSUE THREAD

**Issue by kurnevsky** [jwilm/alacritty#341]
It would be convenient to have this option for launching console apps (tmux, mc, etc) instead of shell.

**Comment by Elronnd** [comment]
Duplicate of #176.

**Comment by Elronnd** [comment]
Duplicate of #176.  It should probably get more attention, though, since it would probably be pretty easy.

**Comment by jwilm** [comment]
Thanks @Elronnd. Closing as duplicate; please subscribe to the original issue for updates.
