### ISSUE TITLE
Missing docs on how to get debug info

### ISSUE THREAD

**Issue by fatso83** [jwilm/alacritty#342]
I just tried out Alacritty on macOS yesterday, and while it seemed super smooth for a while, _it hung after less than five minutes of normal cli activity with 100% cpu usage_. I tried `-h` and `--help` to find any way of capturing a log, but that was quite fruitless. I also looked for pointers on getting debug info in the README, and found nothing. The only thing I could find was an issue on debugging a segfault that mentioned building with debug symbols and executing the process with `rust-gdb`. If that is the way to go, then this should be part of the docs, to lower the noise on the issue tracker.

**Comment by jwilm** [comment]
The issue you encountered is due to a [bug](https://github.com/tomaka/winit/issues/101) in the windowing library we depend on.

Thanks for the suggestion about adding debug instructions--will definitely add that.
