### ISSUE TITLE
"insert" key doesn't work

### ISSUE THREAD

**Issue by Elronnd** [jwilm/alacritty#344]
My keyboard has a "Insert" key that pastes, similar to the middle click.  Binding it has no effect, and it doesn't do anything by default.

**Comment by okuuva** [comment]
You're on Arch, right? What keyboard layout are you using? The following config line works for me on macOS Sierra 10.12.2 (16C67) with both default US QWERTY and my custom Finnish Dvorak on a fresh build from 62294771905917087c484bfc57e4f6ca547d89ba: 
`- { key: Insert,                  action: Paste                        }`

**Comment by guewen** [comment]
For the record, to configure the behaviour I'm used to, which is to have `Shift+Insert` paste the selection clipboard ("middle click clipboard"), I set:

```
  - { key: Insert, mods: Shift, action: PasteSelection }
```

**Comment by okuuva** [comment]
I just confirmed Insert works just fine as a key binding on Debian Jessie stable too. I'm at 08f348ecea0b782cd8539850abe6309d0e5b06c9.

**Comment by Elronnd** [comment]
I've determined that this is a keyboard problem.  Sorry about that.
