### ISSUE TITLE
Random display of characters on git grep + ctrl D

### ISSUE THREAD

**Issue by Dorian** [jwilm/alacritty#346]
Latest alacritty, latest rust (`rustc 1.16.0-nightly`), macOS 10.12.1

<img src="https://cloud.githubusercontent.com/assets/129149/22188368/46492ee6-e0c9-11e6-9594-470530f4d0fc.gif" width="300" />

**Comment by jwilm** [comment]
Thanks for the report!

It looks like you're grepping over the ref tests folder. It's got recordings of terminal protocol which will screw up the display majorly. Not actually a bug.
