### ISSUE TITLE
Can't build current master (1dca5617e2c308b3c2f86d6cfa9d530d8d178885).  Experimental feature error.

### ISSUE THREAD

**Issue by davesque** [jwilm/alacritty#353]
```
Davids-MacBook-Pro-2 ~/projects/alacritty
$ rustc --version
rustc 1.15.0-nightly (8f02c429a 2016-12-15)
Davids-MacBook-Pro-2 ~/projects/alacritty
$ cargo build --release
   Compiling serde_derive v0.8.23
   Compiling alacritty v0.1.0 (file:///Users/david/projects/alacritty)
error: the `proc-macro` crate type is experimental
  |
  = help: add #![feature(proc_macro)] to the crate attributes to enable
error: the `#[proc_macro_derive]` attribute is an experimental feature (see issue #35900)
 --> /Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.23/src/lib.rs:6:1
  |
6 | #[proc_macro_derive(Serialize, attributes(serde))]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(proc_macro)] to the crate attributes to enable
error: the `#[proc_macro_derive]` attribute is an experimental feature (see issue #35900)
  --> /Users/david/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.23/src/lib.rs:14:1
   |
14 | #[proc_macro_derive(Deserialize, attributes(serde))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(proc_macro)] to the crate attributes to enable
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
error: Could not compile `serde_derive`.
To learn more, run the command again with --verbose.
Davids-MacBook-Pro-2 ~/projects/alacritty
$
```

**Comment by jwilm** [comment]
Your compiler is out of date. Please update to any recent nightly.

**Comment by davesque** [comment]
@jwilm Hey.  Sorry to ask this here because I know it's not really the right place for it.  I've been looking everywhere on Google and I can't seem to find anything that will tell me how to update the toolchain that rust is using to compile alacritty.  It seems that cargo is somehow aware of what directory I'm in and is determined to use the outdated toolchain.  Any advice?

**Comment by NickeZ** [comment]
`rustup update` should update your toolchains if you installed rust from `rustup.rs`. For every folder you can then have a local override with `rustup override set nightly`. This way you can have stable as default and nightly in this project. (maybe you already had an override, you could then remove it with `rustup override unset`).

**Comment by davesque** [comment]
Thank you.

**Comment by polyzen** [comment]
Having this issue while trying to [build on Arch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alacritty-git) with Rust 1.15.

rustc 1.15.0 (10893a9a3 2017-01-19)
