### ISSUE TITLE
Allow a relative path for the shell configuration option

### ISSUE THREAD

**Issue by casey** [jwilm/alacritty#358]
It would be nice to allow the shell configuration option to take a binary name instead of an absolute path.

I have alacritty use tmux as the default shell, but tmux is located in different places on different systems, so it would be nice to be able to do:

```
shell:
    program: tmux
```

and have it just work.

I'm willing to write a PR for this feature if it sounds good. Let me know!

**Comment by NickeZ** [comment]
That actually works (at least on ubuntu).. Did you try it?

**Comment by casey** [comment]
Yup, I tried it on macOS and it didn't work.

**Comment by jwilm** [comment]
@casey definitely something that should work. Would love to know why it doesn't on macOS. If you want to look into it and put a patch together, it would almost certainly get merged.

**Comment by casey** [comment]
I think this was some kind of shell configuration problem, and not something related to alacritty. I just tried to reproduce the bug, and a relative path worked fine. I'm not sure what changed, but I'm messing with my shell/path a bunch, so I suspect that.

Sorry for the spurious issue!

**Comment by jwilm** [comment]
Thanks for following up and closing the issue.
