### ISSUE TITLE
Report line, column, and ideally property name in config file error messages

### ISSUE THREAD

**Issue by casey** [jwilm/alacritty#359]
Currently they look like the following:

`problem with config: Custom("Invalid type. Expected `Str`")`

It would be nice if they gave the line, column number, and property path (a.b.c)

**Comment by jwilm** [comment]
There was a new version of the serde library released yesterday which we use for config parsing. It provides some better error messages, but I don't think it's nearly as thorough as you are asking for.

@dtolnay is there any way to get the extra info (line/column/field) in serde errors?

**Comment by dtolnay** [comment]
It is possible but not implemented yet. The yaml-rust library recently added a feature to support propagating line/column information https://github.com/chyh1990/yaml-rust/pull/42. I need to update serde-yaml to use it. I am tracking it in https://github.com/dtolnay/serde-yaml/issues/18.

**Comment by jwilm** [comment]
Oh, wow! That's better news than I had expected :smile:

**Comment by dtolnay** [comment]
I updated serde_yaml to the new serde 0.9.0 error messages and they are slightly better:

> invalid value: string "str", expected an integer at line 2 column 7

> missing field \`w\` at line 2 column 2

> invalid length 2, expected a tuple of size 3 at line 2 column 1

They don't have the property path yet but I filed https://github.com/dtolnay/serde-yaml/issues/42 to track that. It should be pretty quick to add.

**Comment by jwilm** [comment]
@dtolnay I continue to be impressed with your work on serde. I'll be upgrading to 0.9 soon.

Thanks!

**Comment by jwilm** [comment]
Just tested this on master. Example error message:

```
problem with config: Message("invalid type: string \"fale\", expected a boolean", Some(Marker { index: 716, line: 30, col: 14 }))
```

It doesn't give the property name, but it's got enough info to debug it.

**Comment by dtolnay** [comment]
Why are you printing the Debug representation? Errors are designed to be printed with Display.

**Comment by jwilm** [comment]
No reason, that was a mistake. Interestingly, it was the only variant being printed with Debug instead of Display.

Anyway, it's fixed on master.

**Comment by jwilm** [comment]
Oh, and the updated message:
```
problem with config: invalid type: string "fale", expected a boolean at line 30 column 15
```

**Comment by casey** [comment]
Sweeeeeeet!

**Comment by dtolnay** [comment]
I opened #403 to also include the path to the errors.

> font.use_thin_strokes: invalid type: string "tru", expected a boolean at line 51 column 21
