### ISSUE TITLE
Maximize button on alacritty does not work in MacOSX

### ISSUE THREAD

**Issue by Khalian** [jwilm/alacritty#362]
Pressing maximize does not resize and fill screen. I have to manually drag and resize it.

**Comment by martinhanzik** [comment]
The button works for me on 10.12.3, but it gets stuck in mouse-pressed mode and keeps selecting text, it seems that pressing the maximize button does not send the mouse released event.

**Comment by MaxGoh** [comment]
Hi, I'm on MacOS 10.12.2, the maximise button is working properly for me though. I'm able to run Alacritty on full screen.

**Comment by mrkev** [comment]
10.11.6, works for me (albeit the mouse-pressed bug @martinhanzik described)

**Comment by sivamahadevan** [comment]
Works for me as well, the mouse-pressed bug is still there. Is anyone working on a PR for that? Seems very minor.

**Comment by sodiumjoe** [comment]
Relevant winit issues:
1. [maximize](https://github.com/tomaka/winit/issues/460)
2. [selection after resize](https://github.com/tomaka/winit/pull/466)

**Comment by francesca64** [comment]
Both of these issues should be fixed now.

**Comment by chrisduerr** [comment]
@francesca64 Thanks for the heads-up! Great work!

If anyone is still experiencing this problem, please let me know and I'll reopen this issue.
