### ISSUE TITLE
Lack of stdout information on programs ran.

### ISSUE THREAD

**Issue by Khalian** [jwilm/alacritty#363]
There is a lack of information about info posted, other than resize operations and multiplexers ran. 

Here is all the stdout info from one hour of usage:-

    [unhandled osc_dispatch]: [['1',],['.','.','c','/','A','B','A','L','o','a','d','T','e','s','t',],]
    num_cols, num_lines = 182, 57
    num_cols, num_lines = 80, 24
    num_cols, num_lines = 182, 50
    [unhandled osc_dispatch]: [['1',],['b','y','o','b','u',],]
    [Unhandled CSI] action='l', args=[1005], intermediates=[63]
    num_cols, num_lines = 182, 57
    num_cols, num_lines = 182, 50
    num_cols, num_lines = 182, 57
    num_cols, num_lines = 182, 50
    num_cols, num_lines = 182, 57
    num_cols, num_lines = 182, 50

In an ideal world I should see operations done. Is there a different logging level I need to init with so get full access to operation logs. If so would someone mind posting it here?

**Comment by lukaslueg** [comment]
You can increase the verbosity with `-v`, `-vv` and `-vvv`

**Comment by jwilm** [comment]
Closing this unless you are asking for something different than what's in the extra verbosity levels.
