### ISSUE TITLE
Rendering random square glyph on Ubuntu 16.10

### ISSUE THREAD

**Issue by CrashyBang** [jwilm/alacritty#365]
I have a terminal theme that is working fine on Xfce Terminal but rendering with an odd square glyph on alacritty like so:

Xfce Terminal:
![selection_002](https://cloud.githubusercontent.com/assets/2978850/22364949/c0002b0e-e4d9-11e6-870e-bc69e2c46b2a.png)

Alacritty Terminal:
![selection_003](https://cloud.githubusercontent.com/assets/2978850/22364956/d0cfa8b0-e4d9-11e6-9975-2fe34e4fdbba.png)

Please let me know if this is caused by something else I am assuming it is alacritty simply because it works in another terminal but my knowledge of fonts/glyphs is pretty limited.

Cheers.

**Comment by jwilm** [comment]
Hmm that's a bit goofy. Would you mind sharing your PS1? Seems like Alacritty is getting a value for some glyph that Xfce doesn't.

**Comment by CrashyBang** [comment]
Hey, sorry I did a bit of googling but could not figure out what my SP1 was. Could you possibly provide a link with the steps to find it :).

Cheers.

**Comment by jwilm** [comment]
If you run `env | grep $PS1` it should show up.

**Comment by CrashyBang** [comment]
Hey so I tried that and got no output, the I tried `echo $PS1` which returned nothing so I just ran `env` and have attached the output.

Let me know if there is anything else I can do.
[ENV.txt](https://github.com/jwilm/alacritty/files/736515/ENV.txt)

**Comment by N-006** [comment]
Are you using fish shell? If so, could you please run`fish_prompt > prompt.txt` and attach it?

**Comment by jwilm** [comment]
@CrashyBang 

Oh my gosh; I totally brain farted on that grep line earlier. Glad you figured it out though.

**Comment by CrashyBang** [comment]
Have attached `fish_prompt`.
[prompt.txt](https://github.com/jwilm/alacritty/files/736703/prompt.txt)

**Comment by lukaslueg** [comment]
Besides color, your prompt is `HEAVY CHECK MARK, VARIATION SELECTOR-15, SPACE, TILDE, SPACE`. I strongly suspect that [VARIATION SELECTOR-15](http://www.fileformat.info/info/unicode/char/fe0e/index.htm) is the one rendered as a box in Alacritty. If you remove it, things should be fine. Alacritty could be better at handling unicode, though.

**Comment by CrashyBang** [comment]
Hey @lukaslueg I removed the `VARIATION SELECTOR-15` and it is all working, I can always revert later when unicode support is better :).

@jwilm should I leave this open awaiting unicode support or close?

**Comment by lukaslueg** [comment]
I'd suggest to close this in favor of #306

**Comment by CrashyBang** [comment]
Closed in favour of [#306](https://github.com/jwilm/alacritty/issues/306).
