### ISSUE TITLE
Multi-Tab / Multi-Window Support

### ISSUE THREAD

**Issue by MisterTea** [jwilm/alacritty#366]
I would like to use Alacritty but within ssh i run tmux in control mode:

`tmux -CC`

This way I can have multiple tabs and windows and keep their state across reboots.  Is adding tab/window support a priority?

**Comment by jwilm** [comment]
About the only way Alacritty would get tab/window support is via tmux. If this were to get implemented, it would be a long way off.

**Comment by MisterTea** [comment]
Ok thanks. I use tmux with control mode (tmux -CC) where it uses the terminal tabs/windows/scrollbars and I like it too much to give it up. 
Best of luck with the project.
