### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [jwilm/alacritty#369]
Running `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg 'feature="err-println"' --cfg 'feature="default"' -C metadata=ba77e7d3a17f56b2 -C extra-filename=-ba77e7d3a17f56b2 --out-dir /home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps -L dependency=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps --extern fnv=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libfnv-557bfb60b466380f.rlib --extern errno=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liberrno-bd87a5b2fb49c6b0.rlib --extern libc=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liblibc-8d751f39a7380bf8.rlib --extern glutin=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libglutin-82c337e2a6c98fde.rlib --extern serde_json=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde_json-eea150fe898f260b.rlib --extern copypasta=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libcopypasta-b74e6e5f9c8ba141.rlib --extern vte=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libvte-5b6ff9942b6f6079.rlib --extern serde=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde-87a79748e04d6dbe.rlib --extern parking_lot=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libparking_lot-e9d443ebed0629da.rlib --extern log=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liblog-63006d84b4444419.rlib --extern bitflags=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libbitflags-75fc9619122ee22e.rlib --extern lazy_static=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liblazy_static-3b2d015b4349e676.rlib --extern serde_yaml=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde_yaml-be418d3ff0d0e18f.rlib --extern mio=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libmio-878a6eff7e53a112.rlib --extern serde_derive=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde_derive-1f6e4fbcd435203a.so --extern xdg=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libxdg-7b6286b4c94e9a36.rlib --extern notify=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libnotify-254fa238b4fb97b7.rlib --extern cgmath=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libcgmath-7964b7acee178b01.rlib --extern clap=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libclap-393e575a2885d525.rlib --extern font=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libfont-b1e09a02a029609c.rlib -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib`
error[E0277]: the trait bound `grid::Grid<term::cell::Cell>: serde::ser::Serialize` is not satisfied
   --> src/event.rs:121:43
    |
121 |                     let serialized_grid = json::to_string(&grid)
    |                                           ^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `grid::Grid<term::cell::Cell>`
    |
    = note: required because of the requirements on the impl of `serde::ser::Serialize` for `&grid::Grid<term::cell::Cell>`
    = note: required by `serde_json::to_string`

error[E0277]: the trait bound `term::SizeInfo: serde::ser::Serialize` is not satisfied
   --> src/event.rs:124:43
    |
124 |                     let serialized_size = json::to_string(processor.ctx.terminal.size_info())
    |                                           ^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `term::SizeInfo`
    |
    = note: required by `serde_json::to_string`

error: aborting due to 2 previous errors

error: Could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg feature="err-println" --cfg feature="default" -C metadata=ba77e7d3a17f56b2 -C extra-filename=-ba77e7d3a17f56b2 --out-dir /home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps -L dependency=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps --extern fnv=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libfnv-557bfb60b466380f.rlib --extern errno=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liberrno-bd87a5b2fb49c6b0.rlib --extern libc=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liblibc-8d751f39a7380bf8.rlib --extern glutin=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libglutin-82c337e2a6c98fde.rlib --extern serde_json=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde_json-eea150fe898f260b.rlib --extern copypasta=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libcopypasta-b74e6e5f9c8ba141.rlib --extern vte=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libvte-5b6ff9942b6f6079.rlib --extern serde=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde-87a79748e04d6dbe.rlib --extern parking_lot=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libparking_lot-e9d443ebed0629da.rlib --extern log=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liblog-63006d84b4444419.rlib --extern bitflags=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libbitflags-75fc9619122ee22e.rlib --extern lazy_static=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/liblazy_static-3b2d015b4349e676.rlib --extern serde_yaml=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde_yaml-be418d3ff0d0e18f.rlib --extern mio=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libmio-878a6eff7e53a112.rlib --extern serde_derive=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libserde_derive-1f6e4fbcd435203a.so --extern xdg=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libxdg-7b6286b4c94e9a36.rlib --extern notify=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libnotify-254fa238b4fb97b7.rlib --extern cgmath=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libcgmath-7964b7acee178b01.rlib --extern clap=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libclap-393e575a2885d525.rlib --extern font=/home/solaraquarion/.cache/pacaur/alacritty-git/src/alacritty-git/target/release/deps/libfont-b1e09a02a029609c.rlib -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib` (exit code: 101)
==> ERROR: A failure occurred in build().

**Comment by polyzen** [comment]
http://www.co.kerr.tx.us/it/howtoreport.html

https://github.com/jwilm/alacritty#prerequisites
https://github.com/jwilm/alacritty/issues/130#issuecomment-271048646

**Comment by SolarAquarion** [comment]
i have the latest nightly

**Comment by hhsnopek** [comment]
I've also attempted to build from the latest stable & nightly and neither of them allow me to build without this error. 🤔 This is following HEAD as well for alacritty.

**Comment by jwilm** [comment]
Are you building from the git repository or the AUR? Currently waiting on #383 to fix AUR builds.

**Comment by SolarAquarion** [comment]
I should have closed it, it just needed a update of a package

**Comment by jwilm** [comment]
Thanks for the update
