### ISSUE TITLE
Glutin reports wrong KeyboardInput for modifier keys

### ISSUE THREAD

**Issue by lukaslueg** [jwilm/alacritty#372]
I don't know if this is a general problem with glutin or specific to the fork used in Alacritty: The KeyboardInput-events only report `LAlt` / `LControl` / `LWin`, even if the right modifier key is pressed. Since some special characters like `|` can only be reached via the right modifier keys on my keyboard-layout, I can't produce characters like `|` in Alacritty.

Running Darwin Kernel Version 16.3.0 with glutin 0.6.1 (git+https://github.com/jwilm/glutin?rev=af7fe340bd4a2af53ea521defcb4f377cdc588cf)".

> glutin event: KeyboardInput(Released, 62, Some(LControl), , None)
> glutin event: KeyboardInput(Pressed, 61, Some(LAlt), , None)
> glutin event: KeyboardInput(Pressed, 54, Some(LWin), , None)

**Comment by francesca64** [comment]
This should be fixed here: https://github.com/francesca64/alacritty/tree/macos-kb

(Relevant winit PR: tomaka/winit#518)

**Comment by chrisduerr** [comment]
@francesca64 Thanks a ton for tracking down all these issues! Hopefully we'll be able to close a lot of them in the near future.

**Comment by francesca64** [comment]
No problem. There's still a bunch of Linux compose/IME issues dangling too.
