### ISSUE TITLE
AUR package out of date

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#383]
@quininer 

Would you mind updating the AUR package now that Alacritty builds on stable Rust?

**Comment by polyzen** [comment]
Getting `unresolved import` and `constant evaluation` errors while trying to compile `font`.

**Comment by quininer** [comment]
ok.

**Comment by polyzen** [comment]
Turns out Rust 1.15 isn't packaged yet.

**Comment by krixano** [comment]
If you install the rustup package instead of the rust one before installing alacritty-git, it will work.

**Comment by baudlord** [comment]
Getting this error after building with rustup and starting Alacritty.
```

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcollections/vec.rs:1371
note: Run with `RUST_BACKTRACE=1` for a backtrace.

```

**Comment by nikolowry** [comment]
When installing from AUR I get the following error: `no default toolchain found`.

If I clone the AUR package and run `makepkg` locally - everything starts to go well until Cargo throws errors about the experimental/unstable features concerning custom derive macros and `process_exec`:

```
error: custom derive macros are experimentally supported (see issue #35900)
   --> src/ansi.rs:348:62
    |
348 | #[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
    |                                                              ^^^^^^^^^
    |
    = help: add #![feature(proc_macro)] to the crate attributes to enable
```
```
error: use of unstable library feature 'process_exec' (see issue #31398)
   --> src/tty.rs:215:13
    |
215 |     builder.before_exec(move || {
    |             ^^^^^^^^^^^
    |
    = help: add #![feature(process_exec)] to the crate attributes to enable
```

Is there a flag or another easy way to tell Cargo I don't give two-shits whether it's unstable and/or experimental? The only way I could get the package to compile was to install the nightly version of Rust, remove cargo from `makedepends` and use the Cargo that gets installed with Rust.

**Comment by pengowen123** [comment]
You probably have an older version of Rust. Custom derive was only stabilized in 1.15, so if `rustc --version` outputs something older, you should update it.

**Comment by krixano** [comment]
This is exactly what I did, and it worked for me:
* install `rustup` from AUR
* run `rustup default stable`
* install `alacritty-git` from AUR

**Comment by polyzen** [comment]
Rust 1.15 is now packaged.

**Comment by jonhoo** [comment]
Now that we have an alacritty terminfo file (#578), we should probably do the same thing as `rxvt-unicode` does and [provide a split package](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rxvt-unicode#n79) with both `alacritty-git` and [`alacritty-terminfo-git`](https://aur.archlinux.org/packages/alacritty-terminfo-git/).

**Comment by polyzen** [comment]
@jonhoo, better off commenting [here](https://aur.archlinux.org/packages/alacritty-git/).

This issue has been resolved for some time.

**Comment by jonhoo** [comment]
@jwilm request to close?

**Comment by jwilm** [comment]
ty
