### ISSUE TITLE
Scroll on resize

### ISSUE THREAD

**Issue by Elronnd** [jwilm/alacritty#390]
[Here](http://0x0.st/Wqz.png)'s alacritty before being resized, and [after](https://0x0.st/Wqi.png).  [Here](https://0x0.st/Wqo.png)'s what xterm looks after being resized (the desired effect).

**Comment by mbilker** [comment]
Alacritty doesn't have scrollback or any history for that matter. That is why `xterm` shows previous outout. `xterm` contains a scrollback buffer so you can see history. Alacritty is designed to not have this for performance, and other tools like `tmux` provide such a feature.

**Comment by jwilm** [comment]
We may end up [adding scrollback](https://github.com/jwilm/alacritty/issues/124) at which point this could become possible.

**Comment by chrisduerr** [comment]
The original images are not available anymore, but I believe this was fixed in https://github.com/jwilm/alacritty/pull/1506.
