### ISSUE TITLE
ZSH-autosuggestions not rendered

### ISSUE THREAD

**Issue by lukaslueg** [jwilm/alacritty#395]
![alacritty](https://cloud.githubusercontent.com/assets/3148704/22700325/8e4f6d7a-ed5a-11e6-8e3f-2c34b89c17d5.jpeg)

The top portion shows `zsh-autosuggestions` rendered in osx' Terminal, the bottom one is rendered by alacritty. Besides the missing powerline-font, the autosuggestions `-release` is not rendered by alacritty. The cursor is at `|` as in `cargo build -|`.

**Comment by jwilm** [comment]
Can you try this on the latest master? A fix was just landed that may resolve this issue as well.

**Comment by lukaslueg** [comment]
Nope. The logged events suggest however that ZSH does not even try to render the suggestion and move the cursor back so the source of the problem is probably not alacritty to parse or render correctly but to identify it's capabilities sufficiently.

**Comment by lukaslueg** [comment]
Meh. The reason is quite simply that the dark solarized color scheme in default `alacritty.yml` has the background color being the very same as the "bright black" color. Setting the autosuggestion-style to a different color or changing the background/brblack color in alacritty fixes the problem.

My osx' terminal has a different color to prevent exactly that: the text is rendered, but not visible.

**Comment by jwilm** [comment]
Should we update the solarized theme in the wiki?

**Comment by lukaslueg** [comment]
The wiki (and possibly a comment in `alacritty.yml`) should read something like:

> Beware that when using the dark solalized color scheme, the color value for `bright black` matches the background color. Situations know to be affected by this are [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) with the default `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg-8'`, which effectively makes suggestions invisible. You may either change the color scheme or avoid using `bright black` as a color.

**Comment by jwilm** [comment]
Seems like a color scheme specific issue.
