### ISSUE TITLE
OSX: No redraw when changing from/to retina

### ISSUE THREAD

**Issue by philippkeller** [jwilm/alacritty#397]
when switching a alacritty window from thunderbold display (no retina) to the laptop screen (retina) e.g. when unplugging the external screen then the font size is wrong.

I didn't find a way to force the redraw of the screen, as when starting new alactritty instances the font size is correct both on retina as on non-retina

**Comment by philippkeller** [comment]
can somebody give a pointer on how to solve this issue? I've looked through the source code but couldn't find any spot where this could be solved..

**Comment by NickeZ** [comment]
Might be related to glutin/winit. I'm not a mac user so I'm not sure exactly what you want to achieve but you could try some sample application from winit and see if it behaves the same I guess.

**Comment by NickeZ** [comment]
Possible duplicate of #71

**Comment by swansontec** [comment]
Indeed, it is a duplicate of #71.
