### ISSUE TITLE
Error GLSL

### ISSUE THREAD

**Issue by papam8** [jwilm/alacritty#400]
Error :
There was an error initializing the shades: failed compiling shader: 0: 14(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20 ans 1.00 ES

DEBIAN 32 bit

**Comment by l29ah** [comment]
Same problem on my amd64 Gentoo with intel video.

**Comment by jmi2k** [comment]
+1 that one #128

**Comment by jwilm** [comment]
Thanks for the report! Closing as duplicate. Please subscribe to #128 for updates.

**Comment by papam8** [comment]
Sorry, 
Didn't saw that
