### ISSUE TITLE
Issue using Terminus font

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#405]
Backtrace: http://sprunge.us/CiGA
Config: http://sprunge.us/WIhY

As reported by _brotherBox_ on IRC

**Comment by jwilm** [comment]
Fixed

**Comment by jcguu95** [comment]
How did you fix?

**Comment by chrisduerr** [comment]
@jcguu95 There is no problem with the terminus font. Make sure you have it installed and you are using the correct font name.
