### ISSUE TITLE
Flashing terminal on bell

### ISSUE THREAD

**Issue by jonhoo** [jwilm/alacritty#406]
The default alacritty behavior on a terminal bell (i.e., on `\a`), is quite visually disturbing ([a white flash of the terminal](https://jon.tsp.io/share/alacritty-406.ogv)). Could this behavior be customizeable, or at least possible to disable?

**Comment by hhsnopek** [comment]
@jonhoo in your alacritty.yml file set the duration to `0` -
 https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L114

**Comment by jonhoo** [comment]
Ah, I was using an older version of the alacritty template. Thanks @hhsnopek.

**Comment by markandrus** [comment]
Hi @jonhoo,

I wrote that feature so I feel responsible 😬 Any ideas for changes that could make it more friendly? I was thinking letting the color be configurable (or at least the intensity of the color, white) might be helpful. But then visual bell isn't for everyone…

Best,
Mark

**Comment by jwilm** [comment]
@markandrus I've actually been thinking about that a bit. The current approach is to set the clear color and adjust cell background colors. If we took a different approach of drawing a semi-opaque quad over the entire screen, it would open up more possibilities for custom color, min alpha, etc.

**Comment by jonhoo** [comment]
@markandrus while the ability to customize it would obviously be nice, I think having a small set of behaviors (e.g., "none", "flash", "brighten text", "dim text", and "pixelate") and a sane default (probably "brighten") would go a long way. If I were to play devil's advocate for a second, the flash is actually a somewhat dangerous default. For someone with epilepsy, an unexpected, full-screen, white flash on screen straight from a dark terminal, could potentially be a trigger. It is also generally unhelpful for people with light terminal themes, because the flash will only barely be visible (the text will blink white essentially).

@jwilm Drawing a quad over the screen seems like a much better approach.

**Comment by jwilm** [comment]
>  For someone with epilepsy, an unexpected, full-screen, white flash on screen straight from a dark terminal, could potentially be a trigger.

Updated master to have this disabled by default

**Comment by markandrus** [comment]
@jwilm 

> The current approach is to set the clear color and adjust cell background colors. If we took a different approach of drawing a semi-opaque quad over the entire screen, it would open up more possibilities for custom color, min alpha, etc.

Yes, I think that makes sense. I tried to change as few things as possible for #385, but we should make that change.

@jonhoo 

> while the ability to customize it would obviously be nice, I think having a small set of behaviors (e.g., "none", "flash", "brighten text", "dim text", and "pixelate") and a sane default (probably "brighten") would go a long way.

I agree these would be useful behaviors to specify, e.g. with some `behavior` option. The "default" behavior right now is basically "flash background white".

> If I were to play devil's advocate for a second, the flash is actually a somewhat dangerous default. For someone with epilepsy, an unexpected, full-screen, white flash on screen straight from a dark terminal, could potentially be a trigger.

Interesting, I had not considered that. I had modeled the defaults in part off of Terminal.app, which defaults the visual bell to "on" whenever sound is muted. I wonder if they've taken that into consideration. Disabled-by-default is a reasonable position for us to take.

> It is also generally unhelpful for people with light terminal themes, because the flash will only barely be visible (the text will blink white essentially).

That is a good point I overlooked 👍

**Comment by jonhoo** [comment]
Re `behavior`, I think that might actually be *more* useful than the current support for different animation styles. `EaseOutCubic` vs `EaseOutQuint` for example seems like unnecessary complexity in something like a visual bell.
