### ISSUE TITLE
Allacritty hangs when dead key is pressed or emoji keyboard is opened on macOS

### ISSUE THREAD

**Issue by casey** [jwilm/alacritty#411]
For the definition of the somewhat unusual phrase "dead key", see: https://en.wikipedia.org/wiki/Dead_key

I didn't know until looking it up a few minutes ago, but a dead key is one which does not produce a character itself, but combines with the next character pressed. In macOS `option-e` is a dead key that combines with vowels to give them an acute accent: `option-e + o = ó`

Anyways, long story short, alacritty hangs on macOS when any dead key is pressed. It doesn't crash, since the process doesn't exit, but the window freezes and ignores input. I tried option + `e`, `u`, `i`, `n`, and backtick, and they all crashed.

I ran it under lldb, `ctrl-c`-ed after doing it to get to the debugger prompt, and captured this backtrace:

https://gist.github.com/casey/7eb6c2d967da370f106a8d8c5d9761d6

It appears to be waiting for an event which never comes. Kind of sad, really :'–(

(Mach ports and messages are the low-level kernel provided mechanism through which much IPC happens on macOS.)

Also of note is that this happens when you press `command-control-space`, which opens the emoji keyboard on macOS. I captured a stack trace for this, and it appears to be identical.

Obviously, emoji keyboard functionality is of near paramount importance, since without it it is very difficult to include cute emoji in my git commit messages.

**Comment by apexo** [comment]
Possibly related:

Running Linux here (kde on X w/ libinput) … pressing a dead key, e.g. "´" (accent grave), followed by a key that it composes with (e.g. "a"), results in "àà" (two "a" with accent grave).

**Comment by NickeZ** [comment]
@apexo here is what `--print-events` show when you press `´` and `e`. Might be a bug in glutin that we get double characters?

```
glutin event: MouseInput(Pressed, Left)
glutin event: MouseInput(Released, Left)
glutin event: KeyboardInput(Pressed, 21, Some(Equals), , None)
glutin event: KeyboardInput(Released, 21, Some(Equals), , None)
glutin event: ReceivedCharacter('é')
glutin event: KeyboardInput(Pressed, 0, None, , Some("é"))
glutin event: ReceivedCharacter('é')
glutin event: KeyboardInput(Pressed, 0, None, , Some("é"))
glutin event: Awakened
glutin event: KeyboardInput(Released, 26, Some(E), , None)
```

**Comment by sean-** [comment]
I can reproduce this by pushing `ctrl` + `[space]` in `emacs --no-init`, as if to select a region of text.  Once I do this, `alacritty` begins a hot-loop and the CPU spins at 100%.  I tried different `TERM` environment variables and without any emacs configuration files, and it hangs every time.  Version is current (build `715d4f8be8b80604a0b6a8464e55a60660f810a0`).

**Comment by mlsteele** [comment]
I can reproduce what @sean- mentioned by pressing `ctrl + space` at any time. Hangs and spikes cpu in `zsh`, `bash`, and `sleep 30` (just to show it's any program). `ctrl + space` happens to be my `tmux` key but I'm not attached to `tmux` when this happens.

alacritty `f298e0455ab549aac1835ba59467ce06111b9bc9`
rustc 1.17.0 (56124baa9 2017-04-24)
macOS 10.12.4

**Comment by lejboua** [comment]
I'm also able to reproduce this error locally: pressing `~` (on my layout is also a dead key), alacritty hangs in there indefinitely.

alacritty `6659810a22e62f8b41d7bc35ed07905ccebda68b`, May 3
rustc 1.17.0 (56124baa9 2017-04-24)
macOS 10.11.6

**Comment by algesten** [comment]
The actual freezing part of this is fixed by #580, however the [compose key](https://en.wikipedia.org/wiki/Compose_key) part is not (i.e.  option-e + o outputs as `o` when it should be `ó`).

I suggest making a new issue tracking the compose key problem.

**Comment by algesten** [comment]
Incidentally this is the same as #209

**Comment by jwilm** [comment]
Please follow #209 for updates.
