### ISSUE TITLE
Window resize while in vim causes weird render after quitting vim

### ISSUE THREAD

**Issue by DivineGod** [jwilm/alacritty#415]
When quitting vim after having resized the window bigger leaves a bit of the window with a square that's not the background color.

Screenshot of the effect:
<img width="214" alt="screen shot 2017-02-17 at 8 07 57 am" src="https://cloud.githubusercontent.com/assets/36430/23041732/07c10b64-f4ea-11e6-9a59-782a8ca42210.png">

Step to reproduce:
 1. Make sure alacritty is not in fullscreen mode
 2. open `vim`
 3. resize window bigger
 4. quit vim

Observed result is a bit of the window being differently colored. It starts the height of the window but is soon cleared to only be the height of the output which was visible before vim was opened.

This was observed in Mac OS Sierra with vim 8.0 from homebrew. 
I don't know if this is a regression or not.

**Comment by jwilm** [comment]
I'm experiencing this as well but haven't looked into it too much. It may be an issue with saying we support _back color erase (bce)_ but not actually implementing it.

**Comment by jwilm** [comment]
Oh, and I'm actively trying to resolve the _bce_ thing in #407.

**Comment by jwilm** [comment]
@DivineGod if you wanted to debug further, maybe you can see if the branch in #407 exhibits the issue as well?

**Comment by jwilm** [comment]
On further consideration, it's probably not BCE because this is happening in the primary character grid instead of the alternate (which vim uses).

**Comment by DivineGod** [comment]
@jwilm I'll keep debugging this when I have more time later today. I ran with `-vvv` and `--ref-test` and will look into what is happening and add this here.

So far it seems that the characters in that part of the grid have `flags: 3` so `0b00000011` and in the debug output there's a `clear_screen: Below` presumably after the shell prompt has been redrawn.

**Comment by jwilm** [comment]
Oh, interesting. That sounds more like an issue with our save/restore cursor implementation.

**Comment by DivineGod** [comment]
That sounds very likely as it does show up in the whole length before being cleared.

This is what it does immediately before the new prompt line is added:
```unset_mode: SwapScreenAndSetRestoreCursor
CursorRestore
CursorRestore```

**Comment by DivineGod** [comment]
screen does not exhibit the same bug, and it looks like it's adding a CR and and LF after the restore.
