### ISSUE TITLE
Visual Bell produces weird colors with short durations

### ISSUE THREAD

**Issue by lord-re** [jwilm/alacritty#416]
I tried multiple duration values for the Visual Bell and i had small glitches.
I recorded [this video](https://lord.re/alacritty.webm).
Notice that the background is still too white after the animation then after a second get back to it's original color (not an effect of the encoding).

Above 1s there is no bug.

**Comment by jwilm** [comment]
Any ideas @markandrus?

**Comment by markandrus** [comment]
Strange—I may have a chance to look into this this weekend. Very helpful video 👍
