### ISSUE TITLE
config file remarks are misleading

### ISSUE THREAD

**Issue by kfo1182** [jwilm/alacritty#418]
When setting up a config, you used to write "shell: tmux", according to remark. Now this syntax leads to an error. The proper syntax seems to be 
```
shell:
  program: tmux
```
(and maybe some way to specify arguments, I couldn't figure it out).
So easy way to build & install alacritty after reading README.md and default config doesn't work.

**Comment by NickeZ** [comment]
If you look into the sample config files you can see the actual syntax. The config file will have breaking changes until beta or v1 is released.
