### ISSUE TITLE
Is it possible to have something similar to `black screen`?

### ISSUE THREAD

**Issue by AnthonyJacob** [jwilm/alacritty#425]
[Black screen](https://github.com/vshatskyi/black-screen) is terminal emulator build on top of **electron** with pretty impressive 15k stars although in very early stage.

And I really like its design. The separate bottom bar for vc branch and cwd, autcomplete etc. 
But the fact it is electron based completely kills the project for me...

As I am not willing to sacrifice performance but I naturally would like to use terminal with 21st century design I have to logically ask whether it would be possible to achieve something similar in alacritty?

**Comment by lord-re** [comment]
It looks like what you want isn't the terminal's features of black screen but the shell's feature, no ?
You can have customize tmux to have git informations, cwd.
Autocompletion is provided by your shell.
I think what you are looking for is outside alacritty's scope.

> The simplicity goal means that it doesn't have many features like tabs or scroll back as in other terminals.

**Comment by AnthonyJacob** [comment]
I don't think tmux has popups for autocomplete or true icons. 

I am aware that alacritty tries to be simple as possible. I am more interested in the possibilities alacritty brings to the table. 

Could Alacritty with Notty and some addon provide what black screen does - with same level of design but rust performance?

**Comment by AnthonyJacob** [comment]
I should also stress out I am interested in black screen GUI components / features not its functionality. 

Up until now every GUI I have seen was textual. Not only it looks bad, it is also hard to do in it anything more complicated than multiple windows.

**Comment by hhsnopek** [comment]
I think what you want to use is blackscreen, regardless if it runs on electron ... which isn't bad at all. like @lord-re pointed out a combination of tools will get you close, but if you want to create a 1-to-1 of blackscreen in a non-electron environment I don't believe alacritty is the choice here.

**Comment by rafi** [comment]
[Fish](https://fishshell.com/) shell has completion pop-ups with man descriptions out-of-the-box. [Zsh](http://www.zsh.org/) too, but requires configuration.
[Tmux](https://tmux.github.io/) is fantastic for splitting panes, "tabs", scrollback, and it supports true-color.
Alacritty doesn't support emoji icons, [yet](https://github.com/jwilm/alacritty/issues/153).

**Comment by jwilm** [comment]
I don't see this happening
