### ISSUE TITLE
Use error-chain for error handling

### ISSUE THREAD

**Issue by pengowen123** [jwilm/alacritty#426]
It would reduce the boilerplate code for handling errors, and it makes it easy to add additional info to errors to provide more context. This info can be printed as a chain of causes to make it easier to see what caused the error. This change would hurt the performance when errors happen, but I am not sure if this would cause any significant drop performance in non-fatal error handling.

**Comment by chrisduerr** [comment]
I don't think error-chain is a good fit for Alacritty at this point. It can often complicate error handling significantly and Alacritty already doesn't really run into a lot of the problems error-chain is trying to solve.
