### ISSUE TITLE
Mouse scrolling stops working after a while

### ISSUE THREAD

**Issue by vito** [jwilm/alacritty#433]
I haven't been able to work out a repro for this, but after some amount of time scrolling just ceases to work in Alacritty. I use `tmux` + `vim` all the time. No idea what triggers this, just thought I'd open the issue early to see if anyone else is running into it or has more ideas.

/cc @krishicks

**Comment by jwilm** [comment]
My guess is that something is turning off scroll mode in tmux or vim. Next time scrolling stops working, can you try and `:set mouse=a` in vim and `set -g mouse-mode on` in tmux?

**Comment by vito** [comment]
Will do. FWIW it affects both vim scrolling and tmux scrolling, and all other mouse operations (clicking, selecting, etc) work fine.

**Comment by jwilm** [comment]
The additional info is compatible with my proposal. Looking forward to the follow-up :)

**Comment by krishicks** [comment]
I just had this happen for me when the window was resized. I use the tiling window manager i3.

I had two i3 windows open, one running virtualbox and one running tmux. When virtualbox exited it resized the tmux window to fill the remaining space. At that point scrolling was broken. There was no vim running in that pane, either, just alacritty.

`set -g mouse on` did nothing. (`mouse-mode` doesn't exist in this version of tmux).

My tmux session has three panes, two of which are just alacritty and one which is vim. They all changed sizes, but the vim pane still has functioning scrolling.

**Comment by jwilm** [comment]
@krishicks does making the window larger reliably trigger this behavior?

**Comment by krishicks** [comment]
@jwilm Nope; I haven't yet been able to reproduce it. I only noticed it that time because I was scrolling in a window when the resize occurred and resizing broke.

**Comment by jwilm** [comment]
Ugh, one of those bugs.. :unamused:

**Comment by derveloper** [comment]
Hi, i can also report this behaviour. built alacritty today, running tmux with mouse mode does not scroll.
running archlinux.

**Comment by jnelson** [comment]
Just encountered this; also running tmux and neovim. The suggested tmux and nvim config resets have no effect.

A new alacritty instance will scroll one of the previously non-scrolling tmux/nvim sessions as expected, even as the same session continues to be non-scrollable in the old alacritty instance. I'll leave these non-scrolling instances open for a day or two in case there's more debug info available - just let me know what you'd like to see.

Lenovo W550s (Intel+nVidia: the Quadro with proprietary drivers is my default), Ubuntu 16.04, xfce, previously suspended (not usually an issue), two alacritty instances (each running for about a week). One potential hardware difference specific to today that I don't think I've encountered since starting to use alacritty is reaching the "low power" threshold. Not sure whether Ubuntu tries to do anything helpful in that case.

**Comment by jnelson** [comment]
Interesting: the *trackpad* will still scroll. I usually use an external USB mouse. I'm at a different location today due to megasnow, so I'm using a different mouse. The "new" mouse is working fine everywhere but in alacritty.

**Comment by brycefisher** [comment]
Lack of scrolling in alacritty+tmux is really painful right now :-( at least vim can scroll for me.

**Comment by jondo2010** [comment]
I also have scroll problems using vim splits in a tmux split: It seems like it has something to do with focus. Occasionally vim will simply refuse to scroll with the wheel. Changing which pane is currently in focus seems to fix it.

**Comment by jondo2010** [comment]
Restoring the window from maximized and back again seems to (at least temporarily) restore mouse scroll functionality for me.

**Comment by nixpulvis** [comment]
I'm seeming to have intermittent issues (on the order of ms) so scrolling just feels really choppy, or only works sometimes. I'm not sure if this is the same issue or not, but I've tested it in vim, and htop with the same experience.

FWIW I'm using a trackpad for scrolling, which isn't always the best anyway (unless you're on a mac, this is one thing Apple does very well). But I've compared alacritty to termite to be sure it's not the trackpad.

**Comment by chrisduerr** [comment]
Can anyone reproduce this issue with #1141?

**Comment by krishicks** [comment]
I don't think I've experienced this since 8aa8422.

**Comment by chrisduerr** [comment]
If this happens again, especially after #1141, please reopen this issue.
