### ISSUE TITLE
Some glyphs are not displayed properly

### ISSUE THREAD

**Issue by k4nar** [jwilm/alacritty#439]
I've tried with a two variants of Source Code Pro with powerline support, and both cannot display some glyphs with alacritty.

My prompt with termite:
![deepinscreenshot20170224132402](https://cloud.githubusercontent.com/assets/2692721/23303524/e2bb15f2-fa94-11e6-8e72-03c56d56e7e2.png)

My prompt with alacritty:
![deepinscreenshot20170224132437](https://cloud.githubusercontent.com/assets/2692721/23303535/ec2ccbb2-fa94-11e6-9a96-c68f42846cc8.png)

Most unicode chars are displayed properly though. So far I've only identified the following broken chars:
✓ ⚠ ❌ ツ

**Comment by jwilm** [comment]
Thanks for filing the issue! We've actually got a couple of tickets open for tracking this. Please subscribe to #153 and #45.

**Comment by k4nar** [comment]
Ok great, I don't know how I've missed those ones :) .

Thanks for your work, alacritty is truly awesome!
