### ISSUE TITLE
Implement X-specific terminal escape codes

### ISSUE THREAD

**Issue by zacharied** [jwilm/alacritty#444]
In many terminals in ZSH, such as `urxvt`, running `echo -ne "\033;$TEXT\007"` sets the title of the terminal to `$TEXT`. (I'm not sure what the bash version of this would be.) This allows for useful things such as setting the terminal title to the current working directory and updating automatically.

**Comment by siiptuo** [comment]
Alacritty supports changing title. Are you sure that your command is correct? Your command doesn't seem to work with any terminal emulator including urxvt. According to [this](http://tldp.org/HOWTO/Xterm-Title-3.html), it should be `\033]0;`, `\033]1;` or `\033]2;` instead of simply `\033;`.

**Comment by jwilm** [comment]
If your zsh config sets the title whenever a program exits, you might not see the title before it's overwritten. You're also using the wrong escape code. Try this:

```sh
echo -ne "\033]0;FOO\007" && sleep 2;
```

**Comment by zacharied** [comment]
You are correct. Thanks for the tip.
