### ISSUE TITLE
Hasklig font renders incorrectly 

### ISSUE THREAD

**Issue by voxadam** [jwilm/alacritty#445]
When I specify Hasklig as my font the glyphs are spaced incorrectly.

![screenshot from 2017-02-27 02-36-12](https://cloud.githubusercontent.com/assets/108151/23358417/b98596e0-fc96-11e6-9cf5-e848d5fb0f8f.png)

While the above screenshot includes a complex zsh prompt I see the same behavior when launching Alacritty with a default bash prompt by executing `env WAYLAND_DISPLAY= ~/devel/alacritty/target/release/alacritty -vvv -e bash`.

![screenshot from 2017-02-27 02-50-01](https://cloud.githubusercontent.com/assets/108151/23358594/77775d28-fc97-11e6-989f-c27622e60dd9.png)

Here's and example of how things are rendered in Gnome Terminal on the same machine.

![screenshot from 2017-02-27 02-37-42](https://cloud.githubusercontent.com/assets/108151/23358645/b5806b50-fc97-11e6-9c46-bd423913ba73.png)

The _exact_ font that I'm using is available here: https://github.com/i-tu/Hasklig

**Comment by voxadam** [comment]
I neglected to mention that I'm running running an up-to-date copy of Alacritty from git on Fedora 25 x86_64.

**Comment by lord-re** [comment]
Have you tried playing with

> offset:
>   x : ??
>   y : ??
in your alacritty.yml ?

**Comment by voxadam** [comment]
@lord-re, I haven't. I'll try to get to it tonight.

**Comment by lukaslueg** [comment]
What's your exact `font:`-config in `alacritty.yml` ?

**Comment by voxadam** [comment]
23 # Font configuration (changes require restart)                                                                                                                                                                                                                                           
 22 font:                                                                                                                                                                                                                                                                                    
 21   # The normal (roman) font face to use.                                                                                                                                                                                                                                                 
 20   normal:                                                                                                                                                                                                                                                                                
 19     family: Hasklig # should be "Menlo" or something on macOS.                                                                                                                                                                                                                           
 18     # Style can be specified to pick a specific face.                                                                                                                                                                                                                                    
 17     style: Regular                                                                                                                                                                                                                                                                       
 16                                                                                                                                                                                                                                                                                          
 15   # The bold font face                                                                                                                                                                                                                                                                   
 14   bold:                                                                                                                                                                                                                                                                                  
 13     family: Hasklig # should be "Menlo" or something on macOS.                                                                                                                                                                                                                           
 12     # Style can be specified to pick a specific face.                                                                                                                                                                                                                                    
 11     style: Bold                                                                                                                                                                                                                                                                          
 10                                                                                                                                                                                                                                                                                          
  9   # The italic font face                                                                                                                                                                                                                                                                 
  8   italic:                                                                                                                                                                                                                                                                                
  7     family: Hasklig # should be "Menlo" or something on macOS.                                                                                                                                                                                                                           
  6     # Style can be specified to pick a specific face.                                                                                                                                                                                                                                    
  5     style: Italic                                                                                                                                                                                                                                                                        
  4                                                                                                                                                                                                                                                                                          
  3   # Point size of the font                                                                                                                                                                                                                                                               
  2   size: 8.0                                                                                                                                                                                                                                                                              
  1   # Offset is the extra space around each character. offset.y can be thought of                                                                                                                                                                                                          
56    # as modifying the linespacing, and offset.x as modifying the letter spacing.                                                                                                                                                                                                          
  1   offset:                                                                                                                                                                                                                                                                                
  2     x: 2.0                                                                                                                                                                                                                                                                               
  3     y: -7.0                                                                                                                                                                                                                                                                              
  4                                                                                                                                                                                                                                                                                          
  5   # OS X only: use thin stroke font rendering. Thin strokes are suitable                                                                                                                                                                                                                 
  6   # for retina displays, but for non-retina you probably want this set to                                                                                                                                                                                                                
  7   # false.                                                                                                                                                                                                                                                                               
  8   use_thin_strokes: true                                                                                                                                                                                                                                                                 
  9

**Comment by voxadam** [comment]
I should mention that Alacritty appears to be loading the correct font files.

```
# ~/devel/alacritty/target/release/alacritty -vvv
Welcome to Alacritty.
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
got font path="/home/adam/.local/share/fonts/Hasklig-0.9/Hasklig-Regular.otf"
got font path="/home/adam/.local/share/fonts/Hasklig-0.9/Hasklig-Bold.otf"
got font path="/home/adam/.local/share/fonts/Hasklig-0.9/Hasklig-It.otf"
Finished initializing glyph cache in 0.037730288
set_inner_size: 1284px × 316px
width: 1284, height: 316
Cell Size: (16 x 13)
PTY Dimensions: Line(24) x Column(80)
num_cols, num_lines = 64, 59
width: 1024, height: 768
num_cols, num_lines = 80, 24
width: 1284, height: 316
Set Attribute: Bold
Set Attribute: Reverse
Set Attribute: CancelReverse
Set Attribute: Bold
Set Attribute: Reset
carriage_return
carriage_return
[unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/','d','r','o','g','o','n','/','h','o','m','e','/','a','d','a','m','/','d','e','v','e','l','/','n','e','o','v','i','m','%','2','D','q','t','/','b','u','i','l','d','/','b','i','n',],] at line 638
carriage_return

```

**Comment by lukaslueg** [comment]
looks good for me with default config and Hasklig v1.1

**Comment by voxadam** [comment]
I finally got back to this found that things work beautifully after installing Hasklig v1.1. Thanks @lukaslueg.
