### ISSUE TITLE
Change font size by key shortcut

### ISSUE THREAD

**Issue by xliiv** [jwilm/alacritty#446]
I'd like to change font size by a key shortcut, let's say "ctrl++".
I'm wondering how big this change would be.
I changed font in `alacritty.yml` and this didn't take the effect (like theme changing for example).

**Comment by jwilm** [comment]
Thanks for filing the issue! We're tracking this in #286; please subscribe to that issue for updates.

Live reload for font changes aren't yet supported, but it should arrive around the same time as font size changing.
