### ISSUE TITLE
Del key not working on SSH

### ISSUE THREAD

**Issue by michelboaventura** [jwilm/alacritty#454]
I'm having a strange behavior and couldn't figure out what is going on.

If I ssh to *some* machines from within alacritty the Del key stops working on the shell, but works on vim. Using another terminal (I've tried with qterminal and xterm) everything works fine. I've tried to diff the difference from ``stty -a`` between the two terminals but found none. Also played with ``bind`` and ``infocmp`` with no luck. Finally I ran alacritty with debug enable and find out there is no difference between pressing a key local or remote.

I'm using Gentoo locally and both Gentoo and Ubuntu remotely. What puzzles me most is that it works in some Ubunto and Gentoos, but doesn't on another.

Do you have any advice pin this down?

**Comment by jwilm** [comment]
This is because of a bad key binding in the original config. See b169459c991f4ac92d4be2ec5aeb846457157818 for a solution.
