### ISSUE TITLE
alacritty windows don't seem to render until focused in i3

### ISSUE THREAD

**Issue by anderspitman** [jwilm/alacritty#459]
When I switch away from a workspace containing an alacritty window and then switch back, the alacritty window sometimes (50-90% of the time) renders whatever was on the other workspace until I refocus on the alacritty window.

System:
arch with linux 4.9.11-1
i3 4.13-1
GTX950 with nvidia 378.13-2 driver

**Comment by anderspitman** [comment]
If you don't have any ideas off the bat I can try the nouveau driver and see if that helps.

**Comment by jwilm** [comment]
Are you using a recent version of alacritty?

**Comment by anderspitman** [comment]
Master from a couple days ago

**Comment by aeosynth** [comment]
i have the same issue with bspwm (tiling wm similar to i3)

void, linux 4.10_1
bspwm 0.9.2_1
gtx 950, nvidia 378.13_2
alacritty 20170303

**Comment by jwilm** [comment]
Is this still an issue?

**Comment by aeosynth** [comment]
seems fixed for me
