### ISSUE TITLE
`alt` key don't work

### ISSUE THREAD

**Issue by quininer** [jwilm/alacritty#46]
example:

```python
import curses

def Main(screen):
   while True:
      ch = screen.getch()
      if ch == ord('q'):
         break
      elif ch == 27: # ALT was pressed
         screen.nodelay(True)
         ch2 = screen.getch() # get the key pressed after ALT
         if ch2 == -1:
            break
         else:
            screen.addstr(5, 5, 'ALT+'+str(ch2))
            screen.refresh()
         screen.nodelay(False)

curses.wrapper(Main)
```

<img width="556" alt="screenshot_20170103_151940" src="https://cloud.githubusercontent.com/assets/6286761/21601725/2c649b88-d1c8-11e6-8937-47b916038360.png">

**Comment by jwilm** [comment]
I had no idea this was a thing. I've looked into this a bit, and ALT seems to be quite a special case for terminal emulators. When there's a key pressed with alt, the terminal emulator should send the escape character (`27` or `\033` or `\x1b`) followed by the character that was pressed.

**Comment by jwilm** [comment]
Should be fixed :smile:

**Comment by jwilm** [comment]
Also, thanks a lot for the curses script; it was very helpful!
