### ISSUE TITLE
Ability to disable anti-aliasing on Linux

### ISSUE THREAD

**Issue by jamesnvc** [jwilm/alacritty#460]
I prefer to use a non-aliased font for my terminal; as far as I can determine, there's no way to force alacritty to use non-anti-aliased text rendering on Linux?

![screenshot-2017-03-05_21 03 55_est-05 00_1488765835](https://cloud.githubusercontent.com/assets/38405/23594343/4749e51c-01e7-11e7-91a3-11af89a2022e.png)

(Left is konsole, right is alacritty, both using the same font, but alacritty is much "fuzzier")

**Comment by lejboua** [comment]
I've just opened a [pull request](https://github.com/jwilm/alacritty/pull/560) enabling the usage of a `use_anti_alias` boolean flag on the `alacritty.yml` configuration file.

**Comment by sivamahadevan** [comment]
Any progress on this? I would love to be able to use terminus with anti-aliasing disabled, this would help me completely switch to using alacritty on all my systems.

**Comment by jonas-schievink** [comment]
@sivamahadevan https://github.com/jwilm/alacritty/pull/560 implements this

**Comment by jamesnvc** [comment]
That pull request seems to only have implemented the change for macOS though, not linux - the changes are only in `font/src/darwin/mod.rs` while the `ft` implementation is unchanged. I tried looking through the docs for fontconfig but was unable to figure out what the ft equivalent is.

**Comment by jwilm** [comment]
I have some big changes coming on the FreeType and fontconfig side.

**Comment by typekpb** [comment]
@jwilm any news here? For me it's a showstopper (running on linux)
