### ISSUE TITLE
Running tig within Alacritty invokes Zalgo

### ISSUE THREAD

**Issue by ronjouch** [jwilm/alacritty#461]
Running the awesome [tig](https://github.com/jonas/tig/) (2.2.1) under Alacritty (master, aa76b29) / tmux 2.3 / Ubuntu 16.04.2, everything is rainbows initially,

then after n̝͖avigat̠͖̬̹͔̩i͎̱͚̰̝͎͓n̟g̮ co̮m̼̮̖̦̰mi͉̙̮̭̙ts̪̟̫̹̼

--͠ I ̧he͢a̡r ͝it ̕brea̛thi̡n̸g beh͢iǹd͟ ͝the̵ ̨W̸A҉ĻL --,

[Z̶a͢͜͠lg̢o͞](http://knowyourmeme.com/memes/zalgo) ͟i̴̛̕s inv̢͏o̷̡͟ké̡͘d̸ ̵̕a̕͟ńd̴͘҉ ̵c͝or̷̶r͏̵up̵̨ts̛͢ ̡ţ̢h̕e͝ ̧̧͡s̵̴̕c͟r̴eè̸̀-***Ḩ̵̢E̡͢ ͠͞C҉̨O͢͡M̨͟ES͝***

![alacritty-tig-corruption](https://cloud.githubusercontent.com/assets/522085/23619255/17d573c6-0261-11e7-9b4e-fc41a1455b70.gif)

The same `tig` runs smoothly under gnome-terminal+tmux without ever invoking Zalgo.

**Comment by jwilm** [comment]
Thanks for the report! I'll look into it.

**Comment by hlieberman** [comment]
Reproduced on latest master.  This is something specifically to do with the combination of tmux and tig; both tig bare and tig under screen don't have this problem.

**Comment by chrisduerr** [comment]
Can not reproduce on latest master. Probably got fixed at some point in time?

If it's not fixed, please reopen, or tell me to reopen.
