### ISSUE TITLE
Alacritty stops responding when opening OSX emoji panel

### ISSUE THREAD

**Issue by hhsnopek** [jwilm/alacritty#467]
## Description
Upon opening the OSX emoji panel, alacritty becomes non-responsive.

## Steps to reproduce
1. Open alacritty (HEAD)
2. Open emoji panel `ctrl + cmd ⌘ + space`

## Emoji Panel
![](https://cldup.com/biKjYiIE02.png)

**Comment by jwilm** [comment]
Thanks for the report! This is the first reliable repro we've had for a bug in the macOS event loop in glutin :D

**Comment by casey** [comment]
I think this is a dupe of #411

**Comment by hlieberman** [comment]
Closing in favor of #411.
