### ISSUE TITLE
Alacritty DPI on screen change

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#468]
First off, this is freaking amazing, excellent work. 

The issue is when I switch monitors, say from my laptop retina to a non retina via airplay or whichever way to switch displays, the DPI does not update, is there a way to address this? Not an immediately pressing issue, but certainly nice to have. Thanks!

**Comment by blx** [comment]
I've noticed this too. I believe this is the same issue as https://github.com/jwilm/alacritty/issues/71.

**Comment by asilvadesigns** [comment]
@blx ah correct, closing.
