### ISSUE TITLE
Alt-Left/Right and Home/End don't work and prevent alacritty from closing

### ISSUE THREAD

**Issue by spacecowboy** [jwilm/alacritty#474]
Not sure what's up but  `Alt-Left`, `Alt-Right`, `Home`, and `End` do not work as expected.

For example: hitting `Alt-Left` will make the terminal flash and then type a literal `D`.

However hitting `Alt-b` works and does the config suggets `Alt-Left` should do. Issue with escaping somehow?

Even weirder is that after I try any of those "faulty" shortcuts typing `exit` does not quit the terminal and the entire program seems to freeze. It's not even possible to close the window by hitting the "X" in the corner. I have to manually kill the process.

Config is pretty much default:

```
key_bindings:
  - { key: V,        mods: Shift|Control, action: Paste                        }
  - { key: C,        mods: Shift|Control, action: Copy                         }
  - { key: Home,                    chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: Home,                    chars: "\x1b[1~",  mode: AppCursor   }
  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: End,                     chars: "\x1b[4~",  mode: AppCursor   }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
  - { key: F3,                      chars: "\x1bOR"                      }
  - { key: F4,                      chars: "\x1bOS"                      }
  - { key: F5,                      chars: "\x1b[15~"                    }
  - { key: F6,                      chars: "\x1b[17~"                    }
  - { key: F7,                      chars: "\x1b[18~"                    }
  - { key: F8,                      chars: "\x1b[19~"                    }
  - { key: F9,                      chars: "\x1b[20~"                    }
  - { key: F10,                     chars: "\x1b[21~"                    }
  - { key: F11,                     chars: "\x1b[23~"                    }
  - { key: F12,                     chars: "\x1b[24~"                    }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Delete,                  chars: "\x1b[3~",  mode: AppKeypad   }
  - { key: Delete,                  chars: "\x1b[P",   mode: ~AppKeypad  }
```

**Comment by gmile** [comment]
I would add that that changing language via `CMD + Space` while in alacritty also doesn't work in macOS.

**Comment by jonhoo** [comment]
FWIW, I've only noticed this in `bash`, and not in `fish`. Not sure what the difference there is..

**Comment by areading** [comment]
Also FWIW, the case for bash seems to depend on your readline settings. I too had the issue where Home/End didn't work properly (I don't use Alt-Left or Alt-Right), and fixed it by editing my `~/.inputrc`. I added the lower two lines below -- you'll notice they correspond to the same sequence in the config, as well as the returned values from `showkey -a`:

```
$if Bash
"C-i":      beginning-of-line
"C-a":      end-of-line
"\e[1~":    beginning-of-line
"\e[4~":    end-of-line
$endif
```

**Comment by danyim** [comment]
@spacecowboy I added the following lines for support for skipping words via Alt+Left and Alt+Right on macOS:

```
- { key: Left,     mods: Alt,     chars: "\x1bb"                       }
- { key: Right,    mods: Alt,     chars: "\x1bf"                       }
```
(thanks to https://github.com/jwilm/alacritty/issues/93)

I'm still trying to figure out how to get Command+Left (home) and Command+Right (End) to work, however.

**Comment by danyim** [comment]
I'm _very_ close to getting the delete line (Cmd+Delete) working via this keybinding:
```
  - { key: Back,     mods: Command, chars: "\x1b[K",  mode: AppCursor  }
```

I know the value should be `\x1b[2K` because of [what @jwilm mentioned here](https://github.com/jwilm/alacritty/issues/62#issuecomment-333441337) and the [ANSI terminal escape sequence for delete line](http://ascii-table.com/ansi-escape-sequences.php); however, it seems like this escape character isn't recognized. I've also tried `\x1b[J`.

Debugging via 
```
- { key: Back,     mods: Command, chars: "foo",  mode: AppCursor  }
```
seems to print `foo`, so I'm almost certain it's the escape character.

Any ideas?

**Comment by voigt** [comment]
> @spacecowboy I added the following lines to support skipping words via Alt+Left and Alt+Right on macOS:
> 
> ```
>   - { key: Left,     mods: Alt,     chars: "\x1bb"                       }
>   - { key: Right,    mods: Alt,     chars: "\x1bf"                       }
>   - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
>   - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
> ```
> (thanks to #93)
> 
> I'm still trying to figure out how to get Command+Left (home), Command+Right (End), Command+Delete (delete line) to work, however. (Edited)

Worked perfectly for me. However, I needed to uncomment following lines as they would overwrite the settings:
```
#  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
#  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }

```

**Comment by lsnch** [comment]
Other [readline shortcuts](https://readline.kablamo.org/emacs.html) (that are a default in most other terminals) do not work either. Some of the more useful:
`
alt + . -- loop recent arguments
alt + f -- go word forward
alt + b -- go word backward
ctrl / -- undo
alt + d -- delete word ahead
`
Docs on those and info on how they are input are very scarce, or at least I haven't been able to find them. Really the only feature stopping me from using it full time.

**Comment by chrisduerr** [comment]
@spacecowboy I've just tested this and Alacritty behaves exactly the same way as XTerm. Is this still an issue?

**Comment by spacecowboy** [comment]
Seems to be fixed on latest master

**Comment by spacecowboy** [comment]
Closing since it's no longer reproducible

**Comment by chrisduerr** [comment]
Thanks for the update!

**Comment by Empty2k12** [comment]
@danyim Did you ever figure out delete line (CMD+Backspace)?

**Comment by lemeb** [comment]
Can reproduce it here, just after I installed Alacritty on my Mac (Catalina beta). 

Kickass work though! Really impressive :)

**Comment by kchibisov** [comment]
@lemeb Are you on master or on latest release? It should be fixed on master.

**Comment by lemeb** [comment]
I was on the latest release!

**Comment by kchibisov** [comment]
@lemeb  Is it working for you on the latest master? You can launch `cat` and type `Alt+Left`/`Alt+Down` and so on, you should see something like this.
```
^[[1;3D^[[1;3B^[[1;3A^[[1;3C[[1;3F^[[1;3H
```
Also, try launching `alacritty --config-file /dev/null` to test if your configuration is the issue here.

**Comment by lemeb** [comment]
can confirm that it works :)

**Comment by danyim** [comment]
> @danyim Did you ever figure out delete line (CMD+Backspace)?
Yep!

```
    # Delete line
  - { key: Back,     mods: Command, chars: "\x15"                       }
```

There are now "quality of life" keybindings on the official docs which include these: https://github.com/alacritty/alacritty/wiki/Keyboard-mappings#macos

**Comment by Peterpham2401** [comment]
> after the new migration to toml `\x` is deprecated I think
> 
> ```
> [keyboard]
> bindings = [
>   { key = "Left",  mods = "Alt",     chars = "\u001bB"   },
>   { key = "Right", mods = "Alt",     chars = "\u001bF"   },
>   { key = "Left",  mods = "Command", chars = "\u001bOH"  },
>   { key = "Right", mods = "Command", chars =  "\u001bOF" },
>   { key = "Back",  mods = "Command", chars = "\u0015"    },
> ]
> ```

I'm looking for this for a long time. Can I ask how do u know "\u001bOF" stand for "command + right" ??

**Comment by scr2em** [comment]
@Peterpham2401 https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by AndrewP-GH** [comment]
Alt + Back if smb needs
`  { key = "Back",  mods = "Alt",     chars = "\u001b\u007f"  }`

**Comment by Yunir** [comment]
I wonder why the section "General Quality of Life Improvements" with these keybindings for macOS was removed from here https://github.com/alacritty/alacritty/wiki/Keyboard-mappings#macos? was it fixed? 
I am on v0.15.1 and I would still be happy to find it in official wiki, but not just in closed issue. Thanks to scr2em for translating to new format, it worked like a charm!

**Comment by emesterhazy** [comment]
I came here after realizing alt-back didn't work for me anymore. On 0.12.2 it works fine without any config settings, but on 0.16.1 I needed to add the keybinding above to make it work.

Would someone mind explaining what happened? Were these keybindings provided by default in the past?
