### ISSUE TITLE
Vertical alignment in the row different from usual

### ISSUE THREAD

**Issue by dm1try** [jwilm/alacritty#475]
alacritty
<img width="79" alt="screen shot 2017-03-10 at 15 07 51" src="https://cloud.githubusercontent.com/assets/486807/23795013/725c02e2-05a4-11e7-9e9a-00d5b3c9ae7e.png">

iterm2
<img width="92" alt="screen shot 2017-03-10 at 15 08 46" src="https://cloud.githubusercontent.com/assets/486807/23795025/769ab164-05a4-11e7-9dfe-8e7e0b6c6824.png">

I know this is a tiny bug but want to leave it here :)

**Comment by dm1try** [comment]
refs https://github.com/jwilm/alacritty/issues/105 https://github.com/jwilm/alacritty/issues/174
@jwilm it seems this one is a duplicate, feel free to close.

**Comment by jwilm** [comment]
Thanks for the follow up!
