### ISSUE TITLE
Can't see the speed benefits with tmux

### ISSUE THREAD

**Issue by timde9** [jwilm/alacritty#488]
I know your main use case is alacritty with tmux however once launching tmux all the speed benefits of alacritty become bottlenecked by tmux itself.

Perhaps this is just a bug in my setup and this is not intended behavior.  I have run tests on arch linux using both intel open drivers and nvidia proprietary drivers. 

Without tmux alacritty does a 'time find /' in 3s with intel and 1s with nvidia.  When I launch tmux that becomes 10s regardless of driver, which is virtually the same as the 'st' terminal I normally use.

**Comment by 0rdy** [comment]
Well, I've done the two tests with and without tmux in my Termite, urxvt and Alacritty. Tmux has no user configuration.
1. time cat bit.txt.
* Without tmux
![1](https://cloud.githubusercontent.com/assets/9018005/24191006/fc0ca620-0ef2-11e7-9694-1c0079b77e5d.png)
* With tmux
![2](https://cloud.githubusercontent.com/assets/9018005/24191007/fc0cd140-0ef2-11e7-9b4a-cd3d9d9aafb9.png)
2. time find /
* Without tmux
![3](https://cloud.githubusercontent.com/assets/9018005/24191008/fc13e994-0ef2-11e7-9f57-d639eb27ded9.png)
* With tmux
![4](https://cloud.githubusercontent.com/assets/9018005/24191009/fc1a4c58-0ef2-11e7-84bc-d49b0f3fb583.png)

As you can see, it is not the Alacritty problem. Obviously tmux slows down the terminal performance.

**Comment by hhsnopek** [comment]
@0rdy would you mind, for consistency, adding neovim tests here? I'm currently using neovim as my terminal multiplexer and would like to see the comparison on your device 😄

**Comment by 0rdy** [comment]
@hhsnopek yes, I have installed neovim. The order of terminals still the same.
1. time cat big.txt.
![1](https://cloud.githubusercontent.com/assets/9018005/24204105/2530e8a4-0f20-11e7-8a1d-c66e1b2be91d.png)
2. time find /
![2](https://cloud.githubusercontent.com/assets/9018005/24204111/2bf6a5d4-0f20-11e7-9228-8d035dbe742d.png)

**Comment by timde9** [comment]
I just did some experimenting with the latest tmux master and it seems the situation has improved drastically. I am getting nearly identical results now with and without tmux.
