### ISSUE TITLE
background colour does not fill empty lines

### ISSUE THREAD

**Issue by tiziano88** [jwilm/alacritty#490]
I have the following setting in my `.tmux.conf`:

```
set -g window-style 'bg=colour0'
set -g window-active-style 'bg=colour8'
```

The expectation is that the active pane will have a different background colour, but in practice it looks like the following screenshot:

![screenshot from 2017-03-21 10 55 38](https://cloud.githubusercontent.com/assets/387628/24144401/fd0962e4-0e24-11e7-8528-e75bd40819c9.png)

**Comment by DivineGod** [comment]
This is most likely a duplicate of #85, or at least another example of not handling background colour entirely correctly

**Comment by hlieberman** [comment]
Closing in favor of #85.
