### ISSUE TITLE
`-e` flag doesn't appear to work with nvim

### ISSUE THREAD

**Issue by boblehest** [jwilm/alacritty#491]
Edit: (Original comment had too much pebcak)

The -e flag doesn't work with nvim here. [Here's what it looks like when I try.](https://gfycat.com/UnlinedAthleticAbalone)

Update: Looks like a plugin issue in nvim. My bad. :)

Original comment:

The `-e` flag appears to be quite broken.

When running `ls`, the new terminal closes instantly after being created, and alacritty doesn't seem to be happy about it.

```
# alacritty -e ls
num_cols, num_lines = 213, 62
thread 'pty reader' panicked at 'unexpected read err: Error { repr: Os { code: 5, message: "Input/output error" } }', src/event_loop.rs:252
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by NickeZ** [comment]
What did you expect? `ls` will exit immediately after printing the contents of the directory and then `alacritty` will close. You could do something like `alacritty -e bash -c 'ls; sleep 10'`.

**Comment by boblehest** [comment]
NickeZ: Ahh, bit of a mistake on my part when trying to simplify the test case. Originally I tried opening nvim in another terminal, which doesn't work well at all (I get an empty terminal which I can type text into, but real functionality.)

Also, I assume the panic is unwanted behavior.

**Comment by NickeZ** [comment]
`alacritty -e nvim` works for me. That would be a valid bug report ;). nvim doesn't and shouldn't exit immediately.

The panic is probably not wanted, but it might not be the end of the world right now, since this is pre-alpha.

**Comment by boblehest** [comment]
I edited my first comment (so the actual issue will be closer to the top), you can see what it looks like in my terminal there. Is it still a user error?

**Comment by xitep** [comment]
@boblehest is there a reason to close this issue? is there a duplicate ticket for the panic issue?

**Comment by boblehest** [comment]
@xitep 

1. It is not the issue I was trying to report here. The issue I was reporting turned out to be a user error, so I closed the issue.
2. The panic happens when the terminal is closing, and the only side effect (that I am aware of) is that it prints some text to stdout/stderr.

**Comment by xitep** [comment]
thanks for your quick response. it would still be nice if you could set up a ticket for the panic; otherwise nobody will care of fixing it.

**Comment by NickeZ** [comment]
The panic is probably because the child process dies and alacritty tries to read from the child afterwards. I'm going to assume that there is a race condition when the child process dies.
