### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by mscharley** [jwilm/alacritty#495]
Just wanted to mention that I've made a homebrew formula.

Installation instructions:

```
$ brew tap mscharley/homebrew
$ brew install alacritty
```

If you want to cache the rust installation along with cargo libraries across builds then you can append `--with-cache` to the `brew install` command.

Lets keep this thread to discussions of the package itself, issues using it to my issue queue please: https://github.com/mscharley/homebrew-homebrew/issues

**Comment by monouser7dig** [comment]
if this was precompiled  (maybe like once a week?) homebrew-cask would also add it
[https://github.com/caskroom/homebrew-cask/issues/28733](url)
this would reduce the bulk of rust etc. on ones local machine

I acknowledge though that one might argue that alacrity is not yet ready for this

**Comment by jwilm** [comment]
I think it's worth revisiting this once we start producing binaries regularly.

**Comment by srenatus** [comment]
Sharing in case someone else is about to try this: it seems the [issue mentioned in the README](https://github.com/jwilm/alacritty/commit/6659810a22e62f8b41d7bc35ed07905ccebda68b) makes this brew build unsuccessful right now:
```
==> Installing mscharley/homebrew/alacritty --HEAD
==> Cloning git@github.com:jwilm/alacritty.git
Cloning into '/Users/stephan/Library/Caches/Homebrew/alacritty--git'...
remote: Counting objects: 3340, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 3340 (delta 26), reused 30 (delta 13), pack-reused 3289
Receiving objects: 100% (3340/3340), 1.35 MiB | 218.00 KiB/s, done.
Resolving deltas: 100% (2229/2229), done.
==> Checking out branch master
==> make app
Last 15 lines from /Users/stephan/Library/Logs/Homebrew/alacritty/01.make:
   Compiling cgmath v0.7.0
   Compiling serde_derive v0.9.15
   Compiling cgl v0.2.1
error: proc-macro derive panicked
   --> src/ansi.rs:403:73
    |
403 | #[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
    |                                                                         ^^^^^^^^^^^
    |
    = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `alacritty`.

To learn more, run the command again with --verbose.
make: *** [alacritty] Error 101

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mscharley/homebrew-homebrew/issues
```

**Comment by mscharley** [comment]
I've had mixed results but yes, there's often an issue when using homebrews
Rust but I haven't found a good way just yet to use a rustup version.

**Comment by alexanderadam** [comment]
@mscharley your formular just supports OSX at the moment, right?

**Comment by mscharley** [comment]
Yes, but it doesn't even do that well since it relies on homebrews version of Rust which is known to be problematic with alacritty.

**Comment by mscharley** [comment]
More accurately, I've never tried it with anything other than OS X. There's nothing in there that's OS X specific to my knowledge, but I have zero experience with using homebrew on anything but a Mac and very little experience writing brewfiles. Let me know if there's an issue!

**Comment by mscharley** [comment]
I updated the formula to use rustup. This means that:

* The bad
    * Every build pulls down a new copy of Rust.
    * Every build pulls down a new copy of all the libraries that Alacritty uses.
    * Every build is even slower.
* The good
    * No runtime dependency on Rust.
    * It actually works, *reliably*.

I'm disinclined to pull rustup/cargo dependencies into the users home folder so that it can be cached between builds because some people (myself included at the moment) don't already have a Rust installation and just want Alacritty. This way also works well for building/publishing packages.

**Comment by mscharley** [comment]
I also added build caching, just in case that's something you really, really want. Details in the original post now.

@jwilm I mostly opened this ticket to make you aware that this existed. In my mind, it's the OS X equivalent to an AUR package for Gentoo so I wasn't sure if you'd want to add it to the README as an easier way to install for Mac users.

**Comment by peng051410** [comment]
To do this, I got error
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
pandoc ✔                                                   cabal-install                                              pandoc-citeproc

==> Installing alacritty from mscharley/homebrew
==> Cloning https://github.com/jwilm/alacritty.git
Updating /Users/tomyli/Library/Caches/Homebrew/alacritty--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 865727c Remove redundant copy when selecting font_key
==> curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: An exception occured within a build process:
  ArgumentError: wrong number of arguments (given 1, expected 2)
```

**Comment by jedahan** [comment]
Mentioning #1491 since it is related to packaging concerns

**Comment by mscharley** [comment]
Just a quick note to say that the formula now supports the 0.2.1 release and includes information on how to install terminfo as per @jedahan's comment.

**Comment by Amar1729** [comment]
@mscharley I wrote up a simple [Caskfile](https://github.com/Amar1729/homebrew-cask/blob/fcee70a38b9a88494cfaeee359a96f569e25d668/Casks/alacritty.rb) for Alacritty since [tagged releases will now produce binaries](https://github.com/jwilm/alacritty/issues/80).

The binary produced by v0.2.2 still seems to actually be version 0.2.1, and v0.2.3 didn't produce any yet, so I'm waiting to open an official PR for it on homebrew-cask until the prebuilt binaries are regularly being produced.

You have any thoughts on the caskfile? One thing I couldn't figure out how to do was get it to download the alacritty_macos.yml file and put it into $HOME during install.

**Comment by chrisduerr** [comment]
@Amar1729 The v0.2.3 binary for macOS should already be available.

**Comment by Amar1729** [comment]
Oh sweet. Guess I must've had an old version of the page open, thanks @chrisduerr

**Comment by mscharley** [comment]
I'm not familiar with casks, but this line seems wrong:

```
  auto_updates true
```

Alacritty doesn't update itself yet does it? Or did I miss a patch note somewhere? Or does it play into this?

```
  version '0.2.2'
  sha256 '832b2f8e0e79f9ef159415435bf21b5db837b9febe849332039db2367519a534'

  url 'https://github.com/jwilm/alacritty/releases/download/binaries/Alacritty.dmg'
```

That download URL will be the latest version, not version 0.2.2. This will invalidate the hash when the next release goes out.

**Comment by Amar1729** [comment]
Oh yeah missed that. Fixed that and updated the url -
https://github.com/Amar1729/homebrew-cask/blob/a3ee3f164829df29a898d9e63fde5b351ba57a69/Casks/alacritty.rb

**Comment by mscharley** [comment]
That looks reasonable to me. Regarding your concerns about the example config, this also applies to the terminfo entries too. Neither of those being installed would be show stoppers for me personally using the cask. That said, alacritty was my first brewfile and I've not ever looked into casks so I'm not sure how to help further with actually getting them working.

**Comment by chrisduerr** [comment]
Since the homebrew installation method is now part of the official documentation, this issue seems resolved.
