### ISSUE TITLE
Slow start up when using fzf --height

### ISSUE THREAD

**Issue by wooken** [jwilm/alacritty#497]
When using `fzf` with `--height` option, fzf is slow to start up. This issue is not occurring with termite.

alacritty config: default
fzf version: 0.16.6

It takes a noticeable ~1 second for `fzf --height 40%` to start up.

Still trying to figure out how fzf creates this window. It may be ncurses, as that is used for the full screen window.
Anyone else experiencing this or know where I can start?

**Comment by krruzic** [comment]
Just tested on a build from master that I made today, starts instantly.

**Comment by wooken** [comment]
```
 ~ ❯❯❯ pacman -Qi alacritty-git
Name            : alacritty-git
Version         : 0.1.0.453.g715d4f8-1
Description     : A cross-platform, GPU enhanced terminal emulator
Architecture    : x86_64
URL             : https://github.com/jwilm/alacritty
Licenses        : Apache-2.0
Groups          : None
Provides        : alacritty
Depends On      : freetype2  fontconfig  xclip
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : alacritty
Replaces        : None
Installed Size  : 2.79 MiB
Packager        : Unknown Packager
Build Date      : Thu 23 Mar 2017 07:04:48 PM PDT
Install Date    : Thu 23 Mar 2017 07:05:06 PM PDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```
```
[Desktop Entry]
Type=Application
TryExec=alacritty
Exec=alacritty
Icon=utilities-terminal
Terminal=false
Catagories=System;TerminalEmulator

Name=Alacritty
GenericName=Terminal
Comment=A cross-platform, GPU enhanced terminal emulator
StartupWMClass=Alacritty
Actions=New

[Desktop Action New]
Name=New Terminal
Exec=alacritty
```

The latest commit on alacritty master branch as of today is: March 8. I re-built alacritty on March 23. Also checked Alacritty.desktop for the changes from commit 715d4f8be8b80604a0b6a8464e55a60660f810a0 to make sure that I have the latest commits.

If no one else is experiencing this, I'll close this issue.

**Comment by siiptuo** [comment]
I can confirm this issue on Linux with the current Alacritty master and fzf 0.16.6. Other terminal emulators I tested don't have this problem.

**Comment by wooken** [comment]
In addition, this does not seem to happen in tmux

**Comment by krruzic** [comment]
That's probably why I didn't have it :)

**Comment by wooken** [comment]
I ran a bunch of builds and it seems #551 might have fixed this issue. Can anyone else confirm?

**Comment by siiptuo** [comment]
Fixed for me also.

**Comment by wooken** [comment]
Thanks @siiptuo. Closing issue.
