### ISSUE TITLE
Native clipboard support on X11 and Wayland

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#5]
The biggest issue I've been having with alacritty recently is pasting from the clipboard. Copying would be nice to, but apparently pasting comes up _a lot_.

**Comment by jwilm** [comment]
The only X11 clipboard implementation in Rust is GPL licensed; no way can we use that. A new implementation based off resources like https://www.jwz.org/doc/x-cut-and-paste.html and the [ICCCM](https://tronche.com/gui/x/icccm/) will need to be written.

**Comment by jwilm** [comment]
We now have paste support on X11 by shelling out to xclip. This is obviously less than ideal, but at least there's pasting.

**Comment by mrak** [comment]
Just thought I'd share [rust-clipboard](https://github.com/aweinstock314/rust-clipboard) used by Mozilla Servo. It's Apache-2.0 licensed.

I don't think it can be used directly but its in-code comments offer insight into ICCCM atoms and selections in X11

**Comment by jwilm** [comment]
Thanks for the suggestions! If it's the same library I looked at, the X11 portion was actually GPL licensed. Servo removed clipboard support at some point because of it.

I'll take another look this weekend.

**Comment by mrak** [comment]
Oh, you're right. They borrowed code from xclip which is GPLv2 :(

**Comment by mrak** [comment]
Have you looked into `xsel` code?

It appears to be using a permissive, custom license that should be compatible.

http://www.vergenet.net/~conrad/software/xsel/#License

**Comment by jwilm** [comment]
@mrak Hadn't looked into that! We still would want a Rust implementation of it. Maybe deriving one from the `xsel` implementation would be possible with that license. Probably easier than going through ICCCM.

**Comment by spease** [comment]
The inability to copy-paste continues to be a chronic annoyance on Linux, and I see quininer implemented something that may address this. Are there any plans to merge it into the main releases?

**Comment by chrisduerr** [comment]
The PR from quininer should be good, but if you want copy/paste right now, you can use `xclip` for that. From a user-perspective it shoud work just fine on linux right now.

**Comment by philippludwig** [comment]
@chrisduerr Could you elaborate on this? I have tried `xclip`  and `autocutsel` with various parameters, but never got sane Copy+Paste to work. All I want is to paste entries from parcellite to alacritty.

**Comment by chrisduerr** [comment]
@philippludwig Assuming that the configuration file has the actions setup correctly, I don't see what wouldn't work.

If you wish to investigate this, please don't clog this issue with troubleshooting though. If it doesn't work for you, open a separate issue.

**Comment by chrisduerr** [comment]
The way forward with this will likely be to switch from `copypasta` to the `clipboard` library and add functionality to `clipboard` to support the Wayland clipboard.

**Comment by FlyingWombat** [comment]
I'm not very familiar with this project, so forgive my ignorance.  
But, I'm surprised no one has mentioned https://github.com/YaLTeR/wl-clipboard-rs  
I guess it is only half a solution to this issue, as it is wayland only. But, is there another reason this isn't being considered?

**Comment by chrisduerr** [comment]
> This crate is intended to be used by terminal applications, clipboard managers and other utilities which don't spawn Wayland surfaces (windows). If your application has a window, please use the appropriate Wayland protocols for interacting with the Wayland clipboard (wl_data_device from the core Wayland protocol, the primary_selection protocol for the primary selection), for example via the smithay-clipboard crate.

The reason is right there in the readme. And the recommendation (use smithay-clipboard instead) is exactly what is planned.

**Comment by FlyingWombat** [comment]
Oh, sorry, I missed that part.
