### ISSUE TITLE
Right Mouse Click does not work in ncmpcpp

### ISSUE THREAD

**Issue by Holzhaus** [jwilm/alacritty#506]
In [ncmpcpp](https://rybczak.net/ncmpcpp/) you can use the right mouse button to play a track directly. This works in `urxvt` and `gnome-terminal`, but not in `alacritty` - nothing happens if I right-click on a track.

Left clicking (select a track) and scrolling using the mouse wheel works though.

```
$ cat /etc/issue
Arch Linux \r (\l)

$ alacritty -V
alacritty 0.1.0

$ ncmpcpp -v
ncmpcpp 0.7.7
optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info
 - outputs
 - visualizer
 - clock
encoding detection: enabled
built with support for: curl fftw ncurses taglib unicode

$ pacman -Qi ncurses | head -n 4
Name            : ncurses
Version         : 6.0+20170128-1
Description     : System V Release 4.0 curses emulation library
Architecture    : x86_64
```

**Comment by Holzhaus** [comment]
I just checked, it does not work in `tmux` either.

**Comment by mwgkgk** [comment]
Same thing in Vim: `<RightMouse>` binds aren't triggered. Same thing with `<MiddleMouse>` even when it's not defined in `mouse_bindings`. `<LeftMouse>` works fine.

Please make it possible to have Alacritty just pass these mouse events down the line. 👍
