### ISSUE TITLE
Spurrious  (and awesome) GL glitchout upon laptop close/reopen

### ISSUE THREAD

**Issue by liz-mars** [jwilm/alacritty#516]
Lenovo TP T450, Ubuntu 16.04.2. Alacritty 0.1.0. I have not seen this one very often, but when it happens, it's spectacular. The screencap doesn't even do it justice; it transforms in 3D-ish ways as I type. 
![image](https://cloud.githubusercontent.com/assets/315987/25154682/83a49094-2446-11e7-9a9b-e9189425b79a.png).

THESE ARE THE FAILURE MODES OF THE FUTURE WHICH WE WERE PROMISED IN BLADERUNNER

**Comment by Valloric** [comment]
@jwilm Consider not fixing this purely because of how blazingly awesome it is. :D

I'm only half-joking.

**Comment by Valloric** [comment]
@liz-mars You MUST give us a video! The tubes of the internets demand it! :)

**Comment by liz-mars** [comment]
Next time it happens I will ^_^

**Comment by Aventura5** [comment]
Woah. Not fair, I can't write bugs like that!  :grinning:

**Comment by jwilm** [comment]
@Aventura5 

Joke is on you folks; I don't know how to start _fixing_ bugs like that! :upside_down_face:

@liz-mars thanks for filing this one. I hereby grant you the _Coolest Bug_ :tm: award. :trophy:

In all seriousness, I wouldn't know where to start trying to repro this, and as far as I know, you're the only one affected. If that's actually true, I'd suspect an issue with your display server or hardware.

**Comment by liz-mars** [comment]
@jwilm It's quite all right; I'd be sad to forego an opporunity to see this again. (It's a rare treat.)

Here's wishing you happy hacking...on every other ticket. ~_^ And thanks for alacritty, it's awesome!

**Comment by pvaibhav** [comment]
We need a config option to enable this bug to affect all of us 😁
