### ISSUE TITLE
Arrow keys not working in Ubuntu 16.04 

### ISSUE THREAD

**Issue by davidnuon** [jwilm/alacritty#52]
Alacritty doesn't seem to accept arrow keys as input.

**Comment by basile-henry** [comment]
From the FAQ on the README:

- *My arrow keys don't work* It sounds like you deleted some key bindings from your config file. Please reference the default config file to restore them.

Maybe you missed the following step:

- There is an `alacritty.yml` at the git repository root. Copy this to either `$HOME/.alacritty.yml` or `$XDG_CONFIG_HOME/alacritty.yml`

**Comment by davidnuon** [comment]
Silly me, I forgot the dot at the beginning. It works now.
