### ISSUE TITLE
Cursor is being put in the wrong place when running screen

### ISSUE THREAD

**Issue by trashhalo** [jwilm/alacritty#523]
Master -- HEAD a99a69cfcb983b923cb89c6faf5ace3b89d786a5
# Alacritty
![screen shot 2017-04-24 at 8 52 16 am](https://cloud.githubusercontent.com/assets/177491/25338005/c59f3420-28cb-11e7-8ada-71e44b7c48ff.png)
# iterm2
![screen shot 2017-04-24 at 8 52 33 am](https://cloud.githubusercontent.com/assets/177491/25338011/cba0e030-28cb-11e7-989c-15da2bc2e79d.png)
# screenrc
```
hardstatus alwayslastline
hardstatus string '%{= Kd} %{= Kd}%-w%{= Kr}[%{= KW}%n %t%{= Kr}]%{= Kd}%+w %-= %{KG} %H%{KW}|%{KY}%101`%{KW}|%D %M %d %Y%{= Kc} %C%A%{-}'
maptimeout 0
defc1 off
```
# zshrc
```
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="avit"
plugins=(emoji)
source $ZSH/oh-my-zsh.sh
```

**Comment by jwilm** [comment]
Is this still a problem?

**Comment by chrisduerr** [comment]
Closing because no response after 10 months, if this still is an issue, it should be no problem to re-open it.
