### ISSUE TITLE
Rectangle selection

### ISSUE THREAD

**Issue by xorgy** [jwilm/alacritty#526]
Most terminals support rectangular region selection. In Terminal.app this is done by holding alt, and on most X11 terminals (mostly VTE) this is done by holding ctrl.

**Comment by chrisduerr** [comment]
Oh it seems like #978 is a duplicate of this request.

**Comment by shicks** [comment]
FWIW, I believe RXVT uses alt for rectangle selection.  Given that there's likely to be a fair number of people on either side, I'd like to see it configurable.  But I don't have a good hunch for quite where in the configuration it belongs, since it's not exactly a key binding, *per se*.

**Comment by chrisduerr** [comment]
I've already got a semi-working implementation of this. I'll probably wait until scrolling lands until I'm actually gonna work on changing selection though.
