### ISSUE TITLE
position of cursor and text screw up in emacs

### ISSUE THREAD

**Issue by travisfw** [jwilm/alacritty#529]
Easy to reproduce on my system, just open a new file in emacs ```emacs /tmp/tmp.sh```, and type ```if true```, enter for line feed, ```then``` and wait literally a second. Your screen should look like this now:

![screenshot from 2017-04-27 16-50-52](https://cloud.githubusercontent.com/assets/655987/25508922/10c2e3fc-2b6a-11e7-8b71-1770b15002fe.png)

I haven't figured out exactly how to reproduce it, but similar rendering issues happen when simply moving the cursor through text, making no edits at all.

I'm on Fedora 25 /wayland /Gnome Shell 3.22.3, and commit a99a69cfcb983b923cb89c6faf5ace3b89d786a5
My config: https://gist.github.com/travisfw/6b022c1ca6aaa1197e12d1dfe011ba84

**Comment by jwilm** [comment]
Able to repro; thanks for the report!

**Comment by travisfw** [comment]
Thank you! 👍
