### ISSUE TITLE
In i3 alacritty doesn't redraw when changing workspace

### ISSUE THREAD

**Issue by basile-henry** [jwilm/alacritty#53]
In i3 when switching workspace to the one with the alacritty window the window doesn't draw until it gets refreshed (by being selected by example)

Here it is working (alacritty on the left):
![working](https://cloud.githubusercontent.com/assets/3369034/21667917/d7894fa4-d2f4-11e6-834a-42d122586b51.png)

And not working (after a switch from an empty workspace to the current one):
![not-working](https://cloud.githubusercontent.com/assets/3369034/21667919/dc926148-d2f4-11e6-8800-83636e712240.png)

**Comment by jwilm** [comment]
That's not right! Would you mind applying the following patch and providing the output from Alacritty when you return to the workspace?

```diff
diff --git a/src/event.rs b/src/event.rs
index bfcb3f3..7ab557e 100644
--- a/src/event.rs
+++ b/src/event.rs
@@ -162,7 +162,7 @@ impl<N: Notify> Processor<N> {
             glutin::Event::Awakened => {
                 processor.ctx.terminal.dirty = true;
             },
-            _ => (),
+            _ => println!("Event={:?}", event),
         }
     }
```

In any case, thanks for the report!

**Comment by jwilm** [comment]
Alternatively, I've pushed a patch to master that probably fixes this.

**Comment by basile-henry** [comment]
I'll try that patch but it looks like it should work since the event that arrives is `Refresh`:
```
Event=Focused(false)
Event=Focused(false)
Event=Refresh
Event=Focused(false)
Event=Refresh
Event=Refresh
Event=Refresh
Event=Refresh
Event=Refresh
Event=Refresh
```

**Comment by jwilm** [comment]
That's good to hear! Even so, I'll wait for the result before closing this.

**Comment by basile-henry** [comment]
It works! 👍 

Great job by the way, this terminal looks very promising!

PS: I do have another issue completely unrelated but I'm not sure if I should open a new one since I think it's more to do with glutin than alacritty. The key for '#' and '~' on my UK layout keyboard doesn't work in alacritty (which is kind of an issue for a terminal). Do you want me to open a separate issue and edit this PS out?

**Comment by jwilm** [comment]
I'd appreciate you opening a new issue for that, but feel free to leave the P.S. so my comment makes sense :grin:.

**Comment by hazeled** [comment]
Just built from scratch and I have the same issue
