### ISSUE TITLE
build failing on macos

### ISSUE THREAD

**Issue by sodiumjoe** [jwilm/alacritty#537]
```bash
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.4 (16E195)
      Kernel Version: Darwin 16.5.0

$ cargo --version
cargo 0.18.0-dev (fe7b0cd 2017-04-24)

$ rustc --version
rustc 1.17.0

$ git remote -v
origin  https://github.com/jwilm/alacritty (fetch)
origin  https://github.com/jwilm/alacritty (push)

$ git pull
Already up-to-date.

$ rustup override set stable
info: using existing install for 'stable-x86_64-apple-darwin'
info: override toolchain for '/Users/jmoon/play/alacritty' set to 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.17.0 (56124baa9 2017-04-24)

$ rustup update stable
info: syncing channel updates for 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.17.0 (56124baa9 2017-04-24)

$ cargo build --release
   Compiling alacritty v0.1.0 (file:///Users/jmoon/play/alacritty)
error: proc-macro derive panicked
   --> src/ansi.rs:381:73
    |
381 | #[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
    |                                                                         ^^^^^^^^^^^
    |
    = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `alacritty`.

To learn more, run the command again with --verbose.
```

<details>
<pre><code>
cargo build --release --verbose
       Fresh semver v0.1.20
       Fresh linked-hash-map v0.3.0
       Fresh ffi-util v0.1.0 (file:///Users/jmoon/play/alacritty/ffi-util)
       Fresh cfg-if v0.1.0
       Fresh libc v0.2.18
       Fresh pkg-config v0.3.8
       Fresh bitflags v0.4.0
       Fresh rustc-serialize v0.3.22
       Fresh strsim v0.6.0
       Fresh fnv v1.0.5
       Fresh vec_map v0.6.0
       Fresh serde v0.9.8
       Fresh log v0.3.6
       Fresh fsevent-sys v0.1.5
       Fresh rand v0.3.15
       Fresh heapsize v0.3.8
       Fresh fsevent v0.2.15
       Fresh smallvec v0.1.8
       Fresh winapi v0.2.8
       Fresh quote v0.3.12
       Fresh parking_lot_core v0.2.0
       Fresh errno v0.1.8
       Fresh core-foundation-sys v0.2.3
       Fresh unicode-segmentation v1.0.1
       Fresh lazycell v0.4.0
       Fresh itoa v0.2.1
       Fresh serde v0.7.15
       Fresh core-foundation v0.2.3
       Fresh yaml-rust v0.3.5
       Fresh rustc_version v0.1.7
       Fresh lazy_static v0.2.2
       Fresh dtoa v0.3.0
       Fresh serde_yaml v0.6.1
       Fresh slab v0.3.0
       Fresh shared_library v0.1.5
       Fresh unicode-width v0.1.4
       Fresh filetime v0.1.10
       Fresh malloc_buf v0.0.6
       Fresh void v1.0.2
       Fresh num-traits v0.1.36
       Fresh objc v0.2.2
       Fresh block v0.1.6
       Fresh euclid v0.6.8
       Fresh objc_id v0.1.0
       Fresh num-complex v0.1.35
       Fresh nix v0.7.0
       Fresh serde_json v0.9.2
       Fresh objc-foundation v0.1.1
       Fresh ansi_term v0.9.0
       Fresh net2 v0.2.26
       Fresh utf8parse v0.1.0
       Fresh copypasta v0.0.1 (file:///Users/jmoon/play/alacritty/copypasta)
       Fresh winapi-build v0.1.1
       Fresh mio v0.6.2
       Fresh vte v0.3.0
       Fresh term_size v0.2.1
       Fresh khronos_api v1.0.0
       Fresh bitflags v0.7.0
       Fresh core-graphics v0.3.2
       Fresh owning_ref v0.2.4
       Fresh clap v2.20.0
       Fresh core-text v1.1.1
       Fresh parking_lot v0.3.6
       Fresh xml-rs v0.3.5
       Fresh font v0.1.0 (file:///Users/jmoon/play/alacritty/font)
       Fresh time v0.1.36
       Fresh unicode-xid v0.0.4
       Fresh gl_generator v0.5.2
       Fresh num-integer v0.1.32
       Fresh bitflags v0.3.3
       Fresh syn v0.11.4
       Fresh num-iter v0.1.32
       Fresh serde_codegen_internals v0.14.0
       Fresh num-bigint v0.1.35
       Fresh serde_derive v0.9.8
       Fresh num-rational v0.1.35
       Fresh cocoa v0.3.3
       Fresh num v0.1.36
       Fresh xdg v2.0.0
       Fresh kernel32-sys v0.2.2
       Fresh cgmath v0.7.0
       Fresh walkdir v0.1.8
       Fresh gleam v0.2.31
       Fresh notify v2.6.3
       Fresh cgl v0.1.5
       Fresh glutin v0.6.1 (https://github.com/jwilm/glutin?rev=cc64178d39a1fa06b2c5403117e5e0ef24deeac4#cc64178d)
   Compiling alacritty v0.1.0 (file:///Users/jmoon/play/alacritty)
     Running `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="err-println"' -C metadata=d49e65ee8acde8fa -C extra-filename=-d49e65ee8acde8fa --out-dir /Users/jmoon/play/alacritty/target/release/deps -L dependency=/Users/jmoon/play/alacritty/target/release/deps --extern notify=/Users/jmoon/play/alacritty/target/release/deps/libnotify-254fa238b4fb97b7.rlib --extern glutin=/Users/jmoon/play/alacritty/target/release/deps/libglutin-5f9089a313273330.rlib --extern lazy_static=/Users/jmoon/play/alacritty/target/release/deps/liblazy_static-3b2d015b4349e676.rlib --extern copypasta=/Users/jmoon/play/alacritty/target/release/deps/libcopypasta-c668851012aabc1e.rlib --extern mio=/Users/jmoon/play/alacritty/target/release/deps/libmio-878a6eff7e53a112.rlib --extern vte=/Users/jmoon/play/alacritty/target/release/deps/libvte-dcc5c4db56c47787.rlib --extern parking_lot=/Users/jmoon/play/alacritty/target/release/deps/libparking_lot-e18848dc5f4be263.rlib --extern cgmath=/Users/jmoon/play/alacritty/target/release/deps/libcgmath-7964b7acee178b01.rlib --extern serde_yaml=/Users/jmoon/play/alacritty/target/release/deps/libserde_yaml-0f0135443de6ae4a.rlib --extern serde=/Users/jmoon/play/alacritty/target/release/deps/libserde-9f43c5f76d4539b5.rlib --extern serde_derive=/Users/jmoon/play/alacritty/target/release/deps/libserde_derive-363230a9a44ba6e5.dylib --extern libc=/Users/jmoon/play/alacritty/target/release/deps/liblibc-8d751f39a7380bf8.rlib --extern unicode_width=/Users/jmoon/play/alacritty/target/release/deps/libunicode_width-fa365370873b727b.rlib --extern serde_json=/Users/jmoon/play/alacritty/target/release/deps/libserde_json-eea150fe898f260b.rlib --extern bitflags=/Users/jmoon/play/alacritty/target/release/deps/libbitflags-75fc9619122ee22e.rlib --extern errno=/Users/jmoon/play/alacritty/target/release/deps/liberrno-bd87a5b2fb49c6b0.rlib --extern fnv=/Users/jmoon/play/alacritty/target/release/deps/libfnv-557bfb60b466380f.rlib --extern log=/Users/jmoon/play/alacritty/target/release/deps/liblog-63006d84b4444419.rlib --extern xdg=/Users/jmoon/play/alacritty/target/release/deps/libxdg-7b6286b4c94e9a36.rlib --extern clap=/Users/jmoon/play/alacritty/target/release/deps/libclap-393e575a2885d525.rlib --extern font=/Users/jmoon/play/alacritty/target/release/deps/libfont-8cc2447b5812b713.rlib`
error: proc-macro derive panicked
   --> src/ansi.rs:381:73
    |
381 | #[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
    |                                                                         ^^^^^^^^^^^
    |
    = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg feature="default" --cfg feature="err-println" -C metadata=d49e65ee8acde8fa -C extra-filename=-d49e65ee8acde8fa --out-dir /Users/jmoon/play/alacritty/target/release/deps -L dependency=/Users/jmoon/play/alacritty/target/release/deps --extern notify=/Users/jmoon/play/alacritty/target/release/deps/libnotify-254fa238b4fb97b7.rlib --extern glutin=/Users/jmoon/play/alacritty/target/release/deps/libglutin-5f9089a313273330.rlib --extern lazy_static=/Users/jmoon/play/alacritty/target/release/deps/liblazy_static-3b2d015b4349e676.rlib --extern copypasta=/Users/jmoon/play/alacritty/target/release/deps/libcopypasta-c668851012aabc1e.rlib --extern mio=/Users/jmoon/play/alacritty/target/release/deps/libmio-878a6eff7e53a112.rlib --extern vte=/Users/jmoon/play/alacritty/target/release/deps/libvte-dcc5c4db56c47787.rlib --extern parking_lot=/Users/jmoon/play/alacritty/target/release/deps/libparking_lot-e18848dc5f4be263.rlib --extern cgmath=/Users/jmoon/play/alacritty/target/release/deps/libcgmath-7964b7acee178b01.rlib --extern serde_yaml=/Users/jmoon/play/alacritty/target/release/deps/libserde_yaml-0f0135443de6ae4a.rlib --extern serde=/Users/jmoon/play/alacritty/target/release/deps/libserde-9f43c5f76d4539b5.rlib --extern serde_derive=/Users/jmoon/play/alacritty/target/release/deps/libserde_derive-363230a9a44ba6e5.dylib --extern libc=/Users/jmoon/play/alacritty/target/release/deps/liblibc-8d751f39a7380bf8.rlib --extern unicode_width=/Users/jmoon/play/alacritty/target/release/deps/libunicode_width-fa365370873b727b.rlib --extern serde_json=/Users/jmoon/play/alacritty/target/release/deps/libserde_json-eea150fe898f260b.rlib --extern bitflags=/Users/jmoon/play/alacritty/target/release/deps/libbitflags-75fc9619122ee22e.rlib --extern errno=/Users/jmoon/play/alacritty/target/release/deps/liberrno-bd87a5b2fb49c6b0.rlib --extern fnv=/Users/jmoon/play/alacritty/target/release/deps/libfnv-557bfb60b466380f.rlib --extern log=/Users/jmoon/play/alacritty/target/release/deps/liblog-63006d84b4444419.rlib --extern xdg=/Users/jmoon/play/alacritty/target/release/deps/libxdg-7b6286b4c94e9a36.rlib --extern clap=/Users/jmoon/play/alacritty/target/release/deps/libclap-393e575a2885d525.rlib --extern font=/Users/jmoon/play/alacritty/target/release/deps/libfont-8cc2447b5812b713.rlib` (exit code: 101)
</code></pre>
</details>

**Comment by jwilm** [comment]
This is a known issue with the Rust compiler from Homebrew. Please try again using a Rust compiler from `rustup` or [rust-lang.org](https://www.rust-lang.org).
