### ISSUE TITLE
Cursor disappears when going to the beggining of the line 

### ISSUE THREAD

**Issue by paupalou** [jwilm/alacritty#538]
Hello, alacritty is lovely, but i found annoying bug? with cursor movement. It disappears when user go to start of line, and it reappears if you go to end of line again.

This video shows it: https://asciinema.org/a/edvwg4ti2p5f4sxiqbx6gu3j6

environment : shell -> zsh

keys pressed:
bindkey '^A' beginning-of-line (CTRL-A)
bindkey '^E' end-of-line (CTRL-E)
 
Thanks for this great software

**Comment by maximbaz** [comment]
Interesting, to clarify what I understood from the video, after you jump with `Ctrl+A` the cursor is still there, the cursor becomes invisible only while you are typing the text, and reappears when you stopped typing something.

I couldn't repro it by the way.

**Comment by paupalou** [comment]
Hello @maximbaz , sorry if my instructions werent clear. I discovered some things:

- In bash i couldnt reproduce , works as expected, seems is something about zsh.
- Its not only about 'beggining-of-the-line' , if you move with your arrow keys to left the cursor disappears.
- Is related about zsh-completion, i have a module that colorize the command you typing in red if is not executable/findable in path , example "foobar", or green if is a correct command , ex : "ls -lha"/. If i disable this completion module all works correctly.
- In other terminals like urxvt or st this behaviour just does not happen.
- I have been able to fix it setting custom_cursor_colors to true and "playing" with cursor colors.

Anyways, seems is not alacritty related, otherwise is about my setup.

Thanks , you can close this

**Comment by suweller** [comment]
Leaving this here for anyone else encountering this issue. For me, it was triggered because I enabled `cursor` in: [`zsh-users/zsh-syntax-highlighting`](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md#how-to-activate-highlighters).
> ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern **cursor**)

By default it only contains `main`. When you disable `cursor` again you can prevent the bug from occurring.
