### ISSUE TITLE
Crash on mouseover when using padding_x

### ISSUE THREAD

**Issue by brool** [jwilm/alacritty#544]
*Steps to reproduce*:

1. Run the app (I'm using Ubuntu 16.04 -- suspect it will happen in many more configurations).
2. Move mouse over past the edge

App crashes.

*Possible cause*:

See commit 9316771f64842533181cfb04a27aa9ae809cc435.

        let col = Column((x - self.padding_x as usize) / (self.cell_width as usize));
        let line = Line((y - self.padding_y as usize) / (self.cell_height as usize));

if `self.padding_x` >  `x` then an error `attempt to subtract with overflow` will be raised.

Should `contains_point` be using && instead of || on the check? 

n.b. I know nothing about Rust, so apologies if the cause is not correct.

**Comment by jwilm** [comment]
Oops, I totally broke that while refactoring. Thanks for the report! Should be fixed on master.
