### ISSUE TITLE
Issues displaying at least some UTF-8 characters.

### ISSUE THREAD

**Issue by mscharley** [jwilm/alacritty#553]
Terminal (OSX):

<img width="1082" alt="screen shot 2017-05-09 at 8 54 18 pm" src="https://cloud.githubusercontent.com/assets/336509/25847479/b7344468-34f9-11e7-8d6c-b18453aafbd5.png">

Alacritty:

<img width="1014" alt="screen shot 2017-05-09 at 8 54 26 pm" src="https://cloud.githubusercontent.com/assets/336509/25847488/be704e16-34f9-11e7-9175-3262c676660a.png">

You'll notice that the Japanese text is conspicuously missing in the output in Alacritty. Otherwise, the text is laid out correctly. Both terminals are using the same base font (Monaco).

**Comment by jwilm** [comment]
Hey @mscharley,

Thanks for the report! We've still got a TODO for implementing fallback fonts on macOS. Please subscribe to #45 updates.
