### ISSUE TITLE
Performance issues on macos

### ISSUE THREAD

**Issue by rahenri** [jwilm/alacritty#555]
I tried alacritty a few months ago and tried again today. But both times the terminal performance was way bellow iterm2.

I just cloned from commit 5c6b7dd244e309067141a206c2e2518580068d9e and the config is copied from the one in the repo but replacing font with Menlo.

It was particularly slow switching panes in tmux, it takes a full second for all lines in the screen to be updated. Scrolling in vim is not very fast either and half of the screen flashes on page down.

Other opengl applications are working just fine, I have a pre touch bar 15in macbook, I also have an external monitor attached to it.

**Comment by jwilm** [comment]
How are you building Alacritty?

**Comment by rahenri** [comment]
I followed the instructions in the README, namely:

```
$ rustup override set stable
$ rustup update stable
$ cargo build --release
```

My rustc version is `rustc 1.17.0 (56124baa9 2017-04-24)`

**Comment by falood** [comment]
@rahenri how you switch panes in tmux? I also use tmux in alacritty, and it works well for me.

**Comment by jwilm** [comment]
I learned recently that some [macOS-specific perf issues were resolved in _tmux_](https://github.com/tmux/tmux/issues/849) as of version 2.5. You may want to check that out as well.

**Comment by rahenri** [comment]
My bad, I actually meant windows, not panes, I have this in my tmux config:

```
bind -n M-left previous-window
bind -n M-right next-window
```

So alt arrows switch windows.

@jwilm Sounds promising, although I didn't have the same problem in other terminals, I will have to wait till Monday to try that, thanks!

**Comment by rahenri** [comment]
I just tried again, and the terminal was blazingly fast for all the apps I tried. Thanks!

**Comment by jwilm** [comment]
I just landed a patch earlier today that *significantly* improves performance on macOS when running with a very large character grid (typical when full-screen on external monitor). Would love to see how that affects your usage.

Can this be closed?

**Comment by rahenri** [comment]
Performance is excellent now as far as can tell, even fullscreen on external monitor.

Feel free to close it.

**Comment by jwilm** [comment]
Thanks @rahenri!
