### ISSUE TITLE
Spastic Font Spacing

### ISSUE THREAD

**Issue by ibrokemypie** [jwilm/alacritty#561]
![image](https://cloud.githubusercontent.com/assets/7827846/25946834/1ab2c112-3690-11e7-9862-c1de46e977eb.png)
This is with completely default settings, on arch linux from the AUR package...

**Comment by lord-re** [comment]
You should try configuring the offset in .config/alacritty.yml

**Comment by ibrokemypie** [comment]
which one and why is it screwed by default?

**Comment by rafi** [comment]
Are you sure you've entered the font name correctly?

**Comment by ibrokemypie** [comment]
@rafi I have not touched the config in that screenshot, however setting the font to "monofur for Powerline" does change font correctly, however the spacing issue stays.

**Comment by maximbaz** [comment]
The default font is set to `monospace`, I think some fonts are doing this weird spacing and in your case `monospace` resolves to a such weird font. In my case, the default looks all right.

Try starting alacritty from another terminal, you will see which font alacritty is going to use.

For example, my case:

- I have the fonts set to `monospace` in alacritty.yml:

    ```
    ❯  alacritty                                                                                                                                                         

    got font path="/usr/share/fonts/TTF/LiberationMono-Regular.ttf"
    got font path="/usr/share/fonts/TTF/LiberationMono-Bold.ttf"
    got font path="/usr/share/fonts/TTF/LiberationMono-Italic.ttf"
    ```

    And the spacing looks all right.


- I have the fonts set to `monospace222222` in alacritty.yml:

    ```
    ❯  alacritty                                                                                                                                                         

    got font path="/usr/share/fonts/TTF/DejaVuSans.ttf"
    got font path="/usr/share/fonts/TTF/DejaVuSans-Bold.ttf"
    got font path="/usr/share/fonts/TTF/DejaVuSans.ttf"
    ```

    And the spacing looks like on your screenshots.

The best solution for your specific case is to simply define the font to use, and optionally adjust it with `offset` and `glyph_offset`. I would recommend trying some more fonts, maybe some not Powerline-enchances ones, in case the font was screwed while it was modified to include Powerline symbols (but again, you probably can fix it too with `offset` if you want).

I don't think it makes sense to adjust the default though.

**Comment by ibrokemypie** [comment]
i changed some font related variables elsewhere which solved it, thanks

**Comment by ibrokemypie** [comment]
reopening, recently installed void linux and having the same problem, though now its a bit different...
http://imgur.com/a/WEWLI

**Comment by maximbaz** [comment]
Try to play with the `offset` configuration:

```
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0.0
    y: 0.0
```

**Comment by AdrianoFerrari** [comment]
For anyone stumbling on this, this issue shows a fix that worked for me:
https://github.com/alacritty/alacritty/issues/1881

(issue was setting the font name to, e.g., "Fira Mono Regular" when it should have been just "Fira Code")

**Comment by papudebeloper** [comment]
i'm having a weird issue with font spacing too, here it is:
https://imgur.com/7nSdwSL.png

**Comment by FivelFox** [comment]
I'm having the same problem as Beloper. I cannot figure out for the life of me what to do
