### ISSUE TITLE
Missing Prompt Character

### ISSUE THREAD

**Issue by 8-uh** [jwilm/alacritty#564]
<img width="330" alt="screen shot 2017-05-12 at 17 27 46" src="https://cloud.githubusercontent.com/assets/3170885/26019073/6c117848-3738-11e7-81bb-4bd00450dd21.png">

Such a knitpicky thing, but I wanted to be part of history, so I thought I'd complain about someone else's hard work on the internet.

Already just a fantastic piece of software... Thank you <3

**Comment by jwilm** [comment]
Thanks for the report! 

This is due to the lack of font fallback on macOS. Will get to implementing it at some point.. hopefully sooner than later :smile:

Please follow #45 for updates.
