### ISSUE TITLE
intel gpu support

### ISSUE THREAD

**Issue by OliverLeitner** [jwilm/alacritty#567]
is there any plans for supporting intel gpu's at this point?

it lets me compile it on my laptop with intellinux driver, but it doesnt run, missing ES, no support for GSLS 3.x...

`drm:intel_pipe_update_end [i915]] *ERROR* Atomic update failure on pipe A (start=9620131 end=9620132) time 618 us, min 763, max 767, scanline start 760, end 9`

**Comment by maximbaz** [comment]
FYI the alacritty compiles and runs fine on my laptop with Intel HD Graphics 4400, so you probably should a be a bit more specific about your GPU.

**Comment by OliverLeitner** [comment]
oh, thanks for the info, if it helps, heres some better info on the "card":

```
00:00.0 Host bridge [0600]: Intel Corporation Mobile GME965/GLE960 Memory Controller Hub [8086:2a10] (rev 0c)
00:02.0 VGA compatible controller [0300]: Intel Corporation Mobile GME965/GLE960 Integrated Graphics Controller [8086:2a12] (rev 0c)
00:02.1 Display controller [0380]: Intel Corporation Mobile GME965/GLE960 Integrated Graphics Controller [8086:2a13] (rev 0c)
```

the xorg driver im using is the intel "proprietary" one...

https://01.org/linuxgraphics/downloads

the kernel is a intel-drm development build from ubuntu:
http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-next/

`Linux lappy 4.11.0-997-lowlatency #201704182244 SMP PREEMPT Wed Apr 19 02:49:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

the modules loaded:

```
i915                 1515520  3
i2c_algo_bit           16384  1 i915
drm_kms_helper        163840  1 i915
drm                   356352  5 i915,drm_kms_helper
video                  40960  1 i915
```
intel_gpu_top shows its being utilized

the xorg device section:

```
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
Option      "AccelMethod" "sna"
Option      "TearFree" "true"
Option      "SwapbuffersWait" "true"
Option      "VSync" "true"
Option      "DRI" "true"
VideoRam        461632   # sometimes (before i updated the bios, it were useful)
EndSection
```

the laptop is a compaq 610 (compaq branded hp laptop...)

**Comment by OliverLeitner** [comment]
ok, i think i found a way "around" the problem...
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
installed that, rebooted, did the stuff explained on that ppa page
after that, alacritty started working.

**Comment by jwilm** [comment]
Is there anything we should do in Alacritty to address this? Sounds like you resolved it with system config.

**Comment by refacto** [comment]
I'm experiencing this error upon launching alacritty:
```
There was an error initializing the shaders: failed compiling shader: 0:14(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
```
I believe this is because of Intel support, but I'm not sure. I'm using Mesa 17.2.0, with an Intel GM45 Express chipset.
I've included output of 'glxinfo' and would like to include other useful information on request.

[glxinfo.txt](https://github.com/jwilm/alacritty/files/1254446/glxinfo.txt)

This issue happens on X.org and Wayland for me.

**Comment by auscompgeek** [comment]
@refacto that's covered by #128

**Comment by zachliu** [comment]
I was able to compile and run Alacritty on both `Intel® HD Graphics 630` and `Intel® UHD Graphics 620`.
However, it's unuseablely slow. For example, if I type ```$ cd ..```, that ```d``` won't show up until i typed the last dot. Very much unresponsive from time to time.

**Comment by OliverLeitner** [comment]
yeah, it does not seem to use the gpu at all, this is more a "software render" mode of some sort at this stage...

ill have to rety alacritty, i gave up a while ago, seeing the gpu hogging up after a few weeks of keeping the term open.

**Comment by zachliu** [comment]
The latest alacritty is great. I can do `decorations: false` without any problem!

```shell
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Mint 19 tara
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 4.15.0-29-generic
 MMd      /++                -sNMd:    Uptime:
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages:
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: zsh 5.4.2
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution:
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 3.8.8
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme:
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme:
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme:
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Noto Sans 9
      -dMNs-``-::::-------.``    dMM   CPU: Intel Core i7-8650U @ 8x 4.2GHz [-273.2°C]
       `/dMNmy+/:-------------:/yMMM   GPU: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)
          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM: 4948MiB / 15913MiB
             \.MMMMMMMMMMMMMMMMMMM
```

**Comment by chrisduerr** [comment]
Based on the report by zachliu this issue seems to be resolved in the latest Alacritty. For issues with unsupported OpenGL versions, please see #128.
