### ISSUE TITLE
"6c" Appear at prompt end (unexcepted input) on Arch Linux

### ISSUE THREAD

**Issue by NeoChen1024** [jwilm/alacritty#569]
The problem is like this: http://imgur.com/a/3aAsY

Arch Linux 
Kernel 4.10.13-1-ARCH
community/rust 1:1.17.0-1
local/alacritty-git 0.1.0.503.g3224847-1
extra/freetype2 2.7.1-2
extra/fontconfig 2.12.1-4
extra/xclip 0.13-1

CPU: Intel i5-4210Y
Intel Xorg Driver

**Comment by miedzinski** [comment]
Please try alacritty from `master`. Similar bug was fixed few days ago in 08447a220c1bcf9d2e071798da3e1edcde9366cf.

Telling alacritty to be more verbose (`-vvv`) is helpful too.

**Comment by NeoChen1024** [comment]
with community/rust 1:1.17.0-1
and local/alacritty-git 0.1.0.503.g3224847-1 (from aur)
my compiled package https://drive.google.com/file/d/0BzPw4mezYnH5aG1hTXRacWlMSnM/view?usp=sharing

**Comment by NeoChen1024** [comment]
logs https://drive.google.com/open?id=0BzPw4mezYnH5UkNBdkV3M0xyVlk

**Comment by jwilm** [comment]
Is this still a problem on latest master?

**Comment by NeoChen1024** [comment]
No

2017-06-27 5:41 GMT+08:00 Joe Wilm <notifications@github.com>:

**Comment by jwilm** [comment]
Thanks!
