### ISSUE TITLE
Running from master fails

### ISSUE THREAD

**Issue by WhyNotHugo** [jwilm/alacritty#570]
I'm getting

    Error creating glutin::Window; GL context creation failed

I'd guess that all required OpenGL-related deps are installed, since I frequently run lots of games on this host.

**Comment by Raindeer44** [comment]
I'm getting the same problem. I'm on Linux Mint 18.1, using kernel 4.10.0-14-generic. I'm using I3 window manager. I just updated Alacritty from master yesterday.

**Comment by jwilm** [comment]
Please post the output of `glxinfo | grep OpenGL`

**Comment by zacps** [comment]
I got this error after updating nvidia drivers before rebooting on Arch. Specifically after the `nvidia (384.69-2 -> 387.12-1)` update.

I tried running glxinfo but it exited with an error that talked about the failing major/minor opcodes.

Next time there's an update is there any other information that would be useful?

**Comment by Raindeer44** [comment]
Sorry, I missed the notification for the comment asking for OpenGL info. The problem has disappeared for me now, but I haven't changed or updated my drivers. `glxinfo | grep OpenGL` gives me:

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 755M/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 375.66
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 375.66
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 375.66
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by sergekir** [comment]
Same error after updating nvidia drivers (on Ubuntu 16.04) and same solution: reboot. But also I've done full rebuild of alacritty before the reboot. No issues now.

**Comment by sodiumjoe** [comment]
can probably close this?

**Comment by zacps** [comment]
This is still an issue after an update before rebooting. It's not critical but if it was possible to fix it it'd be good.
