### ISSUE TITLE
Neovim's FocusGained event is not fired in Alacritty

### ISSUE THREAD

**Issue by maximbaz** [jwilm/alacritty#572]
I have a very neat autocommand in my nvim's config:

```
autocmd BufEnter,FocusGained * checktime
```

Thanks to it, if I have two terminals side by side and I happen to have the same file opened in neovim in both terminals, after changing something in one terminal, saving the file and moving focus to the other terminal, the file gets automatically refreshed.

I'll try to explain with the gif below:

- I open neovim with no custom config in two terminals (not alacritty)
- On the right side I add this autocommand to monitor focus change and reload the file
- I modify the file on the left (delete a line), save it and move focus to the right
- And immediately the line is also deleted on the right side.

![alacritty](https://cloud.githubusercontent.com/assets/1177900/26037709/6a42a696-38f9-11e7-84bf-f110713db6d8.gif)

However, this does not work in Alacritty, the file on the right is not getting refreshed.

I can only guess that perhaps some kind of `focused` event is not being fired and/or propagated to neovim.

**Comment by tinchoz49** [comment]
Hi @maximbaz how are you? 

I don't know if this is a bug or not but, for your problem you can use: `au CursorHold,CursorHoldI * checktime` in your vimrc. It works with alacritty and solved your problem, I think.

**Comment by maximbaz** [comment]
Hey, thanks, that's a working workaround, but CursorHold will be triggered _much more often_ than FocusGained, I wouldn't recommend sticking to it forever as it might increase CPU usage and even drain your laptop battery a bit quicker. 

FocusGained is nice because while you are inside vim it is not being triggered, it is really triggered only when you come back to vim. We should really see FocusGained fixed in alacritty.

To check for yourself, try this, set `:au CursorHold,CursorHoldI * echomsg "CursorHold triggered"` and work for 5 minutes in vim without leaving it, and then check `:messages`, you will see tons of messages there.

**Comment by tinchoz49** [comment]
uhhh I didn't know that :smile:

**Comment by tinchoz49** [comment]
Hi @maximbaz me again :smile: ! Are you using tmux with your vim? In that case, if you add: `set -g focus-events on` to your tmux conf alacritty works without problem.

**Comment by maximbaz** [comment]
Hey! So it works for you?

I've tried right now both with and without tmux, and alacritty doesn't raise this FocusGained event in either case, while at the same time sakura terminal raises it in both cases, with and without tmux.

I have tmux and alacritty built from the most recent sources, and I already have the `focus-events` enabled in tmux as you suggested.

**Comment by maximbaz** [comment]
Judging from [neovim's code](https://github.com/neovim/neovim/blob/master/src/nvim/tui/input.c#L281-L285) it expects terminal to send some specific sequence codes that indicate that the focus has been gained or lost, and then neovim catches that and converts to FocusGaines and others.

Looks like alacritty is not sending these sequence codes.

**Comment by jwilm** [comment]
We haven't implemented this yet.

http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-FocusIn_FocusOut

**Comment by tinchoz49** [comment]
this is embarrassing :confused:...It wasn't alacritty, I tested with urxvt.
