### ISSUE TITLE
Fontsize hotkey

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#574]
Perhaps this is better handled with Vim/Neovim or Tmux, but I figured I would try here first. Is there a way to map the font size to hotkeys? Namely `+` and `-`. Thanks!

**Comment by jwilm** [comment]
Yep, have plans for this. Please subscribe to #446 for updates.

**Comment by algesten** [comment]
or #121

**Comment by jwilm** [comment]
Oh yeah, #121 is the right place. Thanks for the correction.
