### ISSUE TITLE
Warn on close

### ISSUE THREAD

**Issue by placeybordeaux** [jwilm/alacritty#577]
Just accidentally closed out an alacritty terminal with some unsaved work in it. It'd be nice to have the warn on close option available.

**Comment by maximbaz** [comment]
Use tmux, with it only explicit `$ exit` or <kbd>Ctrl+D</kbd> will actually close the session, and accidental terminal close will do no harm - you will always be able to open a new terminal and reconnect to the previous session.

**Comment by jwilm** [comment]
Thanks for the request! However, this isn't something I intend to address, at least not as requested. In the future, we may support transparently using tmux for session persistence.
