### ISSUE TITLE
XCompose input not detected as utf-8.

### ISSUE THREAD

**Issue by Karl-D-Asmussen** [jwilm/alacritty#583]
OS distro: Xubuntu 16.04  
Compiled with: rustc 1.17.0  
Applications affected: zsh, neovim

In using XCompose, when I try to use a compose sequence to input unicode characters like “SUBSCRIPT ONE U+2081 `₁`” instead the terminal receives the three component bytes; interprets them as ASCII-charset characters; and translates them to unicode once more yielding the sequence U+00E2 U+0082 U+0081 which results in mojibake.

**Comment by algesten** [comment]
Aside from not hanging, this is the same compose key problem as in #209 and #411

**Comment by Karl-D-Asmussen** [comment]
@algesten XCompose is a distinct mechanism from dead keys.

When entering `₁` I press `<Multi_key> <1> <space>` — none of which appear in any way in terminal.

The output of `xev` when I perform the relevant action is:

```
KeyPress event, serial 37, synthetic NO, window 0x4400001,
    root 0x2c9, subw 0x0, time 47795708, (-191,24), root:(680,499),
    state 0x10, keycode 94 (keysym 0xff20, Multi_key), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: True

KeyRelease event, serial 37, synthetic NO, window 0x4400001,
    root 0x2c9, subw 0x0, time 47795793, (-191,24), root:(680,499),
    state 0x10, keycode 94 (keysym 0xff20, Multi_key), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x4400001,
    root 0x2c9, subw 0x0, time 47796032, (-191,24), root:(680,499),
    state 0x10, keycode 10 (keysym 0x31, 1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XmbLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: True

KeyRelease event, serial 37, synthetic NO, window 0x4400001,
    root 0x2c9, subw 0x0, time 47796096, (-191,24), root:(680,499),
    state 0x10, keycode 10 (keysym 0x31, 1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x4400001,
    root 0x2c9, subw 0x0, time 47796299, (-191,24), root:(680,499),
    state 0x10, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XmbLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: True

KeyPress event, serial 37, synthetic NO, window 0x4400001,
    root 0x2c9, subw 0x0, time 47796299, (-191,24), root:(680,499),
    state 0x10, keycode 0 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 3 bytes: (e2 82 81) "₁"
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x4400001,
    root 0x2c9, subw 0x0, time 47796349, (-191,24), root:(680,499),
    state 0x10, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False
```

I cannot repliably detect whether it is the same issue as the dead key issues — although I have access to a Danish keyboard and keyboard layout, the dead keys do not function.

**Comment by algesten** [comment]
Ok. Maybe I'm not familiar with "dead keys". I have a swedish keyboard (hej hej!), and I use two keypresses to make `ü` (which is first `¨` followed by `u`).

* https://en.wikipedia.org/wiki/Dead_key
* https://en.wikipedia.org/wiki/Compose_key

There is a difference between dead key and compose key, but I suspect from the terminal's perspective we will solve both if we solve one. I.e. it's a bunch of "pre-keys" that together generate something else. I'm happy to be prove wrong on that :)

**Comment by algesten** [comment]
And of course there is a difference in utf-8 of composed and decomposed form.

**Comment by jonhoo** [comment]
Isn't this the same as   #148?
