### ISSUE TITLE
Unspecific error messages

### ISSUE THREAD

**Issue by db48x** [jwilm/alacritty#587]
I just upgraded alacritty, and merged the new config file into my existing one. I'm getting this error message:

    problem with config: Custom("Invalid value: invalid value for Action")

I'm presuming that this has something to do with a keybinding (not that I've modified any of them), but it's not very clear, and it doesn't specify even so much as a line number. There are so many ways to improve this that I don't feel that I need to list them all.

**Comment by jwilm** [comment]
Are you sure you're running with the latest master? We changed the error printing at some point, and it looks like this message is from the old format.

**Comment by db48x** [comment]
git says:

    commit 112abf385fef32f30618b4ebb1d1c651661a6fae
    Author: Joe Wilm <joe@jwilm.com>
    Date:   Wed May 24 09:50:49 2017 -0700

which looks relatively recent.

I'll check more carefully when I get back home; perhaps it's still running the old binary.

**Comment by chrisduerr** [comment]
I believe this should be fixed. Errors in the keyboard shortcuts should be more descriptive on the latest master.
