### ISSUE TITLE
Unable to build alacritty after #593

### ISSUE THREAD

**Issue by DarkDefender** [jwilm/alacritty#595]
After #593 had been merged, I am unable to build alacritty without errors. I get the following error message:

```
error: struct field shorthands are unstable (see issue #37340)
   --> src/renderer/mod.rs:188:43
    |
188 |                 font::Style::Description {slant, weight}
    |                                           ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> src/renderer/mod.rs:188:50
    |
188 |                 font::Style::Description {slant, weight}
    |                                                  ^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `alacritty`.
```

OS: Gentoo linux
Rust version: 1.16.0

**Comment by jwilm** [comment]
Oh, shoot. You can upgrade your Rust compiler to work around this.

@algesten can we remove the named field shorthand usage?

**Comment by DarkDefender** [comment]
@jwilm Sadly 1.16.0 is the latest one available in the official gentoo package repo.

I suppose I could bump it up myself to 1.17.0. If you want alacritty to depend on newer rust versions, that is.

**Comment by algesten** [comment]
I fix imminently.

**Comment by algesten** [comment]
So #596 should address this.

**Comment by DarkDefender** [comment]
@algesten Yes, that has fixed it for me atleast! Thanks! :)

**Comment by DarkDefender** [comment]
I'll close this because the fix is now in master.
