### ISSUE TITLE
Problem with mouse selection with alacritty + tmux

### ISSUE THREAD

**Issue by michelboaventura** [jwilm/alacritty#599]
Using xterm and tmux if I want to copy a text I can't just select it with the mouse, since this will trigger a tmux selection, which doesn't copy to clipboard. So, instead, I just hold shift, which seems to bypass tmux and use xterm copy.

On alacritty holding shift does nothing and I can't easily copy a text within tmux, so I end up having to open vim, paste with tmux and copying it from there with :"+y.

Is there a way to do this on alacritty? If not, I would like to implement it, if you can give me a starting point :)

**Comment by maximbaz** [comment]
See if it is a duplicate of #146, maybe join the discussion there.

**Comment by michelboaventura** [comment]
You are right @maximbaz, I'm close this one since is the same issue. Thanks!
