### ISSUE TITLE
ZSH autosuggestions hidden when using Dracula theme from wiki

### ISSUE THREAD

**Issue by wooken** [jwilm/alacritty#604]
ZSH auto-suggestions do not show properly when using the Dracula theme provided in the wiki.

### Dracula theme from wiki

![dracula_suggest_not_work](https://user-images.githubusercontent.com/5219476/26965436-96b900de-4caa-11e7-9bb3-a90c7d581a02.png)

### Dracula theme alternative -- [source](https://www.ur-ban.com/2017/01/07/alacritty-dracula-theme/)

![dracula_suggest_works](https://user-images.githubusercontent.com/5219476/26965467-b2740c92-4caa-11e7-8522-54b402ced77e.png)

### Diff of wiki version vs alternative version

```diff
@@ -11,18 +11,18 @@ colors:
     red:     '0xff5555'
     green:   '0x50fa7b'
     yellow:  '0xf1fa8c'
-    blue:    '0xcaa9fa'
+    blue:    '0xbd93f9'
     magenta: '0xff79c6'
     cyan:    '0x8be9fd'
-    white:   '0xbfbfbf'
+    white:   '0xbbbbbb'
   # Bright colors
   bright:
-    black:   '0x282a35'
-    red:     '0xff6e67'
-    green:   '0x5af78e'
-    yellow:  '0xf4f99d'
+    black:   '0x555555'
+    red:     '0xff5555'
+    green:   '0x50fa7b'
+    yellow:  '0xf1fa8c'
     blue:    '0xcaa9fa'
-    magenta: '0xff92d0'
-    cyan:    '0x9aedfe'
-    white:   '0xe6e6e6'
+    magenta: '0xff79c6'
+    cyan:    '0x8be9fd'
+    white:   '0xffffff'
```

**Comment by jwilm** [comment]
Have you compared either values with the theme spec? You're welcome to update the wiki for correctness.
