### ISSUE TITLE
Add support for user-provided font fallbacks

### ISSUE THREAD

**Issue by sodiumjoe** [jwilm/alacritty#606]
tracking issue for work that was backed out of #575

**Comment by algesten** [comment]
I have a provisional fix for this, where we base the fallbacks always on Menlo regardless of the user configured font.

The only issue, and maybe it isn't an issue, is when the user configures some like "Source Code Pro Light" as the normal font, the weight doesn't match in the fallback.

So if say, a Japanese character would still be the normal weight, even if the Japanese font has a light.

**Comment by algesten** [comment]
PR #610 was intended to remedy this, but that was before @jwilm changed the title :)

**Comment by Determinant** [comment]
Looks like the list of fonts in `.yml` file is not supported still. Is this WIP? I see PR #610 was required to be changed a month ago. I'm glad to help if needed.

**Comment by sodiumjoe** [comment]
closing in favor of #957
