### ISSUE TITLE
[Ranger] Bright colors do not get transferred correctly to bg color

### ISSUE THREAD

**Issue by DarkDefender** [jwilm/alacritty#611]
![ranger](https://user-images.githubusercontent.com/312503/27095152-fdadcb06-506c-11e7-9460-d11924b360f2.png)

Urxvt top, alacritty bottom.

When using ranger with alacritty I noticed that the colors do not match with the ones I get with urxvt. It seems like ranger uses the current color of the file type to draw the background. However in alacritty it doesn't seem to take into account that the bold text changed the color and instead uses the non bright color to draw the bg strip.

**Comment by jwilm** [comment]
There's a config option to draw bold text with bright colors. Please make sure you've got that enabled and that your bright colors are configured differently than normal colors.

**Comment by DarkDefender** [comment]
If you mean `draw_bold_text_with_bright_colors: true` then I have that activated, yes.

As you can see in the screenshot, the bold text has a different color than the bg color with alacritty.
Here is my color settings:
```
# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '0x1b1d1e'
    foreground: '0xf8f8f2'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xb60050'
    green:   '0x88bb22'
    yellow:  '0xc47f2c'
    blue:    '0x30309b'
    magenta: '0x7e49a5'
    cyan:    '0x4699af'
    white:   '0x9999aa'

  # Bright colors
  bright:
    black:   '0x7e8e91'
    red:     '0xf92672'
    green:   '0x80ff00'
    yellow:  '0xffba68'
    blue:    '0x7070f0'
    magenta: '0xbb88dd'
    cyan:    '0x66d9ef'
    white:   '0xf8f8f2'

```

**Comment by jwilm** [comment]
Oh, sorry. I misunderstood. Sounds like a bug.

**Comment by DarkDefender** [comment]
@jwilm It seems like the problem is the "invert" color terminal code:
```
echo -e "\e[32mNormal \e[7mInverted\e[27m \e[1mBold \e[7mInverted Bold\e[27m"
```

Paste that into your terminal any you will see that the inverted bold is not correctly handled. I did take a look at where the bright color computation happens and I think that it happens too late in the pipeline to be able to handle this.

Because as it is now, the fg and bg colors are split of long before the bright check happens. So it is impossible to know if the bg color should be bright or not.

**Comment by AmaiKinono** [comment]
Don't know if it's the same problem, but it looks like the above screenshot when `TERM=alacritty-direct`:

![2019-12-14-024616_1000x750_scrot](https://user-images.githubusercontent.com/28714352/70824138-848d6d00-1e1c-11ea-87c4-8ce893bbebd6.png)

When `TERM=alacritty`, the colors are right:

![2019-12-14-024659_1000x750_scrot](https://user-images.githubusercontent.com/28714352/70824178-9a029700-1e1c-11ea-9642-03b6e961e1de.png)

So maybe this is not fixed for true color mode?
