### ISSUE TITLE
In some terminal programs, bg color changes do not get applied to the whole line

### ISSUE THREAD

**Issue by DarkDefender** [jwilm/alacritty#612]
In mocp and mutt, I've notived that alacritty does not render bg color changes correctly.
Take this example from mocp (urxvt top, alacritty bottom):
![mocp](https://user-images.githubusercontent.com/312503/27095567-786bcfc2-506e-11e7-948f-742fa1a6653f.png)

**Comment by jwilm** [comment]
How recent is your build? This may be related to _back color erase_ which we didn't always support.

**Comment by DarkDefender** [comment]
My build is very recent, I built it today before testing.

**Comment by DarkDefender** [comment]
@jwilm I Found the terminal code that is not handled correctly:
```
echo -e "\e(B\e[38;5;7m\e[48;5;4m../\e[40X"
```

It seems like alacritty does not handle bg change with padding `\e[40X`. With the other terminal I've tested, the bg color change correctly extends 40 chars. But with alacritty it stops when the actual text stops.

**Comment by DarkDefender** [comment]
Seems to be fixed now. Thank you so much @jwilm and @Aaron1011 !
