### ISSUE TITLE
Newly built release binary segfaults on FreeBSD 12 current

### ISSUE THREAD

**Issue by svmhdvn** [jwilm/alacritty#618]
output on running `target/release/alacritty`: `terminated by signal SIGSEGV (Address boundary error)`

my rustc version: `rustc 1.18.0 (03fc9d622 2017-06-06)`

**Comment by Aaron1011** [comment]
@sivamahadevan: Can you run compile alacritty in debug mode (e.g. a plain `cargo build`), and paste the backtrace from running it with `gdb`?

**Comment by sivamahadevan** [comment]
Something seems to be wrong with the backtrace, I don't know if I'm doing this correctly, but this is the output:

```
siva@siva-freebsd ~/alacritty> gdb --args target/debug/alacritty
GNU gdb (GDB) 7.12.1 [GDB v7.12.1 for FreeBSD]
...
This GDB was configured as "x86_64-portbld-freebsd12.0".
...
Reading symbols from target/debug/alacritty...done.
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /usr/home/siva/alacritty/target/debug/alacritty.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) r
Starting program: /usr/home/siva/alacritty/target/debug/alacritty

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb)
```

**Comment by lukaslueg** [comment]
This is caused by `std::fs::metadata()`, used internally via `xdg` for `config::Config::installed_config()`. For some reason, this function reliably crashes on FreeBSD 12 with rustc 1.18 and nightly. The most simple program to cause a segfault is something like

```rust
use std::fs;
fn main() {
    println!("{:?}", fs::metadata("Cargo.toml"));
}
```
Could be an issue with FreeBSD itself, as `fs::metadata()` basically boils down to a simple `stat`, which should not cause native rust code any trouble.

**Comment by myfreeweb** [comment]
So, tl;dr on how to build for -CURRENT right now:

1. Install nightly rust with rustup
2. Patch nightly rust with https://github.com/johalun/rust-ino64
3. Append the following to `Cargo.toml` here and build:

```toml
[patch.crates-io]
mio = { git = "https://github.com/FreeBSDRust/mio" }
libc = { git = "https://github.com/FreeBSDRust/rust-libc" }
```

**Comment by jbeich** [comment]
Another option is to use [downstream package](https://www.freshports.org/x11/alacritty/) which recently got [a workaround](https://github.com/freebsd/freebsd-ports/commit/87fdd25c8ee1cca5eb685200610bb19ef0b43d82).

**Comment by lukaslueg** [comment]
Upstream has updated, this can be closed.
