### ISSUE TITLE
Allow customizing the scroll sensitivity

### ISSUE THREAD

**Issue by tbodt** [jwilm/alacritty#622]

**Comment by jwilm** [comment]
Scrolling sensitivity is dictated by the OS/DM. For instance, X11 tells us how many lines were scrolled. On macOS, the trackpad indicates a distance in pixels.

**Comment by tbodt** [comment]
When I scroll the smallest possible amount I can on my trackpad, Vim scrolls down two lines. It sort of seems to me that the pixel distance reported is being interpreted as a line distance.

**Comment by jwilm** [comment]
ugh, sounds like a Glutin issue. More and more tempted to just switch to glfw...

**Comment by jwilm** [comment]
Wait, didn't you say you're on macOS?

**Comment by tbodt** [comment]
Yup

**Comment by jwilm** [comment]
Could you run alacritty with the `--print-events` flag, try scrolling, and paste the log here? Definitely can't repro locally, so need more info from you.

**Comment by BasilSkrnk** [comment]
I use Alacritty on my MacBook Air 11 with Arch Linux, and while I adjusted the comfortable scroll speed for my system (browser, mostly) it’s incredibly slow in the terminal. I would prefer to have those two speeds separated, if possible. Just saying.

**Comment by kchibisov** [comment]
@BasilSkrnk 

We have `scrolling.multiplier` in a config, just set it to larger value.

**Comment by BasilSkrnk** [comment]
Forgot to reply, thank you, that helped. That’s what I was looking for.
