### ISSUE TITLE
No support for alternative HID-style inputs.

### ISSUE THREAD

**Issue by mscharley** [jwilm/alacritty#629]
Some keyboard inputs on OSX use a HID-aided input and don't rely entirely on the keyboard.

For example, this is the expected view as per Terminal:
<img width="971" alt="screen shot 2017-06-20 at 8 18 55 pm" src="https://user-images.githubusercontent.com/336509/27328540-d365b6c2-55f5-11e7-90de-4b61a73d5d11.png">

What happens in Alacritty:
<img width="1014" alt="screen shot 2017-06-20 at 8 19 39 pm" src="https://user-images.githubusercontent.com/336509/27328571-eaaa031a-55f5-11e7-91c7-4631ce3751b3.png">

I'm not sure exactly what is needed to support this. A+ job on getting the display of foreign characters working though!

**Comment by chrisduerr** [comment]
From what I've seen, this issue has been resolved by winit/glutin a while ago. Though there are some issues like Alacritty not duplicating the current input, though this is already covered in separate issues.
