### ISSUE TITLE
XEmbed support

### ISSUE THREAD

**Issue by alexherbo2** [jwilm/alacritty#631]

**Comment by mkosem** [comment]
FWIW, I took a crack at adding this last night and quickly found resistance in WindowBuilder, which lacks this support for X11.

Unless there was sufficient interest in using XCB or xlib directly, which would not really flow with the Windows/OSX code paths, it seems like this depends upon: https://github.com/rust-windowing/winit/issues/159

**Comment by mkosem** [comment]
I believe I figured this out, and it's not too invasive.  I submitted a pull request for it: https://github.com/jwilm/alacritty/pull/2786
