### ISSUE TITLE
how to send command/super modifier

### ISSUE THREAD

**Issue by falood** [jwilm/alacritty#632]
with the follow screenshot, I know set `chats: "\x69"` to send `i`, and `chats: "\x09"` to send `^i`, could you please help me how to send `⌘i`?
![image](https://user-images.githubusercontent.com/184053/27421987-796d9df0-56e1-11e7-95b6-a8b4b6eef7ea.png)

Thanks!

**Comment by jwilm** [comment]
Can you post the config you've tried? You need to set `Super` as one of the modifiers.

**Comment by falood** [comment]
Hi @jwilm 
Thank you for your reply.
The question is, I use emacs in tmux with alacritty, and config `Command + i` for my emacs, but it haven't trigger my emacs function, so I guess alactritty have send `Command + i` to emacs.
I know to use `mods: Super/Command` to handle alacritty input, and it totally works for me, so my question is what should I send to internal program when I press Command + i in alacritty?
```
- { key: I, mods: Command, chars: "WHAT SHOULD BE HERE?" }
```

**Comment by chrisduerr** [comment]
@falood So this has been opened a long time ago, but does this actually work in a different terminal emulator? I'm asking because usually terminal emulators know only about ctrl + shift and alt. Running `showkey -a` does not report super on linux for example.
