### ISSUE TITLE
Sharing code to implement terminal multiplexer

### ISSUE THREAD

**Issue by beefsack** [jwilm/alacritty#635]
Apologies for creating an issue for this, but was interested to see what thoughts are and there's potential for some abstraction if it's feasible.

I've been thinking for a few months now about creating a terminal multiplexer in Rust. My initial motivation was that tmux doesn't support the "clear to end of line" ANSI control code and the author doesn't appear interested to include it, but that got me thinking that it'd be cool to have a Rust multiplexer, particularly a very high performance one which might pair well with alacritty.

There'd be an argument that some multiplexing functionality could be built directly into alacritty, but it'd be really cool to have something which could work across terminal emulators.

I'm quite interested to hear thoughts on whether there might be some parts of alacritty which would be useful for implementing a multiplexer, which parts they might be, and whether they'd be high value enough to abstract out into a separate crate or crates.

Cheers, and fantastic terminal emulator, I'm now using it as my daily driver!

**Comment by aeosynth** [comment]
dupe of #450?

**Comment by beefsack** [comment]
@aeosynth I think you're right 👍
