### ISSUE TITLE
Update readme to indicate that scrollback is waiting for contributors

### ISSUE THREAD

**Issue by tbodt** [jwilm/alacritty#637]

**Comment by jwilm** [comment]
I'm not interested in advertising for contributors in the README. I also think it would be exceedingly difficult for a new contributor to come up with a solution for that feature that meets the performance demands of the project.

**Comment by tbodt** [comment]
An idea I had for that: Replace the grid, a vector of lines with the bottom line first, with a circular buffer that stores all the scrollback, with the bottom screen line last. Then change the renderer to draw lines starting at the end of the circular buffer minus the number of lines we're currently scrolled up, and moving backwards. When a new line appears, it can be added at the end of the buffer. Not sure how the alternate screen would work though. Thoughts?
