### ISSUE TITLE
characters missing on macOS

### ISSUE THREAD

**Issue by Thomasdezeeuw** [jwilm/alacritty#639]
The following characters don't work on macOS:

- ~
- `
- "
- '

I have found some of the required configuration, but not all:

```
  - { key: Apostrophe,              chars: "\x27"                        }
#  - { key: ",              chars: "\x22"                        }
#  - { key: ~,              chars: "\x7e"                        }
  - { key: Grave,                   chars: "\x60"                        }
```

I can't seem to find `"` and `~` in https://docs.rs/glutin/0.8.1/glutin/enum.VirtualKeyCode.html. Anyone has any luck finding them?

**Comment by falood** [comment]
maybe what you need is `- {key: Grave, mods: Shift, chars: "MODIFIED_CHARS"}`, the same with `Apostrophe`, hope it's helpful for you.

**Comment by Thomasdezeeuw** [comment]
@falood I mean I can't find the required keys for `"` and `~`, the other keys `"` (Apostrophe) and ``` (Grave) do work.

**Comment by jwilm** [comment]
" and ~ are really just apostrophe and grave with a shift modifier.

**Comment by Thomasdezeeuw** [comment]
Ah I misunderstood. I got it to work, thanks guys!

For future reference adding the following to the `key_bindings` settings worked for me:
```
  - { key: Apostrophe,              chars: "\x27"                        }
  - { key: Apostrophe, mods: Shift, chars: "\x22"                        }
  - { key: Grave,                   chars: "\x60"                        }
  - { key: Grave,      mods: Shift, chars: "\x7e"                        }
```
