### ISSUE TITLE
Alacritty fails to start with a shader error.

### ISSUE THREAD

**Issue by billmurphy5th** [jwilm/alacritty#64]
I tried running alacritty inside a VMWare Workstation VM and received and immediately received an error.
```

device_pixel_ratio: 1
Alacritty encountered an unrecoverable error:

	There was an error initializing the shaders: failed compiling shader: 0:14(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
```
Below is information about the VM.

```
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
```

**Comment by nealian** [comment]
I get the same error on a VirtualBox VM with the following details:

Host OS: CentOS 7.3
Guest OS: CentOS 7.3
uname -a output: Linux relativity 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lord-re** [comment]
See Issue #128 for more informations.

**Comment by jwilm** [comment]
Closing in favor of #128
