### ISSUE TITLE
Fails to launch with 'no such file or directory'

### ISSUE THREAD

**Issue by OJFord** [jwilm/alacritty#640]
Trying to run in arch:

```sh
$ alacritty
Command::spawn() failed: No such file or directory (os error 2)
```

I thought it might be my config file, but that certainly exists. Looking at [the code](https://github.com/jwilm/alacritty/blob/b9ec141c927b333bfea5d8a285deedd164181dd8/src/tty.rs#L245-L249), it seems that the only file/directory involved would be the working directory argument, if supplied; I get the same error if I do supply one though.

**Comment by jwilm** [comment]
Could you share your config?

**Comment by OJFord** [comment]
Bah, sorry for wasting your time - I thought I was going to be able to say It's the default, modulo DPI, but while checking I noticed a suspicious path to my shell program.

I removed the (correct on another machine, but not this) absolute path, since it's always going to be `$PATH` anyway, and it works great.

Sorry about that.
