### ISSUE TITLE
Colour profile inversion toggle?

### ISSUE THREAD

**Issue by OJFord** [jwilm/alacritty#644]
An issue I'm having at the moment is that for minutes at a time I can barely read the text in alacritty, due to sudden bursts of unexpected (British) sun, and my usual favour for a dark colourscheme.

I think it would be great to have a 'user action' (to be assigned a keyboard shortcut) for toggling colour schemes, and I'd like to have a go at implementing it, if it sounds acceptable in principle.

In keeping with the general minimalism of alacritty, I imagine this would be just a straight toggle that wouldn't even need further parameters in config: just switch `background` and `foreground`, `white` and `black`, et al.

**Comment by jwilm** [comment]
As a hack in the interim, you can use the `Command` action to modify your config file in-place to get the same effect.

**Comment by OJFord** [comment]
Ahah! Thank you, I didn't realise `command` existed.

In case there's any other interest in this, I've achieved it by:
```yml
key_bindings:
  - { key: C, mods: Control, command: {program: "alacritty-invert-colours", args: [] }
```

```sh
#!/bin/sh
set -e

config="$XDG_CONFIG_HOME/alacritty/alacritty.yml"

switch_colours() {
    sed -i "s/$1/__TMP__/g ; s/$2/$1/g ; s/__TMP__/$2/g" "$config"
}

switch_colours foreground background
switch_colours white black
switch_colours cyan red
switch_colours magenta green
switch_colours blue yellow
```

Note that there presently isn't an example of using `command` in the sample config files (or in the readme) - since it's pretty simple to implement like this I'm less in favour of my own proposal - it might be worth featuring `command` a bit more prominently though, so that users like me see it before we nag for feature bloat. :slightly_smiling_face:
