### ISSUE TITLE
Document Action::Command

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#646]
Provide an example in the config for `Action::Command`.

cc #644

**Comment by OJFord** [comment]
Just to note, since it confused me briefly in the other issue, it's not actually an action variant, but rather it's own 'key' in the `key_bindings` map. (c.f. `[CommandWrapper](https://github.com/jwilm/alacritty/blob/b4a839aee9784a2d281be1bec87ac6f2ae4a79f0/src/config.rs#L383-L390)`, #566)
