### ISSUE TITLE
Make alacritty available from `cargo install`

### ISSUE THREAD

**Issue by Limeth** [jwilm/alacritty#653]
The current alacritty version on crates.io is very outdated. Currently, if installed via `cargo install alacritty`, it just displays "Hello, world!".
It would simplify the process of installing alacritty significantly for Rust developers.
I would like to install alacritty automatically via a script from my dotfiles; the difference between cloning, building and copying the binary vs running a single command is significant.

**Comment by jwilm** [comment]
#357

**Comment by vityafx** [comment]
@jwilm Sorry, how is this related to the problem?

I have tried to install it via:

1. `cargo install`.
2. `sudo snap install alacritty`
3. `sudo apt install alacritty`

All of the installations just show me `Hello, world!` string and exit right after that. I am on ubuntu 18.04. I could not find an answer to that in the issues #357, could you clarify it to me, please?

**Comment by chrisduerr** [comment]
@vityafx That's related to the problem because Alacritty currently isn't published to crates.io yet. So there's only a placeholder available.

Installing through cargo is already possible through git (see INSTALL.md), however to make `cargo install alacritty` work, it's necessary to publish it to crates.io first.

**Comment by vityafx** [comment]
> @vityafx That's related to the problem because Alacritty currently isn't published to crates.io yet. So there's only a placeholder available.
> 
> Installing through cargo is already possible through git (see INSTALL.md), however to make `cargo install alacritty` work, it's necessary to publish it to crates.io first.

I understand that, but in the `README.md` file you are referring to, the option to install via `apt` [is also listed](https://github.com/jwilm/alacritty#pop_os--ubuntu). And yet it does not work.

**Comment by chrisduerr** [comment]
> If you're not running Pop!_OS, you'll have to add a third party repository first

This is not an official Ubuntu repository.

**Comment by vityafx** [comment]
> > If you're not running Pop!_OS, you'll have to add a third party repository first
> 
> This is not an official Ubuntu repository.

But it is listed in the [installation manual](https://github.com/jwilm/alacritty#installation). Shouldn't I follow the instructions there?

**Comment by chrisduerr** [comment]
Yes, but these instructions also tell you that you'll need to add a PPA repository first.

**Comment by vityafx** [comment]
> Yes, but these instructions also tell you that you'll need to add a PPA repository first.

What makes you think I didn't?

**Comment by kchibisov** [comment]
> What makes you think I didn't?

In case you've tried that PPA and it didn't work anymore, then reporting to PPA owner will be a good idea, since it's a third party thing.

However I have a strongly feeling, that you're launching `alacritty` from cargo all the time, try running `which alacritty`.

**Comment by vityafx** [comment]
@kchibisov Indeed, I was running it from cargo all the time, don't know how can that be:

```
~
❯ alacritty 
bash: /home/user/.cargo/bin/alacritty: No such file or directory

~
❯ which alacritty
/usr/bin/alacritty

```
