### ISSUE TITLE
Add support for color changing escape sequences.

### ISSUE THREAD

**Issue by dylanaraps** [jwilm/alacritty#656]
These escape sequences manipulate the open terminal's colorscheme and allow you to change your terminal's colorscheme on the fly. These escape sequences are supported by all of the terminal emulators I've tried with the exception of `konsole` which ignores them.

Two of my projects use these escape sequences for their main purpose and they currently don't work in Alacritty since the sequences aren't yet supported. 

- https://github.com/dylanaraps/wal
- https://github.com/dylanaraps/pywal

Issue on my repo: https://github.com/dylanaraps/pywal/issues/37

I fully understand if you don't want to implement this feature, there are a lot of really weird escape sequences in the Xterm/Rxvt specs and I understand that you want to keep Alacritty simple. \^\^

The sequences are as follows:

```
# Manipulate colors 0-256
# \033]4;{index};{color}\007

# Change color 7 to #FFFFFF
\033]4;7;#FFFFFF\007

# Change color 14 to #333333
\033]4;14;#333333\007

# Manipulate special colors.
# 10 = foreground, 11 = background, 12 = cursor foregound
# 13 = mouse foreground, 708 = terminal border background
# \033]{index};{color}\007

# Change the terminal foreground to #FFFFFF
\033]10;#FFFFFF\007

# Change the terminal background to #000000
\033]11;#000000\007

# Change the terminal cursor to #FFFFFF
\033]12;#FFFFFF\007

# Change the terminal border background to #000000
\033]708;#000000\007
```

Source:

- http://pod.tst.eu/http://cvs.schmorp.de/rxvt-unicode/doc/rxvt.7.pod#XTerm_Operating_System_Commands

**Comment by lord-re** [comment]
Wow, i didn't knew it was possible to change the terminal background on the fly. That's just awesome.
A good way to differentiate local sessions and ssh ones !
