### ISSUE TITLE
Screen tearing with vim/tmux and blank/duplicated lines.

### ISSUE THREAD

**Issue by bititanb** [jwilm/alacritty#660]
Hi, I have tearing screen problem using neovim (or vim, doesn't matter) in tmux in alacritty. Mostly when I scroll up/down (especially when i open empty buffer with :enew and trying up/down, when there is only 1 empty line in a file), but it happens when i use command/insert mode too. Tearing mostly happens in the bottom part of the screen. 

- Can't capture it on video with obs, etc... (strange thing it is gone completely for some time (even on my screen) when i starting to record in obs, but not in the other tools).
- Disabling colorscheme in vim (or looks like at least using the one that doesn't change background color from the terminal default bg color) fixes it.
- Commenting this line in one of my themes (onedark.vim) makes it work:
`call s:h("Normal", { "fg": s:white, "bg": s:black }) " normal text`
(looks like the function sets :highlight for Normal group - I believe just changes basic bg and fg colors)
- Vsync, etc doesn't help (ATI mesa drivers)
- Sometimes tearing disappears completely, but it happens randomly. This thing drives me crazy.
- No tearing with urxvt.
- No tearing when I unmaximize the window to about 3/4 height (Awesome WM).
- No tearing when scrolling through files with at least ~100 lines of text, but there is the second problem.

The second problem is that sometimes lines disappear or make duplicates or just mess up partially. I'm using 24-bit colorschemes everywhere btw, though at least tearing problem is independent from it (tested). When I tried the latest neovim from their repo the second issue became much worse so I downgraded for now to the old one. That's how it looks in latest neovim:
[
![screenshot_2017-07-13_02-28-43](https://user-images.githubusercontent.com/16485581/28145982-224712be-677f-11e7-983b-07af432d9ae8.png)
](url)

It would be great if you have any ideas what can be the cause, because i'm lost.
Thank you for your hard work, besides these occasional bugs the software is awesome, don't even want to think about switching back to urxvt or something.

Software:
> arch-linux 4.11.9-1
> awesome-wm 4.1-1
> alacritty-git 0.1.0.549.ge11ff42-1
> alacritty-terminfo-git 0.1.0.550.g94849c4-1
> neovim 0.2.0-2
> python-neovim 0.1.13-2
> python2-neovim 0.1.13-2
> tmux 2.5-3
> vim-runtime 8.0.0628-1
> xf86-input-libinput 0.25.1-1
> xf86-video-ati 1:7.9.0-1
> xf86dgaproto 2.1-3
> xf86vidmodeproto 2.3.1-3
> xorg-server 1.19.3-2
> mesa 17.1.4-1
> mesa-vdpau 17.1.4-1

**Comment by bititanb** [comment]
Ok, if someone stumbles upon it, this will be the temporary fix for both problems:

`autocmd BufEnter * highlight Normal guibg=0`

This just makes vim background transparent.
With this the tearing is gone too, so I believe the root of the issue is the same.

**Comment by Robin-Jonsson** [comment]
Could be wrong here, but to me that looks like a truecolor vs. 256color issue. Try adding this in your ~/.tmux.conf:
`set-option -ga terminal-overrides ",xterm*:Tc"`

**Comment by jwilm** [comment]
Some of the problems you've experienced here should be resolved on master, and others should be resolved in #720. Would you mind trying out that branch @bititanb? Your feedback would be most appreciated. :smile:

**Comment by bititanb** [comment]
Tried #720 branch, works great, thanks :thumbsup:
