### ISSUE TITLE
I can't resize tmux pane.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [jwilm/alacritty#664]
I know that alacritty don't have tabbed interface and recommend use `tmux`.

I'm trying to learn `tmux` but stuck in resizing pane.

I can resize pane on iterm2.

Is there a way to resize pane on `alacritty`?

Thanks in advance.

**Comment by asilvadesigns** [comment]
@luceat-lux-vestra I feel your pain, learning tmux is at first a bit weird, but helps to understand that mostly every tmux action is composed of your default prefix key plus some other character.

For example, a new split pane with a default setup would be `ctrl + b` + `%`. Where `ctrl+b` is the prefix key ..which you should definitely remap to something more comfortable like `ctrl+a` or something along those lines.

Regarding resizing, enter a tmux session and hit your prefix key plus `:`. In my case, I use `ctrl+a` as my prefix key, so I type `ctrl+a :`. This brings up the tmux command prompt. Then I type the command `resize-pane -R 20`, or some variation of that, which will resize the current pane right by 20 cells, or `resize-pane -L 20` which does the same for the left.

This is a nice resource:
https://gist.github.com/MohamedAlaa/2961058

Here are some others:
http://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/
https://www.sitepoint.com/tmux-a-simple-start/
https://thoughtbot.com/upcase/tmux
https://learnxinyminutes.com/docs/tmux/

Just stick with it, really annoying at first but once you get the hang of it, it's pretty awesome. Have fun!

**Comment by benoit-pierre** [comment]
Note that you can also use the mouse (`set-option mouse`) to easily resize pane by left-clicking on the delimiter between panes and dragging. On that note, the current selection should probably be cleared on mouse events as if anything was previously selected before enabling the mouse and resizing the pane, then the selection rectangle will stay at the same place while the text itself can change position because of the resizing! Same issue when entering copy mode and scrolling in tmux with some selected text...

**Comment by luceat-lux-vestra** [comment]
Thanks, @asilvadesigns!

I didn't know about that `Prefix` + `:`!

But I want to resize pane by normal shortcut way like `Prefix` + `b`, `Ctrl` + `Arrow ` keys.

But it doesn't work on almost all terminal emulator on macOS except `iterm2`.

I also tried some tweaks like [this](https://superuser.com/questions/863295/adjusting-screen-split-pane-sizes-in-tmux), [this](https://taoofmac.com/space/cli/tmux).
All of them doesn't work.

**Comment by benoit-pierre** [comment]
The shortcuts should work, they do on my side (e.g. Ctrl+b+arrow keys). Could be an issue with your version of tmux, or your alacritty/tmux configurations.  What setting do you use for `TERM`? Does Ctrl+arrow keys work as expected in other terminal applications?

**Comment by luceat-lux-vestra** [comment]
@benoit-pierre 
Ctrl+arrow keys worked on `iterm2` right before.

I think I didn't modified terminal setting(alacritty.yml).

I'm testing `tmux` mainly on `Alacritty` and 'iterm2'.
'tmux` is from hombrew, and I'm using `macOS Sierra`.

**Comment by benoit-pierre** [comment]
Was does `$TERM` end up being set to in your alacritty+tmux terminal? If alacritty is configured to send a specific sequence for `Ctrl+Up`, but tmux is configured to use a terminfo database that is not compatible that could explain your issue. Per default alacritty is sending xterm compatible key sequences.

**Comment by luceat-lux-vestra** [comment]
`Prefix, `Ctrl`+`Arrow` is work only horizontal split, and `Prefix`, `Alt`+`Arrow` is work both split.

I'm currently referencing cheat sheet on the web for shortcuts.

Mostly, they tell pane resize shortcut is `Prefix, `Ctrl`+`Arrow`.

`Prefix`, `Alt`+`Arrow` work on my system as I wanted but it seems not a normal way.

Could you explain about this?(I'm googling about it now, but...)

Thanks in advance!

**Comment by luceat-lux-vestra** [comment]
Thanks, @asilvadesigns, @benoit-pierre.

It seems not related with `alacritty`. Sorry!

**Comment by antonio-chaione** [comment]
This seems as a very old post but I had the same issue recently and ended up working with `prefix` + `opt` + `arrow`
