### ISSUE TITLE
`Meta` key is not working on macOS.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [jwilm/alacritty#667]
I found [this](https://github.com/syl20bnr/spacemacs/issues/6470) solution for `iTerm2` and default `terminal` app.

And some discussions on here #62 #93 

But I can't figure out how to make it works on Alacritty.
Defending on #93, it seems I need to add every key combination to `config` file, that's fine but I want more like `iTerm2` or `terminal` way.

I want to know how `Meta` key works on `Alacritty` too.

Thanks in advance.

**Comment by jwilm** [comment]
This seems like the same issue as #62. Is this somehow different?

**Comment by luceat-lux-vestra** [comment]
Sorry for my bad, no difference.

I should comment existing issue rather than create an issue next time.

Could you tell me how is work about this issue going on?

**Comment by jwilm** [comment]
I don't think anyone is working on it at the moment; a common work-around is to add keybindings as you've mentioned.
