### ISSUE TITLE
Issue with `CFBundleIdentifier` on macOS

### ISSUE THREAD

**Issue by luceat-lux-vestra** [jwilm/alacritty#668]
I want to give `CFBundleIdentifier` to `alacritty`.

It worked for the first time, but after once quit it launches but doesn't show up the terminal screen.
I mean, I can see `alacritty` on the menu bar, but no screen shows up.

`CFBundleIdentifier` is already commented out on `info.plist`.

I think there's a reason for it like my issue.

Please let me know if you know something about it.

Thanks.

**Comment by benoit-pierre** [comment]
See #661.

**Comment by luceat-lux-vestra** [comment]
@benoit-pierre I cleared launch services cache accrding to @tbodt s comment on #661 but doesn't work at all.

Aditionally, did more complicated [one](https://www.tekrevue.com/tip/rebuild-launchservices-fix-duplicate-entries-os-xs-open-menu/), it made some difference but doesn't work too.
