### ISSUE TITLE
A way to disable Config Watcher

### ISSUE THREAD

**Issue by lord-re** [jwilm/alacritty#670]
An option to completely disable the config watcher would be interesting.

Editing alacritty's config is very rare. So it's quite pointless to have a config watcher.
As I use i3 with lots of terms open i find myself with tens of config watchers.

**Comment by sodiumjoe** [comment]
Looks like this was fixed by https://github.com/jwilm/alacritty/pull/689.

**Comment by jwilm** [comment]
thx :)
