### ISSUE TITLE
OSX App Multiple Window instances fail

### ISSUE THREAD

**Issue by thechriswalker** [jwilm/alacritty#674]
Trying to open multiple instances of the macOS App fails.

I wanted more than one instance - i.e. more than one terminal window (I usually have at least 4). The core program can definitely do this as I can run the binary directly many times with no problem.

But launching the App...

With spotlight:
 - if not running: fine
 - when app running:  error `The application “Alacritty.app” is not open anymore.`

From another terminal with `open /path/to/Alacritty.app`:
 - if not running: fine 
 - when app running: error `LSOpenURLsWithRole() failed with error -600 for the file /path/to/Alacritty.app.`

**Comment by dominiklohmann** [comment]
`open -n /path/to/Alacritty.app` works fine for me.

From `man open`:

> -n  Open a new instance of the application(s) even if one is already running.

**Comment by thechriswalker** [comment]
thanks @dominiklohmann - that is useful (and I should have thought of reading the manual...)

However while that means I can create some alias to launch a new alacritty window easily, we still cannot:

 1. use spotlight to bring a running version of alacritty to the front - which I guess should be the default behaviour.
 2. open a new alacritty window without dropping to a shell first - maybe the macOS app should have a "new window" menu item, seems like it might be a common usage.

These two things are surmountable, but would greatly improve the UX on macOS (I have no idea the difficulty of implementation however)
