### ISSUE TITLE
build error on 'cargo build --release'

### ISSUE THREAD

**Issue by psiegman** [jwilm/alacritty#676]
Hi All,

I pulled the latest version of alacritty and did a 'cargo build --release'.
This resulted in:

```   Compiling tempfile v2.1.5
   Compiling num-traits v0.1.37
   Compiling lazy_static v0.1.16
   Compiling linked-hash-map v0.3.0
   Compiling phf_codegen v0.7.21
   Compiling yaml-rust v0.3.5
   Compiling serde_derive v0.9.15
error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
  --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.9.15/src/lib.rs:13:1
   |
13 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `serde_derive`.
Build failed, waiting for other jobs to finish...
error: build failed
```

Alacritty revision: c8e4f366e740b98377bf6faf157af358b3bc70d2

```
$ uname -a
Linux flash 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cargo --version
cargo-0.17.0 (built 2017-03-24)
$ rustc --version
rustc 1.16.0
```

Let me know if you need more info.

regards,

Paul

**Comment by jwilm** [comment]
This is a bug with the compiler on homebrew. Two solutions:

1. use Rustup instead of the homebrew compiler
2. uninstall the homebrew compiler, update brew, and reinstall.

**Comment by psiegman** [comment]
I'm not using homebrew, this is an ubuntu system. I'm using apt-get.

**Comment by jwilm** [comment]
In that case, I would recommend using rustup as the README suggests.

Sorry for not looking super closely at first; an extremely similar error has been posted several times about the homebrew issue.

**Comment by scruss** [comment]
Having same problems on Ubuntu. Respectfully suggest changing readme, as it currently suggests “*Alternatively* see below on how to install it with rustup.”

Also, Ubuntu dependencies are missing `cargo`.

**Comment by jwilm** [comment]
@scruss thanks for the feedback. Did it work when you built with the `rustup` provided `rustc` and `cargo`?

**Comment by scruss** [comment]
Yes, built fine, thanks, though the .rs domain gave me pause.

**Comment by jwilm** [comment]
Thanks; I updated the README.
