### ISSUE TITLE
Rendering issue on Debian Stretch

### ISSUE THREAD

**Issue by liuw** [jwilm/alacritty#678]
I've got an issue when using Alacritty + Tmux with NeoMutt running. Sometimes NeoMutt interface is completely garbled. It would only come back to normal after I press Ctrl-L (refresh).

I'm using 94849c4f2a.

Here are two screenshots to show the effects.

![bad](https://user-images.githubusercontent.com/138514/28427906-85280af0-6d6f-11e7-9308-5d2286d5e463.png)

![good](https://user-images.githubusercontent.com/138514/28427912-8c19a0f8-6d6f-11e7-8c5f-b951737e4361.png)

**Comment by liuw** [comment]
Bumping the internal buffer size from 4KB to 1MB seems to solve this issue.

I'm not suggesting that's the right solution though. :-)

**Comment by jwilm** [comment]
Is this still a problem?

**Comment by liuw** [comment]
Sorry for the late reply.

I just tried 7c4e84c695cc54ca1d7089a91a97ce2617010205. The problem appears to be fixed.
