### ISSUE TITLE
Mouse scrolling in tmux is reversed

### ISSUE THREAD

**Issue by arrufat** [jwilm/alacritty#679]
Hi! I've been using alacritty for a while and it works perfectly.
However, I've updated it today, and now the mouse scroll is reversed in tmux.
It worked fine in revision https://github.com/jwilm/alacritty/commit/c8e4f366e740b98377bf6faf157af358b3bc70d2
So my guess is that this commit might have broken it https://github.com/jwilm/alacritty/commit/8e7dd009a4335e6d6673c1aabb2b92d27f86155c

Thanks in advance!

**Comment by auscompgeek** [comment]
Not just tmux.

**Comment by arrufat** [comment]
Yes, I've just noticed that on vim, too.

**Comment by arrufat** [comment]
@jwilm thank you! :D
