### ISSUE TITLE
Key (circumflex) isn't recognized

### ISSUE THREAD

**Issue by OkanEsen** [jwilm/alacritty#680]
I'm not entirely sure if this is related to #392 and maybe alacritty isn't the issue here but rather https://github.com/tomaka/glutin. I'm using a German keyboard and had to manually bind some keys, because they weren't recognized. So far everything works, but if I try to bind keys to the circumflex key, I get following output:

```
glutin event: WindowEvent { window_id: WindowId(Id(140574848048336)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 10, state: Pressed, virtual_keycode: None, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

Keys I had to manually bind:
```
  - { key: Key5,     mods: Alt,           chars: "\x5b"                        }
  - { key: Key6,     mods: Alt,           chars: "\x5d"                        }
  - { key: Key7,     mods: Alt,           chars: "\x7c"                        }
  - { key: Key7,     mods: Shift|Alt,     chars: "\x5c"                        }
  - { key: Key8,     mods: Alt,           chars: "\x7b"                        }
  - { key: Key9,     mods: Alt,           chars: "\x7d"                        }
  - { key: Equals,                        chars: "\xb4"                        }
  - { key: Equals,   mods: Shift,         chars: "\x60"                        }
  - { key: N,        mods: Alt,           chars: "\x7e"                        }
  - { key: L,        mods: Alt,           chars: "\x40"                        }
```

So it seems like the key isn't attached to any virtual key? Is there something I'm missing or is this a bug?

**Comment by jwilm** [comment]
Sounds like a bug; would need to be fixed in winit.

**Comment by jarandaf** [comment]
Same happens to me with a Spanish keyboard (backslash key):

```text
glutin event: WindowEvent { window_id: WindowId(Id(140525160286544)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 10, state: Pressed, virtual_keycode: None, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

Thank you @OkanEsen for your bindings, I also had to manually bind some keys.

**Comment by schumacher-m** [comment]
Since it really annoyed me that I can't hit "^" on my german keyboard for vim, I slapped together a crude fix so it will do this now when I hit the key.
```glutin event: WindowEvent { window_id: WindowId(Id(140464372164496)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 10, state: Released, virtual_keycode: Some(Caret), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }```
Before it returned None.

With this keyboard mapping:
```
 - { key: Caret,                         chars: "\x5e"                          }
```
I can enter "^" again.

See: https://github.com/schumacher-m/winit/commit/a36cd30cf5488572d61e4949660b209fce8d44e9

What you need to do is checkout glutin + winit and modify the Cargo.toml in alacritty + glutin so it points to the checkout'ed version eg. ```{path = "../winit"}```

It's not PR-worthy yet. I'll may work on it on the weekend. Please check it that helps you in some way.

**Comment by schumacher-m** [comment]
I'm on it to get the change into winit:master -> bump glutin and then open a PR for the alacritty itself.

**Comment by schumacher-m** [comment]
This is not forgotten. Now I need to wait for winit to get released (+ the next version appears in glutin) :-D
I'm rebasing every now and then master to my branch: https://github.com/schumacher-m/alacritty/tree/keycode_caret

**Comment by schumacher-m** [comment]
To finally get some closure: https://github.com/jwilm/alacritty/pull/1155
