### ISSUE TITLE
Question: Setting up Mac App

### ISSUE THREAD

**Issue by mhartington** [jwilm/alacritty#687]
Hi, this is more of a question than an actual issue, but could probably end up being a PR in the form of docs. 

I have Alacritty built successfully and it launches by calling the binary, but Im a bit lost/confused on how to set up the mac app portion of things.

Does any path need to be modified at all? 
Copy/Pasting the mac app to the applications folder does not seem to be the correct way as it will just quit upon start up.

**Comment by OkanEsen** [comment]
You just have to run `make app` where the `Makefile` is located, after that you should have 
 Alacritty.app located under `target/release/osx`.

**Comment by mhartington** [comment]
Perfect, that works great. Thanks! I'll send a PR to get this added to the readme for those interested

**Comment by OkanEsen** [comment]
It's already added to the [wiki](https://github.com/jwilm/alacritty/wiki/MacOS-application-bundle) but a hint wouldn't hurt, I agree.

**Comment by asilvadesigns** [comment]
smh wow... I was using automator to call the binary #fail #noob.
