### ISSUE TITLE
Specify a color for bold text

### ISSUE THREAD

**Issue by lewisinc** [jwilm/alacritty#695]
Just a question for config options - am I able to specify a color for bold text? I'm coming from iTerm2 where this was an option, so I'm wondering if it's possible.

Here's iTerm2 with a bold color specified:
![iterm2 example](https://user-images.githubusercontent.com/6754950/28582277-b3988a88-7119-11e7-87b3-0e0976424921.jpg)

And now Alacritty with the same colorscheme minus a bold font:
![alacritty example](https://user-images.githubusercontent.com/6754950/28582290-be26a778-7119-11e7-9bce-341beb6692fe.jpg)

**Comment by jwilm** [comment]
Yes, you should be able to specify alternate "bright" colors and enable the switch "use_bright_colors_for_bold_text" or whatever it's called.

**Comment by lewisinc** [comment]
So, I haven't yet been able to figure out why bold text doesn't work - "use_bright_colors_for_bold_text" doesn't solve the issue. I'm curious if my `$TERM` variable could be messing with things - what supported terminal modes can I use? Right now `$TERM` is `screen-256color`.

I guess the reason I'm coming back to this is that fish shell's `set_color` seems to be able to figure out bold text, but good ol' `tput bold` doesn't seem to have any effect.

**Comment by jwilm** [comment]
@lewisinc you would also want to check that your configured bright colors differ from the normal colors.

**Comment by lewisinc** [comment]
They do, I was under the impression that bold text is different from bright text, however. I'm not familiar with the standards around terminal emulators - just that both Terminal.app and iTerm.app seem to handle this case while Alacritty does not. I'll add in my config file if that helps. If there's something you can think of that I could look into I can give it a go.

Anyways, thanks so much for making this project a reality and being available to me and the community :)

`# Configuration for Alacritty, the GPU enhanced terminal emulator

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color

# Window dimensions in character columns and lines
# (changes require restart)
dimensions:
  columns: 95
  lines: 34

# The FreeType rasterizer needs to know the device DPI for best results
# (changes require restart)
dpi:
  x: 96.0
  y: 96.0

# Display tabs using this many cells (changes require restart)
tabspaces: 8

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: SF Mono
    # Style can be specified to pick a specific face.
    style: Semibold

  # The bold font face
  bold:
    family: SF Mono
    # Style can be specified to pick a specific face.
    style: Semibold

  # The italic font face
  italic:
    family: SF Mono
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 13.0
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0.0
    y: 0.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# Should display the render timer
render_timer: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '0x212121'
    foreground: '0xD9DCDE'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x474646'
    cursor: '0xFD9394'

  # Normal colors
  normal:
    black:   '0x474646'
    red:     '0xDA7085'
    green:   '0x87BB7C'
    yellow:  '0xD5B875'
    blue:    '0x70ACE5'
    magenta: '0xA48ADD'
    cyan:    '0x69C5CE'
    white:   '0xBCBEC0'

  # Bright colorS
  bright:
    black:   '0x6A6C6C'
    red:     '0xED8499'
    green:   '0x97D589'
    yellow:  '0xE9CB88'
    blue:    '0x87BFF5'
    magenta: '0xB9A0EF'
    cyan:    '0x7BDBE4'
    white:   '0xD0D2D3'

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
visual_bell:
  animation: EaseOutExpo
  duration: 0

# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the control key
# `Shift` for the Shift key
# `Alt` and `Option` refer to alt/option
#
# mods may be combined with a `|`. For example, requiring control and shift
# looks like:
#
# mods: Control|Shift
#
# The parser is currently quite sensitive to whitespace and capitalization -
# capitalization must match exactly, and piped items must not have whitespace
# around them.
#
# Either an `action` or `chars` field must be present. `chars` writes the
# specified string every time that binding is activated. These should generally
# be escape sequences, but they can be configured to send arbitrary strings of
# bytes. Possible values of `action` include `Paste` and `PasteSelection`.
key_bindings:
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[1~",  mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[4~",  mode: ~AppCursor  }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
  - { key: F3,                      chars: "\x1bOR"                      }
  - { key: F4,                      chars: "\x1bOS"                      }
  - { key: F5,                      chars: "\x1b[15~"                    }
  - { key: F6,                      chars: "\x1b[17~"                    }
  - { key: F7,                      chars: "\x1b[18~"                    }
  - { key: F8,                      chars: "\x1b[19~"                    }
  - { key: F9,                      chars: "\x1b[20~"                    }
  - { key: F10,                     chars: "\x1b[21~"                    }
  - { key: F11,                     chars: "\x1b[23~"                    }
  - { key: F12,                     chars: "\x1b[24~"                    }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  - { key: Insert,                  chars: "\x1b[2~"                     }
  - { key: Delete,                  chars: "\x1b[3~"                     }

# Mouse bindings
#
# Currently doesn't support modifiers. Both the `mouse` and `action` fields must
# be specified.
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# Values for `action`:
# - Paste
# - PasteSelection
# - Copy (TODO)
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

hide_cursor_when_typing: true

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
#shell:
#  program: /bin/bash
#  args:
#    - --login
`

**Comment by jwilm** [comment]
Config looks fine. If you run this command, do you see two different colors?

```sh
printf "\e[31mNORMAL, \e[1mBOLD\e[m\n"
```

**Comment by lewisinc** [comment]
Yep, those are different.

**Comment by jwilm** [comment]
Great; sounds like everything is working as expected. Must be an issue outside of Alacritty.

**Comment by lewisinc** [comment]
Probably - from what I've read `tput` relies on a terminfo database to supply the right escape codes for each terminal setting. It might not be providing the ones Alacritty expects, which could explain why `tput` doesn't properly embolden text inside Alacritty. Any thoughts on how I might dig further?

I might also just be thinking about this wrong.

**Comment by jwilm** [comment]
You can try asking the terminfo database what it thinks bold is

```sh
infocmp | grep bold
```

**Comment by lewisinc** [comment]
`bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,`

**Comment by jwilm** [comment]
Looks like it's got the correct sequence.

**Comment by jwilm** [comment]
I'm wondering if your config is being loaded from a different file than you are editing. I just pushed a commit to master that will log out where config is loaded from if run with `-v`. Could you try double checking that the path is what you expect?

**Comment by lewisinc** [comment]
Confirming it's the path I expected after rebuilding.

**Comment by jwilm** [comment]
Yes that works for me.

**Comment by lewisinc** [comment]
I think this might be because I haven't copied over changes to a new yaml file in a while. New options are in the provided default, namely `padding`, `glyph_offset`, `dim` colors, `background_opacity` and `live_config_reload`.

Thanks for sticking it out with me, but having modified the new default config to have the changes I made before bold works. Sorry if I've wasted time for you.

**Comment by jwilm** [comment]
No worries; glad you got it working!

**Comment by pkazmier** [comment]
Perhaps related, is there a way to specify a **bold** color for the **primary foreground** color? This is somewhat similar, but not the same as the `draw_bold_text_with_bright_colors` as that only seems to kick in when an ANSI color has been specified before the bold sequence is activated. In the following example, I want to only bold the text without having to specify an ANSI foreground color.

```bash
printf "NORMAL, \e[1mBOLD\e[m\n"
```

On Alacritty, this is how it is rendered:
<img width="335" alt="screen shot 2018-03-10 at 11 51 25 am" src="https://user-images.githubusercontent.com/747855/37245200-4f550e8a-245a-11e8-9e0e-9fd5a727bc61.png">

On Terminal.app, which allows you to specify a bold color for the default foreground color, this is how it is rendered as I have specified a brighter white for the default bold color:
<img width="337" alt="screen shot 2018-03-10 at 11 51 50 am" src="https://user-images.githubusercontent.com/747855/37245213-769e3070-245a-11e8-890a-80f5a2726126.png">

The most common place I miss this functionality is when reading `man` pages. Here is the output for `man iostat` in Alacritty:
<img width="677" alt="screen shot 2018-03-10 at 12 00 52 pm" src="https://user-images.githubusercontent.com/747855/37245236-c346a2e0-245a-11e8-9505-3b9a40da7f93.png">

And here is the output for the same in Terminal.app:
<img width="682" alt="screen shot 2018-03-10 at 12 00 44 pm" src="https://user-images.githubusercontent.com/747855/37245245-d8f83284-245a-11e8-84e4-206a7b5c62cd.png">

**Comment by chrisduerr** [comment]
It's not merged yet: https://github.com/jwilm/alacritty/pull/1026.

**Comment by pkazmier** [comment]
Thanks!

**Comment by davidarmstronglewis** [comment]
@chrisduerr, I've been using your bright foreground color option commit on top of master for a bit now and it's exactly what I've been hoping for - thank you!
