### ISSUE TITLE
Mouse wheel scroll doesn't work past around 200 columns

### ISSUE THREAD

**Issue by thallada** [jwilm/alacritty#698]
If I open vim and create two vertical splits and then drag the separator between the two far enough to the right that the left split is about 200 columns wide, the mouse wheel scrolling in the right split stops working. I can set up the same scenario with tmux panes instead and the right pane won't scroll if it starts past around 200 columns.

**Comment by jwilm** [comment]
Does setting `ttymouse=sgr` help?

**Comment by thallada** [comment]
In vim? I tried that but nothing changed. This occurs outside vim too, e.g. just two tmux panes with mouse on and trying to activate scroll-back.

**Comment by GoldbergAF** [comment]
Same issue in tmux.

**Comment by NickeZ** [comment]
I agree, it's enough to have one wide vim window. If the mouse is around column 225 I cannot scroll.

**Comment by GoldbergAF** [comment]
For me the limit is about midway through column 219.  I can't even left-click to place the cursor at any point to the right of that line in vim. In tmux, I can control the cursor at any point, but cannot scroll if the mouse cursor is to the right of this line. Font is Hack, size 9.5, xoffset=-1.0

**Comment by unphased** [comment]
Interesting. If this were 255/256, it could be some unicode byte thing. I have been trying to track down the xterm mouse reporting protocol for this and haven't found something to really get somewhere yet, but it definitely is the terminal giving up on passing through the mouse wheel when on the right side of the screen.

**Comment by RyanStein** [comment]
I'm having this issue as well (7b4ba80bb195b862f50c16263405a9507f99bb82 with [AUR package `alacritty-git`](https://aur.archlinux.org/packages/alacritty-git/)) and can confirm that the mouse wheel fails to scroll regardless of the program (tested vim with `set ttymouse=sgr` and it did not work, tmux split panes with built-in scrollback failed as well) near exactly 220 columns from the left side of the window, regardless of font size setting (testing with font face Dina and `CTRL+=` and `CTRL+-` to resize).

**Comment by chrisduerr** [comment]
Is it possible that scrolling stops working at exacly column 223?
This looks like the issue:
<https://github.com/jwilm/alacritty/blob/master/src/input.rs#L297>

I'll take a look at fixing this in a second.

**Comment by RyanStein** [comment]
I had a look through the code and spotted that [this block of code](https://github.com/jwilm/alacritty/blob/228400a6c24bf651ecd74996d1fa68c3d92c9ff9/src/input.rs#L427) calls `normal_mouse_report` instead of `mouse_report`, which seems to be the method which delegates to either `sgr_mouse_report` or `normal_mouse_report` depending upon how the terminal mode is setup.

Could changing it to `mouse_report` be all that is necessary to get this working?
