### ISSUE TITLE
Redrawing Issue with a Maximized Window on Ubuntu 16.04

### ISSUE THREAD

**Issue by e0i** [jwilm/alacritty#699]
When Alacritty window is maximized, changes in display will consistently lag until the next key press. For example, when editing a file in Vim with Alacritty window maximized, switching to the next tab in Vim will *not* immediately display the next tab's contents until a key is pressed.

This issue is not present when the window is not maximized or when resized into a maximized size.

**Comment by nilsboy** [comment]
Also on 14.04.

**Comment by ACalix** [comment]
I had this issue on Ubuntu 16.04. It was resolved by removing xserver-xorg-video-intel package as mentioned in #540.

**Comment by e0i** [comment]
Seems to be resolved.
