### ISSUE TITLE
README section about Wayland/glutin no longer accurate?

### ISSUE THREAD

**Issue by nh2** [jwilm/alacritty#702]
Currently it says

> Is wayland supported? Not yet. Alacritty is currently on a fork of glutin that needs some updates to work with Wayland. To stop glutin from detecting Wayland (e.g. for use on XWayland) launch Alacritty like this: `env WAYLAND_DISPLAY= alacritty`

But it seems commit 8e7dd009 - "Update to latest Glutin/winit (#671)" does away with that.

**Comment by NickeZ** [comment]
is this a dupe of #97?

**Comment by nh2** [comment]
Possibly; I don't know about how well Wayland support works but at least `is currently on a fork of glutin` seems no longer accurate.

**Comment by jwilm** [comment]
README definitely needs to be updated a bit. Even though we have some Wayland support now, there are a few caveats, and some might prefer to use XWayland still.
