### ISSUE TITLE
Alacritty as a terminal emulation library, like VTE

### ISSUE THREAD

**Issue by tbodt** [jwilm/alacritty#705]
Alacritty is a great terminal emulator, but I can't use a terminal that doesn't have at least tabs and split panes (I'm not familiar with tmux). So to keep the core small, I think it would be a good idea to make Alacritty into a terminal emulation library, instead of a standalone application. Standalone apps could then be developed that use Alacritty for terminal emulation, and provide features like tabs and split panes, GUI configuration, search, etc. They could also provide a more platform-native experience, like a transparent title bar on macOS (this was suggested recently and could be done with 3 lines of Objective-C code, but winit currently provides no api for it).

@jwilm what do you think?

**Comment by aeosynth** [comment]
dupe of #450
