### ISSUE TITLE
Black screen when switching from virtual console

### ISSUE THREAD

**Issue by aeosynth** [jwilm/alacritty#708]
Switch to virtual console (Ctrl+Alt+F1), switch back to X (Ctrl+Alt+F7), alacritty shows a black screen until its window is clicked. Using Void Linux, bspwm, alacritty 20170624.

**Comment by dylnmc** [comment]
not something I can reproduce on arch in bspwm or gnome

**Comment by chrisduerr** [comment]
Closing as duplicate of #602.
