### ISSUE TITLE
Resolution does not change when switching monitors OSX

### ISSUE THREAD

**Issue by jakecode** [jwilm/alacritty#709]
**OS**: OS X Sierra 10.12.5
**GPU**: Intel Iris Pro 1536 MB
**Macbook**: Retina, 15-inch Late 2013
**Macbook Resolution**: 1440 x 900
**External Monitor Resolution**: Both at a resolution of 2560 x 1440
**External Monitor Connections**: Display Port / Thunderbolt 2 and HDMI (issue persists over both)

When switching between my external monitors and my mac monitor, the rendering of the Alactritty console does not scale the text resolution.

When Alacritty was started on the external monitor
<img width="1174" alt="screen shot 2017-08-03 at 9 40 42 am" src="https://user-images.githubusercontent.com/10501790/28924780-da8a3c40-7830-11e7-8752-2cdcefba68c4.png">

When Alacritty was moved to the mac monitor
<img width="1174" alt="screen shot 2017-08-03 at 9 41 14 am" src="https://user-images.githubusercontent.com/10501790/28924773-d178b9c4-7830-11e7-8376-84768aee07f8.png">

With the opposite effect happening when Alacritty is started on the mac monitor and moved to the external monitor. The rendering will be fine on the mac, but when moved to the external monitors the resolution does not upscale, and text appears giant.

**Comment by tmiller** [comment]
I'm also seeing this.

**Comment by evantravers** [comment]
I also have this bug… I haven't been able to test whether it's related to moving from a "retina screen" to a normal DPI screen…

**Comment by tmiller** [comment]
Looks like this is a duplicate of https://github.com/jwilm/alacritty/issues/71

**Comment by jakecode** [comment]
@tmiller Looks like you're right, I'll close this and defer to the already opened ticket. I guess I wasn't thorough enough in my search.
