### ISSUE TITLE
Implement visual distinction between an active terminal and an inactive one

### ISSUE THREAD

**Issue by gnuvince** [jwilm/alacritty#712]
Some terminals such as urxvt allow the user to know which terminal is active and which ones are inactive simply by looking at them.  By default, the cursor of an inactive terminal is hollow, and it is possible to configure the terminal to be of a different color/shade when inactive.  The screenshot below shows this distinction.

Is this something that other people would be interested in?  Would it be in line with the alacritty goals?

![2017-08-04-142647_156x128_scrot](https://user-images.githubusercontent.com/39868/28981746-03d7efc0-7921-11e7-8807-bfb17a23ce07.png)

**Comment by LeonardKoenig** [comment]
I think shading should be probably done by the compositor, but other emulators commonly use the "filled cursor + blinking" to indicate active terminals, an "empy+static" one to indicate inactive.  This would be very useful indeed.

**Comment by chrisduerr** [comment]
I've actually implemented this feature a bit ago! Should work out of the box on the latest master!

Blinking is not implemented yet, however there's a different issue for tracking that (#302).

**Comment by arg** [comment]
> I've actually implemented this feature a bit ago! Should work out of the box on the latest master!

@chrisduerr sorry for posting here but it's the only place where dimming is mentioned. In `alacritty.yml` there is a whole section of dimmed colors but no any description of how to activate them. Could you please provide some more information how to dim inactive Alacritty windows

**Comment by chrisduerr** [comment]
Dimmed colors are for `CSI 2 m`, so `printf "\e[2mTEST"`, it has nothing to do with focus.
