### ISSUE TITLE
tmux mouse select windows does not support by alacritty

### ISSUE THREAD

**Issue by netroby** [jwilm/alacritty#713]
The default shell(without using tmux) can use mice to select area, then press CTRL+SHIFT+c to copy content.

But inside tmux window. even if we open mouse window select.

The alacritty does not respect the mouse behavior.

====================
I also using terminator, it can support mouse select, and copy/past with mouse(by the menu context)

hope alacritty support the tmux mouse select mode

=====================

I am using archlinux + KDE plasma

**Comment by gmile** [comment]
@netroby the mouse cursors works for me in alacritty/tmux. Can you show your tmux config? I have the following option in `.tmux.conf`:

```
set -g mouse on
```

**Comment by netroby** [comment]
Hello , the mouse can select, but copy text from the alacritty window was broken.

I tested it in terminator. it's ok, and i tested in konsole it ok.

the alacritty+tmux , not working.

**Comment by NickeZ** [comment]
@netroby what is your tmux configuration?

**Comment by maximbaz** [comment]
I am also using alacritty+tmux for quite a while, and copying to clipboard works fine.

What @NickeZ suggests will probably copy the selection immediately, I have a bit different setup where I additionally press a key to copy the selection. I can recommend [tmux-yank](https://github.com/tmux-plugins/tmux-yank) plugin, it handles all the magic of configuring `xsel` or `xclip` and just provides two keys out of the box:

- Select a text (with a mouse if you want) and press `y` to copy the selection.
- Select a text and press `Y` to paste the selection in your terminal without copying it to the clipboard.

Alternatively, holding Shift while selecting text should select the text natively via alacritty, i.e. not via tmux. Then Ctrl+Shift+C would just work as you expect. This feature request is tracked by https://github.com/jwilm/alacritty/issues/146

**Comment by netroby** [comment]
my full .tmux.conf
```
set-option -g assume-paste-time 1
set-option -g base-index 0
set-option -g bell-action any
set-option -g bell-on-alert off
set-option -g default-command ""
set-option -g destroy-unattached off
set-option -g detach-on-destroy on
set-option -g display-panes-active-colour red
set-option -g display-panes-colour blue
set-option -g display-panes-time 1000
set-option -g display-time 750
set-option -g history-limit 2000
set-option -g lock-after-time 0
set-option -g lock-command "lock -np"
set-option -g prefix C-b
set-option -g renumber-windows off
set-option -g repeat-time 500
set-option -g set-titles off
set-option -g set-titles-string "#S:#I:#W - "#T""
set-option -g status on
set-option -g status-interval 15
set-option -g status-justify left
set-option -g status-keys emacs
set-option -g status-left "[#S] "
set-option -g status-left-length 10
set-option -g status-position bottom
set-option -g status-right " "#{=21:pane_title}" %H:%M %d-%b-%y"
set-option -g status-right-length 40
set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-option -g word-separators " -_@"

```

**Comment by chrisduerr** [comment]
The behavior mentioned here does work on the latest master.
