### ISSUE TITLE
Missing build dependency for Arch Linux

### ISSUE THREAD

**Issue by magnus-gross** [jwilm/alacritty#718]
The Arch Linux dependency line in the README.md is missing the cargo dependency. Since cargo is in the official repositories, simply adding `cargo` to the `pacman -S` line would fix this.

**Comment by synaptiko** [comment]
I installed `rustup` as it's mentioned here: https://github.com/jwilm/alacritty#prerequisites and updated `PKGBUILD`:
```
	cd $_pkgname

	rustup override set stable
	rustup update stable

	env CARGO_INCREMENTAL=0 cargo build --release
```

**Comment by maximbaz** [comment]
The cargo was removed from the official repositories recently, the `rust` package is providing both rust and cargo now.

**Comment by jwilm** [comment]
@maximbaz any suggestion on how to update the README?

**Comment by maximbaz** [comment]
Like so: https://github.com/jwilm/alacritty/pull/722

**Comment by quininer** [comment]
If `Arch Linux` need to specifically add `rust` dependence, then `Ubuntu`, `Fedora`, `openSUSE` ... should also be added with the dependence.

In fact I think README should not have specific package name, it is difficult to maintain this list.

**Comment by quininer** [comment]
The dependency of `rust` should be met [here](https://github.com/jwilm/alacritty#prerequisites).

**Comment by maximbaz** [comment]
The package names don't change often, there's not a lot of maintenance to it. But good point about the `Prerequisites` section, I missed it myself 🙂

**Comment by quininer** [comment]
Once  dependency have changes, you need to change the dependency lists of multiple distributions such as `Ubuntu`, `Arch Linux`, `Fedora`, `openSUSE`, `Slackware`, `Void Linux`, `Solus`, `NixOS`/`Nixpkgs`.
