### ISSUE TITLE
IPython appends extra characters on newline

### ISSUE THREAD

**Issue by rbtying** [jwilm/alacritty#72]
Reproduction:

run IPython and hit Enter.

Expected behavior: IPython prints an empty prompt (e.g. `In [1]:`)
Observed behavior: IPython prints a prompt starting with `[?6c`:

[screenshot](https://www.dropbox.com/s/3pptbsg07y104md/Screenshot%202017-01-05%2017.18.18.png?dl=0)

Behavior cannot be reproduced from inside of `tmux` (maybe `tmux` handles the characters?)

**Comment by jwilm** [comment]
Thanks for the screen shot! Alacritty sends an escape sequence `\x1b[?6c` in response to the identify terminal request. It's weird that it's showing up here. I'll hopefully look into this in the next few days.

**Comment by anderspitman** [comment]
@jwilm this bug affects me and I've been wanting to contribute to some Rust projects lately. If you think this would be a good starter bug and can point me in the right direction I'd be open to taking a crack at it.

**Comment by snuderl** [comment]
To help narrow this down a bit this seems to be a problem with prompt_toolkit package that ipython uses.

```
from prompt_toolkit import prompt
prompt('Give me some input: ')
```

**Comment by jwilm** [comment]
Thanks for the info @snuderl! This will be helpful when someone makes time to dig into the issue.

**Comment by lukaslueg** [comment]
Here is the output from `-vvv --print-events` when running `promp('foo')`. The prompt then reads `foo[?1;6c`; I can remove the `[?1;6c`-part by hitting backspace. `identify_terminal()` in `src/term/mod.rs` is never actually called.

> glutin event: Awakened
> unset_mode: CursorKeys
> glutin event: Awakened
> set_mode: BracketedPaste
> unset_mode: ShowCursor
> unset_mode: LineWrap
> Set Attribute: Reset
> Set Attribute: Reset
> clear_screen: Below
> Set Attribute: Reset
> move_backward: 3
> move_forward: 3
> Set Attribute: Reset
> unset_mode: BlinkingCursor
> .. ignoring unset_mode
> set_mode: ShowCursor
> glutin event: Awakened
> unset_mode: ShowCursor
> Set Attribute: Reset
> Set Attribute: Reset
> Set Attribute: Reset
> Set Attribute: Reset
> Set Attribute: Reset
> Set Attribute: Reset
> Set Attribute: Reset
> unset_mode: BlinkingCursor
> .. ignoring unset_mode
> set_mode: ShowCursor
>

**Comment by snuderl** [comment]
Actually it is called but there is no trace! on the identify_terminal function.

> glutin event: KeyboardInput(Pressed, 36, Some(Return), , Some("\r"))
> carriage_return
> linefeed
> scroll_up: 1
> glutin event: Awakened
> unset_mode: CursorKeys
> identify terminal
> glutin event: Awakened
> set_mode: BracketedPaste
> unset_mode: ShowCursor
> unset_mode: LineWrap
> Set Attribute: Reset
> Set Attribute: Reset
> clear_screen: Below
> Set Attribute: Reset
> unset_mode: BlinkingCursor

**Comment by lukaslueg** [comment]
Indeed. I had it patched but again: the goggles, they do nothing.

Works for me when re-launching tmux inside alacritty (which is not launched by default for some reason).

**Comment by OJFord** [comment]
Xonsh also uses `prompt_toolkit`, so that sounds likely @snuderl :+1:

**Comment by OJFord** [comment]
Aha - the characters are also printed on resizing the terminal. I believe this is going to be something to do with ptk expecting the height/width to be set, and it not being quite as expected...

**Comment by OJFord** [comment]
Last thing to add: I've just tried removing the `\x1b[?6c` squawk and re-compiling, no ill-affects that I can discern, and obviously it doesn't print it out.

**Comment by OJFord** [comment]
@jwilm What is the 'identify terminal' response used for?

The only way I'm able to use alacritty with xonsh (and I assume it would work with IPython too therefore) is with this patch:

```patch
diff --git a/src/term/mod.rs b/src/term/mod.rs
index 0829998..7921d61 100644
--- a/src/term/mod.rs
+++ b/src/term/mod.rs
@@ -1178,7 +1178,7 @@ impl ansi::Handler for Term {
     #[inline]
     fn identify_terminal<W: io::Write>(&mut self, writer: &mut W) {
-        let _ = writer.write_all(b"\x1b[?6c");
+        let _ = writer.write_all(b"");
     }
     #[inline]
```

Actually, I haven't tried with merely an empty function, I suppose that would be equivalent since I don't believe `write_all` appends a new line? Regardless, I didn't want to open a PR with this since it only removes something which was obviously added for a reason.

I'd be happy to help with fixing this properly, (mainly out of a selfish interest to not need to keep re-applying this patch on every update :slightly_smiling_face:) but I would need a pointer or two on what the purpose of `identify_terminal` is supposed to be; what breaks without it.

Many thanks.
