### ISSUE TITLE
can we blank out WAYLAND_DISPLAY by default?

### ISSUE THREAD

**Issue by oconnor663** [jwilm/alacritty#728]
As described in the README, we need `WAYLAND_DISPLAY=` to run Alacritty on Wayland desktops like Gnome Shell. Would it be possible to have Alacritty itself set that variable, so that it worked by default, at least until the Glutin fork gets the updates it needs?

**Comment by jwilm** [comment]
Glutin isn't on a fork, and Alacritty should work on Wayland today

**Comment by oconnor663** [comment]
Oh cool, we can probably update this language?

> Alacritty is currently on a fork of glutin that needs some updates to work with Wayland.

I notice now that if I run `alacritty` without that env var, it does launch, but at a very small size by default. (Maybe the minimum size allowed by the window manager?) I wasn't sure if that was one of those Glutin fork issues, since setting that env var did seem to fix it, but now it sounds like it's an unrelated issue. Should I file that as a separate ticket for that one?

**Comment by laerus** [comment]
Alacritty doesn't work on debian-stretch and gnome-shell 3.22 without `WAYLAND_DISPLAY=`

**Comment by chrisduerr** [comment]
Wayland support has improved significantly. Even though it's not perfect yet, I don't think this would be beneficial for most users, especially because it'll only get better in the future.
