### ISSUE TITLE
Fails to build `font` with std/fontconfig error under Arch / rustc 1.19

### ISSUE THREAD

**Issue by ronjouch** [jwilm/alacritty#729]
Since a few days (maybe this started last week, somewhere around August 7), Alacritty fails to build.

See the compiler error below, and here is the [full stdout+stderr](https://github.com/jwilm/alacritty/files/1223703/alacrittyBuildFailArchFontconfig.txt). I followed the README installation instructions (am using package `rust`, and the listed dependencies `cmake freetype2 fontconfig pkg-config make xclip`). rustc 1.19.0, cargo 0.20.0.

```bash
error[E0460]: found possibly newer version of crate `std` which `fontconfig` depends on
  --> font/src/lib.rs:21:1
   |
21 | extern crate fontconfig;
   | ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: perhaps that crate needs to be recompiled?
   = note: crate `std` path #1: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-e22d8ea13fc64833.rlib
   = note: crate `std` path #2: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-e22d8ea13fc64833.so
   = note: crate `fontconfig` path #1: /opt/alacritty/target/release/deps/libfontconfig-a7a099d606d4157d.rlib

error: aborting due to previous error(s)

error: Could not compile `font`.
```

**Comment by jwilm** [comment]
Not sure what the problem might be here. I just built from master using the same compiler version. Perhaps you should try doing a clean build `cargo clean && cargo build --release`.

**Comment by ronjouch** [comment]
> *try doing a clean build `cargo clean && cargo build --release`*

@jwilm worked! Thanks! Today I learned `cargo clean`! One more exclamation mark!
