### ISSUE TITLE
feature request: text shadows

### ISSUE THREAD

**Issue by bearcatsandor** [jwilm/alacritty#730]
Years ago when using Enlightenment, i fell in love with the slight drop shadows on text in eterm (and perhaps now in terminology).

Would it be a feasible feature request to be able to add drop shadows to text in alacritty, perhaps through css?

**Comment by vitiral** [comment]
couldn't this be accomplished through a font?

**Comment by jwilm** [comment]
This sort of feature is outside the scope of Alacritty.
