### ISSUE TITLE
Strips blank lines on copy from terminal

### ISSUE THREAD

**Issue by inducer** [jwilm/alacritty#731]
If I mouse-copy (i.e. select and press Shift-Ctrl-C) some text containing blank lines, then these blank lines do not make it into the copied text. They're significant in some cases (such as diffs), so this is not ideal.

**Comment by NickeZ** [comment]
Possible dupe of #432

**Comment by FichteFoll** [comment]
Also running into this. Usually not too severe, but definitely annoying for situations where empty lines matter, such as for diffs.

**Comment by chrisduerr** [comment]
This has been resolved on the latest master.
