### ISSUE TITLE
Karabiner terminal condition remap does not include allacritty

### ISSUE THREAD

**Issue by jojoyuji** [jwilm/alacritty#734]
I have remapped `L-cmd` as `ctrl` using karabiner for terminal only.

![My Karabiner config](https://image.ibb.co/bVBxKv/karabiner.png)

It does work on [iTerm2](https://www.iterm2.com)  and [Hyper](https://hyper.is/) but does not in alacritty. 

Is there a way to set alacritty as a terminal app type in OSX, so karabiner can apply a conditional remap?

**Comment by jwilm** [comment]
Sounds like we might be missing something from our Info.plist.

**Comment by Sachka** [comment]
This might help! I use Karabiner with Alacritty, I added an Alacritty bundle identifier to my configuration file in Karabiner, here is where I put it:

                     ` "description": "Tmux Prefix Mode [left_control as trigger key]",
                        "manipulators": [
                            {
                                "conditions": [
                                    {
                                        "bundle_identifiers": [
                                            "^com\\.apple\\.Terminal$",
                                            "com\\.jwilm\\.Alacritty$",
                                            "^com\\.googlecode\\.iterm2$",
                                            "^co\\.zeit\\.hyperterm$",
                                            "^co\\.zeit\\.hyper$"
                                        ],
                                        "type": "frontmost_application_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "left_option",
                                    "modifiers": {
                                        "optional": [
                                            "caps_lock"
                                        ]
                                    }`

I also added com.jwilm.Alacritty as Bundle Identifier to the Info.plist of Alacritty.app
macOS 10.12.6, Karabiner-Elements 0.91.13.

**Comment by jojoyuji** [comment]
hey @Sachka , thanks for the suggestion.
I tried however but ir didn't work (Probably cause I don't use karabiner-elements)

I don't know well how info.plist works, so I experimented some stuff:

 I swapped hyper.js info.plist with alacritty and so far karabiner remapping is working. 

Imma dig into it later, and maybe make a pull request ;)

**Comment by sgoranson** [comment]
It looks like developers foresaw this issue, because ./assets/osx/Alacritty.app/Contents/Info.plist has the fix commented out. For me, uncommenting it fixed my Karabiner issues

```
    <!-- <key>CFBundleIdentifier</key> -->
    <!-- <string>alacritty</string> -->
```

I was able to reproduce the problem by opening Karabiner Eventviewer, "Frontmost Application" tab. When Info.plist is working, "Bundle Identifier" will show as "alacritty". When it is not working, it will be blank. HTH!

**Comment by yqrashawn** [comment]
I just uncomment these two lines and add it to my json config of Karabiner Eelments, it works fine now.

**Comment by yqrashawn** [comment]
https://github.com/pqrs-org/KE-complex_modifications/pull/261

Fixed for karabinder-elements.

**Comment by yqrashawn** [comment]
@jojoyuji in karabiner `private.xml` config, you need to use 
```xml
  <appdef>
    <appname>Alacritty</appname>
    <equal>io.alacritty</equal>
  </appdef>
```
to define Alacritty as an app and use it later in the `<item>` tag.
```xml
  <item>
    <name>.....</name>
    <identifier>......</identifier>

    <only>Alacritty</only>

    <autogen>
    .....
    </autogen>
  </item>
```

**Comment by jojoyuji** [comment]
thanks @yqrashawn, I updated and the current alacritty version has it fixed :)

**Comment by muhammadharis** [comment]
> You still need to add bellow in your own configuration.
> 
> ```
> "bundle_identifiers": [
>                                         "^com\\.apple\\.Terminal$",
>                                         "^io\\.Alacritty$",
>                                     ],
> ```

One minor thing, the A isn't capitalized i.e it is `^io\\.alacritty$`

**Comment by stevanmilic** [comment]
At the time of writing the alacritty bundle identifier is `org.alacritty` found in `/Applications/Alacritty.app/Contents/Info.plist`.

It was enough to add `^org\\.alacritty$` where `^com\\.apple\\.Terminal$` was placed to achieve same mappings as default terminal apps.
