### ISSUE TITLE
Line hieght issue

### ISSUE THREAD

**Issue by JostCrow** [jwilm/alacritty#738]
![screenshot from 2017-08-18 11-10-25](https://user-images.githubusercontent.com/390575/29452303-20862868-8406-11e7-99a6-1fa5efd2be84.png)

It is really fast. The only downside is that the line height is not that good. I also tried using bash but that did not work.

I am on Ubuntu 17.04.
I just finished installing using the README.

**Comment by jwilm** [comment]
You might want to try adjusting the `offset.y` property in the config

**Comment by JostCrow** [comment]
Thanks that works.
