### ISSUE TITLE
unhandled osc_dispatch caused by base16 color-scheme

### ISSUE THREAD

**Issue by Darksonn** [jwilm/alacritty#743]
The base16-ocean.dark color scheme causes the following message to be printed by alacritty.

    [unhandled osc_dispatch]: [['1','2',],['r','g','b',':','c','0','/','c','5','/','c','e',],] at line 801

**Comment by jwilm** [comment]
Hmm, there's a number of OSCs for setting colors we don't yet support. Docs: http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands

The message you're seeing is for "Change text cursor color" which we should be able to support pretty easily.
