### ISSUE TITLE
differences with rendering between xterm and alacritty / screen corruption with tmux + vim

### ISSUE THREAD

**Issue by hiciu** [jwilm/alacritty#745]
Hello,

I'm getting some kind of a screen corruption when using tmux with vim under alacritty. The same does happen with terminology terminal, but doesn't happen with xterm / urxvt / vte-based terminals.

The corruption looks like this:

![2017-08-21-230625_774x445_scrot](https://user-images.githubusercontent.com/1618371/29566757-3208da02-874b-11e7-88db-8dd7b9b852c3.png)

Few days ago I've opened issue with tmux project (tmux/tmux#1040) and tmux author has been very helpful in getting to the bottom of it. It is possible that there is an issue with alacritty's handling of "scroll regions" / "change_scroll_region" capability. Tmux author has come up with the test case that allows to reproduce the issue under alacritty, without tmux:

[xtest.txt](https://github.com/jwilm/alacritty/files/1242071/xtest.txt)

To execute it:

    clear; cat xtest.txt; sleep 100

Results under xterm:

![2017-08-22-150134_611x443_scrot](https://user-images.githubusercontent.com/1618371/29566735-23fa2e52-874b-11e7-8c39-a45f818dd7fb.png)

Results under alacirtty:

![2017-08-22-150131_777x533_scrot](https://user-images.githubusercontent.com/1618371/29566743-2814026a-874b-11e7-8ea1-ecc17fc7fe2f.png)

This may be related to #678. There is also tmux issue tmux/tmux#1040. I'll be happy to provide additional details.

I'm running alacritty version 471237d2ced1d1a07de06d832b2902efbc237df9 (`alacritty --versions` says 0.1.0) with mostly default configuration (I've changed only color scheme and shell) under linux.

**Comment by jwilm** [comment]
Thanks for the super detailed report! The bug should be fixed in #747. Would you mind trying that patch before we call it "fixed"?

**Comment by hiciu** [comment]
I just did. Alacritty built from fix-745 branch renders both tmux + vim and the test case correctly. Thank you very much!
