### ISSUE TITLE
Moving alacritty from or to a retina display change the font size

### ISSUE THREAD

**Issue by MarioAriasC** [jwilm/alacritty#754]
In OSX, if I move alacritty from or to a screen that isn't retina it messes up the font size. 

I suppose that is an issue with high-resolution displays

**Comment by asilvadesigns** [comment]
@MarioAriasC there are a few issues which exists related to this, see:
#625, #71

**Comment by jwilm** [comment]
Thanks @asilvadesigns 

Closing as duplicate of #71.
