### ISSUE TITLE
Access mapscii.me with telnet is all black.

### ISSUE THREAD

**Issue by ZWindL** [jwilm/alacritty#755]
Here's the `termite` 's result:
![screenshot_20170825_220041](https://user-images.githubusercontent.com/5116996/29717182-ba62df16-899d-11e7-85ff-3c96ca01ca57.png)
And here's the `alacritty` 's result, it can't show anything unless use mouse to select the text:
![screenshot_20170825_220114](https://user-images.githubusercontent.com/5116996/29717199-cb759c62-899d-11e7-8584-a4c35080ad63.png)
![screenshot_20170825_220131](https://user-images.githubusercontent.com/5116996/29717207-d65edfda-899d-11e7-96d7-04d484a81cc0.png)

**Comment by maximbaz** [comment]
What's the value of your $TERM? This works for me without problems, both with and without tmux.

**Comment by ZWindL** [comment]
@maximbaz It's `xterm-256color`

**Comment by chrisduerr** [comment]
This seems to work with the latest Alacritty master.
