### ISSUE TITLE
Alacritty opens as a tiny spec in a corner

### ISSUE THREAD

**Issue by jaseemabid** [jwilm/alacritty#758]
See the attached screenshot. I'm using the current master (b92ba65) on archlinux + gnome with the default config file. 

![screenshot from 2017-08-27 10-26-32](https://user-images.githubusercontent.com/601714/29747283-876b6a9e-8b12-11e7-96dd-88494f664512.png)

1. Window is a tiny spec in the top left corner
2. Title is 'Unknown'
3. Icons are broken 
4. No icons to maximise/minimize or close the window

**Comment by jwilm** [comment]
Is this under X or Wayland?

**Comment by jaseemabid** [comment]
Wayland

**Comment by jwilm** [comment]
You'll probably have a better experience using XWayland. Run with `env WAYLAND_DISPLAY= alacritty`.

**Comment by auscompgeek** [comment]
Luckily the window can be resized. Wonder why the window isn't being sized properly in the first place though.

**Comment by jaseemabid** [comment]
![screenshot from 2017-08-31 11-42-25](https://user-images.githubusercontent.com/601714/29908998-92d63846-8e41-11e7-9ebc-6e3f39d409d5.png)

@jwilm Interesting. Left side is wayland, right side with xwayland. Font sizes seems really different on both.

**Comment by jwilm** [comment]
@jaseemabid I believe winit doesn't detect high DPI on Wayland.

**Comment by jaseemabid** [comment]
Possibly. I'm using a Dell XPS 13" 1920x1080 display.

**Comment by chrisduerr** [comment]
Winit/Glutin has gotten some big updates since this issue was reported. I believe this should be fixed now by the new DPI mode. If this issue is still present, please let me know and I'll re-open.
