### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by krishicks** [jwilm/alacritty#766]
On Linux using i3 and alacritty built from 7d3fc0d with `rust 1.21.0-nightly (c11f689d2 2017-08-29)` I'm seeing random crashes.

I've returned to an i3 pane to see alacritty has disappeared; luckily (and obviously) I'm using tmux so no actual state was lost. So, it has nothing to do with what I'm doing within alacritty or tmux at the time of the crash as far as I can tell.

I did not have this issue with the last build of alacritty I was using, which was from 9b13e34.

I'd be happy to provide a crash log but I don't know where alacritty stores them.

**Comment by jwilm** [comment]
Thanks for reporting! Could you please try running Alacritty from a console like this:

```sh
RUST_BACKTRACE=1 alacritty
```

The backtrace should show up after crashing.

**Comment by krishicks** [comment]
I haven't been able to reproduce the crash since re-building it from the same SHA; if I get a stack trace I'll re-open.

Thanks!
