### ISSUE TITLE
'say' command hangs in alacritty

### ISSUE THREAD

**Issue by xyin96** [jwilm/alacritty#768]
When using the `say` command, alacritty hangs.

`say alacritty`

Which operating system does the issue occur on?
macOS Sierra (Version 10.12.2 (16C67))

**Comment by jacobthemyth** [comment]
FWIW, I'm on Version 10.12.6 (16G29) and `say alacritty` works fine.

**Comment by chrisduerr** [comment]
Tested on macOS and confirmed it to work great. Probably a `say` issue or it has been resolved since then.
