### ISSUE TITLE
Directional Keys Don't Function

### ISSUE THREAD

**Issue by mmstick** [jwilm/alacritty#77]
Basically, attempting to scroll up and down through history with the up/down keys or completing an auto-completion suggestion with the right direction key does nothing.

**Comment by kazimuth** [comment]
Have you installed your config file?

From the FAQ:

> *My arrow keys don't work* It sounds like you deleted some key bindings from your config file. Please reference the default config file to restore them.

**Comment by mmstick** [comment]
The application should generate the configuration file if no configuration file exists.

**Comment by basile-henry** [comment]
PR #74 is just for that 😄

**Comment by jwilm** [comment]
Default config is now written out. macOS has a default config which should have valid fonts. It's a bit hacky, but it should improve first impressions.
