### ISSUE TITLE
Fonts are fucked up

### ISSUE THREAD

**Issue by ivegotasthma** [jwilm/alacritty#771]
Which operating system does the issue occur on?
Ubuntu 16.06

If on linux, are you using X11 or Wayland?
X11, i3

[non tmux](https://i.imgur.com/0QYNQ4n.png)
[in tmux](https://i.imgur.com/GvWcWUi.png)

Here's the output:

```
asthma@work:~/public/git/alacritty$ cargo run --release
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/alacritty`
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
[Unhandled CSI] action='l', args=[1003], intermediates=[63]
[unhandled osc_dispatch]: [['1','1','2',],] at line 801
[unhandled osc_dispatch]: [['1','1','2',],] at line 801
[Unhandled CSI] action='l', args=[1005], intermediates=[63] 
```

I just cloned and compiled master with `cargo build --release`. I also just installed rust **but used the nightly channel** which didn't yield any errors. I started the binary with `cargo run --release`.

**Comment by virome** [comment]
I had an issue very similar to this while upgrading to a recent version after alacritty changed to the upstream winit.

Mine was solved by refreshing my config file with the latest from the repo.

Do happen to have an older config file floating around in one of the [configuration](https://github.com/jwilm/alacritty#configuration) paths?

**Comment by jwilm** [comment]
Looks like you need to update your `font.offset` and `font.glyph_offset` config. Try resetting both to zero.

Please refrain in the future from using profanities in your issue titles; it's not helpful or appreciated.
