### ISSUE TITLE
How do you get Alacritty to read your bash_profile?

### ISSUE THREAD

**Issue by idkjs** [jwilm/alacritty#772]
Which operating system does the issue occur on?
macOS Sierra
 I have `export PATH="$HOME/.cargo/bin:$PATH"` in ~/.bash_profile but still have to run source ~/.bash_profile to get settings read. Obviously, this is not the way to do it but I cant seem to find the answer anywhere.  I have reread and researched. Obviously missing something. Thanks for the help.

**Comment by NickeZ** [comment]
Maybe if you give bash the `-l/--login` args?

**Comment by idkjs** [comment]
Do you mean to uncomment the shell config in alacritty.yml like this:
 ```sh
# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
#shell:
program: /bin/bash
 args:
   -l/--login
```

Above did not work. It just kinda tries to pop open i guess looking for a login. Same result when the default is uncommented:
```sh
#shell:
 program: /bin/bash
  args:
- --login
```

**Comment by jwilm** [comment]
@idkjs The shell is responsible for reading your `.bash_profile`, not Alacritty.

That said, both of the code snippets you provided look incorrect. Try this instead:

```sh
 program: /bin/bash
  args:
    - --login
```

If you're still having issues after that, I would recommend checking [this stackoverflow answer](https://askubuntu.com/a/121075).

**Comment by idkjs** [comment]
Thank you @jwilm.

Followed your link. Did some research. Ended up by creating a `~/.bashrc` file which I was not using and sourcing the previous `~/.bash_profile`, exactly as you said. Working now.

`~/.bashrc`
```sh
# Source bash_profile so that alacritty could access it
source ~/.bash_profile
```

**Comment by mtrovo** [comment]
@idkjs 
Just for future reference I had the same problem and you had a small typo on your solution.

Instead of:
``` yaml
#shell:
 program: /bin/bash
  args:
- --login
```

You need to edit as:
``` yaml
shell:
  program: /bin/bash
  args:
    - --login
```

**Comment by mjjmjjmjj** [comment]
Adding to this as I had issues with parts of my bash setup

Config file:
```toml
[shell]
program = "/usr/bin/bash"   # Use the command `whereis bash` to verify the location of your bash executable
args = ["-l"]
```

Logon file:
```bash
export TERM=xterm-256color
```

I didn't get colors until I ran `export TERM=xterm-256color` (which is also useful for compatibility with things like vim).  I put this inside my `.bashrc` just after the section labeled `if not running interactively, don't do anything`, (putting it inside `.bash_aliases` didn't work until `.bashrc` was sourced again, it likely ought to be executed earlier on) and things worked just as expected.
