### ISSUE TITLE
servo-fontconfig-sys needs an update

### ISSUE THREAD

**Issue by lukaslueg** [jwilm/alacritty#773]
Fedora 26 moved to glibc 2.25 which has names colliding with fontconfig. I have not been able to compile alacritty for weeks now, since we are stuck on the internal fork of the fontconfig crates.

> /home/lukas/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/src/fcmatch.c:284:63: error: 'PRI_CHAR_WIDTH_STRONG' undeclared here (not in a function); did you mean 'PRI_WIDTH_STRONG'?
>  #define FC_OBJECT(NAME, Type, Cmp) { FC_##NAME##_OBJECT, Cmp, PRI_##NAME##_STRONG, PRI_##NAME##_WEAK },
>                                                                ^
> /home/lukas/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/src/fcobjs.h:54:1: note: in expansion of macro 'FC_OBJECT'
>  FC_OBJECT (CHAR_WIDTH,  FcTypeInteger, NULL)
>  ^~~~~~~~~
> /home/lukas/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/src/fcmatch.c:284:84: error: 'PRI_CHAR_WIDTH_WEAK' undeclared here (not in a function); did you mean 'PRI_WIDTH_WEAK'?
>  #define FC_OBJECT(NAME, Type, Cmp) { FC_##NAME##_OBJECT, Cmp, PRI_##NAME##_STRONG, PRI_##NAME##_WEAK },
>                                                                                     ^
> /home/lukas/.cargo/git/checkouts/libfontconfig-3d5e920c02c2e53f/618a529/src/fcobjs.h:54:1: note: in expansion of macro 'FC_OBJECT'
>  FC_OBJECT (CHAR_WIDTH,  FcTypeInteger, NULL)

**Comment by da-x** [comment]
Saw the same problem under Fedora 26 and submitted a pull request, here: https://github.com/servo/libfontconfig/pull/33

**Comment by da-x** [comment]
My pull request in servo/libfontconfig was accepted. @jwilm you can sync to them or take just two commits to your fork of libfontconfig from https://github.com/da-x/libfontconfig/commits/for-jwilm

**Comment by jwilm** [comment]
Should be fixed on master. Thanks @da-x!
