### ISSUE TITLE
Couldn't find a font with name 'monospace' and style 'slant=Normal, weight=Normal'

### ISSUE THREAD

**Issue by kazimuth** [jwilm/alacritty#78]
```
> target/release/alacritty 
device_pixel_ratio: 2
device_pixel_ratio: 2
width: 2048, height: 1502
Initializing glyph cache
Alacritty encountered an unrecoverable error:

	Couldn't find a font with name 'monospace' and style 'slant=Normal, weight=Normal'
```

OS X El Capitan

This seems fairly odd, because I definitely have monospace fonts on my system. I do have extra fonts installed... somehow, that might have something to do with it?

**Comment by basile-henry** [comment]
In your config file replace the default font *monospace* by something you have on your system. If you're on macOS try *Menlo*

**Comment by kevinburke** [comment]
It would be nice if the config file supported a comma-separated list of font names, like CSS.
