### ISSUE TITLE
Text background always black

### ISSUE THREAD

**Issue by vorner** [jwilm/alacritty#780]
Hello

I'm getting some strange behaviour on some of my computers and not on others. I don't know what the difference is, though. On the broken systems, the cells that have characters in them always have black background, no matter what color is set in the configuration.

The way to reproduce:

1. Start with the default configuration file
2. Set the colors.primary.background to (for example) '0xff0000'
3. Start alacritty and type something ‒ for example `ls -l`

What I get (on some computers) is red background on the blank cells and black background with the occupied ones. See the attached screenshot.

What I think I should get is red background even in the occupied cells.

Any idea what may be the cause or why it happens on some machines and not on others? Something I can try? Is it possible there's some cache that is broken?

Which operating system does the issue occur on?

```
Linux basilisk 4.11.0-basilisk #1 SMP Tue May 9 20:58:27 CEST 2017 x86_64 Intel(R) Celeron(R) CPU N2940 @ 1.83GHz GenuineIntel GNU/Linux
```

If on linux, are you using X11 or Wayland?

X11.

![color](https://user-images.githubusercontent.com/11783500/30240375-98fcd146-956f-11e7-85d7-b458dde97db1.png)

**Comment by jwilm** [comment]
Could you please run Alacritty with `-vvv`, repro this, and share the log? This seems more likely to be an issue with your shell than Alacritty.

**Comment by vorner** [comment]
Here's the log.

Anyway, I'm not sure about the shell. I have the exact same setup on all the computers, even the ones that work. And I get the problems even when I run eg. vim inside alacritty without shell (`alacritty -e vim`).

[log.txt](https://github.com/jwilm/alacritty/files/1290025/log.txt)

**Comment by vorner** [comment]
Here's a log from when it works, for comparison. To me it looks pretty much the same ‒ the background colour is never set, only the foreground ones and resets.

[ok.txt](https://github.com/jwilm/alacritty/files/1291667/ok.txt)

**Comment by vorner** [comment]
Hmm, I found the problem. I had an older copy of the alacritty binary from before and it was sooner in the path. My guess is the old binary didn't run well with new shaders, or something like that.

I must therefore apologize for the invalid report.
