### ISSUE TITLE
Set $TERM_PROGRAM and $TERM_PROGRAM_VERSION by default

### ISSUE THREAD

**Issue by chhschou** [jwilm/alacritty#781]
os: ubuntu 16.04

Many terminal emulator sets $TERM_PROGRAM and $TERM_PROGRAM_VERSION by default or $VTE_VERSION if VTE based. Settings this helps Alacritty integrate with other tools.

**Comment by jonas-schievink** [comment]
> Many terminal emulator

Which ones? Termite doesn't. There's `$TERM`, which probably does the same thing as `$TERM_PROGRAM` with the difference of being more widespread. I can't imagine any use for a `$TERM_PROGRAM_VERSION` variable except for user information, which is usually accomplished via a command line flag like `-v`. For anything else, there's terminfo.

**Comment by chhschou** [comment]
iTerm2.app, Apple Terminal and Hyper does set these env variables.

I had a look at terminfo through `infocmp` but it doesn't tell me anything unique about Alacritty. The tool I'm working on is changing cursor shape in vim (via vimscript). I would be happy if there is something that says `alacritty` or something that uniquely identifies it so I can trigger the desired behaviour.

**Comment by NickeZ** [comment]
I think best practice is to look for if the terminal implements the features you require. That information should be in terminfo. Otherwise you might want to add it there.

**Comment by rafi** [comment]
Great feature request! Neovim, among others, use these environment variables, e.g.
[neovim/neovim/blob/f050aaab/src/nvim/tui/tui.c#L206-L211](https://github.com/neovim/neovim/blob/f050aaabbb31b58ebac519a6f7014610f2b119f0/src/nvim/tui/tui.c#L206-L211) to address capabilities and bugs.

**Comment by DarkDefender** [comment]
@rafi If possible, neovim uses the info from that is provided in termcap/terminfo to see what the terminal supports.

Sadly many terminals lie and says that they are xterm but do not support all the features xterm does. It has gotten better recently, so there are only a few cases where neovim has to work around this by looking for non standard env variables. (Or make sure that the terminal really IS xterm)

As we can see from neovim, the only terminal that is detected via `$TERM_PROGRAM` is iTerm. So I do not think this method is that widely adopted. The other env variables are for konsole and libvte terminals.

**Comment by chhschou** [comment]
Okay I'll have a look at neovim and see what I can pick out thanks.

**Comment by chenull** [comment]
Hm.. is this feature request can be opened again ? although not a standard, many terminal emulators on macOS did this. My use case is to detect if alacritty is in used, then it will launch `tmux`, since no tabs in alacritty, it is my preference though. This is an example `~/.zshrc`:

```
if [ "$TERM_PROGRAM" != "Apple_Terminal" ] && [ "$TERM_PROGRAM" != "iTerm.app" ]; then
    [[ $- != *i* ]] && return
    [[ -z "$TMUX" ]] && exec tmux
fi
```

this will be easily readable:

```
if [ "$TERM_PROGRAM" = "Alacritty" ]; then
    [[ $- != *i* ]] && return
    [[ -z "$TMUX" ]] && exec tmux
fi
```


taken from [here](https://wiki.archlinux.org/index.php/Tmux#Start_tmux_on_every_shell_login)
