### ISSUE TITLE
Font size varies based on discrete vs embedded graphics

### ISSUE THREAD

**Issue by spease** [jwilm/alacritty#783]
See attached screenshots. Taken on a Lenovo W530 with integrated (small) vs discrete (large) graphics settings in the BIOS. AFAIK NVIDIA Optima is not well-supported on Linux (to switch between the two).

Let me know what additional debugging info is needed.

![alacritty_small](https://user-images.githubusercontent.com/2825204/30509160-600074a8-9a5e-11e7-844a-4eb3c6974baa.jpg)
![alacritty_large](https://user-images.githubusercontent.com/2825204/30509161-6000e500-9a5e-11e7-9df0-ef886b398e4b.jpg)

**Comment by chrisduerr** [comment]
Since glutin/winit recently made a major change to how font size works, this is likely not accurate anymore.

If this should still be present, please comment and I'll re-open the issue.
