### ISSUE TITLE
mouse selection behavior

### ISSUE THREAD

**Issue by benoit-pierre** [jwilm/alacritty#784]
The current behavior for a simple click selection, from left to right, is to only select the first cell character if the click occurred on the left side of said cell. This is not how other terminal works (xterm, rxvt, ...). It's also at odd with the way the selection work when it's handled by a terminal application with mouse support (like vim). It would be great if this was at least configurable.

Here's the patch I'm currently using:
```diff
 src/selection.rs | 34 +++++-----------------------------
 1 file changed, 5 insertions(+), 29 deletions(-)

diff --git c/src/selection.rs i/src/selection.rs
index 714c84c..63ee2be 100644
--- c/src/selection.rs
+++ i/src/selection.rs
@@ -264,35 +264,11 @@ impl Selection {
             return None;
         }
 
-        Some(match (front_side, tail_side) {
-            // [FX][XX][XT]
-            (Side::Left, Side::Right) => Span {
-                cols: cols,
-                front: front,
-                tail: tail,
-                ty: SpanType::Inclusive
-            },
-            // [ F][XX][T ]
-            (Side::Right, Side::Left) => Span {
-                cols: cols,
-                front: front,
-                tail: tail,
-                ty: SpanType::Exclusive
-            },
-            // [FX][XX][T ]
-            (Side::Left, Side::Left) => Span {
-                cols: cols,
-                front: front,
-                tail: tail,
-                ty: SpanType::ExcludeTail
-            },
-            // [ F][XX][XT]
-            (Side::Right, Side::Right) => Span {
-                cols: cols,
-                front: front,
-                tail: tail,
-                ty: SpanType::ExcludeFront
-            },
+        Some(Span {
+            cols: cols,
+            front: front,
+            tail: tail,
+            ty: SpanType::Inclusive
         })
     }
 }
```

**Comment by louwers** [comment]
Agreed. This behavior should be consistent with other terminal emulators.

To demonstrate the issue, I created a screen recording of selection in vim, first GNOME terminal, then Alacritty.

![Screen recording](https://user-images.githubusercontent.com/649392/30976872-3d16cbc8-a476-11e7-8743-13740f847808.gif)

**Comment by benoit-pierre** [comment]
@louwers: this is a different issue.

**Comment by louwers** [comment]
@benoit-pierre I created a seperate issue for it! 👍

**Comment by chrisduerr** [comment]
I think this is the standard behavior for VTE-based terminal emulators and generally most text-editing software. The main reason why terminal applications don't do it this way is probably because they only receive cell-based locations so they simply don't know where the cursor is (left or right side).

Is this still a feature you're interested in @benoit-pierre? And does anyone else have interest in a config-option that would allow this? I feel like adding a config option for this might require a bit of code for very little gain.

**Comment by chrisduerr** [comment]
Closing this for now because it seems the main driving force behind this request does not exist anymore.
