### ISSUE TITLE
Htop rendering with missing text

### ISSUE THREAD

**Issue by AlexNPavel** [jwilm/alacritty#786]
Operating System: openSUSE Tumbleweed and Arch Linux

X11/Wayland: Occurs on both X11 and Wayland on both OSes

Running on commit eb231b3e70b87875df4bdd1974d5e94704024d70 built with Rust 1.20.0, I have graphical issues in htop. Specifically, CPU percentages, RAM usage, and occasionally users do not appear (users appear if I select their row).
Image:

![Broken htop rendering](https://i.imgur.com/BDUez9z.png)
Note: All instances of user `alex` appear in the screenshot above, but all other users are invisible unless selected.

**Comment by jwilm** [comment]
This is almost certainly a colorscheme issue.
