### ISSUE TITLE
Strange issue with Fish shell and Neovim

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#787]
Issue occurs on Mac OS.

**Issue - Disclaimer : )**
I realize this may not be Alacritty's fault, I'm simply trying to narrow down my options. That being said, I'm starting here because I only notice this while using Alacritty.

**Issue - You should know...**
I have Fish set as shell for Alacritty within `alacritty.yml` and for Neovim within `init.vim`:

**Issue - What happens...**
If I launch neovim from fish, then quit Alacritty, I can no longer open neovim.

**Issue - Step by step**
1. I launch Alacritty
2. I type `nvim`
3. I quit Alacritty
4. I relaunch Alacritty
5. I type `nvim`
6. just hangs... ultimately pressing `ctrl-c` to kill it

**Issue - Additional details**
After the above step by step, neovim won't work in *iterm* or *terminal*.
Also *bash* and *zsh* won't work either.

**Issue - Temp solution**
I have to restart my machine. : (

I'll be creating an issue on Fish repo as well but, thought to start there.
I'd really appreciate any help, thanks.

**Comment by lukaslueg** [comment]
I understand that you close Alacritty while nvim is still running?

Can you get a trace of the hanging session using `strace -f alacritty -e bash exit 2>alacritty.log` ? A new alacritty-windows should pop up briefly and immediately close again, given that it does not in fact hang; kill it with fire if it does.

**Comment by asilvadesigns** [comment]
That is correct.

I'm getting `strace command not found`.. I'm on mac os, is there a dtrace alternative maybe..?

**Comment by asilvadesigns** [comment]
I think I fixed it...

I did:
```
$ brew uninstall neovim
$ brew cleanup
$ brew update
$ brew install --verbose --build-from-source neovim
```

and I'm not seeing the issue anymore... hmmm weird...

**Comment by asilvadesigns** [comment]
nope. Issue still exists upon restart.

**Comment by asilvadesigns** [comment]
As I've continued to test, this occurs in all terminal emulators, creating issue in Neovim issues here: https://github.com/neovim/neovim/issues/7300

**Comment by jwilm** [comment]
Thanks for chasing that down and determining it wasn't an Alacritty issue :D.

**Comment by asilvadesigns** [comment]
Np! : )
