### ISSUE TITLE
Keychords randomly not working under high load

### ISSUE THREAD

**Issue by rroohhh** [jwilm/alacritty#789]
This issue occurs under linux with X11.

When my system is under high load (e.g. compiling) some keychords seem to be
randomly ignored. This occours only with atleast two modifiers at the same time (I use `Meta-Shift-l` /  `Meta-Shift-h` to switch windows in tmux). Using less modifiers (`Ctrl-b n`/ `Ctrl-b p`) seems to work fine. The process generating the high load needs to be running as root for this issue to occur.

**Step by Step**
1. Add these lines to `.tmux.conf` and reload tmux (or use the tmux prompt)
   `bind -n M-H previous-window`
   `bind -n M-L next-window`
2. run `sudo stress --cpu NUM_CORES --timeout 60 &`
3. Open some tmux windows and try to switch windows in tmux with `Meta-Shift-h` and `Meta-Shift-l`

Doing the same in `xterm` or `urxvt` is working fine.
I'm using alacritty built from [this](https://github.com/jwilm/alacritty/commit/b92ba65f97ec484ac5df0c3b5b3d62667ca43f2a) commit.

**Comment by chrisduerr** [comment]
This issue is quite old, but if it's still present it would be interesting to see if the keys are correctly reported when using `alacritty --print-events`.

**Comment by chrisduerr** [comment]
Closing since there hasn't been any update in over a year. If someone should still experience it, please let me know and I'll re-open this issue.
