### ISSUE TITLE
Alacritty fails to start: GL context creation failed

### ISSUE THREAD

**Issue by sbidin** [jwilm/alacritty#79]
Alacritty crashes immediately upon startup:

```
$ target/release/alacritty       
Alacritty encountered an unrecoverable error:

	Error creating glutin::Window; GL context creation failed
```

I'm on Arch Linux, compiled manually via `cargo`, no compilation issues.

**Comment by jwilm** [comment]
Are you able to run `glxgears`?

**Comment by sbidin** [comment]
No, `glxgears` fails.

It appears this is an issue on my end. Sorry for the noise!

**Comment by jwilm** [comment]
No problem :). I appreciate that `glxgears` is available for such tests.
