### ISSUE TITLE
[Request] Change cursor when windows lose focus.

### ISSUE THREAD

**Issue by dimascyriaco** [jwilm/alacritty#794]
This is a small quality of live suggestion.

I use a two monitor setup, and was used to relying on the 'hollow/full' cursor to find out what window is focused. But with Alacritty i find myself typing on the wrong window all the time, because I look at the cursor and it's full so I think the window is focused.

Well, maybe I'm just dumb.

**Comment by unphased** [comment]
Subscribe to #937 😊

**Comment by chrisduerr** [comment]
This has been implemented with #937. :)
