### ISSUE TITLE
Graphics glitches

### ISSUE THREAD

**Issue by noughtmare** [jwilm/alacritty#795]
Which operating system does the issue occur on?
Arch linux

If on linux, are you using X11 or Wayland?
X11

Using arm to monitor my tor relay causes major graphics glitches:

All the bars should be solid
![image](https://user-images.githubusercontent.com/2665074/30922819-8c5afeec-a3aa-11e7-9f68-58a81fc6fac5.png)

![image](https://user-images.githubusercontent.com/2665074/30922842-997e86fc-a3aa-11e7-8637-7c6ede17cf75.png)

Screenshot of the correct behaviour in urxvt:
![image](https://user-images.githubusercontent.com/2665074/30922951-efb13e7a-a3aa-11e7-9874-d25d4bdf49cf.png)

**Comment by jwilm** [comment]
What's the application?

**Comment by noughtmare** [comment]
[arm](https://www.torproject.org/projects/arm)

**Comment by Aaron1011** [comment]
@noughtmare: I can't seem to reproduce this with the latest `arm` and `alacritty`. Are you using the latest version of both?

**Comment by noughtmare** [comment]
@Aaron1011 I have just updated alacritty to master, and I'm using arm version 1.4.5.0 (I see now that it was released in 2012, but that is the latest version pacman offers)

I get:
```
[Unhandled CSI] action='b', args=[6], intermediates=[]
[Unhandled CSI] action='b', args=[6], intermediates=[]
[Unhandled CSI] action='b', args=[6], intermediates=[]
...
```
And then the screen goes blank very quickly and then the graphics glitches start. In urxvt the screen also goes about every five seconds, but no graphics glitches happen.

**Comment by noughtmare** [comment]
I have noticed now that it is less noticable after the upgrade, because it fixes itself very quickly and the `[Unhandled CSI]` are less common it seems, but it is still noticable.

**Comment by jonhoo** [comment]
This kind of glitching also happens with the top of the bars in [`cpubars`](https://github.com/aclements/cpubars).

**Comment by jbg** [comment]
I also get this consistently with `mutt` on latest master. The inverse-color bars for the top and bottom bars in mutt, and for the selected message, are no longer the full width of the screen but instead only reach to the end of the text on that line.

I get this output:
```[Unhandled CSI] action='h', args=[1034], intermediates=[63]
[unhandled osc_dispatch]: [['1','0','4',],] at line 801
[Unhandled CSI] action='b', args=[113], intermediates=[]
[Unhandled CSI] action='b', args=[107], intermediates=[]
[Unhandled CSI] action='b', args=[103], intermediates=[]```

**Comment by jbg** [comment]
I'm not sure what CSI ?1034 is supposed to be, as it doesn't seem to appear in my usual resource for ANSI (http://bjh21.me.uk/all-escapes/all-escapes.txt). But CSI action 'b' means "repeat previous char" which explains the corrupted bars in `mutt` and other programs. This action appears to be unimplemented in `csi_dispatch` in `ansi.rs`.
