### ISSUE TITLE
Include binaries into releases

### ISSUE THREAD

**Issue by buger** [jwilm/alacritty#80]
Hello!

Nice stuff, but I'm too lame to install Rust. Do not blame me to fast :)

Getting all the development environment to work is damn hard, and you are missing a lot of potential users. Since you are using Rust, it should be straightforward to provide precompiled binaries.

Best wishes, thank you!

**Comment by jwilm** [comment]
Yep, this will happen in the future. Going to leave this open since there isn't already an issue about it.

**Comment by Jarred-Sumner** [comment]
+1 would be great to have binaries to download

Additionally, for macOS users - some way to install via Homebrew would be great, too. Either in the form of:
`brew install alacritty` or a cask (`brew cask install alacritty`)

**Comment by jwilm** [comment]
@Jarred-Sumner thanks for the recommendation about brew! I'll be sure to look into it.

**Comment by AlJohri** [comment]
- 👍  to binary releases via github releases (https://help.github.com/articles/creating-releases/)
- 👍  to brew cask (example casks using github release: https://github.com/caskroom/homebrew-cask/blob/master/Casks/hyper.rb)

**Comment by cema-sp** [comment]
I've created a temporary [brew formula](https://github.com/cema-sp/homebrew-tap/blob/master/Formula/alacritty.rb) (could not be merged into homebrew until stable binary release).
Install it with: `brew install --HEAD cema-sp/homebrew-tap/alacritty`

**Comment by acornejo** [comment]
Should be possible to hookup travis to do the releases for you

https://docs.travis-ci.com/user/deployment/releases/

**Comment by monouser7dig** [comment]
**any news on making release builds available and distribute through homebrew?**
I'm actually using Alacritty daily for some time now and works really well together with tmux.
But doing git and rust is not for everyone so I think it is about time to give travis some more stuff to do for us, compile releases 👍 
**great work guys, thanks**

**Comment by jitendravyas** [comment]
@cema-sp 

I get this `Error: Could not find 'cargo' installation dir neither in CARGO_HOME nor in HOME`

**Comment by AlJohri** [comment]
@cema-sp I got the same error as @jitendravyas

**Comment by jo-m** [comment]
Hi all
I have set up an automatic build/release in my fork of the repo: https://github.com/jo-m/alacritty/releases

It only works for MacOS at the momen (I removed the Linux build from the .travis-ci file). Would be easy to add for Linux though.

**Comment by jasonm23** [comment]
@cema-sp any chance of turning that formula into a tap?

**Comment by jasonm23** [comment]
@cema-cp no worries, found this:

    brew tap mscharley/homebrew

**Comment by omaryoussef** [comment]
Any news on this? It sucks we need a full Rust dev environment to get it working :(

**Comment by jasonm23** [comment]
@jo-m are those releases coming back? The release page was empty.

**Comment by kuntau** [comment]
A quick bump.. any news on this? 🙌

**Comment by johnlunney** [comment]
This is definitely a blocker to adoption for some folks :)

**Comment by nixpulvis** [comment]
Are we planning on building specific versions only, or building every master (automatically, i.e. Travis or something) and simply tagging some for clean version releases?

**Comment by chrisduerr** [comment]
I'd say whenever a specific commit is tagged with a version travis should automatically push it to the github releases. That's pretty easy to do and makes the most sense to me.

**Comment by nixpulvis** [comment]
... and someone to write the release notes 😜

**Comment by chrisduerr** [comment]
I think once we actually have proper versions we should maintain a changelog in the project root. This should be updated whenever a commit is tagged with a version and then it can be copied to the releases either manually or automatically.

I don't know how we would easily automate this through travis right now though, so manually would probably be a good first step.

**Comment by monouser7dig** [comment]
FWIW I was able to build macOS version in this [docker container](https://github.com/hone/docker-rust-cross)

**Comment by chrisduerr** [comment]
That's nice, but since we're already running travis on macos, I don't think we'd need to cross-compile.

We could just export the binaries from travis.

**Comment by andradei** [comment]
Would be nice to have a 0.1 Release with binaries available, indeed. Making a Homebrew formula with a binary available would be easy too.

**Comment by fishhead108** [comment]
Hi, @jwilm!
Is there some tracker or wiki where we could review the plans and progress of this issue?
I'd like to help but want to avoid double work.

If I understood correctly you plan to distribute on this platforms:
- [x] Arch Linux (done)
- [ ] Debian\Ubuntu
- [ ] Fedora
- [ ] CentOS/RHEL 7
- [ ] openSUSE
- [ ] Slackware
- [ ] Void Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Solus
- [ ] NixOS/Nixpkgs
- [ ] Gentoo
- [ ] Cargo
- [ ] MacOS
- [ ] Windows 

Should I create separate issues for each distro (for easier checks and MR)?

**Comment by nirfse** [comment]
It would be great if Flatpak (and maybe both AppImage and Snap) packages were supported at early stage, since they're platform/distro agnostic.

**Comment by chrisduerr** [comment]
@fishhead108 This issue is mainly about tracking the progress on releasing github binaries which get automatically built with travis, rather than Alacritty in repositories.

There is the #alacritty IRC on freenode if you have any questions, usually questions there should be answered fairly quickly, if you don't wish to open an issue here.

Some of the platforms you've listed already support Alacritty (see README), however it is up to the maintainers of the specific distribution to create packages for Alacritty.

**Comment by sandangel** [comment]
any update on this?

**Comment by jwilm** [comment]
> any update on this?

No.

**Comment by chrisduerr** [comment]
Tagged releases will now automatically produce binaries through travis.
