### ISSUE TITLE
Black screen with no output on OS X 10.10.2

### ISSUE THREAD

**Issue by annacrombie** [jwilm/alacritty#802]
System: OS X 10.10.2

Everything compiled with no errors, and on first and all subsequent executions the app launched with a black screen and nothing else.
The config file is in place
I used the right rust compiler (specified in the readme)

**Comment by chrisduerr** [comment]
Is this issue still present with the latest master?

**Comment by annacrombie** [comment]
No, I just checked and everything works fine, but since I opened this issue I have upgraded to macOS 10.13.3 so I can't confirm it is fixed for 10.10.2.
