### ISSUE TITLE
`reset` does not properly reset the terminal

### ISSUE THREAD

**Issue by gyscos** [jwilm/alacritty#804]
On Archlinux, running X11.
After printing some random binary data to stdout (literally ran `cat /dev/urandom`), terminal is messed up. In most other terminals, the command `reset` is enough to bring back the terminal to a usable state; but it doesn't appear to work in alacritty.

To reproduce:

* Prints 10MB random binary data to stdout:
```
 head -c 10MB /dev/urandom
```
* Observe messed up terminal (if not, repeat previous step).
* Press `Ctrl-C` to discard messed-up input prompt.
* Enter the `reset` command (blindly since terminal is messed up).
* Observe alacritty clearing the screen for a second, then showing a prompt again, still in messed up mode.

![screenshot from 2017-09-29 22-58-27](https://user-images.githubusercontent.com/564903/31043031-b23445c2-a569-11e7-96be-44250fa993fb.png)

Tested running bash and zsh.

Note: I remember other terminals getting messed up like that quite often by binary data being printed out, but strangely can't reproduce it on gnome-terminal, konsole, xfce4-terminal or even xterm - they all remain normal after printing such data... Not sure what changed.

The good thing is alacritty is definitely the fastest terminal to print this 10MB of data :)

**Comment by maximbaz** [comment]
> Note: I remember other terminals getting messed up like that quite often by binary data being printed out, but strangely can't reproduce it on gnome-terminal, konsole, xfce4-terminal or even xterm - they all remain normal after printing such data... Not sure what changed.

If I run your command inside tmux, nothing is getting messed up, even in alacritty, only "raw" alacritty is affected - could it be that the other terminals you tried were also running tmux?

**Comment by gyscos** [comment]
No, all terminals were directly running bash or zsh (both were tested).

**Comment by jwilm** [comment]
This is probably because we don't reinitialize the `vte::Parser`; should be an easy fix.
