### ISSUE TITLE
Transparency affects all background colors

### ISSUE THREAD

**Issue by haarp** [jwilm/alacritty#807]
Linux, X11

Hey! When transparency is enabled, it affects every background color. Other terminal emulators have it apply only to the "background" of the terminal, but have custom background colors appear at 100% still.

See screenshots. How it should be (transparency disabled entirely):
![screenshot_2017-10-02_21-46-23](https://user-images.githubusercontent.com/781030/31096217-b32d6fe0-a7bb-11e7-845d-f2f3d9c9726c.png)

What alacritty does with transparency enabled:
![screenshot_2017-10-02_21-49-55](https://user-images.githubusercontent.com/781030/31096234-c0c82352-a7bb-11e7-90d1-88ff04dcbcc0.png)

**Comment by Javyre** [comment]
I'm pretty sure this is now fixed in #847 (merged yesterday)

**Comment by haarp** [comment]
Yes, indeed. Thanks!
