### ISSUE TITLE
Feature request: zoom in/out/reset

### ISSUE THREAD

**Issue by infokiller** [jwilm/alacritty#809]
This is critical for my workflow with terminator and tmux.
I think that if this will be supported, I'll be able to start making the switch

**Comment by lord-re** [comment]
What are you talking about ? 
tmux in alacritty : i can zoom in tmux. It's a tmux feature so any terminal would work.
Alacritty can't split like terminator, so you won't have a zoom like in tmux natively in alacritty. 

Or you just want to zoom on characters to make them bigger ?

**Comment by infokiller** [comment]
I mean to dynamically increase/decrease font size. 
Can this be done in tmux? If so, this issue can indeed be closed.

**Comment by lord-re** [comment]
There is a Push Request pending 625.

**Comment by sodiumjoe** [comment]
I believe this was fixed by https://github.com/jwilm/alacritty/pull/625 and can be closed.

**Comment by jwilm** [comment]
Thanks @sodiumjoe.
