### ISSUE TITLE
Add option to disable dynamic title

### ISSUE THREAD

**Issue by Iambecomeroot** [jwilm/alacritty#816]
Which operating system does the issue occur on?
Linux Hermes 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux

If on linux, are you using X11 or Wayland?
X11

Termite has a great feature that allows you to disable dynamic title:
```
dynamic_title = false
```

It would be great to have such a feature in alacritty. Otherwise, for me the title will stay `tmux`. Another nice option would be to be able to set the title. I would like to set it to `terminal`.

**Comment by voider1** [comment]
I'd like to contribute to Alacritty and I'll look into this, seems like a good entrypoint.

**Comment by voider1** [comment]
I've made a PR, see #819.

**Comment by maximbaz** [comment]
PR is merged, this can be closed :+1:

**Comment by jwilm** [comment]
Thanks @maximbaz
