### ISSUE TITLE
Crashes on macOS High Sierra

### ISSUE THREAD

**Issue by avjinder** [jwilm/alacritty#818]
Screen freezes, then glitches out. Reboots the computer.

I believe this has something to do with the fact that High Sierra is using Metal2.

**Comment by monouser7dig** [comment]
yes
tremendous crash haha 

just after the latest [commit](https://github.com/jwilm/alacritty/commit/e17d38167e174a2cf664e430fe968ec6492e1f08)

worked perfectly fine before

**Comment by jwilm** [comment]
@monouser7dig also on mac?

**Comment by monouser7dig** [comment]
yes macOS 10.13 (17A405)

**Comment by jwilm** [comment]
The commit has been reverted on master; going to leave this open as tracking issue.

**Comment by monouser7dig** [comment]
maybe test the lib updates alone

**Comment by jwilm** [comment]
Would one of you mind trying this PR? https://github.com/jwilm/alacritty/pull/811

It's strictly a lib update for latest winit/glutin (among other things).

**Comment by jwilm** [comment]
Thanks!

**Comment by chetgurevitch** [comment]
@jwilm I just noticed #811 breaks shift+tab for some reason, so we should hold off on merging it. Also let's get @vberger in the loop here.

**Comment by chetgurevitch** [comment]
Shift+tab is also broken in #815. Seems like an upstream bug @vberger.

**Comment by vberger** [comment]
Well, I *think* the macos crash is linked to way I changed resize code, sorry for that. 😕 (the other part of my PR only touched linux specific code).

Though it's quite surprising to it seems to crash the entire graphic driver?

**Comment by vberger** [comment]
@chetgurevitch 

> Scratch that, still happens w/ winit 0.8.1. Reproducable across xorg and wayland using gnome 3.26. Investigating tomaka/winit#274.

The "breaking shift-tab" occurs with wayland using Xwayland, or with native wayland? Because this PR only touches X11 code...

**Comment by chetgurevitch** [comment]
@vberger That issue was introduced by the winit update itself. https://github.com/tomaka/winit/pull/308 will fix it so it's all good.

**Comment by vberger** [comment]
Well, I'm still puzzled at the fact that all this only touches X11-specific code. So I guess my question is: "Is shift-tab broken with the native wayland winit backend, or only with X11?".

**Comment by chetgurevitch** [comment]
@vberger Sorry I understand what you're saying now, seems like that issue was always present on wayland. I just submitted https://github.com/tomaka/winit/pull/314 to address it there too.

**Comment by avjinder** [comment]
@jwilm I built it again, and it works perfectly now. I believe it's okay to close the issue now. Any others still having this issue?

**Comment by chetgurevitch** [comment]
@avjinder The offending change was reverted in master but we'll want to merge those changes or something similar sooner or later, so probably best to leave this open for now.

**Comment by vberger** [comment]
Yes. Actually the changes of my PRs should probably be handled by winit/glutin. I was just trying to provide a quick fix to ease the wayland story here until the issue was solved winit/glutin-side.

I guess it was not much of a fix actually 😅

**Comment by chrisduerr** [comment]
Is this still relevant? It has been a while.
