### ISSUE TITLE
Add support for Backtick and Tilde key binding

### ISSUE THREAD

**Issue by bugeats** [jwilm/alacritty#821]
As far as I can tell, there's no config objects for Backtick or Tilde keys here:

https://github.com/jwilm/alacritty/blob/master/src/config.rs#L1539

I would like to be able to use these very convenient left-hand key bindings.

**Comment by jwilm** [comment]
For backtick, you'll want `Grave`, and for tilde, you'll want `Grave` with a `Shift` modifier. Please lmk if that works for you.

**Comment by bugeats** [comment]
Yep that works. Thanks.
