### ISSUE TITLE
Make alacritty into a library, in order to embed it into other applications?

### ISSUE THREAD

**Issue by fschutt** [jwilm/alacritty#823]
I've thought about making a more user-friendly wrapper using alacritty as a base framework. Basically, like gnome-terminal, with a graphical configuration, system menus and so on. However, I want to respect alacrittys mission to be only a "basic" terminal emulator and not have these features.

So my proposed solution would be to have alacritty be exposed as a library (`alacritty` is currently not used on crates.io). alacritty could draw to an OpenGL texture and take inputs via a `Processor` provided by the embedding application.

Use-cases would be:

- Wrappers for alacritty, for drawing decorations and such
- Embedded system terminals (like having a small command line in an OpenGL application).

This is just an idea.

**Comment by jwilm** [comment]
Yep, this would be great. In fact, we've got another issue open for it already. Please subscribe to #450 for updates.
