### ISSUE TITLE
Improve usage of font metrics

### ISSUE THREAD

**Issue by michaelmior** [jwilm/alacritty#83]
I get the output below when using [Roboto Mono](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/complete/Roboto%20Mono%20Nerd%20Font%20Complete.ttf).

![image](https://cloud.githubusercontent.com/assets/82501/21730051/e654cdc4-d41b-11e6-954e-431928c142ea.png)

Compare this to the output I get from the same under `mate-terminal`. Also of note is that colours are missing in the alacritty output.

![image](https://cloud.githubusercontent.com/assets/82501/21730092/18a9d88c-d41c-11e6-8252-e034fcdaa965.png)

**Comment by quininer** [comment]
No, you can see that font rendering is no problem.
Try editing `font -> offset` on `.config/alacritty.yml` ?

**Comment by michaelmior** [comment]
Yes, font rendering was a poor choice of words. Adjusting the offset definitely helps. Although as a user, I don't expect to have to configure this. Also, there's still the issue with the missing colour and the checkmark character does not appear in the alacritty output.

**Comment by jwilm** [comment]
Alacritty's interpretation of the freetype font metrics needs some work. The missing character will be solved once fallback fonts are supported.

**Comment by rspeer** [comment]
These two problems intersected for me as well. Unicode support is important to me. I'm fine with using Unifont as my font to get consistent Unicode rendering without fallbacks (at the cost of awful-looking W's), but alacritty's interpretation of Unifont's metrics is all wrong.

I did get it working by guessing-and-checking offset values (x: -3.5, y: -7.0).

**Comment by keizie** [comment]
This symptom may be related to these stuff;
* https://bugzilla.gnome.org/show_bug.cgi?id=106618
* https://github.com/adobe-fonts/source-han-sans/issues/154#issuecomment-223736821

**Comment by jwilm** [comment]
Should be resolved by #317

**Comment by jonhoo** [comment]
#317 is a *major* step in the right direction for me for most fonts. [iosevka](https://be5invis.github.io/Iosevka/) still renders weirdly for me though, including with ligatures disable (i.e., the `term` variant).

**Comment by gmile** [comment]
@jonhoo can you show a screenshot of alacritty rendering iosevka fonts incorrectly?

**Comment by jonhoo** [comment]
Actually, looks like it's just the variant with ligatures that's broken (right). The `iosevka term` variant (which is built without ligatures) looks to be functioning correctly:
![2017-05-01-162837_2560x1440_scrot](https://cloud.githubusercontent.com/assets/176295/25593599/4fa27208-2e8b-11e7-9430-85da613a0559.png)

**Comment by be5invis** [comment]
Are you guys measuring the maximum width of the glyphs in a font, to decide the width of each cell?

**Comment by nathanchere** [comment]
Example of Iosevka Nerd Font:

![alacrittyiosevka](https://user-images.githubusercontent.com/853261/32691199-0176cb30-c704-11e7-8752-0d48b2a41b40.png)

and it's even worse with the Mono variant. Renders fine in terminator and mate-terminal. Neither of these (to my knowledge) use ligatures.

**Comment by chrisduerr** [comment]
This should be fixed with 59b561b440060e7b0d13160fb69519d127e6c687.
