### ISSUE TITLE
thread 'main' panicked at 'XOpenIM failed'

### ISSUE THREAD

**Issue by gurditsbedi** [jwilm/alacritty#830]
Which operating system does the issue occur on?
`Linux gurdit-lp 4.9.31-1-MANJARO #1 SMP PREEMPT Wed Jun 7 19:39:15 UTC 2017 x86_64 GNU/Linux`

If on linux, are you using X11 or Wayland? `X11`

I followed the installation instruction of arch linux as specified in the readme. The installation completed with no errors. But when I try to execute `alacritty` from my old terminal. I get this error
```
thread 'main' panicked at 'XOpenIM failed', /home/gurditsbedi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Now I run again `alacritty` after executing `export RUST_BACKTRACE=1` and I get this.
```
thread 'main' panicked at 'XOpenIM failed', /home/gurditsbedi/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: __libc_start_main
  13: <unknown>
```

**Comment by mathstuf** [comment]
Do you have any input methods installed and/or enabled?

**Comment by kiljacken** [comment]
Are you using lightdm? What's the output of `echo $LANG` in a working terminal?

**Comment by kiljacken** [comment]
Okay, that should be a valid locale. I've had experiences with DM's mangling the locale, but this isn't such a case. Hopefully somebody else be more helpful.

**Comment by xyos** [comment]
This is related to this bug: https://github.com/tomaka/winit/issues/277

I solved it by setting a default input method usin `im-config` and setting it to iBus
this command writes a `~/.xinputrc` that contains:
```
run_im ibus
```
then I restarted X11 and now alacritty launches with no problem.

**Comment by gurditsbedi** [comment]
@xyos can you list the steps... I would like to confirm whether its working or not.

**Comment by alagopus** [comment]
I can confirm that starting ibus allows alacritty to start again. A permanent remedy is to roll back to 94849c4f2a19bd49337f5cf090f94ac6a940c414 avoiding recent changes to glutin and winit.

**Comment by NickeZ** [comment]
What is the correct workaround to this? How do I "start ibus" on ubuntu?

**Comment by mathroc** [comment]
I’m using uim, will ibus stay mandatory ?

**Comment by ivarsu** [comment]
Adding either `run_im ibus` or `run_im none` to `.xinputrc` fixes this issue for me.

**Comment by arielb1** [comment]
this can be worked around by setting `LANG=en_US.UTF-8`

**Comment by Limeth** [comment]
Neither of these workarounds seem to work for me, for some reason. Trying it with `8ff3c5d170abe47554f5d2a41ad35ddc451d254d`.
```
$ uname -a
Linux limebox 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ cargo run --release --features live-shader-reload
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/alacritty`
thread 'main' panicked at 'XOpenIM failed', /home/limeth/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sergei-dyshel** [comment]
FYI, I'm running on Fedora 25 with non-DE environment (i3wm) and solved the problem by running `fcitx` (got idea from https://github.com/jwilm/alacritty/issues/732)

**Comment by alexanderadam** [comment]
I have the same problem on Ubuntu 17.10:

```
❯ RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'XOpenIM failed', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:69
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: winit::platform::platform::x11::Window2::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692
   5: winit::window::<impl winit::WindowBuilder>::build
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/mod.rs:181
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/window.rs:113
   6: glutin::platform::platform::x11::Context::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/x11.rs:213
   7: alacritty::window::Window::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/mod.rs:52
   8: alacritty::display::Display::new
             at src/display.rs:140
   9: alacritty::run
             at src/main.rs:95
  10: alacritty::main
             at src/main.rs:45
  11: main
  12: __libc_start_main
  13: _start
```

Sergei's workaround solved the issue for me as well (`sudo apt install fcitx-bin && fcitx`)

**Comment by Limeth** [comment]
@alexanderadam Didn't realize I had to install it if it was missing, but that worked for me.

**Comment by alexanderadam** [comment]
Not just installing. After rebooting I have to call `fcitx` again. Otherwise this error appears again.

**Comment by hcpl** [comment]
I've filed a PR to `winit`: https://github.com/tomaka/winit/pull/424. It uses the workaround proposed by @jwilm from https://github.com/tomaka/winit/issues/277#issuecomment-337751136.

Anything that helps to fix this issue for good is welcome!

**Comment by shwsun** [comment]
I confirm that `sudo apt install fcitx-bin && fcitx` can fix the problem right away. I am running Ubuntu 17.10 with XMonad. This issue only happened when I login XMonad after logout Gnome tho...

**Comment by francesca64** [comment]
glutin 0.14.0 has been released, which uses winit 0.12.0. This includes @hcpl's tomaka/winit#424, meaning this issue (and #701) should no longer be a problem. 

Additionally, tomaka/winit#451 isn't released yet, but it will further assure that there aren't issues with XIM. When that's released, `platform_window_init` can be completely removed, and the panic caused by failing to open any input method is much more verbose and includes diagnostic information (however, it seem quite unlikely it would fail now).

**Comment by farid-fari** [comment]
@francesca64 Is this supposed to be released right now? I'm still getting the issue as of today.

**Comment by francesca64** [comment]
@farid-fari not yet. tomaka/winit#468

Note that after that merges, you'll still be waiting for a new glutin release that uses that winit release, though it should be fairly speedy. I'll probably make a PR here when that happens, since it will include a (minor) breaking API change.
