### ISSUE TITLE
rendering borked with neovim master

### ISSUE THREAD

**Issue by sanga** [jwilm/alacritty#832]
The screen cap is of me editing alacritty.yml. The numbers of the left should be the line numbers of the file. For reference editing the same file with the same version of neovim in gnome-terminal works as expected.

![2017-10-11-112350_1264x1331_scrot](https://user-images.githubusercontent.com/2088/31429587-233e8596-ae77-11e7-8735-1a46cd466cc8.png)

Against neovim (77f1392f073660558d8772cfab8be8cf7c2f8b7f) and alacritty (68cca6eb381f88e861439ed6a1dda1ab6a7429d3) master today. 

On X11 (with awesomewm if that makes any difference).

I get plenty of these spat out to the terminal

```
[Unhandled CSI] action='m', args=[3848], intermediates=[]
[Unhandled CSI] action='m', args=[3848], intermediates=[]
[Unhandled CSI] action='m', args=[3848], intermediates=[]
[Unhandled CSI] action='m', args=[3848], intermediates=[]
[Unhandled CSI] action='m', args=[3848], intermediates=[]
[Unhandled CSI] action='m', args=[38480, 1], intermediates=[]
[Unhandled CSI] action='m', args=[3848], intermediates=[]
[Unhandled CSI] action='m', args=[3848], intermediates=[]
[Unhandled CSI] action='m', args=[3848], intermediates=[]
```

Which may be related.

**Comment by jwilm** [comment]
did this start happening after you upgraded neovim?

**Comment by sanga** [comment]
I'm following neovim master - updating pretty regularly. I believe (but can't tell you definitively) that I'd had this problem for some time now (months?). Sorry I can't tell you very specifically, I have only tried alacritty sporadically. If I get some time I'll do a bit of bisecting and see if I can localise the problem a bit more.

**Comment by jwilm** [comment]
What is your value of TERM? Are you using a multiplexer like tmux?

**Comment by sanga** [comment]
TERM is xterm-256color. No tmux or any other multiplexer

**Comment by sanga** [comment]
I get the same behaviour back to 346ec09 for alacritty (I gave up at trying to bisect alacritty at that point). However switching back to neovim 0.1.7, it renders perfectly.

For reference, it also renders perfectly in xterm with alacritty current master. So my guess is that neovim switched something in [0.1.7, current_master] that alacritty doesn't support?

**Comment by sanga** [comment]
Following this:

https://www.reddit.com/r/neovim/comments/74pupd/anyone_having_success_with_neovim_alacritty/

exporting TERM=screen-256color

fixed the problem.

**Comment by sanga** [comment]
So this is on me, I guess.
