### ISSUE TITLE
Mouse selection doesn't clear when contents change underneath

### ISSUE THREAD

**Issue by mathstuf** [jwilm/alacritty#836]
Which operating system does the issue occur on?

Linux/X11

When there is a mouse selection highlighted, it stays in its position even if the content scrolls underneath. In urxvt, the selection moves with the content if it is scrolled, but cleared if the content changes underneath (or it scrolls off). In alacritty, the selection (highlight) stays in place.

**Comment by dezza** [comment]
I tried on Mac. Same thing.

**Comment by jwilm** [comment]
@mathstuf thanks for filing all of these issues. There's lots of "little" things needing polish, and it's great to get them all into the issue tracker.

**Comment by mathstuf** [comment]
No problem :) . I'm picky about my terminal and `alacritty` is *really* close. One more program closer to Wayland migration for me :) . Thanks!

**Comment by chrisduerr** [comment]
I've looked at `xterm` and `termite` to check how they behave in this case and it seems like they have the selection directly associated to the cells. So when the screen changes or scrolls, it will move the selection with the scrolling content.

It might be possible to add a `selected` attribute to all cells in the buffer and then iterate over the grid when the selection should change or a copy is triggered with ctrl+shift+c.
