### ISSUE TITLE
Incredibly slow compared to urxvt

### ISSUE THREAD

**Issue by alem0lars** [jwilm/alacritty#837]
I have installed alacritty, compiling it from source.

I've tested some common operations I make with terminal and in almost all operations alacritty is 4 times slower than my previous terminal: rxvt-unicode.

I have a NVidia Quadro graphics card (optimized for OpenGL rendering).

Which operating system does the issue occur on?

Gentoo

If on linux, are you using X11 or Wayland?

X11

**Comment by jwilm** [comment]
How did you compile alacritty?

**Comment by alem0lars** [comment]
Following instructions in the readme file.

**Comment by jwilm** [comment]
Could you elaborate on which operations are slow compared to urxvt on your system?

**Comment by alem0lars** [comment]
Simple commands with time prepended, like ls, pwd take 4x times to the
command to run. The command is the same, the only difference is the
terminal.

Also when I type characters in the ZSH input line seems slower.

When the shell shows completions takes more time compared to urxvt. In this
case I can feel the slowness without running benchmarks.

**Comment by lord-re** [comment]
Which graphic driver are you using ?
Can you paste your "glxinfo" (from mesa-progs) ?

**Comment by alem0lars** [comment]
Nvidia proprietary drivers (video card is Nvidia quadro k2200m)

**Comment by jasom** [comment]
Radeon HD 5450 using `radeon` xorg driver, I see `time yes|head -n 1000000` taking about 2x as long on alacritty as urxvt.

`OpenGL renderer string: Gallium 0.4 on AMD CEDAR (DRM 2.50.0 / 4.12.12-gentoo, LLVM 4.0.1)`

I can post full glxinfo if it would be useful to someone.

**Comment by jwilm** [comment]
@jasom that is pretty much resolved on the [`vec-deque-backing`](https://github.com/jwilm/alacritty/tree/vec-deque-backing) branch. Will be going for parity before landing it.

If you want to play around with some other benchmarks, I recommend checking out the [_vtebench_] application we've been working on.

[_vtebench_]: https://github.com/jwilm/vtebench/
