### ISSUE TITLE
Fonts seem to overlap

### ISSUE THREAD

**Issue by pmatos** [jwilm/alacritty#849]
Which operating system does the issue occur on?

Fedora 26

If on linux, are you using X11 or Wayland?

i3, X11 with alacrity master.

See screenshot.
![2017-10-18-143611_1247x499_scrot](https://user-images.githubusercontent.com/7911/31718918-e4a997da-b411-11e7-87a4-56e630081a66.png)

**Comment by mathstuf** [comment]
See also #98 #829 and #827 (at least). What font and size is this?

**Comment by pmatos** [comment]
I haven't set any font or size. But actually if I try to use the default config file, it looks a lot better.
Still think this shouldn't happen. Somehow other terminals don't have this problem even with no configuration.

**Comment by mathstuf** [comment]
Different apps may have different built-in font defaults. If you run with `RUST_LOG=alacritty:debug`, you should get the paths that are being used for fonts. I don't think you get the size though.

**Comment by jwilm** [comment]
This is a configuration issue
