### ISSUE TITLE
alacritty does not draw background color for (some) invisible characters

### ISSUE THREAD

**Issue by d3rrial** [jwilm/alacritty#85]
For example in htop.
![alacritty_bg_example](https://cloud.githubusercontent.com/assets/3718129/21730333/8a3f97ce-d44f-11e6-98e5-e4ac73e3a115.png)
Easily visible in this command:
```zsh
yes "$(seq 16 231)" | while read i; do printf "\x1b[48;5;${i}m\n"; sleep .02; done
```
because it is entirely invisible in alacritty, but visible in other terminal emulators

**Comment by jwilm** [comment]
Thanks for the report! This should be relatively easy to fix as soon as I can make some time.

**Comment by CarwynNelson** [comment]
@jwilm Duplicate issue #123 logged. Hopefully this will provide some extra testing scenarios.

Would it be possible to point to the general direction where this sort of thing is handled in the alacritty codebase? Maybe as a beginner task that is easy to fix?

**Comment by jwilm** [comment]
The logic for when to skip a cell [is in term.rs](https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L135-L136). It uses [`Cell::is_empty()`](https://github.com/jwilm/alacritty/blob/master/src/term/cell.rs#L90-L94) for checking if the cell should normally be displayed. The `is_empty()` logic should be updated for other non-printable characters.

**Comment by d3rrial** [comment]
The problem seems to be elsewhere. I completely commented out the skipping code in term.rs but the output still looks exactly the same, so this issue is either not related to blank characters, or it's located elsewhere in the code.

**Comment by CarwynNelson** [comment]
I can confirm what @d3rrial has described. I tried to comment out the is_empty code and the issue still persists.

I think if you have a theme like gruvbox in vim that isn't rendering properly the problem becomes a little bit more interactive / visible. It seems that you just simply can't "reach" these characters that aren't being rendered.

I'll try and record a gif or a video to demonstrate or maybe try to print out the on the screen what characters are in the empty space.

**Comment by CarwynNelson** [comment]
Here is a gif of me moving around in vim a little bit and adding some text. Hopefully this helps to visualise the issue a little more. 

![gif of issue](http://g.recordit.co/CsISsSMi0j.gif)

I'm not too sure what invisible character (if any) vim tries to render when there is no text in a region, but maybe it might differentiate from the example given in the issue description?

**Comment by CarwynNelson** [comment]
@jwilm I noticed in the test folder a [json dump of the grid](https://github.com/jwilm/alacritty/blob/master/tests/ref/vim_simple_edit/grid.json) whilst in vim. Is there any easy way to produce this whilst in alacritty?

I'm thinking this might serve as a useful debugging tool for figuring out what characters background colours aren't being rendered.

**Comment by d3rrial** [comment]
The easiest way to find out what isn't drawn is probably to look what ncurses uses to fill those line endings with.

Maybe it's not invisible characters, maybe it's calculating a line length that's too short? What would happen if, for every line, an invisible (`' '`) character would be appended to the last column?

**Comment by CarwynNelson** [comment]
That would make sense. It seems that alacritty is rendering the background colour only for places that have text. The rest of the area appears to be the default alacritty background colour.

I imagine a JSON dump of the grid would still help to confirm this though - right?

A total guess from knowing nothing about the architecture of this project (or rust) - I would guess that a cell with truly nothing in it would be populated with null, therefore the majority of an empty vim document would be a grid of cells where `c` (as seen in the struct below) are null.

```rust
pub struct Cell {
    pub c: char,
    pub fg: Color,
    pub bg: Color,
    pub flags: Flags,
}
```

Although I'm not sure if a `char` in rust can be null?

**Comment by basile-henry** [comment]
An empty cell is actually populated with `' '` and the default colour:

```rust
impl Default for Cell {
    fn default() -> Cell {
        Cell::new(
            ' ',
            Color::Named(NamedColor::Foreground),
            Color::Named(NamedColor::Background)
        )
    }
}
```

So the problem I guess is that white space characters ('\n', '\t', ...)don't update the relevant cells with a colour update

**Comment by CarwynNelson** [comment]
@basile-henry I guess that seems like the issue then. I guess the first place to start would be to find out where these cells are created in alacritty and what is done with these white space characters?

**Comment by basile-henry** [comment]
@CarwynNelson 

I think the modification would need to be where the white space characters are handled.
First let's start with '\n' in `src/term/mod.rs`:

```rust
    fn linefeed(&mut self) {
        debug_println!("linefeed");
        if self.cursor.line + 1 == self.scroll_region.end {
            self.scroll_up(Line(1));
        } else {
            self.cursor.line += 1;
        }
    }
```

This should update the current line and add colour data to the cells that need it. I'll see if I can implement that

**Comment by CarwynNelson** [comment]
Just looking at where `linefeed` is used in `Impl ansi::Handler for Term` and it seems that it should only be called when scrolling past the end of the scroll region?

```rust
if (self.cursor.line + 1) >= self.scroll_region.end {
    self.linefeed();
} else {
    self.cursor.line += 1;
}
```

Of course looking at the debug log shows `linefeed` being called when I simply move the (vim) cursor down one line. I'm guessing I'm not understanding this correctly. Could somebody explain to me what is actually going on in this part of the code?

**Comment by basile-henry** [comment]
Oh right I guess maybe this is for movement rather that input, I'll keep looking for where white space characters are actually handled as input

**Comment by CarwynNelson** [comment]
Actually the gif I posted above explains this quite nicely. You can see the `linefeed` debug being printed out even though nothing new is really being rendered. Could this bit of code be to do with moving at all - rather than just rendering "new" things on screen?

**Comment by basile-henry** [comment]
@CarwynNelson I think I've managed to fix it here: https://github.com/basile-henry/alacritty/commit/537471dfd3324162c98d9837da258f9ffa2875f8

Would you mind trying this commit before I make a PR? 😃 
At the moment I'm only fixing '\t' and '\n' any other white space chars I should fix?

**Comment by CarwynNelson** [comment]
Looks like I get a compile error under MacOS 10.12.2.

```
rustc 1.14.0 (e8a012324 2016-12-16)
```

```
cargo 0.15.0-nightly (298a012 2016-12-20)
```

error:
```sh
error[E0554]: #[feature] may not be used on the stable release channel
  --> /Users/carwynnelson/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.0/src/lib.rs:40:34
   |
40 | #![cfg_attr(feature = "nightly", feature(const_fn))]
   |                                  ^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
  --> /Users/carwynnelson/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.0/src/lib.rs:41:34
   |
41 | #![cfg_attr(feature = "nightly", feature(integer_atomics))]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
  --> /Users/carwynnelson/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.0/src/lib.rs:42:34
   |
42 | #![cfg_attr(feature = "nightly", feature(asm))]
   |                                  ^^^^^^^^^^^^

error: aborting due to 3 previous errors

Build failed, waiting for other jobs to finish...
error: Could not compile `parking_lot_core`.

Caused by:
  process didn't exit successfully: `rustc /Users/carwynnelson/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.2.0/src/lib.rs --crate-name parking_lot_core --crate-type lib -g --cfg feature="nightly" -C metadata=b776954c2db52c62 -C extra-filename=-b776954c2db52c62 --out-dir /Users/carwynnelson/alac-henry/target/debug/deps --emit=dep-info,link -L dependency=/Users/carwynnelson/alac-henry/target/debug/deps --extern smallvec=/Users/carwynnelson/alac-henry/target/debug/deps/libsmallvec-cf4677c7857fc4a9.rlib --extern libc=/Users/carwynnelson/alac-henry/target/debug/deps/liblibc-6ec63c5a0e74a074.rlib --extern rand=/Users/carwynnelson/alac-henry/target/debug/deps/librand-8ea7d489d4a383a0.rlib --cap-lints allow` (exit code: 101)
```

**Comment by d3rrial** [comment]
You need to change rust, like normal:
`rustup override set $(cat rustc-version)`

**Comment by CarwynNelson** [comment]
Whoops - my bad! I didn't realise I had to do that for each new terminal window.

Unfortunately this seems to have introduced a weird visual glitch and may have introduced a crash. Either that or made an existing crash more visible.

On the plus side it does seem to have fixed the case given by @d3rrial.

Issues:
1.) If I run @d3rrial's example but then press `ctrl+c` to exit it the terminal crashes with this error:
```
thread 'pty reader' panicked at 'slice index starts at 80 but ends at 79', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/slice.rs:566
stack backtrace:
   1:        0x10e6dd3da - std::sys::imp::backtrace::tracing::imp::write::h1461f67be4bf68a9
   2:        0x10e6df77f - std::panicking::default_hook::{{closure}}::h6dba65b2b498d274
   3:        0x10e6df427 - std::panicking::default_hook::ha8ecbcff1f59e805
   4:        0x10e6dfc46 - std::panicking::rust_panic_with_hook::h5ceed7bd7aef311a
   5:        0x10e6dfa94 - std::panicking::begin_panic::h091a980eb2ddd29a
   6:        0x10e6dfa02 - std::panicking::begin_panic_fmt::h063a49cc71e3d103
   7:        0x10e6df967 - rust_begin_unwind
   8:        0x10e707b20 - core::panicking::panic_fmt::h59374b8a88ef3536
   9:        0x10e707c69 - core::slice::slice_index_order_fail::hec21073d5cd2d63a
  10:        0x10e43ecd8 - <core::ops::Range<usize> as core::slice::SliceIndex<T>>::index_mut::hd98460b5c92240e8
  11:        0x10e40d4ce - core::slice::<impl core::ops::IndexMut<I> for [T]>::index_mut::h133eb666c497fb7b
  12:        0x10e3c1634 - <collections::vec::Vec<T> as core::ops::IndexMut<core::ops::Range<usize>>>::index_mut::hb996221b04053b1f
  13:        0x10e3c642f - <alacritty::grid::Row<T> as core::ops::IndexMut<core::ops::Range<alacritty::index::Column>>>::index_mut::h0ec082e81cc5330b
  14:        0x10e4301ce - <alacritty::term::Term as alacritty::ansi::Handler>::linefeed::h89c021443a9d8fdf
  15:        0x10e42f712 - <alacritty::term::Term as alacritty::ansi::Handler>::input::hc794a4604e6765c8
  16:        0x10e44ab8c - <alacritty::ansi::Performer<'a, H, W> as vte::Perform>::print::h9d9d83142fbb0a8e
  17:        0x10e3e04d6 - vte::Parser::perform_action::hd299ed366d7730e1
  18:        0x10e3e0b4e - vte::Parser::perform_state_change::h5f666f5cea9cfec9
  19:        0x10e3e0ec4 - vte::Parser::advance::h7d7dc702ce94ac05
  20:        0x10e44fcfc - alacritty::ansi::Processor::advance::hc6ee283588c59dee
  21:        0x10e41c8f1 - <alacritty::event_loop::EventLoop<Io>>::pty_read::h1b59f9e710704da8
  22:        0x10e41c02f - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::hcf94650ed8b8287a
  23:        0x10e44bd04 - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h82c52b98e7678c78
  24:        0x10e3e017f - std::panicking::try::do_call::h45001908c6796602
  25:        0x10e6e0b1a - __rust_maybe_catch_panic
  26:        0x10e3df95b - std::panicking::try::h8a297def552a6d19
  27:        0x10e3dd9c4 - std::panic::catch_unwind::hc40aeefc9b70ea57
  28:        0x10e3df11c - std::thread::Builder::spawn::{{closure}}::h1f5974490dc28140
  29:        0x10e4161b9 - <F as alloc::boxed::FnBox<A>>::call_box::h8d077e2e7f3bca57
  30:        0x10e6dee54 - std::sys::imp::thread::Thread::new::thread_start::haeb202749da670ee
  31:        0x10f948aaa - _pthread_body
  32:        0x10f9489f6 - _pthread_start
child finished with error '256'
```

2.) My vim now seems to be quite broken. Here is a gif:
![](http://g.recordit.co/rsihhPhSQj.gif)

**Comment by d3rrial** [comment]
@CarwynNelson Not just vim. Try 
```zsh
ls -al
```

**Comment by basile-henry** [comment]
Yeah sorry about that, '\t' is definitely fixed but '\n' is trickier than I thought. I've been testing with

```zsh
echo -e "\x1b[48;5;31m1\t2\n\n3\x1b[0;m"
```

I'll update my branch when I manage to fix the broken newline. Thanks for testing it out though!

**Comment by basile-henry** [comment]
So the problem with the code I had was that I didn't take into account that carriage return is always right before new line and not the other way around so I was basically erasing the line before going to the next one.
Because of the carriage return I lose the information of where the cursor was before carriage return. I could look for it afterwards (by look at the grid content) but that doesn't seem very clean.

Also, I'm a bit confused by how other terminals apply colour. Take a look at gnome-terminal:

![echo1](https://cloud.githubusercontent.com/assets/3369034/21742292/6a3686ba-d4e3-11e6-9768-da3c5bd57b24.png)

It seems weird the background colour after '3' isn't black...

Maybe it's a standard behaviour in which case it's easy to replicate in alacritty:

![echo2](https://cloud.githubusercontent.com/assets/3369034/21742275/2782ef52-d4e3-11e6-8049-8e763c387b12.png)

But I'm still missing what I would expect to be the normal behaviour of a coloured newline.

**Comment by d3rrial** [comment]
@basile-henry This is how that same command looks like to me in urxvt-256
![basile](https://cloud.githubusercontent.com/assets/3718129/21742387/2f20d5e8-d4ee-11e6-977b-4ba0c38c6ec4.png)

**Comment by basile-henry** [comment]
Alright this time I checked a bit better and the `yes` command shown above works on my [branch](https://github.com/basile-henry/alacritty/tree/draw-background-color).

The only thing I fixed are the backgrounds for characters `'\t'` and `'\n'`.

This still doesn't fix the issue for htop and probably not for vim either. These programs use the terminal in a different mode and move the cursor around instead of using '\n' for a newline.

A bigger refactor of the background colour logic is needed in order to make this work. Instead of not rendering cells that haven't explicitly been changed, alacritty needs to take into account the colour changes from previous cells to decide whether to render an empty cell and how to do so.

**Comment by jwilm** [comment]
On my machine, `htop` emits this around the end of the column headers:

```
00000a90: 2020 436f 6d6d 616e 641b 5b4b 0d1b 5b31    Command.[K..[1
```

"Command" is the last column in my `htop`. The following sequence is `\033[K` which is saying "clear line to the right". It's not clear to me that "clear line" should clear using the current terminal attributes, but it does seem to fix this issue.

**Comment by CarwynNelson** [comment]
@jwilm Just to clarify - are you running the change by @basile-henry or do you have your own changes?

If you have made your own changes could you post a link to the commit so I can test this out in vim? I'm curious to know if it's the same problem.

Thanks :)

**Comment by jwilm** [comment]
My own change, but I'm not convinced it's correct. ECMA-48 mentions ClearLineRight should put characters into the "erased state" but doesn't elaborate much.

```diff
diff --git a/src/term/mod.rs b/src/term/mod.rs
index 73f9ad6..72d39f6 100644
--- a/src/term/mod.rs
+++ b/src/term/mod.rs
@@ -898,7 +898,7 @@ impl ansi::Handler for Term {
     #[inline]
     fn clear_line(&mut self, mode: ansi::LineClearMode) {
         debug_println!("clear_line: {:?}", mode);
-        let template = self.empty_cell;
+        let template = self.template_cell;
         let col =  limit(self.cursor.col, Column(0), self.grid.num_cols() - 1);
         match mode {
             ansi::LineClearMode::Right => {
```

**Comment by CarwynNelson** [comment]
Thanks for the diff. I applied the change to my local version and I have the same result as before - so it appears that it didn't work.

I'm not sure if it will be much help, but back to a previous comment of mine. Is it possible to dump out the current state of the `Grid` so that we can inspect the actual characters that vim is using? Much like the one in the test folder.

**Comment by basile-henry** [comment]
The diff from @jwilm fixes the `htop` and `yes ...` tests for me but something like:

```zsh
echo -e "\x1b[48;5;31m1\t2\x1b[48;5;5m\n\n\x1b[0;m3"
```

is still wrong and vim is like before with the background colour issues.

**Comment by basile-henry** [comment]
@CarwynNelson For the current state of the grid I think you can run `alacritty --ref-test` and it will dump the state in a json file one exit

**Comment by d3rrial** [comment]
the diff does fix htop, but creates other issues, for example my prompt is now in the wrong color:
The `>` is correct, the square however is not.
![promptcolor](https://cloud.githubusercontent.com/assets/3718129/21745265/2d07406e-d528-11e6-9746-94c7217388d2.png)

**Comment by jwilm** [comment]
Thanks for testing that @d3rrial.

**Comment by d3rrial** [comment]
htop looks perfect, if I use `PROMPT="%{$fg_bold[white]%} %n %{$fg_no_bold[white]%}%~ %{$fg_no_bold[yellow]%}>%{$reset_color%}"` in my .zshrc the color is fixed, too (although that is not what I should have to do)

The script remains entirely invisible tho.
```zsh
yes "$(seq 16 231)" | while read i; do printf "\x1b[48;5;${i}m\n"; sleep .02; done
```

**Comment by mbrumlow** [comment]
@jwilm I think both are right after doing some research (or at least can be right). Its called background-color-erase, its something a terminal can support or not support via the bce setting. I don't think alacritty ships and uses its own termcap file yet and is piggybacking off whatever TERM is set to. If TERM=xterm-256 color then bce is enabled . So when htop renders it thinks that erasing to the end of the line will have the currently set background color. We don't see the problem in tmux or without tmux but TERM=tmux-256color, because it does not set bce in the terminfo. This results in htop not trying to draw line with erase to the end of the line. 

> neptune:~
> $ infocmp xterm-256color | grep bce
>         am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
> neptune:~
> $

And for tmux-256 color 

> neptune:~
> $ infocmp tmux-256color | grep bce
> neptune:~
> $

So if the goal is be a xterm compatible / replacement then I think it should use the template, if not then ship a terminfo and use that (not setting bce). At some point the main documentation should be updated specifying what TERM= to use when using alacritty.

**Comment by jonhoo** [comment]
This is pretty well researched by now, but I figured I'd add that this behavior also shows up in `mutt`. The color of any window-wide bar is simply remove in blank areas. As observed by @mbrumlow, the behavior disappears when running through `tmux`.

**Comment by DivineGod** [comment]
I've got a patch that makes `echo -e "\x1b[48;5;31m1\t2\n\n3\x1b[0;m"` work.

**Comment by DivineGod** [comment]
Adding a bit more info to this, that I just found out about iTerm2 and Terminal.app and interaction with the `echo`-test.

If there is no scroll-back happening in either terminal program the command will only output background behind `1\t2`. Otherwise it'll output on both lines; the blank and the one containing 3.

The same is true for the `yes ...` command. No colors will print until scrolling happens.

I am trying to come up with a solution which will be well performing and hopefully work universal across the different use cases highlighted here.

@basile-henry I tried out the solution in your branch but it does seem to slow performance down a bit having to set each cell in a line after linefeed

**Comment by tiziano88** [comment]
Just tried out the latest version, and I can confirm that the fix worked! Thanks so much for this!

**Comment by DivineGod** [comment]
I've found a case with vim, that might be related to this or something completely different. Having default config for alacritty master and using vim with gruvbox dark theme I see black backgrounds when scrolling with `j`/`k`

![alacritty_background_bug](https://user-images.githubusercontent.com/36430/26872278-4d8991c2-4bb9-11e7-97a3-f4dc094a24d5.gif)

**Comment by peyloride** [comment]
I have same problem @DivineGod. Did you find any fix?

**Comment by jwilm** [comment]
@peyloride you'll want to follow #123
