### ISSUE TITLE
CTRL-Space input is not passed through

### ISSUE THREAD

**Issue by TyOverby** [jwilm/alacritty#851]
> Which operating system does the issue occur on?
OSX

Because CTRL-Space doesn't have an ascii representation, many terminals send NUL.

See more: https://stackoverflow.com/questions/23189568/control-space-vim-key-binding-in-normal-mode-does-not-work

**Comment by sodiumjoe** [comment]
dupe of https://github.com/jwilm/alacritty/issues/99

**Comment by TyOverby** [comment]
So it is!
