### ISSUE TITLE
Margins (like xterm -borderwidth)

### ISSUE THREAD

**Issue by ilya-kolpakov** [jwilm/alacritty#854]
The letters in the first/last columns can be difficult to read because they are very close to window borders. It would be nice to have a possibility to create some space similar to `xterm`'s `borderwidth` option. One can have different settings for vertical and horizontal margins.

**Comment by jwilm** [comment]
There's an option in the config called `padding` that does this. See _alacritty.yml_ at the repository root if you don't already have it.

**Comment by ilya-kolpakov** [comment]
Many thanks, somehow I did not spot this option in the config file.
