### ISSUE TITLE
Send text at start support

### ISSUE THREAD

**Issue by k0nserv** [jwilm/alacritty#860]
In iTerm I use

```
tmux ls && read tmux_session && tmux attach -t ${tmux_session:-default} || tmux new -s ${tmux_session:-default}
```

for "Send text at start" to ensure I always start in tmux. Is it possible to do so in Alacritty? I haven't found anything like it so maybe it's something that is open to contriubtion.

**Comment by jwilm** [comment]
You can achieve this using the “program” config. Start bash or zsh with -c as first argument and your snippet as second argument.

**Comment by k0nserv** [comment]
Cool I figure it would be something like that. Thanks :)
