### ISSUE TITLE
Strange glitch with Neovim and mouse mode

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#861]
**Which operating system does the issue occur on?**
macOS

**Description**
I've noticed when setting `set mouse=a` within init.vim, whenever I open neovim in Alacritty, I get a very strange glitch were the colorscheme is disabled or a crazy amount of flickering occurs. Once the mouse setting is disabled in Neovim, problem is gone. So I thought to post this here in case anyone else runs into this issue, I'll be making a new issue in Neovim's repo as well and reference here shortly.

**Comment by chrisduerr** [comment]
I'm not able to reproduce this and it sounds unlikely that this is an alacritty issue (sounds more like issues with the init.vim). If the issue still exists and you wish to troubleshoot this further, please let me know and I'll re-open this.
