### ISSUE TITLE
Request: Globbal toggle key

### ISSUE THREAD

**Issue by haringsrob** [jwilm/alacritty#862]
Hi,

Great product, I really love it, it is basically the only full terminal that allows a smooth vim experience on os x.

The only thing I miss is a toggle. When I am in certain software, I would like to quickly open up, run a command and close down.

Any plans on implementing this?

Regards,

**Comment by snatchev** [comment]
I have been full-screening alacritty and then setting the "Reduce Motion" toggle on OSX Accessibility preferences:
![image](https://user-images.githubusercontent.com/3312/31955515-9dbff6f8-b8b6-11e7-9b95-f94202d5c7ce.png)

This reduces makes switching to a fullscreen app a very quick fade-in animation.

Then alt-tabbing to alacritty or binding a shortcut to display/dismiss Desktop 1 achieves a similar workflow to a toggle.

**Comment by nixpulvis** [comment]
#450 might be relevant to you.

**Comment by haringsrob** [comment]
Lets close this one for now. I'll put a thumbs up in #450 and if it is not there by the end, i'll request a new feature.

**Comment by zx1986** [comment]
is this like the hotkey window feature in iTerm 2?

**Comment by aben** [comment]
@zx1986 Try [HotKey App](https://apps.apple.com/us/app/hotkey-app/id975890633?mt=12)

**Comment by notDavid** [comment]
fyi for people stumbling upon this using macOS, you can also use [BetterTouchTool](https://folivora.ai/) to create a "Keyboard shortcut" to "show/hide specific Application" (Alacritty.app).

This will result in the same behaviour as the iTerm2 window toggle key.

**Comment by wenlibin02** [comment]
HammerSpoon makes it easier. A working configuration is:

``` lua
hs.hotkey.bind({"command", "ctrl"}, "R", function()
    hs.execute('open /Applications/Alacritty.app')
end)
```

Then command+ctrl+R will switch to Alacritty.

**Comment by bric3** [comment]
However I don't think it's possible that an Alacritty window opens over fullscreen aps in macos. (Like quake terminals), or like the iterm2 hotkey behavior.

**Comment by jdalt** [comment]
I started with @wenlibin02 solution using [hammerspoon](https://www.hammerspoon.org/) but added the following to match the iterm2 behavior I wanted (`~/.hammerspoon/init.lua`):
```lua
hs.hotkey.bind({"ctrl"}, "space", function()
  local alacritty = hs.application.find('alacritty')
  if alacritty:isFrontmost() then
    alacritty:hide()
  else
    hs.application.launchOrFocus("/Applications/Alacritty.app")
  end
end)
```
This will pop up the Alacritty with with `ctrl-space` and toggle it hidden if it's already visible. 

Combined with macOS `SimpleFullscreen` support in https://github.com/rust-windowing/winit/issues/473 this allows me to completely replace iTerm2.

**Comment by gandhiShepard** [comment]
OMG! The solution posed by @jdalt works PERFECTLY! And I'm psyched to be introduced to Hammerspoon as well. Mind blown right now.

**Comment by axxapy** [comment]
Shell script to do the same on linux:
```
#!/bin/bash

PID=$(pgrep alacritty)
if [ -z "$PID" ]; then
        alacritty &
        exit 0
fi

WINDOWID=$(xdotool search --pid $PID)
IS_VISIBLE=true
[ -z $(xdotool search --onlyvisible --pid $PID) ] && IS_VISIBLE=false

[ $(xdotool getwindowfocus) != "$WINDOWID" ] && {
        if [ $IS_VISIBLE == true ]; then
                xdotool windowactivate $WINDOWID
        else
                xdotool windowmap $WINDOWID
        fi

        exit 0
}

xdotool windowunmap $WINDOWID
```

you can bind it to any key combination in gnome/kde/your_de settings

**Comment by wenlibin02** [comment]
> I started with @wenlibin02's solution using [hammerspoon](https://www.hammerspoon.org/) but added the following to match the iTerm2 behavior I wanted (`~/.hammerspoon/init.lua`):
> 
> ```lua
> hs.hotkey.bind({"ctrl"}, "space", function()
>   local alacritty = hs.application.find('alacritty')
>   if alacritty:isFrontmost() then
>     alacritty:hide()
>   else
>     hs.application.launchOrFocus("/Applications/Alacritty.app")
>   end
> end)
> ```
> 
> This will pop up the Alacritty window with with `ctrl-space` and toggle it hidden if it's already visible. Adjust to your preferred hotkey.
> 
> Combined with macOS `SimpleFullscreen` support in [rust-windowing/winit#473](https://github.com/rust-windowing/winit/issues/473) this allows me to completely replace iTerm2.
> 
> Config in `.config/alacritty/alacritty.yml`:
> 
> ```yaml
> key_bindings:
>   - { key: Return,   mods: Command,         action: ToggleSimpleFullscreen }
> ```

It is a good idea to hide the window. I modified the 3rd line of the code so that it works on my machine:
```
       if (alacritty ~= nil and alacritty:isFrontmost()) then
```

**Comment by ducva** [comment]
This is my config to work on my Mac.
```
hs.hotkey.bind({"command"}, "`", function()
    local alacritty = hs.application.find('alacritty')
    local awin = alacritty:mainWindow()
    if awin and alacritty:isFrontmost() then
      alacritty:hide()
    else
      alacritty = hs.application.launchOrFocus("/Applications/Alacritty.app")
    end
  end)
```

**Comment by Wai-Lau** [comment]
If the above solutions haven't worked, try this:
```lua
hs.hotkey.bind({"option"}, "`", function()
    alacritty = hs.application.find('alacritty')
    if alacritty then
      awin = alacritty:mainWindow()
    end
    if awin and alacritty and alacritty:isFrontmost() then
      alacritty:hide()
    else
      hs.application.launchOrFocus("/Applications/Alacritty.app")
      local alacritty = hs.application.find('alacritty')
      alacritty.setFrontmost(alacritty)
      alacritty.activate(alacritty)
    end
  end
)
```

Main change is that sometimes your window will not be brought to the front, so it takes three "unhide" operations to finally work.

**Comment by haringsrob** [comment]
If you do not want to use hammerspoon just for this and you already use Karabiner elements you can also use the following rule:

It does not hide, it only brings to the foreground (but for me this was one less app running).
```
                    {
                        "manipulators": [
                            {
                                "description": "Open alacritty",
                                "from": {
                                    "key_code": "spacebar",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_control",
                                            "left_command"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "shell_command": "open -a '/Applications/Alacritty.app'"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
```

**Comment by programus** [comment]
I just created my solution based on @jdalt 's work. Now it support multiple monitors and spaces. 

https://gist.github.com/programus/d3bf9c6b8f9b7648891d1f59b665b35e

Hope this can also help others who have the same requirements.

**Comment by helgeblod** [comment]
Based on the gist by @programus above, I did a short write-up on how I set this up. It works great, I have ditched iTerm2 in favour of Alacritty now. If you want to set this up, check out my post here: https://world.hey.com/jonash/alacritty-drop-down-guake-quake-style-terminal-setup-on-macos-6eef7d73

**Comment by axxapy** [comment]
for gnome-shell users: 
https://extensions.gnome.org/extension/3942/toggle-alacritty/

**Comment by programus** [comment]
> Based on the gist by @programus above, I did a short write-up on how I set this up. It works great, I have ditched iTerm2 in favour of Alacritty now. If you want to set this up, check out my post here: https://world.hey.com/jonash/alacritty-drop-down-guake-quake-style-terminal-setup-on-macos-6eef7d73
> 
> It's basically the solution above with a minor tweak.

Great! I have a suggestion that put a link of this issue in your post, so readers can come here to find more solutions and contribute their own ideas. Furthermore, if there were better solutions  be posted here, your readers can read them too.

**Comment by helgeblod** [comment]
Done 👍

**Comment by wai-lau** [comment]
Hmmm, it looks like it should work to me. I intended it to work with just one window (my terminal), not sure what you mean by "only bringing forward one of my Safari windows".

**Comment by juanmaia** [comment]
> I just created my solution based on @jdalt 's work. Now it support multiple monitors and spaces.
> 
> https://gist.github.com/programus/d3bf9c6b8f9b7648891d1f59b665b35e
> 
> Hope this can also help others who have the same requirements.

This worked great for me with a 2 monitors setup, thank you!

**Comment by truebit** [comment]
Now hammerspoon replaces "https://github.com/asmagill/hs._asm.undocumented.spaces" to "https://github.com/asmagill/hs._asm.spaces", Could we add a new script?
Thanks

**Comment by zhongjis** [comment]
I wrote a bash script instead of lua.
the goal is just using the simplest tools with minimal visual stutter.
https://gist.github.com/zhongjis/4b11381bce4342394e494f733a278c87

**Comment by codevogel** [comment]
For Windows users switching over from Windows Terminal, Here's an AHK script that emulates Windows Terminals' `globalSummon` feature for alacritty (or really any window)

```
#`::
exeName := "yourProgram.exe"
exePath := "path\\to\\yourProgram.exe"

IfWinExist, ahk_exe %exeName%
{
    IfWinActive, ahk_exe %exeName%
    {
        WinHide, ahk_exe %exeName%
    }
    else
    {
        WinShow, ahk_exe %exeName%
        WinActivate, ahk_exe %exeName%
    }
}
else
{
    Run, %exePath%
}
return
```

**Comment by gabeidx** [comment]
For macOS users who also use Raycast, you can simply record a hotkey on the "Extensions" settings panel:

![CleanShot 2024-07-30 at 12 40 17@2x](https://github.com/user-attachments/assets/a1670c10-1c6a-469e-8b21-1bf682359e33)

**Comment by overstart** [comment]
> For Windows users switching over from Windows Terminal, Here's an [AHK](https://www.autohotkey.com/) script that emulates Windows Terminals' [`globalSummon`](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/actions#global-summon) feature for alacritty (or really any other process)
> 
> #`:: ; Hotkey: WIN + `
> 
> ; Define the name of your executable and its path
> exeName := "alacritty.exe"
> exePath := "C:\Program Files\Alacritty\alacritty.exe"
> 
> IfWinExist, ahk_exe %exeName% ; Check if a window with your program exists
> {
>     IfWinActive, ahk_exe %exeName% ; Check if the window is active
>     {
>         WinHide, ahk_exe %exeName% ; If the window is active, hide it
>     }
>     else
>     {
>         WinShow, ahk_exe %exeName% ; If the window is not active (hidden or in the background), show it
>         WinActivate, ahk_exe %exeName% ; Activate the window
>     }
> }
> else
> {
>     Run, %exePath% ; If the window does not exist, launch the program
> }
> return ; End of hotkey

@codevogel Awesome! I've upgraded this to v2 and rebound the Hotkey from  **WIN + `** to **Ctrl+Shift+T**
```bash
^!t:: {
    ; Define the name of your executable and its path
    exeName := "alacritty.exe"
    exePath := "C:\Program Files\Alacritty\alacritty.exe"

    ; Check if a window with your program exists
    if (WinExist("ahk_exe " exeName)) {
        ; Check if the window is active
        if (WinActive("ahk_exe " exeName)) {
            ; If the window is active, hide it
            WinHide("ahk_exe " exeName)
        } else {
            ; If the window is not active (hidden or in the background), show it
            WinShow("ahk_exe " exeName)
            ; Activate the window
            WinActivate("ahk_exe " exeName)
        }
    } else {
        ; If the window does not exist, launch the program
        Run(exePath)
    }
    return
}
```
