### ISSUE TITLE
Alacritty blinks on resize

### ISSUE THREAD

**Issue by andreyorst** [jwilm/alacritty#869]
OS: Arch Linux, openSUSE
DE: KDE
Compositor: KWin
Display Server: Xorg

Resizing Alacritty causes weird flickering
check this video:
(epilepsy warning)
[example.zip](https://github.com/jwilm/alacritty/files/1419366/example.zip)

**Comment by NickeZ** [comment]
Here is also a movie of another blinking behavior. Seems like alacritty fails to redraw content fast enough during resizing. gnome-terminal looks good.

[out.ogv.gz](https://github.com/jwilm/alacritty/files/1421979/out.ogv.gz)

**Comment by omtcyfz** [comment]
I also experience this issue.

OS: Arch Linux.
Compositor: Xorg
DE: KDE
Graphics: NVidia card + Nouveau

**Comment by intelfx** [comment]
@omtcyfz FTR, Xorg is neither a WM nor a compositor. Given that you use KDE, your compositing WM is likely to be KWin, but the usage of a compositor actually should prevent this issue, so it looks like you have compositing disabled or misconfigured in KWin.

**Comment by NickeZ** [comment]
@intelfx I'm using compton (which i believe is a compositor) and I3 and I still have the issue.

**Comment by FichteFoll** [comment]
Here's a video recording of this with i3 and compton (and Xorg):

[alacritty_resize.zip](https://github.com/jwilm/alacritty/files/1591798/alacritty_resize.zip)

Without compton the situation is similar, except that the window is black instead of transparent. I doubt there's anything do be done here, though.

However, termite handles this better in that it seems to not be as eager with redrawing itself and only doing so when the number of columns or lines that can fit into the window change.

**Comment by chrisduerr** [comment]
So I've looked into this and it seems directly related to #969.

When using `with_transparency(false)`, or just removing this call completely, this issue is not present anymore.

**Comment by FichteFoll** [comment]
Can confirm that this issue is basically non-existant with `with_transparency(false)`.
It still looks kinda sub-optimal in ranger, but I suppose that ncurses is to blame for that or something. And I rarely resize a floating ranger window in i3 anyway.

**Comment by unphased** [comment]
Note as specified in #969 that this only affects High Sierra (and possibly Sierra) only. El Capitan performs great with transparency enabled.

**Comment by chrisduerr** [comment]
This has been fixed in winit 0.15.1.

**Comment by unphased** [comment]
Tested on macos 10.13.5 now, window resizing feels greatly improved!

dragging the corner to resize does make the window disappear but performance is better overall.

**Comment by chrisduerr** [comment]
That's nice to hear! This issue was specifically about the window disappearing on X11, which has been fixed. I'm not sure if the MacOS behavior is tracked somewhere else.

**Comment by unphased** [comment]
Hmm. on my 2017 MacBook (I built master earlier yesterday) it is currently resizing very very sluggishly. So maybe I was too quick on the draw with that report. Both on same 10.13.5 though.

**Comment by chrisduerr** [comment]
Yeah, that is tracked in #969, macos definitely still has some issues with resizing.
