### ISSUE TITLE
Unable to type Unicode characters on 105-key Norwegian (bokmål) keyboard

### ISSUE THREAD

**Issue by andreastt** [jwilm/alacritty#87]
alacritty is apparently unable to type Unicode characters, such as æøå. On the empty lines in the attached screenshot, I’ve tried typing “æøå“.

Interestingly, it _is_ possible to paste Unicode characters into the terminal.

![screenshot-2017-01-06-194218](https://cloud.githubusercontent.com/assets/399120/21730571/3ece0778-d448-11e6-939c-d6c87e536903.png)

**Comment by d3rrial** [comment]
alacritty has problems accepting input from non-us keyboard layouts, that might be the reason

**Comment by andreastt** [comment]
That would explain it. The keyboard layout in this case is Norwegian (bokmål) on Linux.

**Comment by srl295** [comment]
I found keyboard input to hang (no longer accepting input until restart) when typing Option-` on the US layout or the equivalent key on the ISO Spanish layout. I'll keep watching this and try again of this is improved, great work though!

**Comment by basile-henry** [comment]
I think it's a keyboard input method issue rather than not handling unicode since you're saying you can paste them.

This seems to be the same thing as issue #55 and can be fixed by modifying the version of glutin alacritty depends on.

**Comment by basile-henry** [comment]
If you want a quick fix for these particular letters, update https://github.com/jwilm/glutin/commit/af7fe340bd4a2af53ea521defcb4f377cdc588cf with (and make alacritty depend on your version):

```diff
diff --git a/src/api/x11/events.rs b/src/api/x11/events.rs
index 4754b1dc..5fb1771a 100644
--- a/src/api/x11/events.rs
+++ b/src/api/x11/events.rs
@@ -305,8 +305,8 @@ pub fn keycode_to_element(scancode: libc::c_uint) -> Option<VirtualKeyCode> {
         //ffi::XK_Acircumflex => events::VirtualKeyCode::Acircumflex,
         //ffi::XK_Atilde => events::VirtualKeyCode::Atilde,
         //ffi::XK_Adiaeresis => events::VirtualKeyCode::Adiaeresis,
-        //ffi::XK_Aring => events::VirtualKeyCode::Aring,
-        //ffi::XK_AE => events::VirtualKeyCode::Ae,
+        ffi::XK_Aring => events::VirtualKeyCode::Aring,
+        ffi::XK_AE => events::VirtualKeyCode::Ae,
         //ffi::XK_Ccedilla => events::VirtualKeyCode::Ccedilla,
         //ffi::XK_Egrave => events::VirtualKeyCode::Egrave,
         //ffi::XK_Eacute => events::VirtualKeyCode::Eacute,
@@ -325,7 +325,7 @@ pub fn keycode_to_element(scancode: libc::c_uint) -> Option<VirtualKeyCode> {
         //ffi::XK_Otilde => events::VirtualKeyCode::Otilde,
         //ffi::XK_Odiaeresis => events::VirtualKeyCode::Odiaeresis,
         //ffi::XK_multiply => events::VirtualKeyCode::Multiply,
-        //ffi::XK_Ooblique => events::VirtualKeyCode::Ooblique,
+        ffi::XK_Ooblique => events::VirtualKeyCode::Ooblique,
         //ffi::XK_Ugrave => events::VirtualKeyCode::Ugrave,
         //ffi::XK_Uacute => events::VirtualKeyCode::Uacute,
         //ffi::XK_Ucircumflex => events::VirtualKeyCode::Ucircumflex,
diff --git a/src/events.rs b/src/events.rs
index 69b4710d..a3d01614 100644
--- a/src/events.rs
+++ b/src/events.rs
@@ -254,8 +254,10 @@ pub enum VirtualKeyCode {
     AbntC1,
     AbntC2,
     Add,
+    Ae,
     Apostrophe,
     Apps,
+    Aring,
     At,
     Ax,
     Backslash,
@@ -291,6 +293,7 @@ pub enum VirtualKeyCode {
     NumpadEnter,
     NumpadEquals,
     OEM102,
+    Ooblique,
     Period,
     PlayPause,
     Power,
```

Hopefully this will all get fixed when glutin stabilises!

**Comment by bluss** [comment]
It's handling keyboard layout fine, including custom x remaps of course. Inserting uncode like `€`, `¿` or `·` is also fine, but not `å`,`ä` or `ö` nor their capitals.

Dead keys in the key layout are also not handled. (AltGr and diaeresis then space → ~).

**Comment by jwilm** [comment]
I just pushed a branch with `fix-intl-input`. I think this should solve a lot of the problems mentioned here. Would anyone be willing to try it?

**Comment by okuuva** [comment]
Just tried `fix-intl-input`, now äöå are working. Thanks!

**Comment by bluss** [comment]
Yep, a lot fixed!

- AltGr + < produces `|` is fixed
- å key produces `å`, ä key produces `ä` is fixed etc

Dead keys changed behaviour (before they did nothing). diaeresis then a => `ää` now (should be just `ä`). The same way AltGr + diaeresis then space produces `~~` (should be just `~`).

**Comment by andreastt** [comment]
@jwilm It appears entering æøå works on that branch, but dead keys get repeated. For example, to produce ö (o with umlaut) on a Norwegian (bokmål) keyboard, you first type ¨ (dead key) and then o. Similarly on a US American keyboard for producing characters with acutes, such as è, é, â, &c.

![screenshot-2017-01-07-143046](https://cloud.githubusercontent.com/assets/399120/21742403/3b5ac10a-d4e6-11e6-97e3-fd0bc6026881.png)

**Comment by jwilm** [comment]
I think the original issue being discussed here has been resolved. Closing in favor of #211.

**Comment by theduke** [comment]
@jwilm forgot to close? ;)

**Comment by jwilm** [comment]
@theduke thx
