### ISSUE TITLE
Unable to start when specifying command

### ISSUE THREAD

**Issue by kovetskiy** [jwilm/alacritty#871]
Arch Linux, latest build from git.

```
 $  alacritty -e /bin/id               
Event loop exitting due to error: Input/output error (os error 5) [src/event_loop.rs:401]                                                                      

```

**Comment by NickeZ** [comment]
`id` is a non-blocking command. What did you expect to happen? It will print and then exit the terminal immediately.

**Comment by kovetskiy** [comment]
@NickeZ ok, there is a problem not in id itself, looks:
1. run tmux new session in background:
```
$ tmux new -d -s xxx
```

2. then try to fork exec alacritty in Go:
```
package main

import (
	"os"
	"syscall"
)

func main() {
	syscall.ForkExec(
		"/bin/alacritty",
		[]string{"alacritty",
			"--command",
			"/bin/systemd-cat",
			"-t",
			"alacritty",
			"tmux",
			"attach",
			"-t",
			"xxx",
		},
		&syscall.ProcAttr{
			Env: os.Environ(),
		},
	)
}

```
```
go run file.go
```

then look into journalctl:
```
alacritty[16522]: Failed to duplicate fd: Invalid argument                                                                             
```

**Comment by kovetskiy** [comment]
Feel free to remove "/bin/systemd-cat", "-t", "alacritty", it will crash too

**Comment by jwilm** [comment]
Running alacritty with `alacritty -e tmux` or `alacritty -e vim` works fine for me. I don't understand what you're trying to complete with this go snippet, but generally it seems like running alacritty with a command is fine.

**Comment by NickeZ** [comment]
@kovetskiy I don't know go so I cannot help you. Seems like the problem comes from your go program.

**Comment by kovetskiy** [comment]
Yeah, sorry guys, the problem was with tmux specific command, but after that I found that it works with any command but it appears only when I run alacritty without specifying standard file descriptors (using syscall fork and exec). 

And right now I found that it fails with following errors:
```
thread 'pty reader' panicked at 'Error while logging!: Error { repr: Os { code: 22, message: "Invalid argument" } }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
This is what I get from shell history file (alacritty pushes these messages to stdout and shell handles it as commands)

I understand that it is weird that program called without specifying standard fds, but the problem does not appear with other terminals like rxvt and xterm.

**Comment by jwilm** [comment]
@kovetskiy why close this?
