### ISSUE TITLE
Delayed command start

### ISSUE THREAD

**Issue by vorner** [jwilm/alacritty#875]
Hello

I use xmonad as a window manager and on session start, I start multiple alacritty terminals with some specific commands inside (like `alacritty -e top &`). The window manager places them on specific workspaces. Therefore, they are not visible right away, only after I switch to the given workspace.

I observe a strange thing. It seems to me the command is started when the alacritty is first show. Therefore, when I have (for example) a music player controlled by global keyboard shortcuts, it doesn't respond to the keyboard shortcuts until I first switch to the workspace with the music player.

Is something like that possible? That it is not really started until it is drawn for the first time? One thing of note, xmonad is supposed to be „non-reparenting“ window manager (whatever that means), which is said to be quite unusual.

I'll be happy to provide further information if needed.

> Which operating system does the issue occur on?

Linux.

> If on linux, are you using X11 or Wayland?

X11

**Comment by nixpulvis** [comment]
I can reproduce this issue with `i3` as my WM as follows:

`~/.config/i3/config`
```
# ...

assign [class="Alacritty"] 9
exec --no-startup-id alacritty -e speaker-test
```

I don't hear the speaker test until I navigate to workspace 9.
