### ISSUE TITLE
Crash on exiting top

### ISSUE THREAD

**Issue by Dirbaio** [jwilm/alacritty#88]
How to reproduce:
- Launch alacritty
- run `top`
- Press q, or Control+C

Full log + stacktrace: http://pastebin.com/raw/pHszgNbd

I'm running Arch Linux. `top` comes from the package `procps-ng-3.3.12-1`. 

It also happens if I SSH to an Ubuntu server and exit top.

**Comment by d3rrial** [comment]
Happens when exiting top in general.

Quit top with "q" and you should get the same error

**Comment by Dirbaio** [comment]
True, updated the issue to reflect that.

**Comment by coder543** [comment]
I didn't see this issue, but I encountered it on my own and created a fix for it here: https://github.com/jwilm/alacritty/pull/91

**Comment by jwilm** [comment]
Is this fixed on master? cc @Dirbaio @d3rrial

**Comment by mbrumlow** [comment]
I had the same problem and pr #91 fixed it for me.

**Comment by jwilm** [comment]
Going to close this until someone says otherwise.
