### ISSUE TITLE
Can't input ~^´`¨[]{} and @ with Portuguese keyboard on macOS

### ISSUE THREAD

**Issue by nunocasteleira** [jwilm/alacritty#893]
Using macOS 10.13 and the Portuguese keyboard layout, I can't get Alacritty (and therefore neovim) to input these symbols
``~^´`¨[]{}@``
I installed Alacritty from master today.

**Comment by k0nserv** [comment]
Are you on macOS? If so look at https://github.com/jwilm/alacritty/issues/458

**Comment by nunocasteleira** [comment]
The very first words i wrote were "using macOS".
The problem is, the keyboard wasn't remapped, I'm using the default layout from Apple, only with Portuguese characters.

Changing it to English I'm able to input those symbols, but the inability to input á à ã é ó ç and []{} and @ is a dealbreaker.

**Comment by k0nserv** [comment]
Welp sorry I must have missed that. Then yeah #458 and https://github.com/jwilm/alacritty/issues/458 are definitely the problem

**Comment by nunocasteleira** [comment]
I'm currently not capable to pass the flag `--print-events` because I'm not understanding how to pass it. I'm sorry for not be able to help, although I'd want to do it.

**Comment by k0nserv** [comment]
From the root of alacritty do `target/release/alacritty --print-events`

**Comment by nunocasteleira** [comment]
Inputting @:
```bash
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 51, state: Released, virtual_keycode: Some(Back), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 61, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 19, state: Pressed, virtual_keycode: Some(Key2), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: ReceivedCharacter('@') }
glutin event: Awakened
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 19, state: Released, virtual_keycode: Some(Key2), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 61, state: Released, virtual_keycode: Some(LAlt), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

Alacritty receives the `@`but doesn't input it.

Inputting á:
```bash
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 30, state: Pressed, virtual_keycode: Some(RBracket), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 30, state: Released, virtual_keycode: Some(RBracket), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(A), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: ReceivedCharacter('a') }
glutin event: Awakened
glutin event: WindowEvent { window_id: WindowId(Id(140532532645728)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```
The keystroke for the `´` is received as right bracket, not passing the argument for the acute sign.

**Comment by rainerborene** [comment]
Same issue here. I can't type characters like `çãíéá`. Not using macOS though.

**Comment by rainerborene** [comment]
Events of ` key:
```
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 34, state: Released, virtual_keycode: None, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(56623107))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 34, state: Released, virtual_keycode: None, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

**Comment by rainerborene** [comment]
How can I help implementing this feature?

**Comment by lrascao** [comment]
i was able to input `~` and ``` using:
```
  - { key: Apostrophe,                      chars: "\u007E"                    }  # tilde (~)
  - { key: RBracket, mods: Shift,     chars: "\u0060"                    }  # grave accent (`)
```

**Comment by rainerborene** [comment]
Thanks for the tip but it didn't work because `Apostrophe` is mapped to another key on my keyboard layout (pt-BR). I guess I can't map because of this `virtual_keycode: None`.

**Comment by felippemr** [comment]
I have the same issue here, @lrascao how should I configure alaritty to use `"`?

**Comment by lrascao** [comment]
regular quotation is U+0022, you're not able to input that?

**Comment by felippemr** [comment]
No I'm not. :(

**Comment by netgusto** [comment]
On MacOS w/ AZERTY layout, was able to input `~` with Alt-n (which is the default for `~`) by adding this line to the alacritty.yml:

```
  - { key: N, mods: Alt,                     chars: "\u007E"                    }  # tilde (~)
```

**Comment by francesca64** [comment]
Does this still happen on the latest version of Alacritty?

**Comment by nunocasteleira** [comment]
The issue seems to be resolved now!

**Comment by pedrocunha** [comment]
I am struggling to get this to work without setting `alt_send_esc` to `false`, is there an alternative to this? 

For example on my keyboard to get a "{" I need to press Shift+Option+8 to get it. 

I tried but it does not work:
```
 {key: 8,  mods: Shift|Option, chars: "\x7b"}
```

However if I replace "8" by "A" it does work as expected. How can get I get around this issue? Thanks

**Comment by lrascao** [comment]
also for future reference, here's my [alacritty.yml](https://gist.github.com/lrascao/2f38d46898fe73d08239b3835d2993b9)

**Comment by ranisalt** [comment]
I have this same problem, using Portuguese layout on Arch Linux, with Alacritty 0.4.2

**Comment by Tech-Nomad** [comment]
I have a German keyboard layout on Mac and have the same issue. I've found out by default pressing Option+5, Option+6, Option+7 etc behaves as expected only when pressing Escape button previously. 

But It's still absolute frustrating, that you can't bind any custom behaviour for those combinations to get those chars as usual: []]|{}@~\
I have wasted now half of the day trying to get this work. No documentation, no solved issue on this....

**Comment by Tech-Nomad** [comment]
Ok, luckily right after writing my last comment. I've found out my config had partly wrong indention. First you have to set `alt_send_esc: false` and be sure, that it's of the top level of the config hierarchy (not indented). For example:
```
shell:
  program: /usr/local/bin/bash
  args:
    - --login
# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: false
```

This disables sending escape sequences when using Alt/Option combinations.
