### ISSUE TITLE
`apt install`'s progress bar is not hidden sometimes

### ISSUE THREAD

**Issue by 0x7CFE** [jwilm/alacritty#896]
I've just installed `sl` and progress bar remained on screen even after `apt` exited. It disappeared only when I resized the alacritty's window using mouse.

Version info:
```
Kubuntu 16.04.3, Xorg
Alacritty built from master f68558e9dcce97e0d4d842a2d5b62e31e4124210
```

**Comment by chrisduerr** [comment]
There have been some changes to rendering since this issue was originally opened, including a big modification with the scrollback PR.

Is this issue still present?

**Comment by chrisduerr** [comment]
Closing since there has been no update to this issue in over a year. If someone is still experiencing this problem, please let me know and I'll re-open it.
