### ISSUE TITLE
Upper part of long characters (f, l) missing a few pixels using small font sizes

### ISSUE THREAD

**Issue by sandersantema** [jwilm/alacritty#900]
Which operating system does the issue occur on? Mac OS 10.12.6, Macbook Pro Retina 13inch, late 2013.

Using certain font sizes a few pixels of the top of long letters are missing. I've only seen this happen with quite small font sizes, which isn't a problem on my 13 inch screen (since they don't need to be small) but is a problem when using a bigger screen. 

This is happening while using the "IBM Plex" font. Possibly a bug of IBM Plex and not alacritty? I've tried adjusting the x-offset which isn't helping. 

Correct F
<img width="245" alt="correct f" src="https://user-images.githubusercontent.com/21057514/32778736-523e1800-c93b-11e7-8082-f1eeedd95e68.png">

Wrong F (look very closely)
<img width="198" alt="wrong f" src="https://user-images.githubusercontent.com/21057514/32778737-526d3478-c93b-11e7-9d9f-a93bc613e569.png">

Alacritty.conf: https://pastebin.com/7TsE5QwC

On a side note: what is the correct way to define the font to use for certain styles? I can't seem to get it to work.

**Comment by chrisduerr** [comment]
There have been a lot of changes to the computation of font metrics since this issue has been created. As a result I'm closing it since it should be resolved with the latest master.

If this issue is still present, please let me know and I'll re-open it.
