### ISSUE TITLE
No way to map plus key

### ISSUE THREAD

**Issue by neonfuz** [jwilm/alacritty#901]
>Which operating system does the issue occur on?
nixos (linux)
>If on linux, are you using X11 or Wayland?
X11

My keyboard has a plus key (I'm using the programmers dvorak layout), and there seems to be no way to bind it. It seems each key has an entry in the Key enum defined in config.rs, but there is no "Plus" entry. 

This is the output xev gives me of pressing the plus key on my keyboard:
`
KeyPress event, serial 34, synthetic NO, window 0x2800001,
    root 0x146, subw 0x0, time 3019940, (110,75), root:(1301,669),
    state 0x0, keycode 18 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XmbLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False

KeyRelease event, serial 34, synthetic NO, window 0x2800001,
    root 0x146, subw 0x0, time 3020087, (110,75), root:(1301,669),
    state 0x0, keycode 18 (keysym 0x2b, plus), same_screen YES,
    XLookupString gives 1 bytes: (2b) "+"
    XFilterEvent returns: False

`

**Comment by chrisduerr** [comment]
The font size patch introduced a config binding for changing the font size using `ctrl+'+'`. This entry looks like this:
`  - { key: Equals, mods: Control, action: IncreaseFontSize }`

You should be able to use `key: Equals` for other bindings too.

**Comment by neonfuz** [comment]
That's not what I need... I have an actual plus key (as xev confirms), not an equals key. Like I said in the first post, I'm using programmers dvorak (accessible on linux with `setxkbmap -variant dvp`) , so what is the 9 key in qwerty is a plus key for me. This key currently seems unmappable, and `key: Equals` does not work.

**Comment by chrisduerr** [comment]
Try applying this patch and then send the output you get when pressing this `plus` key please.

```diff
diff --git a/src/event.rs b/src/event.rs
index b133f8f..0b6daf2 100644
--- a/src/event.rs
+++ b/src/event.rs
@@ -287,6 +287,7 @@ impl<N: Notify> Processor<N> {
                         processor.ctx.terminal.dirty = true;
                     },
                     KeyboardInput { input, .. } => {
+                        println!("{:?}", input);
                         let glutin::KeyboardInput { state, virtual_keycode, modifiers, .. } = input;
                         processor.process_key(state, virtual_keycode, &modifiers);
                         if state == ElementState::Pressed {
```

**Comment by neonfuz** [comment]
Thanks for the suggestion, it seems that it was expecting 'Add' not 'Plus'. It seems other people have complained about this non-intuitive naming before too (https://github.com/tomaka/glutin/issues/785), but I guess it's out of alacritty's control because it's defined by glutin.

**Comment by chrisduerr** [comment]
I suppose we could add a list with all available keycodes.

**Comment by jwilm** [comment]
> I suppose we could add a list with all available keycodes.

There kind of is one, but you have to know where to look. We could just link to that big list in config.

**Comment by chrisduerr** [comment]
I've created a quick PR which puts a link right at the top of the documentation: #1012.
