### ISSUE TITLE
Alacritty crashes when using a to big font size. 

### ISSUE THREAD

**Issue by sandersantema** [jwilm/alacritty#903]
Which operating system does the issue occur on? Mac OS 10.12.6
To reproduce: Open up Alacritty zoom with cmd + until it crashes.
[AlacrittyCrashLog.txt](https://github.com/jwilm/alacritty/files/1478101/AlacrittyCrashLog.txt)

**Comment by maximbaz** [comment]
Duplicate of #842 and #898
