### ISSUE TITLE
locale not set in macOS

### ISSUE THREAD

**Issue by unphased** [jwilm/alacritty#911]
macOS 10.13.1

I have two machines (one a MacBook and one a MacBook Pro) both on 10.13.1

On one of these machines nothing needs to be done to enable utf8. But on one of the machines, when creating or attaching to a tmux session, I must specify `-u` in order for my font to render properly in Alacritty. 

I've actually now tracked it down to locale. So although I've used the same method (build from source and `make app` and copy it to /Applications) on one machine it has proper `en_US.UTF-8` locale, and on the other machine it is `LANG=` and `"C"` for the LC_* variables.

I wonder what might cause this? In my other terminals on the problematic environment they do have locale set.

**Comment by unphased** [comment]
I see that the `launcher` bash script is actually designed to handle this. 

The problem is that on the problem computer, the exec'd `alacritty` does not actually gain these newly set env vars. Trying to get to the bottom of it...

**Comment by unphased** [comment]
looks like if I specify shell as `/bin/bash` with `--login` it works right, but with `/usr/bin/login` with `-f <my username>` it does not.

**Comment by sodiumjoe** [comment]
@unphased have you tried `/usr/bin/login -fp <username>`? from https://github.com/jwilm/alacritty/issues/1071#issuecomment-361975738

**Comment by unphased** [comment]
There appears to be no difference. In fact, in my test now, all 3 methods seem to set proper locale. It would seem that `login` respecting the user's chosen shell is valuable. I think some other changes in Alacritty have "resolved" the issue.

**Comment by sodiumjoe** [comment]
so we can probably close this issue?
