### ISSUE TITLE
macOS app bundle launched multiple times creates multiple instances of the app

### ISSUE THREAD

**Issue by cyphactor** [jwilm/alacritty#912]
Which operating system does the issue occur on?

macOS High Sierra 10.13.1 (17B48)

If on linux, are you using X11 or Wayland?

Just built the latest master (8ff3c5d) using `cargo build --release` and then `make app` and installed it by copying the app bundle into the applications folder.

When I launch the app by double clicking, opening with a launcher (Spotlight, Alfred, etc.), or open the app with `open -a 'Alacritty'` multiple times in a row, it opens multiple instances of the app.

This is abnormal behavior for macOS. It generally should simply focus the first launched instance when opened a second, third, etc. time.

I remember this used to work back in the day when the macOS app bundle was just added to the project. I tried going back to those commits and building but the compilation is failing.

**Comment by jwilm** [comment]
This is captured by #607

**Comment by kyhy** [comment]
@cyphactor were you able to resolve this issue?

**Comment by cyphactor** [comment]
@kyhy sadly no. It is supposed to be part of #607 but that seems like a much larger under taking than this issue. I have completely stopped using alacritty because of this issue. I would love to jump in and figure it out and contribute back but I haven't had enough time to dig in, and I am not sure exactly what changed to cause it to launch multiple instances now.

**Comment by kyhy** [comment]
Thank you for letting me know. Strangely in El Capitan, alacritty behaves as it should by opening the existing instance. (although vim navigation does not work :[ )

**Comment by cyphactor** [comment]
Hmm, I never had that issue.

I just poked around and I am guessing it is a side effect of the use of glutin to create the window. I think glutin does the wrong thing in terms of macOS behavior potentially.

**Comment by cyphactor** [comment]
@kyhy I dug in a bit and determined it has more to do with how it is packaged in the app bundle. Specifically, it has a `lancher` bash script which seems to be the thing that changed and broke the behavior.

The following is the `alacritty/assets/osx/Alacritty.app/Contents/Info.plist` file I have that is working to prevent it from launching multiple windows and behave as I would expect in macOS.

The one thing weird is that the new terminal starts at `/` rather than the users home directory.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
  <key>CFBundleExecutable</key>
  <string>alacritty</string>
  <key>CFBundleIdentifier</key>
  <string>com.github.jwilm.alacritty</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
  <key>CFBundleName</key>
  <string>Alacritty</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.1.0</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
  <key>CFBundleIconFile</key>
  <string>alacritty.icns</string>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSMainNibFile</key>
  <string></string>
  <key>NSSupportsAutomaticGraphicsSwitching</key>
  <true/>
</dict>
</plist>
```

**Comment by kyhy** [comment]
Do I copy this and run `make app` again or copy this directly within `/Application/Alacritty.app`?

**Comment by kyhy** [comment]
Got it to work! Thank you so much! Having to type in `~` is much less annoying than having multiple instances :P 

Perhaps... there is a config some where that needs to be tweaked?

**Comment by cyphactor** [comment]
@kyhy I opened a PR for this, https://github.com/jwilm/alacritty/pull/941

The description has some more details you may be interested in.

**Comment by kyhy** [comment]
You rock. Thank you!

**Comment by cyphactor** [comment]
@kyhy just so you know my PR and one to fix the locale setting and default path setting have been merged into master. So, you should be good if you grab the latest master, build and install it.

**Comment by kyhy** [comment]
Yessss!!! Thank you!!!! You have saved me countless CMD + tabs keypresses and boosted my productivity by a lot!
