### ISSUE TITLE
Support OSC 10-17 `?` parameter

### ISSUE THREAD

**Issue by DirectXMan12** [jwilm/alacritty#913]
According to https://www.xfree86.org/4.8.0/ctlseqs.html, in `OSC 10-17`, if the `?` parameter is given instead of an RGB color, the terminal should return the appropriate control sequence to set the given color to whatever its current value is (so we'd return something `OSC<command>;rgb:<r>/<g>/<b>BEL`).

My copy of vim seems to attempt to use this on startup.

**Comment by chrisduerr** [comment]
Fixed in https://github.com/jwilm/alacritty/commit/f79007035ccc8d52f5f491d35d3d4132aa29898d.
