### ISSUE TITLE
precompiled binaries?

### ISSUE THREAD

**Issue by damnskippy** [jwilm/alacritty#927]
Any chance pre-compiled binaries (x86/amd64, Ubuntu) will be published, or are we not ready for that yet?
Thanks.

**Comment by EvanPurkhiser** [comment]
From the readme:

> Precompiled binaries will eventually be made available on supported platforms. This is minimally blocked on a stable config format. For now, Alacritty must be built from source.

**Comment by danielpclark** [comment]
If you'd like to have a stab at creating a binary for distribution you should know that `.deb` packages are **very involved** and designed more or less for programs written in C/C++.  You can create binaries that are easy to distribute and use through [snaps](https://www.ubuntu.com/desktop/snappy) or [AppImage](https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages).

An AppImage is cool because all dependencies get wrapped into an executable with your program so systems won't have to install any dependencies to use it.

**Comment by chrisduerr** [comment]
There's https://github.com/sharkdp/fd, which is a Rust project that has CI setup to automatically provide binaries. It also provides a `.deb` file which is automatically generated with a short bash script. Would probably be a good place to look for inspiration.

**Comment by peteyy** [comment]
I'd be more than happy to set up a pipeline for you, to build somewhere, especially for [snaps](https://docs.snapcraft.io/core/) let me know if I can work on this.

**Comment by damnskippy** [comment]
Thanks @peteyy .
I assume it's up to @jwilm to take up your kind offer.

**Comment by chrisduerr** [comment]
There's also #80 which seems to be about the same topic as this issue.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by chrisduerr** [comment]
I personally don't believe much in "universal" package managers and there already is a snap as far as I know. So native distro support will always be the preferred way to install Alacritty. However, for platforms that do not (yet?) support Alacritty, I don't see why it shouldn't be offered.

Ideally I'd like to separate packaging from source code whenever possible, I'm not sure exactly how this works with AppImage. But I think if someone is willing to maintain an AppImage out of tree, that would be ideal. Adding installation instructions to the Alacritty upstream would of course still be possible.
