### ISSUE TITLE
Not working on Arch Linux

### ISSUE THREAD

**Issue by bemeurer** [jwilm/alacritty#929]
I'm using alacritty on Arch Linux by means of the `alacritty-git` AUR package. I upgraded all y `-git` packages today, and now alacritty no longer works. I am using i3 as my window manager on X11.
```
$ alacritty
[1]    13215 illegal hardware instruction (core dumped)  alacritty 
```
Here's the backtrace I got using `gdb`
```
#0  0x00005555557b10d3 in ?? ()
#1  0x00005555557b3f2e in ?? ()
#2  0x00005555558e999d in ?? ()
#3  0x000055555572a379 in ?? ()
#4  0x00005555557225ee in ?? ()
#5  0x0000555555664816 in ?? ()
#6  0x0000555555661189 in ?? ()
#7  0x000055555566e00a in ?? ()
#8  0x00007ffff6af1f6a in __libc_start_main () from /usr/lib/libc.so.6
#9  0x000055555557c91a in ?? ()
```

**Comment by enizor** [comment]
Got the same `illegal hardware instruction  ̀ today while building (with cargo) on Mint. It was because I used Rust nightly, setting it back to stable fixed it for me. I don't know if it is relevant for the AUR build though.

**Comment by jwilm** [comment]
please compile with stable instead of nightly

**Comment by bemeurer** [comment]
I can confirm that using the stable toolchain solves the issue. I added a comment on the AUR package asking if it was possible to force it to use stable from now on.

**Comment by AntouanK** [comment]
Any chance we get a normal package in arch? ( and not the git one )

**Comment by bemeurer** [comment]
@AntouanK I'd be willing to maintain a pre-compiled Arch package once Alacritty reaches 1.0, or any stable release. @jwilm, is there any ETA on this?

**Comment by jwilm** [comment]
@bemeurer no ETA. I'll be adding milestones at some point which highlight blockers.

**Comment by bemeurer** [comment]
@jwilm Awesome, I'll keep an eye out for it.
