### ISSUE TITLE
How to open urls with a mouse?

### ISSUE THREAD

**Issue by yevhen-m** [jwilm/alacritty#934]
I just want to click an url and open it in my browser. How can I do it?

**Comment by jwilm** [comment]
Not supported yet. We are planning to support this via #922. You may want to subscribe to that and #113 (url recognition, not necessarily going to implement that half).

**Comment by evmorov** [comment]
@yevhen-m, if you use tmux you can use https://github.com/tmux-plugins/tmux-open
