### ISSUE TITLE
Can't switch keyboards on macOS while alacritty is focused

### ISSUE THREAD

**Issue by azah** [jwilm/alacritty#935]
On OSX I quite often swap between English & Hangul keyboards.
This is done through Keyboard Shortcuts > Select next input source. 

However, in Alacritty, that input doesn't work. (I tested the same setup with iTerm2, it works)

I *think* this has to do with how Alacritty is bundled?

**Comment by melonmanchan** [comment]
This is pretty annoying! FWIW I've got the same issue with US and Finnish layout toggling. I've got mine bound to Cmd + U, and that keyboard shortcut just sends the U key to the terminal, instead of toggling between the input sources.

**Comment by trimailov** [comment]
On the same matter, some other keyboard shortcuts do not work either, i.e. I use `Spectacles.app` and `cmd+alt+shift+arrow` will not move `Alacritty.app` from one monitor to another.

Though some system keyboard shortcuts work, i.e. `cmd+space` for spotlight search. I am not familiar with macOS app bundling, though maybe it's indeed problem with bundling as @azah stated? Because on Linux system keyboard shortcuts seem to work [0]

[0] https://github.com/jwilm/alacritty/issues/948#issuecomment-352766658

**Comment by azah** [comment]
Alacritty also has no menu bar. If you open a regular osx application, it'll have a menu bar with the name of the application and other things like File, Edit, etc etc. Makes me think it's not bundled correctly and thus might swallow some inputs.

I believe Cmd + Space is a global hotkey, so that could be why it works while a custom command like Cmd+Opt+Up or Cmd+U won't.

**Comment by trimailov** [comment]
Seems that one of the #941 PR was to create `Info.plist` from native macOS app.   It maybe that some things are still missing in Alacritty's `Info.plist`.

**Comment by francesca64** [comment]
Could you try out this branch? https://github.com/francesca64/alacritty/tree/macos-kb

(Relevant winit PR: tomaka/winit#518)

**Comment by azah** [comment]
@francesca64 It works! I can now switch keyboards. Thank you.

The only thing to note is that the characters don't actually display until they're "completed", e.g. if I press <esc>, <space>, or move onto a new character. 
E.g. if I type '떡', it would normally show ㄷ, ㄸ, 떠, and 떡 dynamically as I type (before the char is completed). 

It's not *that* big of a deal, I just don't know where I'd report that.

**Comment by francesca64** [comment]
@azah that's a known limitation of the current implementation. winit would need to make some API changes for that to be possible, which would have to be designed in tandem with inline IME support on X11. I'm not sure when I'll get around to that.
