### ISSUE TITLE
Crash on running apt install

### ISSUE THREAD

**Issue by mhammerc** [jwilm/alacritty#94]
Hello :) I ran the command ```sudo apt install tmux``` and alacritty crashed.
Here are the last 5 lines of the output I got, I have nothing more.

    [unimplemented] save_cursor_position
    [unimplemented] restore_cursor_position
    thread 'pty reader' panicked at 'index out of bounds: the len is 86 but the index is 18446744073709551615', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    child finished with error '256'

**Comment by d3rrial** [comment]
I imagine this is the same bug as #88

**Comment by mhammerc** [comment]
Probably, should I close the issue ?

**Comment by JayWalker512** [comment]
This seems to have been fixed for me by pr #91 as referenced in issue #88 .

**Comment by jwilm** [comment]
Thanks for the updates; closing
