### ISSUE TITLE
unhandled osc_dispatch

### ISSUE THREAD

**Issue by grinapo** [jwilm/alacritty#944]
alacritty 0.1.0 (git commit d0fb4c5) [release build using rustc 1.20.0])

Which operating system does the issue occur on?

Debian/sid

If on linux, are you using X11 or Wayland?

X11

```[unhandled osc_dispatch]: [['2','1',],['-','v',' ','e','x',],] at line 849```

It also have crashed once, same variation I guess, but I don't have the message handy.

**Comment by sblundy** [comment]
I'm also seeing this message on OS X 10.11 (El Capitan) when I run it from the command line. Hasn't crashed yet.

Immediately on startup: `[unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/',$HOSTNAME,',',$HOME],] at line 879`

**Comment by chrisduerr** [comment]
Closing this as it is not about any specific escapes necessary to work properly. This was originally just debug output and the log level has been changed to represent that.

If there should be any escape sequences necessary to make something work, opening a separate issue for that sequence explicitly is the way to go.
