### ISSUE TITLE
dimensions aren't working

### ISSUE THREAD

**Issue by grinapo** [jwilm/alacritty#952]
**Which operating system does the issue occur on?**
Debian/sid

**If on linux, are you using X11 or Wayland?**
X11, 5760x2160, 160 dpi

![alacritty_hires_size](https://user-images.githubusercontent.com/1056054/34260285-9f277a84-e665-11e7-8455-5697f7ed1edf.png)

So you see the dimensions given have nothing in common with the dimensions displayed: 80x25 became something like 48x15 or so. Granted, the DPI is not usual, and ther is custom font, still the resolution seems to be based on the system font used in the title rather than the terminal space.

**Comment by accaldwell** [comment]
Similar issue here, window is way too small, and font is way too big. Arch Linux, X11, 1080P, 176DPI.
I'm guessing this is a HiDPI issue. Both terminals below are configured for 80x24 window size. The other terminal is gnome-terminal.

![alacritty](https://user-images.githubusercontent.com/2320451/34335124-4252789c-e901-11e7-8af7-6a1bde76410e.png)

X is configured with the correct DPI:
>xdpyinfo | grep -B 2 resolution  
>screen #0:  
>  dimensions:    1920x1080 pixels (277x156 millimeters)  
>  resolution:    176x176 dots per inch`

**Comment by scottjmaddox** [comment]
I had the same issue on macOS, but https://github.com/jwilm/alacritty/pull/1403 fixed it for me.
