### ISSUE TITLE
Broken config files should not cause Alacritty not to launch

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#954]

**Comment by voider1** [comment]
I will try my hand at this.

**Comment by jwilm** [comment]
That sounds great! Here's the feedback I got in IRC about the best way to do this:

```
13:28 <jwilm> I'd like to handle errors in Alacritty's config deserializer by substituting default values or simply omitting failed entries that are part of a sequence. Is https://serde.rs/ignored-any.html the best example of how to achieve this sort of thing?
14:04 <dtolnay> rovar: the serde(skip) not doing anything is a bug but that should work eventually https://github.com/serde-rs/serde/issues/1048
14:04 <dtolnay> rovar: for now i think the impl you wrote is the best way
14:04 <dtolnay> jwilm: IgnoredAny will not let you omit failing entries in a sequence
14:05 <dtolnay> jwilm: you only get to deserialize each entry once, so you cannot try to deserialize it to T, see that it failed, and deserialize it instead to IgnoredAny
14:05 <dtolnay> jwilm: i would suggest deserializing each sequence entry to serde_yaml::Value which always succeeds as long as the yaml is syntactically fine
14:05 <dtolnay> jwilm: then try to deserialize the Value to a T
```

fyi @dtolnay added your comments here

**Comment by chrisduerr** [comment]
I'm not quite sure if I understand this completely. But wouldn't this mean changing every type in the `Config` struct to `Value` and then using a default if it can't be used the actual destination type?

That seems like quite the effort.

**Comment by jwilm** [comment]
@chrisduerr yeah it's not a very elegant solution. Perhaps we should just use the default config when we fail to parse.

**Comment by chrisduerr** [comment]
For everything that already has a custom deserializer it would be fairly straight-forward to use a default fallback value. Assuming that all fallback values for one deserializer are the same.

But even tho it would be great to have this for every value, it seems to me like it would require a custom deserializer for every type we have.
