### ISSUE TITLE
Update winit, glutin, bitflags, and euclid

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#959]
PR #811 had done this in addition to some other work. Unfortunately, it became coupled to another of other PRs. The TODO with this issue is updating the allowed versions for these packages in `Cargo.toml` and making any necessary code changes.

**Comment by bemeurer** [comment]
Has this been done and fixed in #960?

**Comment by jwilm** [comment]
Yes thanks for the bump!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
