### ISSUE TITLE
Restore mouse cursor on focus

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#966]
The configured mouse cursor should be restored when Alacritty is focused. This doesn't currently seem to work on macOS.

**Comment by bemeurer** [comment]
Steps to reproduce? Doesn't seem to happen on Arch with X11.

**Comment by jwilm** [comment]
Maybe only a macOS issue

**Comment by chrisduerr** [comment]
Is this issue still present in the latest Alacritty? I'd assume it manifests itself in the cursor being an arrow, not an I-Beam after focus is lost once?

**Comment by chrisduerr** [comment]
I've tested this and it seems to be fixed.
