### ISSUE TITLE
Block selection

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#978]
Unphased has mentioned in #974 that block selection would be a nice feature for alacritty. And I'd love to take a look at implementing this.

The main question would probably be about which modifier should be used for it. I'd go for ctrl, which is used by VTE, but it seems like other terminals use alt.

**Comment by unphased** [comment]
I wouldn't even care if it is ctrl or alt, it'd be easy enough to get used to. Best might be if it could be configured, I suppose.

**Comment by lord-re** [comment]
Many i3 users use Alt as a modifier key to enable all their commands so Ctrl maybe better. But if it's configurable…

**Comment by chrisduerr** [comment]
Closed because it's a duplicate of #526.
