### ISSUE TITLE
Font rendering overlap on OS X 10.11.6

### ISSUE THREAD

**Issue by davesque** [jwilm/alacritty#98]
![screen shot 2017-01-06 at 1 38 15 pm 2](https://cloud.githubusercontent.com/assets/791437/21732191/8c5b4e7a-d415-11e6-8b18-1a04f5d9bdfd.png)

Visible in screenshot.

**Comment by basile-henry** [comment]
Try changing the font *offset* on *y* in the config file

**Comment by davesque** [comment]
Nice, that fixed it.  Maybe the default value for y offset should be `0` in the example config file?

**Comment by basile-henry** [comment]
Well *-7* seems to work quite well with the default font. Or are you suggesting to hardcode an offset of *-7* on top of the specified offset to make the default offset *0* with the default font?

**Comment by davesque** [comment]
No I don't think a hardcoded offset would be correct.  I was just trying to point out that, out of the box, the default configuration on OS X if a bit confusing and will likely lead to a lot of questions likes this posted in the issues.  Maybe that could be mitigated by changing the default value.

**Comment by jwilm** [comment]
We just added support for installing a default configuration file on the first run. It's installing a slightly different config file for macOS where those offsets are zero and the font family is Menlo. I'll update the instructions in the README to reflect this.

**Comment by davesque** [comment]
Nice, sounds like a great solution.  I love this project, by the way.  I've often been frustrated by the overhead of using iTerm2 to run tmux.  This may very well become my new go-to terminal on OS X.
