### ISSUE TITLE
Faux scrolling breaks vim scrolling event capture

### ISSUE THREAD

**Issue by rjohnsondev** [jwilm/alacritty#982]
Which operating system does the issue occur on? Linux

If on linux, are you using X11 or Wayland? X11

https://github.com/jwilm/alacritty/commit/e0993587e7c994214aef83a6d50e70959ee05d96 on master disables mouse scrolling events in tmux / vim and inserts up / down arrow events.

I understand this is probably still under development; unfortunately I can't see a config option to disable faux scrolling at this point.

**Comment by kroogs** [comment]
I'm getting this as well on macOS 10.13.2. It also breaks scrollback with a mouse in tmux+zsh, improperly scrolling through command history instead.

**Comment by chrisduerr** [comment]
This has already been mentioned in #946 and there's an open PR to fix it #968.

**Comment by rjohnsondev** [comment]
Apologies for the duplicate, closing.
