### ISSUE TITLE
Scrolling behavior does not match vte3

### ISSUE THREAD

**Issue by PythonNut** [jwilm/alacritty#983]
My apologies in advanced if this issue is unclear. There are several things happening at once, and it's not clear to me how closely related they are, although I currently believe they may be solved at the same time.

I am using `linux` with `X11`.

**The Problem**

Scrolling seems to behave rather strangely for me. To explain what I mean, I will compare the behavior between `gnome-terminal` and `alacritty` and highlight the unexpected results.

  * `htop`
    - `alacritty` scrolls as if the arrow-keys were pressed.
    - `gnome-terminal` scrolls in a different way, which leaves the selected process stationary and scrolls the contents of the process pane.
  * `emacs`
    - **`alacritty` sends arrow key codes (according to <kbd>C-h</kbd> <kbd>k</kbd>)**
    - `gnome-terminal` sends something which `emacs` calls `<mouse-4>`/`<mouse-5>`. (I have yet to figure out what characters these correspond to.)
  * `less`
    - The behavior appears to be the same.
  * `tmux`
    - `tmux` is treated just like `htop` and `emacs`, therefore it receives arrow-key sequences (which are then handed to the program running inside `emacs`).
 
It's worth noting that in `htop` and `emacs`, `alacritty` seems to be sending the arrow keys with the direction inverted relative to my normal desktop scrolling. (I.e., the motion that would scroll down in a web-browser sends the up-arrow key in `alacritty`.)

Right now this difference in behavior is the cause for some ergonomic frustrations (i.e. not being able to distinguish scrolling from arrow keys for anything running inside `tmux`). Any help/explanations would be appreciated!

**Comment by enizor** [comment]
This issue is discussed on the faux-scrolling merged PR #946 and an opt-out option is suggested in #968.

**Comment by chrisduerr** [comment]
The PR doesn't only add the option to opt-out, but also disables it in applications that explicitly state that they have their own mouse support like `weechat` and many noted in this issue. Hopefully the behavior with #968 is more approprate even without having to disable faux scrollback completely.

**Comment by enizor** [comment]
I should have been more careful reading the #946 discussion! Thank you for your work!

**Comment by jwilm** [comment]
#968 landed; this should be resolved in master.
