### ISSUE TITLE
Library libwayland-egl.so could not be loaded.

### ISSUE THREAD

**Issue by grinapo** [jwilm/alacritty#984]
**Which operating system does the issue occur on?**
Linux

**If on linux, are you using X11 or Wayland?**
Same on both.

A fresh pull resulted this executable:
```
thread 'main' panicked at 'Library libwayland-egl.so could not be loaded.', src/libcore/option.rs:839:4
   7: std::sync::once::Once::call_once::{{closure}}
             at src/libcore/option.rs:302
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.9.10/src/egl.rs:32
             at src/libcore/ops/function.rs:223
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.2.11/src/lazy.rs:24
             at src/libstd/sync/once.rs:228
   8: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:308
   9: alacritty::display::Display::new
             at src/libstd/sync/once.rs:228
             at src/display.rs:140
  10: alacritty::run
```
Interestingly, there is egl installed, but apparently not what rust had on mind:
```
/usr/lib/x86_64-linux-gnu/libwayland-egl.so.1
/usr/lib/x86_64-linux-gnu/libwayland-egl.so.1.0.0

libwayland-egl1-mesa:amd64: /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1.0.0
```

**Comment by pklingem** [comment]
same issue here, happened somewhere between https://github.com/jwilm/alacritty/compare/6a1bed0...20aa45c

**Comment by jwilm** [comment]
@vberger any ideas? We updated to the latest Glutin/winit a week or so ago.

**Comment by pklingem** [comment]
due to:
```
> locate libwayland-egl.so                                         
/usr/lib64/libwayland-egl.so.1                             
/usr/lib64/libwayland-egl.so.1.0.0                         
/usr/lib64/qt5/plugins/wayland-graphics-integration-client/libwayland-egl.so                                           
/usr/lib64/qt5/plugins/wayland-graphics-integration-server/libwayland-egl.so
```
I assumed https://github.com/Smithay/wayland-rs/blob/e79172d693817e4da0331717d1b24a5ae5e41860/wayland-sys/src/egl.rs#L30 would fix the issue, which looks like it's in wayland-rs 0.12.5 and glutin 0.12.0.  I noticed that #974 includes glutin 0.12.0, so I rebased that against master and built it and I get a different error when running:

```
Alacritty encountered an unrecoverable error:

        Error creating GL context; Some of the requested attributes are not supported
```

I could be reading the dependency tree/commits wrong though.

**Comment by vberger** [comment]
This issue is indeed due to glutin 0.11 still depending on an old version of wayland-client. Upgrading to glutin 0.12 should fix it not finding the `wayland-egl.so`.

I don't know for the error when creating the GL context though.

**Comment by jwilm** [comment]
@vberger thanks! We just landed a patch that updates to 0.12 so this issue should be resolved. The GL context error sounds like a separate issue.

@pklingem would you mind opening a new issue for the GL context error?

**Comment by pklingem** [comment]
@jwilm thank you so much for the quick fix.  I'll mention the GL context error in #974

**Comment by jwilm** [comment]
@pklingem #974 is completely unrelated. Please open a new issue.
