### ISSUE TITLE
Auto copy

### ISSUE THREAD

**Issue by unphased** [jwilm/alacritty#988]
Feature request for a configuration option that enables selection to auto copy to clipboard. To mirror iTerm2 functionality (as well as a few other terminals i've used).

**Comment by unphased** [comment]
I now understand that Linux has two notions of copy buffer, and the selection buffer is already being auto populated there. 

But, OS X (and windows 😏) only have one system clipboard buffer and that is the "secondary" one. 

So, to clarify, I'd like the ability to configure Alacritty so it will (upon selection) auto populate system clipboard on these systems.

**Comment by chrisduerr** [comment]
I think this should not be too difficult, it's just a matter of implementing it. We already have functionality to copy on selection and functionality to copy to system clipboard (using keybind).

**Comment by cathay4t** [comment]
@unphased Can you try https://github.com/cathay4t/alacritty/tree/copy_selection on OSX?
Just add `save_to_clipboard: true` to `selection` section of `alacritty.yml`.

Thank you.

**Comment by hsiejkowski** [comment]
This works like a charm on OSX 10.13.6. Thank you @cathay4t !

**Comment by cathay4t** [comment]
PR #1571 submitted.

**Comment by unphased** [comment]
Thank you @cathay4t for your efforts! I've tested and commented in the PR.

**Comment by cathay4t** [comment]
@unphased Since PR got merged, could we close this issue now?

**Comment by chrisduerr** [comment]
Closing the issue as resolved.

**Comment by unphased** [comment]
Yep!! Thanks guys. I have also been able to test it and it works great.

**Comment by sansbrina** [comment]
I'm finding this doesn't work for me on OS X Mojave but works okay on my High Sierra machine with the same configuration. Commenting here in case anyone finds the same/is able to recreate.

**Comment by sansbrina** [comment]
Cool! Thanks for following up, I'll recheck my versions and rebuild.
