### ISSUE TITLE
Faux-Srollback not working on Macbook Pro 

### ISSUE THREAD

**Issue by sandersantema** [jwilm/alacritty#989]
Which operating system does the issue occur on? Mac OS

I can't seem to get faux-scrollback to work. It is working in chrisduerr's faux-scrollback [fork.](https://github.com/chrisduerr/alacritty/tree/faux-scrollback) Has this something to do with my touchpad, the code or my config? Config located [here](https://github.com/sandersantema/Alacritty-Config)

Any help would be greatly appreciated! 

And a big thanks to all the contributors! Alacritty makes the terminal a joy to use 😄

**Comment by chrisduerr** [comment]
Does it just not work at all? The current state in master should have all the features of my `faux-scrollback` branch and more. You can try increasing the `faux_scrollback_lines` setting in your configuration, maybe that will help?

**Comment by sandersantema** [comment]
Hey Crisduerr, 

Thanks for your answer. I've tried setting `faux_scrollback_lines` to 10 and 100 this still didn't work. I'll try it with a normal mouse later to see if that works, it might just be a problem with binding of the trackpad?

**Comment by chrisduerr** [comment]
I would assume that it's an issue with pixel-based updates instead of line-based updates. I'm not able to test this because afaik this is mainly a macbook pro thing, but I believe @jwilm has tested this?

It should definitely work with a normal mouse though.

**Comment by sandersantema** [comment]
I've tried a mouse, unfortunately this didn't work either. Possibly the mouse didn't work correctly but that seems unlikely to me. It might have something to do with keybinding the touchpad/ mouse on MacOS or the code for MacOS.

**Comment by sandersantema** [comment]
Do you have any idea what a mouse would normally be bound to with working scrolling in Alacritty? It might be possible to simulate this with [Karabiner](https://pqrs.org/osx/karabiner/) which would provide a temporary workaround. Karabiner is a keyboard/ touchpad customiser for MacOS.

**Comment by sandersantema** [comment]
I think I misunderstood what faux-scrollback is supposed to do. If I set faux-scrollback to zero scrolling doesn't work anywhere but when set to one it works in `man`. In @chrisduerr `faux-scrollback` branch scrolling works everywhere, and isn't affected by setting any value set in `faux-scrollback-lines`. Is this suspected behaviour?

**Comment by chrisduerr** [comment]
That's the intended behavior.

**Comment by sandersantema** [comment]
Ah thanks a lot for clearing that up for me. Scrollback (as in scrolling like you do in the browser) is planned to be implemented soon right?
