### ISSUE TITLE
Tmux prefix command (ctrl+space) unrecognized on OS X 10.11.6

### ISSUE THREAD

**Issue by davesque** [jwilm/alacritty#99]
I have my tmux prefix command bound to `ctrl+space`.  Alacritty doesn't seem to recognize this command or pass it through to tmux when I issue it on my keyboard.  Additionally, issuing `ctrl+space` appears to freeze alacritty and it won't accept any further input.

**Comment by terryma** [comment]
Ctrl-space sends ASCII NUL so you can map in with

`  - { key: Space,    mods: Control, chars: "\x00"                        }`

in your  `~/.alacritty.yml`

**Comment by davesque** [comment]
That fixed it!  However, why would issuing `ctrl+space` without a mapping in your config freeze alacritty?

**Comment by mondras** [comment]
Thanks for the fix @terryma !

Just adding that after doing so, Alacritty is not sending the command to the OS. e.g. I use Ctrl + Alt + Command + Space to switch keyboard input. So now it doesn't crash but the shortcut does not work.

**Comment by swemarx** [comment]
I've got my Spotlight bound to Opt+Command+Space and I've tried to enter that in
the configuration like so:

  - { key: Space, mods: Command|Option, chars: "\xa0" }

Entering that when Alacritty is in focus results in no Spotlight and the following characters written:

![screen shot 2017-06-30 at 08 43 24](https://user-images.githubusercontent.com/9530339/27724036-3a61b840-5d70-11e7-84ef-9dc8e6c507d3.png)

Btw, got 0xa0 from the app "Key Codes" which shows, well, keycodes from combos, looks like this:

![screen shot 2017-06-30 at 08 36 27](https://user-images.githubusercontent.com/9530339/27724092-7554ae08-5d70-11e7-94d7-2304aff5d5c6.png)

Any ideas?

**Comment by adamdawkins** [comment]
In a similar vein (I think), Ctrl + Cmd + Space opens the Emoji keyboard on my Mac. Works in iTerm, but not Alacritty. I use emojis with every git commit, so a pretty big deal for me 😬
