### ISSUE TITLE
Large spacing between characters with default config

### ISSUE THREAD

**Issue by leezu** [jwilm/alacritty#990]
After compiling alacritty on Gentoo Linux with X11 with default config there is a large spacing between characters, making alacritty unusable. Note that this is a device with HiDPI. I am not sure what could cause the issue, any help would be appreciated.

![image](https://user-images.githubusercontent.com/946903/34536066-66726262-f0c4-11e7-9069-8a0cfd230f28.png)

The following ebuild was used to build alacritty: https://github.com/leezu/leezu-overlay/blob/fb8b749d4b74bba44f4e68b3ff293c7e9eeb0436/x11-terms/alacritty/alacritty-9999.ebuild 
It was autogenerated by https://github.com/cardoe/cargo-ebuild

**Comment by chrisduerr** [comment]
This might be related to #902? There's a workaround in the comments, maybe that works for you.

**Comment by leezu** [comment]
Thanks @chrisduerr , it seems to be the same issue.
