### ISSUE TITLE
Error creating GL context; eglCreateWindowSurface failed

### ISSUE THREAD

**Issue by grinapo** [jwilm/alacritty#996]
**Which operating system does the issue occur on?**
Debian/sid

**If on linux, are you using X11 or Wayland?**
Both.

Actual pull results:
```
Alacritty encountered an unrecoverable error:

        Error creating GL context; eglCreateWindowSurface failed
```

**Comment by grinapo** [comment]
Caused possibly by b83a26ffe097ba9bf80b2801ba27737f6ccd90be

**Comment by chrisduerr** [comment]
Sounds like an issue with glutin 0.12.

**Comment by grinapo** [comment]
Weirdly enough a fresh pull of alacritty (and the dependencies of course) and a full rebuild of everything seems to have fixed the issue. It feels like some deps badly needed a rebuild, like someone have changed code but not its version number? :-o

**Comment by chrisduerr** [comment]
If a rebuild fixes this, there shouldn't be an issue, right?

**Comment by grinapo** [comment]
@chrisduerr Well, depends on what do you call an "issue". If building process isn't invariant lots of things may break in really unfunny ways. This may be completely a glutin issue, I cannot tell. Right now a clean build seems to work, so it's okay for me to close this; I hereby have documented that a **clean build may fix the issue**.

**Comment by grinapo** [comment]
Also glutin guys have closed the referenced issue, so I guess this can be closed unless someone see it again.
